### ISSUE TITLE
Magic energy Absorber does not work

### ISSUE THREAD

**Issue by florian96** [Blood-Asp/GT5-Unofficial#10]
I think the Magic energy absorber is not working. In gregTech 4 I have an enchanted item converted into energy. But in this version (5.08.08) he wants to have a liquid. I do not know how this will work.

**Comment by Blood-Asp** [comment]
The absorbing of entchantments is still missing but will be added soon.
Currently it only gets energy from a dragon egg on top or TC energized nodes close to it.

**Comment by florian96** [comment]
It gets energy from a dragon egg? i think that do only the GT 4 "dragon egg energy siphon".

**Comment by Blood-Asp** [comment]
I combined both generators.

**Comment by florian96** [comment]
ok Nice. fast answer.

**Comment by Blood-Asp** [comment]
Entchantment absorbtion and power from ender crystals added in 5.08.17
