### ISSUE TITLE
Processing Array does not output fluids if hatches were small

### ISSUE THREAD

**Issue by ShelfOwl** [Blood-Asp/GT5-Unofficial#100]
Centrifuging 60 Redstones yield 18kL of Mercury. I constructed Processing Array with LV Output Hatch (16kL capacity) and processing Redstones by 6 Centrifuge.
Therefore I should get 16kL of Mercury per process, but no Mercury obtained.

happen in GT 5.08.25

**Comment by pyure** [comment]
I noticed something similar.  With 16 centrifuges, I always get 18kL mercury.  Increasing the hatch size didn't actually seem to fix the problem either.

**Comment by Blood-Asp** [comment]
Fixed the zero output if no hatch can take the full fluid amount at once.
The allways 18kL mercury is, that the array only can accept one stack of materials at once. In case of redstone max 60 RS processed per cycle. Currently can't see how to change that without rewriting huge parts of the recipe system and i will not touch that. That is a rare and not really anything destroying issue, so i will let it be.
