### ISSUE TITLE
[5.09.29] Crash while MC loading

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#1000]
gregtech-5.09.29pre2.jar works fine
gregtech-5.09.29.jar - crashes
https://pastebin.com/j0L5iWzP

**Comment by Blood-Asp** [comment]
Maybe i used a class only in Java 8. Try updating java. I will see if i can change that so java 7 works again.

**Comment by MauveCloud** [comment]
From your crashlog:

> Java Version: 1.7.0_79, Oracle Corporation

Outdated Java.  Runs fine with Java 1.8.0_121.

**Comment by Blood-Asp** [comment]
12 seconds apart. :D

Also i just noticed we reached issue 1000...

**Comment by MauveCloud** [comment]
Yeah.  I saw your comment while I was checking - I noticed I was technically running with _101, which is itself a bit out of date, so I checked again with _121.  If Java 8 has been out long enough to have 121 updates, is it really worth continuing to support Java 7?  Java 8 first released March 18, 2014; The last update to Java 7 was April 14, 2015.

**Comment by Blood-Asp** [comment]
If there is really something in java 8 that i need, i will drop java 7 support directly. But for something small like that risking the trouble of dozens of bug reports is not worth it.

**Comment by SapientMC** [comment]
Actually lots of my modpack users have java7 (same as i am). So i hope you'll find some way to "change that so java 7 works again."
Or some message should be added (may be into first forum post) that GT v 2.09.29 and later works only on java8.

**Comment by draknyte1** [comment]
Do you want security issues?
J8 is standard and we as devs have no reason to support anything less outside of an enterprise environment.

**Comment by Blood-Asp** [comment]
long fixed...
