### ISSUE TITLE
Laser Engraver ocasionally not outputs in cleanroom

### ISSUE THREAD

**Issue by Valps** [Blood-Asp/GT5-Unofficial#1002]
After open the reinforced door for a few seconds, closes, and reactivates the cleanroom controller, the wafer will be consumed, but does not return the raw circuit

If use another type of doped wafer, or change lens, occasionally the bug disapperars

GT: 5.09.29

**Comment by Blood-Asp** [comment]
Thats the way the cleanroom works. It takes a few minutes to completely clean the inside of the room. While it is not clean, there is a chance to fail. Currently the only way to see the cleanness is to use the portable scanner on the cleanroom controller.
