### ISSUE TITLE
[1.10.2] Crash when loading.

### ISSUE THREAD

**Issue by Lgk2** [Blood-Asp/GT5-Unofficial#1004]
Versions:
Minecraft: 1.10.2
Forge: 2254
Advanced Solar Panels: 4.0.4
Gravitation Suite 3.0.1
Gregtech: 5.10.40
IC2: 2.6.188-ex110
Java: V8 Update 121

Ic2 is actually the mod that the crash log mentions but it did work before I added gregtech to the modpack.

GregTech Log
https://gist.github.com/Lgk2/4363d0c202dc5e9a12ff96ab1e275d2d

Fml Client Latest Log
https://gist.github.com/Lgk2/17d7afc3d9d03eb24f4c053fd4b2e703

**Comment by Dragon2488** [comment]
Can't see anything because of trace and debug in log. Disable them first. And where have you downloaded it? You should build latest gt from reppo.

**Comment by Lgk2** [comment]
I downloaded the latest that curse has but I can try with the latest on repo. Here's the crash report (not on the same launch though but it's the same error).
https://gist.github.com/Lgk2/20dab2745c0d26727d4b6385aadb791b

**Comment by Dragon2488** [comment]
Curse build is ancient.
Same for jar in build/libs of reppo.
Rebuild with latest, it should work.

**Comment by Lgk2** [comment]
Huh I checked https://github.com/Blood-Asp/GT5-Unofficial/tree/1.10.2/build/libs 
and they have the same version here. The latest one released on curse was released 2 days ago "5.10.40".
You can check the curse page here: 
https://mods.curse.com/mc-mods/minecraft/251053-gregtech-5-unofficial

**Comment by Lgk2** [comment]
Umm can you link me where i download latest?

**Comment by Lgk2** [comment]
The crash didn't occur in gregtech 5.10.41 so the issue is solved!
