### ISSUE TITLE
Feature Request: More Replicator Recipes

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [Blood-Asp/GT5-Unofficial#1005]
This list may not be perfect but I think all of the elements which cannot currently be made in the replicator even with GT++ installed are: Neon, Germanium, Selenium, Bromine, Krypton, Zirconium, Technetium, Ruthenium, Rhodium, Iodine, Xenon, Cerium, Hafnium, Rhenium, Thallium, Polonium, Astatine, Francium, Radium, Actinium, Protactinium, Neptunium, Curium, Berkelium, Californium, Einsteinium, Fermium, Mendelevium, Nobelium, Lawrencium, Duranium, Tritanium, Naquadah, Naquadah Enriched, Naquadria

Most of these are probably useless, and some only useful with Gt++, but it would probably be useful to have Germanium, Selenium, Zirconium etc. and it's ironic not to be able to replicate Duranium and Tritanium

**Comment by draknyte1** [comment]
This is more applicable for the Gregtech++ issue tracker considering I add those elements. Gregtech doesn't have zirconium (for example) in any way, shape or form. Even elements.Java doesn't contain it.
