### ISSUE TITLE
Minor Enhancement: Fluid Naquadah Reactor Accept Piped-In Fluids

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [Blood-Asp/GT5-Unofficial#1006]
Currently the Naquadah Reactor Mk III only accepts molten enriched Naquadah if it's in IC2 or Gregtech cells. Why not let it accept fuel from pipes and other mods' fluid conduits?

**Comment by Blood-Asp** [comment]
It is not that i do not allow pumping in. I just have no idea why it does not work...
