### ISSUE TITLE
[5.09.29]Processing Array do not check the cleanroom requirement

### ISSUE THREAD

**Issue by Antifluxfield** [Blood-Asp/GT5-Unofficial#1009]
As well as the low-gravity requiring recipes.

**Comment by Technus** [comment]
Hmm looks like issue 1009 from wrong repo got linked

https://github.com/GTNewHorizons/NewHorizons/issues/1009

**Comment by Technus** [comment]
but i think i actually worked on that case of proc arrays

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/1ddc91afc8aa2615241105c331e6fe145a7e8a6f

**Comment by Technus** [comment]
I assumed that the proc array is hermetic since it is quite high tier. (Was to lazy to implement the multiblock support for cleanroom)

**Comment by Blood-Asp** [comment]
There are many things i sometimes find in forks where i wonder why they never made it into the main GT repo.

Bugfixes and stuff like that. Would really help if i was at last told it was done somewhere...

**Comment by Technus** [comment]
Feel free to track our fork like i track the main repo. 
And yes i could be more helpful but i am lazy af.

I will try to give notes about worthy commits.

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/467e6ba02286fa97b2cbd407158227958756032b
