### ISSUE TITLE
IC2 Replicator

### ISSUE THREAD

**Issue by ShelfOwl** [Blood-Asp/GT5-Unofficial#101]
In GT 5.08.25, IC2 Replicator is able to craft. It seems to me not suit to GT machines because it could produce minerals using less UU-Matter, particularly in make Diamond, Redstone and Uranium.
If you felt it too powerful too, or if it is no bother, please disable it in general (and it should be configurable).

**Comment by Blood-Asp** [comment]
Disabled it by default in 5.08.26
