### ISSUE TITLE
[5.09.29] Colors cannot seperate item pipes and machines

### ISSUE THREAD

**Issue by Antifluxfield** [Blood-Asp/GT5-Unofficial#1010]
As what descripted in title, I colored a machine and its adjacent item pipe with different colors, but they only seperated visually. The items pass through the item pipe still go into the the machine.

**Comment by Blood-Asp** [comment]
If i remember right that was intended.
It is just too long that i do not remember the reason anymore. Just use covers like plates or foils to keep them from connecting instead.
