### ISSUE TITLE
Please mention Gregtech addons on your GitHub page / in your thread on the IC forums

### ISSUE THREAD

**Issue by JohannesGaessler** [Blood-Asp/GT5-Unofficial#1024]
I'm a big fan of Gregtech but only recently have I discovered through discord that there is a mod called Gregtech++ which adds some further interesting content.
However, generally I'm not very interested in chatting with strangers and had I not decided to participate in development I might not have discovered the mod at all.
As such, please mention any relevant Gregtech addons on your Github Page or in your thread on the IC forums.

**Comment by draknyte1** [comment]
As the dev of Gregtech++ this would be appreciated, although not a necessary addition. @Blood-asp does as he wants.

**Comment by Bogdan-G** [comment]
in ic2 forum, threads gt addons find?

**Comment by JohannesGaessler** [comment]
Well, sure, if you get the idea that there might be Gregtech Addons finding them is not very hard.
But in my case I simply didn't get that particular idea which is why I would like a short mention.

**Comment by Blood-Asp** [comment]
Adding links to Addons and maybe the main modpacks sounds like a good idea.

Addons: 
GT++
GTTweaker
Tinkers Gregworks
GalacticGreg(not needed anymore)

Modpacks: 
Beyond Reality
Infitech 2
GT New Horizons

Anything else i did forget?
Maybe texture packs or translations too?

**Comment by SapientMC** [comment]
I can add to this list my modpack (Ideal Industrial Assembly).
Latest version are always here https://yadi.sk/d/m0vmhfXyyBE7G
Some textures https://yadi.sk/d/BaGmDjuEnbfbB

**Comment by Bogdan-G** [comment]
Was a translation into Russian. Maybe there were addons to the gregtech, but i do not especially remember their names. There was a texture pack of at least(as minimum) one on 32x.

**Comment by Technus** [comment]
WIP addon

https://github.com/Technus/TecTech

**Comment by Blood-Asp** [comment]
Done
