### ISSUE TITLE
Localization strings missing for bee breeding.

### ISSUE THREAD

**Issue by netmc** [Blood-Asp/GT5-Unofficial#1033]
The NEI tooltips for bee breeding requirements list for chome, maganese, naquidah, tungsten, platinum, uranium, iridium and plutonium all list "requires gt.blockname.x.x.name as a foundation."

**Comment by Blood-Asp** [comment]
compatibility issue beween GT and forestry. i will not rewrite the whole nameing system of Gt for this.
