### ISSUE TITLE
Modtweaker does not work with recipes GT machines.This is bug or not?

### ISSUE THREAD

**Issue by Pilad** [Blood-Asp/GT5-Unofficial#1034]
If you add recipes through a modtweaker for a compressor or an extractor (maybe some other machines also do not work), then the recipe only works in IC2. In GT machines do not want to work.

**Comment by Dragon2488** [comment]
Use GTTweaker.

**Comment by Blood-Asp** [comment]
Actually reading this i think that is unreleated to GTTweaker. The IC2 machine recipes get moved to the GT recipe lists internally. Once in postload and another try a few ticks after loadint to get the later added tweaked recipes. I guess something fails there.

But to make sure: GT for 1.10.2 or still 1.7.10? And do they really not work, or just not show in NEI or JEI (also interesting what is used)?

**Comment by Techlone** [comment]
GTTweaker doesn't contain methods for this. My bad.
Also about GT 5.10. How to get just added recipe? Maybe chage the api for IRecipeAdder that its methods return Recipe object? I guess I can add a normal (more or less) JEI support if IRecipeAdder's methods will be return not bool but Recipe.

**Comment by mura3277** [comment]
@Techlone Maybe add a separate issue for this request?

**Comment by Techlone** [comment]
@Muramasa- GTTweaker 1.7.10 uses the GT api for this machines and it's already released
Also devs of GT 5.10 want to add the minetweaker support into GT
I think this issue is settled

**Comment by Technus** [comment]
Have you tried moving recipes at the 
onServerAboutToStart event?

**Comment by Techlone** [comment]
@Technus Minetweaker executes recepies not GTT. It just uses the class registration via the MT api.
