### ISSUE TITLE
Rocket Fuel

### ISSUE THREAD

**Issue by sergeygta4pony** [Blood-Asp/GT5-Unofficial#1035]
If it's not difficult for you to answer. Is the introduction of GregTech - 5.6 propellant from the components 1,1-Dimethylhydrazine (Heptyl) and Diazotetrafluoride (Amil) planned? In the description, the content of the components is not too complex. This is very important when adding to GregTech, mod galacticraft.
ATP for understanding.

**Comment by codewarrior0** [comment]
Rocket Fuel (the EnderIO variety) can be made from Nitrogen, Oxygen, and Water, but the process is too simple and if it is meant to represent a Tetroxide-Hydrazine mixture (which would spontaneously ignite) then it is not stoichiometric either.

Another Galacticraft-compatible rocket fuel is made by mixing Light Fuel and Heavy Fuel in a mixer - I think it's just called "Diesel" and is treated identically to BuildCraft Fuel.

**Comment by bHXDgiuMa5yLHyC8** [comment]
I too think it would be cool to be able to make UDMH with Gregtech.

**Comment by Blood-Asp** [comment]
On my side not more additions are planned. PRs are still accepted.

But just to make the issue better: Please add more informations about how these are made.
IRL and proposed GT recipes. 
How shoud these get used by GT? Fuel values?

**Comment by nictrace** [comment]
I think, Galacticraft fuel is too cheap - oil conversion rate is 1:1
Real manned rockets uses kerosene (and a liquid oxygen too) 
Maybe GT can disable GC refinery recipe and change fuel fo diesel from dist.tower?

**Comment by Blood-Asp** [comment]
If it is about how the different fuels are used by GC, thats not something GT can change. We can only add new alternatives, not disable existing ones.
