### ISSUE TITLE
[5.09.29] Battery Buffer Tooltips

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#1036]
The inscription about the number of slots was missing in tooltips for all BatBuffers.

**Comment by JohannesGaessler** [comment]
From what I can tell this is happening specifically on the branch I made where I expanded tooltips.

**Comment by Techlone** [comment]
@JohannesGaessler yep I just found it
@SapientMC close this issue

**Comment by JohannesGaessler** [comment]
Damn, I just found the bug, too.
