### ISSUE TITLE
close it achievement 

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#1037]
doesnt activate when you pull the shutters out of the assembler, only when you throw them on the ground and pick them up

**Comment by draknyte1** [comment]
That's the same as any achievement though @Bear989.
Get JR to mine an ore you've never found and chest it, take it out and no achievement.
Drop it and recollect it, then boom, achievement.

Would require an overhaul for the GT achievement system to fix.

Funnily though, crafting grid results seem to work fine.

**Comment by bear989** [comment]
well greg managed to add the iron cooking achievement to the steam and electric furnaces fine, and even does multiple achievements if you missed one, I.E. pickaxe will kick in the inventory, getting wood, and benchmarking. That is why I thought it should be able to click in the achievement when the shutter is made.

**Comment by Blood-Asp** [comment]
In theory it would be possible to check on every machine output if they trigger an achievement for the player who placed the machine. I decided against it since the huge amount of produced items would produce noticable lag. Only the fusion reactor is an execption here as i expect the amount of running, lag producing reactors to stay reasonable low.

**Comment by OvermindDL1** [comment]
You could do it on when the player takes items out of the output, would be a decent work-around I'd think?  Or on when an item enters their inventory?

**Comment by Blood-Asp** [comment]
Is there a proper event for that? I do not know that. Only the one for pickup from ground that i currently use.

**Comment by OvermindDL1** [comment]
> Is there a proper event for that? I do not know that. Only the one for pickup from ground that i currently use.

For when the player takes it out of the output slot, no event, you'd have to encode that on your machines.

For when entering their inventory, not 'directly', but easy to emulate by an onTick event and just, oh, testing one item in their inventory every tick or so to see if it fulfills a conditional (like unification already does, you might even be able to tie it in to the auto-unification system actually...).

**Comment by Blood-Asp** [comment]
yes, auto unification would be the best alternative i guess.
Taking it out of the inventory slot would only work when taking it directly from GT machines, but past LV tier 90% autooutput their stuff into chests or similliar so it would not work out.

**Comment by bear989** [comment]
but this is specifically about shutters, those are usually before
autocrafting. how does the iron achiements in steam and lv furnaces get
activated? those kick in before you ever touch the machine.
