### ISSUE TITLE
[5.09.29] Missing fluid regulator recipes

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#1039]
After adding new circuits, I think it's worth adding an alternative recipe for a fluid regulator with them.

Upd
Actually, they are not missing, but simply do not appear in NEI.

**Comment by Technus** [comment]
If the recipes work - they are not registered properly for NEI?
If the recipes dont work but are in code - probably some null material/fluid pointer is in them.

**Comment by SapientMC** [comment]
Seems like "they are not registered properly for NEI"

**Comment by Technus** [comment]
We have some similar issue with Argon gas cell, the centrifuge recipes does not show when you look for the argon gas cell recipe, but does show when you look trough the uses of liquid air cells (don't really remember the thing).

**Comment by Blood-Asp** [comment]
I do add them oredict: https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java#L406-L410
Also just tested ingame, they really all work. No idea why NEI does not show them...
