### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by KuroNeko87** [Blood-Asp/GT5-Unofficial#104]
Add GT equivalent for the following metallurgy metals.

ingotIgnatius
ingotVyroxeres
ingotCeruclase
ingotKalendrite
ingotInolashite
ingotSanguinite
ingotTartarite
ingotHepatizon
ingotAngmallen
ingotEximite
ingotPrometheum
ingotInfucolium
ingotOureclase
ingotCarmot
ingotHaderoth
ingotOrichalcum
ingotCelenegil
ingotAltarus

These are all included with GT6, and while some of the other metallurgy metals are working with gregtech, as a modpack maker, I like consistency. While not having these metals workable into plates, the tools and weapons made out of them become cheaper to craft then the others, possibly breaking balance.

**Comment by Blood-Asp** [comment]
can you list fitting damage/durability values, and maybe even RGB colors for all materials? Activating the materials is easy, finding out the right values would take me a lot time.

**Comment by KuroNeko87** [comment]
I'll start working on it right away

**Comment by KuroNeko87** [comment]
I tried to find out how the values were assigned to no avail, so i just took screenshots of the values for hammers in gregtech 6.
http://imgur.com/a/t1Fi6

these are all metallurgy metals. Currently working in the RGB data. I will keep updating it until all are complete: https://gist.github.com/KuroNeko87/5cd80cda254038bb7398

**Comment by Blood-Asp** [comment]
All added. Will be in 5.08.26
