### ISSUE TITLE
[5.09.29] Electric Blast Furnace won't process silicon

### ISSUE THREAD

**Issue by woggy** [Blood-Asp/GT5-Unofficial#1044]
I've got an EBF set up, running off a single MV Energy Hatch and with Cupronickel coils.  Despite NEI claiming that I should be good to make Silicon Ingots with this setup, it never actually starts trying to process - the materials (32x Silicon Dust, 1x tiny pile Gallium Dust, item numbers and metadata match the NEI recipe) just sit in the input hatch forever. (and yes, I checked that processing is enabled with a Soft Hammer).

The setup works perfectly for Steel and Aluminium manufacture, so I'm at a loss.

**Comment by codewarrior0** [comment]
I saw this too, and found out the EBF *sometimes* works if you take the materials out and put them back in the hatch in a different order.

**Comment by woggy** [comment]
I've tried reordering to no success. :(

**Comment by Techlone** [comment]
Does the EBF have an input hatch with something fluid? Or cells (empty or full) in this hatch?

**Comment by woggy** [comment]
I did have a fluid hatch with some Oxygen in it for steel processing. Took the cells and the fluid out and things are working now...

Bit baffled as to why it would matter for this and not for Aluminium (which worked fine with the O2 lurking in the hatch), but it is working, at least.

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java#L683

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java#L711

This should be commented out to prevent fluid hatches from exposing items in them.

This is one of the poorly documented features that fluid hatches are also item hatches, much confusion.

**Comment by codewarrior0** [comment]
Is that the same code that causes the output hatches of a distillation tower to receive hydrated coal dusts if the output bus is full?

**Comment by Technus** [comment]
yes

**Comment by Technus** [comment]
Other soulution would be to screwdrive the hatches to allow/disallow that behaviour, and obv. document it.

I will try to implement that in GTNH branch of GT5u then in can be carried over here.
