### ISSUE TITLE
Crash cause a tin wire. GT 5.10.41

### ISSUE THREAD

**Issue by Gohu29** [Blood-Asp/GT5-Unofficial#1045]
Crash happen randomly.

GT version: gregtech-5.10.41
SpongeAPI: 5.2.0-SNAPSHOT-a26c654
SpongeForge: 1.10.2-2281-5.2.0-BETA-2303
Minecraft Forge: 12.18.3.2254

Crash Repport: https://pastebin.com/vZvKaR6K

**Comment by Blood-Asp** [comment]
sponge is not supported and in the crash report
