### ISSUE TITLE
Ignore charge of items for Assembly Line recipes

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1046]
Assembly Line recipe for some armor pieces require fully discharged items, f.e. GraviChestPlate requires fully discharged QuantumSuit, which is a problem because this ingredient is expensive enough for the player to use one they currently wear, which is fully charged in most cases. Discharging this armor piece takes many hours. If the Assembly Line supported ingredients with any charge, players could be able to perform this recipe without spending lots of time discharging this armor piece.

**Comment by Technus** [comment]
~~best to use the wildcard value for damage~~

**Comment by Technus** [comment]
Correction, this produces a ton of duplicate recipes. (Invocvienient when techlone will port the recipe gui thing) So best to use the meta data for fully charged items.

**Comment by Blood-Asp** [comment]
Did a little test and it seems to work fine for me. The armor recipes all ahve wildcards from the start and they are correctly used as far i can see.
