### ISSUE TITLE
Infinite water source

### ISSUE THREAD

**Issue by GreenCat1988** [Blood-Asp/GT5-Unofficial#1047]
As I think, gregtech needs its own infinite water source. Installing EnderIO in modpacks only for its water reservoirs a little stupid. This could be a some block, working only being connected to bedrock. Drilling a water spring could be interesting in some way. A little...

**Comment by draknyte1** [comment]
So many other mods adds infinite water sources, is it really worth it?..

**Comment by Blood-Asp** [comment]
Even more, GT has its own infinite sources. Just not in a single block but a few machines more.
