### ISSUE TITLE
ChunkData code overhaul

### ISSUE THREAD

**Issue by Technus** [Blood-Asp/GT5-Unofficial#1049]
Related commits to cherry:
https://github.com/GTNewHorizons/GT5-Unofficial/commit/c12e474c23ca02fb3479312850f6ae07e623d8b9 - Oldest one

https://github.com/GTNewHorizons/GT5-Unofficial/commit/80bf3fd2e66db794a7fc2678b080cdcf548ebc51 - This one is probably just me cleaning up our code.

https://github.com/GTNewHorizons/GT5-Unofficial/commit/8e0e51673f1148fdbbac13e03b4becaa1ac88ad5

https://github.com/GTNewHorizons/GT5-Unofficial/commit/c855faa14e4c2c30179ca1cfc410b7ab70964590

https://github.com/GTNewHorizons/GT5-Unofficial/commit/7bd71fe6c236fbc337255bdde08e39aa71971a95

https://github.com/GTNewHorizons/GT5-Unofficial/commit/2515502ae77fc9546156d642968754c855ba3880

Rest is rather simple to fix if i didn't catched all the commits.

**Comment by Technus** [comment]
The oil extraction speed/consumption speed values are to be set as u wish, but i prefer them to differ.

**Comment by Blood-Asp** [comment]
also merged
