### ISSUE TITLE
Iron door -1

### ISSUE THREAD

**Issue by Alexandres668** [Blood-Asp/GT5-Unofficial#105]
Hello, 

First of all, sorry for bad english,
I have bug on my custom modpack, the craft of the shutter module requires an bugged iron door with id -1 : 
![-1](https://cloud.githubusercontent.com/assets/8899647/8894554/2ee8f266-33bb-11e5-81a2-9ee8acaa85f1.png)
I have tried to erase the gregtech's config, searched on the internet bug i haven't seen anything about that. I have also tried to take the config of an other modpack with gregtech ( Beyond Reality ) and it didn't help.

Thank you in advance for your answer.

**Comment by Blood-Asp** [comment]
Malisis doors is replacing the iron door. There is a option in it's config to disable that change.
