### ISSUE TITLE
basalt & marble dont allow prospecting with a hammer 

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#1050]
tested on the granites and it does work on them same as stone. also marble isnt in the same ore dict for chisel. marble or blockMarble

**Comment by GreenCat1988** [comment]
More of that. Marble and basalt are blast-proof like granite.

**Comment by Blood-Asp** [comment]
Tested it and "somehow" worked with basalt, so it is not completely broken. There is something really strange about prospecting trough...

**Comment by bear989** [comment]
it seems to work better in GT6 then it ever did in GT5, maybe look at what
greg changed?
