### ISSUE TITLE
[5.09.29] Auto maintenance hatch causes controller blocks to glitch

### ISSUE THREAD

**Issue by Georggi** [Blood-Asp/GT5-Unofficial#1053]
![2017-05-12_08 39 21](https://cloud.githubusercontent.com/assets/6255615/25983783/81621d04-36ef-11e7-8ed9-8f33410448b9.png)
![2017-05-12_08 42 06](https://cloud.githubusercontent.com/assets/6255615/25983784/8166a23e-36ef-11e7-9791-beb7da78b174.png)
Might be some issue with it on dedicated server only, but I doubt so.

After receiving a problem multiblock's controllers become this, while still working and possibly producing energy(for turbine) they are not consuming resources(plasma, cells). Auto maintenance hatch did not consume any repair materials and some machines, like arrays still have full efficiency, while turbines do not.

P.s. Good job testing it....

**Comment by Georggi** [comment]
Will put it here just in case, there is wrong import, got this spamming in GregTech.log:
java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_Hatch_Maintenance.autoMaintainance(GT_MetaTileEntity_Hatch_Maintenance.java:118)

Also would ask to change allowPull\PutStack, methods so auto maintenance hatch can actually work autonomously.

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/blob/mergeGTNH/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java

https://github.com/GTNewHorizons/GT5-Unofficial/blob/mergeGTNH/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Hatch_Maintenance.java

Our changed code works, SMP tested.

**Comment by Technus** [comment]
> Also would ask to change allowPull\PutStack, methods so auto maintenance hatch can actually work autonomously. 

 - The maintenance requires players to interact, even if not quite often, imo it should stay like it is.

**Comment by Georggi** [comment]
@Technus I see why it works, although I was just making commit to fix it. Still would argue, that for IV tier at least allowing to automate it should be a thing. This is mainly for servers anyways, as in SP it doesn't come up that often and I would guess there are other limiting factors, for instance chunk loading, if you are using world anchors you still need to thin about fuel for them.
