### ISSUE TITLE
Pointless code in lightning rod fix.

### ISSUE THREAD

**Issue by Technus** [Blood-Asp/GT5-Unofficial#1054]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/7060cdc2a8ccd9f32cef88cc4ae6559def40e5af

Can you like not do it that way it was? This commit actually makes it work.

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/1c76cb698091b1f462c0ce99e773f2c79522d86f

Also this forces up facing, and makes it look better i guess?

**Comment by Technus** [comment]
![image](https://cloud.githubusercontent.com/assets/4737429/26024158/69c77f08-37cc-11e7-8938-91718682f479.png)

**Comment by Blood-Asp** [comment]
Took me a while to find out how to cherry-pick from other forks... done

**Comment by Technus** [comment]
Just for future reference @Blood-Asp  i use SourceTree, makes life ez game.
