### ISSUE TITLE
Building materials

### ISSUE THREAD

**Issue by GreenCat1988** [Blood-Asp/GT5-Unofficial#1055]
Is it possible to add slabs and stairs, made of granite, basalt or marble?
Another question about metal frame boxes. Their tooltip says that all kinds of them could be covered or foamed. Covering works fine. But foaming has no sense. No recipes in NEI, foam doesn't interract with them in the world.
Solid metal doors, lamps? In any case, a little bit of decoration is needed. Almost all decorative mods are out of industrial theme. Adding other heavy industrial mods only for their little features has no sense too.

**Comment by leagris** [comment]
Cannot be foamed in-world, but inside chemical bath with wet concrete if I remember.
Makes me think, Gregtech wet concrete should be compatible and interchangeable with IC2 Foam. Also the IC2 Foam Sprayer should be in-world compatible with Gregtech Frames to fill with concrete for making IC2 Reinforced stone blocks.

And the ultimate compatibility would be allowing:
- IC2 foam on any GT pipe, wire, cable.
- IC2 Obscurator changing face texture of foamed GT pipe, wire, cable
- Any dyes tinting foamed GT pipe, wire, cable
- And fix this horrible lighting missing ambient occlusion on GT Tile blocks.

**Comment by Technus** [comment]
very much so indeed

**Comment by Blood-Asp** [comment]
For all that decoration stuff we have Carpenters blocks. 

That IC2 foam stuff would need to rewrite most of the GT rendering and not touching that. No idea how to fix the lighting too...
