### ISSUE TITLE
Modular Armor Weirdness [5.09.29]

### ISSUE THREAD

**Issue by woggy** [Blood-Asp/GT5-Unofficial#1056]
I was exploring in my world, and noticed that suddenly I was moving Very Slowly.  I opened up my Basic Modular Armor breastplate, and saw this Very Strange number:

![chestplate](https://cloud.githubusercontent.com/assets/3821254/26029553/c86021fa-37f4-11e7-9e39-7c5cd2b0ec68.jpg)

I was fighting skeletons, and originally had a full set of armor (five Steel plates in each piece). Sometime in the fighting the hat and boots broke, if that matters (i don't see why it would, but?). The pants I still have, and they have a *different* (but still six-digit) number listed for Total Weight.

This seems like a bug to me, but maybe I'm missing something about the way the Armor works.

**Comment by woggy** [comment]
Booted up the world this morning and it's resolved itself. Still weird, but...

**Comment by woggy** [comment]
...or not. Apparently the Total Weight number is increasing by walking around in the armor - the longer I walk, the bigger the number gets.

**Comment by YuRaNnNzZZ** [comment]
Can confirm. Total weight increases if you're wearing modular armor boots without wearing full set of the armor. If you take off the boots or put on the full set, you can see that weight is normal and doesn't increase itself.
EDIT: It appears that weight increases only without helmet, no matter what piece of armor you wearing.

**Comment by Blood-Asp** [comment]
should be fixed in .30 if still happens i will reopen. but you need a new armor to be sure when testing.
