### ISSUE TITLE
Impossible to get wrought iron nugget

### ISSUE THREAD

**Issue by GreenCat1988** [Blood-Asp/GT5-Unofficial#1057]
I have found duplicated smelting recipe for furnace with two different results. Iron nugget=> wrought iron nugget or steel nugget. All time I get steel nuggets. And because of this I can't craft LV machine hull for my first steam turbine. My custom modpack has IC2exp, gregtech, railcraft, forestry, extra utilities, AE2+Extra cells only. All of them with default settings. I have used them before gregtech 5.09.29 and had no problem with nuggets.

**Comment by bear989** [comment]
the steel nugget recipe is from Railcraft and can be turned off in the config, i have never ran into an instance that it was still active with GT.

**Comment by GreenCat1988** [comment]
Thank You! I'll try this today. Is it possible make automatic disabling of this railcraft config?

**Comment by draknyte1** [comment]
It's not gregtech's job to configure other mods in a mod pack.. albeit possible, it's not probable to happen.

**Comment by GreenCat1988** [comment]
At last, I have found this fucking config. Problem is that railcraft has its own type of iron(not vanilla!). As a result, smelted vanilla iron nuggets transform into railcraft iron nuggets by ore dictionary, wich smelt into steel nuggets. All in one time. Configuration file items.cfg has two last rows: ingots, nuggets. No description at all. Disable both and got to heaven. 
Added this just for future generations.

**Comment by MauveCloud** [comment]
"vanilla iron nuggets"?  Those only exist in MC 1.11.1 and beyond (and have the bulge to the left with default textures, unlike most mod-based iron nuggets, which have the bulge at the top).  With older Minecraft versions, you have iron nuggets from Railcraft or GT (and several other mods as well if installed).  With most default settings, smelting iron nuggets will get me wrought iron according to NEI - I think the iron nuggets to steel nuggets recipe is only enabled when the RC blast furnace is disabled in the RC config (or in the MC 1.10.2 build of RC, which iirc hasn't re-implemented the blast furnace yet, but if you're using extra cells, I'm pretty sure you're on 1.7.10)
