### ISSUE TITLE
crop inconsistencies

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#1064]
most crops will allow ore blocks from Gregtech under them, but the ferru doesnt recognize GT iron ore, and bauxia doesnt recognize bauxite ore either. will test others as I get them.

**Comment by MauveCloud** [comment]
Ferru is from IC2, and requires a block below that is ore-dictionaried as "oreIron" or "blockIron".  GT ores, at least in 5.08 and 5.09, are tile entities, so the IC2 metal-producing crops don't recognize them.  Bauxia is just confusion from the naming - it requires aluminium ore or a block of aluminium below, rather than bauxite ore.

You can look at https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/loaders/postload/GT_CropLoader.java to see which other crops need specific materials - look after each array of strings for a "Materials"; if it's there, that's the material needed under the crop.  Two others I notice with potential for confusion: Pyrolusium requires manganese rather than pyrolusite ore, and Scheelinium requires tungsten rather than scheelite ore.

**Comment by bear989** [comment]
I dont believe it is confusing, I think it is inconsistent. bauxite and aluminum ores are found in the same vein and both should be possible as it is called bauxia, can be used to enhance bauxite, and contains as it's largest solid mineral aluminum. as for the Ferru crop, it being IC2 rather than GT doesnt as I see it matter, GT5 changes many many things in IC2 so why not add GT iron ore as possible? also for your examples, pyrolusite and sheelite should be usable ores under them, you shouldnt have to be up to EV and able to process tungsten before you can start breeding that crop.

**Comment by draknyte1** [comment]
It's called technology gating. 
Don't want people getting tungsten too early.

**Comment by bear989** [comment]
but you cant get tungsten from it without processing the sheelite so point
invalid. you dont get tungsten out of it, you use it to make sheelite or
enhance sheelite you already have.

**Comment by MauveCloud** [comment]
> as for the Ferru crop, it being IC2 rather than GT doesnt as I see it matter, GT5 changes many many things in IC2 so why not add GT iron ore as possible?

That would be a deeper change, requiring a GT version of the Ferru crop, and removing the IC2 Ferru crop from the crop registry could corrupt existing games.

> but you cant get tungsten from it without processing the sheelite so point invalid. you dont get tungsten out of it, you use it to make sheelite or enhance sheelite you already have.

Actually, if nerfCrops is set to false, Scheelinium Leaf can be processed in an LV extractor to get tungsten (albeit only tiny dust, and as a high-tier crop, Scheelinium takes a while to grow even with a high "growth" stat).

**Comment by bear989** [comment]
I didnt suggest adding a diffrent ferru, just editting the crop to take GT iron ore, I am not a coder but since GT uses IC2 classes, and greg has changed many things in IC2 it should be possible. and even if you get tiny tungsten dust you still need to cook it,

**Comment by MauveCloud** [comment]
> I didnt suggest adding a diffrent ferru, just editting the crop to take GT iron ore, I am not a coder but since GT uses IC2 classes, and greg has changed many things in IC2 it should be possible.

Changing the drops for Ferru (from tiny iron dust to ferru leaves) was easy, because that's a public field.  Changing the check for blocks below would be much more complicated, and I'm not even sure how to explain to a non-coder how complicated it would be.

**Comment by draknyte1** [comment]
Fuck it. 
ASM. 

Let me look through my IC2 source and post a reply in 8hr when I'm back home.

**Comment by Techlone** [comment]
Also why should we use IC2 crops? GT duplicates several crops from IC2 for example for copper and tin.
I think it's better to continue this behavior for all crops that need an ore block below and delete IC2 crops from the global list to prevent their obtaining through a breeding.

**Comment by Techlone** [comment]
Well the list is `IC2Crops.instance.cropMap` and we can get it with call `GT_Utility.getField`
This list has type `Map<String, Map<String, CropCard>>`. The first string indexer is a mod id; the second is a crop name. I guess if we remove the ferru and other 'bad' crops from IC2 submap (idk the id for IC2) then players will not be able to obtain their through a breeding.

**Comment by MauveCloud** [comment]
> Also why should we use IC2 crops? GT duplicates several crops from IC2 for example for copper and tin.

Coppon, Tine, Plumbilia, and Argentia existed in GT before IC2 added Cyprium, Stagnium, Plumbiscus, and Shining.  Thus it's more that IC2 duplicated the GT crops.

The earliest GT crops (including Coppon, Tine, Plumbilia, and Argentia) were originally from the addon BrainTech Agriculture by "I don't now", merged into GT as of about 2014 Dec 31 (or possibly earlier, I'm having trouble tracking down the exact merge date - that's the last edit date of the first post of the addon thread that mentions the addon being part of GT now).  The similar crops for IC2 were merged from estebes's addon "Useful-Crops" as of IC2exp 2.2 build 805 on 2015 Dec 04.

> I think it's better to continue this behavior for all crops that need an ore block below and delete IC2 crops from the global list to prevent their obtaining through a breeding.

I'm aware that that can be done, but I'm concerned about possible side effects of doing so for players who have already bred such crops.

**Comment by Techlone** [comment]
IC2 crops removing it's not necessary but useful for players if GT will have analogues of IC2 crops
Anyway GT crops will be better cuz we will can influence on them instead of IC2 code
>I'm concerned about possible side effects of doing so for players who have already bred such crops

Well somebody just should test it :)
