### ISSUE TITLE
Missing functionality of Heat Vent Covers

### ISSUE THREAD

**Issue by Antifluxfield** [Blood-Asp/GT5-Unofficial#1065]
The title is the main question I want to ask.
By the way, if they do have some special function, here's a bug that worth to be fixed: Due to the change of IC2, except for the Component Heat Vents, other heat vents cannot be placed on the machines as covers, since they always have a nonzero damage value.
Edit: So the main question is should we inherit the function of these covers in GT4, so that they can increase the efficiency of the machines?

**Comment by leagris** [comment]
Heat vents as covers used to increases machine efficiency (less energy per cycle). This was before Gregtech downgraded from 4 to 5 :rofl:

**Comment by Antifluxfield** [comment]
@leagris 
So when and where do they work? I tested on a scanner and a blast furnace, but cannot find any effect. Neither the time nor the electricity is saved.
More over, when right-clicked the cover with a screwdriver, it will change to other modes, like "redstone" "energy" "fluid" "item" and their combinations. What do all these mean?

**Comment by Techlone** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/loaders/misc/GT_CoverLoader.java#L17-L21
Behavior argument is null so the covers do nothing
>it will change to other modes, like "redstone" "energy" "fluid" "item"

It's common modes for cover without a behavior. It means "what can a cover pass through itself"

**Comment by Antifluxfield** [comment]
@leagris @Techlone Thanks.
So will anybody fix this feature, or just let it be?

**Comment by JohannesGaessler** [comment]
In my opinion the behavior of heat vents reducing EU/t should not be restored because from a physical standpoint that's total nonsense.
Also, depnding on how big the effect is, it might become posible to build a perpetuum mobile.
