### ISSUE TITLE
Fusion Reactor

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#107]
When a fusion reactor runs out of energy it does not "really" stop. It immediently starts again when it gets more material to process.
So my fusion runs with helium3 and carbon but i only have limited helium3 and my endstone processing is slower than my fusion reactor which resulted in the fusion reactor running out of fuel and then restarting again once it had 200mb helium3....
It restarted twice with very little helium3 in it and used the 160 million eu stored inside -.-"

Please make it so that you have to use the soft hammer again after it runs out of fuel.

**Comment by Blood-Asp** [comment]
That can all be automated using only GT tools, so that is intended. Not sure if that way any different in GT4.
