### ISSUE TITLE
Add the pure fluid to NEI

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1070]
Some fluids do not have versions in cells, f.e. Indium Concentrate, and therefore it is somehow hard to guess that they actually exist. I suggest adding the GtFluidDisplay to NEI, unless this fluid represents the hidden item, f.e. Molten Atlarus or Leninade.

**Comment by Blood-Asp** [comment]
You can already enable them in the config. I think Debug1 config shows them.

**Comment by Antillar** [comment]
It does, but it shows all of them instead of just the ones actually useful (and only a few of those are useful). Also, not all of the players know of it

**Comment by Blood-Asp** [comment]
Looking through how the fluid display is generated. Only showing the fluids that have no cell form seems really complex. As long not someone has an idea how to do that easily thats too much work for me for the gain of it.
