### ISSUE TITLE
Pipe/Cable/Wire tweak

### ISSUE THREAD

**Issue by Technus** [Blood-Asp/GT5-Unofficial#1073]
There is some fairly old code that i added into Pipes/Wires/Cables
It is about reducing collision/bounding boxes lists/pool by 1 px to allow "behind acces",

Also there is some HACK added for soldering iron that allows the Pipes/Wires/Cables to be visually smaller when holding the iron.

Affected files:
GT_MetaPipeEntity_Cable
GT_MetaPipeEntity_Fluid
GT_MetaPipeEntity_Item
MetaPipeEntity - probably
GT_Client - for the HACK
Probably listed all since it was not that complicated.

ps. there are also sum changes allowing 16xcables and stuff, textures are also mildly changed

**Comment by draknyte1** [comment]
The 'not having access behind cables' is intended and Greg has the actual solution. He just deemed it realistic.

**Comment by Blood-Asp** [comment]
what is his "actual solution"?

**Comment by Technus** [comment]
Not doing it at all he ment

**Comment by Technus** [comment]
Still if we talk about realism
why i can open hatches from not front?

**Comment by Blood-Asp** [comment]
Best would be to reduce the bounding box to the size of the pipe/cable and when opening guis check if the block in front is air.

**Comment by Technus** [comment]
that won't work, since then placing covers is pain/impossible (assuming u use the corners/edges placement methods)

**Comment by Blood-Asp** [comment]
i did only say check for air for opening guis. placing covers would not care about that.

**Comment by draknyte1** [comment]
No he had the solution for smaller collision/bounding boxes.

**Comment by Technus** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/pull/1077

**Comment by Blood-Asp** [comment]
merged
