### ISSUE TITLE
ore processing change suggestion

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#1075]
This has bothered me for a long time and now that I have been forced to deal with it in GT6 it bothers me even more, compound minerals (chalcopyrite, malicite, limonites, etc) shouldn't have a cheat for getting extra of the base element out of them, I.E. purified dusts smelted into copper ingot when crushed ores and dusts only give 3 nuggets.

**Comment by draknyte1** [comment]
unclean and purified dusts both give an ingot.
It's just crushed types that don't.
