### ISSUE TITLE
Corium uses same textures as corpseplant

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#108]
The default GregTech textures for corium and corpseplant are identical across all growth stages.  However, I discovered that in the mod "BrainTech Agricultures Datachip Package" which they were originally from, they were visually distinct from each other (see the first and third pictures in the first spoiler of http://forum.industrial-craft.net/index.php?page=Thread&threadID=7490 )  The "corpseplant" texture seems to have been used for both crops.

**Comment by Blood-Asp** [comment]
Exchanged textures for GT5.08.26
