### ISSUE TITLE
Tooltip for Small Steel Boiler is incorrect

### ISSUE THREAD

**Issue by draknyte1** [Blood-Asp/GT5-Unofficial#1080]
Tooltip states it adds 20/sec, but it adds 30/sec.

```
if (this.mProcessingEnergy > 0 && (aTick % 20L == 0L)) {
                GT_Pollution.addPollution(getBaseMetaTileEntity(), 30);
            }
```
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler_Steel.java#L155-L157

**Comment by Blood-Asp** [comment]
done
