### ISSUE TITLE
Cannot input oil into distillery while using Galaticraft.

### ISSUE THREAD

**Issue by ackevac** [Blood-Asp/GT5-Unofficial#1081]
The oil cannot be inputted into distillery as soon as I installed mod such as Galaticraft or Buildcraft that adds oil.Probably because of the ID of the fluid?

**Comment by draknyte1** [comment]
Fluid IDs don't matter. 
They are all the same oil.

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/issues/577 should be the same issue as this, including the same fix

**Comment by ackevac** [comment]
I have read the issue,but still don't know how to fix the problem.How to replace the gregtech:oil into Galatic:oil?

**Comment by draknyte1** [comment]
The fluid is called oil. Only one mod can add a fluid per name. All mods use fluids by name. So any mod adding a fluid called oil will use the first one registered to the fluid list. 

BloodAsp provided a fix for your issue.

**Comment by Blood-Asp** [comment]
uploading .30pre4 build to onedrive(http://1drv.ms/1L4h4gC) with an attempted fix for that issue. please try if it does fix it @Akiraca
