### ISSUE TITLE
Add multiple recipes per machine tick in Processing Array

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1082]
When several different items are placed in Multi Smelter, it takes whatever they are, just 2 stacks of items and smelts them at once. Would be nice if it was possible with processing arrays, which are currently unable to process 2 different input items at once.  

For example, if I have 16 macerators in processing array which crushes ores and I get 3 different ores from quarry, it will take 3 machine ticks to process them, one by one, despite the fact that the processing array is capable of processing 16 ores at once.

**Comment by Blood-Asp** [comment]
Historically the processing array was added to prevent spamming centrifuges for supply of d/t for fusion. The important point was to prevent the recipe search for every single recipe to keep it quick and server friendly. Changing it to be like the multismelter would break most of the positive effect it has for servers.
