### ISSUE TITLE
Engraved lapotron chips bug

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1084]
It is obvious - sometimes engraved lapotron chips do not produce. I have lapotronic energy orbs automated and I often order them. More than 10 times the recipe has stopped due to 3 lapotron chips not being crafted. 
I have placed the engraver in the cleanroom long ago. I use a quantum bridge to get ME Network inside, I supply stable EV - more than enough required for these chips to be produced. I never open a door or turn off the power of cleanroom.
Considering that I am absolutely sure in the safety of my ME Network, I have nothing to blame if not the engraver itself.
I would like to hear any suggestions why this could possibly happen.

**Comment by Georggi** [comment]
I doubt that it is internal, I am autocrafting orb clusters and never have encountered this, although I am using machine hulls for access.

**Comment by codewarrior0** [comment]
Your clean room needs maintenance.

**Comment by Antillar** [comment]
The cleanroom required maintenance indeed. Thanks for helping me out!
