### ISSUE TITLE
laser engraver eating wafers in cleanroom

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#1086]
https://youtu.be/2x94_4djw-g

**Comment by codewarrior0** [comment]
#1084

**Comment by Antifluxfield** [comment]
#1002 could help.

**Comment by Blood-Asp** [comment]
in the video you had the door open all the time... while the door is open, it gets dirty inside and crafts fail. It needs to run ~8min with door closed until it is perfectly clean. then 8 min door open lets slowly go down to 0% craft chance again.

just a quick door open for throwing in and taking out items should be fine. the moment it is turned of, it is instantly at 0%.

**Comment by Blood-Asp** [comment]
Also, if you want the exact value, use a scanner on the controller and look at the efficiency. efficency = chance for sucessfull craft.
And new(not sure if in 30pre2/3 or if even already build), the cleanroom controller now outputs a redstone signal equalling the efficency. So crafting can be automated.

**Comment by Blood-Asp** [comment]
as it seems an user error -> closed
