### ISSUE TITLE
chat is blank when using screwdriver on conveyor 

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#1087]
this started after updating to .30pre2. I have disconnected and reconnected multiple times.
![2017-06-12_20 30 28](https://user-images.githubusercontent.com/8433695/27060865-e166298a-4fad-11e7-9a0f-01faea0075e8.png)

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/3caab8d4ffe1d2b343b1ad4189e881e69cbbcdf5 fixed
