### ISSUE TITLE
Flexibility of circuit boards

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1089]
I would like to suggest the higher-tier circuit boards usable in the recipes of lower-tier circuits. It is stupid to have the advanced engraved circuit (SoC or even ASoC) and put this on primitive glued or phenolic plate. Once the fiberglass is accessible, it should be possible to use it in all lower-tier recipes. 

Aspecially, I would like the data stick to be crafted with fiberglass. They are truly used on IV+ when multilayer fiberglass is already available, and maintaining epoxid production just for them seems rather useless.

**Comment by JohannesGaessler** [comment]
I think to make that work a rebalancing of the Circuit Boards is in order though.
Currently Fiberglass Circuit Boards are way too cheap in my opinion, and also their current production process is not accurate at all.

**Comment by Antillar** [comment]
I agree with the lack of difficulty in fiberglass circuit board recipe, aspecially compared to the difficulty of the epoxy circuit board recipe (and add your new chemistry and it will be even more difficult). 

The original meaning of circuit boards is to allow a more complex circuit to be installed on it. So, if SoC can be installed on phenolic board, so it should on fiberglass board.

**Comment by codewarrior0** [comment]
:+1:

Really bugged me that I still had to make wood-and-resin boards while I was etching naquadah wafers.
