### ISSUE TITLE
crash when loading GT5u with IC2Classic

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#1090]
https://pastebin.com/hRhDjPf8
Classic has a actual working Enet vs the broken ass Enet in EXP, can this be fixed?

**Comment by Speiger** [comment]
Basically bloody this crash is caused by that classic doesnt have Biomass in it.
So a crash like this is happening.

**Comment by Speiger** [comment]
@Blood-Asp i know that sounds weird but maybe i can help you making a easy compat for IC2Classic Nuclear Components while using your own Values methode.
Basically i can reduce your work by a big chunk if you want to make that compat happen.
(I know bear would use it)

**Comment by bear989** [comment]
yes I would, I love the IC2c steam reactors!

**Comment by Blood-Asp** [comment]
Can't motivate myself to invest that much time there... too much other stuff that also needs to be done.
