### ISSUE TITLE
outdated mod with many incompatibilities?

### ISSUE THREAD

**Issue by tml32** [Blood-Asp/GT5-Unofficial#1092]
this mod (even though it's WIP) is getting really outdated it seems, since lots of mods have updated to at least 1.11.2 and this on isn't. Also, updates haven't been coming for a Long time, whats up?

also, this mod has multiple isssues with other worldgen-related mods, as shown by other issue posts as well.

please consider updating, whether it it will be an update for 1.10 or 1.11 doesn't really matter anymore at this point, even though many people would propably advise going for 1.11, since 1.10 is getting feature-freeze.

**Comment by Dragon2488** [comment]
We already have beta builds on 1.10 since January. You are blind.
Currently 1.10 version also experiencing modern rewrite.
WorldGen issues were fixed in latest commits.
