### ISSUE TITLE
GT arrows localization broken

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#1093]
![2017-06-14_21 10 59](https://user-images.githubusercontent.com/8433695/27160919-c14a2fb8-5145-11e7-88f7-93f4a289ac1b.png)

**Comment by Blood-Asp** [comment]
Did that always happen? I think there should be the name of the player who shot the arrow, not the type of the arrow...

**Comment by draknyte1** [comment]
Actually I think it has for as along as I've been playing.

**Comment by Blood-Asp** [comment]
From looking trough the code i think the message is send by MC direct and not by GT code. But i'm not sure...

**Comment by bear989** [comment]
yes it has been broken for a long time.

**Comment by Blood-Asp** [comment]
i don't think i can really fix this. if someone thinks differently so tell me how.
