### ISSUE TITLE
Unused Materials

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1097]
These ores are shown in NEI despite the absence of the mods they are from:
Infused Gold
Vinteum
Aer , Aqua, Ignis, Ordo, Perditio, Terra Infused Stone

These ores are shown in NEI despite the fact that they never generate:
Chrome
Naquadria
I will add more ores to this group if I find more. I have to test on a modpack w/o MFR.

I am also unsure about Dark Steel ore, I don't think that it should generate. I have EIO installed and it is processed into 2 dark steel ingots straight away, which is balance breaking if it can be found.

These ores are not visible in NEI, but they still exist and can be aquired with MFR. These ores cannot be processed:
Silicon
Cobalt
Cadmium
Indium
Tungsten
Adamantium
Mithril
Dark Iron
Rutile
Alduorite
Magnesium
Nicolite
May be more to this list, as the ore generated by laser drill is pure random, and chances are very low. Will add these later if I find more.

Idk what to do with the ores from last list, but the fact that they do load makes me think that GT does some useless work during loading stage.

**Comment by Rongmario** [comment]
I've been looking into the materials stuff of GT for a while now

I've been constantly trying to find bits where time can be saved in loading, one thing I want to note is, several times I see the same material being registered during the iterating stage, I've been wanting to catch that somehow but haven't figured out the code.

**Comment by Antillar** [comment]
As for .30, these materials are shown in NEI while being unobtainable:
Infused Gold - Unidye
Alduorite - Metallurgy
Alunite - PFAA
Asbestos - PFAA
Basaltic Mineral Sand - PFAA
Bluestone - Engineer's Toolbox
Borax - PFAA
Cassiterite Sand - PFAA
Chromite - PFAA
Chrysotile - PFAA
Cobalt Hexahydrate - ??????
Crude Oil - TrainCraft
Diatomite - PFAA
Dilithium - Matter Overdrive
Dolomite - Underground Biomes (Greg said:Startrek related)
Emery - Engineer's Toolbox
Epidote - Underground Biomes
Forcicium - MFFS
Forcillium - MFFS
Fullers Earth - PFAA
Garnet Sand - PFAA
Glauconite Sand - PFAA
Granitic Mineral Sand - PFAA
Greenstone - GreenStone Mod
Gypsum - PFAA
Jade - The Erebus?
Kaolinite - PFAA
Kyanite - PFAA
Mica - PFAA
Migmatite - Underground Biomes
Mirabilite - PFAA
Mithril - Metallurgy
Perlite - PFAA
Pig Iron - Tinkers Construct
Pollucite - PFAA
Pumice - PFAA
Quartz Sand - PFAA
Realgar - PFAA
Redrock - ExtraBiomesXL
Siltstone - Underground Biomes
Trona - PFAA
Vermiculite - PFAA
Volcanic Ashes - PFAA
Wollastonite - PFAA
Zeolite - PFAA

Only Adamantium and Infused gold show ore forms.
The full list of default materials shown in NEI without any mods installed alongside is shown here: https://ftbwiki.org/Template:Navbox/GregTech_5

**Comment by Antillar** [comment]
.31:
Adamantium removed.
Everything else remains.

**Comment by Antillar** [comment]
I will rework this and post in more useful way just as https://github.com/Blood-Asp/GT5-Unofficial/issues/1234

**Comment by mura3277** [comment]
@Antillar Isn't this still valid?

**Comment by draknyte1** [comment]
IHL adds some of those materials as well. Consider Mica/Trona/etc.

**Comment by Antillar** [comment]
@Muramasa- this is still valid, however this issue does not provide the mod to relate the material to, so I closed it. I will send you the complete updated list with mods in Discord
