### ISSUE TITLE
Machine texture is bugged in inventory

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1098]
I have a video with this issue because it is hard to describe it with words and/or screenshots
https://www.youtube.com/watch?v=ZkQlxd8dITA&feature=youtu.be

**Comment by Technus** [comment]
Might be related to dynamic hitboxes, probably missing override for inventory hitbox?

**Comment by Technus** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/pull/1118/commits/850f30a9d7a55608e62cc8d4ca972b03b9045e66
