### ISSUE TITLE
Bio-Fossil into Essence Oreberry

### ISSUE THREAD

**Issue by xXGandalfXx** [Blood-Asp/GT5-Unofficial#11]
Previously, sorry for my bad english... :(

I don´t know for 100% that this is a bug caused by this GregTech version, but i think so.

If GregTech not installed, the bug is fixed...

A Bio-Fossil by FossilsAndArcheologyRevival will be automaticaly converted (in the inventory) into a Essence Oreberry by Tinkers Construct. Like a copper dust from IC or TE in a Copper Dust from GregTech. If you know what I mean.

I dont think that this is a feature, or?

Before i updated my modpack to the latest versions of mods (including GregTech and TConstruct), this bug havent exists. So i dont know which mod is the Problem.

**Comment by Blood-Asp** [comment]
can you tell me the oredic entrys of both items?

**Comment by xXGandalfXx** [comment]
EssenceOreberry: oreberryEssence
Bio-Fossil: oreFossil

**Comment by Blood-Asp** [comment]
https://www.dropbox.com/s/jjn500mnrxx2dii/gregtech_1.7.10-5.08.09.jar?dl=0
Please try if this does fix it.

**Comment by xXGandalfXx** [comment]
Yeah, the bug is fixed.

Thank you a lot :-)

**Comment by xXGandalfXx** [comment]
Sorry for reopening, but this problem is not completely fixed, i think.

I have found new bugs on servers. Singleplayer works.

If a bio-fossil drops in the in the world it turns instantly in a essence berry... Also by dropping from a fossil ore. And the old bug with converting in the inventory exists also.

I think again that the bugs caused by GregTech
