### ISSUE TITLE
Axe not recognizing some forestry trees

### ISSUE THREAD

**Issue by netmc** [Blood-Asp/GT5-Unofficial#1101]
Some forestry trees (extra trees) are not recognized as trees when chopping them down with a gregtech axe.  The axe chops single logs only for several of the forestry trees (extra trees).

Some of these include ash, brazilwood, old fustic, and rosewood.  (I believe these are all from extra trees.)

**Comment by draknyte1** [comment]
It also doesn't work on ic2 rubber trees.

**Comment by Blood-Asp** [comment]
GT works by oredict. These tree logs seem to have incorrect oredicts.

**Comment by MauveCloud** [comment]
I can't speak for the logs mentioned from extra trees, but I think ic2 rubber trees were deliberately not ore-dictionaried as logWood so that they can't be used as fuel, converted to charcoal, etc. until they are cooked to get jungle logs first.

**Comment by draknyte1** [comment]
A special case for rubber seems like a logical addition though.. 
Makes the lives of everyone easier I'd say.

Might do it later today.
