### ISSUE TITLE
Robot Arm not working as a cover

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1109]
This machine component should in theory also work as cover, putting items into the chosen slot. However, it always puts items into the first available slot, which is achievable even without the usage of this cover. 

Another bug I have found: if the central part is clicked before the outer part is clicked, the click will increase the slot number by one. But after the outer part was clicked at least once, clicking on the inner part will do complete opposite. When the cover mode is switched, the cover "forgets" about it, and the bug happens again.

The third bug I have encountered is that clicking on any part of the cover with screwdriver always increases the value, although it should decrease the number when clicked on the inner part and increase when the outer part is clicked.

Please fix this cover, it could be very useful in certain cases, aspecially with new assembling machine.

**Comment by Antifluxfield** [comment]
Robot Arms do work properly when you put them on a machine. The first issue you're talking about only happens when you put it on an item pipe.

**Comment by Antillar** [comment]
I have tested the cover only on machines and got all 3 issues. I have not tested it on item pipes.

**Comment by Antifluxfield** [comment]
![image](https://user-images.githubusercontent.com/17354844/27506833-ace4b97e-58f4-11e7-909f-a3af5a2ffbdf.png)
I set its mode to "Grab in for own Slot # 5" and the cover do grab the items into the second input slot;
![image](https://user-images.githubusercontent.com/17354844/27506879-a98c2cac-58f5-11e7-9b27-3954f4df1109.png)
Change the mode to "Puts out into adjacent Slot # 5" later, and the items are in the sixth slot.
I don't know how you test it, but what I find is that it do work properly in these cases.

**Comment by Antillar** [comment]
I have tested the cover on Circuit Assembling Machine

**Comment by Blood-Asp** [comment]
the slot only counts for one direction. either it takes from a certain slot and puts it into the first free, or it takes from any slot and puts it into a certain slot. 
are you certain you set it to the right setting?

**Comment by Antifluxfield** [comment]
![image](https://user-images.githubusercontent.com/17354844/27506943-4985ffc0-58f7-11e7-94d9-13c8047981a3.png)
Circuit Assembling, "Grab in for own Slot # 5".

**Comment by Antillar** [comment]
I have tested up to 10 and it didn't work. I tested with LV arm though.
