### ISSUE TITLE
Quantum tanks do not retain liquids when moved

### ISSUE THREAD

**Issue by pyure** [Blood-Asp/GT5-Unofficial#111]
Test:
* Half-filled a quantum tank with Helium Gas.
* Broke tank with GT wrench
* Placed tank: no liquid.

May be deliberate, although its a bit hard to explain.

If its deliberate I'll add it to the wiki.

**Comment by Blood-Asp** [comment]
For now is it deliberate. For Quantum Chests the same.
Was that different in GT4? Not sure if i can change that anyways, because of MetaTileEnitys...

**Comment by pyure** [comment]
Yeah, I figured that would be the case.

I suspect GT4 was the same.  Having barrels, tanks, etc. retain quantities on movement is a relatively new-era thing.  (Now just about everything besides BC tanks retain quantities)

I'll let you close the ticket if/when you decide its more trouble than its worth.

**Comment by Blood-Asp** [comment]
For now i say, write it on the wiki. TSteel Fluid Cells can transport up to 256000L per Slot, so GT has alternatives for fluid in inventory.

I will take a look at the code if i find a easy way to make it possible before closing.

**Comment by pyure** [comment]
No problem, thanks.

**Comment by pyure** [comment]
btw (unrelated) tsteel fluid cell tooltip says they can transport 64000L rather than 256000L.  Just fyi.

**Comment by Blood-Asp** [comment]
thats why i said per slot ;) They stack up to 4.

**Comment by pyure** [comment]
Oh neat.  Thanks for clarification.

**Comment by DarknessShadow** [comment]
Could you maybe add Jabba Dolly support for the Quantum Tanks / Chests?

**Comment by Blood-Asp** [comment]
That certainly does not work. Again MetaTileEntity problem.
