### ISSUE TITLE
Plastic Fuel Can broken

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1110]
Empty Plastic Fuel can cannot be filled with any fuel. The "Filled" version of the plastic fuel can is then unobtainable. What makes things worse, it cannot even be used at all. This makes this container a total waste of plastic, while it could be useful if it did what is stated in its description, aspecially with new petrochemistry update.

**Comment by Blood-Asp** [comment]
Afaik this is remaining from GT4 times and was never used in GT5

**Comment by Antillar** [comment]
Is it going to be removed then?

**Comment by Blood-Asp** [comment]
There is a lot unused stuff remaining...
