### ISSUE TITLE
Strange naming of 2x Fuel Rods.

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1111]
There are the following fuel rod types added by the mod:
Thorium
Depleted Thorium
Naquadah
Depleted Naquadah
Mox
Uranium

The 2x fuel rod version is called **Double** for Naquadah and Thorium and **Dual** for the other 4 rod types. I suggest renaming the double fuel rods to dual fuel rods, as this will make the naming more logical.

**Comment by JohannesGaessler** [comment]
Fixed via 250f280808ad982120d1851d622bada6d42b5214
