### ISSUE TITLE
Player Detector cannot detect its owner

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1112]
Player Detector has 3 modes:
Emit if any Player is close
Emit if other Player is close
Emit if you are close

For some reason the second mode works exactly the same as the first mode, and third mode never emits signal. This was tested in local world with 2 players logged in, the detector couldn't detect the player who placed it for both of them.

**Comment by Antifluxfield** [comment]
Seems that I wrongly exchanged its message in #1067.
But that's not the critical thing. The main reason is that not all coverable tiles records its owner: the machines do, but the frame boxes don't.
