### ISSUE TITLE
Changing the mode for Drain destroyes fluid block

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1113]
If the Drain cover is attached to the side of the machine, and any fluid block is touching this side (which is a normal situation for using this cover), changing the mode on the cover with screwdriver destroyes this fluid block without doing anything to the internal fluid buffer of the machine.

**Comment by Blood-Asp** [comment]
Is this really a problem?

**Comment by Antillar** [comment]
No, but it is a bug
