### ISSUE TITLE
Suggestion for Assembly Line recipes

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1114]
Currently Assembly Line recipes do not support Forge Ore Dictionary. However it seems like they are intended to. This does not cause problems as long as this does not involves circuity.
The recipes of the Assembly Line are meant to be performed at IV level and higher. This means that the player already has quantumprocessors and is able to craft those. However, the Assembly Line recipes only require Quantumprocessors, when the highest tier of them is needed - the mainframe. In all other cases the Nanoprocessor Mainframe is required or even the yellow Mainframe!
All this makes the Assembly Line recipes unnecessarily expencive and difficult, as the player now needs to craft the highest tiers of primitive circuits, which are usually not autocrafted anymore at the quantumprocessor level. Having to return to them is a significant step back in the progression.

I suggest replacing all circuits from EV level to ZPM level with quantumprocessor variants,starting from a single processor instead of Workstation, then Quantumprocessor Assembly instead of yellow Mainframe, then Master Quantumcomputer instead of Nanoprocessor Mainframe, then Quantumprocessor Mainframe. 

If the machine does not support ore dictionary, it is ok. If it does not support it while behaving as it does, it is not ok.

**Comment by mura3277** [comment]
@Blood-Asp Has this been implemented?

**Comment by Blood-Asp** [comment]
The commit is linked. But not yet released as full release (.31)
