### ISSUE TITLE
Gregtech-5.10.41 and Computronics-1.10.2-1.6.1

### ISSUE THREAD

**Issue by KartAlexPet** [Blood-Asp/GT5-Unofficial#1116]
gregtech-5.10.41 and Computronics-1.10.2-1.6.1
again GT and asielib conflict :(
message "gregtech: [MC1710,MC1710]"
[2017-06-24-2.log.gz](https://github.com/Blood-Asp/GT5-Unofficial/files/1099574/2017-06-24-2.log.gz)

**Comment by Dragon2488** [comment]
report to asie.

**Comment by KartAlexPet** [comment]
I did.

**Comment by KartAlexPet** [comment]
Just updated Computronics. My bad.
