### ISSUE TITLE
Magic Energy Absorbers will not generate energy from energized nodes

### ISSUE THREAD

**Issue by Pyromancer56** [Blood-Asp/GT5-Unofficial#1119]
Tested with a node that has 110 CV of each primal aspect with an Adept Magic Energy Absorber (MV). Would not generate any energy but works fine with all other sources.

**Comment by draknyte1** [comment]
```
// Energyzed node
            if (isThaumcraftLoaded) {
                try {
                    World tmpWorld = this.getBaseMetaTileEntity().getWorld();
                    int tmpX = this.getBaseMetaTileEntity().getXCoord();
                    int tmpY = this.getBaseMetaTileEntity().getYCoord();
                    int tmpZ = this.getBaseMetaTileEntity().getZCoord();
                    int fire = VisNetHandler.drainVis(tmpWorld, tmpX, tmpY, tmpZ, Aspect.FIRE, 1000);
                    int earth = VisNetHandler.drainVis(tmpWorld, tmpX, tmpY, tmpZ, Aspect.EARTH, 1000);
                    int air = VisNetHandler.drainVis(tmpWorld, tmpX, tmpY, tmpZ, Aspect.AIR, 1000);
                    int destruction = VisNetHandler.drainVis(tmpWorld, tmpX, tmpY, tmpZ, Aspect.ENTROPY, 1000);
                    int order = VisNetHandler.drainVis(tmpWorld, tmpX, tmpY, tmpZ, Aspect.ORDER, 1000);
                    int water = VisNetHandler.drainVis(tmpWorld, tmpX, tmpY, tmpZ, Aspect.WATER, 1000);
                    int visEU = (int) (Math.pow(fire, 4) + Math.pow(earth, 4) + Math.pow(air, 4) + Math.pow(destruction, 4) + Math.pow(order, 4) + Math.pow(
                            water, 4));
                    int mult = 85;
                    if (fire > 4)
                        mult += 15;
                    if (earth > 4)
                        mult += 15;
                    if (air > 4)
                        mult += 15;
                    if (destruction > 4)
                        mult += 15;
                    if (order > 4)
                        mult += 15;
                    if (water > 4)
                        mult += 15;
                    visEU = (visEU * mult) / 100;
                    getBaseMetaTileEntity().increaseStoredEnergyUnits(Math.min(maxEUOutput(), visEU * getEfficiency() / this.sEnergyFromVis), false);
                } catch (Throwable e) {
                }
            }
```
The issue may be that it checks where the Absorber actually is for the node, not tmpY +1?
Also, there's no check to see if it's an energized node. Any node should work~

**Comment by Pyromancer56** [comment]
I had tested it with a normal node as well just in case and it doesn't do anything.  The absorber seems to know about the energized node as particle effects start to flow into it from the node.

**Comment by jaskarth** [comment]
the real bug is that  this.sEnergyFromVis is set to 12800 or something like that, so dividing by it always results in 0 because of casting to an integer.

**Comment by leagris** [comment]
The issue is that it converts at only 1/20 rate
A Grand Magical Master Energy Absorber that's supposed to output 2048 EU/t, actually ony outputs 2048 EU per second.

Here is the correct setup to Absorb energy from a node:

Bottom: Node Stabiliser
Center: Actual node with capability to provide Ignis aspect and to be converted to energised node
Top: Node Transducer with redstone signal on

Energy Absorber setup:
Top: a vis relay at max 8 blocs from Energised node or another relay
Bottom: Energy Absorber
![2018-07-13_04 47 42](https://user-images.githubusercontent.com/1111474/42669975-a2673336-8658-11e8-8312-c1d100778307.png)
