### ISSUE TITLE
Nuclear Control 2 Range Trigger

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#112]
The GregTech Sensor Kit does not work with the Range Trigger.
Even though it works with battery buffers and shows the eu stored inside the batteries of the battery buffer on screen.

gregtech_1.7.10-5.08.25
IC2NuclearControl-2.2.5a-GoingForTheKill

**Comment by Blood-Asp** [comment]
I do not even know what the range trigger is and what it does.

**Comment by DarknessShadow** [comment]
It can emit a redstone signal depending on the stored EU. (This would be awesome because it would be the first thing to monitor the eu inside the batteries in battery buffers and emit redstone signal)

**Comment by DarknessShadow** [comment]
And btw the name of the "High Voltage Battery Buffer" is weird on the screen but thats not really important.
<a href="http://imgur.com/GbUMbUR"><img src="http://i.imgur.com/GbUMbUR.jpg" title="source: imgur.com" /></a>

**Comment by Blood-Asp** [comment]
The Energy Detector also has a mode that checks the energy stored including the batterys.

**Comment by DarknessShadow** [comment]
Didn't know that but still the Range Trigger can be configured very precisely to any eu numbers and can do that also remotely.
