### ISSUE TITLE
Missing Extruder recipe for Small Gear

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#1120]
I can not see any reason why Small Gear should be crafted via Fluid Extractor + Solidifier instead of just Extruder like all other "formed" items.

**Comment by Rongmario** [comment]
Could make a small gear mold for the alloy smelting recipes too? :thinking:

**Comment by draknyte1** [comment]
Gregs logic was/is 'you don't need that many of them' which I agree with.

**Comment by MauveCloud** [comment]
I have to disagree with that logic.  Small gears are needed for electric pistons, which are used in the recipes for a fair number of machines.

**Comment by draknyte1** [comment]
Used far less than other components though. Except maybe normal gears..

**Comment by codewarrior0** [comment]
The gameplay is kind of weird. You get to weigh the cost of an MV extractor/solidifier combo (including the mold!) against the cost of wearing out a bunch of hammers for all the small gears you expect to craft, and the hammers usually win. I'm more likely to put hammers into an LP Crafting Table to craft small gears than I am to set up the extractor/solidifier combo.

**Comment by SapientMC** [comment]
@codewarrior0 Hammer Crafting has one inconvenient feature. If all crafting recipes are automated via ME-system and I start crafting some different machines at the same time, several Hammers would be crafted (one for each process). In case with Extractor+Solidifier or Extruder all needed gears will be crafted in turn.

**Comment by codewarrior0** [comment]
That's why I use LP instead of ME for automating gregstuff. I can set a supplier pipe on the LP crafting table to keep exactly one hammer in stock, so the hammer isn't even part of the programmed crafting recipe!

**Comment by MauveCloud** [comment]
@codewarrior0 that's a good point about the hammer.  I usually did it that way myself (except for the Logistics Pipes bit, I haven't used that mod), and was in no rush to set up an extractor/solidifier combo.

Also, thinking about this more, I see two issues with adding an extruder recipe for the small gear:
1. There are already 24 extruder shapes with recipes that can be visualized as having the empty shape plate in the center of a 5x5 grid and a wire cutter somewhere in the grid.  How would one add another recipe?  A second cutter?  An additional tool type?  Hardly seems worthwhile for one component type.
2. Components that can be made via either an extruder or a fluid extractor/solidifier combo often cost significantly more total EU in the extruder, even considering the overclocked cost for the solidifier (most solidifier recipes can be done at LV, even if the fluid extraction requires MV), e.g.:
bronze plate: 9728 EU in extruder, 1128+512=1640 EU in extractor+solidifier
bronze gear: 48640 EU in extruder, 4512+2048=6560 EU in extractor+solidifier

**Comment by SapientMC** [comment]
@MauveCloud
1. Shape for Small Gear could be made in two steps: Empty Shape -> Rod Shape -> Small Gear Shape.
2. At the automation stage of all recipes through ME several thousand eU are conceived as much less than 2x space for Extractor + Solidifier.

**Comment by mura3277** [comment]
Adding to ideas #654

**Comment by draknyte1** [comment]
Added to GT++ via https://github.com/draknyte1/GTplusplus/commit/aa01c059b9dd28e4d3c5625385a6d242ac345a72.
