### ISSUE TITLE
Unpaintable Multiblock Machines

### ISSUE THREAD

**Issue by Creeperologist** [Blood-Asp/GT5-Unofficial#1124]
Both Mutli-Block components (buses/hatches) and the generic blocks they are made from (e.g. Heat Proof Machine Casings) are currently unpaintable, even if these try to mimic the other blocks, they should still be capable of being painted

**Comment by Technus** [comment]
They are paintable, just not visually. Piping will behave correctly.

**Comment by Blood-Asp** [comment]
It would not be possible to paint the main building blocks that are not TEs. So only painting single blocks from a multiblock would look stupid...

**Comment by leagris** [comment]
Would be a valid option if multi-block painting would allow determine if a component can be used by a controller on shared-wall setups.
Like blue painted maintenance hatch belong to blue painted controller only.
Unpainted output hatches/busses in shared wall, can be used by both controllers.
No need to paint walls/casings, but devices as component of a multi-block should appear painted.
