### ISSUE TITLE
aluminum without blast furnace

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#1125]
slag combs with crushed spodumene gives molten aluminium witch can be solidified in a LV solidifier, no blast furnace needed
![2017-06-27_22 41 08](https://user-images.githubusercontent.com/8433695/27618292-6606712c-5b89-11e7-8f5e-56653a070d71.png)

**Comment by draknyte1** [comment]
You'll find lots of metals don't need a blast furnace if you make it molten and then solidify.

**Comment by MauveCloud** [comment]
You might notice it requires 3 L of liquid UU-matter, though, which sort of counter-balances the lack of need for a blast furnace.

**Comment by bear989** [comment]
wtf are you talking about?? this isnt the autoclave recipe, this is the chemical reactor recipe and doesnt take UUM. did you even look at the damn picture before adding your 2cents?

**Comment by MauveCloud** [comment]
Sorry.  I'm not used to default textures (I use PureBDCraft), so I tried to look up the recipe for myself and failed to double-check that it was the right one I was comparing with.  Shame on me.  Still, it takes a fair while to breed bees that can produce slag combs, right?

**Comment by draknyte1** [comment]
Just fluid extract dust. 
Just solidify molten metal to plate.

**Comment by Blood-Asp** [comment]
You know that Blast furnace materials can not be fluid extracted from dust or ore?

I'm currently only considering if it is really unbalanced for be able to make aluminium with bees. building a EBF would be much easier...

**Comment by bear989** [comment]
but you need aluminum to make the MV fluid extractor to get molten aluminum
to be able to solidify it where with the slag combs it doesnt need anything
other than LV.

**Comment by bear989** [comment]
after testing you can not do dust or ore in a fluid extractor even at MV, dust can only be done at HV or higher and ore at none of the 3, only ingots can be done at MV so you have to use the EBF to make them first,
https://youtu.be/-lrU92haynI
