### ISSUE TITLE
fluid regulators only use base circuit

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#1127]
![2017-06-28_20 19 37](https://user-images.githubusercontent.com/8433695/27666004-d1e9dd56-5c3e-11e7-8c5a-6dddafaefdff.png)

![2017-06-28_20 19 40](https://user-images.githubusercontent.com/8433695/27666010-d6898fd2-5c3e-11e7-92e0-855d6124c64e.png)
at the point you will probably be making these you are on to the better versions

**Comment by Dimach** [comment]
duplicate #1039
