### ISSUE TITLE
Nuclear Control 2 wrong name on screen

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#113]
The name of the "High Voltage Battery Buffer" is weird on the screen.
<a href="http://imgur.com/GbUMbUR"><img src="http://i.imgur.com/GbUMbUR.jpg" title="source: imgur.com" /></a>
gregtech_1.7.10-5.08.25
IC2NuclearControl-2.2.5a-GoingForTheKill

**Comment by Blood-Asp** [comment]
Fixed in 5.08.27
