### ISSUE TITLE
Feature request: water from oil drilling rig

### ISSUE THREAD

**Issue by PaulMadsen** [Blood-Asp/GT5-Unofficial#1131]
Being able to obtain water from an oil drilling rig would fit very well with play styles that disable infinite water.  Rather than having 28% of prospected chunks contain no oil, some of them could contain aquifers.

**Comment by MauveCloud** [comment]
I'm not sure where there's much documentation of it, but I think the configuration for oil drilling fluids added in 5.09.28 already makes this possible.

**Comment by SapientMC** [comment]
@MauveCloud You right. Any fluid could be added under bedrock on any dimension via config.
