### ISSUE TITLE
[5.09.31pre1] Something strange with textures of all bus/hull/hatch of pyrolyse oven

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#1133]
Its blue. With or without texturepack.
![2017-07-01_22 25 34](https://user-images.githubusercontent.com/14032818/27765236-9d080700-5eac-11e7-955f-28333af1f2de.png)
![2017-07-01_22 25 42](https://user-images.githubusercontent.com/14032818/27765237-9d099d7c-5eac-11e7-89dd-ca37e2120949.png)
![2017-07-01_22 27 42](https://user-images.githubusercontent.com/14032818/27765238-a2195d5c-5eac-11e7-993c-ddd5fc7cfcdf.png)
![2017-07-01_22 27 46](https://user-images.githubusercontent.com/14032818/27765239-a21c967a-5eac-11e7-8220-22e924f8f348.png)

**Comment by draknyte1** [comment]
With or without GT++?

**Comment by SapientMC** [comment]
Without

**Comment by SapientMC** [comment]
[5.09.31pre2]
![2017-07-07_15 30 29](https://user-images.githubusercontent.com/14032818/27948147-e66b70a8-62f8-11e7-9692-f67c743ce7a0.png)
![2017-07-07_15 47 29](https://user-images.githubusercontent.com/14032818/27948507-56d5edb8-62fa-11e7-9c1e-838497ed6092.png)

**Comment by Pilad** [comment]
pre2 LV and MV input/output hatch/bus
http://imgur.com/omDAsFa
http://imgur.com/zQJxuUS

**Comment by Pilad** [comment]
Default
http://imgur.com/0NzlhAC
http://imgur.com/HBpjhl0
