### ISSUE TITLE
pyroluse oven needs diffrent coils

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#1136]
the pyroluse oven has been pushed further and further down the tech tree do to using Kanthal coils. I have never understood the need for such high heat to make charcoal, especially since the recipes are all, or mostly, MV. I feel that the coils should only require copper nickel or a special heating coil block to move it back to MV rather than the far end of HV.

**Comment by JohannesGaessler** [comment]
I agree.
Making Charcoal is low-tech to the point that you can do it even without electricity.
It makes no sense that you need such a high level of tech.

**Comment by Techlone** [comment]
Maybe add a dependency from temperature for recipes like in EBF?

**Comment by codewarrior0** [comment]
Yep. By the time you can build one, you're usually so far away from charcoal power that you'd only build the oven if you were really starved for oil.

**Comment by Blood-Asp** [comment]
the reason it was added to be late in the techtree, is that it was meant as late replacement for RC coke ovens. About at that point in the game where players start building 50+ of them...

**Comment by JohannesGaessler** [comment]
How about something like this:
-The Pyrolyze Oven can use any Coil tier
-The higher the Coil tier, the more Charcoal you get per operation
-Nitrogen increases effective Coil tier

**Comment by Techlone** [comment]
And what do with other recipes? Or with custom recipes which are added via GTTweaker?

**Comment by draknyte1** [comment]
Just do this;
Recipe time = recipe time / ((Coil Tier / 2)(rounded up))

So cupronickel and kanthal give no speed boost and every two tiers up begins to half the time. Only counting in twos to make the result not too drastic. Or tier 1-5 are recipe time / tier and any coils better do no difference.

**Comment by JohannesGaessler** [comment]
Or you could maybe do something like this:
Recipe time = Recipe time * 2 / (2 + Coil Tier),
with Cupronickel=0, Kanthal=1, etc.
With that the amount of Charcoal produced per time unit will scale linearly with the Coil Tier:
Cupronickel -> 100% Speed
Kanthal -> 150% Speed
Nichrome -> 200% Speed

**Comment by Techlone** [comment]
>Recipe time = Recipe time * 2 / (2 + Coil Tier)

I vote for this

**Comment by BurovB** [comment]
+

**Comment by SapientMC** [comment]
@Blood-Asp RC coke ovens could be totally disabled by modpack authors.

**Comment by draknyte1** [comment]
I don't think we should change the amount of charcoal that gets output.

**Comment by netmc** [comment]
With the pyrolyse oven replacing the charcoal pit, and not requiring railcraft for coke ovens, it should be craftable at the early MV stage.    With railcraft in the mix, the pyrolyse oven is completely unnecessary.  Without railcraft, it is burdensome to craft.

Also, some of the recipes are a little strange.  The wood to oil shouldn't be there as is.  Wood fiber is way too tough to turn into oil.  Biochaff would be a better option for turning into oil.  If you are using wood, you would need sulfuric acid to reduce the wood fiber into something that *could* be cooked down.  Even then, it should take a lot longer than 16 seconds to process..  More like 240 seconds.

**Comment by JohannesGaessler** [comment]
Hm, are you sure about the oil recipes?
According to Wikipedia wood is one of the primary feedstocks for pyrolysis oil:
https://en.wikipedia.org/wiki/Pyrolysis_oil
