### ISSUE TITLE
[5.09.31pre1] Very Heavy Oil have no Dist Tower recipe

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#1141]
subj

**Comment by Rongmario** [comment]
Very Heavy Oil comes from the Oil Drilling Rig, it can be distilled into Heavy Oil for other means.

**Comment by Blood-Asp** [comment]
very heavy oil is only is as PFAA compat, not generated by GT itself. So as compat recipe there is an distillery recipe to turn it into heavy oil.

**Comment by SapientMC** [comment]
Ok, thanx.
