### ISSUE TITLE
Infinite nether quartz loop

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#115]
When AE2 is installed it is possible to make infinite nether quartz with making pure nether quartz and using Lathe with it. Proposed change is to separate Pure and Normal nether quartz making the Pure one producing 1 Rod + 2 Tiny dusts instead of Small dusts.

https://github.com/JasonMcRay/InfiTech-1.7/issues/319

**Comment by Blood-Asp** [comment]
Just looked at this. Pure Quartz into a Rod is not a default GT recipe. My guess: Adding it as OreDict causes this issue.

**Comment by JasonMcRay** [comment]
Yes it is grabbing the oredict. (tried to remove it via MT3, but it has no effect since GT just doesnt care about Minetweaker :D)

**Comment by Blood-Asp** [comment]
You add it in the first place: https://github.com/JasonMcRay/InfiTech-1.7/blob/master/scripts/vanilla.zs#L29
The lathe recipe is oredict, so it gets created with vanilla nether quartz on start up and then accepts every item that hat the same OreDict. In that case adding oreDict with MT works.

Is there no item with the right oredict, GT does not load the recipe on startup and then adding the oredict later on with MT does not change anything.

**Comment by JasonMcRay** [comment]
Oh.. I missed that... Thanks :)
