### ISSUE TITLE
Same oil added to generation twise

### ISSUE THREAD

**Issue by Dimach** [Blood-Asp/GT5-Unofficial#1150]
Here https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/objects/GT_UO_DimensionList.java#L56
And what difference between crude oil and raw oil?

**Comment by Blood-Asp** [comment]
none... so no idea why that happend...

**Comment by Dimach** [comment]
In some versions before, raw oil have 2x more output products with same energy consumption (in dist tower). But now they equivalent...

**Comment by Blood-Asp** [comment]
If i do another change to the oilgen logic someone is gonna kill me... So best it stays as it is...
