### ISSUE TITLE
assembly line

### ISSUE THREAD

**Issue by styopa1** [Blood-Asp/GT5-Unofficial#1152]
I can not replace the mainframe with a nanoprocessor in the assembly line.
So conceived that it takes only the most low-tech schemes?

**Comment by draknyte1** [comment]
It doesn't use the ore dictionary. 
No doubt it only uses the first value it finds.

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/a0031717d11db2c8c7f55ed0dc0de84ff8dc2a26 included in the latest prebuilds. New Datasticks nessary since they do not update.
