### ISSUE TITLE
Molten Phased Gold vs. Vibrant Alloy

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#116]
There is slight inconsistency with these two fluids. They are the same, however:
Phased Gold is made by melting Vibrant Alloy Ingot in extractor.
Vibrant Alloy fluid is made by melting Vibrant Alloy Nugget in extractor.

Of course with this comes changing Fluid Soldifier recipes.

Please unify that to just one liquid (preferably Phased Gold, since I have a feeling that this one was there from the begining)

**Comment by AiwendilCiunio** [comment]
Also they're not interchangeable, that's the problem. And they either should be interchangeable or should be unified into 1 liquid type (phased gold sounds ridiculous, molten vibrant alloy at least resembles what it's made of)

**Comment by JasonMcRay** [comment]
I noticed that there is also Molten Pulsating Alloy, and Molten Phased Iron (again both are same, only nugget gives Molten Pulsating Alloy and Ingot gives Phased Iron)

**Comment by Blood-Asp** [comment]
Phased Gold is the old name of vibrant alloy and still used as oreDict tag. GT is looking at the oreDict to match the fluids and this is the result. 

Might be worth to ask the EnderIO guys to update thier oreDict tags to fit current names?

**Comment by Blood-Asp** [comment]
Added to the recipe adder: When a recipes with phased gold or phased iron is added, the fluids automaticly get replaced with vibrant alloy or pulsating alloy.
