### ISSUE TITLE
GT drill doesn't place torches on right-click

### ISSUE THREAD

**Issue by xarses** [Blood-Asp/GT5-Unofficial#1164]
Please add the right-click torch placement like the IC2 drills support.

**Comment by Blood-Asp** [comment]
What would be the preferred function? Only torches and search the full inventory for them, or place the block right of the tool in the hotbar?

**Comment by OvermindDL1** [comment]
> place the block right of the tool in the hotbar?

This I think is what was discussed with greg a long while back.

I personally opted for it always placing whatever is in the right-most slot, as that was standard of a couple of other mods with similar features at the time.

**Comment by mura3277** [comment]
Adding to ideas: #654
