### ISSUE TITLE
bellows for bronze blast furnace

### ISSUE THREAD

**Issue by makuk** [Blood-Asp/GT5-Unofficial#1166]
It takes too much time to produce steel in Bronze Blast Furnace.
Adding a bellow would be a good solution.

**Comment by mightydanp** [comment]
If we speed it up with billow then there would be no need to make steel in the electrical blast furnace.

**Comment by makuk** [comment]
When we use bellows, it spends more fuel.
And bellows can't reduce time as of electric blast furnace.
Maybe an electric bellow for electric blast furnace will be also good.

**Comment by JohannesGaessler** [comment]
I've at some point added an alternative to the Bronze Blast Furnace that is built from Bricks: https://github.com/Blood-Asp/GT5-Unofficial/pull/1099
Since the Bricked Blast Furnace is much cheaper than the Bronze Blast Furnace you will be able to produce more Steel simply by building more Furnaces.

**Comment by Dragon2488** [comment]
It doesn't take too much time. Tip: steel is cooked faster with coal coke.

**Comment by makuk** [comment]
My mistake. Sorry. I didn't read the pull request carefully and I thought bricked blast furnace produces bronze.
