### ISSUE TITLE
8 Missing Metallurgy GT Materials

### ISSUE THREAD

**Issue by Muramasa-** [Blood-Asp/GT5-Unofficial#117]
In 5.08.26, you added the missing metallurgy materials, but 8 materials either still have no GT support or just some.

Example (Ingot) Ore Dicts:
ore:ingotAlduorite (No GT materials)
ore:ingotLemurite (No GT materials)
ore:ingotMeutoite (No GT materials)
ore:ingotRubracium (No GT materials)
ore:ingotIgnatius (No GT materials)
ore:ingotKalendrite (Some GT materials)
ore:ingotVulcanite (Some GT materials)
ore:ingotInfuscolium (Some GT materials)

Thanks for your hard work, BloodAsp

**Comment by Muramasa-** [comment]
Looking more into some of the ores (Kelendrite for example), there seems to be an issue with the output from macerating the ore.

![](http://i.imgur.com/MaM9nz7.png)

**Comment by Blood-Asp** [comment]
Added the missing Metallurgy stuff. (now hopefully all.)
