### ISSUE TITLE
Random crash when ordering a recipe

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1173]
If the recipe contains hammer, wrench, screwdriver and/or other GT meta-tools which emit sound when the crafting operation is performed, the client can sometimes crash if this recipe is ordered in ME terminal. In this case the successful order is followed by "click" sound, which in my opinion may conflict with the sounds played by GT meta-tools used in the recipe. This is a pretty rare crash. It happens every 100th time such recipe is performed, but it did happen 3 or more times for me.
[crash-2017-07-27_20.41.50-client.txt](https://github.com/Blood-Asp/GT5-Unofficial/files/1180662/crash-2017-07-27_20.41.50-client.txt)
I am using .30 version.

**Comment by draknyte1** [comment]
Tool sounds when crafting have always been an issue as other mods don't always handle them correctly.

**Comment by Rongmario** [comment]
I remembered it was Extra Utilities causing the crash.

**Comment by draknyte1** [comment]
Any mod that does crafting somehow can cause it.

**Comment by Blood-Asp** [comment]
We already tried a few things to fix this... And it was fixed in a few cases, at last improved in most. To do more the other mods have to it in their side.
