### ISSUE TITLE
Some ideas for automation needs

### ISSUE THREAD

**Issue by GreenCat1988** [Blood-Asp/GT5-Unofficial#1175]
1) Stacks of items sometimes need to be divided in to different parts for different processing (for example - A ingots divide to make from them B plates, C wires, D dusts, E alloys and make from them only 1 component). Even dividing into two parts can solve this problem.
2) Mass production of different types of component is possible only with the help of AE2 (pump covers, electric pistons, sensors, motors, etc.). Circuit assembler already exists. Components assembler?

**Comment by JohannesGaessler** [comment]
1. Has already been implemented (Item Distributor), though it's not in any full release yet.
2. I will make a Pull Request for this in the near future.
