### ISSUE TITLE
Broken Recipes

### ISSUE THREAD

**Issue by ghost** [Blood-Asp/GT5-Unofficial#1177]
I'm using *GregTech* version _5.09.30_, *Optifine* , *Not Enough Ids (NEI)* and *AE2 _(if it has something to do with this)_* 
1.7.10 forge latest version

The IC2 recipe for the Forge Hammer doesn't work. I tried every single combination from all the updated wikis and still nothing. I tried removing *NEI* and resetting the config but it didn't work :C

Because of this I can't make anything, not even Iron Plates. I need to craft an Iron Pickaxe but it requires iron plates :/

**Comment by draknyte1** [comment]
Make a hammer and two ingots to make plates..
