### ISSUE TITLE
Missing Blast furnace configs

### ISSUE THREAD

**Issue by redmage17** [Blood-Asp/GT5-Unofficial#1178]
I have Ender IO installed and for some reason there is no option to turn off the requirement in either  the enabled blast furnace configs or the materials list.

**Comment by draknyte1** [comment]
EIO recipes still exist, so they're totally avoidable.

**Comment by redmage17** [comment]
Your thinking it's an NEI issue?

**Comment by mura3277** [comment]
As @draknyte1 said, having the GT recipes does not stop you using the EIO ones.
