### ISSUE TITLE
Resurrection of book shelf of gregtech 4

### ISSUE THREAD

**Issue by Glease** [Blood-Asp/GT5-Unofficial#1179]
Book shelf is one of the most useless stuff ever existed in gregtech 4 (except for decoration), and it is thus removed in gregtech 5. However, since we now heavily rely on printing functions mid game onwards, I think it's now the time to bring it back, as we now really lack a good way to store books (without adding bibliocraft or anything alike, other mods that add "chest" blocks simply can't handle these task). A storage for datasticks/data orbs will also be welcomed (just like TinkerConstruct Pattern Chest).

These book shelves should only store books, data sticks and data orbs, though. Otherwise it doesn't make sense, or looks silly.

PS: BC  electronic library does store books, but locally, not in the remote server, which is bad for our cases.

**Comment by MineWitherMC** [comment]
Don't GT4 bookshelves only store 1 item?

**Comment by Glease** [comment]
At least it's a proper storage, and we can change that, can't we?

**Comment by draknyte1** [comment]
Done - https://github.com/draknyte1/GTplusplus/commit/a264f3e5bc7191d603f187b7f4d03401352db5c4
