### ISSUE TITLE
Microwave Energy Transmiter

### ISSUE THREAD

**Issue by Anarack** [Blood-Asp/GT5-Unofficial#1183]
Pack GT New Horizons
MC 1.7.10
GT 5.09.31.19
The microwave energy transmitter should list its loss %, if it has one, as well as the ability to use nitrogen plasma to move energy between dimensions in the tool tip.

**Comment by OneEyeMaker** [comment]
@Anarack 
Please, report it here:
https://github.com/GTNewHorizons/GT5-Unofficial/issues
or here:
https://github.com/GTNewHorizons/NewHorizons/issues

**Comment by draknyte1** [comment]
@oneeyemaker this is applicable for here if it doesn't do it in gregtech by default. It's more of a suggestion not an issue. 

Good to see you're alive and well, should hop on discord sometime.
