### ISSUE TITLE
Sheldonite or Cooperite?

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1185]
It seems illogical that all the ore processing components and all dust types are named Sheldonite despite having an ore dictionary name as Cooperite. I suggest changing either oredict or ingame naming so they suit each other.

**Comment by draknyte1** [comment]
It's a shit joke, from a show called Big Bang Theory. Main character is named Sheldon Cooper. 

Won't be changed.
