### ISSUE TITLE
Low Gravity Suggestion to help servers

### ISSUE THREAD

**Issue by EconBrony** [Blood-Asp/GT5-Unofficial#1186]
any chance a dimension setting for low gravity could be added to the config? I'd love to be able to add the moon as being considered low gravity. Currently only one player on our server can do low gravity processes since they made the first spacestation. It doesn't work at other spacestations, more or less blocking progression for the rest of the server.

**Comment by OvermindDL1** [comment]
> It doesn't work at other spacestations, more or less blocking progression for the rest of the server.

Wait what...?  o.O

**Comment by EconBrony** [comment]
It appears the low gravity only works in dimension 2, which is the first spacestation that is made

**Comment by OvermindDL1** [comment]
> It appears the low gravity only works in dimension 2, which is the first spacestation that is made

That is *entirely* a bug then...

**Comment by Technus** [comment]
@Blood-Asp look at our fork we should have some of the extra dims catched

**Comment by Technus** [comment]
But i am not sure if it applies here

**Comment by Blood-Asp** [comment]
The first version with the new circuits had that issue, but that is long fixed to go by biome type.

**Comment by EconBrony** [comment]
We are running 5.09.31pre2 and the process will not work on the moon currently. 
![2017-08-10_19 28 15](https://user-images.githubusercontent.com/30838236/29196459-7600f80e-7e02-11e7-8820-3978d0fff667.png)
![2017-08-10_19 28 03](https://user-images.githubusercontent.com/30838236/29196463-7b390802-7e02-11e7-9cc9-cde61cf0ae7b.png)

**Comment by draknyte1** [comment]
I assume it still requires a cleanroom?..

**Comment by EconBrony** [comment]
the recipe just says low gravity, never thought to try in a cleanroom

**Comment by Blood-Asp** [comment]
It was never meant to work on the moon or other planets. It should just work on everyones space station.

**Comment by Blood-Asp** [comment]
And no, no cleamroom nessary.

**Comment by draknyte1** [comment]
Why not moon or mars?
Should be easy enough to add.

**Comment by EconBrony** [comment]
ahh ok, might i suggest adding a config option for adding dimensions such as the moon, having many spacestations on my server would become quite taxing on the server

**Comment by Dream-Master** [comment]
GTNH have a Asteroids addition. So you can make it on GC Asteriods or Space station.

**Comment by Blood-Asp** [comment]
It says low gravity. Micro gravity might even be a better name. So having it working on planets would be right against the idea behind it.
And you only need it one time. No need for loaded and fully equiped space stations.

**Comment by Blood-Asp** [comment]
Well yes,  asteroids would make sense.

**Comment by draknyte1** [comment]
@EconBrony if they're not loaded simultaneously they won't impact performance.

**Comment by EconBrony** [comment]
ahh that would be wonderful, been a wail since I've allowed spacestations. Back in the day they worked similarly to mystcraft dimensions. One by itself was no big deal, but many could bring a server down. Each dimension would have what I call the base tick rate (which is the tick required just to keep the dimension loaded) then of course you have the increased tick rate you have from having blocks in it. The problem was for each spacestation or mystcraft dimension you added in another base tick rate. So once you had a bunch of base tick rates it created a lot of work for the server. If all those players were in the overworld, then youd just have the base tick for the overworld plus all the player builds. If it still works like this, OPIS will display each spacestation separately.

**Comment by draknyte1** [comment]
Opis will display each dimension separately. They simply don't tick if they're not loaded.. which requires a player or chunkloader in there. The only dimension that doesn't unload is the overworks because spawn chunks stay loaded forever.

**Comment by EconBrony** [comment]
Sorry, read that incorrectly, so the issue still persists then, bummer. The idea that members of the server will spend the resources on a spacestation that gives them their own dimension then just use it for the low gravity process is pretty unlikely, already seen that in action lol, would have never made the suggestion in the first place if that were the case :P. It would take a rule to stop them from chunkloading it. Its easier and better for the server to just turn low gravity off until an alternative comes about.

**Comment by EconBrony** [comment]
Forgot to mention, adding the asteroids would work well since most players who are at this point need naquadah as well

**Comment by MauveCloud** [comment]
@EconBrony if you're using an up-to-date version of GT5u, I think it should already work on asteroids, based on looking at this method:
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_BasicMachine.java#L757-L764

**Comment by EconBrony** [comment]
i will give it a try

**Comment by EconBrony** [comment]
It works, thanks MauveCloud
