### ISSUE TITLE
Unification configuration not working? (Properly)

### ISSUE THREAD

**Issue by 34486** [Blood-Asp/GT5-Unofficial#1187]
Alright, so I have my pack, added GregTech 5.10.41, went to configure it and I set everything in the unification file to 'xpotatovaluex_false=true' so I would assume it would not make IC2 items and other mod items into GregTech items only, but it still does. For example, circuits. I have Mekanism in the pack too, so I make a circuit with the Osmium (which all other Osmium ingots turned into gt ingots) and redstone, made the circuit thats a green square, and I put it in my inventory and it changed to a GregTech basic circuit. In the config in Mekanism section, and in the GregTech circuit part, They are both true. So, I reset the config, still the same thing, but then if I go into the GregTech main Config file and disable ItemUnification to false, it will make all circuits into IC2 items.... I Believe this is a bug, but also could you tell me how stop all items from changing to another mod? I might just be too stupid to configure it properly, but I have tested different settings, true and false for different circuits, on or off in main config, just true to that single item or 2 of them or all 3, all end up with the same issue accept the item will change which mod it prefers to change to.

**Comment by Exidex** [comment]
So, I wouldn't recommend you make gt pack right now. GT is being rewritten. The Unification system is already rewritten. Next GT update will break everything. soo yeah wait some time for a release.

**Comment by 34486** [comment]
Alrighty, Thanks! So the unification system works right now, or the update wasn't made yet on curseforge, or it is in the 5.10.41 build and I am doing something wrong?

Anyways, Thanks!

**Comment by Exidex** [comment]
"System is already rewritten" doesn't mean that we released version with this system. We will do it after we finish rewrite.

**Comment by 34486** [comment]
Ah, sorry my misunderstanding there.. Anyways, Thanks for the info, keep up on that great work, its some tiring stuff I tell ye what! 👍
