### ISSUE TITLE
Ore Drilling Plant Issues

### ISSUE THREAD

**Issue by npawk12** [Blood-Asp/GT5-Unofficial#1189]
Currently, the Ore Drilling Plant retracts all its pipe and puts it into the Output Hatch when it reaches the void. As a result, it is difficult to use it in the End since it reaches the void before it can finish mining its designated area. One way to fix this would be to have it mine every ore at its current y level in its designated area.

**Comment by Techlone** [comment]
@npawk12 you can calculate an amount of mining pipes. ODP will finish a process when pipes will be fully consumed.
