### ISSUE TITLE
StackOverFlowError w/ Thaucmcraft

### ISSUE THREAD

**Issue by TehHaloTree** [Blood-Asp/GT5-Unofficial#119]
Hey, I recently wanted to add GregTech (Specifically the GT5 Port) to resonant rise 3. After I added it (version 5.08.26) it crashes with a seemingly long string of code related to thaumcraft. I tested the same setup w/out GT, and it loaded just fine. Any help appreciated.

Crash Report:
http://pastebin.com/FjNC0gE7

Thanks in advance,
TehHaloTree

**Comment by Muramasa-** [comment]
I had a similar issue and it was due to a TC addon loading a different version of the TC API.

Try loading the pack with TC and GT without the TC addons to confirm it works with TC alone. Then add in TC addons until it produces the same crash,

**Comment by TehHaloTree** [comment]
Crash was replicated w/out and TC addons installed, including a couple that add extra TC content (Chromaticraft, Magic bees, etc.).

**Comment by Blood-Asp** [comment]
At last it must be some other mod involved. Likely some mod includes a old TC Api or so. I have seen this bug a few times allready and i know it was another mods fault. Just do not remember what mod it was.

**Comment by Muramasa-** [comment]
I think I remember the TC addon Witching Gadgets producing a similar error and that was due to a error with the TC API. So possibly a mod that is including the TC api that might not necessary be a "TC Addon" could be causing the error.

**Comment by TehHaloTree** [comment]
The only other mod I could think of that possibly includes an old API would be Blood Magic. Other than that, I don't think anything would bother with TC.

**Comment by Muramasa-** [comment]
Well the next thing I would try is to see if GT, IC2 and TC work by themselves.

If they do, then we know it's another mod causing the issue.

**Comment by Blood-Asp** [comment]
It seems not to be GT alone, so: Close
