### ISSUE TITLE
Server/client freezes and stops when alveary has territory upgrade in Electrical Stimulator block

### ISSUE THREAD

**Issue by Krysinski** [Blood-Asp/GT5-Unofficial#1198]
Server core: thermos (latest)
mc version: 1.7.10
forestry: 4.2.16
some from modlist: gregtech 5.09.29, binniemod 2.0.21
log: https://gist.github.com/Krysinski/fdbbf89922d7068f661a40f28eb5dec4
Before this error appeared, I placed a vanilla "marshy" princess and a "diamond" drone (GregTech) (drone created with special genes via Genetics) in "Alveary"
/mt hand with (white contour) item drone:

Forestry:beeDroneGE.withTag({MaxH: 20, Health: 20, IsAnalyzed: 1 as byte, Genome: {Chromosomes: [{UID1: "forestry.speciesDiamond", UID0: "forestry.speciesDiamond", Slot: 0 as byte}, {UID1: "forestry.speedSlowest", UID0: "forestry.speedSlowest", Slot: 1 as byte}, {UID1: "forestry.lifespanShorter", UID0: "forestry.lifespanShorter", Slot: 2 as byte}, {UID1: "forestry.fertilityNormal", UID0: "forestry.fertilityNormal", Slot: 3 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 4 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 5 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 7 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 8 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 9 as byte}, {UID1: "forestry.flowersVanilla", UID0: "forestry.flowersVanilla", Slot: 10 as byte}, {UID1: "forestry.floweringAverage", UID0: "forestry.floweringAverage", Slot: 11 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 12 as byte}, {UID1: "forestry.effectNone", UID0: "forestry.effectNone", Slot: 13 as byte}]}})
link with https://github.com/ForestryMC/ForestryMC/issues/1812

**Comment by draknyte1** [comment]
We don't support thermos.

**Comment by Dragon2488** [comment]
It's not thermos issue, asshole.

**Comment by Krysinski** [comment]
freezed world from server cant be loaded in single game:
[18:13:11] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[18:13:11] [Server thread/INFO]: Generating keypair
[18:15:27] [Server thread/INFO]: Preparing start region for level 0
[18:15:28] [Server thread/INFO]: Preparing spawn area: 22%
[18:15:31] [Server thread/INFO]: Preparing spawn area: 44%
[18:15:32] [Server thread/INFO]: Preparing spawn area: 67%
[18:15:33] [Server thread/INFO]: Preparing spawn area: 95%
and client hangs about 15 min and more....

**Comment by Krysinski** [comment]
We do some tests in single game:
1. Client hang also with pure forge
2. No matter wich bee used in alveary (not GT issue)
3. Game start freezing when alveary has a queen
4. the reason of issue is electric stimulator block in alveary structure with circuit installed. Circuit must make "territory upgrade".
Alveary was tested with:
- 4 stimulator block and 4 "territory" intricate circuits inside (1 lamp 50% * 4=200% for 1 circuit), so i guess 4 stimublock give 200 * 4=800% territory upgrade
- 4 stimulator block and 4 "flowering" intricate circuits inside
I suppose that "forestry.apiculture.flowers.FlowerRegistry.getAcceptedFlowerCoordinates(FlowerRegistry.java:174)" try to "calculate" every f*ckin flower at +800% area.
People say that wasnt issue before we update binniemod from old "last version" (with binnie patcher for forestry 4.2): binnie-mods-2.0-pre14
Please, close this issue for GT.

**Comment by Glease** [comment]
Can't you close your own issue?
