### ISSUE TITLE
Amplifabricator not working

### ISSUE THREAD

**Issue by AiwendilCiunio** [Blood-Asp/GT5-Unofficial#120]
Version 5.8.25

I tried LV and MV, 1-4 amps, it just doesn't work, neither with scrap nor scrap boxes.

**Comment by AiwendilCiunio** [comment]
Nvm didnt work in SP, works fine on server. Closing :P

**Comment by pyure** [comment]
Works fine for me in SP; tested it (and rest of replication gizmos) yesterday.
