### ISSUE TITLE
How to fill ic2 jetpack in gt5u

### ISSUE THREAD

**Issue by k1r0s** [Blood-Asp/GT5-Unofficial#1202]
Ethanol not working over basic canning machine
Also many other fuels

**Comment by Creeperologist** [comment]
biogas is still available and is the intended fuel

**Comment by k1r0s** [comment]
Basic distilery produces Ethanol, not biogas actually, but NEI shows two recipes with the same configuration (circuit == 1)

**Comment by k1r0s** [comment]
Now im trying to disable ethanol from forestry.. I'll update this

**Comment by k1r0s** [comment]
solved. There are two biomas types, that's all... sry
