### ISSUE TITLE
Can‘t get achievement

### ISSUE THREAD

**Issue by YoungGT** [Blood-Asp/GT5-Unofficial#1208]
(I'm not good at English,so if I have any mistakes in grammar,please forgive me.Thank you.)
GT version：5.09.31pre4
I put the raw materials of IC advance circuit into the circuit assembler,and the machine produced the circuits.But I didn't get the achievement(Step forward).I can't get the achievement by picking it up,either

**Comment by Antillar** [comment]
If the Achievement is written like this:
"Obtain/Produce/Create/smth X", put X in the inventory, drop it on the ground and collect it.
