### ISSUE TITLE
Supercondutors

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#121]
The superconductor can be painted and then dont connect with each other but there is nothing visually changed to see if it is painted.
Please change it so that we can either not paint them at all (and use plates) or add something visual to them.

gregtech_1.7.10-5.08.25

**Comment by Blood-Asp** [comment]
While i know it is annoying, this requires a change deep inside GTs rendering logic. I will not change anything there useless it is a really bad bug.

**Comment by Technus** [comment]
#https://github.com/GTNewHorizons/GT5-Unofficial/pull/4/commits/3a83a35433b95e3332b90f6da95d522b1d9798c7

This should solve the issue. Works flawlessly for all uninsulated wiring
