### ISSUE TITLE
crash gregtech 5.09.31 p2p tunnel

### ISSUE THREAD

**Issue by natzgzul89** [Blood-Asp/GT5-Unofficial#1213]
transmission of gregtech energy through the tunnel
https://paste.ee/p/VvPDj

**Comment by Antifluxfield** [comment]
rv3 changed the accessibility of some fields from protected to private...
You can use AE2-rv2 temporarily until someone fix it.

**Comment by leagris** [comment]
I would not advise using AE2-rv2 as it has a shit-load of unfixed critical bugs. That's unfair bug trading.
I'd suggest not using GT EU Tunnels at all or disabling it in configuration (hopefully it has been made an option).
Anyway, AE2 GT EU Tunnels are breaking Gregtech cable loss balance.
If you are going to play without cable-loss, you may as well switch enable RF to GT EU conversion, and use an ordinary AE2 RF Tunnel.

**Comment by Techlone** [comment]
>Anyway, AE2 GT EU Tunnels are breaking Gregtech cable loss balance.

This is not quite true. AE consumes more energy when it transfers GT or IC2 EU. It's about 5% of transferring EU/t.

**Comment by leagris** [comment]
> This is not quite true. AE consumes more energy when it transfers GT or IC2 EU. It's about 5% of transferring EU/t.

That you can feed with RF or anything easy from the AE Network.
In then end, you can even practically move GT EU Inter-dimensionally with AE dimensional bridge and have 0 EU Loss between a generator and tunnel destination.
1. This is overriding Gregtech EU Loss
2. This is overriding Gregtech microwave energy transmitter.
3. This is overriding need of Dragon Egg or Plasma for inter-dimensional energy transfer.

**Comment by SapientMC** [comment]
@leagris All that you listed could have been done before. All that was required was a IC Transformer at the output.

**Comment by natzgzul89** [comment]
in general it's crash out of the box.
and it's very bad.

**Comment by Blood-Asp** [comment]
@Dimach Seems you change did not work. Did kinda expect it but not the time to test it all. Will make this a default off config for now until it is fixed for sure.
