### ISSUE TITLE
Can't make IC carbon plate

### ISSUE THREAD

**Issue by YoungGT** [Blood-Asp/GT5-Unofficial#1222]

**Comment by Blood-Asp** [comment]
What exactly does not work? What GT version?

**Comment by YoungGT** [comment]
GT version is 5.09.31,and I can't see the recipe in NEI,put.the raw carbon mesh in compressor is useless,either.

**Comment by YoungGT** [comment]
I also deleted .minecraft/config folder,but either can't.

**Comment by Blood-Asp** [comment]
for me the recipes does show and it works fine too. I can only guess it is some mod conflict in you pack or some MT script. Maybe others reading here could also check if the recipe shows for them?

**Comment by YoungGT** [comment]
OK...It was my problem,but still don't know how it happend.
