### ISSUE TITLE
Galacticraft Compressed Steel is wrong?

### ISSUE THREAD

**Issue by adamcirillo** [Blood-Asp/GT5-Unofficial#1224]
The Galacticraft Compressed steel recipe takes you to the recipe for steel plates all other compressed metal items show recipes in Implosion Compressor.

**Comment by adamcirillo** [comment]
I've narrowed down the issue a bit seems the addon mod for galacticraft galaxy space is doing it as the mod just updated today and now nei shows the correct recipe but it outputs 1 tiny pile of ash instead of compressed steel and 1 tiny pile of ash. I think it might have to be fixed on galaxyspace end can you confirm?

modlist
galacticraft 3.0.12.502
galaxyspace 1.1.8
gt 5.09.31

**Comment by adamcirillo** [comment]
I spoke to the galaxyspace dev. He said the issue is not on his end as he told me he doesn't touch the compressed steel recipe? not sure if you have the chance to look at it? Here is a link to the open issue with him BlesseNtumble/GalaxySpace#181

**Comment by adamcirillo** [comment]
I've found the issue seems to be intermittent not sure what is causing it I also tested .30 still there.

**Comment by mura3277** [comment]
From reading the GS issue this does not seem to be caused by GT
