### ISSUE TITLE
[5.09.31] Unpackager does not return rubber from cables

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#1225]
![image](https://user-images.githubusercontent.com/14032818/30590900-eccd6ece-9d40-11e7-8384-19f045e22ff4.png)

**Comment by JohannesGaessler** [comment]
This change is intentional.
I introduced more than one type of Rubber and therefore removed the recovery from the unpackager.
If I hadn't it would have been possible to convert one type of rubber into another.
