### ISSUE TITLE
Assembling Machine Outputs 2 Heat Proof Casings

### ISSUE THREAD

**Issue by MineAnPlay** [Blood-Asp/GT5-Unofficial#1229]
Title says it all.

**Comment by Antifluxfield** [comment]
IIRC the recipe was changed intendedly in 5.09.28

**Comment by MineAnPlay** [comment]
Why though? It also allows you to dupe invar so infinite iron and nickel.

**Comment by draknyte1** [comment]
I bet nobody though of that.

**Comment by JohannesGaessler** [comment]
>The title says it all.

I disagree.
What the title for instance doesn't say is that you're a player of the GTNH modpack, which is balanced differently from regular GT5U.
Among other things, GTNH did not reduce the costs of multiblock Casings by half.
This was done by increasing the output of Casings in the crafting/assembling recipes from one to two.
The assembling machine recipe for Heat Proof Machine Casings was originally overlooked in these adjustments.
Later on the mistake was spotted and fixed.
In the current version of GT5U it is not possible to dupe invar via the assembling machine recipe of Heat Proof Machine casings.

What presumably has happened is that @Dream-Master has accidentally taken over the adjustment of the assembling machine recipe.
You then presumably spotted the wrong recipe in GTNH and opened an issue here.

**Comment by MineAnPlay** [comment]
Hmm sorry about :P. Should of checked further but I checked GTNH first and saw it then look at other multiblock casings and saw that they were 1 so checked GT5u and saw that Heat Proof was also one but forgot to check the other casings. Also can you please give a link of the change?

**Comment by JohannesGaessler** [comment]
I don't have a link, sorry.
