### ISSUE TITLE
[Bug] Peripherals++ ME Bridge can't read GT items's display names

### ISSUE THREAD

**Issue by Muramasa-** [Blood-Asp/GT5-Unofficial#123]
Hi,

I initially posted this as an issue on the Peripherals++ (CC Addon) gihub, but this bug is apparently to do with how GregTech handles it's items.

Original issue https://github.com/austinv11/PeripheralsPlusPlus/issues/104#issue-98907905

The ME Bridge can read all of the items in an ME system and compile the data into a ComputerCraft table. From there you can loop through that table and access information about the items like rawId, damage, amount and display name. Unfortunately when you try and print the display name of a GT item (In this case Olivine dust) it outputs: gt.metaitem.01.2505.name.

I'm really not sure how easy this is to fix, but I really hope it can.

Peripherals++ Version: 1.3.0 161
GT Version: 5.08.26

Thanks for your time.

**Comment by Muramasa-** [comment]
So apparently the ME Bridge can read the display names correctly in GT6, but not GT5. That is probably helpful fir finding the cause.

**Comment by Blood-Asp** [comment]
does it work in GT5.07.07? I wonder if that is a bug because of a change i did, or a change greg did on GT6 did that.

**Comment by Muramasa-** [comment]
Ill test it right now for you

**Comment by Muramasa-** [comment]
Can confirm that it does work in GT5.07.07
![image](https://cloud.githubusercontent.com/assets/7321570/9095828/67bdbed4-3bb1-11e5-83e9-b59d13141c9a.png)

**Comment by Muramasa-** [comment]
So I tested 5.08.07, 5.08.12 and 5.08.18 and the ME Bridge can read the display names.

**Comment by Muramasa-** [comment]
Confirmed fixed in 5.08.27. Feel free to close.

**Comment by Blood-Asp** [comment]
o.O 
I thought all my tries to find the reason did not work. Well maybe i was lucky.
