### ISSUE TITLE
Usage for Magic/Mana/Primal Mana (Ma)

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1233]
![issue](https://user-images.githubusercontent.com/12700019/30847143-1bc478be-a2a3-11e7-8072-55d86ddc925a.png)
1. Add new fluid with the name "Mana" or "Primal Mana" and fluid parameters close to these ones:
![mana](https://user-images.githubusercontent.com/12700019/30847194-4183adc2-a2a3-11e7-8946-c7a34625346c.png)
Note that it has to have the same fluid registry name to be unified with the Primal Mana from Thermal Foundation. Also add the cell of this fluid.
2. Add centrifuge recipes for the following items to obtain Ma (if there is already a recipe to obtain metal dust from magic metal dust, remove it):

- 3 Mithril Dust -> 2 Platinum Dust + 1000mb Primal Mana
- 3 Blaze Powder -> 1 Sulfur Dust + 1 Dark Ashes + 1000mb Primal Mana
- 5 Liveroot Pulp (or Dust) -> 4 Wood Pulp + 1000mb Primal Mana*
- 4 Shadow Iron Dust -> 3 Iron Dust + 1000mb Primal Mana*
- 4 Shadow Steel Dust -> 3 Steel Dust + 1000mb Primal Mana*
- 2 Steeleaf Dust -> 1 Steel Dust + 1000mb Primal Mana* 

3. Modify electrolyzer recipe for it to have mana in cells:
- 10 Enderpearl Dust + 6 Cell -> 1 Beryllium Dust + 4 Potassium Dust + 6 Primal Mana Cell + 5000mb Nitrogen

4. Add recipes in Mixer:
- 2 Platinum Dust + 1000mb Primal Mana -> 3 Mithril Dust
- 1 Sulfur Dust + 1 Dark Ashes + 1000mb Primal Mana -> 3 Blaze Powder
- 4 Wood Pulp + 1000mb Primal Mana -> 5 Liveroot Pulp (or Dust)*
- 3 Iron Dust + 1000mb Primal Mana -> 4 Shadow Iron Dust*
- 3 Steel Dust + 1000mb Primal Mana -> 4 Shadow Steel Dust*
I suggest making a requirement of 2048 EU/t for these.

5. Add recipes in Autoclave:
- 1 Steel Dust + 1000mb Primal Mana -> 2 Steeleaf*
I suggest making a requirement of 2048 EU/t for these.

6. Add a config rule allowMoreMagic_false=false or smth. Recipes marked with * should be available only if this config rule is set to true. Setting this rule to true should load additional materials during load stage, which extends the loading time. Therefore this option should be disabled by default, unless the player does want to play with these materials.

P.S. I am aware of the existance of the material called "Magic" with ID -128. The naming is up to the contributor who decides to include this suggestion (if there will be one).
P.P.S. I am also aware of the existance of 41 other magical materials which are not included here for the sake of time and can be included if asked for.

**Comment by mura3277** [comment]
"Magic" in GT does need to be made more interesting. Maybe even the magic energy converter can be changed to use some sort of magic gas rather than just throwing in random items?

**Comment by bHXDgiuMa5yLHyC8** [comment]
I think a very useful magic addition to GT would be a dowsing or geomancy system for finding minerals/underground fluids. For instance, a dowsing pendulum item which you could ask for the location of a specific mineral vein and it would say northeast, southwest, etc. could be made out of thaumium, koboldite, or manasteel.

**Comment by mura3277** [comment]
Adding to ideas: #654
