### ISSUE TITLE
Materials wrongly adressed to Thaumcraft

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1234]
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/loaders/materialprocessing/ProcessingModSupport.java
        if (!aEnableThaumcraftMats) {
            Materials.Amber.mHasParentMod = false;
            Materials.Thaumium.mHasParentMod = false;
            Materials.InfusedGold.mHasParentMod = false;
            Materials.InfusedAir.mHasParentMod = false;
            Materials.InfusedFire.mHasParentMod = false;
            Materials.InfusedEarth.mHasParentMod = false;
            Materials.InfusedWater.mHasParentMod = false;
            Materials.InfusedEntropy.mHasParentMod = false;
            Materials.InfusedOrder.mHasParentMod = false;
            Materials.InfusedVis.mHasParentMod = false;
            Materials.InfusedDull.mHasParentMod = false;
        }

1. Infused Gold was added by a small addon to IC2 and later to IC2E called [Unidye](https://forum.industrial-craft.net/thread/9820-addon-1-6-2-unidye-get-more-awesome-for-your-ic%C2%B2/). This addon was developed in 1.5.2 and 1.6.4 times and never made it to 1.7.10. Infused Gold never existed in Thaumcraft. This material needs to be disabled entirely or removed from the code.
2. Infused Vis and Infused Dull represent Vis Shard and Dull Shard - the shards only present in Thaumcraft 3 and below, which is no longer developed after 1.5.2. These materials are not present in Thaumcraft 4 - the only thaumcraft version for 1.7.10, so they need to be disabled entirely or removed from the code.

**Comment by draknyte1** [comment]
You do realize all this old code exists from GT2/3/4?
Greg has NEVER done a total rewrite, he has always ported forward and improved his existing code base.
Even GT6 was build from GT5 code, though overhauled as he went along..

**Comment by Antillar** [comment]
I do realize that Vis Shard and Dull Shard remain because of old mod versions. However, GregoriusT does not develop GT5U, so his ideas do not have to be followed.

**Comment by MauveCloud** [comment]
While we're at it, Amber should not be considered Thaumcraft exclusive - GregTech itself generates it in small ores.

**Comment by draknyte1** [comment]
It's not the fact we're following his ideas, it's the fact nobody ever bothered to change it because it does 0 harm.

I have NEVER seen GT generate small amber by default.

**Comment by Antillar** [comment]
I may be misunderstood in some of my requests. I do not insist on finding every possible place deprecated items take and wiping them from there. 
I do want to disable their reference, which extends the loading time, provided that Thaumcraft is installed. GregTech is not loading instantly, so any idea on making it load faster is worth considering imo.
On the other hand, I dislike seing unobtainable items in NEI, which are meant to be integrated with items from installed mods, but at some point fail at it.

**Comment by MauveCloud** [comment]
> I have NEVER seen GT generate small amber by default.

I have found small amber ore in GT 5.08, and https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/loaders/postload/GT_Worldgenloader.java#L91 shows it is supposed to still generate, but having it treated as Thaumcraft-exclusive in GT 5.09 might be interfering with that.

**Comment by MauveCloud** [comment]
Update: Just now, I found some small amber ore in GT 5.09.31, only it looked like a strange white-ish large ore, showed in WAILA as "gt.blockores.16514.name", and didn't drop any gem or dust.  I had to check WorldGeneration.cfg to confirm that 514 was amber.

**Comment by MauveCloud** [comment]
On a semi-related note, I'm wondering if this material disabling has eliminated the Liveroots and Steeleafranks crops, which were previously available without needing Twilight Forest to be installed, and still show up in the code:
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/loaders/postload/GT_CropLoader.java#L42-L43
but NEI doesn't show me seed bags for them.

**Comment by MauveCloud** [comment]
I got some screenshots this time, so here's what it looks like with BDCraft textures with amber enabled (I'm technically using a custom build with the line for amber in ProcessingModSupport.java commented out among other changes, but I'm fairly sure you can achieve the same effect with "EnableAllMaterials" in GregTech.cfg):
![2017-11-06_10 42 53](https://user-images.githubusercontent.com/8942955/32457841-4991d62c-c2df-11e7-8641-9deb31ddd0cd.png)
and with amber disabled:
![2017-11-06_10 47 45](https://user-images.githubusercontent.com/8942955/32458051-f3c8b5ca-c2df-11e7-91e8-07a5d2c63889.png)
Additionally, I've noticed that Biomes O' Plenty generates amber ore, but with GT amber material disabled, it does not unify to GT amber, and GT amber tools are not craftable.

**Comment by mura3277** [comment]
Summary of this issue:
- Enable Amber even if TC is not installed. Iirc, Amber was disabled because it has no real use in GT (at the time, haven't kept up with changes). However it probably makes sense to enable it so there isn't broken ore blocks.
- Disable Infused Gold, Vis and Dull by default

**Comment by MauveCloud** [comment]
I know of one use for amber in GT, though I'd be hard pressed to claim it as significant enough by itself to justify enabling amber: it can be used for making tools with silk touch.  Of the materials that are not reliant on other mods, I think the only other one that can provide silk touch is nether star.

**Comment by mura3277** [comment]
Very good point @MauveCloud

**Comment by leagris** [comment]
Shards are also a good source of lenses for cheaper than olivine, emerald, ruby or blue sapphires.

**Comment by draknyte1** [comment]
Shard veins never generate by default though. 

So they're pointless to have enabled without TC..

**Comment by Antillar** [comment]
@Muramasa- 
Amber can be enabled by default, it makes Silk Touch tools and ASoC lense.
Infused Gold has to be removed from Thaumcraft group of materials and disabled. Or the recipe for infused gold dust can be added the same as it was in Unidye. This makes it logical to enable Infused Gold by default.
Vis and Dull shards can technically be removed from Thaumcraft group of materials and disabled, or left to be there.
