### ISSUE TITLE
Config Requests

### ISSUE THREAD

**Issue by redmage17** [Blood-Asp/GT5-Unofficial#1235]
I would like to request a config for the changes that gregtech does to vanilla recipes as well as other mods. 

In addition I would like a config removal of shapeless recipes of ingots into metal blocks and vice versa. 

I am trying to get more people into gregtech and I've scripted a few things but I just can't figure out how to make this commit myself. The main thing with the crowd I have been working with is the forced usage of gregtech early on.

**Comment by redmage17** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/loaders/oreprocessing/ProcessingBlock.java#L18-L30 this is the line for the ore compression I believe

**Comment by leagris** [comment]
> I am trying to get more people into gregtech and I've scripted a few things but I just can't figure out how to make this commit myself. The main thing with the crowd I have been working with is the forced usage of gregtech early on.

I hear you on this specific quest to make Gregtech more accessible.
Lots of scripting efforts have been put into mod-packs like Beyond-Reality to re-balance Gregtech for a larger audience. Unfortunately I don't have the modding knowledge to even propose codes changes, not even what you asks for.

I wish you get the developers here, listening to your one more voice, to make Gregtech more accessible to the average or casual player: Makes stuffs less time consuming, less grindy, and at least, keeps such as optional changes.

**Comment by MauveCloud** [comment]
@redmage17 it looks to me like you already added this config in this commit: https://github.com/Blood-Asp/GT5-Unofficial/commit/45a2057b69ef0942d6c9fdf423d98aff1b78202d

Can this issue be closed now?

**Comment by redmage17** [comment]
This is ancient closing
