### ISSUE TITLE
water missing in recipes

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#1236]
https://youtu.be/97D3RETdLjo

**Comment by JohannesGaessler** [comment]
This behavior is intentional.
Since having a Water output can be more bothersome than actually useful, I have added the option to void the Water output of recipes.
This is controlled via the Programmed Circuit in the recipe (config is increased by one when voiding water).

**Comment by bear989** [comment]
so rather than showing a proper chemical process and making the player find a proper solution of disposing of the waste water you just have a program circuit that does there work for them? what is this Thermal Expansion!

**Comment by leagris** [comment]
> what is this Thermal Expansion!

No it is a fantasy game that's very far from reality.
That realism level as to dispose of water is what kills Gregtech by boring players away of it.
