### ISSUE TITLE
[Proposal] Multiblock fishfarm

### ISSUE THREAD

**Issue by richardhendricks** [Blood-Asp/GT5-Unofficial#1237]
I love building multiblock machines, and I think a fishfarm would be an excellent GT multiblock.

This multiblock is flat, only 1 tall, but can be X*Y, with X and Y = 3-9.

Needs
Fishfarm controller block
Power input hatch - LV or higher
Input hatch
Output hatch
Fish cages - Fish cages must be placed over water source blocks. Cages over non-source blocks do not produce output.

Power usage depends on the number of fishtanks. I propose 5 Eu/tank. 3x3 would work in LV, 9x9 would require HV.

Input hatch provides fishmeal, created by mixing sand, biochaff, and water. Maybe add protein sources like rotten flesh, meats, soy.

Output is ticked once per 30 second (determined by power hatch level), and 0-2 fish is produced per valid fish cage. Since this is a farm, fish only are produced, no other catch. Maybe support a slot in the controller for the type of fish to produce, if different fish produce different products  Fish breeding would be an interesting mod, but probably too close to bees.

A great follow on would be an infernal fish farm, high tier, only works in the Nether over the lava ocean, returns special fish that can be macerated into magma cream or blaze powder or ghast tears. Be careful breaking blocks, or else they'll disappear into the lava!

**Comment by mightydanp** [comment]
fish farm that needs power. haha

**Comment by richardhendricks** [comment]
This is industrial scale fish raising, so a little bit of power is appropriate. We could be really intensive and require oxygen to keep the cages oxygenated, and produce some kind of waste/fertilizer.

**Comment by richardhendricks** [comment]
The idea is that the farm can be used to produce fish -> fish oil -> biodiesel, as well as fish for player food.

**Comment by richardhendricks** [comment]
Could also produce some amount of pollution, if it gets bad water no longer supports fish.

**Comment by draknyte1** [comment]
Implemented via https://github.com/draknyte1/GTplusplus/commit/de8d2d77650c0372783bde24f913c713b012268b.
