### ISSUE TITLE
sapplings to plantball  in compressor

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#1239]
recipe missing in NEI

**Comment by bear989** [comment]
forestry saplings dont work in the compressor, minecraft sapling works just dont have the recipe in NEI

**Comment by MauveCloud** [comment]
Really?  Vanilla Minecraft saplings don't work for me in the compressor.  IC2 without GregTech uses the crafting table to make plantballs, and GregTech removes most of those recipes (except wheat, possibly to compensate for having it compress to a hay bale and pulverize to flour) in favor of either the compressor or macerating directly to bio chaff (the latter is already possible in IC2 without GregTech, looking at the internal config files, though GregTech removes direct maceration of melons/pumpkins to bio chaff).  The exceptions seem to be saplings and sugar cane (aka reeds) - if I don't add a MineTweaker/CraftTweaker script for them, I don't think there's a way to get bio chaff (or plantballs) from them.  Well, unless you count fluid extracting the wood pulp after pulverizing some saplings, but that's only a 1% chance per wood pulp.

**Comment by jaskarth** [comment]
This has been fixed in the latest release; I made a PR to fix this and it has been merged. (someone close this issue please)
