### ISSUE TITLE
weird crafting behaviour

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#124]
https://www.youtube.com/watch?v=cIDmU4FW-rc&feature=youtu.be

logisticspipes-0.9.2.19
gregtech_1.7.10-5.08.25
NotEnoughItems-1.7.10-1.0.5.111-universal

https://github.com/RS485/LogisticsPipes/issues/769#issuecomment-127971513

**Comment by Blood-Asp** [comment]
Not possible for me to change anything on that. GT Items get added a NBT tag on crafting that NEI/LP does not know of. I do not know if there is a way in LP to ignore the NBTs the right way. AE2 at last does that.
