### ISSUE TITLE
[5.09.31] Gregtech-NEI crash on a modpack

### ISSUE THREAD

**Issue by Georggi** [Blood-Asp/GT5-Unofficial#1241]
https://pastebin.com/gfbg6tBh
Used latest commit available at this time.
Link to modpack if anybody wants to test, only need to update gt there: https://github.com/mineproject/pack

**Comment by Georggi** [comment]
OK, GTTweaker doesn't properly handle old recipes it seems, not GT issue I guess.

**Comment by Georggi** [comment]
It seems null in output stack for chemical reactor causes this, might be gt issue so I am reopening it.

**Comment by mura3277** [comment]
This was quite possible caused by an incorrect recipe. It's possible that it's been fixed now. Feel free to reopen if it's still an issue.
