### ISSUE TITLE
[5.09.31]Recipe error in chemical reactor

### ISSUE THREAD

**Issue by alekseyKoD** [Blood-Asp/GT5-Unofficial#1243]
Hi. I found an error in the chloroform recipe  in the chemical reactor.
If you use 6 cell with chlorine and 1000 mb of methane with prog. circuit N3. On the output we get 1000 mb chloroform, 3 cell with HCl and one empty cell. Two cell disappear.
![2017-10-08_00 06 44](https://user-images.githubusercontent.com/15108870/31379840-1631024c-ade2-11e7-9da5-3fd822e90caf.png)

**Comment by jaskarth** [comment]
I fixed that issue see #1261
