### ISSUE TITLE
Assembler recipes for pump covers

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#1248]
Nearly all GT items that require tools when made via crafting table have alternative paths for making them in machines that don't involve using up tool durability.  5.09.21 added assembler recipes for rotors, but pump covers still had to be made in the crafting table, possibly because they had too many distinct parts for the assembler.  However, 5.09.31 now has assembly machines with 6 input slots, which should make it possible to have assembler recipes for the pump covers.  As far as I can tell, there are no existing assembler recipes that use two or more of the components for pump covers to make something else.

**Comment by leagris** [comment]
Fixed in dev, since Pumps are assembled in the Component Assembler

**Comment by draknyte1** [comment]
Actually, both the component assembler and the recipes for all machine parts are content added by GT++. Component assembler exists for compat. With existing recipe conflicts and allows for .07/08 support.

**Comment by MauveCloud** [comment]
I'm not sure why this issue was left open, since merging PR #1487 addressed this a bit over 2 years ago, no longer GT++ exclusive, but I'm closing it now.
