### ISSUE TITLE
Wrong recipe for Dimethyldichlorosilane

### ISSUE THREAD

**Issue by Sinigr38** [Blood-Asp/GT5-Unofficial#1250]
Found recipe that allows you to receive capsules from nothing.
![2017-10-16_21 13 05](https://user-images.githubusercontent.com/9046176/31616917-944798de-b2c0-11e7-9c74-f533f5e27f9b.png)

**Comment by draknyte1** [comment]
Im not sure what is even being made here..

**Comment by jaskarth** [comment]
See #1261 I fixed that bug, it's in a pull request
