### ISSUE TITLE
Useless chipped gems and arrows => machine gun?

### ISSUE THREAD

**Issue by GreenCat1988** [Blood-Asp/GT5-Unofficial#1257]
I had noticed, that arter crushing any gem, you get flawed gems, which could be only crused second time into chipped gems.  And chipped gems could be crafted oly into GT arrow heads. Strict way to produsing tons of arrows. I have never seen anybody using them. NEVER. Bow and arrows just too boring for industrial     players. Tons of work to craft arrows a little better, than crafted from flint.
Is it possible to convert arrow heads into bullets and add tierable gun (from steel single shot to neutronium machine gun)?

**Comment by Antillar** [comment]
1 Gem -> 2 Flawed Gem -> 4 Chipped Gem
1 Gem -> 1 Dust
2 Flawed Gem -> 1 Dust
4 Chipped Gem -> 1 Dust

**Comment by MauveCloud** [comment]
@Antillar you forgot to mention 4 dust + explosives (in imposion compressor) -> 3 gems

**Comment by GreenCat1988** [comment]
May be I wasn't careful enough to find recipe for converting flawed and chipped gems into dust in NEI. My fault:( But tons of unused GT arrows are still at the place.

**Comment by leagris** [comment]
> But tons of unused GT arrows are still at the place

Skeletons would contradict your.
They love shooting radioactive GT arrows at poor Steve.

**Comment by jaskarth** [comment]
I would prefer a crossbow, as a machine gun isn't in the style of Minecraft. Or, preferably better make GT crossbow bolts from GT arrows that can be shot from TConstruct crossbows.

**Comment by mura3277** [comment]
Adding to ideas: #654
