### ISSUE TITLE
Circuits complaint

### ISSUE THREAD

**Issue by tomasbrod** [Blood-Asp/GT5-Unofficial#1262]
I am pleased that electronics parts were implemented into GregTech as precursors to circuits. I like the silicon waffle doping and processing chain. Also like that you can't just assemble your boards in hand, you need some kind of solder station, which the Circuit Assembler fills at lower tiers (could be renamed). Also the idea that you can use high tier machines to manufacture cheaper circuits for lower tiers is very good and encourages industrial progress.
However I don't like few things:

There are way too many circuits which are used mostly randomly in recipes. Yes I understand that there is a concept of tiers, but Why I need high performance Workstation (32 RAMms, 12 CPUs) to power a Electric Furnace and at the same time use primitive circuit made from 4 discrete parts to control Precision Laser Engraver's stepper motors and LASER? Selection of circuit for machine should consider requirements on the circuit eg: High power switching, precision control, timing critical, complex computation.

Not enough parts. There are only few basic parts and they do not evolve. In the game there are only two variants of parts, Normal (THF) and SMT while more could be used. Take for example (power) switching components: tubes and small transistors can't switch much, for low and medium level machines Relays could be used, I can already see two tiers of relays (small/powerful). To unlock higher power and save resources on low, thyristors, IGBTs and Solid state relays could be used.

Capacitors are sensitive to voltage, so there should be caps for every machine voltage levels. And they are parts that should be added to pretty much every circuit. In low tech they are part of the logic and on create suitable power for Chips in higher tiers.

Silicon chip manufacturing goes to Sci-Fi levels too fast. In addition to SoCs, CPUs and RAMms, player should be able to Engrave (diffuse) discrete silicon parts in bulk.
The level of the engraver and quality of raw wafer should determine how complex patterns can it diffuse.
lv1: transistors, diodes
lv2: lv1 + Integrated logic, thyristors, MOSFETs, IGBTs
lv3: lv2 + CPUs, RAMms, NB (support chip for CPU, as CPUs can't operate on their own)
lv4: lv3 + SoCs (cpu+ram+nb in one chip, saves material), ...

Engraved wafers can't be used directly. They must be first cut like it is already implemented, AND packaged into plastic. Since we have multiple tiers of assemblers, SMD parts are more difficult to soldar than THF, so they should require more advanced assembler and BGA parts (chips) even more advanced. SMD parts are small, and complex circuits often require many resistors. There is nothing wrong in requiring up to 30 of them per circuit.

I know that mechanics must be adapted for the game, but I hope that we can refine this inputs into implementable form. That will be all for today, next I will look at different machines and try to estimate their circuit requirements.

**Comment by jaskarth** [comment]
I completely agree with all of these changes. However, won't this break existing circuit setups and require extensive rewiring and re-automating?

**Comment by tomasbrod** [comment]
Yes, I guess if player has circuit auto-crafting setup, players will have to rebuild the automation, but not much more than 5.09.28 had to.

**Comment by tomasbrod** [comment]
In addition to Tiers machines can be logically separated by complexity. A simple machine should require only one circuit in it's recipe, however components can have additional circuits. First let's define which machines are considered simple. Machine is considered simple when it's physical counterpart does not require complicated or precise control (ignoring the ItemStack mechanics). 

Compressor, Electric Furnace, Extractor, Macerator, Wiremill, Brewery, Fermenter, Distillery, Polarizer, Mixer, Forge Hammer, Fluid heater, Sifting machine, Electric Own, Combiner, Pump, Battery Buffer, Alloy smelter, Canning machine, Fluid Canner, Fluid Extractor, Autoclave, Diesel Generator, Gas Turbine, Steam Turbine

Simple machine at tier T requires a Simple Control Circuit of tier T composed of following:
* 1x switching element (T+0)
* 1x switching element (T-1)
* 4x resistor
* switch / sensor
* board (T)
* when crafting on hand
  * 3x 1A wires (T)
  * item casing
* when crafting in assembler
  * solder (solder alloy / tin / lead)
  *  2x 1A wires (?)

Switching components:
* Basic Relay (32V, 128V)
* Good Relay (512V)
* TRIAC (512V, 2kV)
* Advanced TRIAC (8kV)
  - technology advancements allow you to manufacture better version
* Power MOSFET (32V, 128V)
  - cheaper than relays, but require higher tech
* Solid State Relay / IGBT (512V, 2kV)
  - relay alternative in higher voltage range
* SiC MOSFET (8kV, 32kV)
  - approaching energy density levels that should not even be possible
* Something Sci-Fi (128kV, 512kV, 2MV)
  - need someone creative to invent better name

note: some machines from the "simple" group could be moved to a "low-power" group, which requires even lesser circuits


~~This is the rest of the machines: Assembler, Bending machine, Lathe, Microvave Own, Printer, Recycler, Scanner, Electrolyzer, (un)Packager, Fluid Solidifier, Extruder, Rock Breaker, Disassembler, Mass fab, Amplificator, Replicator, Precision Laser Engraver, Slicing Machine, Cutting machine, Centrifuge, Thermal Cent, Ore Washing, Chem Reactor, Chemical Bath, Magnetic Separator, Forming Press, arc furnace, plasma arc furnace, miner, battery charger, magic energy converter, magic energy absorber, monster repellator, seismic prospector, curing own, circuit assembling machine, buffers+filters stuff~~

(The game mechanic slightly complicates the design. All gregtech machines support auto output without conveyor module, turn themselves on and off without item detectors and are able to process whole stacks of items automatically. The circuit complexity should correspond to complexity of the machine, but player must still be able to craft lower level machines. Requiring player to turn on/off machines manually would be a major annoyance on the other hand removing the auto output capability and reducing the input stack size of LV an ULV machines is viable.
The machine tier system is not ideal. Feeding more than 512 V into a single block is weird. On the other hand, machines which use high voltage physics (eg Plasma furnace) should not operate on voltages below 512 V.)

**Comment by draknyte1** [comment]
> Implying we'd recode the entire game at the end of its life?

**Comment by tomasbrod** [comment]
closed in consistency with my other "ideas" thread
