### ISSUE TITLE
Extraction of Biomes O' Plenty Flowers

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#1266]
Companion issue: #170 Extraction of EXBL flowers

Main issue is: Gregtech modifies all flowers to dye workbench recipes output to 1 dye instead of 2 dyes.
But it only adds static extraction recipes from vanilla and EXBXL flowers for 2 dyes.

I propose to automatically add extraction recipes within the same loop/process that modifies those workbench recipes for dyes.

**Comment by mura3277** [comment]
Adding to ideas: #654
