### ISSUE TITLE
complaint, idea for cracking

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#1268]
the cracking unit should be the best way for cracking but as it is there is a 200L gain for using it at a 30K eu cost and a lot of stainless to make in the first place. all levels of cracking can now be done in the chemical reactor at LV but the cracking unit takes HV. the idea witch is from netmc is that if your gonna do all levels of cracking in LV then you should have to do it in steps, so you would need to run 3 reactors to get the severely cracked that gives the best ethylene witch is probably what we are wanting from the cracking and that would get the power usage up as well. my suggestion is to only allow the severely and moderately cracked in the cracking unit, save the best outputs for the best option to use.

**Comment by jaskarth** [comment]
yes and we can up the cracking to needing mv, as well

**Comment by mura3277** [comment]
Assuming this was fixed by cracking followup 2
