### ISSUE TITLE
[Suggestions] DataStickDisplay, BetterMuffler, WireDiode, Generator Array

### ISSUE THREAD

**Issue by bartimaeusnek** [Blood-Asp/GT5-Unofficial#1273]
1. Make a single block that displays whats on Data Sticks, so we dont have to make trillions of books while searching for oil.
2. Active-Scubber-Muffler-Hatch that requiers Air Filters but reduce pollution to 0.
3. Wire-Diode, let energy only flow in one direction, so no more cableburn. Takes 5% of energy flowing thou that cable, if energy is emmited from the wrong side, it will break.
4. Generator Array, same like processing array, but for generators, allowing higher efficiency and easier mid/late game.

**Comment by MauveCloud** [comment]
> Make a single block that displays whats on Data Sticks, so we dont have to make trillions of books while searching for oil.

I like this idea, though last I knew oil drilling was nerfed to near-uselessness anyway - see #1238.

> Active-Scubber-Muffler-Hatch that requiers Air Filters but reduce pollution to 0.

Blood Asp has refused to add ways to actively reduce pollution (here: https://forum.industrial-craft.net/thread/11488-gregtech-5-1-7-10-forge-1355-unofficial-but-approved-port-stable-even-gt5-experi/?postID=204262&highlight=pollution#post204262 ), though EBFs now allow an output hatch next to the muffler hatch to reclaim certain gases, and GT++ has scrubber machines.

> Wire-Diode, let energy only flow in one direction, so no more cableburn. Takes 5% of energy flowing thou that cable, if energy is emmited from the wrong side, it will break.

Doesn't the shutter module already work for this?

> Generator Array, same like processing array, but for generators, allowing higher efficiency and easier mid/late game.

Isn't this what the large gas/steam turbine and large diesel/plasma generators are for?

**Comment by bartimaeusnek** [comment]
First of all thank you for your additions to this. The first one could be used for Ore Searching aswell, certain modpack with ultra rare veins would profit from it. The second, well okay. The third didnt know that was possible. Fourth, well kind of, but imagine 64Naq Gens in a 3x3x3 Block, or single block generators from additional mods(like GT++) in one space.

**Comment by draknyte1** [comment]
Refer to https://github.com/draknyte1/GTplusplus/issues/152.
