### ISSUE TITLE
Oil duplicate loaded

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1274]
![image](https://user-images.githubusercontent.com/12700019/32415646-f0efdcf8-c24d-11e7-9361-3263ceb4790d.png)
This is a duplicate oil that for some reason is loaded along with normal oil. It is missing a texture and is unobtainable. It is used in the same distillation recipes in Distillery and DT as normal oil does.

**Comment by Blood-Asp** [comment]
Oil Galacticraft. So it should only load if galacticraft in the pack and be there for compatibility.

**Comment by Antillar** [comment]
Why is it not unified to normal oil? GalactiCraft is indeed in the pack, but it is unified. This oil cannot be used by GC

**Comment by Blood-Asp** [comment]
thats something you have to ask the GC Devs. I know it was in the past unified with Buildcraft oil(that GT does uniy with too) but then intentionally split off with their own version of oil.
