### ISSUE TITLE
Suggestion: Flexibility for oil crackers

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1278]
Currently Oil Cracking Unit (OCU further) requires hydrocarbons to be inserted and extracted from sides (left and right), this is ok. H2O^ and H2^ can be inserted in the middle ring. This also makes sense. But what else does a player need to fit in the middle ring?
* Controller
* Maintenance Hatch
* Energy Hatch
* and adding previously mentioned Input Hatch

Overall there are 4 neccessary interactive blocks in the middle ring, which by itself only contains 8 blocks.
The side rings, however, have only 1 Hatch on them out of 9 blocks they consist of.

I suggest allowing more flexibility for OCUs in the following details:
* Allow Maintenance hatch to be placed on side ring of casings.
* Allow Energy Hatch to be placed on side ring of casings.

What this allows:
* Players can now have only 2 necessary blocks on each ring: Input Hatch/Output Hatch + Maintetance Hatch/Energy Hatch on one side ring and the rest on the other, Controller and Input Hatch for Hydrogen/Steam on middle ring.
* All I/O blocks along with Maintenance Hatch and Controller can be placed on 1 Y level - the middle level. And they can be placed so they do not touch each other. Also they can be placed to face only front and back sides of the machine (the ones 5 blocks long).
* Due to these blocks placable all in one heigth level, the OCUs can be independently stacked vertically, as top and bottom layers will contain none of interactive blocks, and therefore the machines are independent as they only share coil blocks and casings.

**Comment by bear989** [comment]
I disagree as there is plenty of room in that center block for all you need there why change it? The center is where the work is being done so that is where the power needs to be and maintenance would be needed.

**Comment by Blood-Asp** [comment]
One thing to add for flexibility would likely be processing direction. so that input/output can be placed on either end, but only one a time. I just left that out when adding the multiblock because the code already became quite complex.
