### ISSUE TITLE
Deactivating recipes over Recipes.cfg

### ISSUE THREAD

**Issue by Namarius** [Blood-Asp/GT5-Unofficial#128]
Deactivating Recipes over Recipes.cfg does not work for pulverizing and maceration but works for rock crusher.
I have tested this with field generators. I've changed all occurrences of B:gt.metaitem.01.32670_true=true to B:gt.metaitem.01.32670_true=false.

Any ideas?

**Comment by Blood-Asp** [comment]
Works just fine.
You must not only change every true=true into true=false, but also all with numbers into 0. for example:
      I:gt.metaitem.01.32670_48=48 into  I:gt.metaitem.01.32670_48=0
