### ISSUE TITLE
Fix for uselessness of Oil Cracking Unit

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1282]
Currently Oil Cracking Unit is useless for the folowing reasons:
1. Cracking can be done in Chemical Reactor.
2. Cracking can be done in LCR.
3. This machine occupies almost twice as much space as LCR.
4. This machine is more expensive than a Chemical Reactor at LV or MV or HV (the machine is HV-tier).
5. There are no losses in production values when cracking in any other machine.

The last reason is the one I suggest to change. 
As the OCU is the machine specially designed for cracking hydrocarbons, it should be more efficient than other machines at this job.

I suggest nerfing the amount of resulting fluid to 70% or 80% of the non-cracked fluid when cracking NOT in OCU. 

Bear has suggested another solution, which does not fully cover the problem in my opinion, but also worth considering. This is the link to his issue: https://github.com/Blood-Asp/GT5-Unofficial/issues/1268

**Comment by JohannesGaessler** [comment]
>I suggest nerfing the amount of resulting fluid to 70% or 80% of the non-cracked fluid when cracking NOT in OCU.

Cracking in a (Large) Chemical Reactor currently runs at 80% efficiency.
