### ISSUE TITLE
Radiation

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#129]
Carrying Quad Fuel Rod (Thorium) without the hazmat suit does not give you radiation.

gregtech_1.7.10-5.08.26

**Comment by pyure** [comment]
I figured it was intended since thorium is supposedly lower radiation to begin with.

**Comment by DarknessShadow** [comment]
It might be lower but 1/5 energy output so i think its 1/5 radiation which is still quite alot.

**Comment by Blood-Asp** [comment]
Thorium dust is not radioactive, so putting it into fuel rods should not change that suddenly. Depleted rods on the other side are.
