### ISSUE TITLE
Pump freezes the server in large oceans.

### ISSUE THREAD

**Issue by Buuz135** [Blood-Asp/GT5-Unofficial#13]
It happens when the pipe just touches the ocean

**Comment by Blood-Asp** [comment]
The pump does not freeze, but creates a massive lag.

A IV Pump scans an 512x512 block area while going down. That are 262,144 Blocks. Also most likely not all chunks have been generated at that point making it even slower. While testing, a HV Pump made about 25-30sec lag, A IV Pump needed whole 8 minutes.

Changed the range the pump can work in to something smaller: 8*(2^tier) -> 10*(1.6^tier). This way a IV pump made about 10sec lag while testing and the pumped area is still exremely big. (About 3x the area the advanced pump in GT4 could pump) Also the lower tier pumps are not that much nerved.
