### ISSUE TITLE
Tool breaking sound randomly

### ISSUE THREAD

**Issue by mightydanp** [Blood-Asp/GT5-Unofficial#130]
When i load gregtech up on the newest version everytime i join a world i can hear a random tool breaking effect/ gregtech noise

**Comment by JasonMcRay** [comment]
If you have Extra Utilities installed then downgrade it to 1.2.6

**Comment by Dream-Master** [comment]
The Tools sounds seems to be the Vanilla Anvil Sound and some IC Drill Sounds.
I posted the error in NEI and in Extra Utilities. It seems that RWThema ignore the issue tree.

https://github.com/rwtema/extrautilities/issues/687
https://github.com/rwtema/extrautilities/issues/671
https://github.com/Chicken-Bones/NotEnoughItems/issues/256

**Comment by atomicpulsz** [comment]
Is there another fix for this, or can I only downgrade?

**Comment by mightydanp** [comment]
I dont think any current version fixes  this so you might have to downgrade

**Comment by Dream-Master** [comment]
@mightydanp send me an email i send you the link to the ressourcepack we made

**Comment by draknyte1** [comment]
What versions of mods do I need to fix this? Using GT 5.8.33 & ExU 1.2.12 but am still getting it.
