### ISSUE TITLE
turbine rotors

### ISSUE THREAD

**Issue by Ujinok** [Blood-Asp/GT5-Unofficial#131]
I built such system: large steel boiler and large steam turbine, connected by huge stainless steel fluid pipe. The boiler produces approximately 24000 L/sec. When i use rotors with optimal steam flow less then 24000 L/sec, energy output matches  equation  (optimal flow/20)/2. For example, large stainless steel rotor (21000 L/sec), gives 525 eu/tick (nominal) or 630 eu/tick (real output, eff. 120%). But with more power rotors (large and huge turbine rotors) this formula breaks and real output is defined only by the type of dynamo hatch. For example, in the case of huge bronze rotor (24000 L/sec) HV dynamo hatch gives 2048 eu/tick, IV dynamo hatch gives 8192 eu/tick and so on. And this output is regardless of rotor material. But that bug occurs only when steam input is less than optimal steam flow. If i put another large steel boiler tu produce 48000 L/sec, turbines work normally. 

Moreover, some rotors lose their durability too quickly. Among them large aluminium and cobalt brass rotors. For aluminium rotor durability may decrease from 38400 to 35000 during few minutes. GT 5.08.26

**Comment by pyure** [comment]
This is already addressed in dev and in testing for a pending version.

**Comment by Blood-Asp** [comment]
Durability loss is dependend on output, so thats why the damage is soo high. Also aluminium has quite low dura.
