### ISSUE TITLE
Suggestion: Binnie's Mods integration: Acid and Poison.

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1312]
There exists the following fluid added by the Binnie's Mods mod, by ExtraBees part of it, to be precise. 
![image](https://user-images.githubusercontent.com/12700019/33519542-dd9bf160-d7b9-11e7-8541-d20c4984f200.png)
This fluid is only produced by the branch of one of the hardest to breed bees. It is obtained in small amounts from the Acidic Drops these bees produce in their combs. Unfortunately, it has no usage at all, it cannot even be placed in world.

My suggestion is to unify this Acid with Sulfuric Acid from GregTech. 

Advantages:
* Finally the usage for this particular fluid.
* Alternative way of Sulfuric Acid production without the need of obtaining and processing SO3 and/or H2S.
* It is always better to have more links between different mods as it usually increases the comfort and playability of the modpack.

Disadvantages:
* Possible problems while coding this, as it might be required to overwrite the fluid registry name. It generally depends on the way this unification is being done, provided that it is being done by someone at least.

**Comment by Antillar** [comment]
https://github.com/ForestryMC/Binnie/issues/364

**Comment by Blood-Asp** [comment]
There exists no fluid "unification" only mods using the same fluid. If you request changing the fluid registration, that would be a breaking change that is not recommended.

The only real "alternative" i see here is to add compatibility by conversion recipes.

**Comment by Antillar** [comment]
I have suggested the mod author to change the fluid registry name on his side. Until this is done, the conversion recipes seem to be the easiest option.

* Distillery for **acid** into **sulfuricacid**
* Brewery for **poison** into **potion.poison**

**Comment by mura3277** [comment]
Adding to ideas: #654
