### ISSUE TITLE
GT6 Style Pipes - Misrouting

### ISSUE THREAD

**Issue by mitchej123** [Blood-Asp/GT5-Unofficial#1313]
Preface: I haven't specifically tested on this repository; however I believe the downstream GTNH repo has basically the same code.  Also reported at https://github.com/GTNewHorizons/GT5-Unofficial/issues/59

I've been playing with a self compiled version (from the GTNH fork) from github and noticed the GT6 style pipes mis-route items when adjacent to a machine/chest.

In the image below, I'd expect the items to route from 1 --> 2 --> 3 (green path).  
However, without any paper between the pipe and 2, the items will route 1 --> 2 --> 2 (red path).  

If I paper the pipe or the chest buffer, it will then route 1 --> 2 --> 1 (pink path)

![pipe misrouting](https://user-images.githubusercontent.com/1894689/33521539-3c1fbebe-d789-11e7-9b40-c7a339f052da.png)

**Comment by Dream-Master** [comment]
@antifluxfield any idea ?
