### ISSUE TITLE
Can't make rubber without rubber

### ISSUE THREAD

**Issue by sjh26** [Blood-Asp/GT5-Unofficial#1317]
I'm running 5.09.31, IC 2.2.828, NEI 1.7.10-1.0.5.120.  Using sticky resin in the steam extractor gives raw rubber dust, which requires a chemical reactor to creating molten rubber, then a fluid solidifier to get solid rubber.  I can't seem to find a pathway to making rubber that doesn't eventually use a machine that requires rubber rings to craft?  Is this a bug or is there a recipe I am missing?

**Comment by draknyte1** [comment]
An LV Chemical Reactor does not require rubber to make though?

**Comment by sjh26** [comment]
Bronze alloy smelter has no recipe using raw rubber dust or sticky resin ( at least it doesn't for me)

**Comment by sjh26** [comment]
Nope, LV chemical reactor doesn't use a pump in its recipe.  So i have molten rubber, but can't do anything with it.

**Comment by sjh26** [comment]
Nevermind.  I think there is an issue with the NEI I am using, and it is not showing all recipes.  Apparently there is a pump version that uses a paper ring instead of rubber.

**Comment by bear989** [comment]
you dont need rubber at LV carpet and string, and put the molten rubber into an assembler
