### ISSUE TITLE
[5.09.32pre1] Some Wrought Iron Item Pipe has no extruder recipe

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#1320]
Large one for example.

**Comment by draknyte1** [comment]
You CANNOT extrude wrought iron. 
It becomes normal iron if touched by heat. It cannot have extruder recipes.

**Comment by leagris** [comment]
Then the Huge Wrought Iron Pipe should be removed entirely because it has no recipe.

**Comment by draknyte1** [comment]
Or just be like me and implement shaped recipes. 

While I suggested wrought iron as a material, I didn't think about this. But it seems nobody else did either >.>

**Comment by StragaSevera** [comment]
There is a way to solve this problem. Just add the recipes to extrude normal iron. resulting in a useless item "Not-Wrought Iron Item Pipe", and then add recipe in the arc furnace to convert this item into a useful "Wrought Iron Item Pipe" =-)

**Comment by draknyte1** [comment]
It’s not a problem, it’s ibtended behaviour and won’t ever change.
