### ISSUE TITLE
 [5.09.32pre1] Large Boiler ignore Programmed Circuit

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#1326]
while have any maintenance issue. If all fixed - works fine.
![2017-12-10_17 37 38](https://user-images.githubusercontent.com/14032818/33808443-0d6ebd92-ddef-11e7-8070-7e3d1381501a.png)

**Comment by Pilad** [comment]
There is one mistake. But efficiency is 100%
