### ISSUE TITLE
Pass-through concrete

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#1328]
- Gregtech Version: 5.09.31

When any fluid block is placed at player location, while standing over a concrete block: player enters and pass-through the concrete block just below.

##### Reproduce:

- Place some Gregtech Concrete blocks.
- Stand on Concrete.
- Pour a bucket of water on ground.

**Comment by draknyte1** [comment]
Probably fixed in .09.32 with concrete being redone to be consistent with GT6.

**Comment by OvermindDL1** [comment]
_/me is starting to wonder that since so many GT6 things are being added, perhaps a GT6 addon mod that adds the missing stuff is made using GT6's API instead..._

**Comment by draknyte1** [comment]
@OvermindDL1 unless the API in 6 uses a different MODID, you can't. 
Plus, the small few things backported are fixes to existing objects. 

Why make an additional set of concrete to imitate gt6 when you can just fix gt5s and it's not another mod to install?

**Comment by OvermindDL1** [comment]
> @OvermindDL1 unless the API in 6 uses a different MODID, you can't.

`gregapi_post`/`gregapi_pre`/etc...

But I was more referencing kind of forking GT5u and updating/remaking it to become a new addon mod on top of GT6 instead of being GT5 based.  Just idle thoughts.  :-)

**Comment by mura3277** [comment]
Assuming this is fixed
