### ISSUE TITLE
Sound related crash when Wrenching

### ISSUE THREAD

**Issue by Muramasa-** [Blood-Asp/GT5-Unofficial#133]
Crash report: http://pastebin.com/z7naD2Qc

GT Version: 5.08.26

When I crashed I was wrenching blast furnaces parts and It seems to happen consistently when using tools.

**Comment by Blood-Asp** [comment]
Do you have sound multithreading activated in the GT config?

**Comment by Muramasa-** [comment]
Sorry for the late reply, I do have sound multi threading enabled.

I also crash randomly even when I'm not doing anything. This crash report is when I was tabbed out aft and is different, but seems to be a similar issue: http://pastebin.com/p4A1GaLg

**Comment by Blood-Asp** [comment]
The errors are both multithreading errors and sound multithreading is default off because it crashes in certain combinations(Some other mods or SMP).

So disable it and everyting should be fine.

**Comment by Muramasa-** [comment]
Thanks for the quick reply to these issues, man.

**Comment by Muramasa-** [comment]
Can confirm this has fixed my issue, feel free to close.
