### ISSUE TITLE
Color machine controllers yellow if maintenance is required

### ISSUE THREAD

**Issue by richardhendricks** [Blood-Asp/GT5-Unofficial#1330]
Be nice to have a visual indicator on the front machine controllers for when maintenance is required.

**Comment by Techlone** [comment]
Use a panel from Nuclear Control

**Comment by richardhendricks** [comment]
Why? A GT machine notifying the player of a GT maintenance problem shouldn't require another mod.

**Comment by leagris** [comment]
A Global improvement I proposed a while back was to add additional overlay animated layers for Machine status.
Gregtech already has specific overlays for ACTIVE machines.

#### Example with the Electric Blast Furnace.

##### Machine Background:

- Heat-proof Machine Casing: ![MACHINE_HEATPROOFCASING.png](https://raw.githubusercontent.com/Blood-Asp/GT5-Unofficial/unstable/src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_HEATPROOFCASING.png)

##### Existing Overlays:
- normal inactive overlay: ![OVERLAY_FRONT_ELECTRIC_BLAST_FURNACE.png](https://raw.githubusercontent.com/Blood-Asp/GT5-Unofficial/unstable/src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_ELECTRIC_BLAST_FURNACE.png)
- ACTIVE overlay: ![OVERLAY_FRONT_ELECTRIC_BLAST_FURNACE_ACTIVE.png](https://raw.githubusercontent.com/Blood-Asp/GT5-Unofficial/unstable/src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_ELECTRIC_BLAST_FURNACE_ACTIVE.png)

##### Suggestions for additional Overlays:
We could benefit for more overlays:
- MAINTENANCE REQUIRED overlay: ![image](https://user-images.githubusercontent.com/1111474/34010847-64f2e1f2-e10e-11e7-8dc9-72c61ddf4683.png)
- ERROR overlay: ![image](https://user-images.githubusercontent.com/1111474/34010708-f88e9bbe-e10d-11e7-91ad-6d4a887526f6.png)

**Comment by richardhendricks** [comment]
That would be great, yes. I take it the proposal hasn't gotten anywhere?

**Comment by mura3277** [comment]
Adding to ideas: #654

**Comment by richardhendricks** [comment]
@Muramasa- GT++ added a fish farm btw.
