### ISSUE TITLE
Fluid Filters: Filter output & Easier interaction

### ISSUE THREAD

**Issue by repo-alt** [Blood-Asp/GT5-Unofficial#1335]
As far as I was able to test, fluid filters can filter only input, so if you have a multi-pipe, you cannot easily attach to it a branch pipe, to accept one type of liquid, because fluid filter cover cannot be initialized (set to the given fluid type) from the side. 
It would be nice to fix both issues if possible:
1. Allow fluid filters to filter output
2. Allow fluid filters type to be set from the side (through the "grid" interface)
But, for the second issue it is not clear when to display 'grid' on the pipe - detect if the pipe has any filters on, and if user has viable liquid container in hand perhaps?

**Comment by DEMOOH** [comment]
>Allow fluid filters to filter output

I was the one that implemented some of the fluid filter features. While working on it i wasn't able to make it filter output. So it's obviously a bug and a known one.
I might have another look into this but no guarantees. This is a tricky one to fix without breaking anything.

**Comment by mura3277** [comment]
Adding to ideas: #654
