### ISSUE TITLE
[5.10.41] [crash] Game crashes when igniting mutiple industrial TNTs

### ISSUE THREAD

**Issue by KrisBigK** [Blood-Asp/GT5-Unofficial#1336]
I was trying to blast some ores using about 5-6 industrial TNT. The first industrial TNT successfully ignited and ignites the other industrial TNTs, but when the rest of the industrial TNT were exploding, game crashed. Re-entering the game cause the same crash again. If needed, I can post the save.

[crash-2017-12-17_12.30.51-server.txt](https://github.com/Blood-Asp/GT5-Unofficial/files/1565337/crash-2017-12-17_12.30.51-server.txt)

I'm using: GT5u 5.10.41, IC2 2.6.254, CCL 2.5.9.308, JEI 3.14.7.420, OptiFine E3
MC version:1.10.2
Forge version:12.18.3.2185

**Comment by draknyte1** [comment]
Gregtech 5.10 is no longer supported. 
Due to a total rewrite, mod issues will not be investigated or resolved.
