### ISSUE TITLE
[5.10.41] universal fluid cells 

### ISSUE THREAD

**Issue by charleskong97** [Blood-Asp/GT5-Unofficial#1338]
After installing this mod , when i am holding the universal fluid cells from the IC2 mod , i keep taking damage and died after that , it showed i am boiled alive , which is same with holding any Lava bucket in hand , it is a bug of this mod or from the IC , or if it is a feature of the mod  ? Thank you

**Comment by draknyte1** [comment]
Not intended. 

Gregtech 5.10 is no longer supported.
Due to a total rewrite, mod issues will not be investigated or resolved.
