### ISSUE TITLE
A very strange recipe. 

### ISSUE THREAD

**Issue by Pilad** [Blood-Asp/GT5-Unofficial#1339]
What's the point in the electrolyzer, 
https://i.imgur.com/fUCamx6.png
if there is an easier recipe?
https://i.imgur.com/1283nbg.png

**Comment by draknyte1** [comment]
Thank you for telling us the details as requested for issues. (Sarcasm) 
Please tell us what we required and provide more information than two pictures which could be anything. Otherwise I'll close this tomorrow.

**Comment by Pilad** [comment]
The compressed air capsule is extracted into the air. In an electrolyzer for energy, this is costly. But there is an alternative less expensive recipe. That's why it's strange. It is easier to extract air through a fluid canning machine.

**Comment by Pilad** [comment]
Sorry, it's in an earlier build of there. In the last removed.

**Comment by Antillar** [comment]
Close the issue then. Only the issues relevant to the latest version are to be opened.
