### ISSUE TITLE
Single-blocks Generators renders ACTIVE overlay when fueled, regardless of output

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#1340]
Single-blocks Generators renders their `BLOCKNAME_FACESIDE_ACTIVE.png` overlay as soon as they have fuel, regardless if they actually burn through fuel or produce EU.

Would it be possible to get the `…_ACTIVE.png` overlay, only when a single-block generator burns some fuel or actually output EU?

I also noticed the ACTIVE overlay is used to render machine blocks as Items rather than the inactive one. Not sure it was intended.

**Comment by draknyte1** [comment]
Intended behaviour. 

Animated textures while fueled?
It means they're active and ready to go. 

Animated textures when held?
Aesthetics. 

If you want to resolve a texture issue, create textures for an active turbine.

**Comment by leagris** [comment]
This behaviour can be seen with existing resource textures assets and a Diesel generator. The top piston animation overlay starts as soon as the diesel generator has fuel and never stops until tank is empty or you command machine stop with a machine controller cover.

This behavior is looking inappropriate or misleading for single-block generators, because they produce power on-demand.

If ACTIVE means READY, then it could be renamed READY and have ACTIVE overlays firing when it actually start producing power.

default overlay: Generator empty or disabled by control cover
READY overlay: (replaces current implementation of ACTIVE): Generator has fuel and is not disabled by a control cover
ACTIVE (new state): overlay used when generator actually produce EU and burn through its fuel.
