### ISSUE TITLE
[GT 05.09.32pre1] Implosion Compressor

### ISSUE THREAD

**Issue by BritishCynic** [Blood-Asp/GT5-Unofficial#1344]
The Implosion Compressor does not automatically run, and has to be manually triggered with a Soft Mallet.

Input is taken, but no Output is generated.

**Comment by Blood-Asp** [comment]
muffler hatch blocked or not enough energy

**Comment by mitchej123** [comment]
Does it have power connected?  Sounds like the behavior I had with my EBF that didn't have the wire connected.

Assuming 09.32pre1 has gt6 style cables - try disabling the gt6 cables until the fix is merged in.

**Comment by BritishCynic** [comment]
GT6 cables are already disabled.

I'm checking the muffler hatch (although I swear that it's correct), will update when my world loads.

**Comment by Blood-Asp** [comment]
It does not start at all if 0 energy is inside. ist must have some energy to start and then get supplied with more energy to keep running. only then it shows discribed behavior.

**Comment by BritishCynic** [comment]
OK, this was my fault. I had the wrong power block down.

Multiblock working as intended.
