### ISSUE TITLE
GT 6 Style Wires again

### ISSUE THREAD

**Issue by danbka33** [Blood-Asp/GT5-Unofficial#1350]
To connect the wires don't need soldering iron, if connect from the upper side
https://youtu.be/4yAJ0laNmfU

**Comment by MauveCloud** [comment]
I'm fairly sure that's by design, and it matches actual GT6 behavior (I just checked).  You should also be able to connect wires/cables at the sides (or even the bottom), by targeting an existing wire/cable when placing instead of the ground.

**Comment by danbka33** [comment]
For what then does this option exist in the config?
`B:CableConnectionRequiresSolderingMaterial=true`

**Comment by MauveCloud** [comment]
Now I understand what you mean.  I had forgotten about that option.  Looking at the code, the implementation of that option is non-intuitive (including being able to still use wire cutters and somehow use up soldering alloy when adding connections).
