### ISSUE TITLE
GT Cables and Wire don't not connect EIO RF conduits

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#1355]
##### Versions:

- Gregtech 5.09.31

##### Issue Description:

An EnderIO RF conduit does not create connectors to a GT Cable or Wire converting EU to RF.
Although RF are properly inserted into the RF conduit .
Missing connectors prevents controlling the connexion (example disable unwanted)
Connexion is not visually enabled although RF transfer occurs.

![2017-12-31_18 51 28](https://user-images.githubusercontent.com/1111474/34463444-7439a442-ee5c-11e7-8763-ccd44e97d50e.png)

**Comment by draknyte1** [comment]
Gonna say it's an EIO issue so we probably won't fix it.

**Comment by leagris** [comment]
Interestingly:
- A connector is generated with **EIO Fluid Conduits** against **GT Cables/Wires**.
- A connector is generated with EIO Item Conduits and GT Item Pipes.
- A connector is generated with EIO Fluid Conduits against GT Fluid Pipes.

I guess GT Cables and Wires advertises themselves as Fluid rather than RF.

1. It really look like a Gregtech Issue.
2. I doubt EnderIO behaves wrongly here and even if it were, it is not gonna be fixed since EnderIO has ended 1.7.10 support years ago.

**Comment by draknyte1** [comment]
All wires and pipes are pipes, technically. 

Won't be fixed by GT because it'll be due to rf implementation, and as its visual it's not really an issue. 

Wasn't expecting an EIO fix, but the issue probably stems from their detections of what is an rf supplier/provider. Other mods work as expected and other mods also fail with wire/cable connections.

**Comment by leagris** [comment]
> All wires and pipes are pipes, technically.

- Gregtech Item Pipes correctly advertises themselves as Item containers and causes EnderIO to enable a connector with Item Conduits only.
- Gregtech Fluid Pipes correctly advertises themselves as Fluid containers and causes EnderIO to enable a connector with Fluid Conduits only.
- Gregtech Energy Pipes (Cables and Wires) wrongly advertises themselves as Fluid containers and, causes EnderIO to enable a connector with Fluid Conduits instead of Energy Conduits.

> Won't be fixed by GT because… as its visual it's not really an issue.

#####  Consequences are not only visual, but affect conduit behaviour, ability to control RF transfers and can cause unnecessary ticking load.

- EnderIO Energy Conduit will get injected RF from Gregtech Cables and Wires regardless of unavailable options, since there is no connector to access conduit connection settings. It is so impossible to decide of connexion status, or direction of energy transfer that is needed when RF to EU conversion is enabled.
- EnderIO Fluid Conduits are misled by Gregtech Cables and Wires to enable a connector, ticking useless impossible fluid transfer attempts with Gregtech Cables and Wires, unless each wrong connector is individually disabled.

##### Reasons to review this glitch:

Gregtech Pipes had recent changes to their connexion mechanic.
While reviewing and debugging these pull requests:
- Fixing how Cables and Wires advertises themselves (changing from Fluid Container to RF Energy Emitters and Acceptors instead) sounds just appropriate when attention is focussed on relevant Gregtech code portions.

**Comment by Blood-Asp** [comment]
All GT blocks use the same base block, so all have an tank and an item storage implementated but it is to size 0 if not used. EnderIO fails to check the size. so their problem. same happens with EIO and AE2 cables for example. And there are a few more mods that have shared blocks that get wrongly detected by EIO cables.

Also, GT cables have no RF interface, so EIO condiuts do not automaticly connect to them. But you can just force them and they will simply work.
