### ISSUE TITLE
[change request] Fluid icons ignores materialproperties RGBA settings

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#1364]
### Issue

Currently, each individual material fluid icon [is provided with its very own animated png and mcmeta file](https://github.com/Blood-Asp/GT5-Unofficial/tree/unstable/src/main/resources/assets/gregtech/textures/blocks/fluids/).
This causes rendering of fluids to ignore material colour as set by RGBA settings in `MaterialProperties.cfg`

### Proposed change

1. Deprecate existing `blocks/fluids` assets while keeping them for a wile if needed because of some backward compatibility.
1. Add  new universal assets:   
   - `fluid.thick.png` and `fluid.thick.png.mcmeta`: to represent thick fluids like oil, molten metals, concrete…
   - `fluid.light.png` and `fluid.light.png.mcmeta`: to represent light fluids like water, chlorine, light fuel…
   - `fluid.gas.png` and `fluid.gas.png.mcmeta`: to represent gases
1. Computationally generate each material fluids based on one of relevant fluid.*.png asset and apply MaterialProperty RGBA tint to the pixmap.

**Comment by leagris** [comment]
Another option is to add a `fluid.png` and `fluid.png.mcmeta` into `blocks/materialicons/MATERIALTYPE/` for each material type like `DULL`, `SHINY`, `METALLIC`… as the base greyscale pixmap to be coloured accordingly to Material Properties RGBA.

**Comment by draknyte1** [comment]
Too much work for no direct gain. 

If it wasn't at this point in the project, sure. But since it is, point your suggestion to 1.12 branch.
