### ISSUE TITLE
[Suggestion] Ultimate coil

### ISSUE THREAD

**Issue by Antifluxfield** [Blood-Asp/GT5-Unofficial#1367]
Suggested by Rosanna, from Chinese Minecraft Community:

> The Naquadah Alloy Coil is not ultimate enough. I suggest a real ultimate coil, which let the EBF overclock losslessly(or "upgraded overclock", which "reduce recipe time to 25% and increase EU/t to 400%") all the time.

I: So what about its material?

> Maybe superconductor? Well, superconductors doesn't have resistance... 
What about Neutronium? Neutronium Coil made from Neutronium Wires, which is MAX tier and... whatever the Amperage.

I'm not really sure about this idea and its details, so I (translate and) port it here as an issue.

**Comment by Dream-Master** [comment]
I like the idea.

**Comment by Blood-Asp** [comment]
Some sort of Neutronium Coil with an max heat of 100.000+ would have the result wished for i guess. Would be easy to implement if someone wants to do that.

**Comment by mura3277** [comment]
Adding to ideas: #654
