### ISSUE TITLE
[Suggestion] Horizontal Mining Machine

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [Blood-Asp/GT5-Unofficial#1370]
Rotarycraft has the excellent Boring Machine but once you know the ins and outs of Rotarycraft it can be a little too OP compared to other mods.

Gregtech would really benefit from something like the Boring Machine because all of the ores you need to progress through GT are spread between many chunks.

Maybe it could take the form of upgrades to the Railcraft Tunnel Bore, such as larger tunnel size, silk touch, electric power, greater storage capacity etc.

Or there could be a multiblock Gregtech subterrene, powered by electricity or nuclear fuel rods, that would leave large obsidian-encased tunnels in its wake.

There could be an adjustable-size multiblock, which you build facing a specific direction, and as long as it was continuously supplied with mining pipes, electricity, and perhaps drilling fluid/nuclear fuel, it would push the boring head or thermal penetrator forward at the end of the pipe and chunkload it, while pumping blocks out of the output hatch.

**Comment by Blood-Asp** [comment]
Another one for the List of ideas.
