### ISSUE TITLE
Greg tech 5.09.31 axe 

### ISSUE THREAD

**Issue by mikiones** [Blood-Asp/GT5-Unofficial#1372]
![screen shot 2018-01-12 at 11 22 19](https://user-images.githubusercontent.com/1821412/34873368-c0ddb53e-f78c-11e7-8809-399226b4e635.png)

negative durability, axe broke on next use.

**Comment by Antillar** [comment]
How was this axe obtained?

**Comment by mikiones** [comment]
the 2 plates + ingot how else. was crafted.

was chopping big trees and notice that.

**Comment by draknyte1** [comment]
Yeah, it can happen.. it's not really a bug because you don't get many extra logs even on gigantic trees.
