### ISSUE TITLE
[Suggestion] Modular Ranged Weapon

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [Blood-Asp/GT5-Unofficial#1377]
A lot of the appeal of some mods comes from their very powerful endgame equipment, and it would encourage more players to go through gregtech's progression if it had a couple items like that.

What I propose is some kind of energy weapon, firing particle beams or plasmoids, which would have a few slots for components that you could swap out and upgrade as the rest of you technology got more advanced. So you could swap in higher tier emitters to increase the damage, higher tier field generators to increase the rate of fire, higher tier circuits to increase energy efficiency, and higher tier batteries to increase the storage.

What would really make this appealing is a good first person 3D model like the ones in techguns and vic's modern warfare mod.

**Comment by Blood-Asp** [comment]
added to long list of ideas that likely never will come but are at last written down if some coder is bored...
