### ISSUE TITLE
Phenolic board being uncrafteable

### ISSUE THREAD

**Issue by k1r0s** [Blood-Asp/GT5-Unofficial#1383]
gt version: gregtech-5.09.30.jar

glue cells are uncrafteable since universal cells are the way to go.

I have to tweak the recipe to allow users playing

![image](https://user-images.githubusercontent.com/6052309/35477168-0645e492-03be-11e8-84b4-4b68b6b14653.png)

**Comment by Antillar** [comment]
Please test this issue in the latest version: release 5.09.31 as well as the beta 5.09.32pre1.
Builds can be found on [OneDrive](https://onedrive.live.com/?id=478CC928A26B8E66%212065&cid=478CC928A26B8E66).

**Comment by k1r0s** [comment]
anyways ordinary cells were in fact crafteable at some point :') 

thanks though
