### ISSUE TITLE
1.7.10 Fluidstack issue

### ISSUE THREAD

**Issue by TsavyPrince** [Blood-Asp/GT5-Unofficial#1386]
`java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid`
So apparently this exception happened and the game crashed when I ran IC2 Classic and Gregtech5 Unofficial together.
https://pastebin.com/3AzR09Zm
Here is the entire output log.

**Comment by JohannesGaessler** [comment]
I integrated a fix into https://github.com/Blood-Asp/GT5-Unofficial/pull/1334

**Comment by Blood-Asp** [comment]
And is merged since pre2
