### ISSUE TITLE
[1.10.2] GregTech.lang has no effect

### ISSUE THREAD

**Issue by LasmGratel** [Blood-Asp/GT5-Unofficial#1387]
Version is 5.10.41

I had replaced my GregTech.lang to translated version, however, when I entered the game I found that all messages had been keeping original version thus the language didn't get any work.

Please fix that bug so that I could continue the translation progress.

**Comment by draknyte1** [comment]
5.10.x isn't being actively developed anymore. 

https://github.com/GregTechCE/GregTech
