### ISSUE TITLE
[5.09.32pre2] NEI freezes

### ISSUE THREAD

**Issue by jaskarth** [Blood-Asp/GT5-Unofficial#1389]
Whenever you look at recipes in NEI, Minecraft freezes. The only way to fix the freezing is by killing with task manager and reopening.

**Comment by Pilad** [comment]
I watched the prescription of the fluid regulator, in nei. I pressed R on his icon, there are no freezes. More details can be, on what subject did you show it?

**Comment by Blood-Asp** [comment]
does not happen in Dev enviroment. So it has to be narrowed down to some mod incompatibility or other special conditions.

Are there any logs or similiar showing?

**Comment by jaskarth** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/548f5ec252053dc37634fe569a033a1301325eaf#diff-b8485e3cc7700e7ce3ad641fb6517dad This commit is probably it

**Comment by lycc193** [comment]
The same problem happened when I used NEI to see how to make a Hydro-Cracked Ethane.
There is nothing in the log.

modlist : 

- gregtech-5.09.32pre2
- industrialcraft-2-2.2.827-experimental
- CodeChickenCore-1.7.10-1.0.7.47-universal
- NotEnoughItems-1.7.10-1.0.5.120-universal
- Waila-1.5.10_1.7.10
- CraftTweaker-1.7.10-3.0.13
- ModTweaker2-0.9.6
- GTTweaker-1.7.10-1.6.3
- fastcraft-1.23

**Comment by NNM42** [comment]
configs all set to default.
Ticking textures when press "R"\"U" to see reciept\usage

https://pastebin.com/f6fN2MtX

![2018-02-12_11 46 23](https://user-images.githubusercontent.com/30381383/36083994-45742f00-0feb-11e8-961c-a0b6993650df.png)
![2018-02-12_11 46 33](https://user-images.githubusercontent.com/30381383/36083995-459a8aba-0feb-11e8-9a29-d44fcce24ca6.png)
![image](https://user-images.githubusercontent.com/30381383/36084004-4b93bee6-0feb-11e8-9259-1842d417028f.png)

**Comment by NNM42** [comment]
configs all set to default.


Ticking textures when press "R"\\"U" to see reciept\\usage

**Comment by SapientMC** [comment]
@Antifluxfield I can confirm. Problem solved. Thanx a lot )

**Comment by NNM42** [comment]
all ok now. thx!
