### ISSUE TITLE
[Feature request] Data Orb

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#139]
It would be nice to see in the tooltip of the Data Orb how much UUmatter and EU is needed to produce the item in a (LV) replicator.

**Comment by Muramasa-** [comment]
The best place for this information would be on the NEI recipes GUI for the replicator. However, it's not currently in the game yet.

**Comment by Blood-Asp** [comment]
I will make it as NEI recipe as requested in https://github.com/Blood-Asp/GT5-Unofficial/issues/103
So this will not be needed.
