### ISSUE TITLE
Hi, question about modular armor

### ISSUE THREAD

**Issue by k1r0s** [Blood-Asp/GT5-Unofficial#1399]
Im looking at modular armor code. __There is any documentation about how it works?__

I just discover that HV motors on leggings allows speedrun!!!

:\

**Comment by skeblow** [comment]
Greetings,
found only this old document [drive](https://docs.google.com/spreadsheets/d/1KAGtjwnOEzyENwmWIDUnqD8OW9TLPBQY9x3oXawoA3o/edit#gid=945635104). You can also find some info in code [here](https://github.com/Blood-Asp/GT5-Unofficial/blob/ddf58e6ef45bbffa3c5ecde39114aff0bc4d1efc/src/main/java/gregtech/common/items/armor/components/LoadArmorComponents.java).

Hope you will find this helpful.
