### ISSUE TITLE
Bugs with textures.

### ISSUE THREAD

**Issue by T3XRD** [Blood-Asp/GT5-Unofficial#1407]
This bug happens all the time in a mine with ore and all blocks from this mod, outside with machines.
What i need to do? 
![2018-02-25_11 33 38](https://user-images.githubusercontent.com/36810938/36639587-9792a5c0-1a20-11e8-8ae6-f9d0fa663b37.png)
![2018-02-25_11 33 39](https://user-images.githubusercontent.com/36810938/36639588-97ac86e8-1a20-11e8-9122-590a105a938b.png)
![2018-02-25_11 33 43](https://user-images.githubusercontent.com/36810938/36639589-97c5851c-1a20-11e8-8a83-6cc818888d37.png)

**Comment by draknyte1** [comment]
Can you provide the request information about mod version, etc?

**Comment by T3XRD** [comment]
Mod version is 5.10.41

**Comment by T3XRD** [comment]
AE2 Stuff
Applied Energistics 2
AutoRegLib 
BdLib
Better Fps 
Chisel
Chisels & Bits
Code Chicken Lib
CompatLayer
CraftTweaker
ConnectedTexturesMod
Custom Mob Spawner
Mo'Creatures
Ender Core
Ender IO
Extra Utilities 2
Flood Lights
FoamFix
Forestry
GalactiCraft
Gravitation Suite
GregTech
Grimoire Of Gaia
Industrial Craft
Inventory Tweaks
Iron Chest
Just Enough Items
JEI Bees
Journey Map
Mod Tweaker 2
Modular Powersuits
MrTJPCore
MTLib
Open Computers 
OptiFine HD
Quark
Railcraft
Random Things
Reap Mod
RTG
Surge
Waila 
Waila Harvestability
Dynamic Lights
Thaumcraft 6 beta6
ImmersiveEngineering-0.10-61

**Comment by T3XRD** [comment]
Mods are used

**Comment by T3XRD** [comment]
Minecraft version is 1.10.2

**Comment by Georggi** [comment]
Minecraft 1.10 is not and won't be supported, refer to https://github.com/GregTechCE/GregTech for 1.12+(still indev)
