### ISSUE TITLE
Biomass requires disambiguation

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1416]
Currently GregTech 5 supports both types of Biomass:
* `ic2biomass` as added by IndustrialCraft 2.
* `biomass` as added by Forestry.

Both types are used in recipes, both are obtainable, but they have different usages and they are obtainable differently.
However, they are still both called Biomass.
This same naming can misguide even experienced players, not speaking of new players who may not even know the difference.

I suggest renaming the Biomass with fluid registry name of `ic2biomass` to **Industrial Biomass**.

**Comment by SapientMC** [comment]
game.setLocalization("ic2.itemCellBiomass", "Industrial Biomass Cell");
game.setLocalization("ic2.fluidBiomass", "Industrial Biomass");

**Comment by mura3277** [comment]
GT probably shouldn't rename items from other mods

**Comment by Antillar** [comment]
GT already does it. As long as fluid registry stayes the same, the localization does not matter. However, if 2 different fluids are localized under the same name, it has to be changed.
