### ISSUE TITLE
The problem with GT TC ExU

### ISSUE THREAD

**Issue by AustenXiyue** [Blood-Asp/GT5-Unofficial#1420]
When I install Gregtech, Extra Utilities and Thaumcraft, the game will be crash
I can't install these three mods in same time, I can only install two of them in same time, like GT and TC or GT and ExU or TC and ExU, but if I install like GT and TC and ExU in same time, the game will "bomb"!
I'm trying to find the way to solve this problem in google, but there are no answer
Mod version:
GregTech-5.09.29.jar
Extra Utilities-1.2.12.jar
IndustrialCraft-2-2.2.820-experimental.jar
ThaumCraft-1.7.10-4.2.3.5.jar
Baubles-1.7.10-1.0.1.10.jar

The crash_reports:
[crash-2018-03-16_20.20.32-client.txt](https://github.com/Blood-Asp/GT5-Unofficial/files/1821270/crash-2018-03-16_20.20.32-client.txt)

**Comment by PrincessOfEvil** [comment]
Well, the loop technically happens in ThC.

**Comment by AustenXiyue** [comment]
How to fix this problem?

**Comment by draknyte1** [comment]
Currently using: 
```
extrautilities-1.2.12.jar
Baubles-1.7.10-1.0.1.10.jar
industrialcraft-2-2.2.783-experimental.jar
Thaumcraft-1.7.10-4.2.3.5.jar
Gregtech 5.08.33/5.09.28/5.09.31.jar
```

Not a single issue...

`
UCHIE	ExtraUtilities{1.2.12} [Extra Utilities] ([实用设备]extrautilities-1.2.12.jar)`
Is where your crash is actually happening.. A complete log would actually be helpful.

**Comment by AustenXiyue** [comment]
My mod:
extrautilities-1.2.12 .jar
gregtech-5.09.29.jar
industrialcraft-2-2.2.783-experimental.jar
Thaumcraft-1.7.10-4.2.3.5.jar

This mod inside the 1.7.10 folder
Baubles-1.7.10-1.0.1.10.jar

And when I run the game, It create a new folder call"ic2" and this jar inside this folder
EJML-core-0.26.jar

I'm using HMCL-3.1.59 to run game
and my forge version is 10.13.4.1614

[crash-2018-03-18_13.57.47-client.txt](https://github.com/Blood-Asp/GT5-Unofficial/files/1823133/crash-2018-03-18_13.57.47-client.txt)
[2018-03-18-1.log](https://github.com/Blood-Asp/GT5-Unofficial/files/1823135/2018-03-18-1.log)
These are the log and crash-reports

And i'm using a new clean pack to run game, this pack never use other mods before, but my game is still not work,

**Comment by AustenXiyue** [comment]
![4](https://user-images.githubusercontent.com/25553318/37571157-32cb14f0-2ab6-11e8-981a-4dfe4ed8c2f0.PNG)
![1](https://user-images.githubusercontent.com/25553318/37571158-32e13c1c-2ab6-11e8-9e29-47bc51feb4c7.PNG)
![3](https://user-images.githubusercontent.com/25553318/37571159-32f71e2e-2ab6-11e8-8719-e64dd5cfe460.PNG)
![5](https://user-images.githubusercontent.com/25553318/37571160-330ccb8e-2ab6-11e8-8a48-58a8ec990e63.PNG)
![default](https://user-images.githubusercontent.com/25553318/37571161-3321a68a-2ab6-11e8-8e83-4116456f0b96.PNG)
![2](https://user-images.githubusercontent.com/25553318/37571162-3338539e-2ab6-11e8-8851-7eaf0a32d4ad.PNG)

**Comment by AustenXiyue** [comment]
I don't know whats happening why my game is not work, can you give me a pack and these mod inside the game pack? whatever the version or other things is, please.

**Comment by Rongmario** [comment]
Name your Thaumcraft file:

AThaumcraft-1.7.10-4.2.3.5, and tell me if it still crashes or produces a different error.

這很常在TC裡出現

**Comment by AustenXiyue** [comment]
Oh my gods!!!! My game is working!!!!!
Thank you to help me to solve this problem!!!!!! @Rongmario

**Comment by Rongmario** [comment]
No problem! 

Issue is available for closing.
