### ISSUE TITLE
Steam does not enter machines from the bottom

### ISSUE THREAD

**Issue by tomasbrod** [Blood-Asp/GT5-Unofficial#1437]
This used to work. I am playing with the pipe-require-wrench-to-connect thing on. Steam machines will accept steam from the sides, but not bottom. This breaks compact steam "kitchen desk" workshop build.
![2018-04-09_10 27 20](https://user-images.githubusercontent.com/11995799/38487581-f80bfdde-3be0-11e8-999f-7459160477af.png)
Only the machine with pump and machine connected from back (vent rotated to top) do work.

Edit: I checked with scanner that the other machines do not get steam, as their internal steam tank is zero.

**Comment by GusSmedstad** [comment]
I’m not sure what you’re doing, but in both .31 and .32pre4, steam from the bottom works fine. That’s how my current base worked when I was entirely steam, and I’ve still got 3 machines left (alloy smelter, extractor, compressor) using steam piped from the bottom.
