### ISSUE TITLE
Galena ore processing balance bug

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#1439]
Galena Dust can be processed several ways.
* 1 Galena Dust -> 1 Lead Ingot (smelting)
* 1 Galena Dust -> 0.375 Lead Dust + 0.375 Silver Dust + 0.25 Sulfur Dust (electrolyzer)
* 1 Galena Dust -> 1.5 Lead Ingot + 1 Silver Ingot (primitive blast furnace)
* 1 Galena Dust -> 1.5 Lead Ingot + 0.67 Silver Ingot (blast furnace chemical smelting)

Compare the last 2. You can clearly see that the more primitive one gives more output. This is illogically considering the last one is performed at a higher tech level with higher efficiency and requires some decent work with gases to be performed. 

I suggest increasing silver yield from the last recipe from 6 nuggets to at least 9 nuggets, so it is equal to the primitive blast furnace recipe, and ideally the silver output should be 10-11 nuggets to make the energy and resources spent on performing the last recipe provide at least some profit!

**Comment by Zaxar163** [comment]
Also! I think it is illogically. But it  is not big bug.

**Comment by nictrace** [comment]
maybe simply change silver output between two types of BF?

**Comment by YoungGT** [comment]
I think it's better to exchange the output nuggets of the last two recipes, so there will be both no nuggets problem and no tech level problem.
