### ISSUE TITLE
Fusion reactor running without energy

### ISSUE THREAD

**Issue by doushio9967** [Blood-Asp/GT5-Unofficial#144]
A Mark I (probably the same with the other tier fusion reactors) fed with the initial 150M+ EU and for example He+Molten tungsten will keep on producing molten osmium even after the internal EU store is dry.
You can even freely stop and restart it with a soft hammer.
Only after a relog (or perhaps chunk unload+load?) will it notice that it's not getting the required 24k EU/t, stop the process and refuse to start again until it has the start-EU in store.

I haven't played much with fusion reactors but I doubt that's how it's supposed to work.
GT 08.26

**Comment by Blood-Asp** [comment]
fixed in GT5.08.28
