### ISSUE TITLE
[enhancement] Auto-hide Unobtainable Items

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [Blood-Asp/GT5-Unofficial#1441]
Is it possible to automatically hide non-GT plates, rods etc. that are unobtainable if they aren't special unification targets, so that we can only see GT items and special unification targets in recipes (if unification is enabled)?

**Comment by draknyte1** [comment]
Not worth the effort in NEI.. this is more of a feature for them, not for GT specifically to add.
