### ISSUE TITLE
Issues with LHE output.

### ISSUE THREAD

**Issue by NyaDeveloper** [Blood-Asp/GT5-Unofficial#1442]
We know that Large Heat Exchangers requires 4000L/sec Hot Coolant or 1000L/sec Lava to produce Superheated Steam, at the proportion of half the regular steam amount, so 1L hot coolant = 40L SHSteam or 80L Steam. The thing is, when that exact amount is put in a input hatch, the machine starts working but it doesn't produce any superheated steam, not even regular steam. It seems it is voided. The machine only produces SH Steam after running for some time. 

The current GT version I am using is **5.09.32pre1**

**Comment by Blood-Asp** [comment]
The LHE has to heat up first to produce steam. That takes some time. Use an Scanner to see the progress of the heating.
