### ISSUE TITLE
Tried to over-fill container issue

### ISSUE THREAD

**Issue by juniormint90** [Blood-Asp/GT5-Unofficial#1445]
First, I would like to apologize if this is a derp moment on my part, I honestly have tried to figure it out. Also this is a bit of a 2 problem issue so please bare with me and let me know if I am missing any information or need to clarify anything.

A brief description on what I have done so far before the problem. 
I have been researching this issue for 3 days. 
I have looked at the forums repeatedly and looked through all relevant similar issues I could find. 
I am using the gregtech-5.10.41.jar version.
I have tried the gregtech-5.10.41dev.jar version but it crashes the client (more later)

The issue is this: I am running direwolf20 1.10.2 version from the FTB downloader. I have added in metamorph mod and gregtech-5.10.41. I have updated the server to match the client by updating the server FML to 1.10.2-12.18.3.2316 and copied relevant mods from client to server. This has worked perfectly fine. I can generate the world and play relatively fine without any issues except minor see through blocks in need of block update.(Finding a direwolf20 1.10.2 server rar was tricky and needed update)

The issue I am having is that at certain locations during chunk initial generation (the location is fixed and doesn't change on server restart) the server freezes and I get a "attempted to over-fill container" bug which freezes the server.

The only issue I have been able to find with a similar problem is here: 
https://github.com/Blood-Asp/GT5-Unofficial/issues/854
and I have tried disabling the jasper ore generation and it still freezes(on old and new world) and I have deduced that it could be a issue with dungeons.

This issue only persists if I run gregtech. When the gregtech jar is removed I have no error or freezing.
The above link suggests that this issue was fixed in dev, but as I have stated, dev crashes the client.
The client side crash report  when using gregtech-5.10.41dev.jar is below. The server can start up using this jar but not the client. 
https://pastebin.com/3Sa2hiT3

I have tried to use an earlier version of gregtech such as 5.10.40 but this crashes the server and client and i feel like I have enough issues already with just the client and or server crashing by themselves.

Also if I run gregtech 5.10.41 in singleplayer it still receives the over-fill issue. I have to explore for a while to find it but once found it is the same as on the server.

"==="Extra unneeded info===""
I have tried removing mods that could conflict but the resulting system rework feels like a nightmare and since the bug only occurs with gregtech installed I am hoping to find a gregtech solution. If it is a mod conflict than it would help narrowing it down as any time I attempt to change any certain mod in the pack I usually need to change 5 or 6 other things. Example, updating or changing RFtools mod requires me to updating 4 other mods which in turn may need a new version of FML which then needs all the other mods updated and since most mods dont post the FML compatibility by version, it becomes a nightmare.

**Comment by draknyte1** [comment]
5.10 is no longer developed nor supported.
