### ISSUE TITLE
Suggestion: Hexadecuple Fluid Pipes

### ISSUE THREAD

**Issue by Wolozo7** [Blood-Asp/GT5-Unofficial#1447]
Nonuple Fluid Pipes are a great way to work with fluids, both in collecting and distributing them, if players don't want to use the quite magical EIO Conduits. However, since there are multiblocks that produce more than 9 fluids, like the Distillation Tower and LFTR, I'd suggest adding Hexadecuple (crafted from 4 Quadruple) Fluid Pipes.
Would that be possible?

**Comment by draknyte1** [comment]
I don't see why not. 
It's not really OP because each pipe is smaller as more are added.

**Comment by Blood-Asp** [comment]
The question would now be if 1/16 capacity is enough for the highest output of the Destillation tower in the first place...

**Comment by Wolozo7** [comment]
Edited title to Hexadecuple, but I'm honestly unsure on the correct nomenclature here.

Since the relation for throughput seems to be Quadruple -> Normal Pipe, Nonuple -> Small Pipe, the 16 pipes would be equivalent to Tiny Pipes, meaning 1200 L/sec from Stainless Steel. A lot of the relevant Distillation Tower recipes take 6 seconds of MV, rarely producing more than 500L of a single fluid with one operation. Access to higher energy tiers also includes access to better pipes, so I think the capacity would be sufficient.
