### ISSUE TITLE
Processing Array

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#145]
The Processing Array does not work with the Basic Mass Fabricator or the Basic Wiremill.
[I build the Processing Array correctly because after I switched it out for a macerator inside it started to work normally.]

gregtech_1.7.10-5.08.26

**Comment by pyure** [comment]
Blood, adding the wiremill is a non-issue, but I couldn't figure out how to add a machine that doesn't have a recipe as such.

[code]
public GT_Recipe.GT_Recipe_Map getRecipeMap()
 {
....
   else if(tmp.startsWith("wiremill")){
                                            return GT_Recipe.GT_Recipe_Map.sWiremillRecipes;
                                        }
}
[/code]

**Comment by Blood-Asp** [comment]
I allready added the wiremill on my side.

The Mass Fab can't be added and will not. Makes replicating too easy.

**Comment by DarknessShadow** [comment]
Mass fab in the processing array is too easy but other machines are not ?
Why is it too easy?
Still same amount of scrap / energy needed.

**Comment by Blood-Asp** [comment]
There is rarely any use for the processing array besides the centrifuge in case of the fusion reactor and that is what is was made for in the first place. 

The Mass fab with it's other limitations profits a lot.

**Comment by DarknessShadow** [comment]
Then please change the tooltip of the processing array so we know that the massfab does not work with it.

**Comment by Blood-Asp** [comment]
There is a bunch of recipes i can't add. 
For example: Scanner, Replicator, Rockbreaker, Printer, Brewery, Disassembler and Packager.

Adding them all to the tooltip is a bit overkill. If was originally only meant for the fusion centrifuges, everything else is a bonus.
