### ISSUE TITLE
Heavy Fuel should be added to the Combustion Generator

### ISSUE THREAD

**Issue by redmage17** [Blood-Asp/GT5-Unofficial#1450]
I have no idea what substance it's based on other than the the heavier stuff that floats to the bottom in processing but isn't a plastic. But it's FUEL it should be burnable in that generator.

**Comment by tomasbrod** [comment]
I do not agree for the folowing reasons:
1. You can turn heave stuff to light stuff in the cracker. Making heavy fuel combustible would make that part of processing less useful.
2. It is heavy and viscous. It does not atomize at all in the generator's carburateur.
3. You can burn it in boilers or Alkalus's semifluid generators.

**Comment by redmage17** [comment]
1. I need to double check the math on steam cracking but 10/3 is not a good conversion ration and with the hydrogen involved it's kills the net energy gained. 
2. It's a game and has whatever properties we give it unless you can give me the exact substance it's based on reality only loosely applies.
3, Not sure what tech level those are but I believe on the higher end of the spectrum, also we should never rely on other mods to balance for us in principle.

**Comment by draknyte1** [comment]
Regarding 3)
They're tiered accordingly and like creosote, this should really only be used as semifluid generator fuel (which also includes large boilers)

**Comment by redmage17** [comment]
What voltage tier can you craft the semi fluid boiler at?

**Comment by draknyte1** [comment]
All large boilers accept Semis, unlike normal fuels they don't suffer degraded efficiency. 

My Semifluid Generators can be crafted at LV, MV and HV respectively.

**Comment by redmage17** [comment]
Maybe NEI was being funky, was only seeing the IC2 one

**Comment by redmage17** [comment]
Still think it should have a burn value of some form.

**Comment by redmage17** [comment]
Okay  I did not know that semi fluid fuel did not suffer the degraded efficiency. It has uses some I'm fine with it. You can close this
