### ISSUE TITLE
Nettlesome Phosphor Name

### ISSUE THREAD

**Issue by YoungGT** [Blood-Asp/GT5-Unofficial#1456]
There‘re four materials that contain _phosphorus_ : **phosphorus** ,**phosphor** ,**phosphate** and **phosphorous pentoxide**. The last one is very identifiable ,but those three items are very indecipherable in GT. But why? The reason is that the names of them in GT are confused. Let us check them out.
I list them up![](https://user-images.githubusercontent.com/30253037/40097235-96346c42-5907-11e8-9d02-1ed005ea7c20.png)
And we can find that the names of **phosphorus** and **phosphor** wrong easily.
I'm trying to translate the language file into Chinese and it really makes me vexed. So I'd like to correct the primary names by the containing elements.

**Comment by draknyte1** [comment]
As Dream has found, this breaks mods using these materials. The old ones should be deprecated, not removed. Look at other examples within the materials clas.

**Comment by draknyte1** [comment]
@Blood-Asp I would’ve noticed this upon review, your reckless merging is a pain in the ass.
