### ISSUE TITLE
Generator fuel leftovers

### ISSUE THREAD

**Issue by Usernm0** [Blood-Asp/GT5-Unofficial#1457]
I build simple setup to keep generator near empty and put fuel only when it complete empty.

I believe this setup is easiest to reproduce problem:
Diesel generator with fluid detection cover. Cover set to inverted.
Tank on top of it. Pump attached to bottom side of the tank and set to Export (conditional).
Machine control cover put on tank side and set to inverted. 
Fluid detector cover connect to machine control cover via red alloy cable. 
![](https://i.imgur.com/2Gn40a7.png)

Everything works fine for some time. When generator have 0mb fuel, pump on tank activated and move next part of fuel to generator. But after some time it stop works, because last 1mb of fuel not burn in generator and clog it. 
![](https://i.imgur.com/NGDK12g.png)

Can we do something with this last 1mb fuel? 

Another example of this problem. On my main base i use dozens of diesel generators and pipe system to fuel it. And when I decide to switch from light fuel to diesel I can't do it smoothly, because i try to use all lightfuel leftovers in generators. Some of them easily get new fuel from pipe system and start works, but other clogs with 1mb of old fuel.

**Comment by leagris** [comment]
I know it is not a real fix for generators not able to consume the last 1L on their own, but you can alternatively insert a Gregtech large steel cell or GT++ cells in the top slot; to remove the remaining fluid.

**Comment by Usernm0** [comment]
Large steel cell not take last 1mb, it can take only full volume of fluid. And i don't understand what gt++ cells? If you talk about ic2 universal fluid cell, it works same as large cells if just put them in generator. 

And i want fuel consumes completely(maybe void) in generator, not workaround.

**Comment by leagris** [comment]
Did you even try?
Large steel cells can take arbitrary amount of fluid.

**Comment by Usernm0** [comment]
Take last gregtech 5.09.31 from curse to test. 
![](https://i.imgur.com/H3jIEk5.png)

**Comment by draknyte1** [comment]
GT++ adds hand pump to remove fluids from machine inputs. 
Gt has a plunger to remove them.
