### ISSUE TITLE
Machines cannot be un-painted.

### ISSUE THREAD

**Issue by GusSmedstad** [Blood-Asp/GT5-Unofficial#1459]
Cables, when broken with a wire cutter, forget their color (if any). This allows you to correct painting errors by breaking the cable and replacing it.

Machines remember their paint color, and cannot have their color removed in any way. A machine accidentally painted will no longer connect to painted cables or pipes, and this color cannot be removed. At best, the cables / pipes attaching to the machine must be left unpainted, or match the color of the machine. Often this is undesireable, since a machine needs to connect to pipes or cables of multiple colors.

For example, if MV cables are painted orange, and HV cables painted yellow, accidentally painting a MV transformer means it cannot connect to its cables unless one of them is left uncoded.

**Comment by Vitium92** [comment]
As far as I remember, GT machines can be unpainted using a water bucket on them. I cannot remember if it is  an in-world operation or it is done in a crafting grid.

**Comment by OvermindDL1** [comment]
It was an in-world operation, and yes putting water on a machine sounds terrifying but that is what was done (at least in pre-asp days but it is likely the same).

**Comment by MauveCloud** [comment]
GT machines are weird when it comes to water - expose them to rain and they ignite (and sometimes then explode iirc), but put them completely underwater and they're fine.
