### ISSUE TITLE
GT Shovel spawns Dire Slimes

### ISSUE THREAD

**Issue by Calenria** [Blood-Asp/GT5-Unofficial#146]
EnderZoo does not seem to recognize the Gregtech shovel as a valid tool to harvest Dirt.

@tterrag1098

**Comment by JasonMcRay** [comment]
I am not sure if this is GT issue, since for example it needed a fix on EnderZoo side for slime spawning with quarries.

**Comment by tterrag1098** [comment]
Hm...if the GT shovel says it's effective on dirt this should work fine.

**Comment by Blood-Asp** [comment]
The shovel is a valid tool for dirt. It works in advanture mode, so there should be nothing wrong.
