### ISSUE TITLE
Large Heat Exchanger not starting in v.27

### ISSUE THREAD

**Issue by pyure** [Blood-Asp/GT5-Unofficial#147]
Hopefully I'll close this issue myself.  Our LHE codefile is identical so I'm not sure where the problem is (yet).

Putting this here cuz I'm a good boy.

**Comment by pyure** [comment]
Blood, close this after you read it, its a KB item: warning, players MAY need to break/replace the Controller on any existing LHEs they have for them to work, after upgrading to v.27.  (Confirmed on my end, but not universally confirmed.  So just be aware of it if anyone submits an issue.

**Comment by Blood-Asp** [comment]
Ok, noted.
