### ISSUE TITLE
Glass Crystals are not obtainable

### ISSUE THREAD

**Issue by GusSmedstad** [Blood-Asp/GT5-Unofficial#1470]
Glass lenses are a way to make CPUs.

There are two ways to make Glass lenses: at Medium Voltage, you can grind down an Exquisite Glass Crystal, at High Voltage you can grind down a glass plate. This parallels many other gem lens recipes, where you must have Exquisite gems before HV.

While there are recipes leading up to Exquisite Glass Crystals via the Implosion Compressor, just as there are for gems, it's impossible to make them. Unlike the gem recipes, there are no Glass Crystal recipes that use glass dust.

There should be a way to make Glass Crystals using glass dust.

**Comment by YoungGT** [comment]
Well, actually there's another issue(#1418) that somebody want to remove these useless gems, including Glass. And I think it's better to remove the Glass gem instead of making use of it.
