### ISSUE TITLE
[5.09.32-pre4]---[AE_rv3_beta6] Crash

### ISSUE THREAD

**Issue by DiFaYaL** [Blood-Asp/GT5-Unofficial#1471]
When using a GT cable on the front of the facade, there is a crash
https://pastebin.com/rEh7PM1E
P.s Fix it

**Comment by leagris** [comment]
@DiFaYaL Can you reproduce without Optifine?
`          - Transformer: optifine.OptiFineClassTransformer`

**Comment by DiFaYaL** [comment]
@leagris
didn't not help
https://pastebin.com/SmQ1vw9a

**Comment by Dream-Master** [comment]
There is a ae2 fork not sure if it fix the problem

https://github.com/xsun2001/Applied-Energistics-2-Unofficial
