### ISSUE TITLE
Programmed Circuit(5)

### ISSUE THREAD

**Issue by tier940** [Blood-Asp/GT5-Unofficial#1476]
Assembling Machine in Programmed Circuit(5) -> enderpearl...!?
[link](https://gyazo.com/5fb44b89e2d3681a4890b1884d1537a4)

**Comment by YoungGT** [comment]
It's already fixed. See [there](https://github.com/Blood-Asp/GT5-Unofficial/commit/4e9e3db5ca1a5742fb204b831717e7659e17ff5a)
