### ISSUE TITLE
[Feature] Allow Magic Energy Absorbers (or Converters) to generate energy by consuming liquid Essentia

### ISSUE THREAD

**Issue by PaladinOne** [Blood-Asp/GT5-Unofficial#148]
The title says it all really. The Absorber can absorb Vis directly from Nodes, and the Converter can generate energy from various items including Shards, but there is currently no way of directly consuming Essentia, either from Warded Jars in the style of the Infusion Altar, or directly from Essentia Tube connections.

**Comment by Blood-Asp** [comment]
Magic Energy Absorber can now use Essentia stored in Phials or Jars with the following EU values (1=100EU per aspect)

	  AER(1)
	, ALIENIS(20)
	, AQUA(3)
	, ARBOR(1)
	, AURAM(16)
	, BESTIA(6)
	, COGNITO(2)
	, CORPUS(2)
	, ELECTRUM(24)
	, EXAMINIS(32)
	, FABRICO(2)
	, FAMES(2)
	, GELUM(1)
	, GRANUM(4)
	, HERBA(2)
	, HUMANUS(8)
	, IGNIS(4)
	, INSTRUMENTUM(4)
	, ITER(6)
	, LIMUS(3)
	, LUCRUM(32)
	, LUX(4)
	, MACHINA(16)
	, MAGNETO(24)
	, MESSIS(3)
	, METALLUM(8)
	, METO(2)
	, MORTUUS(16)
	, MOTUS(4)
	, NEBRISUM(48)
	, ORDO(8)
	, PANNUS(6)
	, PERDITIO(2)
	, PERFODIO(4)
	, PERMUTATIO(12)
	, POTENTIA(16)
	, PRAECANTIO(16)
	, RADIO(48)
	, SANO(24)
	, SENSUS(4)
	, SPIRITUS(24)
	, STRONTIO(64)
	, TELUM(6)
	, TERRA(1)
	, TEMPESTAS(64)
	, TENEBRAE(24)
	, TUTAMEN(12)
	, VACUOS(6)
	, VENENUM(16)
	, VICTUS(4)
	, VINCULUM(16)
	, VITIUM(48)
	, VITREUS(3)
	, VOLATUS(12)
	;

Do you think the amount is balanced?
