### ISSUE TITLE
Gregtech crash in initial settings

### ISSUE THREAD

**Issue by stopcraft** [Blood-Asp/GT5-Unofficial#1481]
I'll upload full logs

I created custom server based on FTB Beyond 1.10.2
so add Gregtech5U 1.10.2 and ExtraCells and It crashed
(with a very long repeating lines)

**Comment by stopcraft** [comment]
https://pastebin.com/qBqeWGkg

I removed ExtraCells

**Comment by draknyte1** [comment]
5.10 is not supported at all.
