### ISSUE TITLE
Magic Energy Absorber as Dragon Egg Siphon not exploding on multiple eggs

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#1482]
* gregtech-5.09.32pre4.jar

Relates to closed issue: #171

Even if configuration `config/GregTech/MachineStats.cfg` has
```YAML
B:MagicEnergyAbsorber.AllowMultipleEggs_false=false
```
Multiple Energy Absorbers on a Siphon mode will not explode even if each one uses an egg:
![image](https://user-images.githubusercontent.com/1111474/43370903-d40a54f4-9387-11e8-8135-9dce4a1a1aa0.png)

**Comment by draknyte1** [comment]
So fix it in your PR...

**Comment by leagris** [comment]
This is exactly how I spotted it ^^
I verified it was not my fault introducing a new bug, so I rolled the unmodified gregtech archive and confirm I am not responsible for that bug. Now I can fix this :)

**Comment by draknyte1** [comment]
So why raise an issue for it as opposed to just noting you fixed the issue in your PR?

Or even just using the old one..

**Comment by leagris** [comment]
Cause I like having issues documented I can reference in commits as reasons for changes to code.

**Comment by leagris** [comment]
So if someone wonders why I edited this code portion, I have this issue as a reason.

**Comment by draknyte1** [comment]
As noted, you have a PR open for this stuff and there's a pre-existing issue for the same thing. Please don't do this again in the future.
