### ISSUE TITLE
Chemical dyes have no color

### ISSUE THREAD

**Issue by GusSmedstad** [Blood-Asp/GT5-Unofficial#1483]
Most GT fluids have a color when held in a mod with transparent tanks, such as Railcraft's steel tanks or Simple Fluid Tanks. Sulfuric acid is orange, sodium persulfate is greenish blue, etc. All chemical dyes, regardless of color, show up as opaque white.

Mercury shows up as opaque white as well, but this may be intentional.

**Comment by leagris** [comment]
Later added GT Fluids uses dynamic multi-pass rendering for tint over a base greyscale icon.
Unfortunately, some mods assume fluid Icons are rendered from a single pass and only show you the greyscale texture.
This includes:
- Buildcraft tanks
- ExtraCells Fluid Terminal

**Comment by GusSmedstad** [comment]
To be perfectly clear that we’re on the same page, I’m talking about in-world rendering, rather than GUIs. However, I think what you’re saying still applies - it’s consistent with the way that ores are rendered, a grayscale texture tinted tinted by code.

For fluids, I guess the point is that you can re-use the grayscale texture and just provide tint information? That seems like a relatively small benefit compared to a large incompatibility with most other mods. Are there any mods that render those multi-pass GT fluids correctly? Any at all, aside from GT itself?

**Comment by draknyte1** [comment]
Every texture in Gregtech is desatured and recoloured 10000 times. 
The fluids should render properly in anything that isn't coded like shit. 

EIO tanks do from memory.

**Comment by GusSmedstad** [comment]
Whatever you may think of the coding standards of mods like Railcraft, there are a lot of people who want to use those mods. Or don’t want to switch to EnderIO’s fluid tanks, which have a number of drawbacks compared to the alternatives I know.

**Comment by draknyte1** [comment]
Nothing we're going to do to fix that, it's not our fault other mods behave incorrectly.

**Comment by leagris** [comment]
![image](https://user-images.githubusercontent.com/1111474/52541134-f70f6580-2d91-11e9-84f6-a6f522ae1bae.png)

That's good new actually :)
