### ISSUE TITLE
No Magic Energy Converter recipes for Balanced Shards or Shards added by Thaumcraft Add-Ons

### ISSUE THREAD

**Issue by PaladinOne** [Blood-Asp/GT5-Unofficial#149]
The Magic Energy Converter has recipes consuming for a wide variety of things, including Thaumcraft 4 primal Shards. However, it does not have a recipe to consume Thaumcraft Balanced Shards, and it does not have recipes for consuming shards from any Thaumcraft add-ons like Forbidden Magic, Tainted Magic, and Thaumic Tinkerer.

**Comment by Blood-Asp** [comment]
Can you make a list of all items you want to have added? My knowledge on the thaumcraft addons is a bit limited.

**Comment by PaladinOne** [comment]
Thaumcraft 4:
Balanced Shard

Forbidden Magic:
Wrath Shard
Envy Shard
Pride Shard
Lust Shard
Sloth Shard
Greed Shard
Gluttony Shard
Tainted Shard

Tainted Magic:
Warped Shard
Flux Shard
Shard of Creation

Thaumic Tinkerer: 
Nether Shard
Ender Shard

The Thaumic Horizons Ethereal Shard does not count here, as it serves an entirely different purpose.

And while we're on the point of items with "Shard" in their name, we might as well talk about Blood Magic as well.
Blood Magic:
Weak Blood Shard
Demon Blood Shard
Forbidden Magic:
Tainted Blood Shard
Sanguimancy:
Corrupted Blood Shard

**Comment by Blood-Asp** [comment]
Added to GT5.08.28
