### ISSUE TITLE
Oxygen&Hydrogen Producing from nothing

### ISSUE THREAD

**Issue by dalekin** [Blood-Asp/GT5-Unofficial#1491]
Oxygen and Hydrogen Producing

source recipes
Chemical Reactor: Nitrogen 1000 + Hydrogen 3000 = Ammonia 4000
Chemical Reactor: Ammonia 2000 + Oxygen 1250 + Circuit_12 = Nitric Oxide 1000
Chemical Reactor: Nitric Oxide 2000 + Oxygen 1000 = Nitrogen Dioxide 3000
Chemical Reactor: Nitrogen Dioxide 6000 + Oxygen 1000 + Water 3000 = Nitric Acid 10000
Chemical Reactor: Nitric Acid 1000 + Purified Pentlandite Ore 1 = Nickel sulfide water solution 9000 + Tiny Pile of Platinum Group Sludge Dust 1
Electrolyzer: Nickel sulfide water solution 9000 = H2SO4 8000 + Oxygen 1000 + Nickel Dust 1
Electrolyzer: H2SO4 (as cell) 7000 = Hydrogen 2000 + Oxygen 4000 + Sulfur 1

or normalized
14 Chemical Reactor: Nitrogen 14000 + Hydrogen 42000 = Ammonia 56000      
28 Chemical Reactor: Ammonia 56000 + Oxygen 35000 + Circuit_12 = Nitric Oxide 28000      
14 Chemical Reactor: Nitric Oxide 28000 + Oxygen 14000 = Nitrogen Dioxide 42000      
7 Chemical Reactor: Nitrogen Dioxide 42000 + Oxygen 7000 + Water 21000 = Nitric Acid 70000      
70 Chemical Reactor: Nitric Acid 70000 + Purified Pentlandite Ore 70 = Nickel sulfide water solution 630000 + Tiny Pile of Platinum Group Sludge Dust 70   
70 Electrolyzer: Nickel sulfide water solution 630000 = H2SO4 560000 + Oxygen 70000 + Nickel Dust 70
80 Electrolyzer: H2SO4 560000 = Hydrogen 160000 + Oxygen 320000 + Sulfur 80

result
in:
Oxygen 35000 + 14000 + 7000 = 56000
Water 21000
Nitrogen 14000
Hydrogen 42000
Pentlandite Ore 70

out:
Oxygen 70000 + 320000 = 390000
Sulfur 80
Hydrogen 160000
Nickel Dust 70
Tiny Pile of Platinum Group Sludge Dust 70

---
Oxygen 56k mb -> 390k mb. Profit = 696%
Hydrogen 42k -> 160k. Profit = 380%

where my wrong?

**Comment by leagris** [comment]
I think this is an overly complicated way of getting Oxygen and Hydrogen when you can Electrolyse water.
Chemistry in Gregtech is a very rough approximation of reality. You may like to lower your expectations here, because it is a game after-all.

**Comment by draknyte1** [comment]
Refer to https://github.com/Blood-Asp/GT5-Unofficial/pull/1322.

**Comment by dalekin** [comment]
to @leagris 
This is not the way, this is issue, when you get osmium from purified chalcopyrite or pentlandite dust.
300000 liters of oxygen from 70 purified dust,
100000 litres of hydrogen from 70 purified dust
and 80 sulfur from 70 purified dust
Materials appeared from empty place.
Well, closed... ok

**Comment by draknyte1** [comment]
If you want it reopened, actually state your issue. 
Don't just post irrelevant maths and expect us to figure it out. 

You're responsible for providing 110% of the information.
