### ISSUE TITLE
Bug localization with scaner mod.

### ISSUE THREAD

**Issue by Pilad** [Blood-Asp/GT5-Unofficial#1494]
There is a problem with displaying names of ores with a scanner.
https://github.com/Detrav/DetravScannerMod/releases
 If you disable this option in the Gregtech configuration.
B:UsePlaceholderForMaterialNamesInLangFile=true -->  B:UsePlaceholderForMaterialNamesInLangFile=false
Then everything is displayed well.
Bug https://media.discordapp.net/attachments/225549886219747328/487947351588208661/unknown.png
https://media.discordapp.net/attachments/225549886219747328/487947521948254219/unknown.png

**Comment by Krysinski** [comment]
Thats right, work fine after changes in a config.
![image](https://user-images.githubusercontent.com/15215123/45253893-53073580-b37f-11e8-9bb3-beb4d6c2c7cc.png)

**Comment by Pilad** [comment]
About that and wrote. In theory, this option will probably fix the bug with the assembly line. The description of the items in the book. This is when you play on the server. In a single game in the book, the components are written correctly.
