### ISSUE TITLE
Sulfuric acid recipe

### ISSUE THREAD

**Issue by Erixonich** [Blood-Asp/GT5-Unofficial#1499]
Hello there!
Just opened an issue https://github.com/GTNewHorizons/NewHorizons/issues/3728

Did someone leave this recipe intentionally? We have good alternative! Why don't you just comment lines 1730 and 1729)

https://github.com/Blood-Asp/GT5-Unofficial/blob/1568303ecaf7ffe6b79b1e0a3c27cee3ccf4d9dc/src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java#L1729
https://github.com/Blood-Asp/GT5-Unofficial/blob/1568303ecaf7ffe6b79b1e0a3c27cee3ccf4d9dc/src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java#L1730

**Comment by draknyte1** [comment]
> I also vote no here. The oxygen route has twice the efficiency per H2S so it will always be preferred by higher-tier players anyways. For low tier players it presents an interesting choice between efficiency or saving their oxygen, which they need a lot of for steel and other chemistry. Realism should not be the only goal of GT, it should be a mix of realism and nonrealism for the purpose of fun gameplay.

=== Pending Closure ===
