### ISSUE TITLE
please use another icon for the 'ultimate battery'

### ISSUE THREAD

**Issue by pftbest** [Blood-Asp/GT5-Unofficial#15]
ZPM is a single use energy source, by its definition. so having a battery that looks like ZPM but is rechargeable is not consistent with a fictional universe where it came from.

**Comment by Blood-Asp** [comment]
Then make me new Icons i can use. Making a new set of icons takes a lot more time than the actual coding of a new Battery.

**Comment by pftbest** [comment]
then please don't close this feature request until i make them. somebody else could come up with a better ones than mine.

**Comment by Blood-Asp** [comment]
The open state is a reminder for what i have to do. Once i have icons to add, i will reopen it until i have added them.

**Comment by Blood-Asp** [comment]
Adding new textures with next update.

**Comment by Blood-Asp** [comment]
Exchanged textures.
