### ISSUE TITLE
Large Turbine automation

### ISSUE THREAD

**Issue by AiwendilCiunio** [Blood-Asp/GT5-Unofficial#150]
I made this: 
<a href="http://imgur.com/X4fvuj8"><img src="http://i.imgur.com/X4fvuj8.png" title="source: imgur.com" /></a>

Quite a beast, but there's a problem. I set the LHE so that it only turns on when I'm low on power (machine controller, redstone covers etc). Works great, but - when a Large Turbine runs out of steam, it needs to be manually restarted every time. It cannot be automated with machine controller since the turbine block is surrounded by casings, which are not tile entities, therefore I can't place redstone receivers on them (I tried redstone receiver IN on the turbine block, but it didn't work).

I think it's kind of retarded that there's no way to automate these expensive multiblocks. I can't leave the LHE running all the time, since without the distilled water from turbines it would explode very quickly (I have a Distillation Tower supplying the LHE, but it's not enough).

Can't it be made so when a Large Turbine had been "enabled" with a hammer once, it would automatically turn on whenever it got steam? This would make more sense I think.

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/pull/143

**Comment by pyure** [comment]
You're welcome Aiwen :)
