### ISSUE TITLE
Naquadah Generator change

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#152]
Right now we only have the single block generators which produce lots of energy without needing any support infrastructure all you need to find is a naquadah vein and you have 100% reliable energy for weeks.

I think it would be cool to remove the naquadah generator and add Naquadah Fuel Rods for the nuclear reactor instead.
Those Fuel Rods would be something like 1-2 times the heat output of uranium fuel rods and 10-50 times eu output (don't know how that would affect the fluid reactor though).

**Comment by Blood-Asp** [comment]
Naquadah fuel rods would not work with higher output in fluid reactors. 

Also, while Naquadah is extremely powerfull, it is meant to be limited. Bigger End with HEE, GalacticGreg Asteroids and Naquadah bees might have thrown of the balance, so i will try to think of a way to rebalance.

Without that other mods, naquadah is limited to one vein max on a whole server and it becomes extremely valuable. Burning it in a generator becomes something you dont want to do in that case.
