### ISSUE TITLE
[BackTools Compatibility Issue] Invisible Inventory/Failed render of tool on Player

### ISSUE THREAD

**Issue by UnlimatedStone9** [Blood-Asp/GT5-Unofficial#1520]
I'm writing this bug report to bring attention to a mod compatibility issue, granted the mod is not really useful but it is visually appealing
In its simplest form whenever a player holds a MetaTool from GregTech, perhaps even a MetaItem, and then selects away from it in their hotbar the game tries to render that tool on the players back (because of the BackTools mod), this results in, at least for TerraFirmaCrafts Inventory, the player inventory being invisible and the items in it too, the only way to fix this is to remove GT's items from the inventory and select a different tool like an iron pickaxe for example
The GregTech tool also does not render on the players back either, I assume you would need to contact the mod author to have GT's tools blacklisted from showing on a players back or perhaps make a pull request to fix it yourself? I'm not sure, either way, this is what the issue looks like:
![image](https://user-images.githubusercontent.com/40124890/53096401-f9528c00-3516-11e9-95d6-81089d6b9ced.png)
Note that I have armor on but it does not appear in the armor slots, the inventory was also full at the time of taking this image
Link to the BackTools mod: https://minecraft.curseforge.com/projects/back-tools

**Comment by draknyte1** [comment]
Backtools works fine with just GT by itself.

**Comment by UnlimatedStone9** [comment]
Fair enough, Thanks anyways
