### ISSUE TITLE
Enchantment fatal error

### ISSUE THREAD

**Issue by byalexeykh** [Blood-Asp/GT5-Unofficial#1522]
Minecraft version: 1.12.2
Forge version: forge-1.12.2-14.23.5.2815
GregTech version: gregtech-1.12.2-1.5.20.179

Other mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AppleCore, Aroma1997Core, AromaBackup, AromaBackuprecovery, Backpack, Baubles, Botania, ChickenChunks, Clumps, CodeChicken Lib, CoroUtil Library, Emoticons, Extended Mod Config, Extended Renderer, FTB Library, Forestry, Gravestone Mod, GregTech Community Edition, Hammer Core, Immersive Engineering, Inventory Tweaks, Iron Chest, IvToolkit, Just Enough Items, Lycanites Arctic Mobs, Lycanites Demon Mobs, Lycanites Desert Mobs, Lycanites Elemental Mobs, Lycanites Forest Mobs, Lycanites Freshwater Mobs, Lycanites Inferno Mobs, Lycanites Jungle Mobs, Lycanites Mobs, Lycanites Mountain Mobs, Lycanites Plains Mobs, Lycanites Saltwater Mobs, Lycanites Shadow Mobs, Lycanites Swamp Mobs, Mantle, Morpheus, NetherPortalFix, OMLib, Open Modular Turrets, Pam's HarvestCraft, Railcraft, Realistic Item Drops, Recurrent Complex, Sampling Performance Profiler, Secret Rooms 5, SecretRooms Hooks, Special AI, Spice of Life: Carrot Edition, SpongeForge, Tinkers' Construct, Tree Chopper, YABBA, Zombie Awareness.

Logs: https://paste.dimdev.org/acinapaleg.mccrash

P.S.

Looks like the gregtech mod is in conflict with some kind of enchantment that called "Ender.damage"

**Comment by byalexeykh** [comment]
EDIT 1:

There is no conflict, there is some variable that has a null value in itself, and minecraft crashes with a JavaNullException error.

**Comment by Blood-Asp** [comment]
MC 1.12 is GTCE so go here: https://github.com/GregTechCE/GregTech
