### ISSUE TITLE
Endium Processing

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#154]
Hardcore Ender Expansion adds Endium Ore could you add ore processing for it ? :)
(right now its smelting 1 ore -> 1 ingot)

**Comment by Blood-Asp** [comment]
Hmm, it should allready work. What oredict tag does the ore have?

**Comment by DarknessShadow** [comment]
oreHeeEndium

**Comment by Blood-Asp** [comment]
I see.. the "Hee" part is not standart conform, so the GT automation cant identify it. I will see if there is an easy fix for it. If not this issue is too minor to do much work.

**Comment by DarknessShadow** [comment]
Isn't the easiest solution adding another oredict tag to it?

**Comment by Blood-Asp** [comment]
Hopefully fixed. Can't test since HEE crashes in DEV enviroment and testing compiled version is annoying.

**Comment by JasonMcRay** [comment]
Tested this with GT5.08.29... Still not working.

**Comment by Blood-Asp** [comment]
Just noticed that i forgot to give endium an ID as Material, so it will naturally not generate.

**Comment by Blood-Asp** [comment]
https://www.dropbox.com/s/g5y3sju9aisqz3a/gregtech_1.7.10-5.08.30test.jar?dl=0
HEE somehow does not work in my test enviroment. So someone pease test for me if endium now works.

**Comment by JasonMcRay** [comment]
I can, but not soonar than tomorrow (if i dont forget) :p

**Comment by JasonMcRay** [comment]
Oh and of course I have forgot to test it. Writing this to my ToDoList on my phone, will test it today (if it is not too late). Sorry @Blood-Asp

**Comment by JasonMcRay** [comment]
@Blood-Asp I wanted to test the 5.08.30 with endium....The file no longer available. :(

**Comment by Blood-Asp** [comment]
It allready got deleted. So just restored it: https://www.dropbox.com/s/g5y3sju9aisqz3a/gregtech_1.7.10-5.08.30test.jar?dl=0

**Comment by JasonMcRay** [comment]
Ok testing:
I can see Endium ingots added by GT, but the Endium Ore still can be only smelted into HEE Endium Ingot, no maceration recipes or other.

Also would it be possible to use similiar color for the endium as it is with HEE (blue)
![2015-09-26_21 47 40](https://cloud.githubusercontent.com/assets/4236895/10119511/642f2946-6498-11e5-949e-d18882869ac7.png)

**Comment by chylex** [comment]
What's the dev environment crash?

**Comment by Blood-Asp** [comment]
Forgot to answer... 
I have the same problem with forestry. It loads just fine, i can even start up a world. After a few secs of playing it starts to lagg after 10 more secs it completely stops. A minute of standstill later the JVM closes. So likely something overflows in there... But no crash reports or someting. The ram also stays low enough.

**Comment by Blood-Asp** [comment]
Soo... now it really works.
