### ISSUE TITLE
Crash on server stop

### ISSUE THREAD

**Issue by LuxusDarkangel** [Blood-Asp/GT5-Unofficial#155]
Suddenly it started to crash when i use the /stop command on my server.
Crash report: http://pastebin.com/XQ173mNn

**Comment by LuxusDarkangel** [comment]
You have any plans on releasing a fix for this soon? It's not a big deal, but i'm going to release a hotfix for my modpack and i would like to solve this on that patch.
Just asking :)

**Comment by Blood-Asp** [comment]
I had only a few min so far to look at this error. From how it seems something, that is not GT, changes the world class of minecraft.

So identify if this happens with only GT installed. If not, narrow down the mod behind it.

Bukkit/Cauldron could be the reason. Or any other mod changing the worldData.

**Comment by LuxusDarkangel** [comment]
I've been able to reproduce it using:
1.- AiImprovements
2.- Biomes o' Plenty
3.- Ic2 (just because it's a dependancy)
4.- GregTech (sure you didn't expected i had this installed)
5.- NEI (GregTech crashes if you haven't NEI installed, you want it on another issue?)
6.- Codechickencore (For NEI)
7.- nTweaks

Using these mods together causes that crash, and it's not a Kcauldron fault, btw.

**Comment by 008** [comment]
btw update you KCauldron and JAVA

**Comment by LuxusDarkangel** [comment]
I'm using the latest KCauldron version, but it's named as 2 versions below. I don't think java is the problem anyway.

**Comment by LuxusDarkangel** [comment]
Ok, i'll close this issue. After a loooooot of hours researching about this i found it's a way more complex problem and not an issue with your mod at all. Thank you for your patience.
