### ISSUE TITLE
Cant pump items into certain machines

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#157]
Packager doesnt accept items like Wires or Rubber Sheets from pipes or other item transport methods (test in 5.08.27 and 5.09.01).

**Comment by JasonMcRay** [comment]
After bit more of playing I am also unable to pump items into Assembling machine when it contains any Integrated Curcuit. When I take out the Integrated Curctui, it accepts items, but when it has Integrated Curcuit, it doesnt work. (@Blood-Asp is it ok to have it in one issue, or do you want me to open second one?)

**Comment by Blood-Asp** [comment]
seems to have the same reason, so a single issue should be fine.

**Comment by JasonMcRay** [comment]
Little update on the Assembling Machine, if it will help... I have found out that the Assembling Machine will accept the wire with Integrated Circuit (configuration == 24) already in place ONLY if it also has enough Molten Rubber to actually start processing.

**Comment by Blood-Asp** [comment]
Just tried to change that, but is seems the GT recipe system does not allow for the fluid to be inserted last.

In case your problem is with logistic pipes that one order at the same time orders fluid to be produced in another machine, so the fluid comes late, how about adding a buffer  beween LP and assembling machine that inserts the parts once the fluid is ready?

**Comment by JasonMcRay** [comment]
Yup i have that system with buffer already made. Using eIO conduits to pump the items "constantly" in from the buffer chest.

I found the assembler issue when I was doing some tests in my test world.

**Comment by JasonMcRay** [comment]
@Blood-Asp Did you fixed the Packager in latest 5.08? Or did you forgot because you closed this issue prematurely :D If you did fixed it it seems like its still bugged with some items (http://forum.feed-the-beast.com/threads/1-7-10-infitech-2-modpack-v3-1-9-gregtech-balanced-hard-mode-modpack-updated-09-13-2015.50185/page-326#post-1428434)
