### ISSUE TITLE
Fluid route

### ISSUE THREAD

**Issue by DeckerCHAN** [Blood-Asp/GT5-Unofficial#159]
Is there any mechanism to control fluid direction like BC's pipe in GT? If not, is there any possibility to add this function?

**Comment by PaladinOne** [comment]
Shutter Covers? Attach to the side of a pipe, right-click the cover with a Screwdriver to set it to 'Input Only' or 'Output Only' [or some such, I might have the exact messages wrong]

**Comment by DeckerCHAN** [comment]
Ok, it's my bad. What I mean that is control certain fluid to certain direction. Eg: Let steam and super heated steam, which all generate by head exchanger, inject to there own path.

**Comment by Blood-Asp** [comment]
I allready thought about it, but currently not sure how exactly i would implement it.

**Comment by DeckerCHAN** [comment]
How about gives pump another working mode: Import/Export(Certain fluid) and hit with cell to set  fluid. Or make a fluid filter just like item filter, consume energe and pump fluid to certain direction.
