### ISSUE TITLE
A crash with the compatibility of Minechem V6 unoffical

### ISSUE THREAD

**Issue by Oldmemory1** [Blood-Asp/GT5-Unofficial#1595]
I am sorry that I am poor at English.Before I see the main menu,when the game is loaded,it crashed.The crash reports seemed that gregtech and minechem caused this crash,I do not know how to solve it.Here is the crash report https://paste.ubuntu.com/p/mrSFRv87Hz/

**Comment by MauveCloud** [comment]
> UCE	gregtech{MC1710} [GregTech] (gregtech-5.09.33.02.jar)

Where did you get this version of GregTech?  That version numbering scheme is used by GTNH rather than "base" GT5u which numbers them with things like 5.09.32pre6 instead.  However, if that were really from GTNH, it would be really out of date, since the latest release is 5.09.40.16.  Additionally, I checked the repo for the 5.09.33.02 tag, and the line number mentioned in the stack trace is part of getBurnTime rather than addAutoGeneratedHydroCrackedFluid.

**Comment by Oldmemory1** [comment]
> > UCE	gregtech{MC1710} [GregTech] (gregtech-5.09.33.02.jar)
> 
> Where did you get this version of GregTech? That version numbering scheme is used by GTNH rather than "base" GT5u which numbers them with things like 5.09.32pre6 instead. However, if that were really from GTNH, it would be really out of date, since the latest release is 5.09.40.16. Additionally, I checked the repo for the 5.09.33.02 tag, and the line number mentioned in the stack trace is part of getBurnTime rather than addAutoGeneratedHydroCrackedFluid.

I got it(Gregtech5.09.33.02) from github.Not from gtnh.The game keep crash until I remove one of those mods(minechem and gregtech). However when I use minechem V5 or remove the dragon api,the game can be loaded successfully.

**Comment by MauveCloud** [comment]
Okay, I hadn't noticed that (pre)release was there in the base repo.  Looking at the source code, I can see why this happens. Line 1611 (of GT_Proxy.java) performs an unchecked cast of the mGas field in the Materials enum, but line 1671 picks up fluids that are already in the fluid registry (which might not be of class GT_Fluid) for adding to that field on line 1685.

Now I'm confused that I couldn't reproduce this myself with minechem V6, GT 5.09.31, and minimal other mods, or that switching to minechem V5 or removing dragon api would work for you.
