### ISSUE TITLE
[Suggstion] Redstone Scale and Redstone Display

### ISSUE THREAD

**Issue by AiwendilCiunio** [Blood-Asp/GT5-Unofficial#160]
I absolutely loved these in GT4. Is it possible that when you're done with important stuff you could think about recreating them?

**Comment by pyure** [comment]
Can you provide a summary of what they do, or at least a link to a wiki or something?

**Comment by AiwendilCiunio** [comment]
This video covers the blocks (also Button Panel which is cool too). I couldn't find other info.

**Comment by pyure** [comment]
If you attached a url, I don't see it :\

**Comment by AiwendilCiunio** [comment]
Lol, I'm sorry :D.

Here it is:
https://www.youtube.com/watch?v=ygkR-KkwHvU

**Comment by Blood-Asp** [comment]
Hmm, found the old code of it. But still... quite complex. So many different textures and stuff... Well, i will let it stay on the to do list with low prio.

**Comment by OvermindDL1** [comment]
I was just looking for these on my server, thought I was going crazy not being able to find them...  >.>

**Comment by Blood-Asp** [comment]
Added to idea collection
