### ISSUE TITLE
Generalize heat exchanger

### ISSUE THREAD

**Issue by lawremi** [Blood-Asp/GT5-Unofficial#163]
There are many other fluids that one may want to heat and cool with a heat exchanger. Could the heat exchanger multiblock be rewritten to be based on recipes instead? To preserve the explosion mechanic, there could be a fluid blacklist. I would be happy to contribute a PR if you're open to the idea.

**Comment by Blood-Asp** [comment]
You are free to do that.

I understand it right, that in the basic version there would be no change in function for players, right? Just that adding hot to cold fluids per minetweaker or just simpler ingame would be possible.

**Comment by lawremi** [comment]
That's correct, via the API in my case. It's not high on my TODO list, but I will need it eventually.

**Comment by axlegear** [comment]
I was thinking of this just recently of allowing multiple fluids or materials and allow heat exchange based on thermal conductivity.  If you'd like to discuss it just message me.

**Comment by leagris** [comment]
Lots of GT fluids are just at fringe for their fluid state Kelvins.
What it means, If you are gonna transfer heat from molten iron is you will get solid iron.
So you may need to either work like a fluid solidifier with two fluid inputs. One hotter then the other.
But then, not all fluids have hot states right?
You are going to introduce complex thermodynamic and material temperature can't be static anymore.
I think this can become overly complex. Mods have different materials or fluids Ids for same raw material at different temperatures. (Ice, Water, Steam, Superheated steam).
There are so many inconsistencies in handling heat within mods and within Gregtech alone.
Where do the heat from solidifiers go?
Where do the heat from Vacfreez go?
Why wooden chests don't catch fire when put hot tungstensteel ingots inside?
Why are hot ingots not cooled when dropped into a water block? (this one could go as low tech cooling of hot ingots)
...

**Comment by lawremi** [comment]
I was only suggesting a recipe-based interface, so that we could register heat exchanges between specific fluids. Typically, these would be a state change (between gas and liquid) or a significant change in temperature (between the default fluid state and a "hot" state, for example). But these would be explicit recipes. Automatically deriving them would be too complicated, especially across mods.

**Comment by Blood-Asp** [comment]
Closing this to clean up issues.
