### ISSUE TITLE
Ore generation in the End

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#164]
I've made a waypoint at every ore vein that I find and those are the results (only from the end):

Tin: 82
Iridium: 35
Lapis: 19
Nickel: 9
Naquadah: 4
Olivine: 3
Uran: 3
Emerald: 2
Plutonium: 2
Wulfenite: 2
Neodymium: 2
Manganese: 1
Tungsten: 1

Iridium veins are everywhere is that intended?
Also naquadah veins aren't really rare at all if we ignore tin, iridium and lapis veins.

Those are the results from using the Infitech2 modpack.

**Comment by Dream-Master** [comment]
You can change everything in the config file. High, amount and size. Worldgeneration.cfg
You can add own mixes also.

**Comment by Blood-Asp** [comment]
That should be a GalacticGreg Issue. But well, my mod so somehow fine...

The defaults should be quite different and with this huge number of asteroids it should not be a bad luck thing. Will take a look if i can find a issue in the randomization code.

**Comment by Blood-Asp** [comment]
I'm pretty sure it is this issue:
http://forum.industrial-craft.net/index.php?page=Thread&postID=192920#post192920
If greg agrees, i have to fix it in GT5 and GalacticGreg...

**Comment by Blood-Asp** [comment]
Fixed that spawn issue in GG 0.6. But someone should test that to be sure.

**Comment by Nex4rius** [comment]
I've started to play again and now I have the results if its fixed.
(sorry for being so late but I stopped playing minecraft for some weeks)

Tin: 28
Nickel: 7
Lapis: 6
Olivine: 5
Manganese: 3
Iridium: 1
Thorium: 1
Tungsten: 1

Your fix drastically lowered iridium veins but there are still lots of tin veins.

(Tested) Played in a new world of InfiTech2 v3.2
