### ISSUE TITLE
5.08.27 battery bug

### ISSUE THREAD

**Issue by iCookie1** [Blood-Asp/GT5-Unofficial#165]
When rightclicking a machine (tried LV battery buffer and Advanced Steam Turbine) with a battery in your hand (tried small lithium battery and medium cadmium battery) the battery will instantly fill up with EU. This happens on 5.08.26 for me and also in 5.08.27

**Comment by Blood-Asp** [comment]
Does not happen to me can you make sure it does happen with only GT and IC2 installed for you? Should that be the case, maybe a IC2 or forge change? But no idea how that could happen.

**Comment by iCookie1** [comment]
Thanks for the response

Hm, seems the bug is on my side then. I'll try running with only IC2 and GT, also will try updating forge
