### ISSUE TITLE
Replicator sometimes produces weird stuff

### ISSUE THREAD

**Issue by AiwendilCiunio** [Blood-Asp/GT5-Unofficial#167]
http://i.imgur.com/Ln6BNAU.png

This is what one of my Replicators produces. It works in recipes like chrome dust, it looks like chrome dust, has the same metadata as chrome dust, but it won't unify even when held in inventory (you can see "normal" chrome dust 2 lines below).

This is a minor issue but I thought it should be reported.

**Comment by Blood-Asp** [comment]
looks like the data orb is somehow broken...

**Comment by Blood-Asp** [comment]
Can you look at the NBT tags? With minetweaker installed just take it into the hand an type "/mt hand"
I would like to know the output for that from the data orb and both chrome variants you have.
