### ISSUE TITLE
Vanilla Oregen

### ISSUE THREAD

**Issue by Crdl-Pls** [Blood-Asp/GT5-Unofficial#168]
Just out of curiosity, I assume you disable all vanilla oregen when generating GT ores? If you do then another mod is seemingly overriding this and generating it anyway, I think it may be highlands. http://i.imgur.com/RdaJCIK.png
BTW it's moo :3

**Comment by mr10movie** [comment]
Yeah sorry used my alt accidentally. If u need screenshots or something let me know.

**Comment by Blood-Asp** [comment]
Yes, must be some other mod messing with vanilla oregen...

**Comment by mr10movie** [comment]
Yep it was Highlands, this can be closed.
