### ISSUE TITLE
GT Tools don't go into Mine and Blade slots

### ISSUE THREAD

**Issue by mr10movie** [Blood-Asp/GT5-Unofficial#169]
NEW ISSUE WHICH MAY ALSO NOT BE YOUR FAULT!

GT tools don't go into Mine and blade duel wielding slots. May have something to do with this?
https://github.com/Mine-and-blade-admin/Battlegear2/blob/ec28d7cd28e12a638d9e29fc905a93d829ea9ac6/battlegear%20mod%20src/minecraft/mods/battlegear2/api/weapons/WeaponRegistry.java

**Comment by Blood-Asp** [comment]
I know for sure this was allready mentioned to Greg long ago before he started working on GT6.

If i remember right, the GT equipment must be registered exspecially to work. This must be either done on M&B side or i must add support on GT side. No idea how much work that is on M&B side, but i'm currently not really motivated to add jet another API to GT...

**Comment by mr10movie** [comment]
All I know is the M and B dev is quiet until he updates and then goes quiet again. Not amazing but that's who we're dealing with.

**Comment by Blood-Asp** [comment]
Closing this to clean up issues.
