### ISSUE TITLE
Extraction of EXBL flowers

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#170]
As discussed here: https://github.com/JasonMcRay/InfiTech-1.7/issues/340

List of EXBL flowers and their produced dyes.
Output, Input

minecraft:dye:2, [ExtrabiomesXL:waterplant1]);
minecraft:dye:1, [ExtrabiomesXL:vines]);
minecraft:dye:11, [ExtrabiomesXL:flower3:11]);
minecraft:dye:5, [ExtrabiomesXL:flower3:10]);
minecraft:dye:14, [ExtrabiomesXL:flower3:9]);
minecraft:dye:14, [ExtrabiomesXL:flower3:8]);
minecraft:dye:1, [ExtrabiomesXL:flower3:7]);
minecraft:dye:1, [ExtrabiomesXL:flower3:6]);
minecraft:dye:11, [ExtrabiomesXL:flower3:5]);
minecraft:dye:9, [ExtrabiomesXL:flower3]);
minecraft:dye:11, [ExtrabiomesXL:flower3:4]);
minecraft:dye:13, [ExtrabiomesXL:flower3:3]);
minecraft:dye:5, [ExtrabiomesXL:flower1:3]);
minecraft:dye:5, [ExtrabiomesXL:flower3:2]);
minecraft:dye:12, [ExtrabiomesXL:flower1:1]);
minecraft:dye:11, [ExtrabiomesXL:flower2:15]);
minecraft:dye:1, [ExtrabiomesXL:flower2:14]);
minecraft:dye:9, [ExtrabiomesXL:flower2:13]);
minecraft:dye:14, [ExtrabiomesXL:flower2:12]);
minecraft:dye:7, [ExtrabiomesXL:flower2:11]);
minecraft:dye:7, [ExtrabiomesXL:flower1:7]);
minecraft:dye:11, [ExtrabiomesXL:flower1:2]);
minecraft:dye:6, [ExtrabiomesXL:flower3:13]);
minecraft:dye:12, [ExtrabiomesXL:flower2:6]);
minecraft:dye:10, [ExtrabiomesXL:flower2:5]);
minecraft:dye:1, [ExtrabiomesXL:flower2:2]);
minecraft:dye:9, [ExtrabiomesXL:flower2:1]);
minecraft:dye:13, [ExtrabiomesXL:flower2]);

**Comment by JasonMcRay** [comment]
@Blood-Asp few more extrabiomes flowers have been found without extraction recipes. Reason why it has been found now is that EXBL added their own dye (so players would not be able to exchange flower for lapis (blue dye), or bone meal (white dye) so I missed it in the list.
ExtrabiomesXL:flower2:7 - Black Dye
ExtrabiomesXL:flower3:1 - Blue Dye
ExtrabiomesXL:flower3:12 - Blue Dye
ExtrabiomesXL:flower2:4 - Blue Dye
ExtrabiomesXL:flower1:6 - Brown Dye
ExtrabiomesXL:flower2:8 - White Dye
ExtrabiomesXL:flower2:3 - White Dye

**Comment by Blood-Asp** [comment]
added them
