### ISSUE TITLE
[Suggestion] Titanium

### ISSUE THREAD

**Issue by AiwendilCiunio** [Blood-Asp/GT5-Unofficial#173]
I see that in 5.09 you replicated (more or less) the Kroll process of making titanium :) 
That's nice, but what I don't like is that Bauxite is used to make titanium. This doesn't make sense as bauxite is only used to use aluminium in real world, there's no titanium in it. To make titanium titanite ore and rutile are mainly used. 
If you're going for more "realistic" titanium production I think you should consider changing Bauxite outputs.

**Comment by Blood-Asp** [comment]
According to Wikipedia, Bauxit does contain small amounts of Iron and Titanium oxides. While it is not enough IRL to really use it, all GT ores have at last one byproduct, so processing is mroe complex. So i prefer to keep the current bauxit with titanium.
