### ISSUE TITLE
[Suggestion] Fusion: Molten Vanadium + Hydrogen = Chrome

### ISSUE THREAD

**Issue by pyure** [Blood-Asp/GT5-Unofficial#174]
Been discussing this with MigukNamja:  We need a later-game method of generating chrome that is different than the one we used in the earlier electrical age and doesn't rely on processing redstone.

This more-or-less makes sense (if we're just looking at atomic numbers) and additionally gives us a use for vanadium, which is pretty lacking right now.

Recommend Mark 1 fusion, but exact power requirements at your discretion.

**Comment by MigukNamja** [comment]
Thanks, Pyure. I don't have a problem with the Chrome requirement for Fusion reactors. It's supposed to be difficult/tedious/expensive to make. However, it takes a ridiculous amount of redstone.. I wish there was an alternative recipe (besides bees). And, Vanadium seems underutilized.

**Comment by AiwendilCiunio** [comment]
Well this is just a copypasta from Wikipedia, maybe it's also worth considering:

The two main products of chromium ore refining are ferrochromium and metallic chromium. For those products the ore smelter process differs considerably. For the production of ferrochromium, the chromite ore (FeCr2O4) is reduced in large scale in electric arc furnace or in smaller smelters with either aluminium or silicon in an aluminothermic reaction.[31]


Chromium ore output in 2002[32]
For the production of pure chromium, the iron has to be separated from the chromium in a two step roasting and leaching process. The chromite ore is heated with a mixture of calcium carbonate and sodium carbonate in the presence of air. The chromium is oxidized to the hexavalent form, while the iron forms the stable Fe2O3. The subsequent leaching at higher elevated temperatures dissolves the chromates and leaves the insoluble iron oxide. The chromate is converted by sulfuric acid into the dichromate.[31]

4 FeCr2O4 + 8 Na2CO3 + 7 O2 → 8 Na2CrO4 + 2 Fe2O3 + 8 CO2
2 Na2CrO4 + H2SO4 → Na2Cr2O7 + Na2SO4 + H2O
The dichromate is converted to the chromium(III) oxide by reduction with carbon and then reduced in an aluminothermic reaction to chromium.[31]

Na2Cr2O7 + 2 C → Cr2O3 + Na2CO3 + CO
Cr2O3 + 2 Al → Al2O3 + 2 Cr

**Comment by pyure** [comment]
As a chemical process that would certainly make sense, but Greg is hellbent against providing chromium ore, and I think we should respect that.  Also we'd have to add worldgen :)

The fusion solution is a much later-game notion and doesn't subvert Greg's Grand Scheme.

**Comment by pyure** [comment]
Citation:
http://forum.feed-the-beast.com/threads/gregtech-suggestion-thread-to-do-list.64899/

Specifically:
"Denied Suggestions:
Any kind of Chrome Ore, ANY KIND!!!"

**Comment by AiwendilCiunio** [comment]
In the same thread it also says:

Magnesium (Mg, 12) + Magnesium (Mg, 12) = Chromium (Cr, 24)

**Comment by Blood-Asp** [comment]
There are some points i have to say about this. 
First: Why Chrome fusion, when all the chrome is needed to build the fusion reactor?
So adding a fusion recipe for chrome is no problem and i will do it. But it does not really help.
Second: Do not forget Replication! There is allready a way to make lots of chrome and is is even quite cheap. Chrome is only 1/8 of the cost to replicate as Pu, Iridium or Osmium that often get replicated.

**Comment by pyure** [comment]
Good feedback.  I like replication as alternative method too, although I'm not super fond of replication itself (creating a farm of some sort just to feed it into the recycler kinda bugs me).  That said, I'd forgotten about replication as usual, this is a fine method of getting chrome.

Regarding fusion, I'm told chrome is needed for the MK2 version, hence why its sensible to allow the fusion reaction as a reward in MK1.  In this case its just "fun and cool" to do it with your brand new big fusion toy.

**Comment by DarknessShadow** [comment]
>First: Why Chrome fusion, when all the chrome is needed to build the fusion reactor?
So adding a fusion recipe for chrome is no problem and i will do it. But it does not really help.

Maybe to make a second fusion reactor? One for power and one for the other recipes?

Btw there is already a fusion recipe thats never useful
Hydrogen + Maganese -> Iron
and compared to that the chrome recipe would be really good.

I think the Vanadium + Hydrogen recipe is better than the Mg + Mg recipe because it mean Vanadium is also useful for something else than cables.

I think more fusion recipes = AWESOME MORE FUSION RECIPES !!!

**Comment by DarknessShadow** [comment]
>Regarding fusion, I'm told chrome is needed for the MK2 version, hence why its sensible to allow the fusion reaction as a reward in MK1. In this case its just "fun and cool" to do it with your brand new big fusion toy.

You don't need chrome to make mk2 fusion reactor only for the mk1.

**Comment by Blood-Asp** [comment]
The Mg+Mg recipe is not even possible the way i implemented the reactor. It allways must be 2 different fluids.

**Comment by pyure** [comment]
@DarknessShadow : (fusion is awesome) lol agreed :)
@AiwendilCiunio : Awesome!  That means Chrome-from-fusion is already blessed by Greg.  V + H probably more sensible though.
@DarknessShadow : (no chrome in MK2) I must have misunderstood then.  That said, its still good because cool.

**Comment by Blood-Asp** [comment]
Also, you can allways list more fusion recipes. ;)
As long they make sense and are not outright broken, implementing them is easy.

**Comment by AiwendilCiunio** [comment]
Well one that I was looking for and was kinda suprised that wasn't there is Tungsten recipe.

What about Pd+As or Mo+Y. It sort of adds up to W atomic number and would be a way to utilize these useless metals.

**Comment by MigukNamja** [comment]
Regarding Chrome for a Fusion reactor, it's true you don't need more Chrome if you're upgrading your reactor in-place. However, if you're building a 2nd or subsequent reactor, you need all that Chrome all over again. Gameplay-wise, it would be cool if the 1st Fusion reactor helped you to build the 2nd and subsequent reactor.

And, I'm not wedded to the specific recipe to make it as long as it's reasonable. Since Mg + Mg is not possible, V + H seems nice Vanadium is somewhat underutilized.

**Comment by Blood-Asp** [comment]
I gave Vanadium at last one more use in GT 5.09.xx

**Comment by MigukNamja** [comment]
Thanks, Blood Asp !
