### ISSUE TITLE
Fusion Reactor GUI NEI features

### ISSUE THREAD

**Issue by willis936** [Blood-Asp/GT5-Unofficial#177]
The old fusion reactors had an NEI button that opened up the NEI fusion receipe list.  Also the NEI slot graphic in the GUI does not line up with the multimachine inventory slot.

Also the NEI fusion recipe list background image only uses one fluid slot even though two are shown (a dedicated image for fusion recipes would be a solution).

**Comment by Blood-Asp** [comment]
Only visual issue, so a low priority.
