### ISSUE TITLE
Ultimate Battery Infeasible to Charge

### ISSUE THREAD

**Issue by PaladinOne** [Blood-Asp/GT5-Unofficial#178]
The Ultimate Battery, while true to its name in tiering, is not actually feasible to charge. A charge rate of only 524,288EU/t means that its 9-quintillion EU capacity would take 27,892 years to fill assuming full charge rate per tick and sustained 20TPS.

If the Ultimate Battery were increased to MAX Voltage tier, its minimum charge time would be reduced to a much more reasonable 6.8 years.

**Comment by Blood-Asp** [comment]
The early versions containing the Ultimate Battery even had this. But the IC2 API has the mechanic of Integer.MAX_VALUE = Full in one tick, so batteries of max voltage do not work.

Also, the ultimate battery impossible to charge is actually the gag with the tooltip. ;)
