### ISSUE TITLE
A problem with multiplayer in my modpack

### ISSUE THREAD

**Issue by Tictim** [Blood-Asp/GT5-Unofficial#179]
Hi.
I've made a simple modpack, but it has a trouble.

First, it works well in single player. However, when I try to open it in multi player, it gives error messages and goes back to the title or crashes. It's like when I used the Gregtech 5 Unofficial with forge version 1445-1481.

Linked is the client's crash log.
http://pastebin.com/Qqkksd8j

Lastly, for your information, both of server and client were using Forge ver 10.13.3.1428.

**Comment by Blood-Asp** [comment]
Seems the bug was allready in 1428, so i added it to the unusable range of forge versions. 1490+1492 should work at last.
