### ISSUE TITLE
Bio-Fossil drops as Essensce Berry

### ISSUE THREAD

**Issue by xXGandalfXx** [Blood-Asp/GT5-Unofficial#18]
Hey again,

I have founded new bugs on server... Singleplayer works.

If i try to drop out a bio-fossil, i drop a essence berry. I get also a berry by dropping from a fossil ore.
It turns instantly in a berry.

And the bug with the converting in inventory is back. But all only on Servers.

**Comment by Blood-Asp** [comment]
That somehow sounds like the server did not update, only the client.

**Comment by xXGandalfXx** [comment]
No, server and client versions are the same (08.09)... But when i deinstall a custom mod by my friend. 
The bug is fixed... Sorry for this bug report, but he edited the oredictionary of gt or what else... I cannot programm minecraft mods. But the first bug report was not caused by this mod...

**Comment by Blood-Asp** [comment]
So the problem is not GT.
