### ISSUE TITLE
Output busses are not "smart"

### ISSUE THREAD

**Issue by Timeslice42** [Blood-Asp/GT5-Unofficial#180]
There's a bug that's annoyed me for a long time, but I never remember to report it: the output bus on multiblocks isn't "smart". For example if I put 64 iron ore and 64 calcite into an EBF, I end up with 64 small dark ash, and three stacks of 63 iron ingots. The last three iron gets vaporized because it couldn't find a slot with 3 free spots, despite the fact that there are three slots with 1 free spot.

**Comment by willis936** [comment]
You need to put a conveyor belt on the bus to move the output to a chest.

**Comment by DarknessShadow** [comment]
>You need to put a conveyor belt on the bus to move the output to a chest.

Either I completely missunderstood @Timeslice42 problem or @willis936 "solution" doesn't have anything to do with the problem

**Comment by willis936** [comment]
My understanding is the problem is that when the output bus is full items get lost.  That is the intended behavior.  This sounds like a fringe case of getting burned by the intended behavior and strictly speaking this case isn't intended.  A conveyor belt would fix his problem.

**Comment by PaladinOne** [comment]
A conveyor belt would *work around* his problem. The actual problem is that the busses only check for space in single slots, and if they can't find the space in any slot, they void the entire output stack, rather than placing as many as possible or spreading them across multiple output slots.

**Comment by Timeslice42** [comment]
And PaladinOne nails it in one.

**Comment by Blood-Asp** [comment]
Really minor improvement that needs quite a bit of coding. Will get a really low priority... So as long none does a pull request, it will likely stay as it is now.
