### ISSUE TITLE
Fluid canner compressed air cell output go into wrong slot

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#183]
When inserting an IC2 Compressed Air Cell into a Fluid Canner, fluid:Air output into the fluid input slot instead of one of output slots.

**Comment by Blood-Asp** [comment]
After looking at the canner code a bit, i noticed that it only has one tank and is quite differently coded from most other machines. Likely a relict from old GT2/3 day. Pumping in/out and all automation works just fine, so i will let it be as it is.
