### ISSUE TITLE
Helium Gas texture

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#184]
That one you see in the recipes has the missing texture icon:
![2015-09-15_20 20 09](https://cloud.githubusercontent.com/assets/4236895/9885772/3b548430-5be7-11e5-95f9-d12130af4546.png)

GT5.09.02

**Comment by Dream-Master** [comment]
It is Galacticrafts fault. I post this issue allready but no changes same as the oil (not be a fluid ) thing.

https://github.com/micdoodle8/Galacticraft/issues/1664

**Comment by Blood-Asp** [comment]
exactly, this is a galacticraft issure replacing the GT helium without providing a still texture.
