### ISSUE TITLE
Again Packager

### ISSUE THREAD

**Issue by Zac666** [Blood-Asp/GT5-Unofficial#185]
Packager again stop accept "tiny pile of dust" and "nuggets" with "Schematic(3x3)" from pipes and etc.
Also packager accepts both of them without any Schematics.

**Comment by SapientMC** [comment]
Addition info.
All tiny and small piles acceptable with Schematic (Dust), but there are no way to combine nuggets into ingots at all now.

**Comment by AiwendilCiunio** [comment]
I can confirm this. 
I tried chest bufer-> packager, doesn't work. Same setup worked fine a few updates before.
