### ISSUE TITLE
Hatch/Bus tooltips

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#186]
Could you please add different tooltips to i/o hatches/buses of different tiers.
It would be nice if they contain number of slots/liters.

**Comment by pyure** [comment]
Blood, I should be able to take care of this.  I already added the names on my end, and adding slots/liters is a great idea.

**Comment by Blood-Asp** [comment]
allright, i'm waiting for your PR.

**Comment by pyure** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/pull/193

**Comment by Blood-Asp** [comment]
Merged PR.
