### ISSUE TITLE
type filter doesn't catch granite ore

### ISSUE THREAD

**Issue by willis936** [Blood-Asp/GT5-Unofficial#190]
When the type filter is set to filter ore blocks it doesn't see granite ores as ore blocks.

**Comment by Blood-Asp** [comment]
there shoud be other types to choose from like "oreGranite", "oreBlackGranite" or "oreRedGranite".

**Comment by willis936** [comment]
So multiple filters must be used?

**Comment by DarknessShadow** [comment]
I used only one type filter for normal ores but it also allowed some granit ores to go through.

**Comment by Blood-Asp** [comment]
I only know that the type filter supports all oredict prefixes GT knows. And there are multiple types of "ore" prefixes. Maybe there is a wrong and a right ore prefix to choose?
