### ISSUE TITLE
Regulator Shutter (idea)

### ISSUE THREAD

**Issue by Drawfox** [Blood-Asp/GT5-Unofficial#191]
I run into a problem trying to setup several mass fabricator - the amplifabricator distribution.
As the output is very low and slow, is almost impossible to distribute that evenly to more than one machine.
It is possible to setup a shutter to allow only a certain amount of liquid (or item) to pass trough, similar to a chest buffer?
So, I could set the first shutter to only allow 6L to pass, per fluid movement, for example (as GT pipes seems to take more than one tick to output fluid). No more, no less would pass. 
Until there, liquid would accumulate on that container (if there's no other place to go). When those 6L or more accumulate on that pipe, only 6L they would be outputted on the pipe line. 
As it flows, each pipe connected to a machine would have a shutter set to allow only 1L go on that direction, while the rest would flows normally by the main line. 
Eventually, it would end distributing to each machine evenly.

**Comment by willis936** [comment]
Another cool feature this cover might have is forcing a consistent rate similar to how the IC2 fluid regulators work.  As of right now having an optimal flow of steam feed a large turbine through a GT pipe causes about a 10% hit in efficiency compared to a fluid regulator.  I assume this has to do with how GT fluid pipes update their internal tank.  Shutters don't solve the problem (pumps might though I haven't tested it).

**Comment by pyure** [comment]
You mean, the ability to restrict flow to a specific amount? Like "only allow 200L/t through"?

**Comment by willis936** [comment]
Yes and as long as it would normally be able to allow that amount through it does.  Preferably giving priority to the regulator over other pipe ports (this is functionality that already exists using plates, shutters, and pumps so it isn't "broken" as long as the regulator is priced appropriately).

**Comment by pyure** [comment]
Wait, regulator, what?
I thought this was supposed to replace the regulator.

**Comment by willis936** [comment]
When referring to regulator there I meant the proposed regulator cover.

**Comment by pyure** [comment]
Oh ok I get it.  Sorry for some reason I thought we were proposing changes to the existing shutter.

do you have any ideas of how one would adjust the flow rate?  Screwdrivering from 1L/t to 2000L/t would kinda suck.  Not sure if we're able to add "shift-screwdrivering" into the equation easily either.

**Comment by willis936** [comment]
The only thing I can reasonably think of outside of adding a GUI (not typical and a lot of work) is the same system used in the redstone transmitters and receivers.  It isn't documented anywhere and you have to figure out how screwing which parts of the cover affects the value.  I still haven't figured it out and take several screwdriver uses to get the desired value but it's one existing method to do something similar.

**Comment by pyure** [comment]
Yeah that system drives me nuts dude :p

**Comment by Drawfox** [comment]
My idea is to add a new functionality to the shutter module, or to add a new cover.
For example, I have 6 mass fabricators now. Maybe one or two amplifabricators could handle them, but as there's no way to distribute 6l of fluid to 6 machines, I'm using 6 amplifabricators, one to each MassFab. Even so, I am using a Railcraft cart to distribute 9 scraps each, because there's no GT way to do it. This shutter used on a item pipe could be used to achieve the same end here.
I even thought that this could be used instead of regulators, but GT pipes doesn't seem to output per tick, so I assume that wouldn't work like that. The IC2 regulator only works, because it have an internal buffer tank.

**Comment by Timeslice42** [comment]
What's wrong with using the IC2 fluid regulator? If you have GT then you have IC2...
