### ISSUE TITLE
Annoying sounds with FT Worktable

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#194]
I am gonna leave this for you @Blood-Asp :)
https://github.com/ForestryMC/ForestryMC/issues/842#issuecomment-143371773

GT5.09
FT: 3.6.7

**Comment by AiwendilCiunio** [comment]
Same thing with AE2 autocrafting. Try coding a maintenance hatch for example - the noise you get by hovering over it is ridiculous.

**Comment by mezz** [comment]
I have a PR open here for it: https://github.com/Blood-Asp/GT5-Unofficial/pull/195

**Comment by Blood-Asp** [comment]
I saw it. Will take care of all PRs and bugs on the weekend. Currently working on new features, so bugfixing at the same time will mess stuff up.
