### ISSUE TITLE
Cannot make GT recipes for IC2 reactor components

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#197]
The NaK coolant cells and heat vents (especially the advanced) do not work as per their recipes if you are using the latest IC2 version with GT5U v 5.09.02 and IC2 2.2.780

The recipes show client-side in NEI, but will not actually produce the object.  Server-side it will let you pick it up briefly then it 'undoes' it.  Either way it's not possible to craft many IC2 reactor objects as a result.

**Comment by Dream-Master** [comment]
Ic2 changing the meta data in the new version.

**Comment by axlegear** [comment]
Any known fix presently or wait for GT5 update?

**Comment by Dream-Master** [comment]
Minetweaker

**Comment by Blood-Asp** [comment]
duplicate of https://github.com/Blood-Asp/GT5-Unofficial/issues/187
