### ISSUE TITLE
Large Boiler does not works with Distilled Water

### ISSUE THREAD

**Issue by Drawfox** [Blood-Asp/GT5-Unofficial#198]
As the title says, Large Tungstensteel Boiler explodes if hatches have with distilled water instead regular water.
That does not allows us to make a closed system with Large turbines;

**Comment by PaladinOne** [comment]
This is also entirely illogical. If anything, Distilled Water should be *better* than normal Water in a Boiler.

**Comment by pyure** [comment]
Is there any particular reason distilled water should be superior?

Is there any particular reason distilled water should be inferior/unworkable?  

(asking for quasi-realistic feedback here)

**Comment by Drawfox** [comment]
Only thing I know is that there's less impurities on distilled water, so more efficiency because there's less cleaning/maintenance (wikipedia).
Gameplay speaking, I don't know, I'll be happy enough with boilers running normally.

**Comment by pyure** [comment]
I can't think of too many ways to make it work "better" per se, other than consuming less energy per steam output.  The ratio of water:steam would still need to be exactly the same.

@Blood-Asp can you tag this as an enhancement?  Its one line of code, I can take care of it.

**Comment by Blood-Asp** [comment]
Distilled Water should work in the boiler. No reason why not. But better? Nope.

**Comment by pyure** [comment]
Agreed.

**Comment by PaladinOne** [comment]
Yeah my original comment was mostly pointing out the illogic of it causing the boiler to explode. It was made thinking about the IC2 Steam Generator Calcifying if you used non-Distilled Water in it. It doesn't mean we should actually make Distilled Water better than regular Water.

**Comment by pyure** [comment]
This whole discussion kinda made me realize that we can easily "make" distilled water by putting steam from another source into a GT large turbine.  I'm guessing in this case we're trying to make a closed loop with the Large Boiler + Large turbine (which is fair) but we'll be creating distilled water outta regular water.

Blood Asp, do we care?  We can theoretically require the Large Boiler to require distilled water if you want, but its not a great solution (we'd end up blowing up a lot of bases in the process too)

**Comment by Blood-Asp** [comment]
Creating distilled water as side product is fine. It is realistic and there should be no balance issue. Boiler+Turbine only to produce distilled water would no sane man do.

**Comment by pyure** [comment]
Good thanks.

**Comment by pyure** [comment]
done.  Fair warning: don't try to feed both distilled water + normal water to the boiler in multiple input hatches.  While nothing bad will usually happen, the following scenario can still cause an explosion:
* The boiler requires 100mb of Distilled Water or Water this tick
* Hatch A has 50mb of distilled water
* Hatch B has 50mb of normal water

Both tests will fail to get 100mB of water and the boiler will craterize.  ( I don't care enough atm to avoid that)

**Comment by Blood-Asp** [comment]
merged in.
