### ISSUE TITLE
Arc furnace in Processing Array

### ISSUE THREAD

**Issue by AiwendilCiunio** [Blood-Asp/GT5-Unofficial#202]
From what I tested it doesn't work. Can it be added? I kind of need that for my fusion setup.

**Comment by Blood-Asp** [comment]
Yes, should be easy to add. But i'm interested were in the fusion setup you need an arc furnace?

**Comment by AiwendilCiunio** [comment]
Wood -> charcoal. Not sure if this recipe is part of default GT or was it added by Jason, but I need charcoal for mk3 fusion. I wouldn't like to disclose more information since I don't wanna spoil the surprise. I came up with a nice fuel idea :)

**Comment by JasonMcRay** [comment]
Wood charcoal in arc furnace is my addition :p

**Comment by AiwendilCiunio** [comment]
I just tried normal electric furnaces, and they don't work either :/

**Comment by Blood-Asp** [comment]
For that you have the multi smelter. ;)
