### ISSUE TITLE
Reactor -  Iridium Neutron Reflector

### ISSUE THREAD

**Issue by INVICTRA** [Blood-Asp/GT5-Unofficial#203]
The  Iridium Neutron Reflector seems to not boost EU production at the same % as other IC2 Reflectors.

I think its at 20% value of IC2 Reflectors.

Tested in:
- gregtech_1.7.10-5.08.29 (industrialcraft-2-2.2.780-experimental)
- gregtech_1.7.10-5.08.23 (industrialcraft-2-2.2.742-experimental)

**Comment by Blood-Asp** [comment]
Sounds different from: http://bt.industrial-craft.net/view.php?id=1615
So i will take a look at it.

**Comment by INVICTRA** [comment]
Oh wait... I always used Thorium. Yes the problem is indeed only for Thorium Fuel. Others fuel work!

**Comment by Blood-Asp** [comment]
Then the issue is that IC2 produces too much and the iridium reflector the right amount.

**Comment by INVICTRA** [comment]
That might be right.... but why doesn't that make me happy =/

**Comment by PaulMadsen** [comment]
Problem is not just for thorium.  It happens as well with MOX fuel.
https://github.com/Beyond-Reality/BeyondRealityModPack/issues/330

**Comment by Blood-Asp** [comment]
thats a seperate issue.
