### ISSUE TITLE
Additional OreDict names for ores

### ISSUE THREAD

**Issue by AT611** [Blood-Asp/GT5-Unofficial#204]
We're using Logistics Pipes on our server, creating ore processing plants based on those pipes, and there is one small problem, when we're setting up filters using OreDict ItemSink modules: all versions (rock-based) of any ore have different ore dictionary names. For example:
"oreRedstone" for generic (overworld) redstone ore
"oreEndstoneRedstone" for endstone one
"oreRedgraniteRedstone" for red granite based
Could you add additional names for ores, like "oreRedstoneAny"? Because we need to add all variations of an GT ore we met into our filters all the time, and that's not only annoying, but also requires more chassis pipes to be installed on a machine.

**Comment by Blood-Asp** [comment]
Would it not maybe easier to make a default high priority itemsink and place an GT type filter behind? That would save lots of programming also.

**Comment by AT611** [comment]
That sounds like an option (and I'll give it a try in some way, shape or form), but not all ores needs to be processed the same way the default ones have. And collecting all the ores in one spot may be problematic: there is no priorities (only by module type, like "itemsink > terminus" and so on) in itemsink modules, and setting the "default route" on a processing plant is not an option for most of us. We could use the type filter to filter out all crushed ores from a HV macerator from all "bonus" dusts, but that's also not a problem with the current way we use. The problem is mostly with ores.

**Comment by Blood-Asp** [comment]
tested and can only say: nope, too many issues trough this to do it.
