### ISSUE TITLE
Small bug with Soldering iron.

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#207]
It does not use fine wires during maintenance if only 1 wire left in inventory.
v5.08.30

**Comment by JasonMcRay** [comment]
Can confirm also happening with 5.09.06

**Comment by axlegear** [comment]
It works for me, however you have to try more than once.  It will use the last one, then leave a colorless 'zero uses' version which, if dropped, spawns a stone block.

**Comment by SapientMC** [comment]
I've done 3 success maintenance with single fine wire (and it still was in my inventory).
