### ISSUE TITLE
Controller Extension Hatch (Idea)

### ISSUE THREAD

**Issue by Drawfox** [Blood-Asp/GT5-Unofficial#210]
I have seen the issue with the limited control over multiblock's controller, sorry if this is already planned or there's a motive to not do it.

Here is my idea: could we have a block(hatch) the extends the multiblock main controller's capacity of accepting covers, like the the Maintenance and Machine controller cover?
It could use the same placement configuration available to the other hatches on the multibocks.
That would allow us to have those covers on Large Turbines, which is impossible right now, and to add an extra on Large boilers/LHE/etc... - that would be very useful.

**Comment by DarknessShadow** [comment]
>That would allow us to have those covers on Large Turbines, which is impossible right now,

Its not impossible you just need the wireless redstone covers.

**Comment by Drawfox** [comment]
How so, on the inside?

**Comment by Blood-Asp** [comment]
Well... To turn it on/off, just control the input bus. The "needs maintainance cover" can be placed on the controller and an wireless redstone transmitter on the other side of the controller.

**Comment by Drawfox** [comment]
Good to know, thanks.
For the boilers and such, there's still no way to do it, right?

**Comment by AiwendilCiunio** [comment]
Of course there is. That's what we have wireless covers for.

**Comment by willis936** [comment]
No the turbine is impossible to control at this point.  It's very strict multiblock and almost feels like the lack of automation is intentional.  The machine block must have empty air blocks in front and behind and be surrounded on the sides by casings which don't handle covers or pass redstone signals like vanilla blocks.  The RS in covers don't fix this issue (yet, I made a separate issue).

**Comment by Blood-Asp** [comment]
As allready said, there is nothing that is not allready possible to automate. It is just sometimes nessary to be a bit creative.
