### ISSUE TITLE
Distiller not accepting biomass

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#211]
The GT distiller will not accept Biomass (from IC2) for producing ethanol, despite having a recipe for such.

**Comment by Dream-Master** [comment]
Using GTTweaker and make a recipes for it.

**Comment by axlegear** [comment]
Let me know when you get a script for it so I can add it

**Comment by Dream-Master** [comment]
When i be back home i can make one sure.
You need the GTTWeaker 1.0.9 and Minetweaker 3.0.10 for it.

**Comment by pyure** [comment]
Can somebody tell me what the "balanced" ratio of IC2 biomass to GT ethanol should be?  IC2 has an inflated biofuel cycle which makes a lot of sense in an IC2 closed loop but less sense when it interacts with other mods.

**Comment by Dream-Master** [comment]
I found some recipes i add all ready to my scripts. I thinking i am using the ic2 ratio.
(works only with Minetweaker and GTTweaker)
(You can change the Circuit to a nother number than 4. 
(example <gregtech:gt.integrated_circuit:8> * 0)
````
// --- Biogas
import mods.gregtech.Distillery;
Distillery.addRecipe(<liquid:ic2biogas> * 250, <gregtech:gt.integrated_circuit:4> * 0, <liquid:ic2biomass> * 8, 80, 30, false);
````

**Comment by Dream-Master** [comment]
Biomass from Ic2 and from Forestry are not the same so i am not sure if a recipe would be right balanced ?

**Comment by pyure** [comment]
Probably not: IC2 produces tons of fluids in the cycle because the processing costs are really high.

But whatever gets done we can fix it later if there's a balance issue.  I'll probably fix this tonight (and obviously the MT scripting is a perfect workaround in the meantime)

**Comment by axlegear** [comment]
IIRC, Ethanol has a burn value of 128kEU per L, so I would imagine fair would be a 4:1 ratio or less.  Biomass isn't a great fuel source IRL, so I don't see why it should be great in MC.

Could go full-throttle and make a realistic system, but i'm not sure there'd be a lot of use for wet/dry cake.

**Comment by Dream-Master** [comment]
Forestry Biomass to Ethanol have a 4:1 ratio in the Refinery from Buildcraft.
Not sure how the ratio in the GT Distillation Tower is.

**Comment by pyure** [comment]
Wild guess: it will probably have to get nerfed to at least 16:1.  

No real idea without actual full cycle production numbers however.  Whatever Blood did I'm just gonna make sure it works properly.

**Comment by axlegear** [comment]
Sounds good to me.

**Comment by Dream-Master** [comment]
Recipe duration and eu/ticks?

**Comment by Blood-Asp** [comment]
10L Ic2 biomass produce 200L biogas. Biogas has a burn value of 32EU/L. I added that to the distillation tower but somehow missed the Distillery.
