### ISSUE TITLE
Metal smelting in the arc furnace (Idea)

### ISSUE THREAD

**Issue by Invincible92** [Blood-Asp/GT5-Unofficial#212]
At the moment, the Arc Furnace serves as a recycler for machines and components to ingots and a iron > wrought iron/ copper > annealed copper converter. 

As an idea, could it be possible to add a config (or some kind of it) for allowing all metal dusts (impure, pure and normal) to be smelted into ingots ? I mean, a config that swaps the smelting for all metals except the low tier ones (bronze, copper, tin, lead, zinc, bismuth and bismuth bronze) to be smelted in the arc furnace (without using oxigen). That option would add a important use to the arc furnace instead of being a plain recycler of components.

Currently I'm trying to do this using a MT script, but it's a tedious procedure. I think DreamMaster would like this idea.

**Comment by Blood-Asp** [comment]
About the same Greg did in GT6?

**Comment by Dream-Master** [comment]
To recycling every thing is use a lot of line minetweaker code. It is possible but implement this inside the code would be better i think .

**Comment by leagris** [comment]
I'd say, yeah quite like what greg did in GT6 but with this rule:
If molten metal temperature is <1811K then ok smelt in regular furnaces
Then change iron smelting into furnace to output wrought iron you have to re-smelt to get iron.
Every higher temperature metals have to go in a blast furnace.
It should not break balance and interacting with other mods.

Implementing this would require to traverse ore dictionary for every smeltables, make match against gregtech versions, query fluid version Kelvins, remove output for all other mods furnaces.

**Comment by Blood-Asp** [comment]
Closing this to clean up issues.
