### ISSUE TITLE
GT fluid cells consumed by right-clicking tanks/barrels

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#213]
BC tanks and Extra Utility barrels will consume the tin fluid cell if you right-click them to deposit the fluid if they contain GT fluids.  (Some other mods' fluids are also affected, but not all.  IE, forestry fluids seem to work fine, as do IC2 fluids, weirdly.  Thus why I think it's a GT issue.  I've tested and confirmed using chlorine, mercury, and hydrogen cells.)

**Comment by Blood-Asp** [comment]
Just checked cells like chlorine, mercury, hydrogen, nitrogen, sulfuric acid, IC2 and For biomass on a BC tank. All worked as expected. ExU is not installed on my dev enviroment, so i can't test.

**Comment by axlegear** [comment]
Strange.  Will ask Bear to test.  He's great at breaking stuff.

**Comment by axlegear** [comment]
Bear says it's intended behavior, so I guess you can close this as a non-issue.

**Comment by Blood-Asp** [comment]
The old Tin Cells, that GT simply expands are singleuse. GT made them more expensive and multiuse, but some other mods still use the old behavior.
