### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dream-Master** [Blood-Asp/GT5-Unofficial#214]
I get this Crash with Gregtech 5.08.30
(mod that i update in my pack Modtweaker 2.0.9.3.152, Galaxy Space 2.5beta, Galacticraft 3.0.12.359)

Crash Log
https://gist.github.com/Dream-Master/f89e44f5556da27b42f1#file-gt

**Comment by Dream-Master** [comment]
It crash after long waiting phase from GT.

**Comment by Dream-Master** [comment]
With Galaxy space 2.4 it works weird.

**Comment by Blood-Asp** [comment]
There are two achievements with the name "Aluminium" it seems galaxy space also added that achievement in the latest update.

**Comment by Dream-Master** [comment]
So is there a solution on your side or i have  to ask on Galaxy Sapce Mod side?

**Comment by Blood-Asp** [comment]
The easiest way is to disable the achievements in the config. The only real fix is, that one side renames it's achievements. I should have given all achievements internal names prefixed by an "gt." but noticed it months later and now changing them would mean that all players loose all gt achievements. :(

**Comment by pyure** [comment]
could you add a new achievement for aluminium and disable it by default? There would be two in the system but only one active at a time in theory.

**Comment by Dream-Master** [comment]
@pyure That would be a good idea. I write to BlesseNtumbe the Modauthor from galaxy Space too.

**Comment by Dream-Master** [comment]
In wich config i can disabled the archivents?

**Comment by Blood-Asp** [comment]
i can rename them only, but that would break the achievements for these that allready got them.
With only renaming aluminium it should be more or less fine, but this was not the first time happening, so a real fix should be done... breaking allready gotten achievements is what stops me doing it...

**Comment by Blood-Asp** [comment]
GregTech.cfg general/B:EnableAchievements=true

**Comment by Dream-Master** [comment]
Thanks will try this so long we get a fix from which side whatever.

**Comment by Blood-Asp** [comment]
fixed for sure by renaming gt aluminium achievement. Will annoy likely some...
I guess a full rename will be done when i start adding GT5U stuff to GTE.

**Comment by Dream-Master** [comment]
Thanks
