### ISSUE TITLE
private redstone covers

### ISSUE THREAD

**Issue by willis936** [Blood-Asp/GT5-Unofficial#217]
It would be nice to have the redstone TX/RX covers be able to be set to a private mode so that other players on the server wouldn't run into them.  I know there are 4B frequencies to play with but security through obscurity asks for trouble.

**Comment by Blood-Asp** [comment]
That is a bit difficult to implement in the current system... but i will see if i have an idea how to make it easy.

**Comment by Blood-Asp** [comment]
Closing this to clean up issues.
