### ISSUE TITLE
Bad Weather/Electric Problems Achievs Issue

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#218]
The subtitle of the achiev says: Loose a machine due to ...
The thing is: when the machine explodes with the appropriate conditions for the achiev, I dont get it. If it is not a bug and I was supposed to get this achiev some other way, how then?

**Comment by Blood-Asp** [comment]
That is a bit difficult for me to test.
Looking in the code, there are two things that might be the reason.
Sometimes after server restart, machines loose their owner. In that case the achievement can't be activated correctly and fails. But this does not happen with newly placed machines, so it might be the other.
The other is in the code and a bit random, i will try if i can fix that in the next update.

**Comment by Antillar** [comment]
I have tested this in singleplayer, so it has to be a problem in code.

**Comment by axlegear** [comment]
Also it should be 'lose' not 'loose'

**Comment by Antillar** [comment]
Hey I am Russian. Do you really think I care about spelling?

**Comment by Blood-Asp** [comment]
Thats meant for me to fix. So an seperate issue, but now allready fixed. ;)

**Comment by Antillar** [comment]
What version is it fixed in? Do I have to install experimental build?

**Comment by Blood-Asp** [comment]
I meant the spelling, but your bug is also likely fixed. The latest experimental has the fix, but until it is in the stable version it will take a few days.
