### ISSUE TITLE
Plate-cover bug in 14 version

### ISSUE THREAD

**Issue by Zac666** [Blood-Asp/GT5-Unofficial#22]
All already installed plate like cover after update from 13 ver to 14 get textures block on which they installed + plate no longer can be installed like cover.
Sorry for shitty english, but i guess screenshots must explain what i mean:
http://i.imgur.com/5rJBrTu.png
http://i.imgur.com/IaErHfm.png

**Comment by Blood-Asp** [comment]
Fixed in 5.08.15
