### ISSUE TITLE
Hot pipes no longer damage

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#220]
Forgot about this one.

Steam pipes in GT5U no longer harm you if you touch them, ditto for lava or any other heated pipe that should burn your face off.

**Comment by Blood-Asp** [comment]
Covers attached to pipes now protect against damage. Does your pipe have a cover?

**Comment by axlegear** [comment]
Nope, just a standard steam pipe.

**Comment by bear989** [comment]
I watcged a newer player jump on a large steel pipe full of steam and nothing. no covers just a pipe

**Comment by xarses** [comment]
heated large steel pipes == no damage. No covers

**Comment by JasonMcRay** [comment]
Can confirm this with GT5.09.06.. Standing on Bronze Pipes full on Lava, not taking any damage (naked)

**Comment by Blood-Asp** [comment]
It seems i inverted the check... Only pipes with covers did damage... Fixed in next update.
