### ISSUE TITLE
Crash (during the firework)

### ISSUE THREAD

**Issue by Dream-Master** [Blood-Asp/GT5-Unofficial#221]
I get this crash if i unlock the first vanilla arcivement (during the firework)
Gt 5.08.30

Is this a gt issue or/and a Galacticraft issue?

Crash Log:
https://gist.github.com/Dream-Master/d4aeeee0c18c1264f1e1#file-gt

**Comment by Blood-Asp** [comment]
Does that happen allways? Something calls the "playerTick" twice at the same time. That should not happen, GT does not know how to handle that and crashes. I can somehow prevent that crash, but some random other mod is really at fault here.

**Comment by Dream-Master** [comment]
Open Eyes said it is Galacticraft Core fault. I post the issue there too. My guess is that at the beginning when the games load checking for updates open the Galacticraft Race menu and when you open the inventory at this time too to many events happen at one time.(only my guess)(tested with a large modpack)

http://openeye.openmods.info/crashes/1c3479f595ded84318521d272881415f

**Comment by Blood-Asp** [comment]
Hmm, right. Missed Galacticraft in the stacktrace reading it the first time. Good chance it does trigger the playertickevent again.

**Comment by Dream-Master** [comment]
Galacticraft have a new Version i am testing it now.

**Comment by Dream-Master** [comment]
I think it is fixed on GC side.
