### ISSUE TITLE
[Suggestion] Palladium in EBF

### ISSUE THREAD

**Issue by Dream-Master** [Blood-Asp/GT5-Unofficial#223]
Palladium is a high Tier metal i think. It have a hot Ingot variant but no Blast Furnace Recipe.
Can you add one and disabled it in the normal Furnace like Tungsten Steel. If you add it please for 5.08 too.Thanks

**Comment by Dream-Master** [comment]
Change Line 89 in  gregtech api enums Materials.java
````````
Palladium			(  52, TextureSet.SET_SHINY				,   8.0F,    512,  2, 1|2  |8   |32|64|128                  , 128, 128, 128,   0,	"Palladium"						,    0,       0,       1828, 1828, T, F,   4,   1,   1, Dyes.dyeGray		, Element.Pd		, Arrays.asList(new TC_AspectStack(TC_Aspects.METALLUM, 3))),
````````

change only false to true (F, F --> T,F)

Sorry i can't make a pull request because my forked repository looks different and dont match with your folder structure.

**Comment by AiwendilCiunio** [comment]
Do you realize that palladium has absolutely no use except for mediocre quality tools? Why would you want to make it harder to obtain?

**Comment by Dream-Master** [comment]
I make some recipes with minetweaker so I using it. I think it is a mistake that it not have a ebf recipe. Useful or not the fix is so small I think blood asp can do it.

**Comment by Dream-Master** [comment]
I want it in the ebf because it is a high tier material. If the recipes to hard for you I can make some cheap minetweaker recipes for you. :-)

**Comment by leagris** [comment]
I'd put Osmium and Iridum into High tier EBF as well.

EBF Smelting Iridium shall consume 480EU/t with 2719K heat capacity and require molten salt for fusion.
EBF Osmium shall consume 2048EU/t with 3306.2K heat capacity. It shall not be possible to machine-work osmium; So bye-bye rolling/extruding (Osmium is incredibly dense, hard and brittle)/ So, maybe it shall be kept as an alloy compound.

**Comment by axlegear** [comment]
I second the Iridium and Osmium in in the IBF, requiring Nichrome coil 512v blast furnace.  None of the rest, tho.  As it stands, if you run across a palladium vein early on (like I did) you can blast your way to endgame in half the time.

**Comment by Blood-Asp** [comment]
hmm, right. will change all 3 materials in gt5.09

**Comment by Dream-Master** [comment]
I change it in 5.08. allready for my pack. Will update to 5.09 if this Version is ready for Servers.
