### ISSUE TITLE
What's the license of GregTech?

### ISSUE THREAD

**Issue by panda2134** [Blood-Asp/GT5-Unofficial#225]
I wanna write a small addon for GT,which may use some of the textures of GT.
Am I permitted to use them?

**Comment by danbka33** [comment]
> License
> This Mod as a whole is property of me, Gregorius Techneticies (aka GregoriusT). Don't redistribute and claim any of it as not being owned by me (All Rights Reserved). Only Modpacks are allowed to redistribute the original Mod Jars in order to keep their Download links reliable. I am not responsible for any Damage done by a modified Jar File.
> 
> People, who contributed to the current state of the Mod are credited in the mcmod.info.

**Comment by Blood-Asp** [comment]
The original GT license also counts for my fork. http://forum.industrial-craft.net/index.php?page=Thread&threadID=7156

**Comment by redmage17** [comment]
The license is no longer in that post.....
