### ISSUE TITLE
Fuel Rods Crafting issue

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#226]
Dual and Quad Fuel Rods arent craftable...

If you craft Fuel Rod inside GT Canning Machine it gives out Fuel Rod without any Metadata. This cant be used in crafting. IC2 Canning Machine gives out Fuel Rods with Meta, which then can be used in crafting Dual Rods.

Dual Rods normaly requires those Rods with META.

It eventually can be crafted. This is the wierd part.

if you dont lookup the recipe in NEI, it doesnt work, when you look it up. it works :)

Reproducing steps

1) Get GT Canning Machine
2) Put 2x fuel rod + 2x MOX fuel in
3) You will get 2x Fuel Rod (MOX)
4) Try to craft dual rods (Fuel Rod - Iron Plate - Fuel Rod)
5) It doesnt give any output (even when you click on the output crafting slot it doesnt give you anything)

6) Press U on the Fuel Rod (MOX) you made
7) You see the recipe for Dual Rod
8) Try to craft it again
9) Voila.. Now it works

It happens for both Fuel Rod types (MOX and Uranium)

Ttested with GT5.09.08

**Comment by Blood-Asp** [comment]
https://github.com/JasonMcRay/InfiTech-1.7/blob/master/scripts/gt_ic2.zs#L146

**Comment by JasonMcRay** [comment]
*facepalm* thanks

**Comment by Blood-Asp** [comment]
Also, a thorium fuel rod is no longer 1 dust, but now 3 dusts. Well, maybe time for me to change to into a triple ingot canning recipe myself.
