### ISSUE TITLE
[Suggestion] Covers

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#228]
Could you add covers for decoration blocks like all the different types of stone/granit and for the chisel blocks?
The recipe would be simple: 1block into cutting machine = covers :)

**Comment by Blood-Asp** [comment]
Not sure if possible and surely quite some work. So not sure if it will happen. If it does, then with low prio.

**Comment by Blood-Asp** [comment]
But i can say without trying: It will look bad. The lighting of the GT covers does not work correctly for good looking stuff.

**Comment by leagris** [comment]
Would it be possible to backport the GT6 rendering code?

**Comment by leagris** [comment]
As for covers. A neat way of having whatever texture cover would be with painting plastic sheets into the printer and placing painted plastic sheets as cover.

**Comment by Blood-Asp** [comment]
I have close to no knowledge on the rendering part. The only time i tried to optimize broke everything. So i'm not really keen on changing anything there.

**Comment by Blood-Asp** [comment]
looked at the code: I would have to rewrite huge parts of the cover code for this. that is not worth it.
