### ISSUE TITLE
[Bug] [Reopened] Charcoal pile igniter doesn't accept LOTR wood

### ISSUE THREAD

**Issue by alexdelphi** [Blood-Asp/GT5-Unofficial#229]
I've built a charcoal pile in creative. A mix of oak & birch wood went fine.
However, LOTR (Lord of The Rings) wood doesn't get burnt in the pile. The igniter simply doesn't start, ignoring my rightclicking.
What's weird, this wood is displayed in logs\OreDict.log as
lotr -> logWood
lotr -> treeLeaves
lotr -> plankWood
lotr -> treeSapling etc.
That is, like any normal wood would do.

**Comment by Blood-Asp** [comment]
The charcoal pile currently only works with vanilla wood. oredict support is planned.

**Comment by alexdelphi** [comment]
I see. I just didn't read the changelog properly ("can use all vanilla logs")

**Comment by alexdelphi** [comment]
Was not fixed in 5.09.09, so reopened the issue.

**Comment by Blood-Asp** [comment]
should now work
