### ISSUE TITLE
Extruder removing the "magnetized" property

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#230]
When I put Magnetized Steel into Extruder with Rod Shape, it will give me back 2 normal steel rods and not magnetized. Same goes with other magnetized ingots -> rods

**Comment by Blood-Asp** [comment]
Extruding metals is hot. Not melting hot, but hot enough to demagnetize. Looking in the code, it is especially coded that way.
Well, going with reality, every metal working that forms metal (rolling, hammering, extruding) produces enough heat to demagnetize, but i will just stay with the original greg values here.

**Comment by JasonMcRay** [comment]
Oh ok then :)
