### ISSUE TITLE
dimensional teleporter not working

### ISSUE THREAD

**Issue by Alessandro404** [Blood-Asp/GT5-Unofficial#234]
Hi. First time making an issue :D Hope i'm making this right

I'm using GregtechU 5.09.08 and i'm trying to make a working dimensional teleport 

I've tried this in single player and on a server, and i've seen no crash or console output.

When I try to make a dmensional teleport between the moon dimension (galacticraft, last version) and the twilight forest (again, last version) the teleporter work but transfers me on the right coordinates in the dimension i already was (moon, -30)

I've tried this in single and in multy with already generated worlds and already explored dimensions, 

One strange (and i mean, really strange but maybe not related) thing that happened is when i tried to make a new flat world: I made a new teleporter and IT WORKED! more or less. I WAS teleported in the twi, but... it was a blue void, no chunk was generated, but i heard a bighorn sheep near me (so i guess... the tp worked?). 

So i made another single player flat world, visited the twilight via portal (no strange behaviours) and tried again with the teleport once returned in the overworld. Again, it sent me in the right coordinates, but in the same dimension.

I've sarched on the wiki, on the forum thread and here but I've not seen this bug posted: Hope It helps!

**Comment by Blood-Asp** [comment]
Yes, it is the first time i heard of this. Two questions: Was the target dimension allready generated on the target coordinates? Also what happens when the targed is chunkloaded?

**Comment by Alessandro404** [comment]
when the teleport  worked, the region was never explored, so no chunk was generated. (another thing i noticed, is that i was not floating in the void, The world was invisibile, but definitely there) 
when the teleport fails, the region IS explored, but no chunk loaded.

Give me a moment and I'll try to chunk load the target

**Comment by Alessandro404** [comment]
When i tried teleporting on a chunk loaded area it worked, but again, no chunk around me was visible . Strangely, some distant chunk WAS visible so i tried disconnecting and reloading the game, and the problem fixed itself.

On the server, however, i had a friend on the target location (he told me the coodinates i used) when the teleport failed to change dimension.

**Comment by Alessandro404** [comment]
![2015-10-16_00 26 18](https://cloud.githubusercontent.com/assets/8747581/10529268/9e1851f6-739c-11e5-9adb-7f11df430666.png)

this is what i see when i teleport, every time. The chunk loaded area is behind me (i'm sure it's chunk loaded, i have a gregtech wireless redstone with a timer here and the receiver on the overworld work). 
Again, the world exist, because i glitch back when i try to pass inside an invisible tree.

waiting doesn't seem to fix the bug, only loggin back

**Comment by PaulMadsen** [comment]
I've been having the same problem.
https://github.com/Beyond-Reality/BeyondRealityModPack/issues/345

**Comment by Blood-Asp** [comment]
less than a year to fix this bug... phew...
