### ISSUE TITLE
Custom small ores sometimes generating empty

### ISSUE THREAD

**Issue by TTFTCUTS** [Blood-Asp/GT5-Unofficial#235]
A couple of days ago I noticed that a few gt.blockores.0 were showing up here and there, only really visible in the nether, after I added a set of ten custom small ores via the worldgen config. 

I increased the amount of the two of those ores which generate in the nether to 600 and saw that more of the empty ores appear. Both of the ores can also be seen (so it's not the materials being wrong, checked the numbers three times already), and it only happens in some chunks, not all. 

![2015-10-17_00 08 06](https://cloud.githubusercontent.com/assets/5436317/10555318/2712f682-7465-11e5-8d12-f7d8c8db5fc0.png)

Additionally I noticed some of the stone generation cutting off at chunk borders, though that is more likely the vanilla issue with world generators larger than a chunk which I've seen from time to time before.

WorldGeneration.cfg: https://www.dropbox.com/s/vgrxkx9bjajeqzo/WorldGeneration.cfg?dl=0
Log, in case you want to see if anything's going weird: https://www.dropbox.com/s/zzf4v5pmow98t4f/fml-client-latest.log?dl=0

**Comment by TTFTCUTS** [comment]
Hang on a second - I forgot that I was meant to be updating before checking this again...

**Comment by Blood-Asp** [comment]
What other worldgen changeing mods do you use?

**Comment by TTFTCUTS** [comment]
BoP, EBXL, Natura and Streams are the ones with a major influence. 
Others have smaller stuff like adding some trees, but they shouldn't be affecting this, and certainly not in the nether. All ores are disabled except the TC infused stone/amber and Pam's salt.
Pam's clay spawn and deadly world add pockets of other blocks in the overworld (clay, sand and silverfish blocks).
IHL adds some stones but they're all overworld too.

**Comment by TTFTCUTS** [comment]
Ok, update: I think this might be a networking issue somehow, related to the ore packets. I didn't notice before, but when you reload the area the blocks resolve to the correct ores.

**Comment by axlegear** [comment]
Confirmed.  This also occurs with custom veins.  I am positively certain no mistake was made but sometimes there's just a glob, vein-like, of 'gtore.0' or something similar, just blank ore.

**Comment by Blood-Asp** [comment]
But it only happens with custom ores, not with regular ones?

**Comment by TTFTCUTS** [comment]
It happens with regular ores too, but I noticed it happen most when I was messing with the custom ones. Since then I've found at least a couple of blocks here and there in the larger veins doing it.

**Comment by axlegear** [comment]
I can't confirm whether the blank veins are custom or not, as they're very rare and there's no ore that indicates what they are or were meant to be, and the height doesn't seem to clearly correspond to any one or few...

**Comment by Blood-Asp** [comment]
Well, too random for me to fix anything. Also not breaking anything.
