### ISSUE TITLE
GT Wrenches are not buildcraft compatible

### ISSUE THREAD

**Issue by ShawnBuckley** [Blood-Asp/GT5-Unofficial#236]
As a player, it would be really awesome if GT wrenches were also Buildcraft compatible.  Given that the crowbar is Railcraft compatible, is it by design that these are not compatible?

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/8d8594dabd6c3eafe3c7ed19c129d43fbe66fad4
Certainly needs testing in Modspacks. Pretty sure there was a reason greg did not do this himself.

**Comment by leagris** [comment]
I confirm GT Wrenches still does not work on BuildCraft blocks as of Gregtech 5.09.21.
@Blood-Asp can you have a look if this functionality was pushed into 5.09 build 21 or if it is still somewhere into your local dev branch?
In the mean time, re-open as no fixed please.

**Comment by Blood-Asp** [comment]
Tested on what BC blocks exactly? I remember testing it with 2-3 blocks and it worked. Also tested in what BC version? Maybe there was an API change.

**Comment by spacebuilder2020** [comment]
They don't work on enderio blocks.  I thought those used the standard apis but perhaps not.

I will test them on pure buildcraft blocks and let you know.

**Comment by spacebuilder2020** [comment]
Yes, they do work on pure buildcraft blocks that rotate.  However, I don't think you can shift click buildcraft blocks, (To break them) cause shift clicking does nothing with a BC wrench.

**Comment by Blood-Asp** [comment]
Hmm, GT Multitools block the shift click in most situations. @GregoriusT did add that, but no idea why it is needed.

**Comment by spacebuilder2020** [comment]
ok

**Comment by spacebuilder2020** [comment]
Also normal click does not work with ender io blocks either.

**Comment by GregoriusT** [comment]
Uhhm they dont block shiftclicks. They never did. "shiftclick to
remove" was never a thing with GT, that is only for IC2 Machines that
use the IC2 API in order to get the IC2 Wrenching behavior applied to
get their drop. RC probably has a shiftclick to remove function too.
But that removal would have to be implemented by the Mod itself and
not by GT. This isn't a Force Wrench!

**Comment by spacebuilder2020** [comment]
Buildcraft Wrenches can break ender io blocks with shift click.

**Comment by GregoriusT** [comment]
that might be hardcoded into EIO

**Comment by spacebuilder2020** [comment]
Ok... I will open an issue with ender io

**Comment by DarknessShadow** [comment]
The gt wrench doesn't seem to work properly as a bc wrench.

- shift right click enderio blocks (conduits / machines) doesn't work
- shift right click applied energistics(+addons) blocks doesn't work
- shift right click on a drum doesn't work
- shift right click on gendustry machines doesn't work
- shift right click on pneumaticcraft machines doesn't work
- (shift) right click on galacticraft machines doesn't work
- right click on pneumaticcraft machines doesn't work
- right click enderio conduits (to disconnect 2 conduits or change input/output) doesn't work
- right click to rotate bc blocks work but its opening the gui (doesnt happen with bc wrench)
- right click on me interface to change output direction works but its opening the gui (doesnt happen with bc wrench)

I've tested that on a server in InfiTech 2 v3.2.9 with the following mods.
- appliedenergistics2-rv3-beta-6
- buildcraft-7.1.16
- EnderIO-1.7.10-2.3.0.425_beta
- extrautilities-1.2.12
- PneumaticCraft-1.7.10-1.12.7-150-universal
- GalacticraftCore-1.7-3.0.12.460
- gendustry-1.6.4.135-mc1.7.10
- gregtech-5.09.21

Additionally it would be really cool if the gt wrench also worked like the yeta wrench so you can look through facades while holding it.
