### ISSUE TITLE
Oredict conflict between Thaumcraft and Essential Craft 3.

### ISSUE THREAD

**Issue by dwenograd** [Blood-Asp/GT5-Unofficial#239]
Ran into an oredict conflict between Thaumcraft and Essential Craft 3. The problematic entries are: oreShardFire, oreShardWater, oreShardEarth, and oreShardAir. There is an oreShardElemental in the mod, but it doesn't seem to conflict with anything.

**Comment by axlegear** [comment]
Is this actually a GT problem or a problem to be fixed by thaumcraft and essential craft 3?

**Comment by dwenograd** [comment]
I had a similar problem before with Chromaticraft, with Gregtech Ore Unification merging all items that share the same OreDic tag to be the same item, even if they're two totally separate things. Blood Asp added it to a blacklist in GT5 to prevent it from happening, and it solved the problem

**Comment by Blood-Asp** [comment]
I can blacklist it, but yes, the real issue is essentia craft using the same tags as thaumcraft. Or, if the same tag is actually what they want, then all their recipes should use oredict instead of the item.
