### ISSUE TITLE
Coolant cells still not working in vacuum freezer

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#240]
GT coolant cells still can't be cooled.  Wierdly, NaK cells in NEI show they turn into helium cells.  However, neither actually work-  it never starts.  Once again, regular IC2 cells work fine.

**Comment by Blood-Asp** [comment]
now it really works. C&P error. One single recipe did work, the others not.

**Comment by axlegear** [comment]
Will this fix be released in the next version or is there a hotfix or..?

**Comment by Blood-Asp** [comment]
as part of the hotfix. so allready uploaded.

**Comment by axlegear** [comment]
Alrighty, thanks!
