### ISSUE TITLE
Suggestion:  Use for Caesium

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#241]
Some uses for caesium would be nice, since it's utterly worthless.  Since lithium and sulfur can be used as fuel, why not caesium?  It burns well... especially in water!

IRL, it's useful for making drilling fluids, thermionic devices (which turn heat into energy directly), and used in early ion engines, and magnetohydrodynamic power-generating systems.

I figure fuel, at the very least, would be good.  :3  If just for laughs, make it explode if you throw it in water?

**Comment by Blood-Asp** [comment]
Added Burn values. https://github.com/Blood-Asp/GT5-Unofficial/commit/1e425e662285e6301ea3b9e90e580fe779eda0ce
Other uses might or might not follow.

**Comment by axlegear** [comment]
Hey, that's a use!  Now it's not totally useless.  And more fuels are always welcome.
