### ISSUE TITLE
Suggestion:  Coolant in GT

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#242]
It would be nice if there was a way to make coolant using GT.  Water + Lapis in a chemical reactor perhaps?  Or a mixer?  Then can it.

**Comment by Blood-Asp** [comment]
Done. https://github.com/Blood-Asp/GT5-Unofficial/commit/2c178297e8e8c72492f24144bb2ff6955ae5e6e0
Now IC2 even added the NEI recipes for coolant, so finally people stop asking how to make it...
