### ISSUE TITLE
Cannot recharge RSH/LZH

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#244]
I'm not positive this is GT5U's fault but it's the only mod that makes sense as to why it would be broken.
You cannot apply Redstone or Lapis to either the RSH or LZH devices in the nuclear reactor to recharge them.

**Comment by Blood-Asp** [comment]
Easy to test. Just try it once without GT installed and once with only IC2 installed.

**Comment by axlegear** [comment]
Sometimes, i'm an idiot.  I'll go do that now and report back.  XD

**Comment by axlegear** [comment]
OK, close it, seems to be an IC2 issue.  :(
