### ISSUE TITLE
Suggestion:  Heat Pipe for Nuclear Reactor

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#245]
Heat pipe, an upgraded GT-style heat exchanger.  Works like a component heat exchanger, plus an additional 4 heat/tick from the reactor hull as well.  Made using a heat exchanger, a cell of molten gallium or mercury, and a dense aluminium plate.  Gives some use to the largely useless gallium and mercury.

**Comment by Blood-Asp** [comment]
Nope. No interest. At last now.
