### ISSUE TITLE
RS covers inconsistent on many meta tile entities

### ISSUE THREAD

**Issue by willis936** [Blood-Asp/GT5-Unofficial#246]
RS TX out doesn't transmit to all RS RX out covers of the same frequency unless on specific hulls.  I've found machine hulls work but pipes, battery buffers, and hatches do not.

It appears to be tier related.  LV hatches and hulls work but MV and higher are hit or miss.

Actually I really don't know anymore.  I have an LV hatch working but not an LV hull.  I have EV hulls working...  One LV input hatch but then another doesn't.

Do they have a range mechanic?

I think I got it.  I assumed multiple TX meant the RX took in the active high OR of the TX.  Apparently it just breaks everything.  It would be nice if they could behave this way (like tying vanilla RS together).

**Comment by Blood-Asp** [comment]
The rs cover only checks the rs signal coming from the block it is facing. No idea why there are differences. How do you input rs signal? Directly with lever? Lever on next block? Or per rs dust? Or per cable of one of the rs mods?

**Comment by willis936** [comment]
When I had two RS TX covers on one frequency one had a lever directly on a TX cover and the other was facing a GT fluid detector or had a repeater directly touching it.

Also a friend pointed out to me that RS covers don't take RS if it makes a corner even though it shows the dust going into the block.  That might be a vanilla issue though.

**Comment by Blood-Asp** [comment]
Wait, two redstone transmitters on the same frequency? That is something never to be done. Both try to write their status on the same channel and the whole transfer output turns into race conditions. Allways only use one transmitter per frequency!

**Comment by JasonMcRay** [comment]
Honestly it should be allowed. Sometimes you want to emit a signal on
receiver if one or another transmitter gets a signal. So it works like
classic wireless redstone with "OR" condition

**Comment by Blood-Asp** [comment]
That is not a question of allowed. It is simply not possible the way it is coded.

**Comment by willis936** [comment]
These rules should be documented somewhere.

**Comment by Blood-Asp** [comment]
Why do you just assume it works a certain way? Also, everyone is free to document on the wiki. I do not have the time to do everything. Even for coding my time is quite limited.
