### ISSUE TITLE
Chemical Reactor not accepting second item

### ISSUE THREAD

**Issue by kloftis** [Blood-Asp/GT5-Unofficial#247]
I'm trying to make sodium persulfate in the chemical reactor, but the reactor doesn't seem to want to take the second item. Tried using item filters on different sides, routers from Router Reborn, and Buildcraft and Thermal Expansion pipes on different sides. Replaced all machines and tried different variants of the Chemical reactor as well. Seemed to work before moving to the unofficial mod.

**Comment by axlegear** [comment]
Just tried it, and it works fine for me.  Are you using the correct covers and set with the right screwdriver-setting?

**Comment by kloftis** [comment]
What covers and screwdriver settings are you using? I thought you didn't need anything between Item Filter and machine, though I did try robotic arms on the filters to put out to slots 4 or 5 (as determined by the router).

**Comment by kloftis** [comment]
Version 5.09.09 and 5.09.04 btw

**Comment by Blood-Asp** [comment]
The fluid for the recipe is allready in? And you do not try to insert trough the autooutput side?

**Comment by kloftis** [comment]
The fluid was not in. Works once it is. Interesting mechanic.

Thanks for the help!

**Comment by Blood-Asp** [comment]
The optimized recipe check is a bit complex here. There is an list of all items a machine has in all of its recipes. this is used for the first item. Same is there a list for all fluids used in its recipes. The last component is only accepted in the machine, when the inserted item results in an recipe to use.
Thats also why all recipes are limited to 2 items and 1 fluid max. This way is garanted, that never a unusable item goes into a machine by automation and the machine never get's totally stuck.

GT6 just expaned that mechanic by rewriting quite a huge part of the recipe system, Now it seems up to 12 items and fluids are accepted as inputs.
