### ISSUE TITLE
Ores uncompatable

### ISSUE THREAD

**Issue by mightydanp** [Blood-Asp/GT5-Unofficial#251]
ores harvest level can not be changed with iguana tweak

**Comment by Blood-Asp** [comment]
GT Ores are tileentitys with 32768 blocks in one. I can't change anything about that they are not changeable. Maybe, but only maybe it is possible to add an config file for that. but not really sure about that.

**Comment by mightydanp** [comment]
Would love for you to try

**Comment by Blood-Asp** [comment]
Just added a harvestlevel config. https://github.com/Blood-Asp/GT5-Unofficial/commit/0f288afe8b7ccb8dd164200330677b131408c1b4
It is part of the MaterialProperties.cfg
Must be enabled per harvestlevel/activateHarvestLevelChange.
After next restart the default values get added to config.
The harvestlevel is saved inside the ores, so the changed value only works for newly generated ores.

**Comment by mightydanp** [comment]
So i need to enable it in the gregtech config to in the newer version ? Or ? Little confused there.

**Comment by Blood-Asp** [comment]
The version with the change is not yet released. 
It will be in 5.09.11/5.08.33. And in these versions you must first enable it in the MaterialProperties.cfg

**Comment by mightydanp** [comment]
Is there anythinf special  i need to do in blockoverride.cfg or is the regular  way still  ok?
