### ISSUE TITLE
TerraFirmaCraft Ore Gen

### ISSUE THREAD

**Issue by Muramasa-** [Blood-Asp/GT5-Unofficial#255]
Do you think it would be possible for GT5U to support spawning ores in TFC biomes?

Thanks.

**Comment by Blood-Asp** [comment]
Afaik, TFC needs to declare it's stone as "replacable" and then it should work.

**Comment by Muramasa-** [comment]
I was talking about this on another forum and someone said that mods like Glen's Gases can generate it's "ores" in TFC stone by using the ore dict. Not sure if that it accurate though.

Thanks.

**Comment by Blood-Asp** [comment]
I could add every single TFC stone into GT worldgen so it does know it, but that is not easy and i have other things to do... So i do not really want to do that. As i said, on TFC side it would be easy and all other mods that want to generate inside of TFC stone also would not have to add special support.

**Comment by Muramasa-** [comment]
Ah Okay BloodAsp, thanks for explaining that. I'll mention it on the TFC page and see what they say.

Thanks.

**Comment by Kittychanley** [comment]
TFC has it's own TFCOres.cfg config file explicitly for allowing generation of mod ores in our stones. There's no need for other mods to add in this compatibility.

**Comment by Kittychanley** [comment]
There is a slight issue do to the fact that your ores are a weird kind of tile entity and do not follow the standard block id/meta for placement though. In practice, blocks should never have metadata higher than 15, and yet somehow yours do. The way our file is set up, it needs the actual block info.

However, I have been told that the PFAA mod has GT compatible ores that work just fine in our TFCOres.cfg file. And as long as you don't have CustomOreGen installed, there is no worry about the blocks spawning outside of the TFCOre.cfg settings.

**Comment by Kittychanley** [comment]
@Blood-Asp If you would be willing to take a look at how our TFCOre.cfg file is set up and recommend how we can change it to accommodate your ore blocks since they are not traditional blocks, I would be more than happy to make the change.

We simply cannot declare our stone as replaceable as we have intentionally not done so to prevent vanilla ore generation for multiple reasons.

https://github.com/Deadrik/TFCraft/blob/master/src/Common/com/bioxx/tfc/Core/Config/TFC_ConfigFiles.java#L543

https://github.com/Deadrik/TFCraft/blob/master/src/Common/com/bioxx/tfc/WorldGen/Generators/OreSpawnData.java

https://github.com/Deadrik/TFCraft/blob/master/src/Common/com/bioxx/tfc/WorldGen/Generators/WorldGenOre.java

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/blob/master/src/main/java/gregtech/common/blocks/GT_TileEntity_Ores.java#L99 This is GTs block placing code. Basicly a if() for every new material would have to be added. With allready slow worldgen, that surely is a bad idea. Greg completely remade this in GT6, but for a single feature, i will not do that much work.

So on your side, you would have to place the block, call the TE and then write the right data into it.

https://github.com/Blood-Asp/GT5-Unofficial/blob/master/src/main/java/gregtech/api/enums/Materials.java this is the list of what meta is what material. 0-999 are the material IDs and in steps of 1000 they have different materials, but i guess thats not nessary anymore for you to know.

**Comment by Blood-Asp** [comment]
Well, if nothing else works out, it is still possible for modpack makers, to make their own ores with quadrum or some other mods like that. Once they have the right oredict, GT will add processing recipes for it.

**Comment by draknyte1** [comment]
Would a re-visit of this now be viable?

**Comment by mura3277** [comment]
This will be possible with a GT addon mod once I commit some changes that I haven't got around to since I've been MIA
