### ISSUE TITLE
Suggestion:  U-235 centrifuging

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#256]
Since you can centrifuge U-238 to get U-235 and Pu-244, I was thinking it would be nice to add a recipe to centrifuge U-235 into something else as well, since there's always a vast abundance of U-235 compared to U-238.

**Comment by Blood-Asp** [comment]
abundance of U-235? Where does that happen? In GT5.08, centrifuging U238 is the only way to get U-235. Or did the 5.09 change of Pu into U235 make it too much?

**Comment by axlegear** [comment]
I don't know what changed, but I have 3 ingots of U-238 and 4 stacks of U-235 ingots.

**Comment by Blood-Asp** [comment]
Exchanged some U235 Worldgen into U238. It should be about 1 U235 per 30-35 U238. Before it was about 1 / 10
https://github.com/Blood-Asp/GT5-Unofficial/commit/3af644dffe93bf6f2e2df54025b0b488c3ca758e
