### ISSUE TITLE
Suggestion: Nuclear reactors

### ISSUE THREAD

**Issue by dohvakin96** [Blood-Asp/GT5-Unofficial#262]
You said that you want to increase the output of the nuclear reactors. I think adding a breeder reactor (like in stable IC2) would be a good way to do that.

**Comment by Dream-Master** [comment]
Ic2 (after Version 780) have a new config where you can change many things via ic2 config file.(reactor and heat values)
After i ask Aroma he implement it.

**Comment by Blood-Asp** [comment]
I will not make a new reactor. Only change a few values of the existing one.
