### ISSUE TITLE
Reduce creation of unused crafting items

### ISSUE THREAD

**Issue by ShawnBuckley** [Blood-Asp/GT5-Unofficial#266]
Currently the GT ore processing module iterates through the ore dictionary and produces a standard set of crafting items (plates, rods, bolts, etc) for materials it encounters.  However,  many of these crafting items are unused.  They clutter up both recipe managers and NEI.  Removing them will improve performance and playability.

**Comment by AiwendilCiunio** [comment]
There are also several items that exist for every possible material but have no use whatsoever, like springs, rounds etc. Wouldn't it be better to remove them to shorten up the loading time?

**Comment by ShawnBuckley** [comment]
That is the idea. Only crafting items that are actually used will be generated. As designed it will process recipes first then will process the items that they need.

**Comment by DarknessShadow** [comment]
So like this https://github.com/Blood-Asp/GT5-Unofficial/issues/94?

**Comment by Dream-Master** [comment]
If you want to add unused stuff within a  minetweaker recipe the materials must be there because minetweaker loads at last.

**Comment by Blood-Asp** [comment]
There should be at last a config to disable this (all at once, or in parts). Otherwise it must be made sure that the items are really unused!

**Comment by Dream-Master** [comment]
Configure sounds better.

**Comment by ShawnBuckley** [comment]
I wasn't planning on making it something configurable honestly. However, it could be implemented relatively easily by leaving the existing ore processing code in and creating an entirely new processing mechanism and directing the game to use either one.

Some background:
Currently the mod scans the ore dictionary and runs each material through every single processor which creates all of the items according to its properties. The list of different processors are here: [GT_Loader_OreProcessing.java](https://github.com/Blood-Asp/GT5-Unofficial/blob/master/src/main/java/gregtech/loaders/preload/GT_Loader_OreProcessing.java)

The plan as designed so far would be different.  Certain things would remain the same, like creation of arrowheads, tools, and ingots.  The crafting items would only be created on demand when encountered during a recipe.  An example would be:
```Java
Item tinScrew = MaterialProcessor.get(Materials.Tin, CraftingItem.Screw);
```
The request for screw would go through and create its dependencies if they have not been created yet.

**Comment by ShawnBuckley** [comment]
Also, come to think about it, minetweaker support should be added to it as well. That would allow minetweaker to create previously unused items in the same fashion.

**Comment by axlegear** [comment]
How's the progress coming?

**Comment by Blood-Asp** [comment]
@ShawnBuckley still existing?

**Comment by Dragon2488** [comment]
Lol, because of GT uses metaitems and one texture for each material group, unused items aren't palpably slowing the game down. But all of the unused parts can find uses in another mods recipes and modtweaker, so I think they are useful and shouldnt be removed.

**Comment by mura3277** [comment]
It's the iterations/automatic recipes that slow the game down, not the items themselves.

**Comment by OvermindDL1** [comment]
> It's the iterations/automatic recipes that slow the game down, not the items themselves.

And that could be fixed by instead of making a ton of recipes just make a new (for crafting recipes) Recipe subclass that resolves what is placed in, hence only one registered recipe but the recipe handler would parse through the input items and how they are organized to determine what should happen, like a <type> plate can be melted down into a <type> fluid if the <type>.isMeltable or whatever is set.

Vanilla recipes already have such an ability by subclassing the Recipe as I stated above.  However for the GT Recipe system it will need some new features added to handle that if that is the part that slows things down.

It would also require making new NEI handlers too irritatingly if you wanted to show those.

**Comment by Blood-Asp** [comment]
To be exact, the improvement is about the startup time. Bad PCs or huge modpacks take easily 5-15min to load and reducing items and recipes reduce that time by about 1/3. 

Another improvement is that that the NEI clears up quite a lot, what makes using GT much easier for beginners that have to search there a lot.

Improvement on ticktime, fps or memory usage is close to zero and we knew that from the beginning.

**Comment by Dragon2488** [comment]
Well, i agree that we need one recipe for plates and other OrePrefixes recipes. Hiding unused items in jei (or nei) can be done, but with config option. Deleting unused items itself isnt needed.

**Comment by mightydanp** [comment]
I agre with Dragon but to fix  Dragons problem we can simply add a config. If the config is true it will do a one time scan and scan the mods item for ore dictionary that can be used with gregrech items and if it matches a item it will put it in a config and set it true to be used but if its not found the item would be set to false to be used.
