### ISSUE TITLE
plasma generator NEI not easy to navigate to

### ISSUE THREAD

**Issue by willis936** [Blood-Asp/GT5-Unofficial#268]
If I search uses of the plasma fluid I don't see the plasma generator.  It's only seen when looking at uses of the fluid cells.

**Comment by draknyte1** [comment]
Any ideas on this one? Real pain to look it up :>

**Comment by mura3277** [comment]
A good solution to this is to unhide the GT plasma cells. Then all you need to do us to view the uses of those cells.
