### ISSUE TITLE
Can't build pyrolyse oven

### ISSUE THREAD

**Issue by ObKo** [Blood-Asp/GT5-Unofficial#269]
Seems something wrong happens to multiblock structure checking. 
First, here is what I've built:
![greg1](https://cloud.githubusercontent.com/assets/171339/10709038/0d1d5838-7a39-11e5-909a-491ae4747df5.png)
![greg3](https://cloud.githubusercontent.com/assets/171339/10709047/763a9e5c-7a39-11e5-9667-7f0120024e0f.png)
![greg2](https://cloud.githubusercontent.com/assets/171339/10709070/254f08ec-7a3a-11e5-86ad-1c97d697a4b1.png)
Bottom layer: 3x3 kantal coils, ulv casings, mv out hatch, mv out bus, controller, mv energy hatch, maintenance hatch, and bunch of mv out bus. As you can see, first layer (in z-y plane, right side) is completely accepted by multiblock (i.e. they've changed color), on second layer something went wrong - maintenance hatch (front) got accepted, but muffler hatch (top) is not. I've took a look on checking code - it seems that something inside oven (either coils or air) is not accepted...

**Comment by ShawnBuckley** [comment]
Thanks for reporting this. To speed things up, could you share what you've looked at so far?

**Comment by ObKo** [comment]
I'm talking about src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PyrolyseOven.java, function checkMachine()
```java
    @Override
    public boolean checkMachine(IGregTechTileEntity aBaseMetaTileEntity, ItemStack aStack) {
        int xDir = ForgeDirection.getOrientation(aBaseMetaTileEntity.getBackFacing()).offsetX * 2;
        int zDir = ForgeDirection.getOrientation(aBaseMetaTileEntity.getBackFacing()).offsetZ * 2;
        for (int i = -2; i < 3; i++) {
            for (int j = -2; j < 3; j++) {
                for (int h = 0; h < 4; h++) {
                    IGregTechTileEntity tTileEntity = aBaseMetaTileEntity.getIGregTechTileEntityOffset(xDir + i, h, zDir + j);
                    if ((i != -2 && i != 2) && (j != -2 && j != 2)) {// innerer 3x3 ohne h�he
                        if (h == 0) {// innen boden (kantal coils)
                            if (aBaseMetaTileEntity.getBlockOffset(xDir + i, h, zDir + j) != GregTech_API.sBlockCasings1) {
                                return false;
                            }
                            if (aBaseMetaTileEntity.getMetaIDOffset(xDir + i, h, zDir + j) != 13) {
                                return false;
                            }
                        } else if (h == 3) {// innen decke (ulv casings + input + muffler)
                            if ((!addInputToMachineList(tTileEntity, 120)) && (!addMufflerToMachineList(tTileEntity, 120))) {
                                if (aBaseMetaTileEntity.getBlockOffset(xDir + i, h, zDir + j) != GregTech_API.sBlockCasings1) {
                                    return false;
                                }
                                if (aBaseMetaTileEntity.getMetaIDOffset(xDir + i, h, zDir + j) != 0) {
                                    return false;
                                }
                            }
                        } else {// innen air
                            if (!aBaseMetaTileEntity.getAir(xDir + i, h, zDir + j)) {
                                return false;
                            }
                        }
                    } else {// Au�erer 5x5 ohne h�he
                        if (h == 0) {// au�en boden (controller, output, energy, maintainance, rest ulv casings)
                            if ((!addMaintenanceToMachineList(tTileEntity, 120)) && (!addOutputToMachineList(tTileEntity, 120)) && (!addEnergyInputToMachineList(tTileEntity, 120))) {
                                if ((xDir + i != 0) || (zDir + j != 0)) {//no controller
                                    if (aBaseMetaTileEntity.getBlockOffset(xDir + i, h, zDir + j) != GregTech_API.sBlockCasings1) {
                                        return false;
                                    }
                                    if (aBaseMetaTileEntity.getMetaIDOffset(xDir + i, h, zDir + j) != 0) {
                                        return false;
                                    }
                                }
                            }
                        } else {// au�en �ber boden (ulv casings)
                            if (aBaseMetaTileEntity.getBlockOffset(xDir + i, h, zDir + j) != GregTech_API.sBlockCasings1) {
                                return false;
                            }
                            if (aBaseMetaTileEntity.getMetaIDOffset(xDir + i, h, zDir + j) != 0) {
                                return false;
                            }
                        }
                    }
                }
            }
        }
        return true;
    }
```
this function check multiblock structure, in x->z->y (i->j->h) order (right->forward->up on first screenshot). It seems that all is ok until i=-1 && j=-1 ("column" right behind maintenance hatch on screenshot), because maintenance hatch (i=-1, j=-2, h=0) is accepted, but muffler hatch on top (i=-1, j=-1, h=3) is not. So, "innerer 3x3 ohne h�he" branch returns false somehow...

**Comment by AiwendilCiunio** [comment]
I think this applies to other multiblocks too, since we had a similar issue on our server with Large Turbine. It just wouldn't form, probably 1 of the air blocks had something inside that prevented the multiblock from forming. Moving the turbine 2 blocks away solved the problem.

**Comment by Blood-Asp** [comment]
I just tested it in dev and had no issues in every combination. I can only guess that something invisible is wrong inside the multiblock air. Something not correctly replacing air or so.

**Comment by ShawnBuckley** [comment]
@ObKo, Coud you try placing and harvesting a block for every air block inside?

**Comment by ObKo** [comment]
I've tried placing and harvesting a blocks, rebuilt oven in different place, rebuilt oven in newly digged hole, rebuilt oven in singleplayer - same results.

**Comment by ObKo** [comment]
Modlist: http://pastebin.com/tbUXTvPj

**Comment by dohvakin96** [comment]
I have the same problem.

**Comment by Blood-Asp** [comment]
Can you upload the whole modpack as zip? With configs? Then i can make sure it is some mod, or on GT side.

**Comment by ObKo** [comment]
https://cloud.kosyak.info/index.php/s/rGgkhTPvJ5Pit7X

**Comment by ObKo** [comment]
I can reproduce this issue with GT5 and IC2 (781) only:

* CodeChickenCore-1.7.10-1.0.4.29-universal.jar
* gregtech_1.7.10-5.09.09.jar
* industrialcraft-2-2.2.781-experimental.jar
* NotEnoughItems-1.7.10-1.0.3.74-universal.jar

config folder removed 

world seed: pyrolyse 
world type: default

-100;100 - fail:
![2015-10-25_09 40 12](https://cloud.githubusercontent.com/assets/171339/10713967/23ab7036-7af6-11e5-9fe4-49b3cbd82d6f.png)

-100;-100 - fail:
![2015-10-25_09 43 20](https://cloud.githubusercontent.com/assets/171339/10713969/2b27c88c-7af6-11e5-84d4-8da43ac91e22.png)

100;-100 - fail:
![2015-10-25_09 47 16](https://cloud.githubusercontent.com/assets/171339/10713971/32085680-7af6-11e5-95c0-c15b8d386953.png)

100;100 - fail:
![2015-10-25_09 51 41](https://cloud.githubusercontent.com/assets/171339/10713973/38435cfc-7af6-11e5-9aaa-c3fc87cde3cc.png)

200;200 - weird shit happend:
![2015-10-25_10 01 57](https://cloud.githubusercontent.com/assets/171339/10714005/57052ab6-7af7-11e5-87b1-cff8cb82efa6.png)

300;300 - win!
![2015-10-25_10 07 35](https://cloud.githubusercontent.com/assets/171339/10714012/e886c0c6-7af7-11e5-9152-aefc0bc3aa65.png)
![2015-10-25_10 07 39](https://cloud.githubusercontent.com/assets/171339/10714014/ed1d701c-7af7-11e5-9844-03bfac621303.png)

I have a feeling that I'm doing something really wrong...

**Comment by Blood-Asp** [comment]
Fixed with: https://github.com/Blood-Asp/GT5-Unofficial/commit/9b91a89e1247416497554b75759abdb7797ca67b
