### ISSUE TITLE
Startup lagspike fix

### ISSUE THREAD

**Issue by LuxusDarkangel** [Blood-Asp/GT5-Unofficial#272]
Yesterday Greg found why GT startup is taking that long:

[Oct 23rd 2015, 3:20pm] GregoriusT: Gah, NOW I found out why startup is lagging like hell... It is me adding Thaumcraft Aspects to over 67000 Items...

[Oct 23rd 2015, 3:22pm] GregoriusT: All my own internals are perfectly fine Lagwise, but THOSE ASPECTS are not. Let's see how I can optimise that away.

[Oct 23rd 2015, 3:23pm] GregoriusT: There is some Aspect Itnerface in TC, I just gonna use that one on my Items to reduce the amount of things to register aspects to.

And then i asked him if that affects GT5U too, but:

[Yesterday, 5:36pm] LuxusDarkangel: greg, the aspect thingy on startup affects only gt6 or gt5 too?

[Yesterday, 6:41pm] GregoriusT: GT5 too

[Yesterday, 6:42pm] GregoriusT: however I have NO IDEA how I fixed it.

So i hope you find a way to fix it too on GT5U (i wouldn't mind at all if i could turn off aspect registration in the cfg, but i don't know if this is even possible)

**Comment by Blood-Asp** [comment]
II allready looked at the code after the GT6 changelog. All TV related changes i found was reverting changes made earlier in GT6 back to how it was in GT5. Also tried to disable the registration and could not measure more than 2-3 sec difference in load time.

**Comment by ShawnBuckley** [comment]
I'd bet that reducing the number of items will directly improve this. #266

**Comment by LuxusDarkangel** [comment]
This is the "explication" of greg about his optimizations:

[Yesterday, 12:20am] GregoriusT: Loading time went from 6 Minutes to 3 Minutes, because REASONS. Seriosuly, I dont know what I did to save on the 3 minutes

[Yesterday, 12:22am] GregoriusT: because I first optimised a Thaumcraft related GT thing, found out that Azanors Code sucks horribly at Aspects, reverted that optimisation, and it STILL KEPT THE 3 MINUTES

[Yesterday, 12:23am] GregoriusT: my optimisation had interessting side effects on the assignment of TC Aspects

[Yesterday, 12:24am] GregoriusT: for example random Blocks and Items got their Aspects tripled or +20 of multiple unrelated Aspects

[Yesterday, 12:24am] GregoriusT: now if I would have accessed the Maps or something I would have understood what happened, but it was just the fact that my Items implemented an Interface that fucked up everything

[Yesterday, 12:25am] GregoriusT: even vanilla entries

Maybe you can try and fuck up that tc thingy and then undo the changes to get it working (?)

**Comment by Blood-Asp** [comment]
I tried it in the InfiTech2 pack to have a real test. Normal load time: 3:46. With all TC compat disabled 3:38. So this is invalid. GT6 TC support was broken, GT5U TC support is ok.

**Comment by LuxusDarkangel** [comment]
Can you please upload the version without tc compat to test it myself? Not that i don't believe you, but i've seen people with load times between 3-15 minutes depending on his pc while using GT (this applies to me when i switch between desktop and laptop computers). 3:46 to 3:38 can be 15mins to 12mins for people with slower pcs.

**Comment by Blood-Asp** [comment]
https://www.dropbox.com/s/d3umkq7rs1oeqr1/gregtech-5.09.10-noTC.jar?dl=0
Have fun testing.

**Comment by LuxusDarkangel** [comment]
Well... I really can't have fun testing because the link is broken :P

**Comment by Blood-Asp** [comment]
try again

**Comment by LuxusDarkangel** [comment]
I've done some tests with my laptop, wich is my slowest pc right now (and still is a very nice pc), and those are the results:
With TC compat: 5.7 mins
Without TC compat: 4.75 mins

So as i figured out, slower pcs will notice this a lot.

**Comment by mura3277** [comment]
I'm not sure how much work it is (Since I don't know changed), but maybe we could have TC compat optional via a config option?

It does apparently have a noticeable improvement on slow machines. (Also sorry for necro)
