### ISSUE TITLE
Air uncanning goes into wrong slot

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#273]
When un-canning air, it goes into the machine's input slot instead of it's output.  This halted my nitrogen factory and nitro-diesel plant when I discovered it the hard way.

**Comment by Blood-Asp** [comment]
The canning machine is different internally from the other machines. It only does have one fluid slot. Changeing that would meant to code the whole machine anew incluiding the recipe system for them. The current way does not really have any downside, so that much work should not be nessary.

**Comment by axlegear** [comment]
What?  That doesn't make any sense.  I am unable to extract air from the machine.  Other fluids go into the correct slot:  The output slot.  Only air goes into it's input slot, meaning all I can do with a can of compressed air is re-can it.

**Comment by Blood-Asp** [comment]
Did you ever test that? What NEI shows is different from how the machine works. It only has one fluid tank, and it can pump in/out from it just fine.

**Comment by axlegear** [comment]
I tested, yes.  Air goes into the input slot, and won't come out.  However if I try with a different fluid, such as chlorine, it goes into the output slot, and I can pump it out.

**Comment by axlegear** [comment]
Oh jeez, I found the problem.. I was trying to output to completely the wrong machine.  I'm so sorry!
