### ISSUE TITLE
Machine Controller not working with Redstone Receiver (In)

### ISSUE THREAD

**Issue by AiwendilCiunio** [Blood-Asp/GT5-Unofficial#274]
Doesn't work. It would be really useful for switching on/off Large Turbines remotely or automatically.

**Comment by Blood-Asp** [comment]
Use machine controller on the input hatch. Does the same, even more efficient, for turbines.

**Comment by AiwendilCiunio** [comment]
Could you please explain more? I'm not sure what you mean, I tried using machine controller on input hatch, but didn't notice anything.

**Comment by Blood-Asp** [comment]
Just stop more fuel going in the turbine and it will stop. That way you will also get the energy from the spindown you lose when hammer turbing off.

**Comment by AiwendilCiunio** [comment]
Yes, but even if I use ULV input hatch there will still be 8000L of plasma inside and that's enough to run the turbine for like 10 minutes when using nickel plasma..

But anyway, this needs shutter module on the input face? That's gonna be a problem since I'm using fluid regulator next to input hatch for optimal flow.

**Comment by AiwendilCiunio** [comment]
Nvm figured it out.
