### ISSUE TITLE
Crash when look into some recipes with NEI

### ISSUE THREAD

**Issue by xXGandalfXx** [Blood-Asp/GT5-Unofficial#276]
Hey,

my game crashes when i try to look into recipes of "crafting components", like screws and rods.

Crash: http://pastebin.com/yBzv34fF

GT-Version: 5.09.09
IC2-Version: 2.2.787
NEI-Version: 1.0.5.118
CCC-Version: 1.0.7.47

**Comment by Blood-Asp** [comment]
update ic2 to 790
