### ISSUE TITLE
Sulfuric Gas

### ISSUE THREAD

**Issue by Dream-Master** [Blood-Asp/GT5-Unofficial#277]
Sulfuric gas not have any texture.
GT Version 5.09.10 Ic2 790
![image](https://cloud.githubusercontent.com/assets/2970688/10716110/468efba8-7b2e-11e5-98e8-4deba98cc1b8.png)

**Comment by ShawnBuckley** [comment]
Is this new? It could have been caused by fixing #267.

**Comment by Blood-Asp** [comment]
Yes, texture also had to be renamed: https://github.com/Blood-Asp/GT5-Unofficial/commit/621573fe84077bb29d3d94ec1c071017e9c1f2d2

**Comment by Dream-Master** [comment]
I compiling the source and say you if it gone.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/10774205/20b382f4-7d00-11e5-97ce-9a2dc1e3aafc.png)

Works now with my compiled Version of Gt 5.09.11 and will work after the oficial update from blood Asp .
@Blood-Asp 
Did you want i close this here ?

**Comment by Blood-Asp** [comment]
After the fixed version is released.
