### ISSUE TITLE
Gregtech bee problem.

### ISSUE THREAD

**Issue by cpbplus** [Blood-Asp/GT5-Unofficial#278]
Last version of Gregtech and dev version of Forestry.
http://pastebin.com/ykRwhz79

**Comment by Blood-Asp** [comment]
Do other bee addons like magic bees and gendustry work with that version? Updating to a version no other mod supports would not be good. If you do not want to use the GT bees, you can just disable them in the gt  config to get around the crash.

**Comment by leagris** [comment]
BeyondReality pack just switched to Forestry4.
See: https://github.com/Beyond-Reality/BeyondRealityModPack/blob/master/BR1710/CHANGELOG_2.3.6.md

We did not switch to GT5E 5.09 yet because you state it is not yet stable and also because of this bees registration issues. Maybe for next BR Pack

**Comment by Blood-Asp** [comment]
GT is now compiled against Forestry 4.0.39. 
What version did the change that breaks compatibility?

**Comment by stardustrider** [comment]
4.1.0.44 caused the crash for me. I'd jumped to it from 4.0.39.

**Comment by Dream-Master** [comment]
Working the bees with forestry 3.6 too?
I can see the bees in nei.

**Comment by Blood-Asp** [comment]
Yes, that part somehow allready worked.
