### ISSUE TITLE
Thorium Fuel Rod with Neutron Reflector produces extra EU/t

### ISSUE THREAD

**Issue by ShelfOwl** [Blood-Asp/GT5-Unofficial#28]
Thorium Fuel Rod with Neutron Reflector produces 6EU/t (expected 2EU/t).
Also, 4x Thorium Fuel Rod with Neutron Reflector produces 32EU/t (expected 16EU/t)

A phenomenon reminds me Thorium-Plutonium Hybrid reactor on GregTech 2.90.

**Comment by Blood-Asp** [comment]
GT Version?

**Comment by ShelfOwl** [comment]
I'm sorry for lacking information.
GT 5.08.18, Forge 1387, IC2ex 2.2.717

**Comment by Blood-Asp** [comment]
Fixed with Iridium neutron reflector. Must be fixed on IC2 side for other reflectors.
