### ISSUE TITLE
Can't make RTG pellets with GT Plutonium

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#283]
Latest version seems to have no RTG pellet recipe.  This is kinda nasty.  Luckily there's a workaround by macerating the ingots and then compressing them to make IC2 chunks.

**Comment by Blood-Asp** [comment]
Did the meta on craft also change to :1 here?

**Comment by axlegear** [comment]
Not that I can tell?  Also it affects the enriched uranium fuel and MOX fuel as well.  Basically all the nuclear recipes are broke again with the latest IC2/GT5U combo.... this is getting frustrating.  My nuclear production is suffering.

**Comment by axlegear** [comment]
also, no, no :1 that I can see

**Comment by Blood-Asp** [comment]
Now, does this happen trough updating IC2, or GT? To kniw that would make the search easier.

**Comment by axlegear** [comment]
Unfortunately, i am unsure.  I updated from IC780 to IC790 and GT 5.09.00 to 5.09.10

**Comment by Blood-Asp** [comment]
After some tests, i'm mostly sure, that this is a IC2 issue. IC2 adds these recipes (as oredict recipes) and they somehow stopped working.

**Comment by Blood-Asp** [comment]
Made an IC2 bugreport of it: http://bt.industrial-craft.net/view.php?id=1756
