### ISSUE TITLE
Suggestion: Thorium-powered MSR

### ISSUE THREAD

**Issue by dohvakin96** [Blood-Asp/GT5-Unofficial#286]
I would like to have a thorium-powered molten salt reactor (MSR). I think there was the idea of adding one in GT4, the thermal boiler was able to use molten salt, however it was never coded. 
A MSR would you use a not so big amount of plutonium or uranium 235 (maybe one block or so) to start up. After that, the reactor would breed thorium to uranium 233 and wouldn´t need any fuel, except the thorium. The reactor would use F2LiBe-salt as a coolant, allowing it to operate at really high temperatures (about 1500 kelvin). The nuclear fuel and the fission products are all inside the coolant (while the reactor is active), and the coolant is constantly pumped between the reactor core and the heat exchanger. The reactor would be pretty save, compared to normal fission reactors and also pretty clean (after pollution is added). The reactor would be a high-end technology (obviously) and a pretty big and expensive multiblock. 
Btw. since a MSR uses Lithium containing salt, it would also produce a good amount of tritium.

**Comment by Blood-Asp** [comment]
I do not plan to write a completely new reactor. Only a few changes to the IC2 reactor is the current max. So this will note be done by me.
