### ISSUE TITLE
Suggestion: More-than-one-tier transformers

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#288]
Nice idea from forum
    Quoted from "Elthy"
    How about advanced, harder to build transformers, that can transformup/down several voltage steps at once? Im planning my main powergrid to be UV, when i need an LV machine somewhere stuff begins to look stupid... 

There could be unconfigurable two tiers transformers (1 Amp of N Tier on Input and 16 Amp of N-2 Tier on Output).
Or it could be some kind of tiered configurable transformer which can take 1 Amp of N Tier and output custom number (not more than 4 or 16) of Amp of Custom tier (lower than N). In that case transformation from 32kV to 32V could be possible via single block.

**Comment by dohvakin96** [comment]
Wouldn´t that be OP and boring? You could just place one of those next to all your machines to supply them with power. You wouldn´t need to organize your base in a good way, keep LV machines close to each other to reduce the cable loss. With that new transformer, you could easily send power with UV or MAXV from your power storage to all of your machines, reducing the energy loss to nearly zero and that with zero engineering and way too low material costs.

**Comment by SapientMC** [comment]
It should be more expensive than original transformer of the same tier.
And no, it will not more boring than chain of 5 transformers to convert 32kV -> 32V like now.

**Comment by Blood-Asp** [comment]
A transformer that does all tiers in one step? not happening. Max 2 steps at once. And then the output stays at max 4 amp.
But even if i say max 2 steps, that does not mean i will actually do it. Maybe once i have the time, maybe not.

**Comment by SapientMC** [comment]
Even 2 tiers at once would be better than now. BTW they could be only down-step.

**Comment by Blood-Asp** [comment]
you know they allready can step up in one go? ULV into a UV transformer works.

**Comment by SapientMC** [comment]
Yep. I'm using it on output of all generators. And only near consumers i need chains of down-step transformers.

BTW, IRL single computer case transformer can input 220v and output 12v (for HDD), 5v (for USB) and 1.5v (for CPU and RAM) at the same time. On substations electricity transforms from 200kV to 380/220V by one step. So... chain of transformers in MC are not logically, not aesthetically, not rationally.

**Comment by Blood-Asp** [comment]
As you said, you do not chain transformers IRL. But you also do not wire 200kV directly into your PC and transform it down in one go even trough it would technically be possible.
You go in steps. 380kV -> 10kV in long distances. 10kV ->230V close to the homes, 230V -> 12V in your pc. If you chain transformers next to every machine, you simply planned your factory inefficienctly. Do not line the highest voltage until the machines, split voltages up per room or per level or something and again transform down per machine row. And then the last step next to the machines. Suddenly you have something that resembles RL without chaining transformers.

**Comment by SapientMC** [comment]
For each row of 16-24 machines (LV for example) i have 4-8 LV transformers, 2-4 MV, 1-2 HV and 1 of each next tier up to 32 kV. And so on for each row (i have 6 or 7 of them).

Somewhere a have single multiblock (ImpComp or Vac Freezer) and personal chain of transformers 32kV -> 128 (or 512)V

I'd like to have an option to make 2kV from 32kV in one step, and 128 V from 2kV in another step.

**Comment by DerEchteLanger** [comment]
Just signed up to see my idea is allready reported, but no idea who took "Elthy" on Github, maybe it was me years ago...

Anyway, 2 tiers at once would be great, it would half the size of the tranformer chain. Having the output staying at 4 amps is also great, otherwise you wold have to be realy carefull with how much machines you hook up or allway use 16x wire, which sucks at low voltages...

**Comment by DarknessShadow** [comment]
I don't think this is necessary.
Uptransforming is no problem at all
Downtransforming can be done to any voltage with the help of ic2
gt cable -> ic2 transformer -> gt transformer
