### ISSUE TITLE
Thorium Fuel Rod is OP in 5^3 Nuclear Reactor

### ISSUE THREAD

**Issue by ShelfOwl** [Blood-Asp/GT5-Unofficial#29]
In Pressure-Vesseled Nuclear Reactor, Thorium Fuel Rod produces Heat Unit(Hu) as much as Uranium Fuel Rod.
So thorium works just 2.5x durable (and 1/6 cost) fuel than uranium. Was it intentional?

For example, A design below produces 896Hu/s per 4 Thorium ingot, 448 Million EU per 1 cycle using Stirling Generator.
http://www.talonfiremage.pwp.blueyonder.co.uk/v3/reactorplanner.html?21p7dsedt1jfyv3ow0nznizkke8otxxt1cvtmq6glq801lsblppngcd54opg9wo6t7rvqoz9igz96gw

![2015-05-08_22 21 24](https://cloud.githubusercontent.com/assets/7645511/7863602/3b0dbde8-0598-11e5-98b1-9f93364f8411.png)

**Comment by Blood-Asp** [comment]
Is this in version 5.08.18?

**Comment by ShelfOwl** [comment]
A screenshot is not 5.08.18, but I confirmed also in 5.08.18
I think it is not a code issue but a game design/balance issue, 
so you will confirm it on all version > GT 5.08.01

**Comment by Blood-Asp** [comment]
Fixed with Iridium neutron reflector. Must be fixed on IC2 side for other reflectors.
