### ISSUE TITLE
Multiply redstone transmitters bug

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#291]
We have several wireless redstone transmitter covers and only one receiver, all set to same frequency. Receiver detects signal only from last placed transmitter.

I think it should work like OR condition in this case and detects signal from any transmitter.

**Comment by Blood-Asp** [comment]
I was allready asked this a while ago and rejected it. The GT Wireless redstone is point to point without logic. You can allways add logic by yourself.
For me adding a OR behavior would make it nessary to completely recode the GT wireless redstone and i will not do that.

**Comment by SapientMC** [comment]
Ok, thanx for answer.
