### ISSUE TITLE
Suggestion: Add battery slot to Regulator

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#292]
I'm using regulators to insert nuclear fuel rods to defined slots into reactors. It needs about several thousands of EU for ever. It would be grate to have an option to insert battery in regulator itself instead of placing personal batbuffer for each one of them.

**Comment by Blood-Asp** [comment]
If you knew how much work it is to add one single slot to a gui... 
Well, i see that a batteryslot would somehow make sense, so i will keep the idea and might do someday.

**Comment by SapientMC** [comment]
Thanx a lot Blood.

**Comment by Blood-Asp** [comment]
Added to idea collection
