### ISSUE TITLE
NEI GUI recipes generalization

### ISSUE THREAD

**Issue by desertir** [Blood-Asp/GT5-Unofficial#293]
GT's thermal centrifuge and ore washing plant respectively use the same IC2's GUI in NEI.
It's not important issue but usefull to know amount of amperes (two for thermal centrifuge O_o) and voltage for these machines.
Maybe I'm not first who complains about it.

**Comment by Blood-Asp** [comment]
Not sure how to do that. The other GUIs come from IC2 and i can't simply disable them. And when adding another GT version of it, it would be double.

**Comment by desertir** [comment]
I see. Okay.
