### ISSUE TITLE
Some GemBlocks don't have any Texture

### ISSUE THREAD

**Issue by Dream-Master** [Blood-Asp/GT5-Unofficial#294]
Some GemBlocks don't have any Texture (GT 5.09.11)
![screenshot 2015-11-01 21 54 34](https://cloud.githubusercontent.com/assets/2970688/10871302/5dc64e42-80e3-11e5-9403-42b29730bbf8.png)

**Comment by Blood-Asp** [comment]
It is not that they have no texture, they should not exist in the first place...
