### ISSUE TITLE
Strange result of electrolyzing

### ISSUE THREAD

**Issue by desertir** [Blood-Asp/GT5-Unofficial#295]
Another issue from me.
Electrolyzing of
+ ilmenite dust
+ dark ashes (not sure that is wrong)
+ cassiterite dust (and cassiterite sand)

gives double or wrong result.
It's the right recipes or not? It's cheating especially for ilmente because it's source of titanium dust.
And please check chromium dioxite recipes too (creating in chemical reactor and its electrolyzing).

**Comment by Blood-Asp** [comment]
Dark ash is worth 2 ash or 2 carbon.
casserite is worth 2 tin.
So these are fine.
But what exactly is your issue with ilmenite?

**Comment by desertir** [comment]
I talk about a ratio of chemical elements.
Look, the formula of ilmenite is FeTiO3. So we need to take five (is a sum of all indexes in the formula, of course you know this) dusts of ilmenite for its electrolyzing. That's ok but electrolyzing result is _two_ parts of an iron, _two_ parts of a titanium and _six_ parts of an oxygen. Why? I think the result must completly replicate the formula.
"casserite is worth 2 tin"
I agree but multiplication occurs at a stage of macerating (one cassiterite ore -> four crushed cassiterite ores).
You can to compare these recipes with others (for example electrolizyng of magnetite or ruby dust).
Where my bad?

**Comment by Blood-Asp** [comment]
The 1 casserite ore -> 4 crushed casserite is correct. Or does doublication happen also in another step?
Also, what version are you using? 5.08 or 5.09? I changed the ilmenite/titanium processing in beween.

**Comment by desertir** [comment]
5.08
Maybe a misunderstanding.
"The 1 casserite ore -> 4 crushed casserite is correct"
Agree, no problem.
"Or does doublication happen also in another step?"
In a sence, yes for cassiterite. I think it will be better if I make some screenshots.

A silicon dioxide and a cassiterite dust/sand has equal patterns of chemical formulas but...
![image](https://cloud.githubusercontent.com/assets/10061582/10898665/ae0cd6da-81ee-11e5-9427-d0cef01d3bb9.png)
![image](https://cloud.githubusercontent.com/assets/10061582/10898715/2ec098ca-81ef-11e5-8d6e-72a601b4a37f.png)
I can't understand why these recipes different :/

A calcite dust and an ilmenite dust too.
![image](https://cloud.githubusercontent.com/assets/10061582/10898672/c3d890a8-81ee-11e5-9d93-f06c486591ea.png)
![image](https://cloud.githubusercontent.com/assets/10061582/10898779/e6b1fb86-81ef-11e5-90af-6eb512dba968.png)

**Comment by alexdelphi** [comment]
> A silicon dioxide and a cassiterite dust/sand has equal patterns of chemical formulas but...

I agree. For the compounds of the form **Cm(Hn)(Ok)**, where m,n, and k are numbers and C is not a liquid _or_ a cell, I propose to generate a recipe: **m** of such a compound -> **m** of element C

**Comment by Blood-Asp** [comment]
found in the code that they are forced to output more. likely as balancing as all materials are quite needed/rare.
