### ISSUE TITLE
Support mass fabs in PA

### ISSUE THREAD

**Issue by willis936** [Blood-Asp/GT5-Unofficial#297]
Late game EU gain fusion reactions are practical through mass fabrication but require hundreds of discrete mass fabs.  If there's no real deterrent to a player they're going to take this route but it loads the server.

**Comment by PaladinOne** [comment]
By 'PA' I assume you mean 'Processing Array'?

**Comment by willis936** [comment]
Yes I meant processing array.  I remember Blood Asp mentioning in the thread that it isn't supported.  Admittedly I haven't tested this to confirm.

**Comment by Blood-Asp** [comment]
Rejected. On one side not possible codewise. mass fabs do not use a recipe system but special code.

Otherwise the 5.09 changes invalidate your arguments anyways.
