### ISSUE TITLE
ore or i dont know

### ISSUE THREAD

**Issue by Ldmf** [Blood-Asp/GT5-Unofficial#298]
Finde a block Namd gt.blockores.0.name in woldgen if you min it it will give you cobbel stone

![2015-11-04_14 03 11](https://cloud.githubusercontent.com/assets/15316448/10938817/59814f82-82fd-11e5-8fa4-aac97a5eb259.png)

Gt-u version 5.08.32

Modpack BeyondReality version 2.3.6e

Sory 4 my bad english

**Comment by Blood-Asp** [comment]
Some other mod tries to generate GT ores and fails. Had that issue seen a few times in the past, but should be fixed in most cases. Is the map you play with old?

**Comment by Ldmf** [comment]
no nerly new map i can re generat and make a new screenshot if you need

**Comment by Blood-Asp** [comment]
Afaik it was a old version of IHL that caused it, but i do not know for sure. To make sure, i would need to see how the broken orevein is formed. By that i mean completely digged out.

**Comment by Ldmf** [comment]
no problem any more thx 4 information
