### ISSUE TITLE
RF into GT energy not working

### ISSUE THREAD

**Issue by florian96** [Blood-Asp/GT5-Unofficial#30]
Hey i try to connect a Energy cell with Gregtech cable to a Gregtech Machine. The Cable Connecting but not Transfer Energy.

**Comment by Blood-Asp** [comment]
Cables only do GT EU into RF, not the other way around. To turn RF into GT EU you must place a RF storage next to an GT Transformer. The same way IC2 EU -> GT EU works.

Also some mods do not have the nesseary method implemented, so i can't garantee it to work everywere.

**Comment by florian96** [comment]
How many RF can Transfer for example a 1x TIN cable?

**Comment by Blood-Asp** [comment]
It still transfers GT EU, allways at 1 AMP per machine. When inserting it into a RF machine it gets converted into RF at the configurated rate (default 3.6). So a Tin cable can transfer a max of 115RF/t - cableloss (3.6RF/t loss per block cable).
