### ISSUE TITLE
Forestry 4 logs and planks are not handled by Gregtech

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#300]
GT5E 5.08.32
Forestry 4.1

Logs craft to 4 planks without saw
Logs are not crafted to planks in cutting machine
Planks are not cut to slabs by saw or cutting machine
Slabs are not cut to covers...

See: Beyond-Reality/BeyondRealityModPack#341

**Comment by leagris** [comment]
@Blood-Asp I don't know if it is a limitation of Gregtech API or the Cutting Machine or GTTweaker, but I can not get NBT {WoodType: int} matched for Input and Output.

**Comment by leagris** [comment]
@Blood-Asp @mezz, please See [IC2 Forum post](http://forum.industrial-craft.net/index.php?page=Thread&postID=196036#post196036) by @gregoriust 
>  Edit: And now I have made a Recipe Map for that in GT6. Could easily be copypasted into the Recipe Map System of GT5U too. 

I may not be enough aware of all tenants to make informed comments on this or that implementation choice. But I really hope you all three smart guys can team-up to find a nice arrangement.
Players of BeyondReality classic would be very grateful if you did.

**Comment by Dream-Master** [comment]
My java knowledge is very basic so if someone push some code i will merge it to gttweaker no problem.

**Comment by mezz** [comment]
The wood ItemStacks are using damage values instead of NBT now, it should be easier to fix.
It seems that things are only working with damage values 0-15 but the woods go up to 28.
