### ISSUE TITLE
Harvest level of GT ores bugged

### ISSUE THREAD

**Issue by shifuren** [Blood-Asp/GT5-Unofficial#301]
I have found 3 types of bugged ores (as per MaterialProperties.cfg)
1. Ore is in config but not present ingame (Lemurite, Kalendrite, Ignatius)
2. Ore ignores any harvest level set in config, even defaults=> any version is harvest level 0, even granite versions (Cobalt, Shadowiron, Vyroxeres, Alduorite, Ceruclase, Midasium, Vulcanite, Sanguinite, Eximite, Meutoit)
3. Small ores work okay (config - 1), main ores are always level 0, even granite versions (Prometheum, Atlarus) 
Using latest Gregtech 5.09.11

**Comment by shifuren** [comment]
Issue seems to affect not only metallurgy ores:
no config option for harvest level of lignite coal at all,
type 3 - amethyst ignores config (0 when set to 11)
and new type 4 - both small and regular ores bugged (harvest level 0):
- cobaltite ore ignores config (0 when set to 10),
- tungstate ore ignores config (0 when set to 9),
- opal ore ignores config (0 when set to 10),

**Comment by JasonMcRay** [comment]
Ores are keeping their harvest level when they were already generated.
So changing the config will affect ONLY the newly generated ores.

**Comment by shifuren** [comment]
I know, i'm testing on new ores.

**Comment by shifuren** [comment]
Also, metal blocks and all blocks produced from GT materials ignore harvest level in config, even if it works for ore (copper harvest level for some types of steel etc, wtf?)

**Comment by shifuren** [comment]
Testing now with Gregtech 5.09.13, most ores that were lvl 0 now set to defaults, but still ignore any changes in config.
Still lvl 0: Amethyst
Some of bugged ores are now with granite versions = same level (for example 3), even if granite itself is higher (4)
Also, now all GT ores effective harvest tool shown in Waila is shovel, but i guess it's their bug as pickaxe harvests them correctly

**Comment by PaladinOne** [comment]
Somehow or another WAILA (and WAILA Harvestability) have never been really good with GT ores.

**Comment by Blood-Asp** [comment]
Tested it and it is working.
Yes, WAILA can not be trusted here. Either really try to harvest them, or scan them with the GT creative scanner. The shown "meta" there is the harvestlevel.

**Comment by JasonMcRay** [comment]
I heard that WAWLA mod works rather well with GT ores (http://minecraft.curseforge.com/projects/wawla-what-are-we-looking-at)

**Comment by shifuren** [comment]
GT 5.09.16, no, it's not working, or there is some other mod-interaction problem...
As can be seen on image meta says harvest level 9 as set by me in config, tool has harvest level 0 and cant harvest it - used only to show harvest level in waila (tested)
[img]http://i.imgur.com/3WpV7it.jpg[/img]
ok, now we take pickaxe with copper harvest level -
[Imgur](http://i.imgur.com/mHg0wV6.jpg)
it works and drops when mined, so regardless of meta, it is incorrect
