### ISSUE TITLE
Game-crashing bug with GT

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#302]
http://pastebin.com/zqe61hKv   CORRECT crash log

And this is what it looks like before a crash:   https://drive.google.com/file/d/0B7PNQy2eWIcYWFRtS3dNUG9oeGs/view?usp=sharing

**Comment by JasonMcRay** [comment]
You dont seem to have installed GregTech. I only see GT Extras and thats (if i am not mistaken) only for GT6

**Comment by axlegear** [comment]
I assure you, GT5U is definitely installed.  Five people were playing until it crashed.

**Comment by axlegear** [comment]
Ah crap, wrong damn crash file...

**Comment by axlegear** [comment]
There, posted the correct log and the server logfile showing the wave of spam.

**Comment by JasonMcRay** [comment]
Update forestry. There is a bug in build44 with fermenter when you try to
extract fluid when there is none.

However the crash log also implies corrupted genome from some bees. If the
update will not resolve that let me know and i can walk you through
removing the corrupted genom (not hard to do)

**Comment by axlegear** [comment]
The forestry update seems to have fixed it.  Thanks!
