### ISSUE TITLE
(Suggestion) Punch Card Processor

### ISSUE THREAD

**Issue by Axelandre42** [Blood-Asp/GT5-Unofficial#303]
Hello,

Can you add un __Punch Card Processor__ like computers without filesystems but programmed by editing Books, scanning and printing on punch cards and it can access and control other machines. Or something like that...

Best regards,
Axelandre42 !

**Comment by DarknessShadow** [comment]
>access and control other machines

How exactly should that work?

**Comment by Axelandre42** [comment]
Access : Get data like the Tricorder

**Comment by Blood-Asp** [comment]
Greg did start with something similliar to that, but did never finish. (you can find punchcards as items and a book about what he planned)
But that is far to complex for me to programm something like that just on a suggestion. I will for now only implement my own ideas and only accept small ideas from others that can be done in a few min of coding.
