### ISSUE TITLE
Gregtech's Salt can't work with pam's harvestcraft Pulverizer

### ISSUE THREAD

**Issue by NyanU** [Blood-Asp/GT5-Unofficial#304]
The salt will be converted to gregtech because Ore Dict(Gregtech)
version:
Gregtech_1.7.10_5.08.23
Pam's HarvestCraft_1.7.10i

**Comment by leagris** [comment]
I think it pertain to HarvestCraft using ore dictionary ingredients in its pulveriser recipes.
Y can also configure unification targets within GregTech unfication.cfg and then force Pam's harvestcraft salt unification.

**Comment by NyanU** [comment]
It defaults to false , is set to true?
 }

    harvestcraft {
        B:dustSalt_false=false
    }

**Comment by leagris** [comment]
Yes and set all other dustSalt unifications to false.

**Comment by Blood-Asp** [comment]
It must be set serverside and correct setting is: harvestcraft {
B:dustSalt_false=true
}

That should be all about this issue.
