### ISSUE TITLE
[Idea] Bring back the pneumatic  generator upgrade from GT 4 into GT 5

### ISSUE THREAD

**Issue by Invincible92** [Blood-Asp/GT5-Unofficial#305]
It would be a nice idea bring back the pneumatic generator upgrade (the one which allowed machines to run with MJ, now it would be RF) in order to connect machines in a very tight design with multiple pipes though one face of the block, for example, using Ender IO conduits or a logistics pipes network, because there is not a GT power conduit/converter in that mods. Currently, power needs a face of the block, item import/export needs another one and, only if you're using liquids, a fluid import/export needs an extra one. 

Being possible to import/export items and power the machines via one face of the block (in tight places) would be a nice advantage.

The amount of RF to EU for the upgrade (or viceversa) could be the same present in the config with the conversion that GT cables can do, so it wouldn't be necessary to add a new line in the config for that.

**Comment by DarknessShadow** [comment]
You could just change this
>B:InputRF_false=false

**Comment by DerEchteLanger** [comment]
Having complicated systems for energy and item distribution is one of the main elements in GT. It wouldnt make sense to add a workaround for energy loss, overvoltage, over current...
