### ISSUE TITLE
FPS lag down because of Basic Steam Turbine.

### ISSUE THREAD

**Issue by antkatcin** [Blood-Asp/GT5-Unofficial#306]
Looks like in case if Basic Steam Turbine is under supplied by steam (so turbine on/off few times per second) it cause significant FPS down (60 to 44 for me). That is reproducible on GT 5.08.32.

Also i notice that it's reproducible for one of the streamer. That's a link on exactly moment: https://youtu.be/9lp3d1TBRXQ?t=15m5s

**Comment by axlegear** [comment]
This is actually true of all machines.  For example, hook a hopper up to an HV macerator and fill it with chipped rubies.  It macerates them so far there's an on/off period between each and every one, causing my FPS to drop from ~80 to ~6.

**Comment by axlegear** [comment]
Note:  Installing OptiFine_1.7.10_HD_U_C1 seems to fix this problem, though there may be other bugs caused by it.  I am not sure what specific setting fixes it, but it's there somewhere.

**Comment by Blood-Asp** [comment]
Pretty sure this is more of a vanilla minecraft issue.
Is theory i could do someting against it by making it so that the state of machines only can change less often, but that again creates other problems and the check would impact the TPS(a bit) instead of FPS.

**Comment by antkatcin** [comment]
> Is theory i could do someting against it by making it so that the state of machines only can change less often

That can be useful for machines that supposed to be constantly provided by steam/fuel/lava/gas. E.g. If machine stops because of resource shortage it need something like 5 seconds to restart.

**Comment by JasonMcRay** [comment]
> That can be useful for machines that supposed to be constantly provided by steam/fuel/lava/gas. E.g. If machine stops because of resource shortage it need something like 5 seconds to restart.
I am up for this. Production machines (like for example Bending machine) will start few seconds/ticks after you supply it with enough power again after they got stuck.

**Comment by Blood-Asp** [comment]
did some small improvements, but no idea if it will really help

**Comment by axlegear** [comment]
Even a small improvement is an improvement, and i'll appreciate them!
