### ISSUE TITLE
Remove wrought iron from mod???

### ISSUE THREAD

**Issue by MFernflower** [Blood-Asp/GT5-Unofficial#308]
I play on a very buggy modpack that has GT5-Unofficial in it and I cannot seem to make wrought iron without some crazy thing. I dont know if this is the modpack or if wrought iron is broken

**Comment by PaladinOne** [comment]
Normally, Wrought Iron is smelted as Iron Nuggets -> Wrought Iron Nuggets, however it can also be made in an Arc Furnace.

Normally, Iron in a Blast Furnace should make Steel.

**Comment by MFernflower** [comment]
Ill try that, thanks

**Comment by DarknessShadow** [comment]
There is probably another mod adding a recipe for iron nuggets -> steel nuggets in a furnace.

**Comment by MFernflower** [comment]
I found the problem. another mod was messing with OD - closing now
