### ISSUE TITLE
Charcoal pile igniter doesn't work with forestry woods

### ISSUE THREAD

**Issue by PaulMadsen** [Blood-Asp/GT5-Unofficial#309]
Tried it with blue maho.  It would not ignite.  Replaced maho with vanilla oak in an identical configuration.  It then ignited.

**Comment by leagris** [comment]
I think it is a know issue as it is not checking ore:logWood registered logs. but because Forestry also register fireproof logs under ore;logWood it is going to be an issue or it need checking for fuel value.

**Comment by Blood-Asp** [comment]
Ore dict support is planned. Currently only vanilla wood works.

**Comment by Blood-Asp** [comment]
added oredict support
