### ISSUE TITLE
Unlimited Energy

### ISSUE THREAD

**Issue by florian96** [Blood-Asp/GT5-Unofficial#31]
Hey if you transfer energy from a Resonant energy cell into GT energy with a Ultimate Transformer and your Resonant energy cell has a little bit energy, It generates in the energy cell endless energy.
I think 5 RF per tick.
![image](https://cloud.githubusercontent.com/assets/9999676/7873255/47990a38-05a0-11e5-8d01-5100c8d919fd.png)

**Comment by Blood-Asp** [comment]
can't replicate that. Energy Cell runs empty for me and energy flow stops.
