### ISSUE TITLE
Advanced Miner II ignores GT ores.

### ISSUE THREAD

**Issue by PaulMadsen** [Blood-Asp/GT5-Unofficial#310]
In an attempt to determine the range of the miner, I setup the miner on a flat surface of regular GT coal.  The miner punched through it without collecting any of it.  It also ignored a 3x2x3 chunk of ore I had placed down about 5 levels below the miner.  It picks up the small ores, just not the coal ore.  This happened in SSP and SMP.

**Comment by DerEchteLanger** [comment]
If i remember it right the Advanced Miner 2 doesnt mine self placed blocks, to avoid duplication (afaik it has a higher output than mining the ore by hand).

**Comment by Blood-Asp** [comment]
Correct. The miner only mines naturally generated GT ores, nothing else. That is so to prevent using the miner back at the baae were supply for it is easy.

The range is 47 blocks, so 95x95 block area.
