### ISSUE TITLE
[5.09.11] Analyzed Prospection Book - fluid name localization

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#311]
When I succesfully print the book containing information from Seismic Prospector the fluid name is not localized. It says something in the line of fluid.liquid_light_oil or something like that

**Comment by Blood-Asp** [comment]
Do you use an localisation other than en_us? For me it does work fine somehow.

**Comment by JasonMcRay** [comment]
I have a feeling that I use en_GB localization.

**Comment by Blood-Asp** [comment]
then i close this until you say otherwise.
