### ISSUE TITLE
GregTechSensor Kit/Card

### ISSUE THREAD

**Issue by Ldmf** [Blood-Asp/GT5-Unofficial#315]
Is it right 

4 Slots

![2015-11-12_19 04 19](https://cloud.githubusercontent.com/assets/15316448/11126655/44b4b480-8970-11e5-9bf7-89d59ecd3988.png)
![2015-11-12_19 04 25](https://cloud.githubusercontent.com/assets/15316448/11126665/4d22b4fa-8970-11e5-9979-16e9f74acab3.png)

One slot

![2015-11-12_19 05 48](https://cloud.githubusercontent.com/assets/15316448/11126699/6bca0840-8970-11e5-8442-a81b9ba91d0f.png)
![2015-11-12_19 05 53](https://cloud.githubusercontent.com/assets/15316448/11126706/74547dce-8970-11e5-8117-f483e47ba399.png)

**Comment by Blood-Asp** [comment]
This is a simple overflow. Too big numbers to show correctly. I should be able to fix this with bigintegers.

**Comment by Ldmf** [comment]
in 4 solots only one slot will be shown in the panel (no additiv)(the big number i mean)

![2015-12-16_20 48 51](https://cloud.githubusercontent.com/assets/15316448/11852111/837fbfda-a436-11e5-8b90-4b42ba8cadaa.png)
