### ISSUE TITLE
Pipes/conveyors put items into output slot in Bronze B-Furnace

### ISSUE THREAD

**Issue by ShelfOwl** [Blood-Asp/GT5-Unofficial#317]
when inputs are filled
![b_furnace](https://cloud.githubusercontent.com/assets/7645511/11161166/01f36b10-8ab9-11e5-9769-f1a4e389f57d.png)

**Comment by DarknessShadow** [comment]
As far as I know thats intended so its not so easy to automate.

**Comment by Blood-Asp** [comment]
Yes, they are not intended to be automated.
