### ISSUE TITLE
Suggestion: Imersive Engineering compatability

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#321]
There is plant oil, ethanol, Bio diesel, creosote oil, coal coke, and there is already built in interaction with IC2 and GT power.

**Comment by Blood-Asp** [comment]
IE is still in it's early stages and changing quickly. So i will wait a bit for adding compatability.

**Comment by bear989** [comment]
ok, thanks for the answer, after dealing with other developers, I really
appreciate you even more than I already do!
