### ISSUE TITLE
5.09.11 depend on AppliedEnergistics2

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#323]
Gregtech can not start without AppliedEnergistics2

**Comment by axlegear** [comment]
Works fine for me and I don't have it.

**Comment by Blood-Asp** [comment]
how about a crash log?

**Comment by leagris** [comment]
##### mods:
```
-rw-rw-r-- 1 lea lea 8956359 nov.  17 13:25 gregtech-5.09.11.jar
drwxrwxr-x 2 lea lea    4096 nov.  17 13:25 ic2
-rw-rw-r-- 1 lea lea 5615721 nov.  17 13:24 industrialcraft-2-2.2.791-experimental.jar
```
[crash-2015-11-17_13.25.40-client.txt](https://gist.github.com/leagris/241b88608cc1ff1505ab)

**Comment by Blood-Asp** [comment]
Hmm, you had AE2 installed on first run and then later removed?
The gregtech.cfg has a line: ae2integration. that defaults to if ae2 is installed or not.
So change that line or rebuild your gt configs.

**Comment by leagris** [comment]
Ah true!
Thank you for looking at it.
I indeed had, several mods installed and removed.
I was investigating [this modpack issue](https://github.com/Beyond-Reality/BeyondRealityModPack/issues/351#issuecomment-157325006) about some invalid ore dictionary tag on gravel, for opencomputers Chamelium recipe.
Did a binary dichotomy, disabling mods for hours yesterday. 
Found out this invalid tag is only triggered when  Gregtech + Enderio are present but not if either one of these alone.
I worked around it [with this](https://github.com/Beyond-Reality/BeyondRealityModPack/commit/13f588ec73fdd4e3d68ca403bb0be50572798f65) anyway.

**Comment by JasonMcRay** [comment]
Honestly I am finding more and more blocks in NEI with Invalid Oredictionary Tag. For example with ExU and Chisel, I see 15 diferent obsidian versions all named Invalid Oredictionary Tag and it is indeed GT causing this
https://github.com/Blood-Asp/GT5-Unofficial/blob/123aa6ed288b2f67b0d47177f4d27cd6893daf3a/src/main/java/gregtech/common/GT_Proxy.java#L1049
https://github.com/Blood-Asp/GT5-Unofficial/blob/123aa6ed288b2f67b0d47177f4d27cd6893daf3a/src/main/java/gregtech/common/GT_Proxy.java#L1304

**Comment by Blood-Asp** [comment]
GT is not causing it, but showing clearly were other mods made mistakes that creates issues for whole modpacks.

**Comment by JasonMcRay** [comment]
Well.. problem of the problem is, that its not "easy" to find out which mod
is the cause :(

2015-11-17 17:00 GMT+01:00 Blood-Asp <notifications@github.com>:
