### ISSUE TITLE
Incorrect ores at End Asteroids

### ISSUE THREAD

**Issue by faulknercs** [Blood-Asp/GT5-Unofficial#324]
I'm using GT 5.09.11.
In the End red granite ores are generated instead of end stone ores. This only happens with End Asteroids.

![2015-11-16_17 00 15](https://cloud.githubusercontent.com/assets/1216573/11222568/3a767818-8d7c-11e5-83a6-67489e4dbe94.png)

**Comment by axlegear** [comment]
Where do you get End Asteroids?  Because I want them badly.

**Comment by faulknercs** [comment]
I just have `B:GenerateAsteroids_true=true` at `endasteroids` section in config\GregTech\WorldGeneration.cfg, so they are generated in the End around central part.
Also you can change `I:AsteroidProbability` to increase asteroids amount.

**Comment by axlegear** [comment]
oh!  Will that gen new asteroids if I turn it on?  We already breached the end, but would not mind jetpacking or bridging out further if that works

**Comment by faulknercs** [comment]
I'm not sure, but I think, it should, if you reach jetpacking to undicovered chunks.

**Comment by axlegear** [comment]
I hope so.  Blood, can you confirm?
