### ISSUE TITLE
Distillation tower does not stop when output hatches are full

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#325]
I have setup a distillation tower to produce distilled water for my ore processing.
It has an infinite supply of input water and fills an openblock tank with distilled water.
I then found out it is processing forever even when my tank and hatches are full.
This is inconvenient and a waste of energy + a waste of maintenance runs.

Could you fix multiblocks to have them stop processing when output hatches and buses have no room for another cycle of current recipe?
I don't want to do convoluted redstone covers and wiring or setup opencomputers for the sake of distilling water on the go. Further more I can't see any way to detect when a tank has reached some filled amount. Multiblock machines need to pause themselves/

**Comment by leagris** [comment]
Le 17/11/2015 21:44, DarknessShadow a écrit :
> I think its intended that ALL multiblocks run even when the output is full.

I perfectly remind @GregoriusT mentioning something along this.
Gregtech5 was an abandoned unfinished regression from Gregtech4.
My apologies to you @bloodasp because you did make this GT5 a thing like
a Phoenix revive out of its ashes.
But if Gregtech machines can not regulate themselves without other mods
it is feature broken.
This multiblock bug/issue is not a game-play consideration. It is some
coding shortcut to avoid checking recipe outputs against output
inventories free space and put the controller block on hold.

So in the end, instead of spending a few CPU cycles doing this inside
Gregtech multi-blocks, you have to spend 10000x more CPU processing lots
of other mods tiles with tick lagging logic to combine an inexistent
Redstone fluid level emitting tank of a decent size, with Redstone wires
back to a Redstone controlled shutter cover and a full set of Redstone
in-game ore gates to combine comparisons of all output tank levels to
control shutdown fluid input.

This is not brining any meaningful game-play.
This is not saving or optimizing server CPU cycles either.

-- 
Léa Gris

**Comment by axlegear** [comment]
Or you could just build it correctly the first time like everyone else.

**Comment by leagris** [comment]
> Or you could just build it correctly the first time like everyone else.

You know something I don't. Where can I learn it?

**Comment by axlegear** [comment]
If you upgrade the output hatches they will hole more.  You can also use larger output pipes to hold fluids.  I am not sure but you may also be able to use machine blocks as tanks.  I built a distillery system and if I forget to feed it hydrogen cells and empty cells it would backup.  I upgraded to ZPM hatches and stainless steel pipes now I can run 2 or more full barrel batches of oil drums (256 buckets) without overflowing.  If you have Extra Utilities you can also just use drums as storage buffer tanks:  Two pipes facing each other 1 block apart, a pump on one set to import, and a barrel filling the gap.  That will add 256,000mB of buffer space.    A huge tungsteel pipe holds 48,000mB as well, so that's a pretty good 'microtank'.  And lastly, if you use railcraft tanks you can have truly ludicrous storage amounts, tens of millions of mB.  So really, you don't need a complex setup, just build with anticipation for overflow.

**Comment by leagris** [comment]
I have setup a distillation tower to produce distilled water more efficiently than the single block distillery.
I don't always pump out distilled water, so my buffer tanks fills while I am not using distilled water.
The problem is, when my tank is full, the distillation tower continue to process water and discard the output indefinitely.
So it is not a problem of tanks too small, it is a problem of producing distilled water on demand like the single block distillery does.

**Comment by axlegear** [comment]
Why not just switch the machine off when not in use, then?

**Comment by Blood-Asp** [comment]
Fluid Detector + Machine Controller = no overflow. 
I did the same with water input in large boilers to prevent explosions. Works totally fine. Additional mods are not needed, in the best case make the wireing a bit less complex.
That multiblock machines keep running is afaik intended by greg and also now all are used to it and find ways to make it work.

**Comment by leagris** [comment]
Oh well I give up!!!

**Comment by GregoriusT** [comment]
The "Output Overflow" thing wasn't intended (only the "lack of slots
in general removing parts of the output" thing was intended). It was
just me being too lazy to check if the Output actually fits into those
slots.

**Comment by GregoriusT** [comment]
Note that I am talking about the productive Machines, not the
Generators. The Generators have the primary purpose of making Energy.
