### ISSUE TITLE
No asteroids in the End.

### ISSUE THREAD

**Issue by BobZplus** [Blood-Asp/GT5-Unofficial#326]
Just updated to 9.12 and havent seen any of sign of asteroids.
Config option is enabled.

**Comment by axlegear** [comment]
Ditto, sadly.  I tried to enable it for the server, no go.  I then made a single player world and still no asteroids.

**Comment by BobZplus** [comment]
I think with update it just minimize the chance for asteroid to spawn.
Here is the proof:
http://imgur.com/XDYOMf4
It's not so many of them, but they are here.

**Comment by axlegear** [comment]
I flew around for a while and didn't find any

**Comment by axlegear** [comment]
Hope this gets fixed soon!

**Comment by Blood-Asp** [comment]
asteroids in end do generate. But the chance is 1/300 by default, so one in 300 chunks contains a asteroid. this results often in quite a lot of searching. But since they contain lots of expensive materials, it should be balanced that way
