### ISSUE TITLE
[5.09.12] Half return when processing battery hulls

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#327]
I'm not sure exactly when this was introduced, but according to NEI with GT 5.09.12, processing a battery hull in a furnace, arc furnace, macerator, etc. will only produce half as many ingots/dust as plates required to make it - e.g. macerating a small battery hull only produces 1 battery alloy dust, arc-furnacing a large battery hull only produces 9 battery alloy ingots, and none of the processing options return the metal used for the cables.

**Comment by BobZplus** [comment]
Isn't there was a problem were people was abusing recycling to get extra amount of materials? So i think(but i might be incorrect) that it is intended.

**Comment by Blood-Asp** [comment]
was that really different in an old version?

**Comment by TauZer0** [comment]
Gt 5.09.12 (Same on Gt 5.09.11)
![2015-11-23_16 19 56](https://cloud.githubusercontent.com/assets/14206587/11337687/d998e49e-91ff-11e5-84e5-e54c22b8ad5b.png)

Gt 5.08.32
![2015-11-23_16 31 43](https://cloud.githubusercontent.com/assets/14206587/11337692/e6f1480c-91ff-11e5-96cb-b87c91db7a60.png)
