### ISSUE TITLE
GregTech cable try to connect with ae2.

### ISSUE THREAD

**Issue by florian96** [Blood-Asp/GT5-Unofficial#33]
In Version 5.08.18 try to connect the GregTech Cable with the AE2 (rv1) cable and the Thermal Dynamics Cable. 

![image](https://cloud.githubusercontent.com/assets/9999676/7883091/1c494ae0-0614-11e5-990e-1acf0e3036db.png)

**Comment by Blood-Asp** [comment]
Fixed in GT 5.08.19
