### ISSUE TITLE
Unification problems with MineFantasy II's Pig Iron

### ISSUE THREAD

**Issue by doushio9967** [Blood-Asp/GT5-Unofficial#330]
MFII registers its pigiron as
`ingotPigIron`
`ingotRefinedIron`

GT gives it the normal `ingotAnyIron` name, while the Deprecated tag[1] in `api/enums/Materials.java` thinks RefinedIron should be made into normal iron and gives it the `ingotIron` name.
With one item having both the `ingotIron` and `ingotPigIron` name GT will get confused. So depending on mod startup order and such the MF pig iron will either unificate into GT pig iron or just normal iron.

Adding `ingotRefinedIron` to `common/GT_Proxy.java:mIgnoredNames` works around the problem, alltho I guess it would be cleaner to make GT properly re-register MineFantasy's pig iron if it comes across them.

[1]
`/** * Materials which are renamed automatically */`
`[...],`
`@Deprecated RefinedIron (Iron, false),`

**Comment by JasonMcRay** [comment]
I would primarily aim this to MFII devs, because Pig Iron is not the same as Refined Iron.

**Comment by Blood-Asp** [comment]
i will blacklist it. it afaik this would be an issue due to MFIIs double registering of materials.

**Comment by doushio9967** [comment]
>i will blacklist it.

Yes, please do..
