### ISSUE TITLE
food values with spice of life and hunger overhaul changed?

### ISSUE THREAD

**Issue by Alessandro404** [Blood-Asp/GT5-Unofficial#332]
Hi
I'm using the last version of gregtech unofficial (experiental branch), the last ic2exp and the last hunger overhaul/spice of life/applecore in a new world.

I know that some of the foods gregtech adds used to be "feasts" or "large meals" (steam baguette ftw). That doesn't seems to be the case anymore. 

If intentional, I find those values very poor (I don't use harvestcraft or many other foods mod so...)

![2015-11-22_16 34 33](https://cloud.githubusercontent.com/assets/8747581/11324641/dc208a32-9137-11e5-9a54-5498d80bed33.png)

**Comment by Blood-Asp** [comment]
that is likely an issue for hunger overhaul. I can't set the type of food it becomes.

**Comment by JasonMcRay** [comment]
HO is basically looking at crafting steps and then assignes the type. But since many of GT food is made in machines, HO is not recognizing that as crafting steps.
