### ISSUE TITLE
can't make graphene.

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#333]
There appears to be no way to make graphene.

**Comment by Blood-Asp** [comment]
yes, it was allways that way. but i guess, it is time to add a way.

**Comment by axlegear** [comment]
Depending on your means, two ways are postulated IRL.  One is to strip it chemically using an epoxy from graphite which is a means we currently have, the other involves assembling it using nanomachines from raw carbon.  I imagine both would be electrically pricey and difficult.  Plus, potential use for glue!

**Comment by Blood-Asp** [comment]
What exactly do you mean with potential use for glue? looked into wikipedia but found nothing that points at glue for production.
Any recipe Ideas? If not, i will likely add a scientificly incorrect recipe.

**Comment by axlegear** [comment]
Currently IRL, one of the ways being looked at with great potential for producing graphene is by 'tearing' it from graphite using a polymer.  Hence, glue.  https://en.wikipedia.org/wiki/Graphene#Production   They used adhesive tape.

The various other methods are also listed in that article.. so, plenty to work with to be realistic and balanced both.
