### ISSUE TITLE
Transposer bug, OpenComputers 1.5.19.37 Gregtech 5.09.11 Bug

### ISSUE THREAD

**Issue by Rosethorns** [Blood-Asp/GT5-Unofficial#338]
I have filmed the bug please follow the link below to watch the report.
I have filmed this due to it being far easier to show and tell than type.

IMPORTANT: I forgot to mention in the report that this occurs in Multiplayers situations and /not/ single player.

Also I cannot tell from playing where the bug lays here. So I have also brought this to opencomputer's attention

https://www.youtube.com/watch?v=bBwgMiFx4hs

**Comment by JasonMcRay** [comment]
I had similiar problem with just Regulators not wanting to put items in the specified slot. However. I changed the slot to put stuff in to 4 and it started to work just fine.

I have a feeling that the slots are number 4,5 and not 5,6 for the inputs. Have you tried that?

**Comment by Rosethorns** [comment]
As you saw in the video I confirmed that the slot number for the left hand slot is 5. But I will check 4 just for completeness sake.

**Comment by Blood-Asp** [comment]
The check for it being the right item fails. You need the add in the fluid in the recipe first for it to work. That is a function to prevent insertion of items that are not part of the same recipe. I could not find a way to match the two items first and the fluid last so far.

**Comment by Rosethorns** [comment]
But you allow manual input? I don't see the reason for such a restriction when you allow manual input anyway. Its just confusing and. As has lead to this report. Appears as a bug rather than a feature.

**Comment by Blood-Asp** [comment]
that is to make more complex automation possible without filters and stuff. that way machines can not get stuck by automation inserting the wrong items. it helps a lot. only that it does not accept the second items without the fluid inside is what should not be.

https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_BasicMachine_GT_Recipe.java#L554-L567 
that is the problematic method. i somehow can't think of how to fix that.
