### ISSUE TITLE
5.08.18 unificate to gt whereas unification is set to false

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#34]
If all unification targets for an item are set to false, it is unified to Gregtech.

It is an issue with mods that don't use the Ore Dictionary name in recipes.

Example: gt:ingotDarkSteel is incompatible with EnderIO crafting and repair recipes:
https://github.com/SleepyTrousers/EnderIO/issues/2529

**Comment by Blood-Asp** [comment]
set default unification taged of dark steel to enderio in 5.08.19
