### ISSUE TITLE
Lv Machine casing

### ISSUE THREAD

**Issue by mightydanp** [Blood-Asp/GT5-Unofficial#340]
I am having trouble making wrough Iron for a lv Machine casing, but I looked into nei and couldnt really find a way to make it. Is there a way to make it without a machine or what not or ?

**Comment by JasonMcRay** [comment]
Wrought Iron is made by smelting Iron Nuggets inside a furnace.

**Comment by Blood-Asp** [comment]
exactly, smelting nuggets is the early way.
