### ISSUE TITLE
Quantum Chest looses items when used with enderio itemduct

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#342]
Most likely crossmod issue. If you will figure that there is nothing you can do @Blood-Asp about it. I will repost this to EnderIO (or maybe @HenryLoenwind, @tterrag1098 - who seems like current most active eIO collaborators - can give an insight what might be wrong and if it is eIO or GT).

![d47249b2-96da-11e5-8fec-b974eec1644c](https://cloud.githubusercontent.com/assets/4236895/11561422/a932ee06-99c7-11e5-80a0-4f42efc26981.png)

> QuantumChestII - EnderIoItemConduit - VanillaChest
put a few stacks into the QChest manually, it showed 1500+
pumped them out to the VanillaChest with EnderIoItemConduit using 12 speed upgrades.
piped them back from VanillaChest to QChest with EnderIoItemConduit using 12 speed upgrades.

>Very reliable to reproduce, i noticed it when moving stone from quarry, to another quantumchest a few blocks away, somehow went from over a million stone or so down to about 10k.

> tried without speed upgrades and 2 stacks manually inserted into empty QuantumChestII,
pumped out to VanillaChest with EnderIoItemConduit without speed upgrades, 2 stacks in vanilla chest.
Pumped them back into QuantumChest with EnderIoItemConduit without speed upgrades, only 64+4 left. Was using CobbleStone. So extraction works fine, insertion is bugged.
Insertion using ME export bus seems to work tho.

**Comment by Blood-Asp** [comment]
Got it fixed. It was a GT error, but only happend when inserting a non pow2 number of items two times withing two ticks. So it does not happen in most combinations.
