### ISSUE TITLE
Neodymium Rod

### ISSUE THREAD

**Issue by Ldmf** [Blood-Asp/GT5-Unofficial#343]
If you put a magnetic version of a Neodymium igot i a Excuter you get normal rods out of it

![2015-12-03_21 00 21](https://cloud.githubusercontent.com/assets/15316448/11572391/49d286a8-9a01-11e5-9804-826647637096.png)

Beyond Reality 2.3.7a

GTU 5.09.12

**Comment by Blood-Asp** [comment]
Intended behavior. Processing with heat demagnetizes. So for rods you must first extrude and then magnetize.
