### ISSUE TITLE
New crops all have the same stats

### ISSUE THREAD

**Issue by retep998** [Blood-Asp/GT5-Unofficial#347]
You gave them all the same stats of `2, 0, 5, 2, 6`. This is entirely uncreative and also means that these crops all have a higher chance of cross-breeding to each other than to other crops even though they shouldn't be any more similar to each other than to the others.

**Comment by Blood-Asp** [comment]
My knowledge about crops is quite limited. If you give me some good example stats i could update them. Or should i just randomize the stats?

**Comment by retep998** [comment]
Well, for example the last stat is weediness, which means the more of a weed that plant is, the higher it should be, while if it is a rare plant the weediness should be lower. Something like the iridium crop should have a weediness of 0 because that shit is probably super rare, meanwhile trollplant can have a fairly high weediness because why wouldn't it be a weed?

To quote the IC2 API:

>* - 0: Chemistry (Industrial uses based on chemical plant components)
* - 1: Consumable (Food, potion ingredients, stuff meant to be eaten or similarly used)
* - 2: Defensive (Plants with defense capabilities (damaging, explosive, chemical) or special abilities in general)
* - 3: Colorful (How colorful/aesthetically/beautiful is the plant, like dye-plants or plants without actual effects)
* - 4: Weed (Is this plant weed-like and rather unwanted/quick-spreading? Rare super-breed plants should have low values here)

Don't just randomize the stats. If you want, I could go through and choose some stats myself, just tell me.

**Comment by Blood-Asp** [comment]
If you are fine with going trough them yourself that would be good. Otherwise have currently other things priority to fix.

**Comment by axlegear** [comment]
I would also like to see this tweaked as it has made it super difficult to get any normal GT or IC2 plants.  It's just GT5U as far as the eye can see.
