### ISSUE TITLE
IHL platinum group and GT not unifying 

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#349]
for myself I can fix this easily with backdating IHL but larger automation setups may have issues.

**Comment by Blood-Asp** [comment]
I had some codelimitations, so it is currently not oredicted. But i guess, i should try again. What exactly are the issue? All unprocessed IHL sluge not being able to be processed, or also something else?

**Comment by bear989** [comment]
IHL platinum group wont process, tiny platinum group doesn't work with GT counter parts
