### ISSUE TITLE
Minor bug:  Data Orb achievement not working

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#352]
Achviement doesn't unlock when you make one, including dropping and picking it up.
I've already made 9 for replicators.

**Comment by Blood-Asp** [comment]
I know for sure this works. Just did it myself a few days ago. Should be drop and pickup. The achievement before is correctly unlocked?

**Comment by axlegear** [comment]
AFAIK it has never worked

**Comment by Blood-Asp** [comment]
confirmed working on my side. so not sure what happend on your side...

**Comment by axlegear** [comment]
Just a note:  Clearing my character profile or making a new world to reset the achivements, then picking up an orb, it works.  Must have been a corrupt file on my side.
