### ISSUE TITLE
Possible minor bug:  Oil-free chunks

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#355]
Possibly unintended, or I may have just misread.  But while most chunks have some amount of oil or natural gas, even very little, every once in a while a chunk has nothing.
Previously this would generate an unuseable datastick in the seismic prospector, but that seems to be fixed now.
If you use a debug scanner, these chunks give no oil/gas readout like normal chunks.

**Comment by Blood-Asp** [comment]
It is intended. Actually 50% of the oil sources should be <1.  It still shows that there is a oil type, so i maybe should make it clear by changing it to "no oil".

**Comment by axlegear** [comment]
Ah, good.  Thanks!
