### ISSUE TITLE
Possible bug:  Diesel has 1/2 the energy of Light Fuel

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#356]
Nitro diesel is 512,000.  Light fuel is 256,000.  Diesel is 128,000.

Heavy fuel is 160,000.  Sulfuric light fuel is 32,000.  Oil and light oil is 16,000.  Raw oil is 24,000.  Heavy oil is 32,000.
Naphtha is 128,000.  LPG is 80,000.
Refinery gas is 35,000

Most of these make sense and seem right except diesel.. making diesel and then into nitro-diesel seems to be a waste.

**Comment by Blood-Asp** [comment]
That is an intended change in the last update. Diesel is the normal fuel of all other mods and often much cheaper produced. It is now only in for cross mod compat. Diesel -> nitro fuel process became less efficient to show that. Now you can directly and more efficient produce nitro fuel from light fuel.
