### ISSUE TITLE
Minor bug:Thaumium Block of Gregtech can't be recognized by Thaumcraft

### ISSUE THREAD

**Issue by secirpac** [Blood-Asp/GT5-Unofficial#358]
Gregtech deleted the original recipe of Thaumium Block,but the Thaumium Block of Gregtech(made by Extruder) can't be recognized by Thaumcraft(Alchemy,or Infusion).

**Comment by Blood-Asp** [comment]
Go into GTs Unification.cfg, search for the thaumcraft area and turn blockThaumium_false=false into blockThaumium_false=true then it should turn into TCs blocks again. I will change the default for it next update.

**Comment by secirpac** [comment]
Thanks.And i think probably more materials might be unable to be accepted by other processes(of other mods) similarly.

**Comment by JasonMcRay** [comment]
Honestly mod devs should add oredict tags to their blocks and use recipes
with oreduct entries to avoid provlems like that

**Comment by PaladinOne** [comment]
@JasonMcRay This was an issue with Applied Energistics that caused a lot of complaints a year ago. AE registered Certus Quartz and Nether Quartz in the ore dictionary, but did not use the Ore Dictionary in its crafting recipes.

It was exactly as annoying as it sounds like it would be.

**Comment by leagris** [comment]
@Blood-Asp 
unification.cfg editing does not work in Gregtech 5.09.19
No entry exists for blocks unifications.
Adding an entry does not unify.

**Comment by leagris** [comment]
So, as @azanor may not fix Thaumcraft 4.2; Here is a [Thaumcraft.zs](https://raw.githubusercontent.com/Beyond-Reality/BeyondRealityModPack/e9a4b813f12ccbd20b0440ab93b26e31405f8b60/BR1710/scripts/Thaumcraft.zs) MineTweaker3 script to allow any kind of `<ore:blockThaumium>` in recipes.
