### ISSUE TITLE
Minor bug: GT bees NEI support missing

### ISSUE THREAD

**Issue by dohvakin96** [Blood-Asp/GT5-Unofficial#359]
It looks like the newest version (09.14 and 09.15) break the NEI support for the GT bees. I can´t see their recipes in NEI, however I can still obtain them through breeding. And yes, I have NEI integration for forestry installed.

**Comment by Blood-Asp** [comment]
I never did anything to add NEI support for bees. But i know that some time ago some NEI support got moved from NEI Integration to Forestry itself. So my guess is that it is more likely something on their side broke.

**Comment by dohvakin96** [comment]
OK, thank you.
