### ISSUE TITLE
Unify the size info about multiblocks in tooltips

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#360]
EBF says it is 3x3x4 (where it is 3x3 bottom and 4 high) - xzy
Charcoal Pile Igniter says its max 11x5x11 (where it is 11x11 bottom and 5 high) - xyz

Can you please unify all of these. I personaly would prefer the 3x3x4 (xzy), because most of ppl are used to reading it 3x3 at the bottom and 4 high.

Thanks.

**Comment by Blood-Asp** [comment]
As much as i hate it for beeing wrong, i guess everyone is allready used to it.
