### ISSUE TITLE
Suggestion: More ore background blocks via config

### ISSUE THREAD

**Issue by Muramasa-** [Blood-Asp/GT5-Unofficial#361]
I wasn't sure how to word that, but this effect:
![image](https://cloud.githubusercontent.com/assets/7321570/11768242/6fcd13cc-a1be-11e5-99f1-5d6a0bfe5055.png)

It would be awesome for users who use mods that add more "stone" blocks to have a config area to add more ore background blocks.

**Comment by Blood-Asp** [comment]
Nope. That needs a complete rewrite how the ores are coded internally.

GT6 added that, but that is one of the reasons why it is GT6 and no longer GT5.
