### ISSUE TITLE
End asteroids still use wrong ores (red granite)

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#363]
![photo_2015-12-13_23-24-56](https://cloud.githubusercontent.com/assets/7531754/11773571/6508aee6-a1f1-11e5-8b43-7b41921bec04.jpg)

**Comment by axlegear** [comment]
I've already verified that i'm using the latest version, and also cleared the chunk/reset the end entirely, deleted configs and regenned.

**Comment by axlegear** [comment]
Reminder

**Comment by Blood-Asp** [comment]
Deleted End and searched for new asteroids: 
![2016-03-19_00 29 18](https://cloud.githubusercontent.com/assets/8116649/13894583/d0dca6ea-ed69-11e5-9892-67f96b8948c1.png)

**Comment by axlegear** [comment]
Update:  Confirmed fixed in latest versions.  Not sure when it got fixed but has been for a while.
