### ISSUE TITLE
[Suggestion] Seismic Prospector and Small Ores

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#365]
Iit would be useful to have the Prospector to also defirence Small ores vs. Regular ores. IC2 OV scanner is already capable of it.

**Comment by Blood-Asp** [comment]
Since the last update, the Seismic Prospector fully ignores small ores. That should do the job, right?

**Comment by JasonMcRay** [comment]
Yup. Thats enough... It was bit annoying to see whole bunch of ores, and figuring out what vein it is...
