### ISSUE TITLE
GUI bug all bronze machines 

### ISSUE THREAD

**Issue by Armagedon13** [Blood-Asp/GT5-Unofficial#367]
Gregtech 5.09.16
Forge 10.13.4.1558 1.7.10
images:
http://i.imgur.com/8M3hCeA.png?1
http://i.imgur.com/iTYp79e.png?1

**Comment by Timeslice42** [comment]
You weren't supposed to notice those buttons :P

**Comment by draknyte1** [comment]
From memory, the john Smith Technicians Remix Texture pack actually added textures for them. Haven't made bronze machines in a while though.
