### ISSUE TITLE
Wrench Enhancement

### ISSUE THREAD

**Issue by Timeslice42** [Blood-Asp/GT5-Unofficial#369]
It has always bothered me that we can no longer rotate machines with the wrench as we could in previous iterations of gregtech. The solution just smacked me in the face tonight.

Can we get the wrench changed so that sneak-left click will rotate the machine according to the quadrant clicked?

**Comment by hohounk** [comment]
Huh? When/how was it changed? I can rotate stuff just fine with right clicking on the overlay-thingy - corners to put output to opposite side, edges to put it towards that edge and center to turn it towards the face clicked on. Using 5.09.15

**Comment by JasonMcRay** [comment]
Thing is you cant rotate the face. Thats what is asked here.

**Comment by Blood-Asp** [comment]
When did that change? GT4 -> GT5 or was there something like that in GT5 before i took over?

**Comment by hohounk** [comment]
Oh, now I get it. Being able to rotate the face in addition to the output would be quite nice indeed.

**Comment by Timeslice42** [comment]
It was from GT4 to GT5
