### ISSUE TITLE
Superconductor Wire recipe overwrite craft-grid

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#37]
## Nitrogen Cells in Superconductor Wire recipe are overwritten with Empty Cells upon crafting.

It cause issues when shift click to craft with stacked cells in a Steve's Workshop craft grid, where stacked Nitrogen Cells are erased by an Empty Cell.

[EDIT] Not a GT5U bug, but Steve's workshop bug

#### ~~Input:~~
* ~~2 Tiny Tungstensteel Fluid Pipe~~
* ~~2 Electric Pump (LV)~~
* ~~2000L of Nitrogen Fluid~~

#### ~~Output:~~
* ~~3 Cryo-Jacket~~

~~Combine 1 Cryo-Jacket with 1 LuV wire to create a Superconductor Wire~~

**Comment by Blood-Asp** [comment]
I do not really understand what is supposted to happen. I have Superconductor Wires in AE2 autocrafting on my server without issues.

**Comment by leagris** [comment]
Well, it is now verified this issue only manifest within a Steve's workshop craft grid.
It work perfectly fine in a vanilla Workbench.
Anyway, changing for an intermediate item and moving to an assembler look like it would be safer and appropriately balanced, given it is a very high tech miniaturized assembly.

Spwnx just whistled about adding Fluid Nitrogen coolant crafting instead of canned Nitrogen as of now. Like Nitrogen Cells would need to go into a vacuum freezer.

**Comment by Blood-Asp** [comment]
I will close this for now, but maybe get back to it once i have time.
