### ISSUE TITLE
GregTech does not actually contain Lightning Rod

### ISSUE THREAD

**Issue by PaladinOne** [Blood-Asp/GT5-Unofficial#373]
GregTech was created over three years ago as a Lightning Rod mod. WHERE IS THE LIGHTNING ROD?

**Comment by Timeslice42** [comment]
The bane of Alblaca is no more!

**Comment by Blood-Asp** [comment]
Soo damn long. But finally we have the Lightning rod again! :D

**Comment by PaladinOne** [comment]
**PRAISE THE BLOOD!**
