### ISSUE TITLE
[Suggestion] Reducing the output for small boilers and allowing distilled water in boilers instead of the nerf set in current version

### ISSUE THREAD

**Issue by Invincible92** [Blood-Asp/GT5-Unofficial#374]
Personally, I don't think the answer should be forbidding the automated refueling of the small coal boilers in order to stop its spamming. From my point of view, the answer should be adding a diminishing return in the steam production until a fixed value, like diminish the steam production from 100% to 25%, the same as you added to the solar steam boilers. I mean, add a 'calcification' alike penalty from using normal water in that kind of boilers (solar and the small ones) and allowing the use of distilled water in order to bypass that penalty. It would also require a more 'complex way' of making distilled water than the current one, like returning less distilled water from normal water in the distillation tower or the equivalent machinery, like a 25% of loss, or something like that. With that, people ought to use normal water with the penalty in mind until they have the infrastructure in order to bypass that. At that time of the game, people would be clever enough (or at least I think) to use petroil, the big steam boilers or equivalent methods for energy production instead of just spam everywhere that small boilers. 

Or even you can reduce it's permanent output to 75L instead of 150L. In  /main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler_Bronze.java you could substitute at lines 82 to 102 where it puts 150L per 75L (for example):

           if (aTick % 25L == 0L) {
                if (this.mTemperature > 100) {
                    if ((this.mFluid == null) || (!GT_ModHandler.isWater(this.mFluid)) || (this.mFluid.amount <= 0)) {
                        this.mHadNoWater = true;
                    } else {
                        if (this.mHadNoWater) {
                            aBaseMetaTileEntity.doExplosion(2048L);
                            return;
                        }
                        this.mFluid.amount -= 1;
                        if (this.mSteam == null) {
                            this.mSteam = GT_ModHandler.getSteam(75L);
                        } else if (GT_ModHandler.isSteam(this.mSteam)) {
                            this.mSteam.amount += 75;
                        } else {
                            this.mSteam = GT_ModHandler.getSteam(75L);
                        }
                    }
                } else {
                    this.mHadNoWater = false;
                }

Or instead of putting what I've said above, put all of this nerf you've created in the config, so players could choose between using the nerf to solar and the automation nerf to small coal boilers or not.

**Comment by axlegear** [comment]
I'd also propose that if we're going to have calcification, you should have a way to scrape said mineral deposits out and process them somehow.

**Comment by Blood-Asp** [comment]
The coal boilers will stay as they are now. The intention is as allready said to reduce spamming low tech stuff. Reducing output will for many just mean to build more of them to compensate.
Saying that solar boilers calcinate is only a excuse to force interaction every few hours. Might even lower putput of them to 0 once i added it to the gui and make it possible to fix without picking up.

The only way to stop spamming machines is to increase the work for the owner, not reducing the output if they can be fully automated. That would make starting with your first steam machines extremely hard while these anti automation nerfs will not even be noticed early on.
