### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by Eterias** [Blood-Asp/GT5-Unofficial#375]
Crash at installing. I give in folder ,,mods". Start Minecraft - Crash! Version 1.7.10. Help me please :)
GregTech 1.7.10 5.0.9.16.

**Comment by Eterias** [comment]
GregTech.

**Comment by Blood-Asp** [comment]
No crash report.
No list of other mods installed.
No forge version.

So no way i can help with that...
Something like this would also be best in the forum thread.
http://forum.industrial-craft.net/index.php?page=Thread&threadID=11488

The three most typical reasons for crashs are: 
Old Forestry version(4.2 needed)
Netherores mod (disable IC2 compat in their config)
Dense Ores mod (remove, not compatible or needed with GT)
