### ISSUE TITLE
An asteroid overlaps another,using wrong kind of ores 

### ISSUE THREAD

**Issue by secirpac** [Blood-Asp/GT5-Unofficial#378]
using version 5.09.09,maybe it's a rare situation

![2015-12-26_13 07 42](https://cloud.githubusercontent.com/assets/16161401/12005255/a5b37898-abd5-11e5-983e-13f4235266e0.png)
BTW,wish you a Merry Christmas

**Comment by Blood-Asp** [comment]
Not much i can do here. simply two granite blobs spawning close to each other but not at the same time.

Also a Merry Christmas
