### ISSUE TITLE
Server-Crashing bug with Item Pipes

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#379]
Sometimes adding/removing item pipes will cause the server to crash.

[crash-2015-12-26_03.24.05-server.txt](https://github.com/Blood-Asp/GT5-Unofficial/files/72409/crash-2015-12-26_03.24.05-server.txt)

**Comment by Blood-Asp** [comment]
It is not the pipe itself doing that. Likely some mod checking the block change event handler or some other interaction. The crash report file is also not much helping.

**Comment by axlegear** [comment]
Not sure what it could be.  Only GT machines connected to the pipe and only GT pipes used.
