### ISSUE TITLE
How often Adv.miner 2 produces byproducts?

### ISSUE THREAD

**Issue by ShelfOwl** [Blood-Asp/GT5-Unofficial#381]
The Adv.miner 2 produces byproducts each time it seems. Is it intended?
edit: happen In GT 5.09.16

**Comment by Blood-Asp** [comment]
Yes, intended.
The miner gives overall huge bonus. So the 100% chance is intended. The primary output has a 1-5x random multiplier, so one ore is not 2 crushed and 0.1 byproduct, but in average 6 crushed and 1 byproduct.

**Comment by ShelfOwl** [comment]
Hmm I see. But I saw Adv.miner 2 produces 2-8 crushed and 1-4 byproducts, not 5x...
Thanks reply.
