### ISSUE TITLE
AE Quartz oredict trouble

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#382]
Pure Nether and Pure Certus Quartz are registered under wrong oredictionaries

Nether Quartz - craftingQuartz, **itemNetherQuartz**
Pure Nether Quartz - craftingQuartz, **itemCertusQuartz**

Certus Quartz - craftingQuartz, **itemCertusQuartz**
Pure Certus Quartz - craftingQuartz, **itemNetherQuartz**

**Comment by Blood-Asp** [comment]
fixed: https://github.com/Blood-Asp/GT5-Unofficial/commit/efbf251938c344dc7c73c5042c9ed04edc06b938
