### ISSUE TITLE
Spatial IO compatibility

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#384]
When transporting GT blocks via AE2 Spatial IO, they come on the other side as untextured ".name" blocks. Is there anything to do about it? Either fix, or blacklist them.

**Comment by Blood-Asp** [comment]
Added to idea collection

**Comment by Nex4rius** [comment]
You shouldn't have to blacklist them but instead gregtech just has to stop adding them to the whitelist.
><a href="http://ae-mod.info/Spatial-IO-Port/">* Note Spatial uses a white list compatibilty system, only tile entities marked as "whitelisted" can be moved with this system, other mod authors can opt-into this, AE2 provides support for itself, and Vanilla.</a>
