### ISSUE TITLE
MOX cells no longer affected by temperature

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#385]
MOX cells' output is no longer affected by heat, since their output was changed.  It puts out 2x as much as it did with 0% heat, but even at 69% heat there is no change.
Enriched Uranium Cells are unaffected-  no boost.
Thorium seems to work fine, and is now 2x the previous output.

Since MOX is unaffected by heat now, they are effectively useless as they generates less plutonium per uranium-238 consumed, and output the same total energy as enriched uranium.

**Comment by Dream-Master** [comment]
I send Blood Asp already a pm and wait what he have to say about it.

**Comment by Blood-Asp** [comment]
As i wrote in the forum. Will take a look at it.

**Comment by Dream-Master** [comment]
:+1:

**Comment by Blood-Asp** [comment]
And fixed. stupid internal conversion...
https://github.com/Blood-Asp/GT5-Unofficial/commit/9362235140add1620d9076e6221ecc1242035548
