### ISSUE TITLE
Master Magic Energy Converter (HV) needs Europium=Fusion1

### ISSUE THREAD

**Issue by ghoulsblade** [Blood-Asp/GT5-Unofficial#386]
just a suggestion, Master Magic Energy Converter (HV) needs Europium to craft.
Europium needs Fusion Mark1, which can produce IV, 2 tiers above HV.
So by the time you can craft the HV converter, you dont need it any more.
Maybe sth else thats high tier but before Fusion, e.g. lutetium (from depleted thorium rods), tungstensteel, that eldritch eye or boss drop primorial pearl, ultimet (ebf2 + vacfreezer), enderium/naquadria/enr.naq/naq.alloy/fluxed electrum/ (ebf3+vfreezer), plutonium 241 isotope (hv centri, small chance), superconductor wire, 1 fusion coil (rather than whole reactor), or lapo orb which needs EV assembler.
Was redirected here from infitec2 modpack :) https://github.com/JasonMcRay/InfiTech-1.7/issues/459

**Comment by Blood-Asp** [comment]
That is quite difficult to balance. I want the magic gens to be worse than the normal GT alternatives, but still good enough to be used. Well, i will take another look at the recipes i guess.

**Comment by axlegear** [comment]
Personally?  I think it's good.  Magic is way easy to farm, I have a netherstar farm that took a couple weeks to set up but once I did it just pews stars.  (Of course it all died due to a dumbness, but I digress..)  Using only 128v nerfs it a bit, though I just get around that by spamming them in.

**Comment by ghoulsblade** [comment]
yeah the LV and MV ones are ok, but the HV=512eu/t one is pointless if you need a fusion to craft it, when fusion mark1 can get you around 25.000-30.000 eu/t easily. more with large plasma gens.
