### ISSUE TITLE
Crops still only 10% per 16 in autoclave, while combs recently changed to 100% per 16

### ISSUE THREAD

**Issue by adudney** [Blood-Asp/GT5-Unofficial#388]
https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java#L1664

Compared to

https://github.com/Blood-Asp/GT5-Unofficial/blob/a9aac6ff58cb7321528e67f6179667ae72a437c9/src/main/java/gregtech/common/items/ItemComb.java#L274

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/b167f735880fdadaca4665824fd27dc8c42f49b7
fixed
