### ISSUE TITLE
MOX cells cause server crash when depleting.

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#389]
Fun, fun!

[crash-2015-12-28_20.17.25-server.txt](https://github.com/Blood-Asp/GT5-Unofficial/files/73689/crash-2015-12-28_20.17.25-server.txt)

The server will not restart after this, always crashing with the same error.  I had to reload to a previous state.

**Comment by Blood-Asp** [comment]
Sometimes it is just details: renamed reactorDepletedMox -> reactorDepletedMOX
https://github.com/Blood-Asp/GT5-Unofficial/commit/87e9feebc345571acea71aa82d42b46f6af82ad1

**Comment by axlegear** [comment]
LOL, that really caused such a crash?
