### ISSUE TITLE
Recipe Removal

### ISSUE THREAD

**Issue by Gameonlp** [Blood-Asp/GT5-Unofficial#39]
I would really enjoy if you added the possibility to remove recipes (via Minetweaker would be great). I am working on mods an tweaking many recipes, so that it gets annoying too not have the possibility of creating a shared Tech Tree.

**Comment by Dream-Master** [comment]
Use GTTweaker together with Minetweaker. All Machines supported all ready.

Git Wiki:
https://github.com/Dream-Master/Minetweaker-Gregtech-5-Addon/wiki
Download 
http://forum.industrial-craft.net/index.php?page=Thread&threadID=11353

**Comment by Gameonlp** [comment]
still missing the possibility of removing recipes... gregtech can be too easy at some points

**Comment by Blood-Asp** [comment]
Look into the Recipes.cfg. There you can disable/change all recipes of GT. No need for minetweaker.

**Comment by Gameonlp** [comment]
thanks for the information, sry for the derps
