### ISSUE TITLE
Charcoal Pile Igniter

### ISSUE THREAD

**Issue by Ldmf** [Blood-Asp/GT5-Unofficial#392]
Charcoal Pile Igniter dosent work with Twilight Oak Wood 3x3x3 nothing hapens

**Comment by Blood-Asp** [comment]
does the wood have an "woodLog" oredict tag?

**Comment by Ldmf** [comment]
![2015-12-29_15 43 20](https://cloud.githubusercontent.com/assets/15316448/12036071/f81ab744-ae42-11e5-8063-a50d100baeed.png)

the same as normal oak wood

**Comment by Blood-Asp** [comment]
Just tested it. works fine for me. So maybe it was not set up correctly? Or you used an old version of GT?
