### ISSUE TITLE
Carbon Dioxide and Argon has no use

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#393]
It cannot be emptied and has no use.  Carbon Dioxide is produced when centrifuging 53 liquid air cells.

Ditto for Argon.

**Comment by Blood-Asp** [comment]
For now CarbonDioxide can be electrolyzed into carbon and oxygen.

Any ideas what it can be used for? Argon is used in metal processing to keep oxygen away while it is hot, but no idea were i could put that into a good recipe that fits.

**Comment by axlegear** [comment]
Well, CO2 has a ton of industrial uses.  Argon... not so much.  It replaced nitrogen when nitrogen is not inert enough, so possibly pyrolyse oven stuff?
 Mostly argon is just for lighting and neutrino or dark matter experiments.

As long as it can be extracted in fluid form (perhaps to can or store in a tank, mostly for decorative purposes) then i'm satisfied, and it can sit around until a viable use pops up from someone smarter than me.

**Comment by wormzjl** [comment]
The main industrial is the production of urea
Also it can be used to make methane, methanol, formic acid, by a photocatalytic process
more: making organic/inoreganic carbonates, feed microalgue clutivations, solvents under supercritical state, etc

**Comment by wormzjl** [comment]
Argon is mainly inert, perhaps in the production of some hightech alloys and circuits?

**Comment by axlegear** [comment]
Add cerium to the list of useless materials, too.

**Comment by wormzjl** [comment]
Used in the catalyst for oil cracking, can be integrated in the oil processing chains IMO

**Comment by axlegear** [comment]
Agreed.  Perhaps it can be fed into the oil cracking unit to increase yield, and/or reduce time and power consumption.  (Palladium is also used for oil cracking, as is lutetium)

**Comment by wormzjl** [comment]
Made a new issue for that https://github.com/Blood-Asp/GT5-Unofficial/issues/424

**Comment by yznpku** [comment]
You can now create carbon dust out of nothing.
We generally call it OP instead useless, considering that you need to mine for carbon intentionally prior to this patch.

**Comment by leagris** [comment]
Add: Cerium, Caesium, Lanthanum, …
