### ISSUE TITLE
Advanced Miner II causes extreme TPS lag

### ISSUE THREAD

**Issue by PaulMadsen** [Blood-Asp/GT5-Unofficial#397]
This occurs when its input hatch has between 1 and 99 drilling fluid in it, inclusive. Once the chunk it resides in is unloaded the dimension it is located in experiences extreme TPS lag. /cofh tps shows .5 TPS. 
Also, when the chunk loaded the drill will continue to operate despite not having enough drilling fluid to complete an operation.

**Comment by Blood-Asp** [comment]
Does this happen with GT 5.09.18 or an older version?
Because it should be fixed in the latest version: https://github.com/Blood-Asp/GT5-Unofficial/commit/2baf34b03a4040a5aa12b791b569395fa612df58

**Comment by PaulMadsen** [comment]
Sorry for delayed response.  I am running GT 5.09.12

**Comment by Blood-Asp** [comment]
"should" be fixed in the latest version, so please update and reply again. otherwise i will simply close this soon.
