### ISSUE TITLE
Possible bug: Autoclave top texture

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#399]
![2015-12-31_07 32 27](https://cloud.githubusercontent.com/assets/8942955/12065743/846ebb74-af91-11e5-9951-435889ab00b5.png)
Using default GregTech textures, the Autoclave's top texture looks like it would make more sense as the front texture (since most other top textures are rotationally symmetric, and the red/green lights to indicate whether a machine is active are normally on the front).  Is it really supposed to be the top texture?

**Comment by Blood-Asp** [comment]
No, that is correct. There are a few other machines like that.
