### ISSUE TITLE
[Suggestion] "Satellite Island" in The End?

### ISSUE THREAD

**Issue by 3TUSK** [Blood-Asp/GT5-Unofficial#4]
Just curious about the possibility. It may be an awesome feature, while it may break the balance.
Thanks for your time.

**Comment by Blood-Asp** [comment]
I'm currently only porting GT4 stuff to GT5 and doing bugfixes. There will be no completely new stuff for GT5 from me.
But what exactly do you mean with "Satellite Island"? If it's an interesting idea, it might be good for GTExtras.

**Comment by 3TUSK** [comment]
Seems like I forget the correct name of this feature.
So, the "satellite island" refers to the small island stuff around the main island in The End in GT4, which means you can explorer farther to find more ores, like tungsten, olivine, platinum. 
Some people just complain about the rarity of naquadah... so basically the "satellite island" means the infinity generation of The End.
Sorry for ambiguous description.

**Comment by Blood-Asp** [comment]
GalacticGreg allready adds something like that. Rare small meteorites floating in the end. But it needs also Galacticraft to be installed.

**Comment by 3TUSK** [comment]
All right... forgot GC...
