### ISSUE TITLE
Missing parentheses in chemical formula for diatomite

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#401]
Chemical formula is listed as "SiO28Fe2O3Al2O3", implying that it is only one part silicon, but it centrifuges to 8 flint dust, 1 banded iron, and 1 sapphire, so the formula should really be "(SiO2)8Fe2O3Al2O3"

**Comment by Blood-Asp** [comment]
Looked at it. Fixing that is not worth the work.
