### ISSUE TITLE
Strange behaviors with leaves

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#402]
Vanilla leaves (oak, spruce, etc.): can be sheared with a GT chainsaw, or cut for 100% drop rate of saplings/fruit with a GT branch cutter.

Forestry leaves: can be cut for 100% drop rate of saplings with a GT branch cutter, but shearing them with a GT chainsaw gives "for.leaves.corrupted Leaves" with a black texture, which are usable in ore-dictionaried recipes (such as macerating them for bio chaff), but placing one of these caused an NPE.  Shearing them with an IC2 chainsaw preserves the type (and presumably genetic information).

IC2 Rubber leaves: hitting them with either a GT chainsaw or a GT branch cutter has no special effect; the drops seem to be the same as breaking the leaves with bare hands.

Biomes O' Plenty and Thaumcraft leaves: I haven't tried a GT chainsaw on them, but the GT branch cutter showed no apparent increase in drop rate compared to breaking the leaves with bare hands (it seems reasonable to keep this behavior intentionally for silverwood leaves, not so much for greatwood leaves, and not at all for BoP leaves)

**Comment by Blood-Asp** [comment]
The corrupted leaves are fixed.

The sapling drops from modtrees need special support for every type of tree and i will not do that.

**Comment by MauveCloud** [comment]
Forestry corrupted leaves fix confirmed, and I won't press the BoP/Thaumcraft saplings, but is there a justification for the branch cutter not affecting the sapling drops from IC2 rubber trees?
