### ISSUE TITLE
Typo: Hydric sulfide and sodium sulfide incorrect formula

### ISSUE THREAD

**Issue by Invincible92** [Blood-Asp/GT5-Unofficial#403]
H2S should be hydrogen sulfide, the IUPAC recommended name, not hydric sulfide which doesn't exist.

Also, sodium sulfide is Na2S (sulfur is divalent, as oxygen), not NaS.

**Comment by Invincible92** [comment]
Another typo I found: The pyrolyse oven should be pyrolyzer oven

**Comment by JasonMcRay** [comment]
Actually... Pyrolyse is correct. In german. Blood-Asp is german (if I am not mistaken). Correct translation of pyrolyse is Pyrolisis. So Pyrolysis Oven.

**Comment by MauveCloud** [comment]
According to some online dictionaries at least, "pyrolyse" is a valid spelling of the verb form in English (see http://www.thefreedictionary.com/pyrolyse), though possibly British spelling (U.S. spelling would more likely use "pyrolyze"), and the noun form "pyrolysis" might make more sense.
