### ISSUE TITLE
Fuel cells still not getting boosted

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#404]
Thorium boost works fine, but the Uranium and MOX are still defaulting.  5 EU/t and heat for a cell in EU reactor.  GTU 5.09.19

**Comment by Blood-Asp** [comment]
Make fresh cells. Uranium/Mox crafted before the change does not change on it's own.

**Comment by axlegear** [comment]
K, testing.  Will take a bit, as I only had Bear test them in creative mode after the update, and it took 14 hours because we wanted to make sure the depletion crash was truly gone.  XD

**Comment by axlegear** [comment]
Uranium tested, works.
Thorium tested, works
MOX testing will take a while... c.c  No pu on hand.
