### ISSUE TITLE
palladium dusts cant be used in a fluid extractor

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#405]
you have to do full ingots rather than tiny or small dusts

**Comment by axlegear** [comment]
I am fairly sure that's intentional

**Comment by JasonMcRay** [comment]
A lot of dusts, tiny and small can be fluid extracted.

**Comment by Blood-Asp** [comment]
It is intentional. Palladium needs the blast furnace and freezer for processing. Allowing the fluid extractor to work on them would be a way around that.
