### ISSUE TITLE
Solar Boilers cause FPS lag

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#406]
TPS is perfectly A-OK but for some odd reason they seem to degrade client-side FPS a lot.  1-2 isn't noticeable but with 22 like I have, it makes people crawl.  Removing them brings FPS from 5-10 to 60+

**Comment by Blood-Asp** [comment]
I heard similliar things about other GT machines but never could reproduce it. Even 100 solars are still 60+ fps for me (and others on the same server). Maybe an issue with optifine, some resource pack or any other mod?

**Comment by axlegear** [comment]
Not using Optifine or any resource pack.  Adding optifine makes it much less severe.

Not sure what other mod would cause a GT machine to cause FPS render lag.  Ideas/suggestions?

**Comment by Timeslice42** [comment]
I hear people say this about GT distilleries as well. Maybe try reproducing it with IT2 in a non-dev environment? If you can't repro like that, you're very unlikely to repro in a clean dev environment.

**Comment by Blood-Asp** [comment]
Having hundreds of solars or a few destilleries next to me without fps lag was on the kirara server, so in a real enviroment.
What piping are you using? These machines produce fluid output only every 10 to 16 ticks. Maybe it is rapid rendering changes on the pipes?

**Comment by Timeslice42** [comment]
Is it Opis that has the rendering profiler? It would be handy to see what it thinks is taking up the most time.

**Comment by axlegear** [comment]
Using GT pipes, Huge Steel for steam (overkill!) and small stainless steel for water.  Opis was not installed.  The only 'rendering profiler' was from the default MC tools.  Fully recreateable in SP.

As mentioned, the problem is FPS, not TPS.  IE, render lag.

**Comment by Timeslice42** [comment]
Yeah, drop in Opis and run the profiler. It has both a TPS profiler and a rendering profiler (which is the one you want). See if you can find anything interesting. Don't leave it installed for normal play though, it causes issues of its own these days.

**Comment by axlegear** [comment]
Nothing significant shows in the rendering profiler.  It suggests there should be no lag, despite the fact the FPS is crawling.  Removing the boilers fixes it though, as usual.

However it seems Blood is not interested in looking into the issue.

**Comment by axlegear** [comment]
![image](https://cloud.githubusercontent.com/assets/7531754/12177850/f1ca98e4-b533-11e5-92a8-e88315da8d80.png)

**Comment by axlegear** [comment]
As you can see, nothing shows any significant render time at all.  Certainly not enough to explain >10 FPS.

**Comment by Blood-Asp** [comment]
Not interested in looking into it? That sounds a bit offensive to me and i normaly do not care much about something like that.

I did hours of testing with that and related issues, but found no way to replacate it. Without any idea what is causing it, there is absolutely not way for me to fix it.

I need a sure way to replicate the issue to find a fix. As long there is nothing like that, all i can do is to observe.

**Comment by axlegear** [comment]
If you like, I can try to send you our modpack.

**Comment by Blood-Asp** [comment]
Well, other things you could test first: Does it happen to you with only GT (+IC2) installed? In that case it would be the graphics driver. 
Also you might test a few different forge versions. Most recent and oldest working with GT for example. That should be 1355.
Also different graphic settings might help. Stuff like disable advanced GL or fast shadows in the config. Just testing all if it maybe changes something.

**Comment by axlegear** [comment]
1)  Yes, it does occur with GT+IC2 only.
1.5)  Latest graphics driver available.  Little has changed for a long time, and neither driver nor card changed at the time the problem began, which is shortly after the solar boiler nerf.
2)  Will try a few and report back.
3)  I've tried every combination possible without optifine, no help.  Optifine helps by being installed but no settings seems to make any significant difference.  FPS is 1-2 without and 5-10 with Optifine.  In both cases, removing my solar boiler array (20-24) fixes FPS within a few moments.  Using stainless steel tiny pipes for water and huge steel for steam.  Feeds directly into an HV turbine.

**Comment by axlegear** [comment]
I tested a few major versions first:
Occurs in 1558
Occurs in 1540
Occurs in 1492
Does not occur in 1448

Want me to keep checking the ones between 1492 and 1448?

**Comment by Timeslice42** [comment]
So it's a forge issue?

**Comment by axlegear** [comment]
Looks like it may be, though I need Bloody to take a look and make sure it's specifically Forge and not a malformed implementation or something else, or a change in forge's API or something I don't know about.

Also I tested and it seems the problem began specifically with 1492.

**Comment by axlegear** [comment]
Gonna assume that means it's indeed Forge issue only.  XD

**Comment by Blood-Asp** [comment]
I could not replicate it whatever way i tested. Might also possibly a graphics driver issue or something.
