### ISSUE TITLE
Suggestion: Hard / Soft Hammer icon change

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#407]
Right now the icons for both the soft and the hard hammer look exactly the same and the only way to see the difference is by hovering your mouse over them.
<a href="http://imgur.com/qOCNXxb"><img src="http://i.imgur.com/qOCNXxb.png" title="source: imgur.com" /></a>

I think simply rotating the soft hammer icon by 90° would be enough to end all confusion. :)

**Comment by Timeslice42** [comment]
Although renaming it to a mallet and changing the graphic accordingly would be a nice long term goal...

**Comment by draknyte1** [comment]
Closed now ;)

**Comment by Blood-Asp** [comment]
Right...
