### ISSUE TITLE
Request: multiblock diesel generator

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#409]
GT5u added multiblock generators (turbines) for steam, gas, and even plasma, but there's no good multiblock option for diesel, ethanol, nitro-diesel, etc.  Technically they can be used in large boilers for steam, but the tooltips for those include the line "Refined liquid fuels have 1/4 efficiency"

**Comment by Blood-Asp** [comment]
Meh...

**Comment by mura3277** [comment]
Damn I was really hoping this was going to be added. There is definitely a use case for this if you change your mind.
