### ISSUE TITLE
Missing Unification Options

### ISSUE THREAD

**Issue by hephinator** [Blood-Asp/GT5-Unofficial#41]
AE2: Stable, rv2, Build #5
GT: 5.08.19 (same with all 5.08.X and 5.07.X)

AE2 unification is missing gemCertusQuartz in Unifcation.cfg (unifies to GT's darkish version)
dustCertusQuartz is present and works fine (unifies to AE2)

orecamouflage {
    B:CertusQuartzCrystal=false
    B:CertusQuartzDust=false

As you can see, AE2 is set properly to allow other mods to manage certus unification.

(if I recall, this issue cropped up in GT 5.07.00, 5.06.06 worked fine.)

**Comment by Blood-Asp** [comment]
should be fixed in 5.08.21
