### ISSUE TITLE
(Hand) Scanner bug/enhancement

### ISSUE THREAD

**Issue by Timeslice42** [Blood-Asp/GT5-Unofficial#411]
While the Progress indicator works correctly on GT fluid pipes, it doesn't work correctly on item pipes. The max progress is correct, but it always shows the current value at zero, even when there are items stuck in the pipe.

**Comment by Blood-Asp** [comment]
There is nothing i can change on that point. At last not without beeing hacky.

**Comment by Timeslice42** [comment]
Bummer. Is there any way for the scanner to know when a pipe is stuck?
