### ISSUE TITLE
Gregtech Sensor Kit/Card Enhancement

### ISSUE THREAD

**Issue by Timeslice42** [Blood-Asp/GT5-Unofficial#412]
First, could you label the display values? When you put the card in a display it asks you which values you want to display, but unlike other cards the GT card is just numbered.

Second, and this one may not be possible, for large turbines can you display the current and optimal flow rate, and current EU/t?

**Comment by Blood-Asp** [comment]
A display for the turbine sounds like a good idea. Will take a look at the possiblity. Not sure about labling the values. Might be easy, might be impossible. No idea.

**Comment by leagris** [comment]
I'd like sensors working with Generators, single or multiblock.
Example Naquadah reactors.

**Comment by Timeslice42** [comment]
Doesn't the generator nuclear control sensor kit work for GT generators?

**Comment by leagris** [comment]
It does not work as of 5.09.19

**Comment by Timeslice42** [comment]
Do you remember it ever working in GT5? I might be remembering GT4 interaction.

**Comment by leagris** [comment]
Never worked in GT5 since it diverged EU Net from the one from IC2.

**Comment by Blood-Asp** [comment]
I wonder what it should show? Working and stored fuel? Should be possible to monitor with covers only. Since they always output their full voltage, there is not much more to monitor.

**Comment by leagris** [comment]
While generators output at their Tier level, they only output on-demand. So it virtually has a given output rate you could compute like:
Number of packets last second / 20 \* 2 ^ (4 \* Tier) = Average EU/t for 1s

Fuel units and internal buffer would be good as well (any data a Gregtech scanner can have)

The Gregtech sensor kit/card should pull very same data a Scanner can pull.

Adding average EU Packets Item input, Fluid Input for 1 second to Scanner/sensor data would be good also.

**Comment by Blood-Asp** [comment]
The only way i currently can think of for monitor the average EU/t would be quite laggy. Each machine would need additional integer arrays, and few calculation steps more whatever they are monitored or not. So that is a bad idea to do... Generally everything that calculates averages over time is stuff that shoud be avoided.

**Comment by leagris** [comment]
Well if sensor can get current EU as when looking at interface this is good enough.
I used to poll these kind of counters and compute average using it in LUA with OpenComputers.
