### ISSUE TITLE
implosion compressor recipes with new explosives 

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#413]
dynamite only stacks to 16 so the implosion compressor isn't working with 32 and iridium alloy.

**Comment by axlegear** [comment]
Tested and confirmed broken.

**Comment by xarses** [comment]
Not sure if it's relevant here, but the iTNT is more effective than TNT (by 2x on diamond dust and iridium plate recipes). If this is expected then great

**Comment by axlegear** [comment]
Almost positive it's intended since iTNT is harder than TNT is harder than powder kegs to make.  More effort = more reward.  That's the GT way!
