### ISSUE TITLE
Mox Fuel Rod did not produce bonus heat in fluid reactor

### ISSUE THREAD

**Issue by ShelfOwl** [Blood-Asp/GT5-Unofficial#416]
IC2 MOX Fuel Rod generates double heat in fluid reactor with 5000+ temperature, 
but in GT 5.09.19, new GT Mox Fuel Rod did not.

**Comment by Blood-Asp** [comment]
Shoud be the same issue as with mox in electric reactor. Incorrect float/integer conversion...
Will fix it once i have a working eclipse.

**Comment by axlegear** [comment]
Eclipse?

**Comment by Blood-Asp** [comment]
The programming enviroment i code GT in.
I upgraded my PC this weekend and installed a new windows. Now i need to reinstall all programms step by step.

**Comment by axlegear** [comment]
Thanks!
