### ISSUE TITLE
Multi-blocks output items into fluid output (cell-out) slots when output-buffer is full

### ISSUE THREAD

**Issue by xarses** [Blood-Asp/GT5-Unofficial#417]
Seen with both pyrose ovens, and distillation towers, if the output-buffer becomes full, the items are placed into the fluid output (cell-out) slots of the fluid output hatches. Other than being annoying, it doesn't impact the usage of the hatch with pipes

**Comment by MauveCloud** [comment]
http://ftb.gamepedia.com/Output_Hatch indicates that's intended behavior.

**Comment by xarses** [comment]
filled cells, yes. However I'm talking about the pyrose oven emitting charcoal in the slot, or the distillation tower outputting tiny piles of hydrated coal dust

**Comment by MauveCloud** [comment]
I was considering this line from the Wiki:
> The Output Hatch is a Block where GregTech 4 Multiblocks output Items and Fluids.
I interpret that to mean that the output hatch is not limited to filled cells.  If that isn't allowed, that means one less slot for potential items, and the multiblock will start voiding items sooner.  Do you really want that?

**Comment by Blood-Asp** [comment]
intended design. better have the items go into the hatch slots than getting destroyed.
