### ISSUE TITLE
Microwave Transmitter doesn't seem to work

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#418]
Trying to use an HV microwave transmitter to a nearby LV machine, nothing seems to happen.  I tried transmitting to a cable, then to a batbuf, then to an HV machine.  Nothing doing.  I'm positive the coords are right, and I put a lever on to turn it on... just get nothing.

**Comment by Blood-Asp** [comment]
did you supply the transmitter with enough power? 2-3Amp are needed  depending on the distance. Also, supplying HV to an LV machine results into a big boom. Cables have no energy buffer, so they do not work for sure.
Coordinates + RS signal on buffer and it should work. At last it does in my testworld.

**Comment by axlegear** [comment]
It was being supplied up to 24 amps (lol) and transmitting to an LV machine directly next to it.  I tried all possible +/-1 offsets and just.. nothing.  It's definitely switched on but nothing.  No explosion, no power, nothing.

Also, shame to know it can only power HV machines and up.  :(  Kind to makes it useless for me now.

**Comment by OvermindDL1** [comment]
Cannot transform the receiver down using a transformer?

**Comment by axlegear** [comment]
Can't do anything.  There's zero evidence that the microwave transmitter does anything, and i've tried everything.  I tried an HV machine with HV transmitter, same thing.  Tried transmitter to transmitter, nadda.  Tried batbox, tried transformer, tried RF device even.  I got nothing.

**Comment by Blood-Asp** [comment]
This does work for sure:
http://i.imgur.com/MC0yt9V.png
4x HV Battery Buffer -> HV Microwave Transmitter -> HV Electric Furnace.
