### ISSUE TITLE
Infinite worldgen loop

### ISSUE THREAD

**Issue by Methes** [Blood-Asp/GT5-Unofficial#42]
Just a reminder that the problem exists. I guess it's pretty difficult thing to fix with GT6 being different so it's just a reminder.

**Comment by Blood-Asp** [comment]
I must go through it anyways to fix galactic greg. once i get it to work, i will try to also fix it on GT5U

**Comment by Andrey96** [comment]
Problem is it's completely unreal to play with this bug. Once generation is started (after around 5-10 seconds), it hangs server threads and that's it. Restart (that tooks damn 5 minutes) is only option. So, this fork is useless until it will be fixed.

**Comment by Blood-Asp** [comment]
That only happens in combination with some other worldgen changeing mods. In most cases GT worldgen is just fine.

**Comment by pyure** [comment]
What exactly is the issue?  I'm asking more so I can avoid it.  I've been playing 5U for months haven't encountered a problem yet.

**Comment by Andrey96** [comment]
There is no crashes, so it's kind of hard to find the loop. On new not generated map when you start generating it, after 5-10 seconds TPS lowers and then all players are kicked with "timed out" error and never able to login back until restart (cause server threads except network threads are in loop or under very high load). Once it was not the complete loop, but tps 0.4

**Comment by Blood-Asp** [comment]
I tried to copy the changes Greg did in GT6 into GT5.
https://www.dropbox.com/s/z5tprbw1xgv0adj/gregtech_1.7.10-5.08.21-test1.jar?dl=0
This might help, but who knows...

**Comment by Andrey96** [comment]
I tried to copy for loop in Worldgenerator and it didn't help. I'll try your changes, hope it will.

**Comment by Blood-Asp** [comment]
Still seems not to be fixed but i'm out of ideas...
