### ISSUE TITLE
request: Add fluid filter or fix order of distillation tower outputs

### ISSUE THREAD

**Issue by xarses** [Blood-Asp/GT5-Unofficial#421]
The distillation tower outputs nearly the same for Light and Heavy cracked fuels, however it results in two of the outputs being flipped. This makes reusing the same tower for both fuels quite difficult. 

On the more useful overall side it would be fantastic to get a machine that can filter fluids similar to a type filter.

On the other hand addressing the output order of the Heavy and Light cracked fuels will solve my most complicated automation problem I have at the moment
(from bottom to top)
Heavy Fuel emits:
0: tiny hydrated coal dust
1: Refinery Gas
2: Naphtha
3: Light Fuel
4: Toluene
5: lubricant

Light fuel emits:
0: None
1: Refinery Gas
2: Naphtha
3: Toluene
4: Heavy Fuel
5: None

The problem I can't solve easily at this time, is that outputs 3 and 4 are reversed between the two recipes, which is going to take some complicated logic to reuse the tower.

**Comment by Timeslice42** [comment]
While I think this is definitely a valid request, why not just use the fluid distributor?

**Comment by xarses** [comment]
I checked that and the fluid regulator, and as far as I can tell, I can't control which fluids are allowed through, so it doesn't work as a fluid filter

**Comment by Timeslice42** [comment]
The fluid distributor will only output to a side that will accept it. If you put tanks on each side that already contain the fluid in question then you can filter that way.

**Comment by leagris** [comment]
Any pipe will only output to a side that will accept fluid :)

**Comment by xarses** [comment]
yes, but unless I'm missing something nothing will let you 'pin' a fluid to the tank, this assumes that this is the final location for the fluid, and that you have somehow prevented it from reaching 0 or won't re-open to accept any fluid. This isn't relastic at the final location, let alone in a distribution network.

**Comment by leagris** [comment]
You can combine a fluid level emitter, a shutter and a machine controller covers, so your machine block will emit a redstone level suitable to shut down fluid transport before becoming empty, so acting as a fluid selector.
Basically lay down x blocks of redstone from the fluid level emitter cover to an inverter redstone torch, so as when the redstone signal reach a given low the redstone torch will shut down before your machine block internal tank reach less or equals to next fluid transmission. Then run your redstone torch signal back to the machine controller cover side to control fluid flow.
Hopefully this will take less than 20 blocks space within same chunk, and if you are lucky fluid level to redstone level will match a fluid transmit unit and the signal propagation lag will be precise enough to preserve fluid inside machine tank as a filter.
I understand it is a convoluted solution depending on unreliable redstone signal, subject to tick hoops... But there are other issues with output hatches, that also call for convoluted unreliable solutions, like distillation tower continuing process of input fluid while output hatch has insufficient space.
This is why you will need to add another convoluted redstone system to stop your distillation tower before any output hatch reach out of free space.
Hope you will find space for emitting fluid level redstone signal from all 6 fluid outputs and the item output hatches, tweak proper redstone signal levels with corresponding length of redstone, inverter redstonne torches, redstone or gates and route back signal to a machine controller cover to stop the distillation tower.
By chance this should fit in your base if you build rooms a few chunks wide and work perfectly and reliably as long as your server run at 20tps, never miss ticks and your chunks never unload.
