### ISSUE TITLE
Chem reactors cell slots don't always accept valid items

### ISSUE THREAD

**Issue by xarses** [Blood-Asp/GT5-Unofficial#422]
After spending over an hour trying to figure it out, I finally came to the conclusion that the Chem reactors are behaving different from electrolyzer and centrifuges. In that when feed by a GT pipe, they won't accept cells belonging to a valid recipe in the "cell" or second slot. 

They happily accept cells in the primary slot. Placing empty cells in this slot continues this behavior(they do not accept additional empty cells). 

However when placing the empty cell to the first slot, and the filled cell to the second slot. In this configuration, additional cells of both type fill the machine. 

Tested with hydrogen cell + empty cell as part of sulfuric processing line.
ver: gregtech-5.09.19

may be related to #337

**Comment by Blood-Asp** [comment]
There is no "cell" or "normal" slot. Even trough they look like that in the gui, both item slots are internally equal. The difference beween chem reactor and electrolyzer+centrifuge is that all chem reactor recipes with cells need an fluid inserted, while most electrolyzer and centrifuge do not need that. Insert the needed fluid into the chem reactor first before trying to insert the items and it should work.

**Comment by xarses** [comment]
Hrm, when empty the reactor is fluid-empty this behavior exists, when there is a fluid for a recipe present, it accepts the cells as expected
