### ISSUE TITLE
Strange behavior of IC2 liquid reactor and Liquid Heat Exchangers.

### ISSUE THREAD

**Issue by ObKo** [Blood-Asp/GT5-Unofficial#423]
First of all, here is setup I'm testing:
![2016-01-24_11 15 52](https://cloud.githubusercontent.com/assets/171339/12534632/80351e22-c28d-11e5-8d0e-48e3b590d61b.png)
![2016-01-24_11 17 57](https://cloud.githubusercontent.com/assets/171339/12534634/8e89c7fc-c28d-11e5-8405-77754282762d.png)
As you can see, reactor generates 192 hU/s. Problem is that LHE behavior significantly differs between vanilla IC2 (2.2.807-experimental) and IC2 + GT (5.09.19).

In IC2: 
![2016-01-24_11 19 06](https://cloud.githubusercontent.com/assets/171339/12534647/ef0c0ed2-c28d-11e5-9e06-5703ad259bea.png)
Reactor produces 192 mB/s of coolant, one LHE eats 100 mB/s of hot coolant and produces 100 hU (=50 EU/t in stirling generator). So, 1 hU/s in reactor = 0.5 EU/t

In GT:
![2016-01-24_11 22 34](https://cloud.githubusercontent.com/assets/171339/12534684/38d08976-c28e-11e5-99f0-e1221d9ad6a7.png)
Reactor produces 192 mB/s of coolant, one LHE eats **20 mB/s** of hot coolant and produces **80 hU** (why?! there is 10 conductors) (=40 EU/t in stirling generator). So, **1 hU/s in reactor = 2 EU/t**

For example, Large Heat Exchanger math: (src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_HeatExchanger.java):
1L/s of hot coolant = 2 (mEUt) = 4 (tGeneratedEU) = 4L/t of steam = **2 EU/t** (at 100% eff.)
So, Large Heat exchanger + Turbine have same energy output as striling. 

Is that bug or correct behavior?

**Comment by ObKo** [comment]
I'm not a minecraft coder, but it seems source of problem is in a448be8d4a118b85a64e68f53309c4ea38893b91

**Comment by draknyte1** [comment]
It seems that it was quadrupled on purpose.

**Comment by ObKo** [comment]
Well, I've thought about that a bit and now it makes sense for me.
Here:
 * IC2 LHE + Stirling: 1000 hU/s -> 50x LHE -> 4000 hU -> **2000 EU/t**

 * IC2 LHE + IC2 Steam: 1000 hU/s -> 50x LHE -> 4000 hU -> 2000 mB/t HP steam + 2000 mB/t steam -> 2000EU/t + 1000EU/t = **3000 EU/t**

* GT LHE + GT large turbine: 1000 hU/s -> 5000L per 5 seconds -> ~2000 mB/t HP steam + 2000 mB/t steam -> >2000 EU/t + >1000 EU/t (depends on rotor eff.) = **>3000 EU/t**

So, using only IC2 stuff, total amount of energy in case of steam is the same as in stirling gen, and 1.5x more in case of superheated steam. 

GT's LHE has same steam output as IC2 setup, but large turbines can have >100% efficienty, so GT setup can produce more energy.

Only one things bothered me now - why IC2's LHE consumes only 20mB/s of hot coolant and produces 80 hU? It should be 25 mB/s / 100 hU. But I'm not sure that Bloody can do something with that...
