### ISSUE TITLE
[Suggestion]Add catalyst for chemical stuffs

### ISSUE THREAD

**Issue by wormzjl** [Blood-Asp/GT5-Unofficial#424]
Like oil cracking and so on, this gives some uses to these rare metals
They degrades over time and need to be regenerated after use, probably first pass by oxygen then hydrogen

**Comment by axlegear** [comment]
Not sure about degrading and such but I do know that palladium, lutetium, and cerium are all used for cracking.  Only small amounts are needed, which is good because (except for palladium) they are all rare.  [I've been making turbines out of palladium just to use it up... over 64 stacks!]

**Comment by wormzjl** [comment]
Seem that they are not "rare" metals anymore :P

**Comment by PaladinOne** [comment]
The term "rare metals" doesn't really have a normal meaning in Gregorian world generation.

**Comment by Timeslice42** [comment]
To be fair "rare earth metals" aren't actually rare in the usual sense either. It's more a holdback from historical times. Like the name "pitchblende".
