### ISSUE TITLE
Fluid Extractor recipes missing in Recipes.cfg

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#425]
Lots of fluid extractor recipes are missing in the Recipes.cfg. It would be nice to have an option to disable some recipes for crossmod balancing purposes.

**Comment by MauveCloud** [comment]
I think you might be mistaken, especially if you're only looking at the "fluidextractor" section of Recipes.cfg - scroll down a bit and look at the "fluidsmelter" section.  The former is for special cases like creosote oil, fish oil, and seed oil; the latter is for items that are in GT's material system, like bolts, dusts, foils, gears, etc.

**Comment by JasonMcRay** [comment]
Hmm... You actually might be correct.... Thanks for pointing that out... will check when I get home.

**Comment by JasonMcRay** [comment]
Ok. Tested and it is indeed that. Thank you @MauveCloud
