### ISSUE TITLE
Some fluids have no cell container

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#429]
Epichloridrin, Polytetrafluoroethylene and other fluids have no cell or any other registered fluid container.
This makes it hard or impossible to handle fluid filtering/selection with other mods like Appliedenergistics2/Extracells2

**Comment by Blood-Asp** [comment]
You have to use IC2 universal cells. Programming EC2 with them should work just fine.
The reason i have not added normal cells, is that these needs new entrys in the Materials enum and that is full. Java limitation i can't change.

**Comment by leagris** [comment]
Would it be then something reasonable and not too dev intensive to enable IC2 Universal Fluid cells in Gregtech Machines and recipes, as well as other fluid container items?

**Comment by Blood-Asp** [comment]
The GT recipe system can not handle different but equal items. Even for oredict items it does first an unification step before searching for a recipe.
The only way to get the universal fluid cells working would be to also add recipes for them. While it is possible, i would call it not efficient. 
Efficiency is also the reason why it can not handle dynamicly similliar items in the first place.
