### ISSUE TITLE
Large Turbine cannot exceed optimal efficiency when using GT Fluid Pipes

### ISSUE THREAD

**Issue by sxtyzhangzk** [Blood-Asp/GT5-Unofficial#430]
The machines are connected like this: 
![2016-02-05_14 37 32](https://cloud.githubusercontent.com/assets/7344200/12847022/5d7fdb7a-cc4b-11e5-9488-1883fef22f79.png)

The Large Tungstensteel Boiler produces steam and store it in the RC Steel Tank. Finally it's sent to the Large Steam Turbine by Tungstensteel Fluid Pipe (12000 L/sec)
![2016-02-05_14 48 18](https://cloud.githubusercontent.com/assets/7344200/12847204/99ecde54-cc4c-11e5-8bb4-67b66052eb7a.png)

I used Steel Turbine in the Large Turbine:
![2016-02-05_14 47 34](https://cloud.githubusercontent.com/assets/7344200/12847158/43467e52-cc4c-11e5-9786-8f9a7bab85df.png)
(Its optimal steam flow is also 12000 L/sec = 600 L/t)

The Large Turbine output EU with a HV Dynamo Hatch, which was connected to a MFE.
![2016-02-05_14 49 12](https://cloud.githubusercontent.com/assets/7344200/12848905/8bd24876-cc57-11e5-936d-65e5902bd60e.png)

The power level of the MFE grew from 0 EU to 1M EU in 244 seconds (1,000,000/244/20 = 205 EU/t),
and when I turned off the boiler, the steam amount of the tank dropped from 3,000,000 mB to 2,000,000 mB in 84 seconds. (1,000,000/84/20 = 595 L/t)

In theory, the turbine should produce energy at a speed of (595 [L/t] \* 0.5 [EU/L] \* 95% \* (595/600) = **280 [EU/t]** ), but it was only **205 EU/t** ! The loss of the circuit should not be so much.

I checked the source code and it seems that GT Pipe transports fluid every 5 ticks (or 10 ticks?):

_[https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Fluid.java](url)
    public void onPostTick(IGregTechTileEntity aBaseMetaTileEntity, long aTick) {
        if (aBaseMetaTileEntity.isServerSide() && **aTick % 5 == 0**) {
            mLastReceivedFrom &= 63;
            if (mLastReceivedFrom == 63) {
                mLastReceivedFrom = 0;
            }
//something else...._

But the large turbine depletes steam every tick:

_[https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeTurbine.java](url)
public boolean checkRecipe(ItemStack aStack) {
//...
**this.mMaxProgresstime = 1;**
//...
}_

It means that the steam amount in the Input Hatch will be like this:
- Tick 0: +3000mB (from pipe) -> -750mB (125% fluid usage) = 2250mB (produce 600 \* 0.5 \* (1-150/600) = 225 EU)
- Tick 1: -750mB (125% fluid usage) = 1500 mB (produce 225 EU)
- Tick 2: -750mB (125% fluid usage) = 750 mB (produce 225 EU)
- Tick 3: -750mB (125% fluid usage) = 0 mB (produce 225 EU)
- Tick 4: 0 mB (produce 0 EU, considering the max change limit, produce 215 EU)

Considering some random things of the fluid pipe, that might be the reason why the turbine cannot run in full efficiency.

**MY SUGGESTION**: use average fluid flow in a few ticks to produce EU, or just let the turbine work longer every time (e.g. 5 ticks or 10 ticks) to fit the pipe.

Thanks for reading.

**Comment by OvermindDL1** [comment]
You can also add more input hatches with more pipelines too.  Don't forget shutters.

**Comment by MauveCloud** [comment]
For that matter, don't forget about fluid regulators (from IC2) - they can be configured to output an exact amount of fluid per tick, as long as they have enough.

**Comment by Blood-Asp** [comment]
Jep, fluid regulators. Also fixed another bug in the energy calculation reducing output while over optimum flow. So next update shoud rise the output of this construction after all.
