### ISSUE TITLE
Machine sounds not emitted from block center

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#433]
Machine sounds are emitted from the down-north-west corner of blocks instead of block center.

Could you add +0.5 to each sound location axis?

**Comment by Blood-Asp** [comment]
I know that this was changed multiple times in the history of GT. I have no idea anymore why it was changed back, but certainly the +0.5 change broke something else.

**Comment by OvermindDL1** [comment]
It did not break something else, rather when Greg kept updating GT to new MC versions he reverted chunks back to vanilla code, we'd talked about this before and it is safe to add 0.5 to each x/y/z value for sounds.

**Comment by Blood-Asp** [comment]
I just looked trough the code and noticed that all machine sounds allready have that +0.5 offset. Either there is some machine i missed, or you heard something wrong.

https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java#L615
