### ISSUE TITLE
Suggestion: Turbine multiblock tweaks

### ISSUE THREAD

**Issue by mura3277** [Blood-Asp/GT5-Unofficial#434]
**Better balanced casings for the different turbines:**
So currently what makes the better turbines harder to make is the turbine block itself. Upgrading to a plasma turbine from steam isn't really that difficult once you have a Mark 1 fusion reactor (Which is when you should be making them imo).

This suggestion will probably break existing turbine multiblocks, but maybe the turbines could use different turbine casings that use the same materiel thats in the turbine block. Example: Large plasma uses Tungstensteel.

**Show fuel with scanner:**
Since it's difficult to access the input hatch for the large turbines when you have pipes and fluid regulators blocking it, it would be really handy if the scanner told you the amount of liquid in the hatch when you scanned the large turbine block itself.

And possibly if there is multiple input hatches it would probably be best to show a total of current fuel and a total of maximum fuel storage across all hatches.

Thanks for reading.

**Edit**
A Diesel Turbine would be fantastic.

**Comment by mura3277** [comment]
So just to highlight something:

I understand that changing the casings for the turbines would break the current multi blocks in players worlds, but it was just to highlight a possible improvement next time someone is working on the turbine code.

**Comment by Blood-Asp** [comment]
Count the expanded scanner info for the turbine as sure to come.

Adding more casing materials for the turbine is technicly no issue, but a lot of work. So unlikely that i will do that.

**Comment by mura3277** [comment]
Thanks for adding the current output to the scanner info, that confirms that my google sheet containing the turbine math is correct ;p

May I ask that current fuel consumption is shown too along with the mb in the tank?

Also side note: I just let the input hatch fill up with nickel plasma and the turbine was making double what my math suggested. What situation would cause it to output double it's supposed to when the tank is full?

**Comment by mura3277** [comment]
Added with PR
