### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by OvermindDL1** [Blood-Asp/GT5-Unofficial#435]
Direct download did not download the dependency from maven for shedar.mods.ic2.nuclearcontrol.api nor does this dynamically link shedar.mods.ic2.nuclearcontrol.api.  Either of those would fix this issue.

1  Link via gradle to the shedar.mods.ic2.nuclearcontrol.api so the dependency will download for linking purposes, but not embed.
-- or --
2  Dynamically link to nuclearcontrol, though this requires class generation at loading time, not hard to do, but is a pain, option 1 is significantly easier.

**Comment by Blood-Asp** [comment]
I have no idea how and where to link to for NC to work. The buildscript of GT5U was a PR and all i did there was updating the links for newer dev/api versions.

**Comment by OvermindDL1** [comment]
As nuclear control does not seem to be well set up enough to have the dev api on maven then the easiest way would be to compile nuclear control yourself and host the dev/api yourself (like here on maven, or I can put it on files.minecraftforge.net if you want) and link to it via the gradle script like you do the other dependencies.  Can also dynamically link to it, but you know java, that is a pain, possible, but a pain.  Want me to host it or do you want to?  If you can get this repo compiling clean then I can even add it to the forge build server so it can be hosted like GT itself is at http://files.minecraftforge.net/maven/com/gregoriust/gregtech/index.html

**Comment by OvermindDL1** [comment]
Can also include the api itself in a lib directory too to be used for compilation, just keep it in git then.

**Comment by OvermindDL1** [comment]
I'm walking xbony how to generate proper dev jars and how to upload to maven with an offer for him to use the forge maven, so this issue may be resolved shortly.  :-)

https://github.com/xbony2/Nuclear-Control/issues/141

**Comment by Blood-Asp** [comment]
I'm always up for the last time comsuming option. Lets see what bony changes and adapt. That i did not add it so far was simply that it would take me more time adding it to the build script than adding it to the libarys myself every install.

I would be glad if you would add the nessary change to the buildscript. Doing that myself would likely take me a few tries and a lot of time...

About adding it to the forge build server, so far i see no need for that. Everything works fine as it is. Maybe when i do some bigger changes again.

**Comment by OvermindDL1** [comment]
Can do once his side is complete.  :-)

**Comment by Blood-Asp** [comment]
Could add NC2 trough curse download: https://github.com/Blood-Asp/GT5-Unofficial/commit/ff4cfa3933d9015d1f27bafa908ab7dea2ae6193
