### ISSUE TITLE
Fluid pipes hitbox too small

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#437]
Fluid pipes placed in-world have a hit-box smaller than full block (7/8).

Having a tiny polyethylene pipe running in ground, it cause player character to step down a bit each time walking over the pipe.
Even covering the pipe does not fix the hit-box.

I understand it is a mean of dealing dealing damages when player enter the fluid pipe block.
But covered sides should expand hit-box to full block.
That would also make covers a suitable protection against damages/touching pipes/power cables...

**Comment by Timeslice42** [comment]
Covers already protect from damage...

**Comment by leagris** [comment]
Then, covered sides of pipes should expand hit-box to full block limit.

**Comment by Blood-Asp** [comment]
The base metatileentitys are not made to change their size. Tried it once but gave up after a few unsucessfull hours.
