### ISSUE TITLE
Quantaria leaf requires ungenerated ore for processing

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#438]
Processing Quantaria leaf require crushed Osmium ore.
Problem: This ore is not in standard/default Worldgeneration.cfg

**Comment by Blood-Asp** [comment]
I added it for the UUM based ore production. Allowing to produce Osmium ore from other crushed ores would be unbalanced, so i will for now keep it that way. Not perfekt, but at last there is some way to use the leafes.
