### ISSUE TITLE
Fluid Detector Cover Not working in Normal Mode

### ISSUE THREAD

**Issue by traeger** [Blood-Asp/GT5-Unofficial#44]
The fluid detector cover is not working in "normal mode" at all (emitting always 0).
In "inverted mode" it works pretty fine.

Tested on a Basic Steam Turbine.

Nothing in the error log.

Used Versions:
gregtech 5.08.19
forge 1428
ic2 2.2.732

**Comment by Blood-Asp** [comment]
fixed in 5.08.21
