### ISSUE TITLE
Gregtech crash with Dimensional Control

### ISSUE THREAD

**Issue by Charnuz** [Blood-Asp/GT5-Unofficial#443]
Gregtech 5U crashes when Dimensional Control by BloodNBonesGaming when loading mods.
Using:
- Gregtech-5.09.19
- industrialcraft-2-2.2.795-experimental
- DimensionalControl-1.6.0
- BNBGamingLib-2.3.2
- forge-10.13.4.1614

Crash Log:
http://pastebin.com/n7yGH3iz

**Comment by Blood-Asp** [comment]
Not much i can do there. That mod should not use the GT Dummy class.
