### ISSUE TITLE
[Sugestion] GT Grafter

### ISSUE THREAD

**Issue by ElderEvil** [Blood-Asp/GT5-Unofficial#445]
May I suggest you to make Forestry grafter GT style like Scoop and other instruments?

**Comment by leagris** [comment]
This tool already exists and is called a [Branch Cutter](http://ftb.gamepedia.com/index.php?title=Branch_Cutter_%28GregTech_6%29).

**Comment by ElderEvil** [comment]
Thank you, I didn't know that.
