### ISSUE TITLE
Branch Cutter does not work on IC2 Rubber Tree leafs

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#446]
While a Branch Cutter can get 100% sapling drop on vanilla and forestry mod trees leafs; It fails to do so, with Industrialcraft2 Rubber Tree leafs.
For a mod that's an add-on to Industrialcraft, it is kind of a contradiction not being compatible with it's own parent mod :)

**Comment by Timeslice42** [comment]
This is technically IC2's fault, because of the hacky way they did the rubber trees.

**Comment by Blood-Asp** [comment]
yes, missing blockharvestevent. Would need a completly different way to handle the tools for this to work.

**Comment by OvermindDL1** [comment]
Or just wipe and replace the rubber trees with a GT rubber trees?  (perhaps some way to use the same block ID too.  Or inject code into it.

**Comment by Blood-Asp** [comment]
still not worth the work just for making the cutter work on them....

**Comment by MauveCloud** [comment]
I came up with a workaround:  one can use GTTweaker to allow putting sheared leaves in the cutting machine to get saplings, and this should work even for leaves not affected by branch cutters or Forestry grafters.  It won't work for Forestry leaves, though, because the different leaf types are only distinguished by NBT data.

Also, I don't recommend doing that for saplings that are supposed to be difficult to get, such as Thaumcraft silverwood saplings, unless you give it additional nerfs, such as making it require a higher-tier cutting machine, more leaves per sapling, and/or more valuable fluid in place of water/lubricant.

**Comment by OvermindDL1** [comment]
> still not worth the work just for making the cutter work on them....

Might be worth it if it adds the ability to hook a bucket or so on to the side of a rubber tree and let it auto-catch sap from the tree, say it holds 1-3 loads worth (maybe upgradable versions).  Or other things to do with the trees...

**Comment by MauveCloud** [comment]
> Might be worth it if it adds the ability to hook a bucket or so on to the side of a rubber tree and let it auto-catch sap from the tree, say it holds 1-3 loads worth (maybe upgradable versions).

That sounds like IHL, which encourages you to keep the leaves on the tree when collecting sap from it (and also allows collecting sap from spruce trees iirc, which the GT branch cutter already works on, so you don't even need the rubber trees anymore).

**Comment by leagris** [comment]
IHL Sap Sack on Spruce is spruce resin, not rubber.
Now i think Silicone (polysiloxane) should be a substitute for all rubber stuffs.
See also [Polybutadienes](https://en.wikipedia.org/wiki/Polybutadiene).

**Comment by MauveCloud** [comment]
> IHL Sap Sack on Spruce is spruce resin, not rubber.

I haven't really used IHL myself, but I just checked its wiki, which says the sap gathering sack can be placed on either a spruce or rubber trunk.

**Comment by PaladinOne** [comment]
And as far as I knew from playing with the mod last year, the Sap Sack was explicitly designed to capture fluid raw rubber sap from Rubber Trees (and, if attached to a Rubber Wood block it changes the block to an IHL version of the block), and that then there were two machines and a GT Centrifuge recipe that would convert that sap into Sticky Resin.
