### ISSUE TITLE
Issue with Nitro-Diesel

### ISSUE THREAD

**Issue by lilmoefow** [Blood-Asp/GT5-Unofficial#448]
Output with Gregtech Nitro-Diesel is lower than output with Bulcraft Fuel (regular Diesel)

The image is showing one generator with Buildcraft Fuel in it and the other with Nitro Diesel. Both generators were turned on at the same time and let run for a few seconds.

http://imgur.com/1tgBjyj

Forge 1.7.10 - 10.13.4.1614
gregtech-5.09.19.jar
industrialcraft-2-2.2.810-experimental.jar
buildcraft-7.1.14.jar

**Comment by leagris** [comment]
Exactly, it is output rate. It is like it skip generating full 32EU/t every few ticks so in the end, while still outputing more total EU for longer, its output rate is lower with Nitro-Disel.

**Comment by Blood-Asp** [comment]
The generator internal EU storage was to small for nitro diesel energy density.
