### ISSUE TITLE
Crash client when I want to join the server

### ISSUE THREAD

**Issue by Maffeo** [Blood-Asp/GT5-Unofficial#45]
GT: 5.08.19
IC2: 2.2.731
Forge: 10.13.4.1448

In new version forge I get crash client when I want to join the server [forge version] , with this same set up. 
In old version forge [10.13.3.1355], all works fine 

Client crash report: http://pastebin.com/Zw25GSvh
Client crash log: http://pastebin.com/ukn7tVHf
No logs about this from the server side

EDIT
I tested different release forge and results are below.
Forge 10.13.4.1448: SSP is works; SMP is not works
Forge 10.13.3.1355: both modes works fine [SSP & SMP]
Forge 10.13.3.1408: both modes works fine [SSP & SMP]

Sorry for my English, it is not my native language.

**Comment by Bogdan-G** [comment]
Test in 1428?

**Comment by Blood-Asp** [comment]
As you found out yourself, incopatibility with newest forge version. Might be just a forge bug, so i will wait a bit with updating GT.

**Comment by Maffeo** [comment]
I checked changelog forge and in version 1228 is some changing about fluid race condition. 
Below quotation from changelog forge:
> cpw:
>    Fix up the client/server fluid race condition that could cause the game to bail when an SSP game connects.
> There's still a teeny gap, but it's MUCH less prominent than it was before.

**Comment by Bogdan-G** [comment]
LexManos not planned update 1.7.10 forge branch.
