### ISSUE TITLE
Crops

### ISSUE THREAD

**Issue by Nex4rius** [Blood-Asp/GT5-Unofficial#451]
It would be nice to know what items are being dropped by which crop.
I know for some seeds its easy like Oilberries but for other its a bit more difficult.
Reactoria - is that uranium?
Stargatium - Is that supposed to be for naquadah?
Starwart, Evil Ore, Quantaria, Transformium - no idea

Could you add information for the seeds into the tooltip or into this nei info thing?

**Comment by Blood-Asp** [comment]
The seeds are generated by IC2, so not by me.

**Comment by Timeslice42** [comment]
FYI, infitech is adding an NEI mod that works for IC2 crops, and also has partial support for GT crops.
