### ISSUE TITLE
Naquadah/Enriched ores cannot be mined with Efficiency V

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#456]
Pickaxes with Efficiency V break Naquadah and Enriched Naquada ores without dropping an Ore block so destroying block instead of mining it.

**Comment by Blood-Asp** [comment]
Only efficiency V does that? Everything else works fine? How the f\* could that happen?

**Comment by leagris** [comment]
Vanilla Diamond Pickaxe with:
Fortune III
Unbreaking IV
Efficiency V
Destroy Naquadah ore instead of mining

Same with GravisuiteReloaded Vajra

But good with:
EnderIO Dark Pick
Empowered IV

After further tests:
A vanilla Diamond Pickaxe without any enchant also destroy Naquadah Ore.
So it turns out, Efficiency only accelerate block break but Diamond tool has not enough hardness to mine Naquadah Ore.
Then usage feed-back is misleading.
Efficiency enchant should not accelerate break time if tool cannot mine block.

**Comment by Blood-Asp** [comment]
So it is actually just wrong mining level and only feels wrong?

Well, the calculation of the mining time is part of the tool, the blocks only have the values for hardness and resistance, so nothing i could do to change that.

**Comment by leagris** [comment]
Exactly!
Thank you for looking at it.
Closing issue since there is nothing to be done Gregtech side.
