### ISSUE TITLE
5.09.20 Regulator cover recipes broken

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#457]
Gregtech 5.09.20

> *Added Regulator cover(pump cover with adjustable L/sec).

Each regulator cover recipe output an LV regulator cover according to NEI.

So higher tier of regulator covers are unobtainable.

**Comment by leagris** [comment]
In an assembler, inserting any tier of pump immediately start crafting an LV regulator. Not even require a 2nd pump or circuit. Recipe is processed with only one.

## I'd suggest recipes with:

### Inputs:
- IC2 Fluid regulator // IC2:blockMachine2:14
- Gregtech Pump (tier)

### output
- Gregtech Fluid Regulator Cover (tier same as pump in recipe)

## Suggestion

Fluid Regulator Cover should have a Redstone ramp-up controlled mode where each time redstone level goes from 0 to >=1 regulator output programmed Litre amount.

### Example

It could be used to send exactly 144l for solidifying 1 ingot/plate/.. item per Redstone pulse/

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/6e0f90964ec2b6d7b436fb5b9bc0c1e0b09be0bf
Crafting recipe is fixed.
Sending per pulse is sadly not possible the way covers are coded. They have no way to store the prior redstone signal to see there was a singnal change.

**Comment by leagris** [comment]
Can it check destination has enough free space for a full amount transfer?
It would prevent a regulated 144l/s to go off because destination received less (cause full).

**Comment by Blood-Asp** [comment]
A check might be possible, but likely needs quite a lot of code. Will try it later.
