### ISSUE TITLE
wroght iron creation is missing from arc furnace

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#458]
the only recipe showing is a recycling recipe for reinforced tungsten steel blocks.

**Comment by Blood-Asp** [comment]
Did you actually test that? 
All recipes should work, just hidden to easier find the important recipes. you can unhide them in the config.

**Comment by bear989** [comment]
it's the fact it is missing from NEI that I have issue with, not for me,
for newer players. that isnt a recycling recipe it is part of progression
for making steel cheaper.

**Comment by axlegear** [comment]
I haven't tested yet if it works but just to pipe up, I do want to say that if it's not showing in NEI, it might as well not exist-  we live and breathe by NEI's word.  So May want to unhide the one recipe of iron ->  w. iron.

**Comment by Blood-Asp** [comment]
I planned to only unhide all recipes with iron and copper as input, so there is an example how the rest works. But it seems that filter i coded does not work as planned.

**Comment by axlegear** [comment]
Actually I just tested and Arc Furnace will not make w. iron anymore, or annealed copper.  Or anything, actually.  Seems that while trying to hide the recipes it instead removed them.
