### ISSUE TITLE
Some new fluids have their temperature missing

### ISSUE THREAD

**Issue by yznpku** [Blood-Asp/GT5-Unofficial#459]
Notably oxygen gas, nitrogen gas and argon gas.

Their temperature are currently displayed as 0K.

**Comment by Blood-Asp** [comment]
what do you mean by "temperature missing"?
It is not possible to add fluids without an temperature in forge.
There are some cases, were other mods override GT fluids. Often happens with galacticraft, which also breaks the icons and sometimes even machine usage of said fluids.
