### ISSUE TITLE
Fusion reactor issue while playing on server

### ISSUE THREAD

**Issue by Anikilulala** [Blood-Asp/GT5-Unofficial#46]
Fusion reactor seems not working correctly in a SMP game.
In the single player game,it seems everything goes right.
However, when i did exactly the same design on a public server ,something weird happend.
The fusion had successfully started,but not working continuously.Its working status was switching fast between "Working perfectly" and "Hit with Soft Hammer..... " about 5 seconds a cycle, and the output was only 1/5 of the normal.

If you don`t turn it off or cutting down the power supply,the reactor will keeping on adsorbing energy from e-net.And as soon as the storage reaches another 40M EU threshold ,the reactor will try to start another new reaction automatically consuming all energy and then start to recharge.
Tested on gregtech 5.08.19, cauldron server

**Comment by siriulx** [comment]
After that, we use an official forge server (version: 1403) to test that, and try to exclude the influence of using cauldron.

When we are running the fusion reactor, the server will spam following message:
 [Server thread/INFO] [STDOUT]: [gregtech.loaders.misc.GT_Achievements :issueAchivementHatchFluid:264]: fluidAchievement fluid.plasma.helium

Then, I turned off the GT achievements system in the config file, and solved the spamming issue. But this time, the fusion reactor won't work perfectly as it before, and the status will be switching between "Working perfectly" and "Hit with Soft Hammer.....

**Comment by Anikilulala** [comment]
According to several comparative experiments, there might be a bug involving the fusion reactor and the new achievement system,no matter your are running a vanilla server or a cauldron server.
IF the server option B:EnableAchievements=true ,the fusion reactor works correctly but the server side will suffer a error message spam.
IF the server option B:EnableAchievements=false,the weird bug mentioned before will occur although message spam stops.

**Comment by MIINELZ** [comment]
Also I had the same problem in the SMP

**Comment by Blood-Asp** [comment]
should be fixed in 5.08.20 Did not MP testing so far.
