### ISSUE TITLE
Bee foundation name issue with NEIAddons

### ISSUE THREAD

**Issue by mura3277** [Blood-Asp/GT5-Unofficial#461]
![image](https://cloud.githubusercontent.com/assets/7321570/13939108/bb38520a-efc9-11e5-9881-f584624f613f.png)

This isn't really a large issue since if it's a foundation block with a GT bee it's probably the corresponding materials block.

**Comment by axlegear** [comment]
Confirmed, been an issue for a while but it's just a minor deal.. I think we can guess what it's asking for.  XD

**Comment by Blood-Asp** [comment]
I guess NEI Addons can not handle with meta blocks. Unlikely that i can fix that. Should be fixed on NEI Addons side afaik.

**Comment by axlegear** [comment]
We have NEI addons but it seems to be still that way.  Unless there's a newer version i'm not aware of?  We have neiaddons-1.12.14.40-mc1.7.10

**Comment by Blood-Asp** [comment]
I did not mean that it is allready fixed. I meant that it is NEI Addons that has to do it.

**Comment by axlegear** [comment]
Ah, gotcha.

**Comment by mura3277** [comment]
Oh I didn't realize this would likely be on the NEIAddon side, my mistake.

I'll leave it up to you to close this or not.

Thanks.
