### ISSUE TITLE
5.09.20 High pressure pipes crafting recipes disappeared

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#464]
High pressure pipes can not be crafted since release 5.09.20.

See: http://forum.industrial-craft.net/index.php?page=Thread&postID=199596#post199596

**Comment by axlegear** [comment]
Confirmed.  It shows in NEI but there's no crafting recipe and you can't do it with the previous components.

**Comment by Blood-Asp** [comment]
The recipe shows for me in NEI in my dev enviroment. But it might be that i allready fixed it without knowing about because i fixed something that might be similiar to it.
