### ISSUE TITLE
Disassembler destroying items without ingredient

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#465]
From a Player perspective it is impossible to tell if an item can be disassembled in disassembler.
When inserting an item without ingredients it is discarded.

Correct behaviour should be to not start processing or output item as-is with no or minimal EU cost like 1 tick, 1 EU/t.

I have machines created with Gregtech 5.07 from @GregoriusT that contains ingredients, and thus can be disassembled (My old MV Arc Furnace). Some if not all recently created machines have no ingredients and must be processed in an Arc Furnace/Macerator/Solid Fluidifier to recover some materials.

Really, player has no way to know if this or that has ingredients to disassemble.
In this situation: Inserting anything in disassembler is gambling.

**Comment by axlegear** [comment]
Rejection or some indication would be nice yes.

**Comment by GregoriusT** [comment]
Good Idea. If I re-add the Disassembler in GT6, I will add a Tooltip
to the Item indicating it, also I will either disable "hopper" input
of unsuitable stuff or just drop the item as-is in the output.

And did Bloody really disable the Disassembler for things that can be
arc smelted or pulverized? That's horrible from my pov if that
happened.

**Comment by Blood-Asp** [comment]
I did not disable disassembling for anything intentionally. So far i also did not notice any machines not working in the disassembler, but since i rarely disassemble anything besides tools ore turbine rotors i might just have missed that. 
So in case that function is broken i will try to fix it.

**Comment by GregoriusT** [comment]
Note: cheated in machines don't work ofcourse, only the ones you
actually crafted. So smelt/macerate the cheated machines. But a
Tooltip would be nice ;)

**Comment by leagris** [comment]
I have a Tungstensteel File perfectly legit crafted but without crafting components.
I have a ToolWrench HV this one has crafting components and can be disassembled.

Can't remember cheating it but I had some very old machine I could not disassemble and it was lost in disassembler. (I likely did and forgot it)

Anyway, there are surely rules about what can be disassembled but some lore mention and rejection/by-pass could really help.

**Comment by GregoriusT** [comment]
wait a regular File? yeah manual tools cannot be disassembled, only
the electric ones.

**Comment by axlegear** [comment]
Yeah, it would be nice if it rejected those instead of just vaporizing.

**Comment by Blood-Asp** [comment]
Only case were disassembler did destroy items was with non electric GT tools.
Improved check to: No item output = do not start/destroy item.

**Comment by GregoriusT** [comment]
I hope you didnt forget that the thing has chances that nothing comes
out even if something has valid components to disassembly. Otherwise
you might break balance if you inserted the check at the wrong
location.
