### ISSUE TITLE
Greg Tech 5.09 with Forge 1291 and Forestry 4.1.1.46 crashes when i'm trying to watch any NEI recipe

### ISSUE THREAD

**Issue by FireWarrior2** [Blood-Asp/GT5-Unofficial#466]
First, internal server shuts down but MC doesn't crash and then it writes "Failed to connect to server". When i'm trying to enter the world for second time, it loads, but when i want to watch any NEI recipe MC crashes. Who knows why?

**Comment by Blood-Asp** [comment]
First, the forge version is really old and no longer supported.
Next, try so update Forestry. Currently i use Foresty 4.2.10.58.

**Comment by FireWarrior2** [comment]
I tried to use latest version of Forge but it crashes even without mods! latest  Forestry depends on this Forge

**Comment by Blood-Asp** [comment]
Forestry certainly does not depend on Forge 1291. I currently use Forge 1566 and it is more likely that it crashes with such an old forge version. Did you maybe download forge for Minecraft 1.8 or 1.9?
At last the issue is you doing something wrong, not on my side.
