### ISSUE TITLE
Crowbars can be used to break grass/netherwart

### ISSUE THREAD

**Issue by yznpku** [Blood-Asp/GT5-Unofficial#467]
If done so, a tool-breaking sound is played, and the crowbar loses 1 point of durability.

Is this behavior intentional? I'm not getting it.

**Comment by MauveCloud** [comment]
I think it might be a side effect of some fallback code that makes the crowbar usable for removing blocks from other mods that aren't properly coded to handle adventure mode.

**Comment by Blood-Asp** [comment]
Jep, actually correct working.
