### ISSUE TITLE
drills aren't getting power automatically

### ISSUE THREAD

**Issue by Nex4rius** [Blood-Asp/GT5-Unofficial#468]
The gregtech drills don't get power from batpacks

Tested with
BatPack (IC2)
Adv.Batpack (IC2)
Energypack (IC2)
QuantumSuit Bodyarmor (IC2)
Advanced Lappack (Graviation Suite)
Ultimate Lappack (Graviation Suite)
Advanced Electric Jetpack (Graviation Suite)
Advanced NanoChestPlate (Graviation Suite)
GraviChestPlate (Graviation Suite)

I used this drill:
<a href="http://imgur.com/G1QnrO1"><img src="http://i.imgur.com/G1QnrO1.png" title="source: imgur.com" /></a>

Infitech v.3.2.3
gregtech-5.09.21
industrialcraft-2-2.2.817-experimental
GraviSuite-1.7.10-2.0.3

**Comment by yznpku** [comment]
Try right click at the ground with the drill?

**Comment by Nex4rius** [comment]
that works ..
Why is that manual and completly different from all other (ic2) electric tools :(?

Could you change it to the normal ic2 tool behaviour? (automatic energy refilling)

**Comment by mura3277** [comment]
Not that this is adds to the issue, but just to highlight that GregTech 5 powered tools/items use GTEU, not IC2EU so it's not that this is "missing" rather it's just now what we're use to.

To add to the issue:
I think the tools should attempt to pull energy from lappacks etc when the player breaks a block(or a relevant action with any electric tool).

**Comment by Blood-Asp** [comment]
Nope, stays as it is. Otherwise source of lag, uncontrolled behavior and needs deep changes in the tool.

**Comment by Nex4rius** [comment]
Thats annoying now we have to go mining and hold both mouse buttons at the same time :(

**Comment by Blood-Asp** [comment]
make a right click once every 10min, is that so difficult?
