### ISSUE TITLE
IC2 Wire Cutter - Craftable, should not be

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#47]
Both gregtech and ic2 wirecutter are enabled. Even having the config option in recipes.cfg
disabledrecipes
IC2_blockCutter_true=true

is not disabling the IC2 cutter.

**Comment by Blood-Asp** [comment]
The blockCutter is not the wireCutter.

Now i remove IC2 Cutter recipe when IC2 cables are disabled.
