### ISSUE TITLE
Fluids at 0K ?

### ISSUE THREAD

**Issue by Nex4rius** [Blood-Asp/GT5-Unofficial#470]
Some fluids are at 0K which doesn't make sense:
Oxygen
Methan
Hydrogen
Nitrogen

Infitech2 modpack v3.2.3.1

**Comment by Blood-Asp** [comment]
That is some other mod loading the fluid before GT and overriding the stats. Likely Galacticraft again, but i did not test it so far.
But with GT alone the issue is not happening.

**Comment by yznpku** [comment]
Got the same issue from infitech2. The issue only presents when both GT and Galacticraft are installed. Wish I could look into it some day.

**Comment by JasonMcRay** [comment]
It is an issue with Galacticraft. All these 4 fluids/gases are present in there. I raised an issue on their tracker: https://github.com/micdoodle8/Galacticraft/issues/2167
