### ISSUE TITLE
machine restarts very often

### ISSUE THREAD

**Issue by Nex4rius** [Blood-Asp/GT5-Unofficial#474]
If you have a machine controller and the multiblock runs out of power it will restart immediently (and destroy whatever it has in the input bus).
I don't think it should restart even with a machine controller that tells it to run when its out of energy.
<a href="http://imgur.com/Yx0aeZ7"><img src="http://i.imgur.com/Yx0aeZ7.png"/></a>

**Comment by Blood-Asp** [comment]
Thats really difficult to fix because of how the machine controller is coded... and since it interacts with every type of machine changes there effect basicly everything...
I will see if i can find a way to fix it, but no promise.
