### ISSUE TITLE
distillation tower

### ISSUE THREAD

**Issue by Nex4rius** [Blood-Asp/GT5-Unofficial#476]
The distilation tower will not use the oil in a second input hatch if the first one still has less oil in it than required for processing (less than 50-150 mb).
You cannot use the same distillation tower to process different types of oil (each with its own hatch) because of that.

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/2427bc1521d110aded737e2d4f1bed0f20671426
