### ISSUE TITLE
[5.09.21] missing recipes

### ISSUE THREAD

**Issue by kharbick** [Blood-Asp/GT5-Unofficial#480]
I updated from 5.09.19 to 5.09.21 recently and saw the feature in the changelog about removing recipes for unused materials from NEI.  However it seemed some additional recipes were also removed.  For example, recipes for Data Stick and Soldering Iron were not visible in NEI, but could still be crafted.  I tried turning off the config flag and the recipes were visible again, but unfortunately also so are the unused materials.  It's a very minor inconvenience, just wanted to let you know.

**Comment by Timeslice42** [comment]
Yes, I agree. Hiding recipes such as machines to parts in an arc furnace is a reasonable thing to do. Hiding recipes such as gold to molten gold in a fluid extractor is a bad thing, and makes the feature unusable.

**Comment by MauveCloud** [comment]
I can see recipes for Data Stick and Soldering Iron in 5.09.21 at the moment, with HideRecyclingRecipes=true in the config.  However, I had it temporarily set to false, then set it back to true, which might have strangely fixed this for me.

**Comment by kharbick** [comment]
Wrong flag, it's the one that hides unused materials.

**Comment by MauveCloud** [comment]
You mean "HideUnusedOres"?  I'm fairly sure I've had that true since I started my current world, and it hasn't stopped me from seeing the recipes for Data Stick or Soldering Iron.  If you mean a different one, please tell me the exact name and which config file it's in.

**Comment by kharbick** [comment]
That's the one.  I can't explain why, but setting that to true turns off hundreds of recipes that shouldn't be turned off.  Another example, it turned off about 90% of the recipes that use steel as an ingredient, including really basic stuff like tool heads.

**Comment by MauveCloud** [comment]
Wait, what? Tool head recipes show up for me, at least when I look up usages of steel plates or steel ingots (I can't look up the tool heads directly because I have the option "show_all_metaitems_in_creative_and_NEI" set false)

**Comment by kharbick** [comment]
I tried to reproduce the problem to get more info, by reverting the config back to 'true', but couldn't.  All the recipes are there.  When it was happening, finding the recipes using the usage function on a component worked fine (sorry I meant the names not the ingredients before), and crafting worked fine, it's just they didn't show up in the search window when I searched for "solder" or "data".  When I searched for "steel" I got less than a full page of recipes, instead of 9 pages (at my resolution).

Anyway I can't reproduce it now so feel free to close this if no one else has a problem.

**Comment by Blood-Asp** [comment]
I can not really think of a way how to reproduce this. Or how it can even be possible.
The "hideUnusedOres" config does not even touch anything part of the recipes.

Also about "Hiding recipes such as gold to molten gold in a fluid extractor is a bad thing", i made it so that of every material the "ingot -> molten" recipe is there to show the needed voltage and also every iron melting recipe is also there to show amounts of every item type. Other machines have similiar behaviors.

**Comment by Timeslice42** [comment]
Good. That should help alot towards making the "hideRecyclingRecipes" feature useful.
