### ISSUE TITLE
IC2 Single-Use batteries

### ISSUE THREAD

**Issue by Timeslice42** [Blood-Asp/GT5-Unofficial#483]
Currently the GT machines do not support the IC2 single-use batteries. I imagine that this is because they aren't actually batteries, as far as the API is concerned. IC2 machines support two(?) items as power in machines: redstone, which provides 800 EU, and single-use batteries, which provide 1200 EU.

We probably don't need to support redstone as power, but it would be really nice to support the single-use batteries, both as an early game stop-gap for power needs, and because that's the only use for hydrated coal dust, which is an output of some GT recipes (the distillation tower, I believe).

**Comment by leagris** [comment]
If you are running a Distillation Tower, maybe you don't need those IC2 1200 EU batteries any-more.
IC2 stopped using Hydrated Coal for anything since Experimental. Maybe you are referring IC2 Classic?
Either fluid extract your Hydrated Coal for a Total of 128EU or smelt it to Coal, or dispose/recycle it.

**Comment by Timeslice42** [comment]
IC2 has a method you can call on any ItemStack which will tell you the energy value of an item when that item is placed in a charge slot: ic2.api.info.Info.itemEnergy(ItemStack)
This is exactly the same as calling ic2.api.info.Info.itemFuel(ItemStack) to see how much fuel an item is worth when placed in a fuel slot (i.e. a vanilla furnace or IC2 generator).

You could potentially call itemEnergy() before line 450 here: https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java#L450

If the energy value is > 0 and the energy value + getSoredEU() is < getEUCapacity() then remove an item from the itemstack and add the energy to the stored EU. Something like that.

This will then automatically support any item IC2 adds as a single-use energy source, rather than just hard-coding support for the SU batteries.

**Comment by Timeslice42** [comment]
If I had a dev environment set up I'd just do a PR myself, as it's a simple change.

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/183a681d529fda727d16009a60cb97b6994b03f3
There...

**Comment by Timeslice42** [comment]
Woot! Thanks :) As far as I'm concerned this ticket is closed, but I don't know if you like to leave them open until the issue is published, so I'll leave it as is for now.

**Comment by Blood-Asp** [comment]
I uploaded a precompile to play around with on the forum.
Will close the fixed issues once the real release is done and a proper changelog too.

**Comment by Timeslice42** [comment]
Confirmed working in my test world :)
