### ISSUE TITLE
mass fabricator needs a little more than 4 amps..

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#484]
@ghoulsblade said:

> 4 amps hv -> mv transformer -> mass fabricator with battery in it, battery drains slowly.
> No cable in between, massfab directly at transformer, no other machines connected, so loss minimized as much as possible.
> Maybe due to transformer not being lossless and 32eu/t x 4 amps uu recipe ?
> Please set the recipe to 30eu/t if possible, the difficulty should be in producing the required amount of power, not in running an extra tiny cables because it doesnt add up even if you optimize loss as much as possible.

Feel free to close if irrelevant, or not gonna change

**Comment by Blood-Asp** [comment]
Unsure right now. Borderline case beween me wanting it more complex and unessary hassle.

**Comment by leagris** [comment]
There is an option already to enforce or not the use of UUAmplifier.

As Mass fabricator creates UUM with direct Energy to Matter conversion, there is a logic behind consuming energy massively but:
When given UUA Input, it should require much less energy per UUM.
To make the LV Mass fabricators more practicable while maintaining reasonable complexity, it should only draw 1 Amp 30EU/t when input of UUA and 4 Amp 480 EU/t without UUA.

Something like that would create better incentive to produce UUA.
Maintain complexity and motivation for using more complex infrastructure.
Render Lower tier Mass Fabricators more practical.

Alternatively, a more efficient multi-block combined functions of recycler+unboxinator+amplifier+massfab+replicator could have its Reason-d'etre.
Have a data orb/circuit slot where if:
Config=0/Empty → output scrap
Config=1 → output unboxed items
Config=2 → output UUA
Config=3 → output UUM
Data Orb → Replicate material from Data Orb

Could have: 
- input bus for items to recycle
- input hatch for UUA/UUM
- output bus for items (unboxed/replicated)
- output hatch for UUA/UUM

Controller crafted with all 5 Machines

Be as fast as an IV Replicator while much more energy efficient.

Could be named a: Synthetiser

**Comment by Blood-Asp** [comment]
Decided Mass Fabs will stay as they currently are.
