### ISSUE TITLE
Nerf suggestions for magical energy absorber

### ISSUE THREAD

**Issue by DerEchteLanger** [Blood-Asp/GT5-Unofficial#485]
I think that the magical energy absorber doesnt realy fit the rest of the mod. They can provide lots of maintainance free energy, since nodes and enderdragon-eggs are easy to get with e.g. bees. To reduce their usage as "place and forget" energy sources they should require some sort of maintainace/manual work, e.g.:
-Decreasing energy output after some time
-Needing a catalsyst item thats either not renewable or only insertable by hand
-Having the nodes degrade/the egg jump away (like clicked) after some time
-Making them standart multiblock structures with their maintainace needs
other good ideas?

**Comment by leagris** [comment]
Dragon Egg could be consumed. But unless you install Magic Bees or some mods that bring renewable Dragon Egg, it is not. And only One can be used to produce energy or it expload.

Nodes, well if you install Thaumcraft it is that you want some magic, why nerf?
If you find magical energy to be OP, then don't add mods that bring OP magic.
You also have the option to nerf efficiency of generators in Gregtech config. Setting magical energy absorbers to lower efficiency could be a good nerf option.

**Comment by Xavion3** [comment]
From the looks of nodes they need a lot of oomph anyway, to hit HV power gen you need 51 centivis of the same aspect, although it scales non-linearly so you only need a bit over 70 for EV. Going for the efficiency increase by supplying all at least 5 centivis of all six aspects drops the single aspect centivis by about 8 points, but looking at this without some really amazing setups (1500+ vis pre-energize) you'll be needing quite a few dedicated energised nodes to keep up later in. They will need to be dedicated too, the magic absorber will happily consume several hundred centivis of all the types at once from what I can see.

You can configure a multiplier for vis EU output (default is 1/25000 I think) and actual EU output for ender crystals and dragon eggs anyway, so you should be able to configure dragon eggs to only produce at most MV levels of power for instance assuming I'm reading the code right.

**Comment by Blood-Asp** [comment]
The Magic Energy Absorber is balanced against default Thaumcraft where it is a lot of work to grow a node enough to be usable. Also the Dragonegg should be a one time use per server. Default option is at last that a second Egg lets the generators explode.
Finally the build costs of the Absorbers are quite endgame and should allready be infinior to other types of powergen.
So i will not do anymore nerfing there. If other mods throw of the balance, it is the job of the modpack author to make the absorber less efficient and/or more expensive to craft.
