### ISSUE TITLE
Magic Energy Absorber calculating efficiency incorrectly

### ISSUE THREAD

**Issue by Xavion3** [Blood-Asp/GT5-Unofficial#486]
Currently fails to account for efficiency being an integer, giving 100x EU production for dragon eggs and centivis that are affected by efficiency. In addition enchanted items ignore efficiency altogether.

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/20201d069a2de9c0684be69b3353df89a0781e9c
