### ISSUE TITLE
Achievement trigger quirks

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#488]
1. The achievement "Better Circuits", described as "Get Good Circuits" in the tooltip, did not trigger upon the assembling machine completing an operation to make a good circuit or upon manually transferring the circuits from the machine output to player inventory.  After dropping them on the ground and picking them up, it finally triggered.  This does not seem like a sensible trigger for the achievement.
2. The aluminium achievement, last I checked, only triggered when using aluminium dust in the EBF, even though it is somewhat faster and takes significantly less EU per ingot to process gems or dust (ruby, sapphire, or green sapphire) into nuggets and combine those into ingots.  If the EBF requirement for aluminium is disabled in the configs, that makes it impossible to get this achievement and cuts off several others.
3. The achievements "Crushed" and "Clean" can be triggered when mining small ores, without performing the actions described in their tooltips.
4. The achievement "Maintenance" triggered upon using a soldering iron in the maintenance hatch of a rebuilt EBF (moved, replaced LV energy hatches with a single MV energy hatch, replaced LV output bus with MV output bus), even though there were still other problems to perform maintenance for.

**Comment by githubuser28394** [comment]
1. The achievement "Oil Plant", described as "Start up a distillation Tower" triggered upon starting up a multi smelter

**Comment by Blood-Asp** [comment]
For the most points here, there is no way to fix them since there are no events to check. For example triggering on machineoutput is annoying enough for multiblock machines. 

The Distillatin Tower achievement triggering wrongly is the only one really annoying me.

**Comment by MauveCloud** [comment]
Okay, here's a new one I just ran across today: I got the achievement "Bad Weather" (legit, I left out a basic gas turbine powering a a BuildCraft filler without putting a roof over it), but the resulting explosion seems to have also triggered the "Electric Problems" achievement (which is supposed to be for an overvoltage explosion).  Looking at https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java#L1093 , I'm having trouble determining whether the formula is correct.

**Comment by Blood-Asp** [comment]
The code for explosion from other explosion or overvoltage in the same block seems to be combined. Not worth the work for me the seperate that...
