### ISSUE TITLE
Neutronium durability(Done) -> Wormhole Idea

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#489]
Current Neutronium tools and turbines durability does not offset EU, material and infrastructure cost of production.

To give an order of magnitude.
A Neutronium turbine is only 16 times more durable than best HS Steel same size turbine.

Crafting that turbine cost a full stack of Neutronium ingots.
That is 1,087,163,596,800 EU @98604EU/t + 600,000,000 EU startup Or 1,087,763,596,800 Total EU
Plus cost of getting and processing 1024 NqX Naquadria and 1024 Americium ingots.

I'd give Neutronium infinite unbreakable durability.
it cost so much to produce, once you have it; you deserve to keep it forever, unless it gets destroyed by mishandling/explosions... (any kind of Minecraft mishap).

That would make this Neutronium production the ultimate material and target for players.

Additionally, I'd create all Machines at Max tier, with Max processing speed but without over-clock penalty.

Those Max machines are only crafted with Neutronium.  So unless you already developed it or have proper infrastructure; it cannot break balance.
If you are at Neutronium, you are now more concerned about refining optimising your infrastructure than getting more tech around.

**Comment by yznpku** [comment]
According to https://docs.google.com/spreadsheets/d/1ypolb7s6aLHTMSyClcbFxEPIlYP19qZGNUgDUOqpP4Q/edit#gid=1713677046, it takes you 10 months' continuous playing to break a neutronium rotor, by which time you should have been swimming in neutronium I guess (and you DO DESERVE an achievement for breaking that rotor).

But IMO neutronium and that ultimate battery are just placeholders now. Gregtech does need more end game contents.

**Comment by DerEchteLanger** [comment]
It takes 10 months with steam, the durabilitys of rotors in plasma generators is way, way lower. I doubt anyone would use neutronium for steam energy...

**Comment by leagris** [comment]
Neutronium needs special case for damage exempt on anything made of it
Gregtech registers other materials that have no in-game use or source, but could constitute intermediate high tier very durable materials that last 32× 128× longer than HSS-G if there is an infinite durability Neutronium.
These are [Duranium](http://memory-beta.wikia.com/wiki/Duranium) and [Tritanium](http://memory-beta.wikia.com/wiki/Tritanium). Looking at these materials stats, they are currently quite weak.
They should take the durability slot and higher of current Neutronium version, while using simpler resources in their fabrication. (no [Naquadah](http://stargate.wikia.com/wiki/Naquadah) please, but manufactured material compounds made of simple elements found in quantity, but with a complex industrial process or at least some Mk2 fusion).

**Comment by mura3277** [comment]
@leagris So I have been thinking about this for a while and I think it would be really really interesting if we combine your new reactor idea (https://github.com/Blood-Asp/GT5-Unofficial/issues/504#issuecomment-215588831) and implement a better use for neutronium.

So as a result of your (really cool) idea we could have an ultimate density fuel that requires a "max generator" and we can have this new generator require neutronium in some way.

**Comment by leagris** [comment]
Firstly, there is currently no anti-matter in Gregtech, and this would be required to produce an anti-matter reactor.
I have read months/1 year ago, @GregoriusT mentioned Anti-matter as a projected addition.
Now it raise its set of issues.
RealWorld have multiple kinds of anti-matter See: https://en.wikipedia.org/wiki/Antimatter
For the sake of simplification, it could be a unique fluid type, a soup of anti-protons or positrons, or even some anti-UUM fluid.
Anyway it has to be defined.
Then you have to move transport this anti-matter. How?
None of the existing pipes can or should be appropriate.
It has to be something very high-tech with an active field (magnetic?) to avoid contact with standard materials.
Maybe pipes made of fusion coils and casings. (OMG cost).

Another problem. Producing anti-matter costs an insane amount of energy. In reality it probably cost more energy to build a single particle of anti-matter that can be recovered by reacting that anti-particle with matter.

So where do you get anti-matter from?

Lets continue with StarTrek fantasy then: http://memory-alpha.wikia.com/wiki/Antimatter
Then get anti-matter by opening a wormhole into a parallel universe made of anti-matter.
Using a special wormhole device that need high amount of energy to sustain maintain that opened and huge amount to open it.
Lets design a vertical disk the diameter of the fusion tokamak, center block is made of anti-matter transport pipe. Outer ring made wormhole field generators.

This has all to be weighted for decent game-play, not too op, not too impossible while maintaining incentive to use this.

Once you have anti-matter, transport, sourcing, you can start thinking about anti-matter reactor with dilithium crystals stabilizers and all the fluff of Max power.

**Comment by mura3277** [comment]
Yeah there would be a lot of content, mechanics and balancing to figure out to add everything.

But I'm definitely interested in attempting to add this. However this is @Blood-Asp's fork so we will see once he is around what he thinks about this and what direction he wants to take it. 

Greg himself might even let us know if he had any more plans for antimatter :+1:

**Comment by GregoriusT** [comment]
Antimatter related things are indeed planned. How I will do it is
however not set in stone yet.

**Comment by mura3277** [comment]
@leagris Are you describing something like this?
![image](https://cloud.githubusercontent.com/assets/7321570/15588687/f944cf56-2386-11e6-9cea-19f8b32b2236.png)

The radiation casing being "antimatter" casing and the UV energy hatches "wormhole field generators" and of course the antimatter transport pipe.

I thought having a radiation proof casing was interesting since we don't want to leak cosmic radiation into our wold (Lol). Also having insanely powerful magnetic coils (where the fusion coils would go) would be a good idea to "contain" everything.

**Comment by leagris** [comment]
Something like that but with Portal field when active.
Anything touching the active portal is instantly annihilated. (Because until matter creatures finds a mean to travel and live in the anti-matter dimension, this is what it is.
Add an entity pull effect like with Thaumcraft Hungry nodes and you have something no one would like to approach while active.

Maybe the mean of siphoning anti-mater through this wormhole portal is to send matter, but if you don't care of sending stuffs, that drag sucking force will help itself and suck surrounding content matter ;D

**Comment by mura3277** [comment]
So I have refined the structure a little:
![image](https://cloud.githubusercontent.com/assets/7321570/15636582/e23a2e2e-25fb-11e6-8db5-e2cf2167f80b.png)
 Wormhole casing as main casing
Energy injectors in fusion location (all 8 needed)
12 Wormhole generators
1-4 Input hatch (Can maybe be used for a liquid for "stability")
1 wormhole siphon in center (Where the antimatter collects)
Currently uses fusion coils inside the casings (possibly some extreme magnetic coils?)
And eventually, end portal textured blocks (hopefully) in the middle of the structure

@Blood-Asp, what do you think of the whole idea? refer to the past two posts by @leagris and this initial idea here: https://github.com/Blood-Asp/GT5-Unofficial/issues/504#issuecomment-215588831

**Comment by Blood-Asp** [comment]
Improved Neutronium by a lot for being the best endgame material. 4x speed/damage/flowrate. 16x dura. https://github.com/Blood-Asp/GT5-Unofficial/commit/e340d1733739da237163536d9a8f988245b6e0eb
That Wormhole thing might sould interesting, but unlikely that i will still do that much work on GT5U. Maybe someone else want to. There were quite a few PRs in the last few months.

//Edit: Should read it all before posting... Sounds like @Muramasa- is already working on it, right?

**Comment by mura3277** [comment]
@Blood-Asp Yep, I'm working on trying to design an antimatter age with the help from a couple people.

However it's probably best to close this issue or change the label to "fixed in dev" since I'll be submitting a more structured and probably a very different design breakdown as it's own issue sometime soon.

**Comment by Blood-Asp** [comment]
Good, will let this open until you make a seperate issue.

**Comment by Nex4rius** [comment]
So this will be a Stargate-like device thats producing antimatter?

about the fluid antimatter:
Could you make it that it can only be transported in the "antimatterpipe" and not in all the other extremely cheap pipes from other mods (e.g. bc waterproof pipes, enderio conduits)?

**Comment by mura3277** [comment]
That was the plan yes, but I think I'm going with a route that revolves around more science fact since a wormhole wouldn't really follow the GT philosophy.

**Comment by Georggi** [comment]
@Muramasa- Hey, any progress on anti-matter?

**Comment by mura3277** [comment]
@Georggi Not a lot of progress code-wise due to currently working on the Materials System, but I do have a clear idea of how it will work.

**Comment by FreeGMan** [comment]
@Muramasa- How about something like this:
1) Get antimatter in multiblock WormHole stucture (Antimatter is lquid, like UUMatter)
2) Antimatter pass through special pipes in reactor (generator). 
3) In reactor - Antimatter interacts with UUMatter.
4) Antimatter and UUMatter annihilate each other, and produce Energy (the energy produced by the interaction of substances and generated due to high-energy photons)
