### ISSUE TITLE
Gregtech centrifuges no longer process Forestry products

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#49]
Due to a recent change in Forestry to [Improve the probability system for centrifuge outputs](https://github.com/ForestryMC/ForestryMC/commit/e70d5981890af187def19e089baf6774f11716e8)  Forestry centrifuge recipes are no longer handled by GT5U centrifuges.
https://github.com/ForestryMC/ForestryMC/issues/703

**Comment by traeger** [comment]
link is dead, here is properly the right one: https://github.com/ForestryMC/ForestryMC/issues/703

**Comment by leagris** [comment]
Updated links

**Comment by Blood-Asp** [comment]
fixed in 5.08.20
