### ISSUE TITLE
machines exploding in rain

### ISSUE THREAD

**Issue by Nex4rius** [Blood-Asp/GT5-Unofficial#490]
You can submerge your machines in water to protect them from the rain :)

**Comment by leagris** [comment]
Removing paint from a machine require right-clicking with a water bucket. I remember @GregoriusT letting machine safe against water blocks, or it would be an issue risking a machine explosion while washing out paint.

**Comment by Nex4rius** [comment]
Removing the paint doesnt actually place a water source block.

**Comment by leagris** [comment]
If you click on an un-painted machine or double click a painted machine by accident, it will indeed place a water source.
Lag or failing mouse button will cause such issues.

**Comment by GregoriusT** [comment]
someone mentioned me? simple explanation here:
Water Blocks => Okay, you actually wanted that water to be there.
Rain => Bad, lets Machines explode because you were stupid enough to
place them outside.

And the water bucket thing can be solved by I think just fixing the
onblockactivated in the basemetatileentity

**Comment by Technus** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/blob/6e0f90964ec2b6d7b436fb5b9bc0c1e0b09be0bf/src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java#L1154

Line of code responsible for cleaning.

**Comment by GregoriusT** [comment]
that is not the only line you have to take into account, but I dont
know how far that bug goes

**Comment by Blood-Asp** [comment]
Well, will take a look at the bucket issue. The main point of this issue will stay as it is.

**Comment by Blood-Asp** [comment]
Do not see any issue here. Bucket does not get placed when cleaning the machine. Only shift clicking agains clean machine places bucket what should not be an issue.
