### ISSUE TITLE
GT_Tool_Scoop does not implement IToolScoop

### ISSUE THREAD

**Issue by AnrDaemon** [Blood-Asp/GT5-Unofficial#492]
GT_Tool_Scoop does not implement IToolScoop, making it useless as a scoop.
Refer to https://github.com/MagicBees/MagicBees/blob/master/src/main/java/magicbees/item/ItemThaumiumScoop.java for example, if you need one.

**Comment by AnrDaemon** [comment]
And https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/lepidopterology/entities/EntityButterfly.java#L374-L385 for references.

**Comment by Blood-Asp** [comment]
It is https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/items/GT_MetaGenerated_Tool.java that must implement IToolScoop. This class means every tool from GT implements it at the same time. So to make this work correcly there must be a method to check if the tool is truely active and working. There is no such method https://github.com/ForestryMC/ForestryAPI/blob/master/forestry/api/core/IToolScoop.java , so adding it will not work correctly.

**Comment by AnrDaemon** [comment]
May be I'm missing something, but I only see it implementing IToolGrafter.
Did you link correct class file?

**Comment by Blood-Asp** [comment]
I told you that IToolScoop can not implemented in GTs metatools, there is no way to make it work only for the scoop. The Grafter is there because it works.
