### ISSUE TITLE
Suggestion: Make GC asteroid blocks yield something valuable

### ISSUE THREAD

**Issue by DerEchteLanger** [Blood-Asp/GT5-Unofficial#494]
Its strange that moon dust and mars stone yield usefull stuff, while the asteroids are only decorative. Some have an ore core, but thats not realy usefull. They could yield rare metalls like platinum or larger amounts of iron or carbon...

**Comment by Blood-Asp** [comment]
That would be a part of GalacticGreg. But still i will try to remember this.

**Comment by mura3277** [comment]
Rare earth could be a good fit since you can get it from AE Sky Stone Dust which is essentially a meteor.
