### ISSUE TITLE
Input Hatch not accepting liquids when part of multiblock

### ISSUE THREAD

**Issue by githubuser28394** [Blood-Asp/GT5-Unofficial#496]
The input hatch refuses to accept liquid when part of an EBF, the EBF can use liquid in it, but i cannot put in new liquid, neither via pipes or via cells in the GUI
As long as it isn't part of a multiblock I can put in new liquid via cells or pipes and remove liquid via cells(haven't tested pipes).
All the hatches are MV. The EBF works fine otherwise as far as i can tell
Versions:
Forge: 1.7.10-10.13.4.1614
gregtech-5.08.33
industrialcraft-2-2.2.811
fastcraft
various other mods
i edited the black granite texture but i doubt that affects anything
![](http://i.imgur.com/UeKSUsN.png)

**Comment by leagris** [comment]
Because Universal Fluid Cells are unsupported?

**Comment by githubuser28394** [comment]
it doesn't work with gregtech's oxygen cells either and universal fluid cells DO work while it's not a part of the multiblock

**Comment by Blood-Asp** [comment]
Did you add another mod with oxygen after you started the map? For example Galacticraft is known for this issue.
The forge fluid list gets mixed up and GTs fluid blacklist fails. To fix this you need to delete the fluid list in the level.dat with NBTexplorer.

**Comment by githubuser28394** [comment]
I do have galacticraft installed so that's probably the issue. Thanks!
