### ISSUE TITLE
[Idea] Make Fluid Regulator less useless?

### ISSUE THREAD

**Issue by AiwendilCiunio** [Blood-Asp/GT5-Unofficial#498]
I tried my best and all I could get was 4 settings: full export, half export, full import, half import. Seriously? Name "regulator" in GT always meant a powerful, versatile thing, and this cover is pretty useless.

Could it be made more precise? With 1L/s or at least 10L/s treshold?

**Comment by Blood-Asp** [comment]
It works in 1L/t steps. As there are 20t per sec it can not be made more precise.

Saving more settings is also quite difficult for covers. There is just one single integer value to store any data. I could use negative values for one more setting, but not sure how exactly i would use that.

**Comment by Blood-Asp** [comment]
Why did i leave this open anyways?
