### ISSUE TITLE
Graphite dust smelting

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#50]
Its not possible to smelt Graphite Dust in the furnace into ingots.
if I will convert Dust into Small Piles, and put them into Alloy Smelter with Ingot mold, it smelts. So I suppose dust should be smeltable normaly as well. (Smelting raw ore also gives Graphite Ingot)

**Comment by JasonMcRay** [comment]
Oh and also would like to add, if I move the unification from GT Graphite to BR Graphite.

**Comment by Blood-Asp** [comment]
This must be something special happening with BR. GT alone only has Graphite Dust, no Ingots. Also more realistic for Graphite would be Compressing the dust into ingots instead of smelting.

Maybe i can at last do something when i do know the OreDic tags of BR Graphite.

**Comment by JasonMcRay** [comment]
Dust: dustGraphite
Ingot: ingotGraphite

**Comment by Blood-Asp** [comment]
Added a compressor recipe for dustGraphite -> ingotGraphite. I do not have BR installed so i can't test if it works, but it should.

**Comment by JasonMcRay** [comment]
If you are adding this recipe, are you also removing the smelting recipes for 4x Small Dusts inside Alloy Smelter + Plate Mold?

**Comment by Blood-Asp** [comment]
For now only adding a new recipe, but that the alloy smelter recipe gets added is likely a bug, so i should disable it too.

**Comment by JasonMcRay** [comment]
Tested the Graphite. It still doesnt work. After looking at it i might see the culprit why.
There is already a compressor recipe for 9x Graphite Dust => Graphite Block; this should be changed to 9x Graphite Ingot => Graphite Block.

If I am not mistaken you can't have multiple recipes using same input.

**Comment by JasonMcRay** [comment]
Also i see the Graphite tools from GT cant be made at all as well. Maybe do similiar thing as you did with EnderIO Dark Steel? Add GT version of the ingot?

**Comment by Blood-Asp** [comment]
You know that graphite, even pressed into form, is totally brittle and would even break when handled with care? Tools from that would not make sense... I would prefer: 9 dust into 1 block, 1 block in cutting machine cut into 9 ingots.

**Comment by JasonMcRay** [comment]
I would personally still prefer just the Dust into Ingot smelting :) But I guess we will all be satisfied with Cutting machine style. :p

**Comment by Blood-Asp** [comment]
5.08.21 now has cutting recipe.

**Comment by JasonMcRay** [comment]
I do not like that. Why?
1) I can smelt Oreblock directly to Ingot
2) I can smelt 4 small dusts in Alloy Smelter with Ingot Mold into Ingot

**Comment by Blood-Asp** [comment]
hmm, right. Forgot to remove the wrong recipes.
