### ISSUE TITLE
Brittle Charcoal and related blocks do not enforce tool levels

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#503]
While testing my changes for fixing #439, I discovered that mining brittle charcoal with a wooden tool (tier 0) or even with bare hands still drops charcoal.  Additionally, mining a tungstensteel reinforced block with an iron pickaxe dropped the block, even though it is supposed to require a tier 4 tool.  Might be related to #436.

**Comment by Blood-Asp** [comment]
So strange block mining behavior...
