### ISSUE TITLE
Turbine damage weight on EU/t is inappropriate for large Plasma

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#505]
Given a Large HSS-G Turbine rotor
Durability: 1200000
Efficiency: 130%

Large Plasma Generator output with Nickel Plasma and the above turbine is:
154419 EU/t

About every 3000 ticks, the turbine takes 20% of the EU/t generated damage.

So every 3000 ticks this Large HSS-G Turbine loose 30884 damage points out of its total 1200000
1200000 ÷ 30884 × 3000 = 116565 ticks in operation
Thats 5828 seconds or
1 hour 37 minutes 8 seconds 5 ticks
This is way too short a life time for a Large HSS-G Turbine

Now, lets repeat same computation with a Large Neutronium Turbine. This the most lasting material in Gregtech 5.09:
Durability: 24576000
Efficiency: 160%

Large Plasma Generator output with Nickel Plasma and the above turbine is:
95027 EU/t (less than HSS-G Turbine despite 160% Efficiency for Neutronium VS 130% for HSS-G

So every 3000 ticks this Large Neutronium Turbine loose 19005 damage points out of its total 24576000
24576000 ÷ 19005 × 3000 = 3879400 ticks in operation
Thats 193970 seconds or
2 days, 5 hours, 52  minutes and 50 seconds

Given a Large turbine cost 78 ingots of material + 1 ingot (long rod) of other material;
It takes 2 hours to create a single ingot of Neutronium in Fusion at 9kEU/t?

The durability of Neutronium Rotors can not even give back enough EU to pay for the fusion process alone. And I think it does not pay for replication cost either;

You scrap 78 ingots of the most hard, lasting and costly material in 2 days and few hours of operation.

Please @Blood-Asp the damage loss of turbines need new calculation or scales for Large Plasma Generators and the ridiculous life span of Neutronium turbine is another argument for https://github.com/Blood-Asp/GT5-Unofficial/issues/489

**Comment by Blood-Asp** [comment]
The correct Damage for turbines is:
`mInventory[1].getItem()).doDamage(mInventory[1], (long) Math.min(mEUt / 5, Math.pow(mEUt, 0.7)));`
So 20% of EUt OR EUt^0.7 whatever is smaller. So in the example of 155000EUt it is not 31000 but 4300 damage per damage cycle. So at last 7.2x as long.

Also, disassemble and reassemble you damaged turbine rotors for zero material usage(IV Disassembler) once you have them.

**Comment by leagris** [comment]
On Start, my Large HSS-G Turbine took 4286 damage points That's still roughly 12 hours of operation for Large HSS-G Turbine. Too short in my humble opinion. Such turbine should run for a full week without player interaction.

I did not know it could be disassembled because when I tried with a brand new unused turbine, it did not enter the disassembler. Now tried with a used turbine and it disassemble properly.

**Comment by Blood-Asp** [comment]
I could lower the damage calculation from EU^0.7 to EU^0.6. That would result in about 40h instead of 12h. If you want more without interaction, build multiple turbines and automate them to switch over once one is too damaged. The material costs for that should be not too bad anymore when you at that point. Or use turbines with better dura less speed for longer lifetime.

Also, Why HSS-G and not HSS-E that has 20% more dura?

**Comment by mura3277** [comment]
Isn't your EU/t calculation assuming the turbines input hatch is filled with fluid?

If you use the optimal flow your output would be half @77209eu/t but your rotors would last about 3x as long. So the solution is to build more turbines which aren't terribly expensive at your stage of the game. (More expensive in the next GT version however)

**Comment by leagris** [comment]
I calculated an optimal flow of 1L/t of Nickel Plasma:
(30000×40)÷59392÷20 ≈ 1.01 truncated to 1∈ ℤ
Is that correct?

Well, until I can work with Fluid Regulators Covers (See: https://github.com/Blood-Asp/GT5-Unofficial/issues/502), I can still use IC2 Fluid Regulator.

**Comment by mura3277** [comment]
So looking at the code:
actualFlow:  (((30000/20) \* 40) + 59392 - 1) / 59392 = 2.0102202316810344827586206896552

Now this is cast to an integer so I believe that it is rounded down so the optimal flow would be 2L/t

**Comment by leagris** [comment]
At 2L/t on the IC2 Regulator it still output 154419 EU/t with that little durability.

**Comment by mura3277** [comment]
Are you sure there isnt left over fluid in the hatch?

Edit: Never mind it was my mistake.

**Comment by leagris** [comment]
No Optimal flow displayed for Large Plasma Generators:
![2016-04-29_02 30 30](https://cloud.githubusercontent.com/assets/1111474/14905613/a06bc428-0db2-11e6-8344-713ad9975481.png)
![2016-04-29_02 29 22](https://cloud.githubusercontent.com/assets/1111474/14905619/a35984e0-0db2-11e6-9e9f-0813d426d12d.png)

**Comment by mura3277** [comment]
Sorry derp on my part. I was looking at the wrong part. Optimal flow is 1L/t.

I actually thought it was 1 too, but decided to look at the code again when you asked if it was correct the made a mistake.

**Comment by leagris** [comment]
Indeed at 1L/t it output 38604EU/t that's close the optimal flow 30000 × 130% = 39000 EU/t
98.48% of optimal flow is the best achievable here due to L/tick quantification.

**Comment by mura3277** [comment]
So to sum up:
Using Optimal Flow = Most efficient use of turbine rotor's life.

Ignoring Optimal Flow = Highest EU/t from rotor at a bigger rotor maintenance cost. So it would be best to ignore the Optimal Flow if your rotor is made from something that can be replicated like Osmium. And the EU/t cost to make the extra rotors is usually a lot less than the bonus EU/t from ignoring the optimal flow.

**Comment by leagris** [comment]
Rotors can be disassembled to recover all blades. The only part that's lost in Large turbine is the long Tungstensteel Rod that's worth an ingot.
The most annoyance caused by short lived rotors is player interaction requirement. Using more turbines also aggravate the situation where you spend more play time checking and replacing turbines at random short intervals.
If you run only one turbine with 12hours rotor life, you have to check every less then 12 hours and change rotor.
If you run 2 turbines, you have to do it twice every 12 hours... but your rotors may not die simultaneously, particularly if your energy consumption vary.
I have planned 12 large Plasma Generators. They will fill an ultimate battery and I will trigger charging cycles on thresholds. Large generators are to be run for extended periods of times to be worth it. Variable load on Large generators is a nightmare with randomized maintenance times.
I really don't need that much energy. There is this nagging tooltip on the ultimate battery. Win Gregtech by filling it entirely. It is a pretext to make a fancy looking power-plant.

**Comment by mura3277** [comment]
You can recover all the blades regardless of dura? isn't that a little OP?

**Comment by DerEchteLanger** [comment]
"build multiple turbines and automate them to switch over once one is too damaged."
How would that work?

**Comment by mura3277** [comment]
I think she means that you could have two turbines for example and when the first turbines rotor is 95% damaged it is turned off for the rotor to get repaired and the second on is turned on.

So the idea would be you always have a turbine running.

**Comment by leagris** [comment]
@Muramasa- wrote:

> So the idea would be you always have a turbine running.

Exactly

@Blood-Asp Given all what I could learn about turbines recycling issue looks less critical than envisioned. I still think durability is not long enough for industrial operation of Large Plasma Generators.

@Blood-Asp wrote:

> I could lower the damage calculation from EU^0.7 to EU^0.6. That would result in about 40h instead of 12h.

That's definitely better with 40 hours rather than 12.
It would be handy to experiment with different damage factors, without having to change Gregtech code but with a run-time option like:
`F:turbineDamagePowerEU_0.6=0.6`

It means turbine damages could be disabled entirely with 0.0.

I still think Neutronium needs special case for damage exempt on anything made of it https://github.com/Blood-Asp/GT5-Unofficial/issues/489#issuecomment-215698867

@Muramasa- It would be handy having real optimal flow displayed with scanner as in your now edited-out screenshot.
Is it already part of recent turbine casings re-balance?
I like it! :+1:

**Comment by mura3277** [comment]
It's not part of that since I forgot to add it, but I'll add it to the Diesel engine PR.

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/537d6e9330160f9d5d75b95bfd2153bc884a8207

**Comment by axlegear** [comment]
I agree and am glad this is fixed.  Just set up an HP and regular steam turbines for my nukular plant today and the HSS-E is already down 5% in just a few hours.
