### ISSUE TITLE
Typo:  Sufluric Naphtha

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#506]
Should be 'Sulfuric'.

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/aa922c5470a59e21397551223816210e9f44aeb2 long fixed, just not released

**Comment by MauveCloud** [comment]
Proof here: https://github.com/Blood-Asp/GT5-Unofficial/blame/experimental/src/main/java/gregtech/loaders/preload/GT_Loader_Item_Block_And_Fluid.java#L391
