### ISSUE TITLE
Advanced Miner II is magic

### ISSUE THREAD

**Issue by zaitsevyan** [Blood-Asp/GT5-Unofficial#508]
It always mines something interesting: NetherQuartz in overworld, crushed diamond ore at 40 lvl pipe, Ores that are not in current location of miner(huge amount of it, it is not small ores.), etc. I am using Infitech 2 modpack.

**Comment by Blood-Asp** [comment]
What seems to happen is, that multiple miners in one world seem to link up and share found materials...

**Comment by DerEchteLanger** [comment]
Thats not the case, on the official server we are the only one with such a miner and still got even naquadah in the overworld...

**Comment by zaitsevyan** [comment]
@Blood-Asp There was only one miner in the world.

**Comment by PaulMadsen** [comment]
I can confirm the ores are shared.  I am not sure, but it appears that they will truncate ores when they share it.  As if one will overwrite what the other is pulling up.  I have not tested this.  It just appears to be this way.

**Comment by SapientMC** [comment]
Seems like its same bug as https://github.com/Blood-Asp/GT5-Unofficial/issues/469

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/pull/533 maybe fixed?
