### ISSUE TITLE
project red / big reactor materials

### ISSUE THREAD

**Issue by Nex4rius** [Blood-Asp/GT5-Unofficial#509]
Big Reactor:
Yellorite ore doesnt have the full gregtech ore processing it only has 1 ore -> 2 dust recipe in a macerator.

I'm not sure if its useful or not but the yellorium, cyanite, blutonium and ludicrite ingots cannot be made into plates, rods and so on.

<ore:oreYellorite> <ore:oreYellorium>
<ore:ingotYellorium>
<ore:ingotCyanite>
<ore:ingotBlutonium>
<ore:ingotLudicrite>

ProjectRed:
Electrotine Ore doesn't have gt ore processing

<ore:oreElectrotine>

**Comment by mura3277** [comment]
The solution for ore processing is AOBD.

The solution for getting plates, rods etc would be to use GT unification to convert yellorium to uranium and blutonium to plutonium.

**Comment by draknyte1** [comment]
BR materials are already in the material enum, just gotta change the textureset and what you get from each i.e:cells/toolsparts/plates/etc and you're done..

The only problem is by default, unification will make BR recipes uncraftable.

**Comment by Blood-Asp** [comment]
Added to idea collection
