### ISSUE TITLE
Distillation tower overflow output items in fluid hatch

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#510]
Distilling Cracked Heavy Fuel:
Ase the output Bus becomes full of Tiny Piles of Hydrated Coal Dust
Tiny piles are output into the empty lower cell slots of fluid output hatches.

**Comment by Blood-Asp** [comment]
well, better than voiding items i guess. 

Also works for other multiblock machines and might even be desired in some setups.
