### ISSUE TITLE
[Suggestion] Ore processing

### ISSUE THREAD

**Issue by OneEyeMaker** [Blood-Asp/GT5-Unofficial#512]
Hello!
Firstly, thank you very much for your work!
Secondly, I have a suggestion about adding/removing processing recipes.
GregTech adds many ores, but not all ones have processing recipes (for example: mob drop ores, glowstone ore, etc.). But these ores can be useful on some modpacks.
If I understand correctly, GregTech registers ore in OreDictionary and adds processing recipes, only if type of material of ore contains specific flag, i. e.:

```
(aOre.mMaterial.mTypes & 8) != 0
```

I suggest to add specific configuration file to enable/disable processing recipes for specific ores.
It may be done, for example, [like so](http://pastebin.com/egB8SUa6).

If I understand incorrectly or you don't want to add this feature, please explain me why.
P. S. // Sorry for my English. I'm from Russia.

**Comment by MauveCloud** [comment]
@OneEyeMaker I'm curious: since you seem to know Java fairly well to make such a class for the example in the pastebin, why did you only attach it to the bug, instead of making a Pull Request?  If Blood Asp has a reason for not adding the feature, he can still decline a Pull Request if I'm not mistaken.

**Comment by OneEyeMaker** [comment]
@MauveCloud 
I didn't create PR only for one reason: (read first line of my code) _I don't know **where** to put this class_.
Structure of GT's packages is a mystery to me at some points/in some places.

**Comment by draknyte1** [comment]
@OneEyeMaker I'd say gregtech.loaders where anything else related to recipe loading goes.
Probably gregtech.loaders.misc, as I don't think it fits the classes within gregtech.loaders.oreprocessing

**Comment by Bogdan-G** [comment]
> Structure of GT's packages is a mystery to me at some points/in some places.

Part of the code mod is identical to the code decompiler, i agree that there is confusion in the source code.
