### ISSUE TITLE
Wierd bugged Assembler Recipe

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#514]
Gregtech 5.09.21

There are strange recipes in assembler with: Gregtech Batteries and IC2:itemCropnalyuzer to output null meta tiny dust
Format: ![Recipe screenshot](http://s32.postimg.org/cppaf58b8/bug.jpg)

Likely comes from:  https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/oreprocessing/ProcessingBattery.java#L16-L20

``` Java
    public void registerOre(OrePrefixes aPrefix, Materials aMaterial, String aOreDictName, String aModName, ItemStack aStack) {
        if (aMaterial == Materials.Lithium) {
            GT_Values.RA.addAssemblerRecipe(GT_Utility.copyAmount(1L, new Object[]{aStack}), GT_ModHandler.getIC2Item("cropnalyzer", 1L, 32767), ItemList.Tool_Scanner.getAlmostBroken(1L, new Object[0]), 12800, 16);
        }
```

Initial commit https://github.com/Blood-Asp/GT5-Unofficial/commit/9353aa711b1d750ff945acdfed2d3b956291b615 on  22 Oct 2015  by @ShawnBuckley

Possibly fooled by Ore Dictionary entry: `batteryLithium`

**Comment by MauveCloud** [comment]
Is this with mostly-isolated GregTech or in a modpack?  I don't find such a recipe with my manually-assembled modlist.

**Comment by leagris** [comment]
@MauveCloud Beyond Reality Classic ModPack

**Comment by draknyte1** [comment]
@MauveCloud the item is in the code for us all.
It's just not there because you're not oredicting things like @leagris is.

Removing the code snippet should have no ill effects, from what I can tell.

**Comment by Blood-Asp** [comment]
From what i can see it is dead code that got active again when adding GT batteries to oredict in your pack. GT itself does not have that recipe.

Removed that useless line of code anyways. https://github.com/Blood-Asp/GT5-Unofficial/commit/87ef0280f033f789fa0bfb176805520496d9c093
