### ISSUE TITLE
Curing Oven liquid support.

### ISSUE THREAD

**Issue by mura3277** [Blood-Asp/GT5-Unofficial#516]
So when I seen you were adding this machine, I thought it would be the perfect machine to implement Tinker tool repairing via GT. 

Now I'm not saying I want you to implement this(I'll be taking a crack at it in my own little mod, however you're more than welcome) but it would be really handy if the Curing Oven had a tank so it accepted liquids so if I get this done, I could repair tools with liquids. A second inventory slot (This might be planned anyway?) would also be really nice so it can support repairing with ingots.

I suppose this is also an interesting mechanic to repair GT tools by "adding new material" to the tool, and re-hardening it or something.

Anyway let me know what you think.

**Comment by Blood-Asp** [comment]
Added to idea collection
