### ISSUE TITLE
Sever ticking and extreme lag

### ISSUE THREAD

**Issue by Xireka** [Blood-Asp/GT5-Unofficial#519]
SO I added Gregtech 5 unofficial to my custom modpack.

First java crashed when creating a new world due to not enough heap space.

Afterwards I managed to enter the newly created world but my FPS was between 1 and maximum 8.

I used shift+F3 to check the root usage and 90% or more were ticks from somewhere.

The tick graph (the one going from left to right) was covering my entire screen in white.

Any help as to what I could do to solve it?
I'm guessing it's the massive ore veins causing the issue but no idea what to do to fix it so I'm turning towards you in hope of finding a fix.

Thanks in advance for the help :)

**Comment by MauveCloud** [comment]
> I'm guessing it's the massive ore veins causing the issue

That's highly unlikely, as those of us more familiar with GregTech know that the ore veins are composed of **non-ticking** tile entities.

Also, question: does this extreme lag last more than 5-10 minutes after creating the world?  If not, it's probably just caused by GregTech's recipe initialization, and afaik nobody has figured out a way to prevent that lag, but since it usually only lasts a few minutes upon world creation, it's not generally that big a deal.

**Comment by Xireka** [comment]
Oh okay sorry about thinking it's the ore veins :(

Recipe initialization after the world launched?

Cause the lag comes from the ticking, so if you say that that causes lag and ticks, then I'll try again cause I didn't know that it did that and I'll try waiting 5-10minutes then.

**Comment by MauveCloud** [comment]
Lag on startup has been a known issue for a while, since it's in the Q/A (which is at http://files.minecraftforge.net/maven/com/gregoriust/gregtech/qa.txt):

> Q: REMOVE THOSE USELESS ITEMS, THEY LAG THE HELL OUT OF MY STARTUP!!!
> A: Okay that isn't actually a Question at all, but no, I won't remove them since I rely on them. Also it is the Recipe System doing that and not those Items, if you have an Idea on how to improve that System then fine tell it to me, but don't complain about those Items, because I will not remove those.

I'll admit I'm not sure the mentioned Recipe System causes ticking, so it could be something else.

**Comment by Xireka** [comment]
But it started when I added Gregtech, so maybe it is indeed the recipe thing, no idea :/

Although the weird thing is that after seeing the massive lag at first I deleted Gregtech, the configs, and now my old existing world ticks as well :/

**Comment by Blood-Asp** [comment]
GT alone has close to zero reasons why it should lag in a new world. There are plenty of reasons of it having with other mods. But in that case you have to find out yourself what mod is actually causing the lag. The currently listed reasons do not help in finding the issue.

I can only say that it is most likely not GT (alone) causing this.
