### ISSUE TITLE
Unification not dynamic/caching too soon?

### ISSUE THREAD

**Issue by Timeslice42** [Blood-Asp/GT5-Unofficial#52]
I want Pam's Harvestcraft salt to be used for food, and GT salt to be used for GT. I noticed that the PHC recipes use <ore:foodSalt> and the <harvestcraft:saltItem> belongs to that entry. Using minetweaker I've removed the PHC salt from the dustSalt and itemSalt entries so that it only has foodSalt, but it still gets unified into the GT dust salt. The unification file doesn't have an entry for foodSalt, and the GT dustSalt and PC dustSalt are both set to false.

I figure that the unification caching is happening before MT is changing the ore dictionary entries. If this can't be fixed then I would need a (new?) config section for blacklisting an item from unification, as I want PHC salt and GT salt to be two seperate entities.

The GT salt still works in PHC recipes, which is fine, but I don't want to be making batteries out of the PHC salt.

**Comment by Blood-Asp** [comment]
registering the removal of oredic tags is not possible code wise, or at last really difficult for GT.
Adding oredics later on is possible, but the cached unification list inside GT must be rebuild every time, so it should lag quite a bit when MT adds oredic tags.

**Comment by Timeslice42** [comment]
So would it be that hard to add a new section to the unification config file where we could list oredict tags where items with that tag won't get unified?
