### ISSUE TITLE
Low-tech fluid tanks?

### ISSUE THREAD

**Issue by mura3277** [Blood-Asp/GT5-Unofficial#520]
I'm thinking about adding 3 low tech GT fluid tanks that are made from Steel(32B), Titanium(64B) and Tungstensteel(128B).

What does every one think about this?

**Comment by leagris** [comment]
There are already large cells (steel and tungstensteel) that can be stacked and stored into an item container.
If you use large cells wisely, they can even transport fluid more efficiently than most lower fluid pipes.

Large Steel Cell 16000 Liters
Can stack 16
A Brass Item Pipe (Normal) can transport 1 Stack/s
So this low tech item pipe can transport 16 Large Steel Cells per second
or 256000L/s
The most advanced fluid pipe is Large TungstenSteel and transport 48000L/s
Now guess witch transport pipe wins for fluid rate?

Well back to your low tech tanks.
They already exist.
Place a simple fluid pipe ;D

**Comment by MauveCloud** [comment]
> The most advanced fluid pipe is Large TungstenSteel and transport 48000L/s

That's huge tungstensteel rather than large, but you're forgetting the large high pressure fluid pipe (192000 L/s), though admittedly it still loses to your calculation for a brass item pipe carrying large steel fluid cells (effectively 256000 L/s).

**Comment by mura3277** [comment]
Yeah thats a good point about large cells. The point of this idea is I really like the extrautils drums as they are really convenient to place and dump random fluids out of cells. These wouldn't have a GUI and you would just right click filled and empty cells to transfer fluid.

I really like the idea of having a GT version and more of them made out of different materials.

**Comment by leagris** [comment]
I'd really like an option to move quantum storages with content.

As for low tech tanks with interfaces, in Gregtech 3-4 you could use Fluid Hatches.

Pipes can also be used as low tech tank as they have a fluid content.
Now, pipes have no interface. Maybe make use of Computer screen cover on pipe block to enable a fluid interface where player can fill/empty with fluid container items (cells, buckets...)

**Comment by Blood-Asp** [comment]
Feel free to add such fluid tanks. But to have them usefull they should be possible to pick up without using the fluid inside and also a bit bigger i guess (2-4x).

There is actually an addon for GT adding such tanks (and a treefarm besides other stuff). I do currently not remember the name, but it was in one of the last GT5 videos from bear989
