### ISSUE TITLE
Diesel Fuel Now unbalanced comparison to light and heavy fuel

### ISSUE THREAD

**Issue by spacebuilder2020** [Blood-Asp/GT5-Unofficial#521]
So I made an issue at BeyondRealityModpack and @leagris requested I make an issue here.
Here is the original issue:
https://github.com/Beyond-Reality/BeyondRealityModPack/issues/406#issuecomment-221860754
In a nutshell, Diesel can be crafted from light and heavy fuel but has a burn time that is less than both of them.
 Given #500, @leagris suggested that diesel fuel and nitro diesel fuel value be raised since even 256,000 eu/t is under-powered even at high efficency when your goal is EV/IV

Edit:
Nitro-diesel is fine (It is 512,000)

**Comment by Blood-Asp** [comment]
normal "diesel" is only left there for compatibility with other mods. GT only you should use light/heavy/nitro fuel.

**Comment by spacebuilder2020** [comment]
ok
