### ISSUE TITLE
Processing array not outputting certain recipes

### ISSUE THREAD

**Issue by toawa** [Blood-Asp/GT5-Unofficial#522]
Discovered bug in Infi Tech 2 v3.2.3. Reproduced bug in clean install with only GT 5.09.21, IC2 2.2.819, Forge 1614.

It seems that certain electrolyzer recipes do not properly output their products when performed in a processing array.

To reproduce (as I discovered it)

Make a processing array, with EV energy input, LV input bus, MV output bus, HV input hatch, EV output hatch. Put in one (or more) MV electrolyzer. Put 7 sulfuric acid cells in the input hatch.  The processor will take them and start working (however, if you only put in 7, when it takes them, it will leave a phantom cell in the input bus. This cell can be removed, but will disappear if you try to drop it or add it to a stack of cells).  The processing array will finish, and no outputs will be available in the output bus.  I've confirmed this happens with

7 sulfuric acid cell -> 2 H cell, 4 O2 cell, 1 sulfur, 1 empty cell
3 CO2 cell -> 2 O2 cell, 1 carbon, 1 empty cell

I've confirmed this does not happen (outputs are as expected) with

9 nickel sulfate (liquid) + empty cell -> 8 sulfuric acid (liquid) + nickel dust + O2 cell
2 monazite dust -> rare earth + sulfur.

(Nothing special about those last two, just two recipes I successfully used before finding the above bug).

**Comment by Divran** [comment]
Not sure if it's the same bug, but in InfiTech 2 v3.2.12 I've run across a similar issue. Specifically macerators in processing arrays and centrifuges in processing arrays (i've not yet had any issue with electrolyzers). What happens is I put items in, they get processed, but nothing comes out at all. In addition, the macerators will leave one ghost item behind in each input slot. I can pick up this ghost item and move it to my inventory, but if I try to stack them, only one remains, and I can't place the ghost items on the ground as that deletes them.

So far I've seen it happen with copper ore, rock salt ore, salt ore, and a few others which I can't remember right now unfortunately. If I see any more I'll add them to this list.

Very strange glitch indeed.
EDIT: After reading the first post again, this really does sound like the same bug.
