### ISSUE TITLE
Missing machine support from Processing Array

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#524]
Looking at the code for the Processing Array, I see the following single-block processing machines are not supported (yet), and in most cases it's not clear why:
- Amplifabricator (maybe because PA support for UUM-related machines is overpowered?)
- Brewery
- Canning Machine
- Cutting Machine
- Disassembler (admittedly, most of the things one puts in a disassembler wouldn't stack)
- Distillery (maybe because there's the distillation tower multiblock)
- Electric Furnace/Oven (maybe because there's the multi smelter)
- Fermenter
- Fluid Canner
- Fluid Extractor
- Fluid Solidifier
- Forming Press (related machines Laser Engraver and Assembler are already supported)
- Lathe
- Mass Fabricator (maybe because PA support for UUM-related machines is overpowered?)
- Microwave (again, maybe because of the multi smelter)
- Packager
- Polarizer
- Printer
- Rock Breaker (special requirements regarding adjacent water and lava might be impractical for Processing Array to check)
- Replicator (maybe because PA support for UUM-related machines is overpowered, and because PA has no way to handle extra slot for data orb?)
- Scanner (probably impractical; even setting aside the data orb slot, most items to be scanned don't stack)
- Slicing Machine
- Unpackager

**Comment by Dream-Master** [comment]
We had the same problem and add all/some of those machines to the code.

https://github.com/GTNewHorizons/GT5-Unofficial/commit/0d1ac677da84a09607425bd89d91d74af357095c

**Comment by Blood-Asp** [comment]
Amplificator, Disassembler, Electric Furnace, Mass Fabricator, Microwave, Printer, Fluid Canner, Forming Press, Rock Breaker, Replicator Scanner: Special code, not possible.

All others Added. https://github.com/Blood-Asp/GT5-Unofficial/commit/7424f75315f691fb18f2c8404751dcfd9356f152

**Comment by MauveCloud** [comment]
I'm not too surprised about the Amplifabricator, Disassembler, Mass Fabricator, Printer, Rock Breaker, Replicator, or Scanner.  Also, I can understand the Microwave - it has special code to make it ignite/explode if certain materials are inserted.  However, what's so special about the Electric Furnace, Fluid Canner, and Forming Press that they can't be supported in a Processing Array?

**Comment by Blood-Asp** [comment]
The Furnace is using the Vanilla furnace recipes system and not the GT recipe system.
Fluid Canner does not use recipes, but fluid container + fluid calculations and Forming Press is for some reason coded seperatly but i can't explain that myself.
