### ISSUE TITLE
Please move bee species registration earlier than postinit

### ISSUE THREAD

**Issue by bdew** [Blood-Asp/GT5-Unofficial#525]
Currently you are registering your forestry bee species in postInit, this make them problematic to use from Gendustry custom mutation configs.

I'm processing the mutation in Gendustry postInit and if Gregtech postInit fires after Gendustry - user configs can't use GT species. There is no way i can control the order of lifecycle events AFAIK (i've tried adding after:gregtech to my dependencies and it seems to only change load order, not events).

Could please move bee species registration to an earlier event?

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/f2525afb8df6ef1c4ba7424fe3264be32b8d993b
