### ISSUE TITLE
wrenches don't work properly as bc wrenches

### ISSUE THREAD

**Issue by Nex4rius** [Blood-Asp/GT5-Unofficial#527]
The gt wrench doesn't seem to work properly as a bc wrench.
- shift right click enderio blocks (conduits / machines) doesn't work
- shift right click applied energistics(+addons) blocks doesn't work
- shift right click on a drum doesn't work
- shift right click on gendustry machines doesn't work
- (shift) right click on pneumaticcraft machines doesn't work
- (shift) right click on galacticraft machines doesn't work
- right click enderio blocks (to disconnect 2 conduits or change input/output) doesn't work
- right click to rotate bc blocks works but its opening the gui (doesn't happen with bc wrench)
- right click on me interface to change output direction works but its opening the gui (doesnt happen with bc wrench)

I've tested that on a server in InfiTech 2 v3.2.9 with the following mods.
- appliedenergistics2-rv3-beta-6
- buildcraft-7.1.16
- EnderIO-1.7.10-2.3.0.425_beta
- extrautilities-1.2.12
- PneumaticCraft-1.7.10-1.12.7-150-universal
- GalacticraftCore-1.7-3.0.12.460
- gendustry-1.6.4.135-mc1.7.10
- gregtech-5.09.21

Additionally it would be really cool if the gt wrench also worked like the yeta wrench so you can look through enderio facades while holding it.

I opened this new issue because https://github.com/Blood-Asp/GT5-Unofficial/issues/236 was already closed since 1 Nov 2015.

**Comment by Blood-Asp** [comment]
Added EnderIO Support and fixed a small bug. https://github.com/Blood-Asp/GT5-Unofficial/commit/96607760e1903eb34c535ab7f7756e5f27a8910d
Seems i have to add support for other wrench apis also if i want them working... and that seems a bit too much work too me. Maybe most of this will now work.
