### ISSUE TITLE
Unifcating ExU stable ingots -> unstable ones

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#529]
An issue with gegtechs uification, not sure if modifiable though, but making an unstable ingot with nuggets should make a "safe ingot" but greg converts it to the deadly kind

oredict entry: ingotUnstable

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/1ace2c4e35b21da7fc1070f3df24299a5892e498
