### ISSUE TITLE
Fluid items icons for mutual fluids with IHL are displaying "missing icon" texture

### ISSUE THREAD

**Issue by Foghrye4** [Blood-Asp/GT5-Unofficial#53]
It seems that mutual fluids (such as sulfuric acid and glycerol) displayed incorrectly.
GT fluids that are have not mutual fluid registry entry displayed correctly, and as well IHL fluids without GT analog.
This is how fluid icons registered in IHL now:
	public static void registerIcons()
	{
		Iterator<Fluid> ii = fluidInstances.iterator();
		TextureMap iconRegistry = Minecraft.getMinecraft().getTextureMapBlocks();
		while(ii.hasNext())
		{
			Fluid instance = ii.next();
			IHLFluidType instanceType = localFluidRegistry.get(instance.getName());
			if(instanceType!=null)
			{
				instance.setIcons(
						iconRegistry.registerIcon(IHLModInfo.MODID + ":" + instanceType.textureName + "Still"),
						iconRegistry.registerIcon(IHLModInfo.MODID + ":" + instanceType.textureName + "Flowing")
						);
			}
		}
	}

**Comment by Blood-Asp** [comment]
Took me some time to look at this, but it seems like all fluid icons are there with the most recent IHL version. Did you fix that on your side?

**Comment by Foghrye4** [comment]
Not sure. May be i simple forgot to test new way of registering fluid icons, written above. If so, sorry for bothering.
