### ISSUE TITLE
Damaged vanila tools

### ISSUE THREAD

**Issue by Leytek** [Blood-Asp/GT5-Unofficial#530]
GT machines accept damaged vanilla tools via GUI, but it's not possible to put damaged tools in machine through pipes, hopper or other stuff.

**Comment by Nex4rius** [comment]
You can put **anything** into a machine via gui.
Input via pipes works differently they only accept items that the machines can process.

**Comment by Leytek** [comment]
I mean GT machines process damaged vanilla tools, but accept them only via GUI.

**Comment by MauveCloud** [comment]
Wait, which GT machines can process damaged vanilla tools?  I don't recall any that can, except maybe the recycler, which is a weird special case, since it doesn't exactly "process" the items.  I'm not sure there are even any that can process freshly-crafted vanilla tools.

**Comment by Nex4rius** [comment]
> I'm not sure there are even any that can process freshly-crafted vanilla tools.

Macerator? Arc Furnace?

**Comment by Blood-Asp** [comment]
With automated input, all machines only accept items they can process. Manually everything can be put into the input slots, but then items without recipes will block that machine.

The recycler is the only machine that processes items that can not be inserted by automation. But these items do not return scrap but get simply voided.

Undamaged metallic vanilla tools and armors can be recycled. Once they have damage not anymore.

**Comment by leagris** [comment]
I think damaged vanilla wooden tools retains their fuelValue and should be an acceptable automated input in fuelboxes input hatches, and boilers..

**Comment by Leytek** [comment]
Ok, for example, i have iron axe with durability 0/256, and i can put it in macerator via GUI and get 3 iron dust. But why i can't push it into macerator via pipes, hoppers, ect...?

**Comment by yznpku** [comment]
https://github.com/JasonMcRay/InfiTech-1.7/issues/654

This issue may be related. Both are the cases that GT macerators will process the item but won't let it in by automation.

**Comment by Blood-Asp** [comment]
The issue is, damaged tools should not get processed at all. not the not working automation.
