### ISSUE TITLE
Dyed item pipe and machine doesn't work correctly.

### ISSUE THREAD

**Issue by EAirPeter** [Blood-Asp/GT5-Unofficial#532]
Why a dyed item pipe outputs items to a dyed machine which was dyed in another colour?
While fluid pipes don't.
For example, a blue item pipe shouldn't output items to a red chest buffer.

**Comment by EAirPeter** [comment]
p.s.
GT version: 5.08.33
IC2 version: 2.2.822-experimental
Forge version: 10.13.4.1614
MC version: 1.7.10

**Comment by Blood-Asp** [comment]
For now just use covers on your machine to seperate them. Will take some time till work in this.

**Comment by Blood-Asp** [comment]
Added to idea collection
