### ISSUE TITLE
[Compat] Add Practical Logistics support

### ISSUE THREAD

**Issue by Buuz135** [Blood-Asp/GT5-Unofficial#535]
Add extra mod support to [Practical Logistics](https://github.com/SonarSonic/Practical-Logistics) thorugh his [API](https://github.com/SonarSonic/Practical-Logistics/wiki/API-Documentation). It provides enough information about blocks but GT has very extensive information that it can't handle without [support](https://github.com/SonarSonic/Practical-Logistics/issues/76).

**Comment by Blood-Asp** [comment]
Could you give me some information what that Mod needs or how it does use it? I did not juse that Mod before and need some introduction.

**Comment by Buuz135** [comment]
The mod porvides Information Displays about everything possible, as shown here https://github.com/SonarSonic/Practical-Logistics/wiki , to monitor any block. Essentially a display monitor for everything. According to it's API, you only need to implement some interfaces and register them to add the information/energy type to it's mod.

**Comment by Blood-Asp** [comment]
Added to idea collection
