### ISSUE TITLE
Pipe clipping issue

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#539]
When walking across large pipes, sometimes you fall through partially and get stuck inside and can't escape or jump/walk out at all.

Usually happens wehn a floor is flush with a pipe, such as the huge coolant pipes in my reactor.

visual example:  ---=---
The = is a huge pipe and the --- is normal floor.  Seems more common when running over them.

**Comment by OvermindDL1** [comment]
That is just normal minecraft physics, nothing special there and that is why Mojang added code to 'push' you 'up' out of a block.  That code is disabled for 'transparent' blocks like a pipe, I always had to add it back in manually so it should be added manually back in here as well (be sure to push the entity just a little bit above your block or if they can fall back on and touch it within one tick then they can fall back through).

**Comment by axlegear** [comment]
I should note that other transparent blocks such as wire do not have this issue.  It seems specific to pipes for some reason.
Once stuck in the pipe, nothing will dislodge you.  I've tried.

**Comment by Blood-Asp** [comment]
All machines, pipes and cables are exactly the same block, so they should be habe exactly the same on player interaction.

@OvermindDL1 Can you tell me in what exact MC class i find that Code as example. Using that for GT machine Blocks seems to be a bit more complex as they are not full blocks and it is normal for players to be within blockbounds. And all players below 0.875 is also not enough, since they might be inside on the side or bottom.

**Comment by OvermindDL1** [comment]
Yeah I had to make it myself based on the... whatever entity collide function on the Block class was (I delegated it to my TE's).  I forget the function name but it passes the entity to you and is called 'before' collision checks (it was occasionally handy to do things like give them back a collision box of fullsize for a player, or no collision box if, say, a piece of metal, cheap/easy water sorter), but back on my old gears system back in MC 1.2 I used the callback for rotating the  gears (if standing on an 'edge' it would 'rotate' the player off the block, if standing on and 'end' then it would spin the player around at the same speed as the gear was going, great for making a non-water-based item transporter system by just pushing items along, or cows, or creepers...).  But I had a lot of issues with players getting stuck in my gears the same way as described above, so I basically had to return a collision as normal for the player but then immediately test where the player was and if their collision box intersected mine (block) then I had to push them 'up' and out with an additional clearance based on their velocity (or they'd shoot through my block thanks to 'minecraft physics', good to also push them 'outwards' a bit too).  Minecraft itself I am not even sure uses that callback for anything fancy, it is just a 'getCollisionBox' callback that gives you an entity (but was not called getCollisionBox at the time, it takes an entity and returns a List of AABB's as I recall...).  And yeah I had fairly complex checking to determine if the player was above, to the side, or below but intersecting the block.  My code ended up working really well though after tuning it for a few days.  :-)

**Comment by Blood-Asp** [comment]
Sounds like horribly much work for something that never happed to me so far.

**Comment by OvermindDL1** [comment]
Lol, it was a lot of work yes, and it happens in certain situations only, I was just able to reliably reproduce one of those situations, hence why I fixed it.  It can be fairly deadly so it is a very very bad experience for the player.

**Comment by leagris** [comment]
Filled plasma containment pipes are instant kill no protection. Player vaporise instantly by just entering the box by 1/8.
The fact covers don't protect you for this hazard is a problem also. But @Blood-Asp  knows I asked for hitbox expands to full block on covered sides.
