### ISSUE TITLE
Super fuel recipes

### ISSUE THREAD

**Issue by Techlone** [Blood-Asp/GT5-Unofficial#540]
Please check recipes of SSF. They are disbalanced
Simple:
![image](https://cloud.githubusercontent.com/assets/17011260/16329197/5280bf92-39fa-11e6-9471-e92fd6ec4d0e.png)
And more complex:
![image](https://cloud.githubusercontent.com/assets/17011260/16329236/985ba388-39fa-11e6-9c47-fb20c552fbe5.png)
But output is the same - one block of SSF

**Comment by Blood-Asp** [comment]
The first recipe should include the Railcraft coal Coke block. I guess you do not have it Installer but the recipe still got loaded even though it has a Null item in it.

**Comment by Techlone** [comment]
He he I see but Railcraft_1.7.10-9.8.0.0 has been installed.
