### ISSUE TITLE
[Question] Degrading Fluids & TE Model

### ISSUE THREAD

**Issue by mura3277** [Blood-Asp/GT5-Unofficial#544]
BloodAsp,

Is there any way to have a fluid degrade over time or "convert" into another? I suppose it's possible with onPostTick with pipes and tanks, but is there a good way to get this or a similar effect?

Also, how much work would it be to give a GT tile entity a model? specifically a tank.

**Comment by Blood-Asp** [comment]
I do not know if degrading fluids over time is even possible with the forge fluid system. For certain it would need support of all mods handling fluid, die fluid itself could not do that.

I have no idea so far how models work. Also i think it is not possible to combine that with the GT metaTEs.

**Comment by mura3277** [comment]
Ok, thanks for answering. I suppose it's equally difficult to limit what containers a forge fluid can go into?

**Comment by OvermindDL1** [comment]
Correct, it would be impossible to handle in any place that you do not control, I.E. another mods fluid container.
