### ISSUE TITLE
Beyond 1.7.10

### ISSUE THREAD

**Issue by mura3277** [Blood-Asp/GT5-Unofficial#545]
GT and GT packs will probably remain on 1.7.10 for a while since even GT6 apparently won't be upgrading MC version until it's in a more completed sate.

So I'm wondering, what's your plans (If any) for this fork? do you think eventually you will just move onto GT6 when it is done? I think there is a large amount of people who would like to see this fork continue past 1.7.10 on it's own path and keep the GT5/GT4 format.

If you haven't thought this far, don't worry about it, but I was just curious about what your thinking was.

**Comment by Blood-Asp** [comment]
For now I plan to finish all open plans i have for GT5U and make a "final" Version. After that only Bugfixes and PRs from my side. I guess that would take 1-2 months. 
After that I will likely try to do a plain Port of GT5 to 1.10 or whatever is the current IC2 Version then. But not sure if I will really get that work and certainly no new features from my side.
After that I will likely work on GTExtras and 1-2 other "small"ideas I had some time ago.

**Comment by mura3277** [comment]
That's nice to hear. Nobody can expect you to actually port GT5, but the fact it's on the table is exciting.

**Comment by Techlone** [comment]
How about refusing of IC2 dependency in the future?

**Comment by mura3277** [comment]
Removing the IC2 dependency would be nice, but I feel like we will be lucky enough to get GT5 past MC1.9.4 because of the work involved. However, if it has the possibility to happen, it definitely doesn't make sense for GT to be a IC2 addon anymore.

**Comment by mura3277** [comment]
So just to make sure its known, NEI has been updated to 1.9.4: https://github.com/TheCBProject/NotEnoughItems

If GT5U is ported to 1.9.4/1.10, then it might be easier to use this rather than trying to rewrite it for JEI.

**Comment by Blood-Asp** [comment]
There is no reason to use 1.9. It is already dead. Doing that would be a useless half way port. In that case it would be better to just disable not ported mods and implement them/alternatives once everything else is working.

**Comment by mura3277** [comment]
Yeah that was just example versions. I mentioned it because it was looking like NEI might of been dead.

**Comment by Dragon2488** [comment]
I think this issue should be closed now.

**Comment by Blood-Asp** [comment]
#624
