### ISSUE TITLE
Portable Scanner shows incorrect Large Steam Turbine status

### ISSUE THREAD

**Issue by ShelfOwl** [Blood-Asp/GT5-Unofficial#549]
![2016-06-29_23 03 13](https://cloud.githubusercontent.com/assets/7645511/16489828/22071a10-3f12-11e6-8b99-99180307d730.png)

Using large cobalt turbine.(24000L/s = 1200L/tick, 130% eff.)
- Current Output seems not considers Current Speed
- Optimal Flow shows a quarter of actual optflow

As a side note, Fuel Remaining is not make my sense. 
Steam in input hatches are must be ZERO; otherwise you supply fuels far too much. 
So... what does it for?

in GT 5.09.22pre

**Comment by mura3277** [comment]
I added that scanner info and followed the WIki directions
(1200L/t / 2) \* (0.5) = 300L/t

Is this not correct?

Edit: It's not correct. I assumed it multiplied by the Fuel Value of steam, not divided by it.

**Comment by mura3277** [comment]
Also the fuel remaining part is there so you know you're not supplying too much fuel because if you have a pipe/fluid regulator next the to input hatch, you can't open it.

**Comment by ShelfOwl** [comment]
Ah... I thought "Fuel Remaining" means how last long the turbine generates,
but in this term it means the result of excess flow, I see.

(I was confused because I signed to fuel tank as "Fuel Remains" :D )

Thank you for answer and improvement.
