### ISSUE TITLE
Jackhammer has GT Metadata issue

### ISSUE THREAD

**Issue by hephinator** [Blood-Asp/GT5-Unofficial#55]
Example: http://puu.sh/ip8VC/ffbb17e77b.png
Example 2: http://puu.sh/ip8X3/594f5f6afc.png

All recipes show Titanium components with various long rods for the tip.

Almost impossible to find a working recipe.

**Comment by retep998** [comment]
Isn't it intended that all jackhammers have titanium bodies?

**Comment by hephinator** [comment]
They're supposed to be craftable in the early game to counter the harder ores mechanic. theyre supposed to be made from steel and aluminum and such in LV and MV variants, Titanium for HV, its a huge metadata derp.

**Comment by Thesphero** [comment]
Going over the previous versions, and even comparing the update from gt 4 to gt 5, it looks like jackhammers were never updated properly, so while the HV version was added with the rest of the HV tools, nothing else exists. The chainsaw and drill recipes seem to work, so it just looks like a case of an item falling by the wayside.

**Comment by Blood-Asp** [comment]
I do not count this as a bug. It is just the way greg wanted it to be.
