### ISSUE TITLE
More Circuits

### ISSUE THREAD

**Issue by mura3277** [Blood-Asp/GT5-Unofficial#552]
With machines past IV being added, it might make sense to add circuits for the new tiers of machines.

This might be already planned?

**Comment by Blood-Asp** [comment]
I posted about half a year ago a plan to change the circuits and i still plan to do that. But might still take a few weeks.

Not only higher tier circuits, but also more variations of all tiers. Also a need for cleanrooms for higher tier circuits and maybe optional galacticraft support, forcing highest tier circuits to be build in zero gravitiy space stations.

**Comment by Nex4rius** [comment]
That sounds awesome!

**Comment by leagris** [comment]
Processing stuffs in another dimension without means to move items and fluids wirelessly, that just sound like too much.
We already suffer from sever tech gaps with vaccum freezer requiring polytetrafluoroethylene.

**Comment by Blood-Asp** [comment]
Thats certainly something with confing option. Also Galacticraft has it's own way to automation transfer beween planets.
