### ISSUE TITLE
GT Axes does not affect IC crops

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#555]
I'm not sure it is on GT side, but all vanilla and vanilla-like axes (bronze, steel, etc) works fine.
But GT neither axe nor chainsaw does nothing.

**Comment by Blood-Asp** [comment]
What exactly do you want to do to IC2 crops? Why do you want to use an axe on crops?

**Comment by SapientMC** [comment]
I want to remove them. For example i plan to pause my cropbreeding process and need to remove all crops without any plant on it to prevent weed generation.

**Comment by Blood-Asp** [comment]
Pretty sure an axe is the wrong tool then. GT Tools always work like in advature mode not mining anything not for them, while vanilla tools handle everything else in that case like using bare hand. So likely the correct way is pulling them out by hand.

**Comment by SapientMC** [comment]
WAILA shows axe as effective tool. Vanilla axes works much faster than empty hands.

**Comment by Blood-Asp** [comment]
Well, no idea where the issue is, but GT axes are implemented as correct axes, so not much mroe i can do here.
