### ISSUE TITLE
6 different machines have 1 textures

### ISSUE THREAD

**Issue by aLegoz** [Blood-Asp/GT5-Unofficial#558]
Pyrolyse oven, Oil cracking unit, Advanced Miner II  and 3 Boilers have 1 texture. 
I think, it must have a unique textures.
http://i.imgur.com/1LPAJ0i.png

UPD1: 
- Processing Array
- Oil Drilling rig
- Diesel Engine
- Large Heat Exchanger

**Comment by Techlone** [comment]
Are you sure that it's GT's textures? Don't think so.

**Comment by aLegoz** [comment]
@Techlone Its my textures. All this machines use one texture (from Boiler)

**Comment by draknyte1** [comment]
Adding more Overlays isn't worth the time.
95% of the mod uses the same textures with a hue change, we'll live.

**Comment by Blood-Asp** [comment]
well, making 6 copies of that texture with different names and having every machine link to another one of it should be not too difficult. 
Ideally some texture artist provides also some different textures for them, otherwise it only helps texturepack makers.
