### ISSUE TITLE
Assembly line dont work on Z coordinates.

### ISSUE THREAD

**Issue by aLegoz** [Blood-Asp/GT5-Unofficial#559]
A machine works only in X coordinates
http://i.imgur.com/CBPVI7x.png

**Comment by perkinslr** [comment]
That would be the Z direction, Y is up, and isn't supposed to work.  Z is.

**Comment by Blood-Asp** [comment]
This cant be the direction alone. Maybe something like + or - coordinates in addition. I only tested in positive x and z coordinates.

**Comment by Georggi** [comment]
Seems to not work on negative x for me. I've put everything needed but it doesn't start(mallet was used, stick was put inside) placed on X line and inside one chunk.
EDIT: Nvm, I've put yttrium barium cuprate wires instead of cables..

**Comment by Blood-Asp** [comment]
So negative X does work. Anyone to test negative z before i finally get to it? xD
