### ISSUE TITLE
Ore generation (sometimes) creates large deposits of gt.blockores.0.name

### ISSUE THREAD

**Issue by aerospark** [Blood-Asp/GT5-Unofficial#56]
First off, great job continuing GT5, you're "doing god's work."

Anyway, when exploring the world, you can sometimes come across MASSIVE deposits of gt.blockores.0.name, that when mined, drop vanilla iron ore. These blocks won't update to a proper ore meta no matter what. (Block update/server restart/etc)

This issue has been a part of GT5 for quite some time, here's a few other people talking about the issue:
https://github.com/JasonMcRay/InfiTech-1.7/issues/167
http://forum.feed-the-beast.com/threads/1-7-10-infitech-2-modpack-v3-0-1-gregtech-balanced-hard-mode-modpack-updated-6-9-2015.50185/page-148#post-1019437
http://forum.industrial-craft.net/index.php?page=Thread&postID=184956

Because of how rare this issue is, a quick hack-fix would be to make change whatever code tells gt.blockores.0.name to drop iron, to drop cobblestone instead. Users without WAILA wouldn't even notice and it would solve the problem of being able to obtain ridiculous amounts of iron ore early game.

The modpack I'm using is stock Beyond Reality, though it -seems- to be unrelated to 3rd party mods.

**Comment by aerospark** [comment]
The "quick partial hack-fix" I mentioned could be done by editing this line: https://github.com/Blood-Asp/GT5-Unofficial/blob/master/main/java/gregtech/common/blocks/GT_TileEntity_Ores.java#L153 changing iron to cobblestone.

**Comment by aerospark** [comment]
Because these "blobs" are solid and contain no stone in between them, I can only assume It's replacing some "other kind of stone" from an external mod, they're not true gregtech deposits.

**Comment by Blood-Asp** [comment]
There is no code in GT5 that can generate the ores in that form (blob ore vein instead of the normal big ones with normal stone in beween). I can only asume that some random other mod tries to place GT ores but can't handle the metadata setting.
