### ISSUE TITLE
Electric Blast Furnace doesn't add progress

### ISSUE THREAD

**Issue by Lainiel** [Blood-Asp/GT5-Unofficial#563]
I dedided to try the new version 5.09.22 on my multiplayer world, but now I encountered a problem where when I put something into the Electric Blast Furnace it lights up and starts consuming power, but refuses to add any progress towards finishing the process. I waited several minutes and I couldn't even smelt one aluminum. Progress is always stuck at 0 sec no matter how long you wait.

![225c223905 1](https://cloud.githubusercontent.com/assets/18221846/16672886/65b6f1a8-44a9-11e6-840c-860086a1e7b3.jpg)

When the power is disconnected the furnace stops working.

**Comment by SapientMC** [comment]
I confirm it.
Work cycle started at 5.09.21 continues after update to 5.09.22 but new cycle does not starts until i change GT back to .21

**Comment by SapientMC** [comment]
Additional info. Same problem with all machines with muffler hatches
- MV EBF stops working after 49 sec
- Multi Smelter after 49 sec
- Emp. Compressor after 1 sec
- Large bronze/steel boiler after 66 sec

**Comment by SapientMC** [comment]
Additional info.
All works fine (after replacing controllers) in version without this commit https://github.com/Blood-Asp/GT5-Unofficial/commit/57deb3b3e13091f6c4fe2169cd878c75451cfdce

**Comment by Blood-Asp** [comment]
I more or less know what the issue is. Should soon be fixed.

**Comment by Blood-Asp** [comment]
catch the error for now. real fix soon

**Comment by SapientMC** [comment]
Nice. Thanx a lot
