### ISSUE TITLE
Mean to detect large turbine damage

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#564]
@Blood-Asp 

Some time ago you mentioned the Need-Maintenance Cover triggered a signal as turbine reached <20% durability.
I could not reproduce this behavior, so I guess that either the feature is broken or remained as a project.
Could you or someone skilled for the task adds that to the Need-Maintenance Cover or another applicable mean to detect and stop the turbine if it reaches less than 20% durability?
And please, please, don't make the turbine controller the turbine axle. Make it placed onto an edge or corner. Wireless redstone transmitter covers are wrong by design in this kind of use. I see no reason you can not control a Large turbine by wires.
Alternatively, it would be very very cool using a dedicated controller box you stick against any GT Machine and that controller box would have control on all states, emit various redstone signals, receive signals and expose data to sensors and OpenComputers.

**Comment by Blood-Asp** [comment]
I will look were the problem is. I did some creative testing when i implemented it and it worked back then. Pulling out signals from multiblock controllers into other blocks seems quite difficult to me, so no promises here.

**Comment by Blood-Asp** [comment]
Added a new mode only for turbine rotor control: https://github.com/Blood-Asp/GT5-Unofficial/commit/8ef12119e06d291b779fd124a2fa8a74a111fa56
Using wireless redstone covers to get the signal works just fine for me.
