### ISSUE TITLE
Naquadah reactors GUI and items tootips

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#57]
#### GUI kind
All Naquadah reactors wrongly uses a `BasicTank` GUI asset because there is no Generator GUI or no Solid Generator GUI kind.
#### Working Icon
While working, a Burning Flame icon is shown into the GUI.
It could be fixed by using a more appropriate Solid Fuel Generator GUI instead.
##### Working Icon Tooltip
Currently displlay `Generating: 199999488 EU 51` for all tiers.
It should display the real amount generating.
A better GUI with more text display space (maybe re-purpose the `MultiblockDisplay` asset) and more appropriate string formats should allow these larger numbers to fit properly.

#### Generator Item name
The `Fluid Naquadah Reactor` should be renamed `Naquadah Reactor Mark III` because it does not use fluids at all.
#### Item description
The Fluid Naquadah reactor should say: `Require Enriched Naquadah Cells` instead of ~~`Require Fluid Heavy Naquadah`~~.
#### Fuel burn time/energy per unit
Enriched Naquadah bolts and Cells Tooltip shall show amount of time or energy it can produce.

**Comment by Blood-Asp** [comment]
GUI building is really annoying in Minecraft and since it works i will not make big changes there.

The Tooltip stuff is valid through...

**Comment by Blood-Asp** [comment]
Changed tooltips in 5.08.21

**Comment by leagris** [comment]
Thank you @Blood-Asp :thumbsup:
