### ISSUE TITLE
RFTools Compatibility

### ISSUE THREAD

**Issue by ghost** [Blood-Asp/GT5-Unofficial#570]
According to this post on MCF: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2229562-rftools-dimension-builder-teleportation-crafter?comment=808

McJty had to blacklist GregTech ores from generation in RFTools dimensions due to not handling the MetaTileEntity of ores properly. That results in modpacks which **only** have GT ore generation and no others, to be completely useless with RFTools dimensions.

Therefore, I propose adding hooks in GT5 to allow RFTools to properly generate GT ores without causing the dimensions to crash, or generation gt.blockores.0.name (stone ore)

Also, RFTools has API hooks for you to set the power / resource cost from your side. Hopefully the two of you can talk and see what needs to take place.

There is no reason an entire mod should be blacklisted when its intermod compatibility can be worked out.

**Comment by OvermindDL1** [comment]
Sounds like a bug in RFTools if they do not handle oregen properly?  Why is this here since it seems like a bug on their side (and their lack of programming ability so they blacklist it instead of do oregen properly)?  Setting the power/resource cost via API could be interesting, though I do not use RF mods myself.

**Comment by mura3277** [comment]
The GT ore generated by RFTools must be missing its tile entity or has null data. The problem might be solved by RFTools using GT_TileEntity_Ores.setOreBlock() instead of using setBlock() via a World object.

But yes, likely an RFTools issue.

**Comment by OvermindDL1** [comment]
If they are using setBlock for ore-gen then they are stupid.  They should call the ore-gen callbacks.

**Comment by draknyte1** [comment]
My build of RfTools (v4.2.2) spawns GT ores?..
Not sure where McJty thinks the issue lies when I've generated 100s of worlds over various versions without a hitch..

**Comment by mura3277** [comment]
From what I remember, I think it's if you use a specific dimlet for a specific GT ore. It might work correctly if no ore types are specified for the dimension, and thus using the normal generation.

**Comment by draknyte1** [comment]
Nope, I literally NEVER have specified an ore dimlet.. GT Ore DO Generate within my GT fork and RfTools.

Maybe it related to something Blood Changed in Experimental related to OreGen (I never commited any worldgen changes to my fork, because I don't want them on my servers world.)

**Comment by Muramasa-** [comment]
Yeah that's what I mean, I think the issue is when you DO specify an ore dimlet.

"I'm getting a crash whenever I go into a dimension where the base terrain is a Gregtech ore (Chrome in this case)"

**Comment by draknyte1** [comment]
I'll message @McJty I guess, if it's only specific ores being set wrong, shan't be too hard to fix.

**Comment by mura3277** [comment]
If he looks at GT_Worldgen_GT_Ore_Layer he should be able to see how GT ores are handled.

**Comment by Blood-Asp** [comment]
Well, GT ores are different from other mods ores and this problems will happen with some mods. Not much i can do here to change that.
