### ISSUE TITLE
naquadah generator

### ISSUE THREAD

**Issue by Nex4rius** [Blood-Asp/GT5-Unofficial#571]
The naquadah generator mk1 and mk2 are using enriched naquadah bolts and are giving normal naquadah bolts in return but the naquadah generator mk3 is using enriched naquadah cells and is only giving empty cells in return.

Could you change it so it gives normal naqudah back?

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/pull/568
