### ISSUE TITLE
Large Plasma Generator

### ISSUE THREAD

**Issue by reignbringer** [Blood-Asp/GT5-Unofficial#573]
I was testing in creative mode with the Large Plasma Generator, and noticed it exhibiting some strange behavior. The multiblock formed correctly and stated it was operating, yet it was not outputting any power. I had a large HSS-E turbine rotor in the controller block, and a ZPM dynamo hatch at the rear, feeding it helium plasma cells from an ME storage bus so it didn't run out of plasma. Though the turbine stated it was "running perfectly", no power was being output to a battery buffer I had connected (ZPM was transformed down to LuV to input into the buffer). When I switched the dynamo hatch to a LuV one, the generator began outputting power, however, since the large HSS-E turbine has 140% efficiency with 30,000 optimal plasma flow per tick, it should output 42,000 EU/t, so shouldn't the LuV dynamo hatch melt/explode from being over-volted? Does rotor efficiency factor in to the large plasma generator, or does that only apply to the steam/gas versions of the multiblock? This was all done in a single-player creative test world running InfiTech 2 version 3.2.10.1.

**Comment by Blood-Asp** [comment]
Have to test this later. Sounds like instead of exploding when too much energy is produced for used dynamo hatch, the energy is fully voided. In case that is, a simple change of one boolean should fix it.
