### ISSUE TITLE
Reactoria leaf recipies missing

### ISSUE THREAD

**Issue by DEMOOH** [Blood-Asp/GT5-Unofficial#574]
Reactoria crop drops Reactoria and Uranite leaves. Uranite leaf has it's own recipies for ore multiplication, but Reactoria leaf don't, which makes it useless.

**Comment by axlegear** [comment]
Oop, yeah, no recipe, sure enough!

**Comment by Blood-Asp** [comment]
guess you fixed it yourself: https://github.com/Blood-Asp/GT5-Unofficial/pull/568
When i remember right, i fixed it on the wrong place creating duplicate code that got deleted a few updated back.
