### ISSUE TITLE
Can't seem to add fluids to EBF

### ISSUE THREAD

**Issue by DarkholmeTenk** [Blood-Asp/GT5-Unofficial#577]
http://imgur.com/a/25uyw

Despite having oxygen cells in the input slot of the input hatch, they never seem to get processed. Can't seem to pipe oxygen in using any mod's fluid handling either.
I've tried both with and without oxgen requiring recipes (galena dust and iron dust), but I can't seem to input the fluid.

If the input hatch hasn't formed part of the multiblock (e.g. on loading or if separated), I can input fluids with no problem, but as soon as it joins the EBF, I can't.

I'm assuming this is the correct way to insert fluids to the EBF as when some is inserted before the multiblock is loaded, it uses it correctly and starts cooking steel or silver/lead.

Nothing is outputted to the console.

Am I doing something wrong, or is this a conflict/bug?

Mod list:

> appliedenergistics2-rv3-beta-6
> Automagy-1.7.10-0.28.2
> BiblioCraft[v1.11.5][MC1.7.10]
> BloodMagic-1.7.10-1.3.3-17
> Carpenter's Blocks v3.3.8 - MC 1.7.10
> Chisel-2.9.5.11
> CodeChickenCore-1.7.10-1.0.7.47-universal
> CoFHCore-[1.7.10]3.1.2-325
> darkcore-0.42-208
> Darkcraft-0.15-235
> dimensional-anchor-59.0.3
> EnderStorage-1.7.10-1.4.7.37-universal
> GalaxySpace-1.0.9 STABLE
> INpureCore-[1.7.10]1.0.0B9-62
> ExtraCells-1.7.10-2.3.10b190
> extrautilities-1.2.12
> Forbidden Magic-1.7.10-0.575
> gadomancy-1.7.10-1.0.7.2
> GalacticGreg-0.7
> GalacticraftCore-1.7-3.0.12.460
> Galacticraft-Planets-1.7-3.0.12.460
> SGCraft-1.11.2-mc1.7.10
> gregtech-5.09.22
> GTTweaker-1.7.10-1.4.1
> immibis-core-59.1.4
> industrialcraft-2-2.2.822-experimental
> InventoryTweaks-1.59-dev-152
> MapWriter-1.7.10-2.1.10
> MicdoodleCore-1.7-3.0.12.460
> MineFactoryReloaded-[1.7.10]2.8.1-174
> MineTweaker3-1.7.10-3.0.10B
> ModTweaker2-0.9.5
> MouseTweaks-2.4.4-mc1.7.10
> NotEnoughItems-1.7.10-1.0.5.120-universal
> NotEnoughKeys-1.7.10-3.0.0b45-dev-universal
> OpenComputers-MC1.7.10-1.6.0.3-rc.1-universal
> Opis-1.3.1-MAPLESS_1.7.10
> SkillAPI-1.7.10-0.02-94
> SonarCore-1.7.10-1.1.2
> SoulShards-TOW-1.7.10-0.1-RC9-7
> sprinklesforvanilla-1.7.10-1.6.0
> StevesAddons-1.7.10-0.10.16
> StevesFactoryManagerA93
> StorageDrawers-1.7.10-1.10.0
> TaintedMagic-1.1.6.4
> tcinventoryscan-mc1.7.10-1.0.11
> tcnodetracker-1.7.10-1.1.2
> Thaumcraft-1.7.10-4.2.3.5
> thaumcraftneiplugin-1.7.10-1.7a
> thaumicenergistics-1.0.0.5
> thaumichorizons-1.7.10-1.1.9
> ThaumicInfusion-4.32
> ThaumicTinkerer-2.5-1.7.10-164
> ThermalDynamics-[1.7.10]1.2.0-171
> ThermalExpansion-[1.7.10]4.1.2-240
> ThermalFoundation-[1.7.10]1.2.4-114
> VeinMiner-1.7.10_0.31.6.unknown
> Waila-1.5.10_1.7.10

**Comment by Blood-Asp** [comment]
Do you have multiple types of oxygen? Maybe you got the wrong one.

Also possible might be that you added an mod that also has oxygen After you started the world. Galacticraft is a typical canidate for that. This would require you to NBTedit the fluidlist of your world.

**Comment by DarkholmeTenk** [comment]
Galacticraft is installed. I assumed the gregtech oxygen cell (i.e. the one which has the atomic symbol on it) would work.
I assume the fluid list is in level.dat? Any indication of exactly what changes I should make?

Edit: as far as I can see, the only oxygen in the fluid list is "gregtech:oxygen" and the only oxygen fluid galacticraft adds is "GalacticraftMars:liquidoxygen", so I'm not quite sure why this should cause a problem.
In fact, as far as I can tell, Galacticraft never registers oxygen itself as a fluid.

**Comment by Blood-Asp** [comment]
Jep. You have to delete all the entrys for oxygen and start the world again to regenerate them. Remember to backup before. Might mess up your stored fluids in world, but nothing you can do there. Sometimes even a full delete od the list was needed.

**Comment by DarkholmeTenk** [comment]
For future reference, it looks like it can be fixed by just replacing "gregtech:oxygen" with "GalacticraftMars:oxygen", without negatively impacting any stored fluids or anything.
Presumably the blacklist looks for GalacticraftMars:oxygen because that's how the fluid list ends up after postinit, but doesn't actually take in to account the fact that the world's fluid list may not exactly match.
