### ISSUE TITLE
Super Fuel does not burn in large boilers

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#579]
Yep.  My large bronze boiler can't do anything with it.  >.<

**Comment by DEMOOH** [comment]
If you started a boiler with superfuel then you have to wait a lot for the boiler to actually run. Can you check your boiler status with a tricoder?

**Comment by mura3277** [comment]
Magic Super Fuel seems to burn in the boilers, but weirdly normal Super Fuel does not.

**Comment by DEMOOH** [comment]
Confirmed. Can't find any difference in code between Super Fuel and Super Magic Fuel though. And i doubt that there is one.

**Comment by axlegear** [comment]
![image](https://cloud.githubusercontent.com/assets/7531754/17087148/e117bdba-51c8-11e6-85b6-5372daa66c3e.png)
![image](https://cloud.githubusercontent.com/assets/7531754/17087149/e519575c-51c8-11e6-8c71-00b9e182d4fd.png)

**Comment by axlegear** [comment]
As you can see, nothing.  No progress, doesn't start.  I've bopped it with a hammer, nadda.  Zero.  Zilch.

Real shame 'cuz I automated making it.. sitting on quite a few stacks.  >.<

**Comment by Blood-Asp** [comment]
Really strange. There is really no difference beween them. As long it is not something strange when dealing with huge fuel values in the burning math, i can only think of one small issue of the pollution system breaking the boiler itself. but in that case everything should stop burning in there.

**Comment by axlegear** [comment]
I don't know but it sure is disappointing!  _Builds a castle out of the superfuel blocks he made._

**Comment by DEMOOH** [comment]
> huge fuel values in the burning math

Coke Block - 32k heat units - 26 seconds in titanium boiler
Magic Super Fuel - 150k heat units - 15 seconds

Vanilla furnace works as intended, so does NEI's tooltip.

**Comment by OvermindDL1** [comment]
Well considering 150k > 2^15-1 it sounds like it is going beyond a 'signed short' somewhere.  Some quickie math, 150k/(2^15-1) ~= 4.5776, so if it overflows 4 times leaving 57.76% remaining, multiplied by 26 seconds leave 15.01 seconds, rounded to 15 seconds due to 20tps, so yep.

**Comment by DEMOOH** [comment]
> rFuelValue = (short) Math.max(rFuelValue, 150000);

Does it have to be short? We have a problem then.

> net.minecraft.nbt.NBTTagCompound;
> short tValue = tNBT.getShort("GT.ItemFuelValue");

getInt or smth?

**Comment by OvermindDL1** [comment]
Wow someone was not paying attention or on something if they put `150000` and a `(short)` on the same line, like wow.  ;-P
Changing that getShort to getInt might cause backwards compat issues, be careful for there be dragons in NBT.

**Comment by OvermindDL1** [comment]
You could always add a new entry safely in NBT of some key like "GT.ItemFuelValueMult" then if it exists then multiply "GT.Item.FuelValue" with it.  That would be backwards compat-safe.

**Comment by Blood-Asp** [comment]
I did notice that when adding the super fuel, changed the attribute to integer but forgot to remove the casting to short... https://github.com/Blood-Asp/GT5-Unofficial/commit/b4bcebf4583a0cac5b59a30b23cd8bb41422c7d4

**Comment by axlegear** [comment]
Can't wait for this update/release.  I got all these superfuel blocks just burning holes in my pocket.
