### ISSUE TITLE
SMP: FluidRegistry / FMLPacketHandler errors on PlayerLogin

### ISSUE THREAD

**Issue by hephinator** [Blood-Asp/GT5-Unofficial#58]
Crash Log 1: http://www.hephinator.com/crashlogs/crash-2015-06-16_00.13.33-client.txt
FML Log 1: http://www.hephinator.com/crashlogs/fml-client-latest-1.log

Crash Log 2: http://www.hephinator.com/crashlogs/crash-2015-06-16_00.44.26-client.txt
FML Log 2: http://www.hephinator.com/crashlogs/fml-client-latest-2.log

Various molten fluids are not being handled properly, and the item in question cycles on each login. Got about a dozen various metals, all with the same stacktrace shown in the logs above.

Forge 1448 (recommended build)
GT 5.08.19
IC2 2.2.736.

If GT5 is disabled, IC2 stops kicking clients and I can join the server.
Just to reiterate, this does NOT affect SSP, only SMP.

I will continue to do some testing and report back with any additional findings I may come across.

EDIT #1: Definitely doesn't exhibit this behavior on Forge #1355

**Comment by iamtakingiteasy** [comment]
I can confirm this issue happening on forge #1448 and the latest #1451.

**Comment by florian96** [comment]
Its for me too.

**Comment by Blood-Asp** [comment]
Known bug with new forge. use older forge for now. I will only update once other mods force me to do that or there is something in newer forge versions i need.

**Comment by Maffeo** [comment]
In issue #45 I wrote what I found in changelog from forge:

> cpw:
>    Fix up the client/server fluid race condition that could cause the game to bail when an SSP game connects.
> There's still a teeny gap, but it's MUCH less prominent than it was before.

**Comment by Blood-Asp** [comment]
Opened a issue on forge. I hope they can fix it on their side or at last tell me how to get around it. 
https://github.com/MinecraftForge/MinecraftForge/issues/1973
As i can't do anything about it right now, closed.
