### ISSUE TITLE
light fuel incompatible with GC

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#581]
Diesel fuel was fine but light fuel doesn't work. 
https://youtu.be/hz6Hg-JZ4WU

**Comment by mura3277** [comment]
So IIRC, Diesel is in the game more for compatibility. Its not actually intended that you use it for power production, but for using it with other mods. You can make diesel if you look for the uses of a Light Fuel fluid cell, you will find a mixer recipe.

To add to the mess, GC rockets will only accept fluids with certain names. So you have to use Diesel util GT Rocket Fuel is added.

**Comment by Blood-Asp** [comment]
That's fully on GC side to decide what is usable as Rocket fuels. Nothing I can do here. GC decided to accept only default fuel and fluids with "Rocket" in the name.
