### ISSUE TITLE
How to specify the loss of ore in mining?

### ISSUE THREAD

**Issue by Lucelarius** [Blood-Asp/GT5-Unofficial#585]
Help me please!
How to install the unit as a drop gregteh ore desired Metadata?

``` javascript
@Override
    public Item getItemDropped(int par1, Random par2Random, int par3)
    {
        return GT_Item_Ores.getItemFromBlock("???drop gregtech ore???"); // for example "Iron Ore Black Granite" (gt.blockores.3032.name)
    }
```

**Comment by Blood-Asp** [comment]
Something like:
GT_OreDictUnificator.get(OrePrefixes.oreBlackGranite, Materials.Iron, 1)
?

**Comment by Lucelarius** [comment]
Gives an error message: "incompatible types: ItemStack cannot be converted to Block"
if

``` javascript
@Override
    public Item getItemDropped(int par1, Random par2Random, int par3) {
        return GT_Item_Ores.getItemFromBlock(GT_OreDictUnificator.get(OrePrefixes.oreBlackgranite, Materials.Iron, 1));
    }
```

or: "incompatible types: ItemStack cannot be converted to Block"
if

``` javascript
@Override
    public Item getItemDropped(int par1, Random par2Random, int par3) {
        return GT_OreDictUnificator.get(OrePrefixes.oreBlackgranite, Materials.Iron, 1);
    }
```

**Comment by mura3277** [comment]
Because GT_OreDictUnificator.get() returns an ItemStack. I assume you have put that in getItemFromBlock?

It might help to pastebin.com your class.

**Comment by Lucelarius** [comment]
I this is a beginner and can be silly mistakes.

Finish: http://pastebin.com/Zbwrnsr2

PS: Thanks in advance for your help.

**Comment by mura3277** [comment]
What's the purpose of creating a "copy" of GT ores?

You should be able to register the ore in GT to enable ore processing etc with this in your blocks constructor if I'm not mistaken:
GT_OreDictUnificator.registerOre(OrePrefixes.oreBlackgranite.get(Materials.Iron), new ItemStack(this, 1, meta));

**Comment by Lucelarius** [comment]
Add the ability to extract the ore from the "GregTech" asteroid "Galacticraft", on how to "astrominer" out of it, does not see the asteroids generated "galacticgreg".
Add a conventional generator blocks in the asteroid is no problem.

**Comment by Lucelarius** [comment]
> You should be able to register the ore in GT to enable ore processing etc with this in your blocks constructor if I'm not mistaken:
GT_OreDictUnificator.registerOre(OrePrefixes.oreBlackgranite.get(Materials.Iron), new ItemStack(this, 1, meta));

Add a registration I believe it is necessary in the main class?

**Comment by Blood-Asp** [comment]
https://github.com/micdoodle8/Galacticraft/issues/2215 Is that about this?

**Comment by Lucelarius** [comment]
Ore mine, he can, but he does not see the asteroid themselves. When generating an asteroid, its data is written to the file: world/data/GCAsteroidData.dat
According to these data astromayner and oriented in the world of asteroids.

**Comment by Lucelarius** [comment]
THANK YOU SO MUCH!!!
The unit automatically assign all kinds of processing recipes. This is quite enough.

If anyone is interested:

``` javascript
@Mod.EventHandler
    public void onPostLoad(FMLPostInitializationEvent aEvent) 
    {
        GT_OreDictUnificator.registerOre(OrePrefixes.oreBlackgranite.get(Materials.Iron), new ItemStack(Iron, 1, 0));
    }
```

It remains to be understood as a single line to do it for all ores. I'll deal.
