### ISSUE TITLE
Biogas/Bioethanol conflict

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#587]
Both take biomass in a distillery with a No. 1 circuit.  The recipes conflict.  Suggest changing one to a different circuit # so you can choose bioethanol or biogas.

**Comment by mura3277** [comment]
I believe they're different fluids. I think the biomass used to create biogas is actually Ic2biomass. The fluid used to create ethanol is standard biomass.

**Comment by OneEyeMaker** [comment]
There are two different fluids with the same localized name ("ic2biomass" supported by IC2 and "biomass" supported by Forestry). From first one in distillery you can create biogas ("ic2biogas"), from second - ethanol ("bioethanol").

**Comment by mura3277** [comment]
What @OneEyeMaker said :smile:

**Comment by axlegear** [comment]
Then there is no appaent way to obtain the biomass to make bioethanol in GT5U.

**Comment by OneEyeMaker** [comment]
Because biomass (source of bioethanol) provided by Forestry (I guess, GT has this recipe for compatibility)

**Comment by axlegear** [comment]
Wierd, we don't have Forestry in this pack.

**Comment by OneEyeMaker** [comment]
GT adds many materials from different mods itself (for compatibility) without checking is mod loaded. For example, you can find Thaumcraft shards in GT recipes even Thaumcraft isn't installed. The same thing with fluids: GT adds seed oil, biomass and bioethanol (all three liquids are from Forestry) itself and mostly for compatibility. (But, sometimes GT uses these materials for custom purposes, for example, AFAIR lubricant requires seed oil in its recipe)

**Comment by Blood-Asp** [comment]
As everyone here explained, no issue, just cross mod compatibility.

**Comment by axlegear** [comment]
Kinda sucks tho.  I wanted to make ethanol.  XD

**Comment by mura3277** [comment]
Then why not install forestry?

**Comment by axlegear** [comment]
Why not zoidberg?
