### ISSUE TITLE
Osmiridium and naquadah alloy recipies wierdness

### ISSUE THREAD

**Issue by DEMOOH** [Blood-Asp/GT5-Unofficial#588]
**Osmiridium and naquadah alloy recipies don't work**
Got this issue on the way to Tier 3 Fusion Reactor. Can't fix this by myself, i am not really into it. But the code is quite different from others. Some suspicious nulls for example.
Edit. Should add that i am aware of the need of helium and argon in those recipies.

**Comment by mura3277** [comment]
Are you sure this isn't #563?

**Comment by DEMOOH** [comment]
Nope, EBF just doesn't launch, like there are no such recipies.

**Comment by DEMOOH** [comment]
Wow, it's actually worked. Don't know, what happened. I just manipulated a little with items in input bus. That's strange, i tested it with a palladium dust before and never touched after.

**Comment by DEMOOH** [comment]
So the furnace launched as soon as i removed cells with gas from input hatch. Also there is problem with filling the hatch (argon at the moment), i have to remove control block and hatch, install the hatch, fill it, place the controller back, fix the multiblock, remove filled cells from the hatch. And then i can launch the EBF. With some luck i can also refill the hatch without this actions. And i can't fill the hatch with pipes or something simillar.

**Comment by Blood-Asp** [comment]
So the reason it did not start earlier is that argon was missing in the hatch?
The hatch not accepting a fluid as part of the multiblock means, that the multiblock did not accept the fluids as a valid fluid for any of its recipes.

This usually happens when a mod that also adds this fluid got added to a modpack after the world was started. How to fix if it is that, see here: https://github.com/Blood-Asp/GT5-Unofficial/issues/577

**Comment by DEMOOH** [comment]
Right, i met this before too. Good thing i don't need to supply the EBF with argon constantly. 
This discussion can be closed. I don't know which mod caused this, because admin just deleted level.dat and rebooted the server. But it worked anyway.

**Comment by Blood-Asp** [comment]
deleted the full level.dat? That should not work...
Well, as long your world still works, i guess your admin did it right.
