### ISSUE TITLE
Suggestion for cleaner textures.

### ISSUE THREAD

**Issue by mightydanp** [Blood-Asp/GT5-Unofficial#589]
I want to know if you could possibly make it to where there is a config where you turn it to true and you if set to true instead of using the default textures for the ores it will look by the blocks around it for a white listed block and if the block is white listed it would use the texture of that block underneath the ore texture.

**Comment by mura3277** [comment]
What mod do you specifically have in mind?

**Comment by leagris** [comment]
I think Ore tiles should be backported from GT6, it would fix this issue.

I have Galacticraft Galactigreg in mind were RedGranite is not a good background on Mars and Stone background inappropriate for Moon. Same for Granite Asteroids.

The Ore tile shall reference the block it replaced during generation as background material.

**Comment by mura3277** [comment]
@leagris I actually just redone some of the ore system due to this very issue. UndergroundBiomesConstructs is already supported by #576 and I'm working on submitting GC support when the GalacticGreg merge is done.

**Comment by Blood-Asp** [comment]
Checking blocks next to them is far too laggy. Also most stone types just got added. I think this is safe to close.

**Comment by mightydanp** [comment]
is it possible to check the generation of a block. say if there is a block here then generate a ore with this texture when loading chunks for the first time and that texture will be permemint so it wont have to reload it when you reload the world it will just load  the block with the texture that it has save.

**Comment by Blood-Asp** [comment]
Checking what block it replaces and using a version of that stone is what is already done. The way it is makes it nessary that a type of that ore stone is known and generated by GT. Grabbing the texture and saving it... Not sure if even possible without breaking existing worlds.

**Comment by mightydanp** [comment]
make it a config option, make it to where it only does it for newly generated blocks.
