### ISSUE TITLE
Double-Unification 

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#59]
When I craft for example Iron Ingot into Iron Nugget in the crafting output I get Thaumcraft nugget, then I put it into my inventory and it changes to GT iron nugget. Is there a way to force it to unify the crafting output? i have noticed that there is an config option for: CraftingUnification=true; and I assume this is what is handling it. Broken?

**Comment by JasonMcRay** [comment]
I have also noticed, when I start modpack once, I get output as Thaumcraft Iron Nugget, when I pick it up it turns into GT Nugget.

When I started the modpack second time, I got as an output GT Iron Nugget and when I picked it up it stayed as GT Nugget.

**Comment by Blood-Asp** [comment]
can't get it to work with GT code. Seems to be the TC crafting handler. The easiest way to fix that should be to remove/readd the recipe with MT.
The TC machines will allways output TC nuggets, no way to change that.

**Comment by JasonMcRay** [comment]
It worked in earlier versions of GT without an issue

**Comment by JasonMcRay** [comment]
And also its happening in normal crafting table (crafting Iron Ingot into 9x Iron Nuggets for example)

**Comment by Blood-Asp** [comment]
hmm, i have one more idea were the problem might be. if it is not that, i will likely let it be as an minor issue
