### ISSUE TITLE
Diesel Engine tooltip is misleading

### ISSUE THREAD

**Issue by DEMOOH** [Blood-Asp/GT5-Unofficial#593]
So there is nothing about engine intake casing. I think that's something that @Muramasa-  should fix. Also the interaction with oxygen should be mentioned too. And lubricant.

**Comment by mura3277** [comment]
I wouldn't say it's misleading, but it should definitely say something about intake casings. I swear that I had that in the tooltip, but obviously not.

The mechanics of the multiblock would be better suited on the wiki. (I really need to do that, sorry)
