### ISSUE TITLE
the problem with the information translated into Russian

### ISSUE THREAD

**Issue by natzgzul89** [Blood-Asp/GT5-Unofficial#595]
I have translated the information about the multi-block structures, but in the game it is not translated.
![screenshot_1](https://cloud.githubusercontent.com/assets/20620700/17462659/89f2cd6a-5cde-11e6-9a49-28120662b465.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/20620700/17462660/89f63dd8-5cde-11e6-9fc6-5d56035696a4.png)

**Comment by draknyte1** [comment]
I wasn't aware you could change the locale for tooltip info.. considering it's all hardcoded

**Comment by natzgzul89** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/20620700/17504602/a7dc8e82-5e24-11e6-9901-70f79924d92f.png)
I understand they are included

**Comment by Blood-Asp** [comment]
Not really sure why that is happening... needs some deeper testing.

**Comment by natzgzul89** [comment]
I can be any help in testing?

**Comment by ShadowT1me** [comment]
Now gets another problem - http://data3.floomby.com/files/share/5_9_2016/19/weqcbk7N0i7BvFShGsQTA.jpg

**Comment by Blood-Asp** [comment]
As i can't read it, what exactly is the problem?

**Comment by ShadowT1me** [comment]
Do not render values of turbines (all of them), all information lines are zero...

same picture, but in en version - http://prntscr.com/cejqy4

**Comment by SapientMC** [comment]
> Now gets another problem

Мне кажется лучше написать "Потери на метр на ампер", а то если бы не знал о чем речь не понял бы, точнее понял бы непрапвильно. Как будто амперы теряются.

**Comment by ShadowT1me** [comment]
> Мне кажется лучше написать "Потери на метр на ампер", а то если бы не знал о чем речь не понял бы, точнее понял бы непрапвильно. Как будто амперы теряются.

Читай внимательно и все поймешь. Поскольку он не знает англ(в чем он сам признался) я добавил поясняющую информацию для любого не знающего русский, но знающий хоть от части англ. Свои возражения, которые ты указал мне на недостаток информации лишь подтверждает твою не внимательность или не понимание, то с чем занимаешься, так что лучше молчать чем что-то говорить неся полнейший, необоснованный и неаргументированный  бред.

**Comment by SapientMC** [comment]
При чем тут какой-то "он", который не знает английского и еще какие-то "любые, не знающие русского"?
Я вообще не про описание ошибки как таковой, а конкретно про корректность перевода строки "Loss/Meter/Ampere" как "Потеря Ампер на блок".
В оригинале она означает "Потери на метр на ампер", а то, что переведено - это "потери ампер", которые еще и в вольтах измеряются почему-то.

**Comment by natzgzul89** [comment]
я сам прикалывался когда переводил)) сам то уже давно это убрал и сделал по своему.

**Comment by natzgzul89** [comment]
ShadowT1te wrote that tooltip info does not transfer to the description of the cable

**Comment by draknyte1** [comment]
Did it ever work properly, if so, when?..

None of us read Russian afaik, so speaking Russian here doesn't help to fix it..

**Comment by SapientMC** [comment]
All Russian talk not about this problem, but correct localization.

**Comment by natzgzul89** [comment]
SapientMC, на 23й сборке русский перевод везде присутствует)) такое ощущение что мод совершенно другой стал) прям весь перевод есть.

**Comment by SapientMC** [comment]
natzgzul89, ну чтож, значит кто-то неплохо поработал над этим.

**Comment by Blood-Asp** [comment]
the tmp fix did not work as intended, so i had to remove it again. did not figure out how to fix it corretly, so i will ask greg about it later.

**Comment by Blood-Asp** [comment]
This time hopefully fixed in a working way. Test the latest prebuild on Onedrive to be sure.

**Comment by natzgzul89** [comment]
http://prntscr.com/czag4y gregtech-5.09.26pre.jar

**Comment by Blood-Asp** [comment]
Try to redownload it. I cut the Numbers off from the translation, you need to edit the lang file to fit the new string.

**Comment by natzgzul89** [comment]
work, I will have to rewrite the entire file Lang?
Monday more thoroughly check the entire translation.
