### ISSUE TITLE
Wrong recipes for quintuple plates.

### ISSUE THREAD

**Issue by OneEyeMaker** [Blood-Asp/GT5-Unofficial#599]
The title says it all. Quintuple plates can be made only from **_5 quintuple_** ingots.
In `ProcessingIngot5` (https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/oreprocessing/ProcessingIngot5.java#L18) there is:

```
GT_Values.RA.addBenderRecipe(GT_Utility.copyAmount(5L, new Object[]{aStack}), GT_OreDictUnificator.get(OrePrefixes.plateQuintuple, aMaterial, 1L), (int)Math.max(aMaterial.getMass() * 1L, 1L), 96);
```

But there should be:

```
GT_Values.RA.addBenderRecipe(GT_Utility.copyAmount(1L, new Object[]{aStack}), GT_OreDictUnificator.get(OrePrefixes.plateQuintuple, aMaterial, 1L), (int)Math.max(aMaterial.getMass() * 1L, 1L), 96);
```

Please, fix it!

**Comment by DEMOOH** [comment]
Seems fine to me. Can you confirm this bug in practice?

**Comment by Dream-Master** [comment]
yes the recipe is wrong i test it and fixed it in my version allready.
