### ISSUE TITLE
Missing unification options

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#6]
When Railcraft is installed Copper, Iron, Steel and Tin Alloy plates are auto unifying into Railcraft versions. When checking unification.cfg and setting plateCopper, plateIron, plateSteel and plateTinAlloy to true under Gregtech, it still unifyies into Railcraft version.

Not a big deal since RC plates works with all the recipes requiring plates. its mostly annoying "aesthetic issue", since all the plates are becoming GT versions but not these 4.

**Comment by JasonMcRay** [comment]
Actually they are not unifying at all.... I am able to have both Railcraft Copper plates and GT Copper plates in inventory without it getting unified.

**Comment by Blood-Asp** [comment]
Railcraft crafting recipes do not use oredic, so without railcraft plates, all railcraft stuff using them is not craftable.

**Comment by JasonMcRay** [comment]
Well if i remember correctly, for example Steel plates were always unfying. Same as Iron Plates.

**Comment by Blood-Asp** [comment]
I just asked Greg. It seems the problem was the rolling machine that can't handle oredic.
Added the railcraft plates to the unification.cfg anyways. Just make sure that nothing gets broken by changeing the defaults.

**Comment by JasonMcRay** [comment]
I had it like that in InfiTech 2, and there were only few problems, which I caught and "fixed" via Minetweaker.
