### ISSUE TITLE
Breaking mining pipe can make it useless

### ISSUE THREAD

**Issue by basdxz** [Blood-Asp/GT5-Unofficial#600]
If you break the end of a mining pipe which I have done on multiple occasions, you get the generic IC2 mining pipe end block. Pretty sure this was an old IC2 bug but we can fix it. 

A way to fix it would be either to add a crafting recipe to change Mining Pipe 208 into Mining Pipe 207, making 208 drop 207 or making 208 convert into 207 when it is detected in your inventory like dusts and ingots do.

**Comment by DEMOOH** [comment]
I don't think we should. It's just a mining pipe anyway.

**Comment by Blood-Asp** [comment]
Did not happen to me so far and even then it is still a IC2 bug. not sure if adding such an recipe would not beak something else. My guess is, the mining pipe "208" should not even be dropped in the first place. Maybe you used some special tool to mine them?
