### ISSUE TITLE
Hydric Sulfide looks wrong

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#602]
When processing sulfuric fuels in a Chemical Reactor, it outputs `Hydric Sulfid` Cells with `HS` formula.

I think this is wrong, as this compound does not exists.

The real compound from natural gas and oil products is gaseous `H2S` that is toxic and smells like rotten eggs.

I'd suggest the following changes:
- Keep the actual fluid
- Change its local name to `Hydrogen Sulfide` and tool-tip formula to `H2S`.
- Add an electrolyzer recipe to split H2 gas and Sulfur dust with: 
  - Input: `2×Hydrogen Sulfide Cells + 1×Empty Cell`
  - Output: `1 Hydrogen Cell + 1 Sulfur Dust`
  - Alt Input: `2000l Hydrogen Sulfide`
  - Alt output: `1000l Hydrogen + 1×Pile OF Sulfur Dust`

Anyway, the whole hydrogen gas stuff is wrong as it has formula `H` instead of `H2`.
So if you don't want to fix the formula and name of current Hydric Sulfid, please add an electrolyzer recipe to split hydrogen and sulfur.

**Comment by Blood-Asp** [comment]
Both, name and formular are long fixed in the materials file:
https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/enums/Materials.java#L512
It also shows correctly as H2S and Hydrogen Sulfide ingame for me.

**Comment by Blood-Asp** [comment]
Also that processing only goes trough the sulfuric acid processing path is intended.
