### ISSUE TITLE
GregTech food crops

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#604]
I have noticed Pepper, Tomato, Cucumber, Onion, Tea and some other food-related crops. Are they yet obtainable? I can't seem to find any information about them in the Internet. If they are, what are their attributes (f.e. Edible, Red, Ingredient ect?) and requirements for obtaining (such as light 12+ or fertility 3+) ?

**Comment by Blood-Asp** [comment]
Nope, there is no GT way to get them. They are oredict and only to get with other mods like harvestcraft.

But adding them should not be that much work anymore by now so the idea is not bad. I would just need someone to make textures...

**Comment by Antillar** [comment]
Also, the oil: I do not have BuildCraft or other mods to add oil installed, so I found out that the only way of getting polytetrafluoroethilen for processor boards is to process oilberries, which I have to get via agriculture. It is not a big problem, but it will take roughly 15-20 hours to breed this plant to max level, so I thought that there could be another option.

I can also use bees since I have forestry installed, but this also takes plenty of time.

**Comment by leagris** [comment]
You can also process Oilsand ores that generate close to surface.
There is also Oil production with the Pyrolyze Oven.

**Comment by Antillar** [comment]
Oh, thats more "normal", I suppose. I will try to find these next time I get to play.

**Comment by leagris** [comment]
Forgot about the Oil Drilling Rig also
