### ISSUE TITLE
FTB Changelog not updated?

### ISSUE THREAD

**Issue by abculatter2** [Blood-Asp/GT5-Unofficial#606]
Is there another changelog available that details the 5.09.23 and 5.09.22 changes? I have a tendency to be blind to these things, but if there really isn't one (other then the github commits) then could someone please compile one in the FTB changelog?

http://ftb.gamepedia.com/GregTech_5_Unofficial/Experimental_Changelog

**Comment by mura3277** [comment]
Look [here](http://forum.industrial-craft.net/index.php?page=Thread&threadID=11488&pageNo=197) for the .22 changelog.

And I don't think .23 has been released yet.

**Comment by Blood-Asp** [comment]
updated FTB wiki page too.
If you want to know the changes of the .23 prebuilds, you only have the github commits
