### ISSUE TITLE
battery buffer redstone signal

### ISSUE THREAD

**Issue by natzgzul89** [Blood-Asp/GT5-Unofficial#607]
the ability to configure the emission redstone signal from the battery buffer (full, empty...)
Add a job with Gate buildcraft (energy)

**Comment by Blood-Asp** [comment]
http://ftb.gamepedia.com/Energy_Detector ?

**Comment by natzgzul89** [comment]
Yes detector reads this information and gates from buildcraft No
Gate sees only the presence of the battery inside

**Comment by Blood-Asp** [comment]
The Energy Detector gives out a redstone signal that can be used by BC gates. Direct integration is quite some work.
