### ISSUE TITLE
[Suggestion] GT Tanks and Machine-based fishing

### ISSUE THREAD

**Issue by abculatter2** [Blood-Asp/GT5-Unofficial#608]
It would be nice to have some Greggy tanks prior to the quantum tanks. Maybe have a couple tiers similar to the GT pipes? Wood could be made with wooden planks, sticks/rods, and some glass panes, and would burn if given hot fluids. Better ones can be made with metals, plastic, and/or reinforced glass.

Ideally, you'd also be able to see into the side of it to get some idea of how much fluid is in it, and be able to empty/fill it by right clicking with fluid containers. Also ideally you can put covers on it, because who doesn't want to hide their osmiridium in tank form as a part of the floorboards?

Also, a partially-joking suggestion, what about adding a way to sift, centrifuge, or otherwise process water to get fish? I would personally make it be low-energy, slow, and take a large amount of water to get the fishies, and also give a decent amount of junk like wood pulp, rotten flesh, and maybe chum.
It might also be interesting to be able to add mince meat to the recipe to increase the chance of getting fish.

EDIT: And a third suggestion, what about adding some way to make plywood blocks out of wood pulp and epoxide/glue? Possibly replacing the compressed wood pulp plate that currently exists. Plywood could have a unique texture, and possibly have a higher blast resistance and be fire proof. If you don't want to add a texture for it, it could also just take the texture of one of the vanilla wood planks. Also slabs and stairs for it, because why not.

EDIT2: Also, has a Greggy chunkloader been suggested/implemented? That would be a nice thing to have, probably have it consume ender pearls and/or eye of enders, and possibly their dusts as well, while also consuming energy.
Ideally these would also have options for how they should chunkload, such as whether or not the force load on world startup and whether or not they stop chunkloading when their player has logged off. Server owners would also probably appreciate being able to force these settings in the configs.

**Comment by OvermindDL1** [comment]
I usually just use the pipes as tanks, they hold a large amount of liquid (especially the later ones that hold a **huge** amount).

Although it would be nice to have 'open-top' tanks that can be bucketed in/out but otherwise act like a pipe.  Hmm, or a cover...

**Comment by mura3277** [comment]
Having something similar to the ExtraUtils drums (In terms of functionality) is something I've always wanted myself. A chunkloader could also be an interesting addition, possibly requiring some sort of plasma (Like the teleporter).

**Comment by OvermindDL1** [comment]
Wasn't there a block that prevents mob spawns in small area around it or a much larger area if powered?  A chunkloader that works like that would be quite nice, except only have it work one-chunk at a time and only if powered (though let it have a slot for a batter type item to hold a lot of power in case there are power fluctuations in your network if the person wants a buffer, but do not have it have a large buffer by default, only a few seconds worth for when a person wants a place to unload when 'something' is done).

It would also be nice to have a 'long-range' chunkload block.  I.E. just have it take a large wack of power to chunkload a chunk anywhere for a minute or so (perhaps depending on tier), this would allow you to automate loading and unloading chunks based on processing demand, so unload when no processing, then reload when you dump stuff into your AE system or something to start reloading your remote processing chunk, which then powers itself until its work is done then unloads again.  I've not seen such a block anywhere yet but wanted it.

**Comment by mura3277** [comment]
That's actually a really interesting idea. Maybe it could take chunk coords similar to the teleporter. Maybe only loading chunks if it has a redstone signal instead of an X amount of time since that would be easier to control for the player. Using AE level emitters combined with this chunkloader could only load an area of it's needed.

Having two types of chunk loaders (Similar to ChickenChunks) might be best. One which load a specific chunk and the other that loads a radius of chunks.

**Comment by OvermindDL1** [comment]
> Having two types of chunk loaders (Similar to ChickenChunks) might be best. One which load a specific chunk and the other that loads a radius of chunks.

That could be the 'tier' yeah.  Higher tiers use more power but load a larger area.  Two or three tiers would probably be sufficient (and would start using huge amounts of energy on the larger one anyway for a 5x5 area).

Keeping just one chunk always loaded (central AE store perhaps) and loading the others on-demand as processing needs would make for a wonderfully efficient and yet still huge base.  :-)

**Comment by draknyte1** [comment]
I messed around with Railcraft like modular tanks for GT, my idea was to have them require power depending on fluid temp/size (hardcode common fluids, since they may not be set properly by authors)

When I get back into things later in the week, I'll see what I end up with.

**Comment by Blood-Asp** [comment]
For the tanks there is an GT addon mod. I think GT++ was the name.

**Comment by draknyte1** [comment]
https://github.com/draknyte1/GTplusplus/issues/4
![2016-09-10_12 27 31](https://cloud.githubusercontent.com/assets/3060479/18407527/30c82dd8-7756-11e6-9099-8a5775918755.png)

Multiblock tanks are still on my To-do.
Chunk Loader, I'll gander at. Never touched any related code yet.

**Comment by Blood-Asp** [comment]
Added to idea collection
