### ISSUE TITLE
[Suggestion] IC2 -> GT Power converter block

### ISSUE THREAD

**Issue by Erik3003** [Blood-Asp/GT5-Unofficial#610]
Converting EU to GT electricity has always required an IC2 power storage block with a GT transformer, which is very "resource-intense" and doesn't look good. So implementing a block, that has five input sides for EU and one output for GT electricity could be a good option.

**Comment by Blood-Asp** [comment]
Not an IC2 storage block, but any IC2 power outputting block works. Direct input from an IC2 cable is not possible because of API limitations.
