### ISSUE TITLE
Extruder rod shape issue

### ISSUE THREAD

**Issue by basdxz** [Blood-Asp/GT5-Unofficial#611]
How come the extruder shape only has one hole in it whilst it makes two normal length rods? The shape should have two holes in it or better yet extruding should return a long rod. I don't remember using a saw in my extruder so please help fixing my immersion, thanks.

**Comment by Blood-Asp** [comment]
Double holes would not be realistic.  The extruder has integraded cutting. There are many other recipes that would need cutting in that case. Like tiny pipes, wires, bolts, rings and casings. And now think about all the other machines that would have the same problem...
