### ISSUE TITLE
Question: fusion reactor

### ISSUE THREAD

**Issue by Technus** [Blood-Asp/GT5-Unofficial#613]
It it planned that the fusion reactor does not consume start up cost when seamlessly switching recipes?

**Comment by Blood-Asp** [comment]
Well, i did not really plan for it, but by now it is an secret feature. So you can safe EU by having an more complex reactor startup.

**Comment by Nex4rius** [comment]
We can really use the startup cost of helium plasma and then run neutronium with it? (94% less energy required)
I don't think having 1 bucket of deuterium and tritium in the reactor at the start is really a "complex" reactor startup.

**Comment by Blood-Asp** [comment]
Well, it's "only" the startup energy you save. Doing that manually all the time is also annoying and at that point of the game, energy is not that important anymore.
