### ISSUE TITLE
Distillation tower missing air distillation recipes.

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#615]
The distillation tower recipes from air should output multiple products into dedicated slots.
Currently it only produce argon.
#### Mass sorting of air distillation:
1. Argon: 39.948 g/mol
2. Oxygen: 15.9994 g/mol
3. Nitrogen: 14.0067 g/mol
4. Helium: 4.002602 g/mol
#### Distillation ratios:
- Argon: 1/200
- Oxygen: 21/100
- Nitrogen: 39/50
- Helium: 1/20000
#### So common mean air input in distillation tower shall be:
- Input: 20000l Air
  #### Sorted outputs amounts:
- Out 1: 100l Argon
- Out 2: 4200l Oxygen
- Out 3: 15600l Nitrogen
- Out 4: 1l Helium
#### Energy requirement:

HV or more
#### Total EU per cycle
- Argon: 61440 × 100 = 6144000 EU
- Oxygen: 20480 × 200 = 4096000 EU
- Nitrogen: 2560 × 400 = 1024000 EU
- Helium: 12000 × 1 = 12000 EU
  Max of above is Argon:
  Then apply only energy cost of Argon: 6144000 EU @ 512EU/t = 12000t / 20 = 600s

**Comment by Blood-Asp** [comment]
Not default GT recipe.

**Comment by draknyte1** [comment]
I would've kept 1:20000 for helium (It's added by GT++) but the single block machine can't have a recipe for it then.. Plus with how easy it is to get from endstone, I don't see it being such a bad ratio when oxygen and the rest give far more in return. 

Afaik, Argon, oxygen and nitrogen may be added by IHL if not by GT itself.
