### ISSUE TITLE
Recipe for Naquadah alloy uses too much Argon

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#616]
1000l of Argon for 2 ingots in EBF
Did you compute how much EU and time it takes to distillate 1000l of Argon?
Cooling Argon Plasma is not an option since there is no recipe for this plasma.

**Comment by Blood-Asp** [comment]
https://github.com/asiekierka/Computronics/blob/master/src/main/java/pl/asie/computronics/integration/gregtech/GregTechRecipes.java#L206
The default GT way to produce argon is cooling compressed air cells in vacuum freezer and centrifuge them.
