### ISSUE TITLE
Missing Feature auto maintenance hatch

### ISSUE THREAD

**Issue by basdxz** [Blood-Asp/GT5-Unofficial#618]
Why is there no way to automatically use maintenance hatches? Wondering if we could get some super-high-tier-neutronium-auto-repair-thingy implemented eventually.

**Comment by draknyte1** [comment]
...or just use Tape? Pretty sure that's the point of the Braintec Aero-tape..

**Comment by PaladinOne** [comment]
BrainTech Aerospace Advanced Reinforced Duct Tape FAL-84 is a single-use catch-all fix for maintenance problems. It wasn't designed for automation, it was designed for no-tools convenience. This being said, if you can detect 'maintenance needed' and have some sort of 'autonomous activator' you could probably rig up a system to automatically run maintenance by on-signal auto-using a Duct Tape on the Hatch.

**Comment by draknyte1** [comment]
Why bother making an auto-repair hatch when the Tape is literally there to keep it fixed..
Seems sort of redundant to me, tbh.

**Comment by mura3277** [comment]
I think he is asking for a solution that does not require a player to fix maintenance problems.

**Comment by draknyte1** [comment]
Unless I missed some massive change somewhere, braintech should be fix once leave alone..

If it's not, then it should be..

**Comment by OvermindDL1** [comment]
Braintech tape is fix all problems instantly, however the fix does not last as long as fixing them properly individually with tools.

But yes, I'd say an entirely Neutronium built multi-block should have no maintenance issues.

**Comment by draknyte1** [comment]
I've never had to repair my taped multiblocks?..

Don't think it was a commit I missed..

**Comment by Blood-Asp** [comment]
I tought about adding a maintainance hatch with automatic self repair function using parts you put in.
So you craft for example average expensive repair packs and then the multiblock can autorepair up to 64 times until you have to act again.

What kept me from doing it so far was that the way it is coded. The Multiblock controller checks the maintainance hatch if something was repaired there and that every time it tries to start up. So the maintainance hatch works fully passive.
