### ISSUE TITLE
GT 5.09.23-pre2 cannot craft Naquadah Alloy in EBF

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#619]
@OneEyeMaker can you check this please?

EBF does not start Naquadah Alloy recipe.
It has:
1 LuV Energy Hatch powered by an Mk3 Nq+ reactor
16 Naquadah coil blocks with 7200 Kelvin heat capacity

Recipe for Naquadah Alloh in EBF tells me these are proper to what I provide
![capture du 2016-09-01 23-00-19](https://cloud.githubusercontent.com/assets/1111474/18184225/5832fb2e-7098-11e6-8321-6cc2bbee7aa3.png)

![capture du 2016-09-01 23-05-03](https://cloud.githubusercontent.com/assets/1111474/18184322/cd53dbee-7098-11e6-9545-51803cbf53a5.png)

Input hatch has 40000l Argon Gas as stated by NEI:
![capture du 2016-09-01 23-08-36](https://cloud.githubusercontent.com/assets/1111474/18184368/1437086a-7099-11e6-8975-52937cf0cdb5.png)

Input bus has Osmiridium ingots and Naquadah ingots:
![capture du 2016-09-01 23-10-04](https://cloud.githubusercontent.com/assets/1111474/18184416/4d5bdbca-7099-11e6-95a0-3728ce62134b.png)
![capture du 2016-09-01 23-11-03](https://cloud.githubusercontent.com/assets/1111474/18184432/605aadc8-7099-11e6-92dc-16c3bcd3db35.png)

Soft Mallet does not even start/blink or consume resources.

Other recipes works fine in this EBF.

Maybe Naquadah Coil blocks should have 7201 Kelvin instead of just 7200 like the Naquadah Alloy Coils have 9001K to support Naquadria with 9000K

**Comment by Technus** [comment]
Are you sure that the energy input tier is high enough?

also the heat capacity works like:
(Energy_Hatch_Tier-1)*100 +Coil_Base

(9001 is a meme not a required thing)

**Comment by leagris** [comment]
Energy Input is LuV (32768EU/t)
Generator is Fluid Naquadah MkIII witch output 32768EU/t
If energy input was not enough the controller block would blink once, ingots and argon gas would be consumed and no output produced.
Here the recipe does not even enter the processing stage.

Still as it is a modpack. There is a possibility of conflicting registration of the Argon gas by IHL Tools And Machines or Computronics mods.

**Comment by leagris** [comment]
Ok probably found the culprit:

#### From level.dat
```yaml
GalacticraftMars:liquidargon
GalacticraftMars:argon
gregtech:plasma.argon
```

#### From Minetweaker report
```javascript
<liquid:argon>, Argon Gas
<liquid:liquidargon>, Liquid Argon
<liquid:plasma.argon>, fluid.plasma.argon
```

**Comment by leagris** [comment]
ok finally got it working and identified the cause.

Input hatch was full, had argon cells waiting in input slot and empty cells waiting in output slot.
Once I removed the cells from the input hatch, the EBF started processing.
Very weird glitch.
