### ISSUE TITLE
The dismantling machine doesn't start to work.

### ISSUE THREAD

**Issue by n2o2333** [Blood-Asp/GT5-Unofficial#62]
I gave the dismantling machine electricity and put a machine into it,but it could't work.I hope the bug will be repaired,thanks very much.

**Comment by Blood-Asp** [comment]
The machine/item/tool/whatever needs a proper NBT tag telling you what it is made of to be disassembling.
The easiest way to test NBT tags in most modpacks is with minetweaker. If you have it in, just hold the item you want to recyce in your hand and type: /mt hand
