### ISSUE TITLE
Strange limitation of item pipe output quantity

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#622]
Setup: Brass Item Pipe, one input (barrel with lots of pumpkins) and 20 outputs (LV centrifuges), HV Conveyor Module in Import mode near barrel.
It never fills more than 16 centrifuges.

Same setup but with MV centrifuges - never fills more than 8 on them.

Seems like Item Pipe transfers not actually "one stack per sec", but "not more than 1 stack between input and just one of outputs". So it can't fill more than one centrifuge per second and total not more than duration of one work circle in seconds.

In my setup real transfer rate of Brass Item Pipe is just one item per sec... 64 times lower than expected.

Hope it could be fixed.
The only workaround i see - to use item pipes from another mode for pumpkin centrifuge line.

**Comment by DEMOOH** [comment]
Can you post some screenshots of your setup?

**Comment by SapientMC** [comment]
LV
![2016-09-05_12 02 46](https://cloud.githubusercontent.com/assets/14032818/18244540/3c4d9490-7369-11e6-8e62-32d9ed7839ef.png)
![2016-09-05_12 02 52](https://cloud.githubusercontent.com/assets/14032818/18244548/452c7fae-7369-11e6-97d1-7ff9d225b29c.png)
![2016-09-05_12 02 59](https://cloud.githubusercontent.com/assets/14032818/18244549/454dad14-7369-11e6-8964-2d99f2021e68.png)

MV
![2016-09-05_12 03 09](https://cloud.githubusercontent.com/assets/14032818/18244551/4568a68c-7369-11e6-90ff-c1524138ebbd.png)

**Comment by DEMOOH** [comment]
I played with your setup and couldn't really improve your result (15 mv centrifuges with hell lot of shutters and restrictive pipes). GT pipes are dumb, they are just inventories with a capacity equal to their speed per second. The speed is nominal and true only with the easiest setups.
You should use "smart" network-based pipes from other mods to deal with such heavy load.

**Comment by natzgzul89** [comment]
SapientMC я в этом случае в стыки между труб добавлял модули на выталкивание предметов в следующую трубу. правда я это делал с водой)

**Comment by SapientMC** [comment]
У жидкостных труб совсем другая механика.

**Comment by natzgzul89** [comment]
да, но у них была другая проблема. они в интерфейс воду не могли прогнать через 128 труб. с предметами я так делал, в итоге начал использовать ограничительные трубы.

**Comment by SapientMC** [comment]
Ничче не понял. При чем тут вода и ограничительные трубы?

**Comment by natzgzul89** [comment]
для начала я пытался передавать по предметным трубам ресурсы, когда они начали зависать в трубах я использовал модули для их проталкивания между труб. потом надоело, стал использовать ограничительные трубы. на воде была проблема как с предметами стал сразу использовать помп модули.

**Comment by DEMOOH** [comment]
Also you can try to use electrum pipes, they are quite cheap.

**Comment by natzgzul89** [comment]
and platinum is also not particularly expensive.

**Comment by SapientMC** [comment]
Ну в данном-то случае зависаний не происходит. Просто не успевают.

**Comment by SapientMC** [comment]
Theoretical transfer rate of pipes and conveyor are more than enough for all my centrifuges. I'd like to use GT pipes, but forced to use Item Conduits instead of them.

**Comment by natzgzul89** [comment]
1 стак в секунду. трубы рассчитывают так что будет принимать предметы 60 раз за минуту. каждые 14 секунд перерабатывается 1 тыква. т.к. все центрифуги работают не одновременно (доли секунды разницы) труба передает через себя не стаками предметы, а частями. по этому все центрифуги не получают тыквы.

**Comment by SapientMC** [comment]
Понимаю. Я собственно примерно это и описал. На мой взгляд раз в секунду она должна забирать стэк со входа и пытаться отправлять его на все имеющиеся выходы, куда можно, а не удовлетворяться только одним.

**Comment by natzgzul89** [comment]
Даже если будет забирать стак,  то около 10% машин не будет получать ресурсы постоянно. Внутренний буфер трубы 1 стак. Все машины будут требовать ресурсы в разное время. Можно попробовать установить на машины контроллеры и через беспроводную сеть включать их разом все когда они будут заполнены. Если машины будут все в 1 чанке то теоретически все должно работать

**Comment by SapientMC** [comment]
Так проблема в том, что если две машины запрашивают одновременно, и обоим нужно по одному предмету из этого стэка, то получит только одна. И это косяк. Должны получить все кто хотят, в сумме не более стэка.

**Comment by Technus** [comment]
For me the only proper way of making setup like that in gt is with processing array

**Comment by leagris** [comment]
> For me the only proper way of making setup like that in gt is with processing array

When you have the tech-level, energy and material for processing arrays, chances are you don't need to centrifuge pumpkins for methane.

**Comment by Blood-Asp** [comment]
The change that has to be done, is that the pipe continues to search for outputs until its input stack is empty, or no other output inventory is to be found along the whole pipe.

The current way is to lag as little as possible when transferring items, but i must say that i'm also annoyed with that current behavior.
