### ISSUE TITLE
please update

### ISSUE THREAD

**Issue by danielkanjo** [Blood-Asp/GT5-Unofficial#623]
please update it to 10.13.4.1614-1.7.10i want to use it :) but it's not working with the latest forge and mods :S

**Comment by Blood-Asp** [comment]
It does work. I use that version myself.

**Comment by danielkanjo** [comment]
what version of the mod?

**Comment by danielkanjo** [comment]
i had gt 5.09.22 it don't work :S

**Comment by mura3277** [comment]
Crash report? log?

**Comment by danielkanjo** [comment]
it's not crashing just won't to start new world or load my save when i click on the start new world and client kick me out to the main menu and nothing happening i try to read the log or the crash but nothing in that two folder :S

**Comment by mura3277** [comment]
How do you know it's an issue with GT?

Also, you need to put the contents of minecraft/logs/fml-client-latest.log on something like pastebin

**Comment by danielkanjo** [comment]
hmm i've played FTB infinity evolved mod pack and it's worked when put the GT it's stoped i'll upload my log wait a second :)

**Comment by Blood-Asp** [comment]
Thats likely a problem with mod interactions. There are a few mods that do not work together fine with GT.

**Comment by danielkanjo** [comment]
https://www.mediafire.com/?pdqitwu6qyc1rgq

there is my latest log file :)

**Comment by Muramasa-** [comment]
I've seen that issue before. The problem is with the denseores mod. It's interaction with IC2 has issues when GT is loaded for it's processing recipes.

**Comment by Blood-Asp** [comment]
```
[09:11:17] [Server thread/ERROR] [FML/]: Caught exception from denseores
java.lang.RuntimeException: ambiguous recipe: [[1xtile.denseores:block0@0] -> [4xtile.oreIron@0]]
    at ic2.core.BasicMachineRecipeManager.displayError(BasicMachineRecipeManager.java:306) ~[BasicMachineRecipeManager.class:?]
    at ic2.core.BasicMachineRecipeManager.addRecipe(BasicMachineRecipeManager.java:40) ~[BasicMachineRecipeManager.class:?]
```

Dense Ores is adding a recipe double to IC2 because GT did that all before. So remove dense ores as GT takes over the oregen anyways.

**Comment by danielkanjo** [comment]
i'll try it now :) if it's i would be happy :) i love the old days of gregtech :)

**Comment by danielkanjo** [comment]
thanks it's worked :)
