### ISSUE TITLE
Unofficial 1.10.2 Port.

### ISSUE THREAD

**Issue by Dragon2488** [Blood-Asp/GT5-Unofficial#624]
About mouth ago i asked for 1.10.2 port. I noticed that port hasnt even was started, so I started my own port. Now it's almost complete, most things implemented and work perfectly. However I don't know what to do after port. Pull requesting a branch isn't looking nice, however GT will die without new features and just ports. So there is question: Should I develop port myself or it will be better if it will be pull requested to main reppo.

@Blood-Asp 

[https://github.com/Dragon2488/GT5-Unofficial](The port is here)

**Comment by OvermindDL1** [comment]
Makes sense to dev it in a new branch here I would say.

**Comment by Blood-Asp** [comment]
Wow, that was unexpected. I did a little work on porting, but mostly to look how the changes beween 1.7 and 1.10 are in the first place.

Personally i would recommend adding it here as a new branch. I can add you as Collaborator and then you can manage that branch without me in the way. I would continue pushing new stuff to the exterminental branch until i'm done with 1.7. 

PS. Your link is broken. ;)

**Comment by Dragon2488** [comment]
Ok, thanks.

**Comment by Blood-Asp** [comment]
Invited you.

You can open your own 1.10 branch and freely work with it. Bugfixes are also always fine on other branches, just changes to GTs content i would prefer you ask before.

How many hours did it take you to port GT so far? Looking trough the commits seems to be quite a lot of work.

**Comment by Dragon2488** [comment]
Well, nearly 3-4 weeks for 4-5 hours a day.

**Comment by Speiger** [comment]
@Dragon2488 i found a little bug. (LagSource & Memory leak)
You need to cache the backed quads that you created so that you do not always recreate them when a world rerendering is happening (chunk updates). I had that issue when i made cables without cache and it really starting to drop my FPS&Free Memory when i placed hundreds of them...

**Comment by Dragon2488** [comment]
@Speider. According to code, quads returned by models arent stored anywhere, so after they are rendered, they will be fastly removed. Same thing about ITexture objects. So it doesnt leak any memory or causing lag spikes

**Comment by Speiger** [comment]
@Dragon2488 just for the notes.
I think we solved that now on discord.
