### ISSUE TITLE
gregtech-5.09.23 Crash

### ISSUE THREAD

**Issue by ShelfOwl** [Blood-Asp/GT5-Unofficial#625]
GT5.09.23NewMatsSystem-3 crashed with small number of mods.
Roughly saw the code, it seems to have dependency to Forestry.

mods:
[modsList.txt](https://github.com/Blood-Asp/GT5-Unofficial/files/465668/modsList.txt)

crash log:
[crash-2016-09-11_07.18.58-client.txt](https://github.com/Blood-Asp/GT5-Unofficial/files/465667/crash-2016-09-11_07.18.58-client.txt)

edit: wrong version

**Comment by mura3277** [comment]
Again, another material oversight. Fixed in unstable branch.
