### ISSUE TITLE
Cannot make EBF in 5.09.23NewMatsSystem-3

### ISSUE THREAD

**Issue by ShelfOwl** [Blood-Asp/GT5-Unofficial#626]
hence Invar removed.

**Comment by Blood-Asp** [comment]
you sure that is the pre3 build? sounds more like .23NewMatsSystem-3 which is an other dev branch.

**Comment by ShelfOwl** [comment]
Sorry. you are right.

**Comment by mura3277** [comment]
My mistake, I made Invar only generate if Thermal Foundation is loaded. Fixed in unstable branch.
