### ISSUE TITLE
1.10.2

### ISSUE THREAD

**Issue by mightydanp** [Blood-Asp/GT5-Unofficial#627]
I tried to do a build jar version of you 1.10.2 to do some bug hunting and it gives me this

C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\api\util\GT_Utility.java:1580: error: diamond operator is not supported in -source 1.6
        ArrayList<String> tList = new ArrayList<>();
                                                ^
  (use -source 7 or higher to enable diamond operator)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\api\world\GT_Worldgen_Ore_Normal.java:84: error: lambda expressions are not supported in -source 1.6
    public static Predicate<IBlockState> STONE = input ->
                                                       ^
  (use -source 8 or higher to enable lambda expressions)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\blocks\GT_Block_Machines.java:61: error: diamond operator is not supported in -source 1.6
    public static ThreadLocal<IGregTechTileEntity> mTemporaryTileEntity = new ThreadLocal<>();
                                                                                          ^
  (use -source 7 or higher to enable diamond operator)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\blocks\GT_Block_Ores_Abstract.java:43: error: diamond operator is not supported in -source 1.6
    public static ThreadLocal<GT_TileEntity_Ores> mTemporaryTileEntity = new ThreadLocal<>();
                                                                                         ^
  (use -source 7 or higher to enable diamond operator)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\blocks\GT_TileEntity_Ores.java:135: error: lambda expressions are not supported in -source 1.6
            if (aOverridingStoneBlock.isReplaceableOreGen(worldObj.getBlockState(getPos()), this.worldObj, getPos(), state -> state.getBlock() == Blocks.NETHERRACK)) {
                                                                                                                           ^
  (use -source 8 or higher to enable lambda expressions)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\blocks\GT_TileEntity_Ores.java:177: error: diamond operator is not supported in -source 1.6
        ArrayList<ItemStack> rList = new ArrayList<>();
                                                   ^
  (use -source 7 or higher to enable diamond operator)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\GT_Client.java:39: error: diamond operator is not supported in -source 1.6
    private final HashSet mCapeList = new HashSet<>();
                                                  ^
  (use -source 7 or higher to enable diamond operator)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\GT_Client.java:163: error: lambda expressions are not supported in -source 1.6
        RenderingRegistry.registerEntityRenderingHandler(GT_Entity_Arrow.class, manager -> {
                                                                                        ^
  (use -source 8 or higher to enable lambda expressions)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\GT_IC2RecipesHandler.java:17: error: diamond operator is not supported in -source 1.6
    private HashMap<RecipeInputWrapper, RecipeIoContainer> recipes = new HashMap<>();
                                                                                 ^
  (use -source 7 or higher to enable diamond operator)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\GT_Proxy.java:912: error: diamond operator is not supported in -source 1.6
                            .onHarvestBlockEvent(new ArrayList<>(aEvent.getDrops()), aStack, aEvent.getHarvester(),
                                                               ^
  (use -source 7 or higher to enable diamond operator)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\items\armor\ModularArmor_Item.java:342: error: diamond operator is not supported in -source 1.6
            List<PotionEffect> effects = new LinkedList<>(aPlayer.getActivePotionEffects());
                                                        ^
  (use -source 7 or higher to enable diamond operator)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\items\behaviors\Behaviour_Plunger_Item.java:40: error: diamond operator is not supported in -source 1.6
                for (Object tTileEntity : GT_Utility.sortMapByValuesAcending(IMetaTileEntityItemPipe.Util.scanPipes((IMetaTileEntityItemPipe) tMetaTileEntity, new HashMap<>(), 0L, false, true)).keySet())
                                                                                                                                                                           ^
  (use -source 7 or higher to enable diamond operator)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\items\behaviors\Behaviour_Prospecting.java:50: error: lambda expressions are not supported in -source 1.6
        if ((block.isReplaceableOreGen(blockState, aWorld, blockPos, state ->
                                                                           ^
  (use -source 8 or higher to enable lambda expressions)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\items\behaviors\Behaviour_Scanner.java:27: error: diamond operator is not supported in -source 1.6
            ArrayList<String> tList = new ArrayList<>();
                                                    ^
  (use -source 7 or higher to enable diamond operator)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\render\newblocks\BlockRenderer.java:124: error: diamond operator is not supported in -source 1.6
                ArrayList<BakedQuad> quads = new ArrayList<>();
                                                           ^
  (use -source 7 or higher to enable diamond operator)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\render\newblocks\IBlockIconProvider.java:19: error: default methods are not supported in -source 1.6
    default TextureAtlasSprite getIcon(IBlockAccess world, BlockPos pos, EnumFacing aSide, int metadata) {
    ^
  (use -source 8 or higher to enable default methods)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\render\newitems\GT_IIconProvider_Item_Model.java:132: error: diamond operator is not supported in -source 1.6
            ArrayList<BakedQuad> resultQuads = new ArrayList<>();
                                                             ^
  (use -source 7 or higher to enable diamond operator)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\render\newitems\IItemIconContainerProvider.java:13: error: default methods are not supported in -source 1.6
    default TextureAtlasSprite getIcon(ItemStack stack, int pass) {
    ^
  (use -source 8 or higher to enable default methods)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\render\newitems\IItemIconProvider.java:13: error: default methods are not supported in -source 1.6
    default int getRenderPasses(ItemStack stack) {
    ^
  (use -source 8 or higher to enable default methods)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\render\newitems\ModelUtil.java:25: error: try-with-resources is not supported in -source 1.6
            try (InputStreamReader reader = new InputStreamReader(resource.getInputStream())) {
                ^
  (use -source 7 or higher to enable try-with-resources)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\common\tileentities\generators\GT_MetaTileEntity_MagicalEnergyAbsorber.java:25: error: diamond operator is not supported in -source 1.6
    public static final ArrayList<EntityEnderCrystal> sUsedDragonCrystalList = new ArrayList<>();
                                                                                             ^
  (use -source 7 or higher to enable diamond operator)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\GT_Mod.java:989: error: diamond operator is not supported in -source 1.6
        ArrayList<RecipeOutput> outputs = new ArrayList<>();
                                                        ^
  (use -source 7 or higher to enable diamond operator)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\loaders\misc\GT_Achievements.java:37: error: diamond operator is not supported in -source 1.6
    public static List<Materials> oreList = new ArrayList<>();
                                                          ^
  (use -source 7 or higher to enable diamond operator)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\loaders\misc\OreProcessingConfiguration.java:18: error: diamond operator is not supported in -source 1.6
        this.mEnabledMaterials = new HashMap<>();
                                             ^
  (use -source 7 or higher to enable diamond operator)
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\loaders\postload\ChestGenHooks.java:23: error: diamond operator is not supported in -source 1.6
    private static final HashMap<ResourceLocation, ArrayList<LootEntryItem>> lootEntryItems = new HashMap<>();
                                                                                                          ^
  (use -source 7 or higher to enable diamond operator)
40 errors
1 warning
:compileJava FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileJava'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4 mins 35.612 secs

C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2>gradlew Jar
This mapping 'snapshot_20160518' was designed for MC 1.9.4! Use at your own peril.
###### 

```
     ForgeGradle 2.2-SNAPSHOT-c438b06
```

  https://github.com/MinecraftForge/ForgeGradle
###### 

```
           Powered by MCP unknown
         http://modcoderpack.com
     by: Searge, ProfMobius, Fesh0r,
     R4wk, ZeuX, IngisKahn, bspkrs
```
###### 

Version string '5.09.22' does not match SemVer specification
You should try SemVer : http://semver.org/
:extractMcpMappings
:deobfCompileDeobfDepTask0 SKIPPED
:deobfCompileDeobfDepTask1 SKIPPED
:deobfCompileRemapDepSourcesTask2 SKIPPED
:deobfCompileRemapDepSourcesTask3 SKIPPED
:deobfCompileDummyTask
:getVersionJson
:extractUserdev UP-TO-DATE
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:applyBinaryPatches SKIPPED
:deobfProvidedDummyTask
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:genSrgs SKIPPED
:deobfMcMCP SKIPPED
:sourceApiJava UP-TO-DATE
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:sourceMainJava UP-TO-DATE
:compileJava
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\asm\ASM.java:3: error: package javassist does not exist
import javassist.*;
^
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\asm\ASM.java:11: error: cannot find symbol
    private static ClassPool pool = ClassPool.getDefault();
                   ^
  symbol:   class ClassPool
  location: class ASM
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\asm\ASM.java:11: error: cannot find symbol
    private static ClassPool pool = ClassPool.getDefault();
                                    ^
  symbol:   variable ClassPool
  location: class ASM
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\asm\ASM.java:14: error: cannot find symbol
        pool.appendClassPath(new LoaderClassPath(Thread.currentThread().getContextClassLoader()));
                                 ^
  symbol:   class LoaderClassPath
  location: class ASM
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\asm\ASM.java:15: error: cannot find symbol
        pool.appendClassPath(new LoaderClassPath(ClassLoader.getSystemClassLoader()));
                                 ^
  symbol:   class LoaderClassPath
  location: class ASM
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\asm\ASM.java:21: error: cannot find symbol
            pool.appendClassPath(new ByteArrayClassPath(s1, bytes));
                                     ^
  symbol:   class ByteArrayClassPath
  location: class ASM
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\asm\ASM.java:22: error: cannot find symbol
            CtClass ctClass = pool.getOrNull(s1);
            ^
  symbol:   class CtClass
  location: class ASM
C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2\build\sources\main\java\gregtech\asm\ASM.java:25: error: cannot find symbol
                CtMethod method = ctClass.getDeclaredMethod("getModelForState");
                ^
  symbol:   class CtMethod
  location: class ASM
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
8 errors
:compileJava FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileJava'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 33.367 secs

C:\Users\chris\Desktop\GT5-Unofficial-1.10.2\GT5-Unofficial-1.10.2>

the one thing i had to change is that i added this to get ity to build properly 

targetCompatibility = "1.8"

sourceCompatibility = "1.8"

**Comment by Dragon2488** [comment]
Well, first you need to add to a manifest coremod gregtech.asm.ASM and javassist to final jar. Secondly, you're setting java version wrong. It need to be inside compileJava block. I'll fix buildscript in 3-4 hours, just wait.

**Comment by Blood-Asp** [comment]
Also the forge version is too old for JEI.
