### ISSUE TITLE
problem 5.09.23pre6

### ISSUE THREAD

**Issue by natzgzul89** [Blood-Asp/GT5-Unofficial#629]
problem in displaying values after translation into Russian: liquid pipe, cables, wires, item pipe (only displays the speed)
![screenshot_1](https://cloud.githubusercontent.com/assets/20620700/18434871/1036db94-791a-11e6-8733-fe50d6ebdca4.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/20620700/18434872/1039ce4e-791a-11e6-80c0-87fcc5109f13.png)
will be able to translate multi-block problem?
![screenshot_3](https://cloud.githubusercontent.com/assets/20620700/18434915/4bde0320-791a-11e6-8fff-683df6b33b59.png)
and the possibility of other translate
![screenshot_4](https://cloud.githubusercontent.com/assets/20620700/18434945/6f7dc194-791a-11e6-8829-678297c4d76b.png)

It is also interested in the opportunity to highlight the text, as is done with the word imagination
"§5В§dо§4о§cб§eр§aа§bж§3е§9и§1е§5.§r" "Воображение."
There is a table for the characters under each color? and the order of the characters?
"§r" before the text          "§5В§dо§4о§cб§eр§aа§bж§3е§9и§1е§5.§r" colored text

**Comment by Dragon2488** [comment]
Чувак, ты действительно кэп, раз впервые узнаешь о цветовых кодах.

**Comment by natzgzul89** [comment]
Я не обращал внимание на них просто, пока информация не отображалась.

**Comment by natzgzul89** [comment]
5.09.23pre6 
![screenshot_1](https://cloud.githubusercontent.com/assets/20620700/18591068/5385ff12-7c5b-11e6-954f-a263b4efbf39.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/20620700/18591088/658a4fb0-7c5b-11e6-99d1-5d2647274003.png)

https://github.com/Blood-Asp/GT5-Unofficial/issues/595

**Comment by Blood-Asp** [comment]
reopend first issue.
