### ISSUE TITLE
Is this a gregtech error?

### ISSUE THREAD

**Issue by xXGandalfXx** [Blood-Asp/GT5-Unofficial#63]
http://pastebin.com/w6dU5uMP

This error appeared for the first time? I dont know why

**Comment by Blood-Asp** [comment]
More informations please. When does this error appear? Does is allways appear or only at certain places/times? What did you do in that moment? Is that on a new or old world? Did you update before this, if yes, what did you update?

**Comment by xXGandalfXx** [comment]
Yes, this error appears allways on joining the server. In a mystcraft world. I teleported me out of mystcraft and this error is disappeared.

**Comment by Blood-Asp** [comment]
does this happen in all mystcraft dimensions, or only in special ones? If it is only in one, do you know the way it generates in there(used pages)?

**Comment by Blood-Asp** [comment]
Can't really find the reason for this crash, so close for now.
