### ISSUE TITLE
[1.10.2]

### ISSUE THREAD

**Issue by mightydanp** [Blood-Asp/GT5-Unofficial#630]
I was looking around the world in creative mode and could not see or spot any ores.

**Comment by mightydanp** [comment]
Update: it appears only hydrogen spawns, and sometimes the texture would glitch out and turn every gregtech block black.

**Comment by mightydanp** [comment]
update. when i press r or u with nei and jui some of the recipes are extremely off, for example when i press u on andisite apparently you can make Perditio axe heads , arrows, and you can apparently cut it onto wenge planks.

**Comment by Dragon2488** [comment]
No, ores spawn perfectly, it's just tile entity sync glitches. Tried myself. I dont know about andesite, it's very strange

**Comment by Dragon2488** [comment]
The issue in ores that they aren't tick -> aren't sync to clients. I wrote my own sync handler, however it sometimes works very strange. There should be a better solution. 
@Blood-Asp, any ideas?

**Comment by mightydanp** [comment]
its not just andisite its alot of other blocks to, but it is strange. I just wish NEI didnt require JEI now

**Comment by Dragon2488** [comment]
About texture glitches. 1.10.2 is extremely strange and broken. It shades IBakedModels to black by applying strange lightning. The best solution that i find is getPackedLightmapCoords method in block. I'll re-implement it for better behaivor today.

**Comment by Dragon2488** [comment]
Try to make recipes that jei show. If they arent work, that i need own JEI handler for gregtech crafting recipes.

**Comment by mightydanp** [comment]
the recipes that show the granite do not work. but one thing i saw is that the cables are just boxes for now.

**Comment by Dragon2488** [comment]
I know, i havent implemented their thickness yet

**Comment by mightydanp** [comment]
So the onlything you dont know how to fix is the server to client on the ores ?

**Comment by Dragon2488** [comment]
I have already fixed it and it worked in dev. However fix doesnt work now and ugly a bit

**Comment by mightydanp** [comment]
Hopfully it can gey easly resolved i am looking foward to finding more bugs

**Comment by mura3277** [comment]
@mightydanp You might be best just waiting for an official test build. It is still a WIP from my understanding and likely many issues that @Dragon2488 is aware of.

I'm sure he'll be releasing a build for everybody to test when the time is right.

**Comment by Dragon2488** [comment]
Well, after texture glitches fix and ore sync it should be ready for first alpha

**Comment by mightydanp** [comment]
im just helping him find some bugs before he realeases. its why i was testing it to help him.

**Comment by Dragon2488** [comment]
About black textures. I'll make them always full bright, because mojangs are brainless.

**Comment by mightydanp** [comment]
i wonder if you can check to light level to set the brightness

**Comment by Dragon2488** [comment]
yes, I can CHECK light level, but i can't make it work properly.

**Comment by mura3277** [comment]
@Dragon2488 Is this something you know how to fix? #575

**Comment by Dragon2488** [comment]
This issue lives on 1.10.2 too.

**Comment by Dragon2488** [comment]
I really annoed with lightning issues on porting. So i won't fix any lightning problems anymore. Ores sync and most of lightning fixed. Everything is almost work and ready for alpha build.

**Comment by Dragon2488** [comment]
For now I'll finished. The mod is playable.
@Blood-Asp

**Comment by mightydanp** [comment]
On

**Comment by Blood-Asp** [comment]
@Dragon2488 Should i put a alpha build on the forum? Can you make a list of known issues, so there are no double reports?
Also how much do you plan to continue working on that branch? When others make PRs for that branch, it might be better for you to be the one merging it.
And last point: Better communication than only github would be good. You are on Discord? I'm typicly on the InfiTech2 chat, but at this point i think opening a GT chat might be a good idea.

**Comment by OvermindDL1** [comment]
Come to https://gitter.im/Blood-Asp/GT5-Unofficial already.  ;-)

**Comment by Dragon2488** [comment]
Yes, you should put alpha build. I'll maintain branch as long as i can, however help is really a thing. Fixes/additions/ideas are always welcome.

Known issues:
*Any lightning bugs -> Fixed
*Full-block-wide wires 
*Ore sync issues (sometimes?) -> Fixed

Yes, i'm in Discord, but aren't in InfiTech2 chat (but play on InfiTech2 since August). GT chat is a good idea. If you'll do it, please post invite here.

**Comment by Blood-Asp** [comment]
I'm thinking about how to name the 1.10 releases.
Upping the GT version to 5.10.xx? Seems the best to me, or does someone have better ideas?

**Comment by mightydanp** [comment]
That sounss good because 5 is the version of gregtech and 10 is minecraft version. And the . After would be the build number.

**Comment by Dragon2488** [comment]
@Blood-Asp Have you created GT chat? If so, give invite please (or at least invito to InfiTech2 chat)

**Comment by Blood-Asp** [comment]
Just created GT chat: https://discord.gg/7qqsmX7

InfiTech2 would be here: http://discord.gg/0jo51aWck9kbqIRf For now there are more active.
