### ISSUE TITLE
Crashing without JEI (1.10.2)

### ISSUE THREAD

**Issue by kojul** [Blood-Asp/GT5-Unofficial#635]
@Dragon2488 GT5u in 1.10.2 crashes if JEI isn't present. I can't imagine playing modded without it, but just thought you should know. Recommended fix is either making it a dependency or adding the api to the source.

Log: https://gist.github.com/kojul/fb99f63fa932f70249897724bf160127

**Comment by Dragon2488** [comment]
Lol, it's a feature. 
Yes, i'll fix it on days.
