### ISSUE TITLE
[1.10.2] JEI recipe text overlap

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#637]
Not sure if there is something it can be done on GT side, but I thought i will let you know.

Certain recipes are overlapping the text on the bottom.
![2016-09-17_18 33 51](https://cloud.githubusercontent.com/assets/4236895/18609576/808dfad2-7d05-11e6-9c30-3e2e487720f1.png)

There is unnecesary free space on top... But as I said... it might be something for JEI, if it is. Let me know and I will repost this to them.

**Comment by Dragon2488** [comment]
I don't know how to expand basic recipe gui height and amount of recipes on page. @mezz

**Comment by mezz** [comment]
Jei lays out the recipes automatically based in the size of the background IDrawable. You can crop the background closer to the top and give it some padding on the bottom for the extra text.

**Comment by Dragon2488** [comment]
It's cool, but can I set it explicitly?

**Comment by mezz** [comment]
There's no way to set it directly, no. If you need more per page, make your recipe less tall so that they can fit.

**Comment by Dragon2488** [comment]
Okay, another question. If user want to view recipes of Copper Ingot and it's registered in ore dictionary like ingotCopper, can JEI show all recipes that output any item with ingotCopper? It was very cool feature of NEI

**Comment by mezz** [comment]
I'm not sure I understand the question. Did you try it out in-game?

**Comment by Dragon2488** [comment]
Yes, i did. JEI shows only recipes of Copper Ingot, ignoring all recipes outputing same ore dictionary name.

**Comment by mezz** [comment]
When you look up the uses for a copper ingot, you should see all recipes that can accept it. If there are multiple copper ingot types accepted in one ingredient slot, it will only show the one you're looking up at that time instead of rotating through all the ingots.

**Comment by Dragon2488** [comment]
..... I want to look up recipes that OUTPUT any copper ingots.

**Comment by mezz** [comment]
Recipes only output one type of ingot, you can't output an OreDictionary value from a recipe. Wouldn't it be misleading to show all the OreDictionary ingots? There are cases like Pam's Harvestcraft that use the OreDictionary for things like "all meats" or "all food", if I looked up by those OreDictionary tags you would never find what you are looking for.

**Comment by Dragon2488** [comment]
Yes, i know. But when I want to view ways to obtain copper ingot, can it show all recipes which output is registered in ore dictionary like copper ingot. Example:

Copper Ore (GT) -> Copper Ingot (GT) (ingotCopper)
Copper Dust (Immersive Engineering) -> Copper Ingot (Immersive Engineering) (ingotCopper)

When I click on Copper Ingot from GT, i also want to view recipe of IE Copper Ingot, because both of them have got ingotCopper ore dictionary name.

Is my english so bad or you just can't understand what I want?

**Comment by mezz** [comment]
Unfortunately OreDictionary is not the same as "equal" so I can't reliably look up things that way.
There are cases like Pam's Harvestcraft that use the OreDictionary for things like "all meats" or "all food", if I looked up by those OreDictionary tags you would never find what you are looking for.
There are recipes like "bone block -> bonemeal" that do not work either. Imagine I look up "floral white powder" which has OreDictionary "dye white" (which is shared with bonemeal), it shouldn't show a recipe for "bone block -> floral white dye".

**Comment by Dragon2488** [comment]
It shouldn't, of course. Test that item have got only one ore dictionary tag and recipe accepts ore dictionary. If clicked on item on right panel, show all recipes that output same ore dictionary tag.

**Comment by mezz** [comment]
I don't think that solves it, the Bonemeal case only has one OreDict tag.

**Comment by Dragon2488** [comment]
Well, than only test if recipe accepts ore dictionary or item was clicked on right panel. I don't know how, but NEI did it.

**Comment by mezz** [comment]
If you find out how please send me a PR, it sounds useful.

**Comment by Dragon2488** [comment]
Well, than can you please make it at least for ingots, dusts, gems and nuggets please? @mezz
