### ISSUE TITLE
New ultra-strong alloy

### ISSUE THREAD

**Issue by Antillar** [Blood-Asp/GT5-Unofficial#640]
The Alloy Ti3Au is known for quite some time, and it has proven to be much more resilient than Ti. Scientists are planning to create prothesises from it. I suggest adding it to the mod for onbe of the final tiers of the machines. Below is gif image of its molecular structure, where it is shown that atoms of Ti and Au support each other which makes this alloy very durable.
![1474197315135665034](https://cloud.githubusercontent.com/assets/12700019/18616458/c2d21328-7dc4-11e6-8b72-f418ee93b542.gif)

**Comment by Blood-Asp** [comment]
Added to idea collection
