### ISSUE TITLE
[1.10]Starting axe does not look like a flint axe

### ISSUE THREAD

**Issue by xbony2** [Blood-Asp/GT5-Unofficial#646]

**Comment by Dragon2488** [comment]
It's fire enchantment glitch. It's really flint axe, trust me.

**Comment by xbony2** [comment]
It is, I'm just reporting the display glitch :P

**Comment by Reknot** [comment]
Got the same problem.

**Comment by Dragon2488** [comment]
Well, seems like its common for all items with black-tons textures
