### ISSUE TITLE
pre7 build issue with client-side update of scanner machine block

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#647]
gregtech 5.09.23-pre7 has bug preventing client to receive machine block meta that affect all tiers of Scanner

![Advanced scanner II seen by client before forcing a client update with NBTEdit](https://cdn.discordapp.com/attachments/225549886219747328/229724612844322826/unknown.png)

A client update can be forced with In-Game NBTEdit
[Here is the log for NBedit](https://pastebin.com/hKHm7iAZ)

NBT Data seems perfectly conform to what it should be.
Just note that client cannot display or interact properly because it does not know what machine block it is.

It affect all tiers of the Scanner machine. Have not noticed the issue with other machine blocks.

**Comment by mura3277** [comment]
Fixed with 97d7efc
