### ISSUE TITLE
Every start generates new lines in recipes.cfg

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#65]
Everytime I start my modpack the recipes.cfg file is getting bigger and bigger. Every start inside it it generates entries for "wierd" items under "canning" group. Here are some examples:

> I:"extrabiomes.items.ItemCustomCrop@12590fd5.32767_200"=200
    I:"extrabiomes.items.ItemCustomCrop@13640e2.32767_200"=200
    I:"extrabiomes.items.ItemCustomCrop@1828f220.32767_200"=200
    I:"extrabiomes.items.ItemCustomCrop@1844b0de.32767_200"=200
    I:"extrabiomes.items.ItemCustomCrop@198f7ef1.32767_200"=200
    I:"extrabiomes.items.ItemCustomCrop@19b5f9b2.32767_200"=200
    I:"extrabiomes.items.ItemCustomCrop@1f468801.32767_200"=200
I:"forestry.core.items.ItemFruit@1467e6e0.32767_100"=100
    I:"forestry.core.items.ItemFruit@169c4b68.32767_100"=100
    I:"forestry.core.items.ItemFruit@17706a33.32767_100"=100
    I:"forestry.core.items.ItemFruit@18f97be3.32767_100"=100
    I:"forestry.core.items.ItemFruit@1963f144.32767_100"=100
    I:"forestry.core.items.ItemFruit@1aa595cc.32767_100"=100

etc...
https://raw.githubusercontent.com/JasonMcRay/InfiTech-1.7/master/config/GregTech/Recipes.cfg
If you look here and search for most entries that contains "@". Every start it adds one new of these lines.

**Comment by Blood-Asp** [comment]
Should be fixed in 5.08.21
