### ISSUE TITLE
Nerf'd recipes for Armour etc broken in .23 -> Redo reverted code and fix properly

### ISSUE THREAD

**Issue by mura3277** [Blood-Asp/GT5-Unofficial#651]
Greg'd recipes for IC2 bronze armour, RC steel armour, shears etc are no longer working.

Narrowed down to changes with GT_RecipeRegistrator with commit d2a098f

**Comment by Dream-Master** [comment]
Vanilla Armor have vanilla Recipe too except Diamond Armor.

**Comment by Blood-Asp** [comment]
Hmm, but reverting all GT_RecipeRegistrator changes in that commit did not get it working again. Must be something else too.

**Comment by mura3277** [comment]
Reverted the necessary changes for a temp fix. I'll look into fixing it properly if I can get a hold of Bogdan.

**Comment by mura3277** [comment]
@Bogdan-G So we are having a problem with the recipes that GregTech nerfs from Vanilla and other mods. Example: 
![image](https://cloud.githubusercontent.com/assets/7321570/18963986/f031a9fc-866e-11e6-8603-d956d49c9678.png)

The issue seems to come from the code reverted in this commit: c283f7f Is this something that is fixed in your recent commits or is this a new issue?

**Comment by Bogdan-G** [comment]
@Muramasa- I do not know, the default algorithm in the official 5, has too many empty aisles (0 recipes found) apparently does not find a recipe or I do not fully understand what it does (some recipes, it still gives the recipe list should be the actual items consideration, and not the logic of where to add the recipe and check whether it is valid again, which is strange).

PS partially corrected the translator(in this post use  translate ru->en), but not completely.
PPS github notification appeared only now, before i checked it 12h ago and there was nothing(no notify changes)

**Comment by Bogdan-G** [comment]
hmh, im fixing missing vanilla recipes https://github.com/Bogdan-G/GT5-Unofficial/commit/c760605e140bec65cb32d9c8af3ef07c59c2f80e
~~i checked the weapons, armor, door. it should still be?~~
PS oops, not full replaced xD
PPS now it seems completely (or almost 100%, because I'm not sure until the end) https://github.com/Bogdan-G/GT5-Unofficial/commit/b147085200ebf75b5b8ce42d169fcd9442f590a9

**Comment by Bogdan-G** [comment]
status issue?

**Comment by Bogdan-G** [comment]
@Muramasa- problem fixed, look ^
