### ISSUE TITLE
Pollution chunk borders calculation bug

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#652]
In negative Z direction pollution chunk borders are different than F9 shows.
![2016-09-28_10 33 46](https://cloud.githubusercontent.com/assets/14032818/18906280/96af410a-856f-11e6-9b57-1c1029d752c1.png)
![2016-09-28_10 33 51](https://cloud.githubusercontent.com/assets/14032818/18906279/96acc8e4-856f-11e6-9483-ecee4548b7d3.png)

**Comment by SapientMC** [comment]
Btw, Underbedrock oil spot borders has same bug.

**Comment by Technus** [comment]
If they are shifted by one block then i assume rounding error when dividing by 16 (captain obvious reply)

**Comment by OvermindDL1** [comment]
> If they are shifted by one block then i assume rounding error when dividing by 16 (captain obvious reply)

If so then that is because someone is not using MathUtils.trunc or whatever the core minecraft function to do the double->int block coordinate conversion.  Anyone who relies on implicit conversions knows not math on the CPU.

**Comment by Technus** [comment]
I see that forge code uses simply >>4 and that works for int/long numbers.

**Comment by OvermindDL1** [comment]
> I see that forge code uses simply >>4 and that works for int/long numbers.

Yep, you do not need to use `Math.trunc` if the number is already integral, only if it is a double/float.

**Comment by Blood-Asp** [comment]
So far i did just not care about this. Nothing gets broken from this, it is just a little bit off.

**Comment by SapientMC** [comment]
@Blood-Asp Seems like it was Scanner bug. After this https://github.com/Blood-Asp/GT5-Unofficial/issues/712 fix all works fine. Thanx a lot :)

**Comment by Technus** [comment]
No Problem... i guess?

**Comment by SapientMC** [comment]
You right. All fine :) Thanx for fix.
