### ISSUE TITLE
GT Ore spam

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#660]
This error spams the logfiles in enormous amounts, causing the server to become unresponsive and time out for several minutes before briefly recovering, but keeps occuring again and again.  I'd classify it as severe and game-breaking, as once it starts everything is kaputsky.

[22:11:55] [Server thread/INFO] [STDOUT/]: [gregtech.common.blocks.GT_TileEntity_Ores:setOreBlock:113]: gregtech.common.blocks.GT_Block_Ores@5ec4cc7c

[fml-server-latest.txt](https://github.com/Blood-Asp/GT5-Unofficial/files/502124/fml-server-latest.txt)

**Comment by mura3277** [comment]
What version are you on? This should be fixed in .23

**Comment by axlegear** [comment]
5.09.23pre6

**Comment by mura3277** [comment]
Yeah, use the build of .23 on the forum post and it will be fixed
