### ISSUE TITLE
A bug?

### ISSUE THREAD

**Issue by DevDengChao** [Blood-Asp/GT5-Unofficial#666]
Is it a bug =-=?
From MC1.7.10-Forge10.13.4.1614-1.7.10, gregtech-5.09.22.
I was trying to known how it works and then discovered this.
Sorry for I don't known how it called in English...,For I'm using a translated pakeage : )

the short video almost 1 minute:
[https://youtu.be/BNWrOpOtFO0](https://youtu.be/BNWrOpOtFO0)

**Comment by PaladinOne** [comment]
Yep that's a bug.

For those not watching the video: the Charcoal Pile Igniter continues operating when its pile's dirt casing is broken, runs a full cycle, but does not transform wood into charcoal. However, if the cycle completes, the wood is removed, and replaced with Bricks, and the dirt casing is restored, when the dirt casing is broken again the inserted _bricks_ turn into charcoal.

Three issues, one probable fix: one, the Charcoal Pile does not check for 'incomplete structure' after starting a work cycle, but it does check when ending one. Two, the Pile does not reset itself if it's structure is broken then restored. Three, the Pile does not check if what it's turning into charcoal is actually wood.

... Could probably fix all this by just fixing the Incomplete Structure check and/or forcing progress reset on incomplete structure

This all being said: 5.09.22 is an old version by now, can this be done in 5.09.23 or 5.09.24?

**Comment by DevDengChao** [comment]
The same in 5.09.24
The Charcoal Pile's animation does not play when I repaired the structure...

The tootip said : Converts LOGS into brittle charcoal bolcks;
Then I placed a plank,a wooden slab, fence, stair ,crafting table...all truned into brittle charcoal bolck...
Is this designed to benifit players or...part of this bug?

**Comment by PaladinOne** [comment]
Part of the bug
