### ISSUE TITLE
NEI items and blocks hiding

### ISSUE THREAD

**Issue by ghost** [Blood-Asp/GT5-Unofficial#667]
![8356](https://cloud.githubusercontent.com/assets/22619187/19079470/ec374f1a-8a7d-11e6-9ecf-d4dbfedad010.png)

White marked plank covers:  "_-hiding Forestry planks or not even loading them when forestry is not installed sounds like a fine idea_" (Bloody Asp). 

White marked boxes and even textureless thing named like "_gt.metaitem.03_..." may be removed, too. 

Same about non-marked, but just entire bottom line with the blocks named like "_gt.blockcasings_...".

**Comment by mura3277** [comment]
The strange unnamed crates is a bug from .24. I'm not sure what causes it, but it doesn't seem to happen if "show_all_metaitems_in_creative_and_NEI" is enabled.
