### ISSUE TITLE
[Crash] [Optifine] Render crash with Optifine

### ISSUE THREAD

**Issue by alfuken** [Blood-Asp/GT5-Unofficial#669]
When using latest version of GT (5.10.05) from CurseForge for MC 1.10.2 with Forge 12.18.1.2092 in combination with latest OptiFine version 1.10.2_HD_U_C3, I'm getting a crash with following error when browsing "Main" creative tab or searching for "steel". I believe it crashes when trying to render steel cable.

```
java.lang.IllegalStateException: Already building!
    at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291)
    at net.minecraft.client.shader.Framebuffer.func_178038_a(Framebuffer.java:264)
    at net.minecraft.client.shader.Framebuffer.func_147615_c(Framebuffer.java:229)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1103)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Full error log is [here](http://pastebin.com/raw/JNvb06H6)

This happens only with GT. Only 3 mods installed: Optifine, GT, and IC2-2.6.69-ex110.

**Comment by OvermindDL1** [comment]
Regardless, that still looks like an Optifine bug, not a single bit of that stacktrace is touching GT, just GT adds more and it probably is not handling it well.  Optifine has always been buggy, sadly, good idea though.

**Comment by alfuken** [comment]
If you're fast enough (ctrl+v) and narrow down the list of items displayed to show only steel cable, it will still crash. So I think it's not the amount of renders, but the way this cable is rendered.

**Comment by OvermindDL1** [comment]
This is a common issue with Optifine though, it renders differently than stock Minecraft and it has always caused this precise issue, even if nothing is wrong with the mod code at all (not saying nothing is wrong with the code in the GT renderer, but its renderer is very stock, nothing special in the great majority of it).  

Hmm, lets look, https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/render/GT_MetaGenerated_Item_Renderer.java#L43-L152 I'm guessing, thus the only different thing there is just 'blend' is being set in the OGL state, but it is also being properly unset at the end of the call, so I am not seeing any issues?

**Comment by OvermindDL1** [comment]
Also, does it actually 'show' the steel cable?  Because if it does then it is definitely not in the GT renderer at all, rather at least a frame later.

**Comment by alfuken** [comment]
Well, if one disables optifine then it plays well, that's true. But the amount of FPS decrease from Optifine is too damn high to just throw it away.
And no, it doesn't render the cable.
<img width="640" alt="screen shot 2016-10-05 at 13 48 59" src="https://cloud.githubusercontent.com/assets/75377/19121993/d8326210-8b28-11e6-9541-e80c47b358bd.png">
Here I've searched for "steel" and scrolled down. It tries to render cable, and crashes.

**Comment by OvermindDL1** [comment]
Hmm, well the code it is in is definitely not during GT rendering but rather the pass from the tesselator to the video card it looks like.

**Comment by Blood-Asp** [comment]
When something is crashing in combination with optifine, first go to them. You might give them a link to this repo, but first they have to look what might be the isse.

**Comment by Dragon2488** [comment]
Should be fixed in massive rendering overhaul
