### ISSUE TITLE
[Question] Forking policy?

### ISSUE THREAD

**Issue by aerospark** [Blood-Asp/GT5-Unofficial#67]
So, I'd like to maintain my own fork of this, and add additional new things, but I'm not sure the policy on forking. I'd intend to maintain a separate public build based on the fork.

**Comment by Blood-Asp** [comment]
Generally i see no problem with that, but you should also ask greg about that to be sure.

If you plan to add some new stuff or to fix bugs, pull requests instead of a fork might be better?

**Comment by aerospark** [comment]
Yeah if it's fixes I'd do pull requests but I'm planning on also doing some fundamental things like ex: making nuclear fuel enrichment require the chemical reactor to process it to yellowcake

Just adding more sciency things. I'll contact greg about it.

**Comment by Blood-Asp** [comment]
Sound interesting. I plan to start a GT5U Experimental version in a few months that will contain many other fundamental changes. Maybe i can then merge a bunch of what you plan to do into the main branch? GT has easy config support anyways.

**Comment by aerospark** [comment]
That would be really cool, well I'm going to add my changes to my branch anyway, even if I don't release builds of it.

**Comment by aerospark** [comment]
I've contacted Greg and everything is ok, closing this now.

For future reference here's his response: http://i.imgur.com/UgFV3UG.png

**Comment by Blood-Asp** [comment]
How about direct chat contact? Skype for example for easier talks?

**Comment by aerospark** [comment]
Sure that would be good, feel free to add me (aerospark1861)
