### ISSUE TITLE
wrong Crop Recipies when using NerfCombs=false

### ISSUE THREAD

**Issue by ghost** [Blood-Asp/GT5-Unofficial#672]
Used Mods:
- gregtech-5.09.24-b2
- industrialcraft-2-2.2.826-experimental
- CodeChickenCore-1.7.10-1.0.7.47-universal
- NotEnoughItems-1.7.10-1.0.5.120-universal

When changing the NerfCombs config to false the outputs of crop processing is wrong.

Plumbilia --> Galena
Argentia  --> Galena
Ferru --> Pyrite 
Aurelia --> Magnetite
Bobs-Yer-Uncle-Berry --> Beryllium
Titania --> Bauxite
Nickelback --> Powellite
Galvania --> Sulfur
Pyrolosium --> Tantalite
Coppon --> Stibnite
Scheelinium --> Lithium
Platina --> Bastnasite
Tine -->Cassiterite

If the following mods are added
- MicdoodleCore-1.7-3.0.12.462
- GalacticraftCore-1.7-3.0.12.462
- GalacticGreg-0.7
- Galacticraft-Planets-1.7-3.0.12.462

Ferru --> Meteoric Iron

**Comment by mura3277** [comment]
Fixed by b88e197
