### ISSUE TITLE
Advanced Miner II bug

### ISSUE THREAD

**Issue by Antifluxfield** [Blood-Asp/GT5-Unofficial#674]
5.09.22&.23, multiple adv miners "share" the ores. The problem is similar to, or maybe the same as #508.
Moreover, when mining with laser, drill or pickaxe, with the adv miner working at the same time, it seems that the adv miners also output the crushed version of the manually excavated ores. For example, my adv miner II was working on a naquadah vein in the end, and I knocked off some phosphorus in overworld. Later I found some crushed phosphorus and a apitite crystal in the miner's output, which should never occur in the end.

**Comment by Blood-Asp** [comment]
All i can say about that is: I have no idea. Tried it a few times already and never found anything.
