### ISSUE TITLE
Tri-corder problems

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#675]
1) Tri-corder/Portable Scanner seems to not consume any EU when used.
2) It requires 10k - 20k EU to actually start doing something (but still does not consume its energy).

Got this report on InfiTech that it happens only on server, but I am able to recreate it also on Single Player

**Comment by leagris** [comment]
@JasonMcRay Are you sure your player wears no IC2 power source like a ModularPowerSuit, a Gravysuite, Charged crystals, batteries in inventory, solar helmet or other IC2 powered tools that could act as a recharge EU donor?

**Comment by JasonMcRay** [comment]
I tested it on my own in my test world, completely naked and in survival.

**Comment by SapientMC** [comment]
I'm using Portable Scanner a lot (crops breeding) and it consumes energy from Nano Body Armor as it should.

**Comment by Blood-Asp** [comment]
I did look a bit at the code and all changes.
The Portable scanner is only using energy when scanning a tile entity. Zero costs when scanning normal blocks. And it was always that way.
Maybe no one did notice this because before pollution there was no reason to scann normal blocks?

**Comment by JasonMcRay** [comment]
Oh... I had no idea that it consume energy only when used on Tile Entities. Well then I think this issue can be closed.
