### ISSUE TITLE
A  couple of bugs

### ISSUE THREAD

**Issue by mightydanp** [Blood-Asp/GT5-Unofficial#676]
![bug](https://cloud.githubusercontent.com/assets/4637469/19218145/43ed3468-8db7-11e6-83e4-46eed186bc3d.PNG)

There is apparently no Ingot to 9 nuggets  furnace recipe.

**Comment by mura3277** [comment]
This should be fixed with the newest build of .24. Try downloading it from the forum post again.

**Comment by Blood-Asp** [comment]
The newest builds are always on onedrive. I update there almost every time i commit to github.
Also updating the forum post and github all the time is too much work.

**Comment by mightydanp** [comment]
I am using the current .24 version

**Comment by mightydanp** [comment]
I also got it fron one drive 3 days ago

**Comment by Blood-Asp** [comment]
the latest upload on onedrive is 5minutes old. I do not rename them, so just look at the timestamp.

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/bdee358c0ca97ac0c856812d301b63c963836df6 is about 3 days old. So if you got it 3 days ago, you likely downloaded it just before i reuploaded.
