### ISSUE TITLE
Will this ore spawn in nether or not?

### ISSUE THREAD

**Issue by TehporP** [Blood-Asp/GT5-Unofficial#679]
![qq 20161011161117](https://cloud.githubusercontent.com/assets/8299221/19263249/01b58276-8fce-11e6-9477-bec3883d49eb.png)
I am pretty confued   Which one I can delete  Which one I cant?

**Comment by leagris** [comment]
You can Backup all your Gregtech configurations, delete the config/Gregtech folder to force the game to regenerate it. Then do a side-by-side comparison, remove duplicates, add new config options and keep your customizations.

This is the exact shortcoming of defaultvalue varname.
Could have used comments instead but as the GTConfig class is not handling comments and is writing to the config file continuously while the game is running, even if that does not make sense, that would be even more data to update and write.

**Comment by TehporP** [comment]
@leagris   Thanks for your help
