### ISSUE TITLE
Problem with Unification Process in .24

### ISSUE THREAD

**Issue by chaos234** [Blood-Asp/GT5-Unofficial#680]
Hey @Blood-Asp ,

at first great work on this mod, I am confused the first time since I have ever played modded MC and nothing was so complicated as GT5U (I know that GT is original from GregoriusT but without your work we did not have this version for the latest forge version).

But actually I think that there are some problems with the unification process. It does not matter if this happends in the inventory or on craftin or on throwing things away. The problem is, that the ordictionary has so much entries, that some items, sepcialy those from Essential Craft 3, are not friendly to this unification so they are "morphing" in not wanted things on some point even if I set the crafting and inventory unification to false which happend with Immersive Engineering's Dropping Conveyer Belt.

I think that the dropping effect of this belt acts like throwing things away which turns them in another item from the oredict source.

I must look into the soure code how the unification process currently works but changing the values in the unification.cfg from false to true it hase some wired effects because some things which did not changed are changing now and some other not anymore.

My highest problem is the handle from the Essential Craft's Items like the plates or the pale gem. The pale gem can be stoped from morphing into a Olivine (if I am right) gem but if I want to stop chaging a Mithriline Plate into a Demonic Plate it won't work because it changes into a Magical Plat or into a Pale Plate which is used in the recipe for the Magmatic Furnace and from what NEI tells me this recipe does never use the ordict in any way like much oter recipes but instead of going through the hole recipeas and using MineTweaker I hope you can "force out" Essential Craft so that nothing from it will be morphed. Better is that only ingots should morph or eventually circuits too? But important stuff from other mods shouldn't be changed because it can be that they are used for a deeper recipes.

At the end I think that this is caused because some recipes or items are not registeres (correctly) with the oredict and so this situation happends. I hope you can help and I'll also look on the source code to help too :).

Cheers

**Comment by chaos234** [comment]
Here is the full list of my unification.cfg: http://pastebin.com/180UxW38
Here is the full list of the MPs ordict from minetweaker: https://1drv.ms/t/s!Ajy7SuD2gGVw7mcl4-YGwMnT5b4O

**Comment by mura3277** [comment]
Cause explained by Greg [here](http://forum.industrial-craft.net/index.php?page=Thread&postID=203676#post203676). (Just for future reference)

**Comment by draknyte1** [comment]
> Remove all the OreDict entries from the other mod if it's doing it wrong. Use MineTweaker if you don't know how.

It's not on Gregtech to fix mistakes, such as improper use of the oreDict. As it is, the unification basically does allow entire mods to be on/off, you just have to do it per item..

**Comment by Blood-Asp** [comment]
Basicly Essential Craft does stupid stuff with their oredict registration...
If it was 2-3 strange items, i could blacklist them, but here i really can not see how i could get this to work properly.

**Comment by chaos234** [comment]
@Blood-Asp - Is it possible to ask for the Mods Name? I assume that it is possible so try to add an additional request over an array of blacklisted Mods without looking for case sensitive writing.

If a mod with the given name is found (exclude GT here) then simply do nothing, simply don't call the Unification-API and all should work. If you want, I can try it out and if it works on my side (client and server), I'll make a PR to you ;).

**Comment by Blood-Asp** [comment]
GT can blacklist certain tags, but if the mod has dozens of them and for items that are well used, that does not work so well.
There is no function to exlude a full mod from GTs oredict functions because that might break the usage of the other correctly registered items of the mod.
