### ISSUE TITLE
Material System Troubles

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#682]
So. First, the new material system is really great and speeds up the loading times by fair amount. 

BUT

I am having lots of troubles with it. Just two examples: Vinteum and Enderium (InfiTech 2 modpack of course)
Vinteum:
MaterialProperties.cfg file
I:MaterialID_529=529
I:MaterialTypes_77=77 (this should include Gems)
MaterialComponents.cfg file
B:gem_true=true

I expect that it will appear in NEI, but it does not. Also the Parser says that the Material 529 is not enabled

Same happens with Enderium:
Properties file:
I:MaterialID_321=321
I:MaterialTypes_67=67 (this should include Ingots)
Components file:
B:ingot_true=true

But guess what... also nothing appears in NEI, nor Ingame... nowhere.

Using latest GT.24 from One Drive

**Comment by leagris** [comment]
If either the original mod providing these materials is not present or not detected, these materials will not be enabled even if you tell it to.
Alternatively, you maybe be able to move declarations for these materials in custom material entries, even re-using the MaterialID.

**Comment by Blood-Asp** [comment]
They "should" be possible to be reenabled in the materialProperties.cfg.

The question is why this does not work.

**Comment by JasonMcRay** [comment]
It worked in one of the .24 builds, but really cannot say which one.

**Comment by mura3277** [comment]
For Enderium, 796b822 should fix that. I also see Vinteum in the latest build (Not sure if on Onedrive).

Once the build is updated, you should be able to turn "HasParentMod" to true (if false) to override a material to generate without its parent mod.

**Comment by draknyte1** [comment]
> requiring parent mods for materials to be enabled is fucking stupid anyway. 

What if you'd wanted every material again?.. 

When will we admit .24 is a mess? lol

**Comment by mura3277** [comment]
@draknyte1 You can override it.
