### ISSUE TITLE
Wrought Iron Nugget does not shows up in NEI

### ISSUE THREAD

**Issue by chaos234** [Blood-Asp/GT5-Unofficial#683]
Like title says hte Wrough Iron Nugget isn't shown in NEI and I dunno why.
I hope that this is a small bug from NEI self because the item still exists.

I am glad for each help to get this item shown in NEI up.

**Comment by mura3277** [comment]
I'm not sure what you mean. You shouldn't be able to see nuggets in the NEI item panel, but the nuggets should be shown by looking at ingot recipes.

**Comment by chaos234** [comment]
I should be able to see all items in NEI which I want so why hiding that key item in NEI if it's used in recipes? Hiding blacklisted items or items which are not used in any recipe are quite ok, but the nugget(s) should appear every time.

Currently I see 139 nuggets from all the mods but adding the wrought iron nugget to NEI makes 140 so how can I enable it? I don't like it if items are not visible in NEI if they are used and this applies to all items.

**Comment by draknyte1** [comment]
Is there an option to enable nuggets showing?
I feel they're pretty important tbh.

**Comment by Blood-Asp** [comment]
yes, there is a config.
GregTech/GregTech.cfg general/B:show_all_metaitems_in_creative_and_NEI=false
Before .24 this config made a lot sense. For example the Nuggets. GT did generate 100+ nuggets, but only 2 of them where used. Now with the new material system only the 2 that have use are generated, so showing all the stuff would no longer spam NEI to death.

**Comment by chaos234** [comment]
Thanks Blood for the help ;).

Can you also tell me which 1.7.10 branche I can use to write on it to send you then PRs?

**Comment by draknyte1** [comment]
The one you see when you visit - https://github.com/Blood-Asp/GT5-Unofficial
Experimental

**Comment by Blood-Asp** [comment]
Up to 5.09.23 is experimental, master is still 5.08.33.
The .24 releases currently made are the unstable branch. 
So depends on what exactly you want to PR.

It will be mainly experimental and in case the issue comes from the new material system, then it is unstable.

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/d4c23ed7a706f9e04993621bec669e665c4162e0
