### ISSUE TITLE
Bug  recipes.

### ISSUE THREAD

**Issue by Pilad** [Blood-Asp/GT5-Unofficial#684]
Cantal not welded in a blast furnace at a voltage of 128 ey/t and a vacuum freezer just can not cool ingot at a voltage of 128 eu/t . If use 256 eu/t or 512 eu/t work fine.
Test with builds 23 and 24. Build 22 work fine(128eu/t).

**Comment by draknyte1** [comment]
Kanthal smelting cost in EBF is off in .23 and .24 but .22 works?
~Making things readable.

**Comment by Blood-Asp** [comment]
Download the latest .24 build from OneDrive. The Kantal stuff is fixed there. Before you needed 512EU/t to smelt cantal even trough the recipe said 120EU/t

But i have no idea what the problem with the vacuum freezer is.

**Comment by Pilad** [comment]
Hmm.. Latest build 24 work. 23 will not fix?

**Comment by Blood-Asp** [comment]
Sure, .23 will get that fix. but i do not update that version after every push.
