### ISSUE TITLE
[.23/.25] Mold (Nuggets) gives ingot

### ISSUE THREAD

**Issue by chaos234** [Blood-Asp/GT5-Unofficial#687]
![2016-10-17_13 56 40](https://cloud.githubusercontent.com/assets/340106/19439430/4c0f2ca0-947e-11e6-965e-1adcf014e499.png)

![2016-10-17_13 56 57](https://cloud.githubusercontent.com/assets/340106/19439432/4fa7741c-947e-11e6-8757-a575d45b9053.png)

As you can see the Mold for Nuggets is giving ingots which shouldn't be or should it be?
I don't think so and if this is a bug try to fix it ;).

**Comment by Blood-Asp** [comment]
Thats melting down the shape for its raw materials, not using the mold to form other materials, so this recipe is completely right.

**Comment by chaos234** [comment]
Oh, ok. Did not thought about that. Good to know :).
