### ISSUE TITLE
Conveyor module bug

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#688]
Alloy Smelter. Two chests near (on right and left sides). Conveyor module on right side in Import mode. Auto output to left chest.
Mold (nugget) inside Smelter and lots of nuggets in right Chest. All works fine. Nuggets loads from right chest, smelts to ingots and outputs to left chest.
But. If I take mold and nuggets from Smelter and put there redstone with copper, than conveyor module every 20 sec take one stack of nuggets from chest and drop them outside (because there are no free space in Smelter).

**Comment by Blood-Asp** [comment]
Bug seems to be caused by double chest handling... You did pull out of a double chest?

**Comment by SapientMC** [comment]
Yep. From left side of it.
