### ISSUE TITLE
[GalacticGreg|Galacticraft] Missing recipe for HeavyDuty Alloy Ingot T1

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#690]
CC: @Muramasa- 
Gregtech 5.09.24
It is no longer possible to craft the `Heavy Duty Alloy Ingot`
ItemID: `gregtech:gt.metaitem.01:32462`

See: https://github.com/Beyond-Reality/BeyondRealityModPack/issues/438

The higher tiers of Heavy Duty Alloy Ingot T2 and T3 still have valid recipes.

![capture du 2016-10-18 17-46-32](https://cloud.githubusercontent.com/assets/1111474/19485270/e7977b46-955a-11e6-8f26-fb2ae446ea55.png)
![capture du 2016-10-18 17-47-44](https://cloud.githubusercontent.com/assets/1111474/19485292/0139e002-955b-11e6-97cd-f4e90e64625a.png)

**Comment by Blood-Asp** [comment]
Is the compressed aluminium plate available?

**Comment by leagris** [comment]
Yes, it is

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/4384688c079f5f945c0427ddc4c025e8a4abf29b this fixes it. But the real reason seems to be the failed replacement of aluminum with aluminium internally in GT. Might cause other issues. @Muramasa- Any idea why that happens?
