### ISSUE TITLE
Items Missing from .24+ that GT++ requires.

### ISSUE THREAD

**Issue by draknyte1** [Blood-Asp/GT5-Unofficial#691]
This is a to-do list for myself and anyone else who notices;

Without Dense plates enabled for all materials, Multipicks and MultiShovels don't generate for 99% of materials.

Invar, Brass, Bronze and Wrough Iron Rings, for cells.

To-Do~

**Comment by mura3277** [comment]
You can enable things you need with a MaterialProcessor. [Example here](https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/loaders/materialprocessing/ProcessingConfig.java).

You can to use onComponentIteration(called for every component) or onComponentsInit(called once after the defaults have been enabled/disabled). You can then check to see if the material can be made into a tool head and remove that material from the dense plate disabled list.

**Comment by draknyte1** [comment]
issue isn't on my end.. Works fine pre .24~

It's on yours if expect me to use version specific code.. you said yourself I'd get compat on your side?..

**Comment by draknyte1** [comment]
The issue isn't on my end.. Works fine pre .24~
It's on yours if expect me to use version specific code.. you said yourself I'd get compat on your side?..

Materials[] rm = Materials.values();
        for (Materials m : rm){
            MP_GTMATERIAL = UtilsItems.generateMultiPick(gtStyleTools, m);
            MS_GTMATERIAL = UtilsItems.generateMultiShovel(gtStyleTools, m);
        }

Already contains valid recipe checks.. 

As with my cells, the issue lies with items not existing on the GT side.

**Comment by draknyte1** [comment]
https://imgur.com/a/ZEeDf

"You two have to tell use what problems you have with .24 so we can fit it. nothing else"
Told you this whole 'we'll add support on our side Bs' won't work, but whatever..

**Comment by Blood-Asp** [comment]
I can add exceptions to enable the stuff you need without much problem, but that means you would always need to wait until the next GT update for them to work. And that might take months depending on the state of work...
So it would really be recommended to enable the parts you need yourself.

Also your

> The issue isn't on my end.. Works fine pre .24~

is stupid... Changing content of a programm almost always breaks something. All the mods do that. Forestry, EnderIO, Buildcraft even Forge itself had breaking changes since GT5U is ongoing.
Some changes might not be nessary and annoying because of that, but do not expect that always to be the case.

**Comment by draknyte1** [comment]
Considering I compile against .08, I expect the API to retain compatibility.

Where it doesn't, for whatever reason, then that falls on you as the Developer to fix the issue. I'm not adding .09.whatever.whatever specific code into my mod when there is NO way to detect mod version, only API version.. 

Alternative option, just make me a project contributor.. I'll add my compat as I see fit and not have to wait, you'll have no more whinging from my end about shit. /2cents

**Comment by draknyte1** [comment]
^ A few more things,
Plus Naquadah foil should probably be a thing too~
