### ISSUE TITLE
Mobs spawn on blocks

### ISSUE THREAD

**Issue by dalekin** [Blood-Asp/GT5-Unofficial#692]
Marble and granite smooth blocks have text "Mobs cannot Spawn on this Block"
However mobs spawn on them.

**Comment by Blood-Asp** [comment]
It does work for me. NEI also does show the blocks as not spawning mobs.

**Comment by dalekin** [comment]
My test: gregtech-5.09.26pre & forge 1566
- waila, nei, optifine, journeymap
- CodeChickenCore-1.7.10-1.0.7.47
- CodeChickenLib-1.7.10-1.1.3.140
- EnderCore-1.7.10-0.2.0.36
- industrialcraft-2-2.2.823-experimental
  NEI show the blocks as spawning mobs on marble blocks
  but machine parts show ok.
  ![smooth marble](https://cloud.githubusercontent.com/assets/22941859/19540512/a54edebe-9668-11e6-9a1f-be6cb7ac00ed.png)
  ![machine block](https://cloud.githubusercontent.com/assets/22941859/19540515/a78632cc-9668-11e6-882f-ca8fcbb2e7d5.png)

**Comment by Blood-Asp** [comment]
can not get this behavior at all
try to remove all mods besides IC2, GT and NEI.

**Comment by leagris** [comment]
I confirm same with Gregtech 5.09.24 in BeyondReality.

**Comment by Blood-Asp** [comment]
You can confirm what? Monster spawning or not spawning?

**Comment by leagris** [comment]
Monster spawns and the grid highlight shows the area as spawnable exactly like the screenshots above.

**Comment by Blood-Asp** [comment]
In InfiTech2 everything looks fine for me. So something, not GregTech, is changing the behavior here.

Can someone also test if this happens with older GT versions? For me it does not happen, so i can not test.

**Comment by dalekin** [comment]
I spent more tests. If you do not include optifine 1.7.10_HD_U_D6, then everything is fine and the grid is not shown. Once loaded with activated optifine, the grid appears. It seems Optifine changes the mechanics of spawning. Strange.

**Comment by Blood-Asp** [comment]
so optifine is the issue here... i have no idea why this could happen, but since GT is using vanilla methods to stop spawns, this will likely also be an issue with other mods or even vanilla blocks. If there are any full blocks that stop mob spwns...

**Comment by OvermindDL1** [comment]
It is a _long_ standing bug that Optifine overrides mob spawning rules, one of the many reasons not to use it.
