### ISSUE TITLE
Ore Generation logic lag

### ISSUE THREAD

**Issue by Reknot** [Blood-Asp/GT5-Unofficial#693]
[Read in fourum thread it is known(?) but didnt see an issue here regarding it so thought I'd make one]

Versions:
**Forge**: forge-1.10.2-12.18.2.2099
**IC2**: industrialcraft-2-2.6.89-ex110
**GT5u**: gregtech-5.10.05

Issue:
  Whenever chunks are loaded(?), the server can't keep up. 
  Both on hosted Localy by singleplayer or on a Server setup.
  When standing still everything is working fine.

`[17:13:55] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2443ms behind, skipping 48 tick(s)
[17:14:21] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2953ms behind, skipping 59 tick(s)
[17:14:42] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2473ms behind, skipping 49 tick(s)`

**Comment by draknyte1** [comment]
GT for 1.10 is laggy for basically everyone, for some totally unplayable. This is rather well known and the issues for it are probably closed (There was definitely more than one)

**Comment by Dragon2488** [comment]
Well, I'm trying to fix it.

**Comment by Reknot** [comment]
Ah. Cool. Just thought it was a 'everyone is talking about it but noone made a official ticket' thing since there was no official one.
And thanks all devs. Seriously good work you're doing.

**Comment by Dragon2488** [comment]
Well, it should be almost fixed now

**Comment by Reknot** [comment]
Hello again! 
Sorry for not checking back in a while.
How ever now I'm back at it. Tried x.6 and indeed the world generates a lot smoother! 
But now instead get bombarded by java.lang.NullPointerExceptions
I believe it's related? Cant tell from the logs. 

Versions:
**Forge**: forge-1.10.2-12.18.2.2114
**IC2**: industrialcraft-2-2.6.87-ex110
**GT5u**: gregtech-5.10.06
**Optifine** Optifine.1.10.2_HD_U_D2 _(Tested with and without)_

Don't know what logs you'll need. So here are them all. 
[logs.zip](https://github.com/Blood-Asp/GT5-Unofficial/files/560118/logs.zip)

**Comment by Dragon2488** [comment]
dont_know_which_tiles_emit_it.jpg
