### ISSUE TITLE
negative durability

### ISSUE THREAD

**Issue by Nex4rius** [Blood-Asp/GT5-Unofficial#694]
<a href="https://i.imgur.com/iii6rrL.gif"><img src="https://i.imgur.com/iii6rrL.gif" alt="gif doesn't work :("></a>

gregtech-5.09.25

**Comment by draknyte1** [comment]
Well, it cut down the tree, plus a lil extra.. so next use will break it and do nothing else

Honestly, would you prefer treetops that are floating in the sky or a visual issue (afaik, the negative durability won't do anything bad)

**Comment by Blood-Asp** [comment]
Looking at the code, the item actually is already destryed with the negative durability, but it is missing an inventory update for the tool to disappear.

**Comment by draknyte1** [comment]
That's why Greg left it that way, axe is the only tool that exceeds 0 dur in such a way as well from memory.
