### ISSUE TITLE
EnderIO alloys in GT alloy smelter

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#696]
just for more compat so there isnt a reason to need two alloy smelters from different mods.

**Comment by Blood-Asp** [comment]
most enderIO alloys should already be in the electric blast furnace.

**Comment by bear989** [comment]
all I can find in configs and NEI is electrical steel.

**Comment by PaladinOne** [comment]
Also a fair number of EnderIO alloys require 3 inputs, while the GT Alloy Smelter can only take 2. Definitely Blast Furnace material.

**Comment by Blood-Asp** [comment]
I noticed that it was only Electrical Steel and Dark Steel that were in the EBF. The latest .26pre build has recipes for all EnderIO Alloys.

**Comment by bear989** [comment]
thanks bloody, i will try out the pre.26 then
