### ISSUE TITLE
Adv Miner Blincking Off/On

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#698]
After update .22 -> .26pre my Adv Miner II start blinking to off and on after second (there are enough power, pipes and drilling fluid).
As i can see, it happens just before it mines some ore.

Another issue, seems like in produces no byproduct right now. More than full stack of Crushed Brown Limonite in output bus and not even single stone dust.

**Comment by SapientMC** [comment]
Seems like all Pulverizer recipes lost main byproduct. Ruby ore does not give chrome for example.

**Comment by Blood-Asp** [comment]
The pulverizer recipes are all fixed.

**Comment by SapientMC** [comment]
Grate!
Waiting for new version on OneDrive :)
Hope there are no more serious bugs and i can update GT in modpack.

**Comment by Blood-Asp** [comment]
The Adv Miner II itself has still some issue, but i'm mostly done with all known bugs...

Will upload a new build soon.

**Comment by SapientMC** [comment]
Thank you very much, from me and from over 500 users of my modpack :)
