### ISSUE TITLE
[Idea] Tool for test Maintenance

### ISSUE THREAD

**Issue by Usernm0** [Blood-Asp/GT5-Unofficial#699]
Add for existing tool, wirecutters for example ability to add random issue, when it used in maintenance hatch. It help test multiblock setups a lot.

**Comment by draknyte1** [comment]
Can you elaborate how that helps testing setups?
You never want maintenance issues, lol.

**Comment by leagris** [comment]
You can already generate or Edit simulate issues with a mod called In-Game NBTEdit.
No need to add a feature only coders will need/use to existing Gregtech Tools.
Or the only valid tool for handling those kind of features would be the Gregtech Debug Scanner. It would need an interface to allow manipulation of Gregtech Tiles and process.

**Comment by Technus** [comment]
If you talk about power usage increase that happen when machine goes bad it is +10% per maintenance issue. So the power computation multiplication can be done manually.

**Comment by Blood-Asp** [comment]
Or just pickup&place the controller and repair only few of the issues...

**Comment by Technus** [comment]
Lol yes

**Comment by PrincessOfEvil** [comment]
Iirc that's impossible because the controller needs to be completely fixed
the first time to work.

**Comment by Blood-Asp** [comment]
no, it must not be completely fixed. only at last one fix has to be done.

**Comment by Usernm0** [comment]
Now i pickup and place controller to test how something work (or not work), and when i again remove controller, put it back and use 5 tools to partial fix issues in multiblock, i think, that we need easier way to do it. 

Another idea - make issues in multiblock toggleable. One use of tool fix issue, second use - put it back.

**Comment by draknyte1** [comment]
What are you trying to test? Every machine issue adds 10% inefficiency? (I think)

You're asking for more work than is needed, really..
Just make tools that don't break in five uses.. A tungsten set will let you test controller issues for days.
