### ISSUE TITLE
Magic energy converter doesn't work

### ISSUE THREAD

**Issue by Buuz135** [Blood-Asp/GT5-Unofficial#7]
The magic energy converter doesn't work with Hardcore Ender Expansion as it replaces the vanila Minecraft egg. Forestry fixed it by loading after HEE.

**Comment by Blood-Asp** [comment]
The egg goes on top of the magic energy absorber. Also i tried it with HEE installed and the egg still works. can you tell more about the HEE egg? maybe output of minetweaker command /mt hand?

**Comment by Buuz135** [comment]
Sorry about that, I was using the Converter but not the Absorber.
