### ISSUE TITLE
[Code cleanup] Strip leading linenumber comments from source files

### ISSUE THREAD

**Issue by aerospark** [Blood-Asp/GT5-Unofficial#70]
A good portion of the code contains leading line-number comments created by the decompiler. These should be stripped in order to make the code cleaner and collaboration easier.

I could do it and create a pull request but since it would be such a huge change to all the source files it should probably be coordinated.

**Comment by Blood-Asp** [comment]
I tought about that before, but other stuff was more important...

Feel free to make a pull request, but maybe first a small section, so i can see if the formating is allright with me.

**Comment by pftbest** [comment]
I'm using this code to strip line numbers:
 `find -name '*.java' -exec perl -i -p0e 's/\/\*[^a-zA-Z]+?\*\/ ?//sg' {} \;`
This regexp is designed to keep all real, usefull comments, and removes only empty comments and comments that do not contain any alphabet letter.

**Comment by aerospark** [comment]
That script works wonders, regex is awesome.

I created a pull request but even so I don't think it should really be done as a pull request

**Comment by Blood-Asp** [comment]
merged it in and seems fine. Just a single comment in the api that should not be removed, so i will add it back.
