### ISSUE TITLE
Ingots generated for gem materials

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#702]
In .26 build from Octobre, 22, Gem materials default to having ingots generated.
One annoying consequence is smelting Ruby, Emerald or any Ore Gem outputs an Ingot instead of a Gem.

Except from [`MaterialProperties.cfg`](https://gist.githubusercontent.com/leagris/d74a020b83033a37c484191ce3176ce0/raw/f4393715967e18da82e8e817c1c3e2a917db2c8c/MaterialProperties.cfg) ruby:

```
        ruby {
            I:MaterialTypes_77=77
```

It rally should not generate ingot

But in [`MaterialComponents.cfg`](https://gist.githubusercontent.com/leagris/d74a020b83033a37c484191ce3176ce0/raw/f4393715967e18da82e8e817c1c3e2a917db2c8c/MaterialComponents.cfg) ruby

```
general {
    B:enablePerItemSettings_false=true
}
        ruby {
            B:ingot_true=false
```

The default is to enable Ingots.
Despite having explicitly set it to false, Ruby Ingots continue to be generated.

Both of my config files are made available here
https://gist.github.com/leagris/d74a020b83033a37c484191ce3176ce0#file-materialproperties-cfg

**Comment by Blood-Asp** [comment]
guess we took care of that...
