### ISSUE TITLE
Auto maintenance, doesnt work on server?

### ISSUE THREAD

**Issue by Technus** [Blood-Asp/GT5-Unofficial#707]
Idk but it doesnt work on server, i don't like using "this" in gt code btw, expecially when the function gets the object as parameter.

https://github.com/GTNewHorizons/GT5-Unofficial/commit/264f1810814a690e9ecf163761e651f907ed3ef7

**Comment by Technus** [comment]
Hopefully this should fix it

**Comment by Blood-Asp** [comment]
That fix is just hope and not tested? So i better wait with porting it? MP Testing is quite annoying...

**Comment by Technus** [comment]
The previous commit is reversed:
So far i come up with this commits:

https://github.com/GTNewHorizons/GT5-Unofficial/commit/df0264a9ab2e58c58dc3ab44ae6e996921c7a06f
https://github.com/GTNewHorizons/GT5-Unofficial/commit/4caeb9ae609049601cfe04c3bd3a7d858716e369
https://github.com/GTNewHorizons/GT5-Unofficial/commit/2cb81309e3a4f3e00a88e3c72b51bfa898ad2a69

Will test (on server) when i get time, but that change makes the auto maintenance share-able.

**Comment by Blood-Asp** [comment]
I tried it with a bit simpler code. https://github.com/Blood-Asp/GT5-Unofficial/commit/ed724da44d7783705cb8fd503b3f4623b1cf1b86

**Comment by Technus** [comment]
yeah but you could optimize tle logic like using the logic laws:
;]
https://en.wikipedia.org/wiki/De_Morgan%27s_laws

!(a || b || .....)=== !a && !b &&.....
!(a && b && .....)=== !a || !b ||.....

And shouldn't that be there?
https://github.com/Blood-Asp/GT5-Unofficial/commit/ed724da44d7783705cb8fd503b3f4623b1cf1b86#diff-9afe173dcb05846f08257b653eb98338L717

**Comment by leagris** [comment]
I'd add the first form force evaluation of the whole expression and whole term where-as the second form after === do stop evaluation on first FALSE term.

On the second line; right side expression stop evaluation once it encounter a term resolved to TRUE

Anyway, I think compilers are smart enough nowadays to optimize/factorizes nested conditions, but it is good practice to write it explicitly rather than praying on compilers to do it.

**Comment by Technus** [comment]
Yeah that thing i knew it was in LUA, good to know java has it also.
Still the problem on server seems to be in the "recipe check" like the methods on hatch either does not execute or always return false.

**Comment by Technus** [comment]
@leagris it will even stop evaluating inside parenthesis so i save some ! operations

**Comment by Technus** [comment]
another attempt this time succesful.
https://github.com/GTNewHorizons/GT5-Unofficial/commit/b5686c26514ee4d8a3df9beed55ebeaa0b90ffed
(recipe check code ripped from basic machine works flawlessly)
