### ISSUE TITLE
minecraft crash: AE audio "loop" 1.7.10 / 5.9.25

### ISSUE THREAD

**Issue by wtfmynamesarepopular** [Blood-Asp/GT5-Unofficial#708]
this issue is quite old, but it's still up in gt5 unofficial 5.9.25:
when you make, for example, 512 superconductor cables at once in an ME system, the game can crash if you let the ME system also use a hammer/wrench for pumps (anything that makes a sound).
fix: config option to disable crafting sounds, or even better, disable crafting sounds entirely just for ME (probably on their side, but i heard they won't update for MC 1.7 anymore).

crashlog: http://pastebin.com/ju7yE4h8

**Comment by Blood-Asp** [comment]
For now i try it this way... https://github.com/Blood-Asp/GT5-Unofficial/commit/16f03e76e82cfbde8f3c355fa1224a3b88472f06
