### ISSUE TITLE
Closing issues via commit messages

### ISSUE THREAD

**Issue by danbka33** [Blood-Asp/GT5-Unofficial#709]
I think it's useful to use: https://help.github.com/articles/closing-issues-via-commit-messages/.
It's very hard to keep track of what bug report closes commit. This should solve the problem.

**Comment by Blood-Asp** [comment]
I know this, but do not like it.

I want a function to add the "Fixed in Dev" label and only close them after a proper update and changelog.

Otherwise i would get spammed with bugreports for long fixed issues since no one seems to check the closed ones.
