### ISSUE TITLE
[1.10.2] gt.metaitem.01 confuses IC2-provided crafting recipes shown in JEI

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#710]
When looking up usages for an iron plate (other items are similarly affected, but the iron plate is the one that I first saw this happen for - it's gregtech:gt.metaitem.01:17032), I see it show up in some recipes for which it makes no sense.
Here are some examples:
- the top position of the MFSU or MFSU upgrade kit crafting recipe (which normally requires an advanced circuit there)
- the top, left, right, and bottom positions of the water mill crafting recipe (water mills shouldn't even be craftable any more, now that kinetic water generators / water turbines exist)
- the center and corners of the ic2 solar panel recipe (which I thought was disabled in the GregTech configs in favor of GT solar panels)
- the center of the advanced circuit recipe (which should be disabled with GT installed in favor of making it via Assembling Machine)

Putting one of these corrupted recipes on an actual crafting table was allowed via JEI's "+" button, but it didn't produce a result.  When I view alternate recipes for one of these, JEI cycles through various metadata values for gt.metaitem.01, usually dusts, so I tried viewing usages for a match (gregtech:gt.metaitem.01:32471), and it showed up in the same position for many recipes.

**Comment by Dragon2488** [comment]
I dont know why it's happening, maybe bug in ic2 or JEI? @mezz

**Comment by Dragon2488** [comment]
Also, seems like JEI is failing when getInputs() or getOutputs() return immutable list. @mezz

**Comment by mezz** [comment]
Try updating your JEI integration?

**Comment by Dragon2488** [comment]
Current integration supports both old and jei. But not about it. Why strange things happening with standard crafting recipes? I mean this issue.

**Comment by mezz** [comment]
I'm not sure, I have not seen anything similar happening to other mods.

**Comment by Dragon2488** [comment]
Than its pure ic2 issue?

**Comment by Timeslice42** [comment]
Honestly, IC2 has no business using a custom recipe handler at this point. It was done to handle batteries, and partial charges on output items when crafting with partially charged batteries, but that doesn't need a custom handler anymore. There are alot of hold-over eccentricities with their recipe handler (and alot of other parts of the mod) that just don't fit well with modern forge mods.

This is to be expected when you make a mod which is pioneering new features. However, it's well past time for IC3, written with today's forge standards.
