### ISSUE TITLE
Machines pollute neighboring chunk instead of it's own

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#712]
Seems like attempt to fix this https://github.com/Blood-Asp/GT5-Unofficial/issues/652 made calculations more broken than it was before.
Now some gas turbines or diesel generators pollute neighboring chunk instead of it's own.
![2016-10-29_15 16 24](https://cloud.githubusercontent.com/assets/14032818/19829773/21274ca6-9df3-11e6-86da-5fb78fe090b7.png)
![2016-10-29_15 16 39](https://cloud.githubusercontent.com/assets/14032818/19829774/21283648-9df3-11e6-9d1c-f010a528627d.png)

**Comment by SapientMC** [comment]
Additional info. Something very wrong with pollution on chunks near 0.0 coordinates.

**Comment by Technus** [comment]
The shift u see happens on x axis not z axis that is ood

**Comment by Technus** [comment]
tbh i blame scanner code.
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/util/GT_Utility.java#L1757

should also be unified to >>4 computation, i dont have that bug in GTNH branch

**Comment by Technus** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/pull/713

**Comment by SapientMC** [comment]
@Blood-Asp seems like it was scanner bug. After this fix https://github.com/Blood-Asp/GT5-Unofficial/issues/652 all works perfectly :)
Thanx a lot :)
