### ISSUE TITLE
Encountered Exception while loading MetaTileEntity..

### ISSUE THREAD

**Issue by Pilad** [Blood-Asp/GT5-Unofficial#714]
I do not know, it's important or not. In the log(GregTech.log) there are some mistakes.
GT-PlusPlus-1.4.9-release and gregtech-5.09.26pre
http://pastebin.com/agsVfdQY

**Comment by draknyte1** [comment]
Ownership data on a player safe was corrupt..

**Comment by Blood-Asp** [comment]
So issue on GT++ side and can be closed, or do i have to look into the issue?

**Comment by draknyte1** [comment]
I never noticed your comment sorry, I fixed it. Nothing to worry about. 👍🏻
