### ISSUE TITLE
Vein centers in negative coordinates are 1 chunk closer to axes than they should be

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#718]
This issue actually predates the unofficial fork, and occurs in 5.08, 5.09, and 5.10, but Greg fixed it for GT6 back in May 2015 (ref: http://forum.industrial-craft.net/index.php?page=Thread&postID=187659#post187659)
Current code is this:
```java
if ((Math.abs(this.mX / 16) % 3 == 1) && (Math.abs(this.mZ / 16) % 3 == 1))
```

However, that results in a pattern like this:
```
Math.abs(-160 / 16) % 3 = 1
Math.abs(-144 / 16) % 3 = 0
Math.abs(-128 / 16) % 3 = 2
Math.abs(-112 / 16) % 3 = 1
Math.abs(-96 / 16) % 3 = 0
Math.abs(-80 / 16) % 3 = 2
Math.abs(-64 / 16) % 3 = 1
Math.abs(-48 / 16) % 3 = 0
Math.abs(-32 / 16) % 3 = 2
Math.abs(-16 / 16) % 3 = 1
Math.abs(0 / 16) % 3 = 0
Math.abs(16 / 16) % 3 = 1
Math.abs(32 / 16) % 3 = 2
Math.abs(48 / 16) % 3 = 0
Math.abs(64 / 16) % 3 = 1
Math.abs(80 / 16) % 3 = 2
Math.abs(96 / 16) % 3 = 0
Math.abs(112 / 16) % 3 = 1
Math.abs(128 / 16) % 3 = 2
Math.abs(144 / 16) % 3 = 0
```

Which produces excess overlap near the axes.  However, if one adds a large multiple of 3 after dividing by 16 instead of taking the absolute value, proper spacing is maintained:
```
(-160 / 16 + 402653184) % 3 = 2
(-144 / 16 + 402653184) % 3 = 0
(-128 / 16 + 402653184) % 3 = 1
(-112 / 16 + 402653184) % 3 = 2
(-96 / 16 + 402653184) % 3 = 0
(-80 / 16 + 402653184) % 3 = 1
(-64 / 16 + 402653184) % 3 = 2
(-48 / 16 + 402653184) % 3 = 0
(-32 / 16 + 402653184) % 3 = 1
(-16 / 16 + 402653184) % 3 = 2
(0 / 16 + 402653184) % 3 = 0
(16 / 16 + 402653184) % 3 = 1
(32 / 16 + 402653184) % 3 = 2
(48 / 16 + 402653184) % 3 = 0
(64 / 16 + 402653184) % 3 = 1
(80 / 16 + 402653184) % 3 = 2
(96 / 16 + 402653184) % 3 = 0
(112 / 16 + 402653184) % 3 = 1
(128 / 16 + 402653184) % 3 = 2
(144 / 16 + 402653184) % 3 = 0
```

I don't know why Greg chose that particular number.  Given that Minecraft limits the playable area to -30000000<=x, z<30000000 (ref http://minecraft.gamepedia.com/World_boundary), adding 1875000 after dividing by 16 would be sufficient.

**Comment by Techlone** [comment]
> I don't know why Greg chose that particular number

It's theoretical maximum.
The type of coordinates (this.mX and this.mZ) is int. The min value is -2147483648 => the min coordinate of a chunk is -2147483648 / 16 = -134217728 => then multiply by three: -134217728 \* 3 = -402653184.

**Comment by Antifluxfield** [comment]
Why not use something like "(this.mX / 16 - 1) % 3 == 0"? Whether it uses positive or negative numbers as the remainder, the divisibility never changes. No need to consider about the limit.

**Comment by MauveCloud** [comment]
> Why not use something like "(this.mX / 16 - 1) % 3 == 0"? Whether it uses positive or negative numbers as the remainder, the divisibility never changes. No need to consider about the limit.

I wasn't certain that would work, but when I actually tried it in a small Java program, it gives the desired spacing:

```
(-160 / 16 - 1) % 3 = -2
(-144 / 16 - 1) % 3 = -1
(-128 / 16 - 1) % 3 = 0
(-112 / 16 - 1) % 3 = -2
(-96 / 16 - 1) % 3 = -1
(-80 / 16 - 1) % 3 = 0
(-64 / 16 - 1) % 3 = -2
(-48 / 16 - 1) % 3 = -1
(-32 / 16 - 1) % 3 = 0
(-16 / 16 - 1) % 3 = -2
(0 / 16 - 1) % 3 = -1
(16 / 16 - 1) % 3 = 0
(32 / 16 - 1) % 3 = 1
(48 / 16 - 1) % 3 = 2
(64 / 16 - 1) % 3 = 0
(80 / 16 - 1) % 3 = 1
(96 / 16 - 1) % 3 = 2
(112 / 16 - 1) % 3 = 0
(128 / 16 - 1) % 3 = 1
(144 / 16 - 1) % 3 = 2
```
