### ISSUE TITLE
Diesel gens (single block gens?) broken

### ISSUE THREAD

**Issue by Technus** [Blood-Asp/GT5-Unofficial#719]
https://github.com/GTNewHorizons/NewHorizons/issues/759

**Comment by Blood-Asp** [comment]
Can not reproduce as described. Is the amount of nitrofuel <1000L, the last universal fluid cell will not be filled and empty cells stay in upper slot.

**Comment by Technus** [comment]
Hmm i don't remember changing anything in the item handling code, might've not ported something.

**Comment by Blood-Asp** [comment]
Did you do some code change to allow fluid cells to be partly filled?

**Comment by Technus** [comment]
nope

**Comment by Technus** [comment]
I am waiting for the guy to make a vid, and meanwhile trying to reproduce too

**Comment by Blood-Asp** [comment]
What i did:
1: Placed Diesel gen
2: Put in 8 nitodiesel cells
3: gen used 2L, left 7998L nitro diesel
4: put in 16 empty universal fluid cells
5: took out 7 full universal fluid cells
6: 998L nitro diesel and 9 emtpy universal cells left, nothing changes anymore.

**Comment by Technus** [comment]
i did:

placed diesel
put inside stack of >universal< fluid cells with nitro diesel on top
then took everything out (items only)
(there was x buckets+995mB inside)
then i put stack of empty  >universal< fluid cells on top
and took the output (leaving the top)
and it happened

**Comment by Blood-Asp** [comment]
So it has to be a issue in your fork...

**Comment by Technus** [comment]
k then will compare the codes

**Comment by Technus** [comment]
found it one line of code that was missing for some reason...
