### ISSUE TITLE
Biomes O Plenty causes GT to generate overworld features in the Nether

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#726]
With Biomes O Plenty installed, and GregTech's WorldGeneration.cfg left as defaults, I've seen black granite in the Nether, and the first 4 ore veins I've found were a Galena vein, two Lignite veins, and a Pitchblende vein, which are not supposed to generate in the Nether.

It seems to be related to line 51 in GT_Worldgenerator.java:
```java
this.mList.add(new WorldGenContainer(new XSTR(aRandom.nextInt()), aX * 16, aZ * 16, ((aChunkGenerator instanceof ChunkProviderEnd)) || (aWorld.getBiomeGenForCoords(aX * 16 + 8, aZ * 16 + 8) == BiomeGenBase.sky) ? 1 : ((aChunkGenerator instanceof ChunkProviderHell)) || (aWorld.getBiomeGenForCoords(aX * 16 + 8, aZ * 16 + 8) == BiomeGenBase.hell) ? -1 : 0, aWorld, aChunkGenerator, aChunkProvider, aWorld.getBiomeGenForCoords(aX * 16 + 8, aZ * 16 + 8).biomeName));
```

That includes a comparison to BiomeGenBase.sky or BiomeGenBase.hell for determining the dimensionType passed to the WorldGenContainer constructor, instead of checking the dimension id, or at least checking the Forge biome dictionary for the biome being marked as a Nether or End biome type.

**Comment by MauveCloud** [comment]
Update: I found a Coal vein where the predicted vein center was in "Hell" biome.  However, if I'm understanding line 51 correctly, should have caused GT to treat the area as Nether dimension, and "re-roll" the vein type if it picked one that wasn't valid for the Nether.  Now I'm extra confused.

**Comment by MauveCloud** [comment]
Update 2: Looking closer at my copy of WorldGeneration.cfg (pasted here: http://paste.ubuntu.com/23478605/ which I have _not_ manually edited), I notice some oddities in the "dimensions" section:  

There are a number of mix veins that are supposed to default to false in the Nether according to http://ftb.gamepedia.com/GregTech_5/Mining_and_Processing (such as lignite, salts, and diamond) but are somehow defaulting to true, while some veins that are supposed to default to true (such as nether quartz, sulfur, small nether quartz, and small saltpeter) are defaulting to false.

Even weirder are the mixes listed with both true and false as default.

**Comment by MauveCloud** [comment]
Okay, NEI data dump reveals why having the predicted vein center in "Hell" biome was not enough to make GregTech forbid Overworld mixes there: the class for that biome is "biomesoplenty.common.biome.overridden.BiomeGenBOPHell".  However, I had explored a bit with "Debug=true", and confirmed that it eventually generated a Nether Quartz vein somewhere (and I think a Sulfur vein as well), but I'm still not sure how - if BoP was using its own version of "Hell" biome, I'd expect the line I quoted before to treat all of the BoP Nether biomes as being Overworld for purposes of ore generation.

**Comment by Blood-Asp** [comment]
I wonder, this must have been the case since GT5 started about 3? years ago and no one did ever complain about this? Was there some change on BoP side? This is not 1.10.2, right?

**Comment by MauveCloud** [comment]
BoP removed the Nether biomes as of Minecraft 1.8.9 and hasn't re-added them yet - see https://github.com/Glitchfiend/BiomesOPlenty/issues/606

Thus it won't trigger this in 1.10.2.

Also, idk how many players actually use GT5 in combination with BoP - in the Beyond Reality modpack, BoP is an optional mod iirc, and the other popular GregTech modpack, Infitech 2, doesn't include BoP.

I don't think a change on the BoP side is to blame, since according to GitHub, the last change to that "BiomeGenBOPHell" class was Jun 8, 2014 (when it was added)

**Comment by mura3277** [comment]
So since I recently started a new modpack, I ran into this issue yesterday. (Couldn't find a sulfur vein).

This wasn't an issue in 5.09.20 as I can remember finding sulfur in the nether with that version. I'm using the same BoP AND RTG version in my new pack, but with GT 5.09.28pre. So this must be since .19 / .20.

**Comment by MauveCloud** [comment]
If it recently changed in GT, then apparently I've been looking in the wrong place for why it's happening - according to the commit history, GT_Worldgenerator.java was moved in GitHub in October 2015, making it difficult to track further back than that, but I checked 5.07.07 via jd-gui and that instanceof check for ChunkProviderHell and comparison to BiomeGenBase.hell was there also.

**Comment by MauveCloud** [comment]
Update: I can tell now that this is not a recent issue.  With GT 5.08.00, BoP build 1067 (the oldest I could find on CurseForge, it's dated March 4, 2015), and completely fresh config files (I deleted the contents of the config folder beforehand to make sure), I started a creative game with Biomes O Plenty world type, went into the Nether, and within a few tries, I found a diamond vein.

**Comment by OvermindDL1** [comment]
/me confirms that this happens, has always disabled BoP Nether biomes because of this

**Comment by MauveCloud** [comment]
I hesitate to make a new PR for this while there's a pending one with a change near the relevant line (see #975).  However, I think changing `((aChunkGenerator instanceof ChunkProviderEnd)) || (aWorld.getBiomeGenForCoords(aX * 16 + 8, aZ * 16 + 8) == BiomeGenBase.sky) ? 1 : ((aChunkGenerator instanceof ChunkProviderHell)) || (aWorld.getBiomeGenForCoords(aX * 16 + 8, aZ * 16 + 8) == BiomeGenBase.hell) ? -1 : 0` to simply `aWorld.provider.dimensionId` in the call to the WorldGenContainer constructor will fix this.  

This may have the mild side effect of making GT oregen default to false in non-vanilla dimensions, such as the Twilight Forest or the Outer Lands from Thaumcraft 4, but I imagine modpack makers would want to customize the oregen for those dimensions anyway.
