### ISSUE TITLE
Oil drilling rig not work.

### ISSUE THREAD

**Issue by Pilad** [Blood-Asp/GT5-Unofficial#728]
I use latest build 26 from onedrive.
http://pixs.ru/showimage/2016110501_6689284_23919717.png
http://pixs.ru/showimage/2016110501_9808298_23919724.png
http://pixs.ru/showimage/2016110501_6904271_23919733.png
http://pixs.ru/showimage/2016110501_1541295_23919738.png
Oil is found. Output hatch is empty.

**Comment by Blood-Asp** [comment]
Uploaded first .27pre build on onedrive. Does the fix for oil drilling rig work there?

**Comment by Pilad** [comment]
Yes. Rig is work.
