### ISSUE TITLE
Forestry Combs can't be centrifuged any more.

### ISSUE THREAD

**Issue by Dream-Master** [Blood-Asp/GT5-Unofficial#73]
Forestry Combs can't be centrifuged any more with Version 5.08.20.

Works well with 5.08.19

**Comment by Blood-Asp** [comment]
Update Forestry

**Comment by Dream-Master** [comment]
I have to using the stable one because i can't update Computronics not working with unstable version.
What is changed ?

**Comment by aerospark** [comment]
I'm fairly sure this is the cause: 
https://github.com/ForestryMC/ForestryMC/issues/703

**Comment by Dream-Master** [comment]
?

**Comment by aerospark** [comment]
Forestry changed it's centrifuge recipes to a new float-based system instead of an integer so it breaks compatibility with older versions

**Comment by Dream-Master** [comment]
Ok I didn't see the link on my Mobil. I know why it happens and I want only that it is compatible for both versions. Adding all recipes with minetweaker back is a pain.

**Comment by Blood-Asp** [comment]
I guess everything is clear now...

**Comment by Dream-Master** [comment]
I get the old class file from Version 19 and everything works.
