### ISSUE TITLE
Flint Pickaxe vs Small Ores

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#730]
Small Tine Ore in Blue Shcist stone can't be mined neither by Flint nor by even Iron pickaxe.

**Comment by dalekin** [comment]
Harvest Level of small ores changes for ores spawned in Underground Biomes blocks which have BlockMeta 3 and 4. In getHarvestData they receive harvest level 3 as if they locate in black or red granite.

**Comment by SapientMC** [comment]
Additional info:
Also something wrong with mining level of several normal ores in several UBC stone variants.
