### ISSUE TITLE
[1.10.2] AbyssalCraft Crash

### ISSUE THREAD

**Issue by MechanosG** [Blood-Asp/GT5-Unofficial#731]
If AbyssalCraft is installed when trying to use GT5, you get a crash on load with this error:
"java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=metadata, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} to 836 on block gregtech:gt.blockores, it is not an allowed value"

Included crashlog.
[crash-2016-11-04_20.35.53-client.txt](https://github.com/Blood-Asp/GT5-Unofficial/files/573003/crash-2016-11-04_20.35.53-client.txt)

**Comment by Dragon2488** [comment]
Its abyssal craft issue.

**Comment by MechanosG** [comment]
Any chance you could elaborate so I can go report it to them instead?  Just in case it might help them.
