### ISSUE TITLE
NEI filter doesn't work with UB ores

### ISSUE THREAD

**Issue by Techlone** [Blood-Asp/GT5-Unofficial#732]
![image](https://cloud.githubusercontent.com/assets/17011260/20029937/2008c1f4-a37c-11e6-9136-233ace467729.png)
With UndergroundBiomes I can't filter ores normally. It's very uncomfortable.
Bug of NEI or GT?

**Comment by Blood-Asp** [comment]
seems to be NEI. Or i have no idea.

**Comment by leagris** [comment]
If you need to filter by oredictionary name use `#ore` instead

**Comment by Techlone** [comment]
@leagris I know only about at sign. If hash works it's great thx.

**Comment by Techlone** [comment]
@Muramasa- reopen the issue please for a reminder.
Hint: look at a using of `tHideOres` variable in `GT_Block_Ores_Abstract` class.

**Comment by mura3277** [comment]
@Techlone The problem with this is you can't hide ores in NEI AND have them highlighted with NEI search because NEI excludes stacks that have been hidden with its API in its own search tool.

**Comment by Techlone** [comment]
@Muramasa- I hacked this filter but I'm not sure if this worth it. I think it's not.
Code from the `onPreLoad` method
```
if (GregTech_API.isNeiLoaded) {
    List list = new LinkedList<codechicken.nei.api.ItemFilter.ItemFilterProvider>() {
        @Override
        public boolean add(codechicken.nei.api.ItemFilter.ItemFilterProvider itemFilterProvider) {
            if (itemFilterProvider.getClass().getEnclosingClass() != codechicken.nei.api.ItemInfo.class) {
                return super.add(itemFilterProvider);
            }
            return super.add(new codechicken.nei.api.ItemFilter.ItemFilterProvider() {
                @Override
                public codechicken.nei.api.ItemFilter getFilter() {
                    return new codechicken.nei.api.ItemFilter() {
                        @Override
                        public boolean matches(ItemStack itemStack) {
                            return codechicken.nei.NEIClientConfig.world.nbt.getBoolean("searchinventories") || !codechicken.nei.api.ItemInfo.hiddenItems.contains(itemStack);
                        }
                    };
                }
            });
        }
    };
    try {
        Field field = GT_Utility.getField(codechicken.nei.ItemList.class, "itemFilterers");
        Field modifiers = GT_Utility.getField(field, "modifiers");
        modifiers.setInt(field, field.getModifiers() & ~Modifier.FINAL);
        field.set(null, list);
    } catch (Exception ignored) {
    }
}
```
Anyway the simplest solution is disable HideUnusedOres in the general config.

**Comment by draknyte1** [comment]
I wouldn't suggest disabling the config option for everyone because 95% of players aren't affected by this issue.

**Comment by mura3277** [comment]
I think he means if someone wants the ability to filter all the ore types they can disable HideUnusedOres in their config.

**Comment by Techlone** [comment]
@draknyte1 it's useful at the early game for those who play with UB and use NEI's SearchInventory mode. And it can be reverted when you will reach the Ore drilling plant.
>because 95% of players aren't affected by this issue

Sure but I hope that it will help somebody even if it's only one person :)
Let's close this.
