### ISSUE TITLE
Steeleaf rings not craftable

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#733]
Everything other Steeleafy is craftable (rods, plates, bolts, etc...) Only Rings are not.

Tested in fresh instance with GT only (using configs from Infitech to enable Steeleaf)

GT: 5.09.26

**Comment by Blood-Asp** [comment]
after a long long time...
Should be possible to enable by adding them to a MT script. I still have to find out why it does not work in the config.
