### ISSUE TITLE
Suggestion - Internal Fluid tank switching (Like IC2 Fluid canner can)

### ISSUE THREAD

**Issue by Lithorn** [Blood-Asp/GT5-Unofficial#734]
Can we get this added to things like Electrolyzer, distillery, Chemical Reactor, it would help to alleviate loss of a lot of potential use of material liquids. Any machine really that has 2 fluid tanks should be able to switch, this way you won't lose a lot having to break the machine down and place it or make more and more (Unless that is what you intended?)

**Comment by Dragon2488** [comment]
(Or just abjust how much fluid you insert into input slot)

**Comment by Lithorn** [comment]
How?

**Comment by Timeslice42** [comment]
The fluid regulator cover combined with a status/machine cover combo should work.
Also, you can clear the tanks on a machine by using a GT plunger on the machine block (not the UI).

That being said, I _really_ wish that GT had a tool like the pipette from forestry.

**Comment by Blood-Asp** [comment]
adding new buttons to machine guis is a no.
