### ISSUE TITLE
Adv Miner II dupes Oilsand.

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#735]
While mining Oilsand Adv Miner II add 1-5 blocks of oilsand per operation to output bus. Bus it does not take away blocks from Overworld. Mining pipe even does not move down after more than 1000 Oilsand blocks mined.

**Comment by codewarrior0** [comment]
I can't confirm that it happens now, but this did not happen in 5.09.21.

**Comment by SapientMC** [comment]
i'm on latest 27pre

**Comment by codewarrior0** [comment]
Dunno if it's relevant, but I just let an advminer run for a couple of hours and found two oilsand blocks in its output. There were no oilsand veins within 100 blocks of the thing.

**Comment by SapientMC** [comment]
@codewarrior0 may be you mined it somewhere else during AdvMiner working?

**Comment by codewarrior0** [comment]
Yes, I did! And I found out exactly what is happening. Patch incoming.
