### ISSUE TITLE
Basic Diesel Generator doesn't correctly generate with Nitro-Diesel fuel

### ISSUE THREAD

**Issue by JackB1024** [Blood-Asp/GT5-Unofficial#736]
There is a bug in how generators decide to burn new fuel which causes Basic Diesel Generators to not be able to work at full speed when using Nitro-Diesel Fuel.

It is in the code to determine how much fuel to use (in GT_MetaTileEntity_BasicGenerator line 194)
Basically it does :  maxEUOutput() * 20 + getMinimumStoredEU() - aBaseMetaTileEntity.getUniversalEnergyStored()) / tFuelValue
Subbing in values we get
(32 * 20 + 512 - (energyStored)) / 512
= (640 + 512 - (energyStored)) / 512
as this is an integer divide, we will only burn fuel if the numerator is larger than the denominator, so this is
640 + 512 - energyStored >= 512
now this seems like it would work fine, given that 1152 is > the amount we would burn in 10 ticks (320), however there is an issue...
getMinimumStoredEU() is EU that while stored, will never exit the machine. (drainEnergyUnits has a check that the energy being taken will not put the stored energy under this value)
Eg, Lets take our current energy to be 641.
640 + 512 - 641 >= 512 is 511 >= 512, so no fuel will be consumed this tick
however while we have 641 energy stored, 512 of that will never be used, so we only effectively have 129EU, which is enough for only 4 ticks, the generator will not attempt to burn fuel for 10 ticks, so we will effectively be offline for 6 of the next 10 ticks.

Why not instead use:
(maxEUStore() - aBaseMetaTileEntity.getUniversalEnergyStored()) / tFuelValue
That way it will just burn however much fuel is needed to as closely fill the tank as possible.

**Comment by Blood-Asp** [comment]
Just noticed i fixed this 3 months ago and forgot to close this...
