### ISSUE TITLE
[5.10.06] Pipe covers not working

### ISSUE THREAD

**Issue by willis936** [Blood-Asp/GT5-Unofficial#737]
Pipes connect to each other and machines but cannot have covers placed on them.

**Comment by Dragon2488** [comment]
Covers wont work correctly on 1.10.

**Comment by willis936** [comment]
Do you mean they will never work in 1.10 or just for now?

**Comment by Dragon2488** [comment]
They need re-implementation for 1.10.2 they will work, but not now.
