### ISSUE TITLE
Solar Boiler gains heat at night

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#74]
As title says, Solar boiler is heating up constantly even when night. Happens on SP and MP as well.
![8dd4c336-1a84-11e5-8105-cde4273b786e](https://cloud.githubusercontent.com/assets/4236895/8350132/1034b4c8-1b23-11e5-8307-b5931090e196.png)

**Comment by Blood-Asp** [comment]
fixed in 5.08.21
