### ISSUE TITLE
[5.9.26] Missing Quarried Stone -> Marble Dust recipe

### ISSUE THREAD

**Issue by Timeslice42** [Blood-Asp/GT5-Unofficial#741]
Somewhere recently we lost the Railcraft Quarried Stone macerator/pulverizer recipe. It should be returning marble dust. It should probably return one dusts now instead of the nine that it historically returned.

**Comment by MauveCloud** [comment]
I don't see such a recipe in 5.08.33.  Are you sure it was a GregTech-native recipe, rather than added by IHL or a Minetweaker script for a modpack?

**Comment by Timeslice42** [comment]
It's a GT4 recipe that's been in and out of GT5 several times. Actually, I think it even dates all the way back to minecraft 1.4.7, so that would be... GT 2.78 maybe?
