### ISSUE TITLE
Graphite usage

### ISSUE THREAD

**Issue by Dimach** [Blood-Asp/GT5-Unofficial#743]
Graphite now uses only to make graphene and in arc furnace.
Maybe add electrolyzer recipe to convert its to carbon (because this realistic) or make it possible to use as fuel?

**Comment by codewarrior0** [comment]
Would love to convert Graphite to Carbon. I can convert Diamond Dust to Carbon too, after all.

**Comment by Timeslice42** [comment]
Or at least let us make pencils so we don't need ink and quill for everything ;)

I never did understand why we can't convert graphite to carbon, but IANAC.

**Comment by MauveCloud** [comment]
Technically it's already possible to get a little bit of carbon from graphite cells by putting them in an arc furnace to get small ashes, which can then be combined and centrifuged for carbon dust, but I often add a Minetweaker script for graphite to carbon dust in the electrolyzer (16 carbon output, same voltage as for diamond dust, but 1/4th the time)

**Comment by dalekin** [comment]
May be convert carbon to graphite? And get solar panels from graphene wires?
