### ISSUE TITLE
[GT5u 1.10.2] General lag issues

### ISSUE THREAD

**Issue by Silvrus** [Blood-Asp/GT5-Unofficial#746]
Mods: GT5u, IC2, JEI
Forge: 12.18.2.2122

I'm getting serious lag while playing the game, blocklag, worldgen lag, etc. No CTD's or crash logs, but I am getting this in the console: 
[18:00:45] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]

Here is a pastebin of the latest.log file: http://pastebin.com/LW7drWYV
Please let me know if more information is needed, thanks!

**Comment by GordonHollow** [comment]
Has same trouble with lags while playing, game just skipping ticks with greg

Had the same console-spamming, but without waila - no more console-spam

But game lagging already with 16Gb RAM

**Comment by Dragon2488** [comment]
@Silvrus How much memory have you allocated? If you allocated too much memory like @GordonHollow, it will lag much worse than with 1 GB. I recommend something near 4 GB for playing modded 1.10.2.

**Comment by GordonHollow** [comment]
Hm...
When i'm allocating less than 6 GB game just don't load in main menu 
And Java consume more than allocated anyway, with allocated 8 GB it consume near 12 GB, but this don't GT problem, it's just Java
But world lagging come with GregTech and ticks skipped

**Comment by Silvrus** [comment]
@Dragon2488 4GB, same as I've always allocated. It never eats it all up, but does run up 85-90% before dumping the garbage.

**Comment by Silvrus** [comment]
Has this been resolved?

**Comment by Dragon2488** [comment]
If it was closed, how do you think?

**Comment by Silvrus** [comment]
Sorry, just curious as I don't see an update yet, and nothing stating what the issue was and what was fixed.

**Comment by GordonHollow** [comment]
A don't see any update too, only in dev-version that crashes themselves without any other mods

**Comment by Dragon2488** [comment]
@GordonHollow @Silvrus now i publish builds just in builds/libs:
https://github.com/Blood-Asp/GT5-Unofficial/tree/1.10.2/build/libs

**Comment by GordonHollow** [comment]
@Dragon2488 this console spam stopped with last version gregtech
but now it spams Skipping BlockEntity with id GT_TileEntity_Ores when i try loading in world

**Comment by Blood-Asp** [comment]
afaik the TE ores got removed in favour of normal block ores that need more IDs instead. So loading up a old world with the new version will remove all the prior generated ores.

**Comment by Dragon2488** [comment]
yeah. exactly.
