### ISSUE TITLE
Can't board minecart while holding GT metatool (with Railcraft installed)

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#748]
Without Railcraft, I can board a minecart while holding a GT axe (or presumably pick, shovel, etc. - something that has no special right-click effect).  However, with Railcraft installed, having a GT metatool selected on the hotbar makes right-clicking the minecart have no effect - I have to switch to something else, such as a block, torch, or an empty slot to be able to board the minecart.  Holding non-GT tools, such as a vanilla diamond sword, diamond pickaxe, or a Railcraft steel pickaxe, still allow me to board the cart.

I can understand not being able to board while holding a crowbar, since that has a special right-click effect for linking carts (with Railcraft installed), but most other tools should not interfere.

**Comment by Dragon2488** [comment]
All metatools implement same RC crowbar interface, so that's why it happens.

**Comment by MauveCloud** [comment]
So... this is effectively a Railcraft bug?  Because GT_MetaGenerated_Tool optionally implements IToolCrowbar, RC treats all of them as crowbars, preventing minecart boarding, even though most of them return false for canWhack, canLink, and canBoost?

**Comment by draknyte1** [comment]
^Yes.
That's what interfaces are for, if they're returning the correct values for non-crowbars, it's RC.

**Comment by MauveCloud** [comment]
Looking at Railcraft source code, I can't make sense of why it happens in 1.7.10.  1.10.2 code has a couple of times where it cancels the minecart interaction event if the tool involved is an instance of IToolCrowbar before checking canLink etc., but the 1.7.10 version looks like it only cancels the event if the crowbar is actually used to start/complete/break a link.

However, since you've confirmed that this isn't really a GT-side bug, I'll close this issue.
