### ISSUE TITLE
Oil not being generated "kinda"

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#749]
So this came after some testing of why the hell there is no Oil in 20 prospected 96x96 areas.

For some reason the Prospector doesn't show Liters. Only when I actually built and started Oil Rig, it then started to show.

Recreate steps:
1) Prospect an area using Seismic Prospector
2) Do usual steps to create a book, the book will contain 0L of certain type of Oil
3) Build a rig and start it up, let it drill down to the bedrock
4) Rig starts to get some Oil, even since the prospecting said 0L (it is the same type of oil as reported in the book)
5) Prospect the area again
6) The book now says correct number of L.

GT: 5.09.26

**Comment by Timeslice42** [comment]
What happens if you immediately prospect the same area twice in a row?
