### ISSUE TITLE
Fusion reactor spam issue.

### ISSUE THREAD

**Issue by Anikilulala** [Blood-Asp/GT5-Unofficial#75]
Just the same issue reported 
https://github.com/Blood-Asp/GT5-Unofficial/issues/46
It might be caused by println codes
System.out.println("fluidAchievement "+fluid.getFluid().getUnlocalizedName());
in main/java/gregtech/loaders/misc/GT_Achievements.java,line 271

**Comment by Blood-Asp** [comment]
Missed that. Now removed.

**Comment by Anikilulala** [comment]
But the spamming codes is still there.
Maybe codes on github is not up to date?
Haven`t tested on the server...
