### ISSUE TITLE
Multiple advanced miners mixed output

### ISSUE THREAD

**Issue by Usernm0** [Blood-Asp/GT5-Unofficial#751]
I build two advanced miner setups. One on tungsten ore, and other on platinum ore. Ore drops in little ae setups, and i see, that i get sheldonite ore on tungsten deposit, and scheelite on platinum deposite. Both ore mixes are rare, and i check around chunks for ores. No platinum near tungsten, and no tungsten near platinum.

**Comment by ZMikkie** [comment]
Confirming that. We have a server running GregTech-5.09.26. When there are multiple miners, they get mixed outputs too. Like, naquadah in overworld when one miner in end, or iridium and sheldonite in nether, when other miner is on platinum vein in overworld.
