### ISSUE TITLE
[Question] Scythe Durability

### ISSUE THREAD

**Issue by Timeslice42** [Blood-Asp/GT5-Unofficial#754]
@Blood-Asp When you improved scythes, did you decrease the amount of damage they took from breaking ground cover (grass, flowers, etc.)? It feels like you did, however it definitely does not seem to be taking less damage from harvesting crop sticks. This still seems to be breaking scythes rather quickly.

**Comment by MauveCloud** [comment]
Looking at https://github.com/Blood-Asp/GT5-Unofficial/commit/a8f91902d1c64062d27c0b09c7cd5e8ba5bc51aa#diff-87fe258e47c19de0092c90a50e014bba it looks like the amount of damage they take wasn't changed, but their durability got buffed 4x.

**Comment by Blood-Asp** [comment]
The durability is set on crafting, so it should be better with an newly crafted sense. Does it?

**Comment by Timeslice42** [comment]
Yes it is. I think the only problem is that the durability of the scythe is getting reduced by the hardness of the crop sticks, rather than the crops. So clearing flowers or vanilla crops is quite cheap, but harvesting IC2 crops is far more expensive. I feel like the flowers and vanilla crops should cost more to harvest, and the IC2 crops should cost less (ideally with the same cost for all of them), but I don't see a clean way to do that.
