### ISSUE TITLE
Pollution causing server time-out loop??

### ISSUE THREAD

**Issue by lilmoefow** [Blood-Asp/GT5-Unofficial#758]
https://gist.github.com/lilmoefow/8e57a05bdbfa3b3533f5a76ff4940bfc

Our server was stuck in a "time-out" loop.  It would not create a crash log.  Playing the Beyond Reality mod pack, I have reported to them but was also told to post here as well.  I was able to "fix" it, by disabling the pollution config option.  Which allowed for the effected player to log on, "crashing" the server again. After it restarted again, the player was able to log on fine.  When disabling Pollution in the configs, does it remove it from world? Or is the Pollution residual?

forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
gregtech-5.09.26pre.jar

**Comment by Blood-Asp** [comment]
should be fixed in actual .26 release or .27pre builds.
