### ISSUE TITLE
[1.10.2] IC2 Recipe issues

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#762]
Appears that ANY item from IC2 can be crafted using ANY metaitem.01 from GT.

For example Heat Conductor. I can craft it with anything. Screenshot shows an example of this with EnderPearl Dust

![image](https://cloud.githubusercontent.com/assets/4236895/20457035/5ebcb26e-ae82-11e6-8647-b6058d44c266.png)

GT 5.10.6

**Comment by MauveCloud** [comment]
This is a duplicate of https://github.com/Blood-Asp/GT5-Unofficial/issues/710 that I posted a few weeks ago.

Edit: also, technically, I don't think it's quite _any_ item from IC2, only those that some gt.metaitem.01 already has the right ore dictionary registration for.  Try looking up the recipe for reinforced glass, for example.  I'm guessing that one won't show gt.metaitem.01 as a possibility.

**Comment by JasonMcRay** [comment]
Oh I have missed it...  thanks
