### ISSUE TITLE
[1.10.2 - 5.10.6] Breaking with correct tool - destroys block

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#763]
Machines get destroyed when broken with a wrench.

edit: Same goes for wires when using Wire Cutters

**Comment by JasonMcRay** [comment]
@Dragon2488 Does this mean it is fixed? Because well... I loaded GT 5.10.22 I can now break any machine with just a bare hand and drops itself.

**Comment by Dragon2488** [comment]
Lol. Ill watch it today.
