### ISSUE TITLE
Torches from coal config error

### ISSUE THREAD

**Issue by dalekin** [Blood-Asp/GT5-Unofficial#764]
In recipes.cfg
B:torchesFromCoal_false=true    disables torches from coal recipes
B:torchesFromCoal_false=false   enabled torches from coal recipes

But it must be over the left.
If B:torchesFromCoal_false=false then it must be no recipes with coal.

**Comment by MauveCloud** [comment]
I disagree.  This is in the "disabledrecipes" section, correct?  That means that "true" disables the recipe, and "false" leaves the recipe enabled.  It's only counter-intuitive if you ignore the section name.
