### ISSUE TITLE
[Cleanup] GT Hydration Spray

### ISSUE THREAD

**Issue by Timeslice42** [Blood-Asp/GT5-Unofficial#765]
I don't remember if this recipe actually got ported over from GT4, but this item can be completely removed as now the IC2 hydration cell's only use is as a hydration spray.

File: GT5-Unofficial/src/main/java/gregtech/api/items/GT_Spray_Hydration_Item.java

**Comment by Blood-Asp** [comment]
Reading again i finally understand what you mean.
There is quite a lot dead code in GT5, but cleaning it up does not really help that much. At best a few KB less .jar size.

**Comment by Andrey96** [comment]
Actually this item is pretty useful to have. It can clean tileentities from color and has durability unlike water bucket that can be used only once and then must be refilled.
