### ISSUE TITLE
Some gases incorrectly registered as liquids

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#766]
The mod NEI Integration makes it possible to view details of the Forge Fluid Registry, revealing that some fluids are registered with "State: Liquid" when they should be gaseous:
Hydric Sulfide (boiling point 213 K: https://en.wikipedia.org/wiki/Hydrogen_sulfide)
Chlorine (boiling point 239.11 K: https://en.wikipedia.org/wiki/Chlorine)

**Comment by draknyte1** [comment]
The materials are defined as such based on other properties.. 

```
if (FluidRegistry.registerFluid(rFluid)) {
			switch (aState) {
			case 0:
				rFluid.setGaseous(false);
				rFluid.setViscosity(10000);
				break;
			case 1:
			case 4:
				rFluid.setGaseous(false);
				rFluid.setViscosity(1000);
				break;
			case 2:
				rFluid.setGaseous(true);
				rFluid.setDensity(-100);
				rFluid.setViscosity(200);
				break;
			case 3:
				rFluid.setGaseous(true);
				rFluid.setDensity(55536);
				rFluid.setViscosity(10);
				rFluid.setLuminosity(15);
			}
		} else {
			rFluid = FluidRegistry.getFluid(aName);
		}
```

Most materials don't have the right bit for gas anyway.

**Comment by Blood-Asp** [comment]
If you want to check more fluid states, this is the list: https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/loaders/preload/GT_Loader_Item_Block_And_Fluid.java#L391-L455
0: Semifluid
1/4: Fluid
2: Gas
3: Plasma
