### ISSUE TITLE
better mining drills

### ISSUE THREAD

**Issue by Nex4rius** [Blood-Asp/GT5-Unofficial#770]
Could you add a high end mining drill that can mine 3x3 blocks?

**Comment by JasonMcRay** [comment]
I remember that blood said he will not add 3x3 tools, because they already exist within GT++ addon-mod

**Comment by draknyte1** [comment]
I've considered 3x3 drills, but they're not on my roadmap yet.
GT++ already has 3^2 Spades and Pickaxes though.

**Comment by Blood-Asp** [comment]
well, at last there are 3x3 tools in GT++. So, at last for now it will not be added to GT5 directly.
