### ISSUE TITLE
The multi block diesel engine was output 9 times when boost

### ISSUE THREAD

**Issue by johzhao** [Blood-Asp/GT5-Unofficial#771]
The mEfficiency was 30000 at max for multi block diesel engine.
In checkRecipe method, this.mEUt was multiply by 3 when boost at max efficiency.
In onRunningTick method, it generate EU with value of the mEUt multiply by 3.
That cause the diesel engine output 9 times when boost. Is this a bug or by design?

**Comment by codewarrior0** [comment]
Can confirm. Boosted diesel engine with IV Dynamo Hatch (8k EU) supplies enough voltage to run an EBF with IV Energy Hatch (8k EU). Portable Scanner incorrectly says the engine only outputs 6k.

**Comment by codewarrior0** [comment]
Huh. My Diesel Engine is continuing to produce energy even after turning it off with a mallet. It's not consuming any inputs and is still putting out 8k EU. Will investigate some more.

EDIT: After breaking and rebuilding the IV Dynamo Hatch, it no longer produces energy after shutoff.

EDIT 2: See #785
