### ISSUE TITLE
Sulfuric Acid recipes seem to ignore chemical formula

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#773]
In GregTech 5.09.23, looking up the recipes for sulfuric acid reveals basically two ways to do it:
1. Combine hydrogen sulfide with water in a chemical reactor
2. Combine sulfur dust with water in a chemical reactor, using a circuit to control it (and possibly to distinguish the recipe from the fertilizer recipes and the liquid rubber recipe).

However, looking at the chemical formulas, those recipes make no sense:
1. H2S + H2O = 3/2 H2SO4
2. S + 2 H2O = 3 H2SO4

Where is it getting the extra oxygen for either, and where is the extra hydrogen going in the first one?

Edit: looking more closely at the quantities in the recipes (which I've updated above), it is even generating extra sulfur in both cases.

**Comment by Nex4rius** [comment]
To make it more real would be cool but then we would also have to increase the energy gain from sulfuric batterys otherwise it would be useless to build something this complex for almost no extra energy.

It would go like this:
1)
<img src="http://imgur.com/RHZ5wsZ.jpg">
Sulfur + Oxygen -> Sulfur dioxide
<img src="http://imgur.com/nRw64cm.jpg">
Hydrogen Sulfide + Oxygen -> Sulfur dioxide + Water
2)
<img src="http://imgur.com/axSWnlv.jpg">
Sulfur dioxide + Oxygen -> Sulfur trioxide
3)
<img src="http://imgur.com/TSxSa4Q.jpg">
Sulfur trioxide + Water -> Sulfuric acid

**Comment by MauveCloud** [comment]
I had not looked that deeply into how sulfuric acid was manufactured IRL, but according to Wikipedia, it also involves vanadium oxide as catalyst for making sulfur trioxide, which would probably require the unstable branch to add as a material.

However, what about considering the chemical reactor to take care of the intermediate steps and making the recipes as follows:
1. 1 hydrogen sulfide cell + 4 oxygen cells (or equivalents with one in fluid input tank) -> sulfuric acid
2. sulfur dust + 3 oxygen cells + water in fluid input tank -> sulfuric acid
Then at least the extra oxygen wouldn't be coming from nowhere and the excess hydrogen mysteriously vanishing.

**Comment by PrincessOfEvil** [comment]
The excess hydrogen is probably just dumped into the air.

**Comment by MauveCloud** [comment]
> The excess hydrogen is probably just dumped into the air.

With no visible venting, even when GT machines can operate underwater or on Galacticraft planets (where there is no air)?

**Comment by Dragon2488** [comment]
Gt machines will explode underwater.

**Comment by MauveCloud** [comment]
> Gt machines will explode underwater.

Not as of 5.09.26.  I tried it earlier today in creative mode, but that shouldn't make any difference to the behavior of the machine once it's running, right?  I've known about this since May 2015: http://forum.industrial-craft.net/index.php?page=Thread&postID=185950#post185950

**Comment by draknyte1** [comment]
GT Machines don't give a fuck about water, only rain. This is by DESIGN, as stated by Greg.
https://github.com/Blood-Asp/GT5-Unofficial/issues/490

If we want proper chemical balance, we need the input of @Vexatos.

**Comment by Vexatos** [comment]
The most commonly-used method is [this](https://en.wikipedia.org/wiki/Contact_process). Uses vanadium(V) oxide as a catalyst.

**Comment by Blood-Asp** [comment]
This is for now a balancing decision.
The chemical processing is already complex enough, to change this would just annoy players...
Also it would then need to recalculate the energy values and more depending on this.
I would say this is a detail that can, for now, be overlooked.
