### ISSUE TITLE
Not able to get Bronze dust achievement

### ISSUE THREAD

**Issue by miguel1118** [Blood-Asp/GT5-Unofficial#78]
I cant get the bronze dust achivement on GT5 (InfiTech 3.1.2)
I've tried with the normal craft (3 copper dust + 1 tin dust on inventory)
Giving me gt bronze dust with creative
Using a mixer
Crafted it with small bronze pile dusts
Converting bronze ingot into dust

Nothing seems to work

http://s28.postimg.org/pxkmhipcd/Sin_t_tulo.jpg

**Comment by pftbest** [comment]
have you tried to drop it on the ground and then pick it up?

**Comment by miguel1118** [comment]
Yes I've tried that lot of times

**Comment by Blood-Asp** [comment]
It only works with crafting.
In GT 5.08.19-5.08.22 there was a bug, that the achievement could only be triggered once per restart, so if you were missing the pickaxe achievement and crafted bronze, you could no longer unlock the bronze achievement.
But the current IT2 version should have 5.08.23...
Can you try to restart IT2, load a creative game and see if you can unlock the achievements in the right order?

**Comment by miguel1118** [comment]
What you mean with "once per restart"?

Is there any file which could I delate to erase my achievements and do them in the right order?

**Comment by Blood-Asp** [comment]
Just restarting the server once. and then it should work again.
Did you make sure, that you really have GT5.08.23 in the pack?
And as i said, try once on a new creative singleplayer world if it is a general problem or just in one case.

**Comment by miguel1118** [comment]
Im playing it on SinglePlayer and I've loged in and out many times but still dont work
Yes I have GT 5.08.23 on the pack
I've tried it again in a new world in the right order, didnt work:
http://s3.postimg.org/450nbsbzn/Sin_t_tulo.jpg

Plus, someone told me that magnetic rod achivement wasnt working on a older version, maybe you should check that all achivements are obtainable

**Comment by Blood-Asp** [comment]
Tested the said achivements and about a dozen more. All worked fine. The achivement checks the crafting output for the oredict tag "dustBronze" test if the crafted bronze really has that tag.

**Comment by j2ghz** [comment]
https://github.com/JasonMcRay/InfiTech-1.7/issues/328
