### ISSUE TITLE
[Request] Side benefits for high tier EBF Coils

### ISSUE THREAD

**Issue by codewarrior0** [Blood-Asp/GT5-Unofficial#783]
With the new ranks of EBF Coils available, it would be wonderful if the EBF had some benefit when doing a recipe that has a (much) lower Coil requirement. Maybe something like reduced processing time when cooking Aluminum (1700K) in an EBF that has HSS-G Coils (5400K).

**Comment by Techlone** [comment]
About coils.
Now coils and an energy hatch do not affect each other. I think more progressive coils must require more progressive energy hatch. For example

Material | Temperature (+diff) | Required EU/tick
-------- | ------------------- | ---------------
Cupronickel | 1800 | 128
Kanthal | 2700 (+900) | 128
Nichrome | 3600 (+900) | 128
Tungstensteel | 4500 (+900) | 512
HSS-G | 5400 (+900) | 512
Naquadah | 7200 (+1800) | 2048
Naquadah Alloy | 9001 (+1801) | 2048

Need to think about game balance. EU/tick has been chosen without thinking.
Table template for your suggestions:
```
Material | Temperature (+diff) | Require EU/tick
-------- | ------------------- | ---------------
Cupronickel | 1800 | 128
Kanthal | 2700 (+900) | 128
Nichrome | 3600 (+900) | 128
Tungstensteel | 4500 (+900) | 512
HSS-G | 5400 (+900) | 512
Naquadah | 7200 (+1800) | 2048
Naquadah Alloy | 9001 (+1801) | 2048
```

**Comment by Techlone** [comment]
Such requirement may be a solution for this issue.

**Comment by codewarrior0** [comment]
I see what you mean, but naturally there is already an incentive to put higher tier energy hatches on the EBF as you progress. Many of the higher tier recipes have only a 120 EU requirement, but they have such long processing times (10 minutes for Tungsten!!) that you will want to bump the hatch up to EV just to cook things at a reasonable pace. And that's even after building several EBFs!

**Comment by Techlone** [comment]
Hmm. How about coil efficiency like in multismelter?
Aluminum needs cupronickel and each next (or each second) tier of coils can smelt 2 times more per operation.

- Cupronickel or Kanthal - 1 Al
- Nichrome or Tungstensteel - 2 Al
- HSS-G or Naquadah - 4 Al
- Naquadah Alloy - 8 Al

**Comment by codewarrior0** [comment]
I like it. It even works in the hatch requirement, since smelting 2 Al at once needs 240 EU/t, so you'll need an HV Hatch to power it.

And to avoid any unpleasant surprises, you can make it so if there's only an MV hatch, it doesn't do the multismelting.

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/e1c60d8bad983d838e9871fdacf5e80f814d81e7
This was easy to code, is not OP and a nice upgrade.
