### ISSUE TITLE
Dynamo Hatch buffers unlimited amounts of EU

### ISSUE THREAD

**Issue by codewarrior0** [Blood-Asp/GT5-Unofficial#785]
In [`addEnergyOutput()`](https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java#L494), the Hatch's capacity is not checked before injecting all energy produced by the Multiblock. This causes the Hatch's energy buffer to increase without limit, storing enough energy that it will eventually roll over to a negative amount, causing sadness. 

`addEnergyOutput()` is unchanged since the last version Greg put out, and it looks like it never got properly tested because he didn't have any multiblock generators. So... I'm just going to add the capacity check right in there.

**Comment by Techlone** [comment]
Second argument in [`increaseStoredEnergyUnits(long aEnergy, boolean aIgnoreTooMuchEnergy)`](https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java#L895) designed for this. Change it to `false` and issue will be solved I think.

**Comment by Techlone** [comment]
Also `increaseStoredEnergyUnits` are using with `true` almost always. May be bugs not only in dynamo hatch?

**Comment by codewarrior0** [comment]
Many of the calls to `increaseStoredEnergyUnits` that I can see will all check the EU capacity, and only increase by the amount it can hold. The other ones are for things like the Magic Energy Absorber, which is probably fine because it eats an enchantment or something and produces a ton of energy all at once.
