### ISSUE TITLE
dustTinyBone missing packing recipes

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#79]
`dustTinyBone` is a small dust of BoneMeal/Bone.
It is a by-product of crushing raw or cooked, meat or fish.

Unfortunately, `dustTinyBone` is unusable, because it is missing both ×9 workbench packing and packager recipes to make it a full dust.

If adding recipe to combine 9× `dustTinyBone` into `dustBone`, don't forget having unification into vanilla Bone Meal.

**Comment by Blood-Asp** [comment]
In my instances all recipes 9 tinyBone = 4 smallBone = 1 Bone Meal work just fine. Maybe some conflict with other mods?

**Comment by leagris** [comment]
Assembler recipe: OK
Workbench shaped: KO
NEI recipes: None is shown.
ModPack: BeyondReality 2.3.2

**Comment by Blood-Asp** [comment]
In other words, a modpack problem. Let them figure out which combination of mods breaks the recipes in NEI and narrow the reason down.
There are some similliar bugs. One i know of: http://bt.industrial-craft.net/view.php?id=1632 
It is not the same, but "close".
