### ISSUE TITLE
[Request] Add way to not generate superheated steam in LHE

### ISSUE THREAD

**Issue by Usernm0** [Blood-Asp/GT5-Unofficial#790]
We need smaller input hatch, less than 1 bucket of liquid, or ajustable input hatch volume. Or maybe integration circuit option to not generate superheated steam at all.

Today i load my infitech 2 save, and after about ten seconds my large heat exchanger explode. I think when i loading some ticks missed and heat exchanger not work for some time, but fluid regulator fill input hatch for more than 1 bucket of lava. After it exchanger start work and generate portion superheated steam, it struck in turbine input hatch and block steam-distilated water cycle, after few seconds distilated water gone and exchanger blow up.

Everything works fine few hours before i exit my world.

**Comment by Usernm0** [comment]
I rebuild my setup a little and make few tests. Every time i enter my world LHE try to make portion of superheated steam.

I find 2 workarounds. First - put stack empty cells in lava input hatch. Every time i enter world one cell filled with lava. Regulator input only 10 mb\tick and in normal time i haven't more than 200 mb lava in input hatch. But i can't automate input-output cells in lava input hatch, because regulator on it. 
http://i.imgur.com/g0rWEaF.png

Second workaround - use ender io ender fluid conduits, because it can teleport multiple fluid and not block by any of them. But it not works in pure gregtech modpacks. Every time i enter world i get portion of superheated steam before system start work properly.
http://i.imgur.com/mgBCCSl.png

**Comment by Nex4rius** [comment]
You could just use the Fluid Filter and then void the superheated steam thats being produced at the start.
<img src="http://imgur.com/Kg6p0Pl.jpg">

**Comment by Usernm0** [comment]
Because i don't know about it. It's good third workaround, but not solve initial problem - input hatch fills when LHE not work.

**Comment by Blood-Asp** [comment]
the easy way i did before, but likely incomplete, is that wrong types of steam get simply voided by the steam turbines. HP turbines do that with normal steam. That way the systems get not stuck.

But the explosion of the LHE certainly does not come from this. if there is no way to output for GT multiblocks, they will simply void it. Maybe something with building the LHE over chunkborders and it not finding its water supply.

**Comment by Usernm0** [comment]
It's good, if normal turbine void superheated steam. 

About explosion, I know why it happened. In normal cycle we not need add additional distilled water, but when turbine stuck, it not convert steam back to water and cycle broke. And it's ok.

**Comment by ghost** [comment]
There is a simple solution for this.
A fluid regulator cover on the last segment of pipe prior to entering the bottom Input Hatch.

LHE's process up to 8000L of hot fluid per second.
If an LHE processes 50% of its processing capacity (4000L) or more, superheated steam is produced.

Regulate your fluid input to a maximum of 190/t (3800/s) and you will ALWAYS have steam.

no need for fluid filter, no need for all of that other crazy nonsense.
design your delivery system properly.

**Comment by Usernm0** [comment]
You not understand what we talking about. Again, problem is working fluid regulator on LHE input hatch, and not working LHE itself on first ticks when game loading. Any solution without check input hatch tank before send another portion of fluid not work in this environment. Fluid regulator on pipe do same thing as fluid regulator on input hatch. It not check tank, just limit throughput. And limit works fine all time, except loading.
