### ISSUE TITLE
Nuclear Reactor + GT Transformer

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#791]
GT Transformers can receive energy from Nuclear Reactor Block itself, but can't from Reactor Chambers.

**Comment by codewarrior0** [comment]
What about Reactor Chamber -> IC2 Transformer -> GT Transformer?

**Comment by Techlone** [comment]
Works but we want remove IC transformer from this chain.

**Comment by leagris** [comment]
I use:
Reactor Chambre
MFSU
GT EV Transformer

**Comment by codewarrior0** [comment]
Can't really do anything about it from GT's side. IC2 energynet is schizophrenic, not all machines act the same way for input/output of energy. Same thing happens if you try to power IC2 machines using RF via Immersive Engineering cables. Some machines can be powered directly, but others can only get power through a transformer.

**Comment by draknyte1** [comment]
Leagris' suggestion is literally what you have to do to turn IC2->GT EU.. It's 100% foolproof

**Comment by Techlone** [comment]
MFSU or transformer not matter
Maybe you are right... but it looks more beautiful without IC's transformer/battery :)

**Comment by draknyte1** [comment]
Well, that's not how it works. 
Many things would look nice in this world, but that's not the reality of it.

**Comment by Blood-Asp** [comment]
GT Transformers can only accept IC2 EU with pull mechanic. The Reactor does not implement the nessary API for that, so it does not work. A few more of the new machines added in IC2Experimental also have strange APIs implemented. To force compatibility of these few special cases would need many internal changes in GT and absolutly needs to break compatibility with older savegames. So this will stay as it is.
