### ISSUE TITLE
Deuterium and Chlorine not enter in machines

### ISSUE THREAD

**Issue by ApokalypseStudios** [Blood-Asp/GT5-Unofficial#792]
I tested in my own modpack and looks like Mekanism is interfering with the Deuterium and the Chlorine.
I can't insert Chlorine into my chemical reactor for making titanium tetrachloride and I can´t insert Deuterium into my Centrifuge for making Tritium.
I have also comunicated this bug to the Mekanism author.
I'm using the last version of gregtech for 1.7.10.

(Sorry if my english is not good, it's not my own language)

**Comment by Blood-Asp** [comment]
Did you add Mekanism later on in an already existing world? If you did that, the bug is the same as https://github.com/Blood-Asp/GT5-Unofficial/issues/577
