### ISSUE TITLE
Crash whis new ic2 2.6.128

### ISSUE THREAD

**Issue by Ktor-usm** [Blood-Asp/GT5-Unofficial#793]
UC	IC2{2.6.128-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.128-ex110.jar) 
UE	gregtech{MC1.10.2} [GregTech] (gregtech-5.10.06.jar) 

Caused by: java.lang.NoClassDefFoundError: ic2/core/item/ItemUpgradeModule$UpgradeType

**Comment by Claycorp** [comment]
Full log: http://pastebin.com/TuGXA8gc
