### ISSUE TITLE
GregTech 5.09.26 & Tinkers Construct 1.8.8 Glue

### ISSUE THREAD

**Issue by volodya7292** [Blood-Asp/GT5-Unofficial#794]
Glue from **G**reg**T**ech will be replaced to Glue from **T**inkers **C**onstruct and I can not use a Glue from **TC** for a Assembling Machine from **GT**.

If I will remove **TC** from my modpack then I can use Glue from **GT** for Assembling Machine.

**Whether there are solutions?**

**Comment by Blood-Asp** [comment]
Did you add Tinkers later on in an already existing world? If you did that, the bug is the same as https://github.com/Blood-Asp/GT5-Unofficial/issues/577

**Comment by volodya7292** [comment]
I did add GregTech 5.09.26 later on in an already existing world

**Comment by Blood-Asp** [comment]
hmm, might result into the same issue. The fix of #577 should also work in this case.

**Comment by motangish** [comment]
What I should do?

**Comment by volodya7292** [comment]
Good, it's work.
