### ISSUE TITLE
Fluid Regulator Cover ignor Shutter Module

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#796]
If put Fluid Regulator Cover (set to pump in) on Input Hatch and Shutter Module to closest side of fluid pipe (connected to it Hatch) then fluid will move from pipe to Input Hatch through Shutter Module no matter with or without redstone signal on Machine Controller Cover.
![fluid 1](https://cloud.githubusercontent.com/assets/14032818/21076267/45e23e78-bf38-11e6-8269-2b059a1ed675.png)
![fluid 2](https://cloud.githubusercontent.com/assets/14032818/21076270/490da6fa-bf38-11e6-921c-2a18b9e9e617.png)

**Comment by codewarrior0** [comment]
Probably a bug with the Fluid Regulator.

I tried the same setup, but replaced the Hatch+Fluid Regulator with an EnderIO Fluid Tank set to Pull from the pipe, and it could not pull the fluid as long as the shutter was closed.
