### ISSUE TITLE
Processing Array stack size over 64

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#80]
Using the Processing Array with 16 Macerators macerating 16 Redstone Ore gives an output stack of 160 items crushed redstone ore

gregtech_1.7.10-5.08.23
Tested on a server with Infitech2 modpack v.3.1.2

**Comment by pyure** [comment]
DS, is the problem that you get a gigantic stack, or are the total numbers also incorrect?  My recollection is that 160 is the correct total number.

**Comment by Blood-Asp** [comment]
160 is the correct number, i just have to split it up once the max stack size is reaced.

**Comment by Blood-Asp** [comment]
fixed in GT 5.08.24
