### ISSUE TITLE
Add an Ender IO integration

### ISSUE THREAD

**Issue by ghost** [Blood-Asp/GT5-Unofficial#804]
Can you add Ender IO integration because this mod is very interesting thanks for his conduits. BUT, recipes in this mod, are very cheap and uninteresting. Can you ahd an integration which will be complicate recipes and do that Ender IO crafting components will be created in GT machines?

**Comment by Blood-Asp** [comment]
GT does not change recipes besides IC2 and Vanilla. Doing that is just inviting trouble.

That would be the job of Minetweaker. Pretty sure there are already scripts that do that in some modpacks or so.
