### ISSUE TITLE
GT Integration

### ISSUE THREAD

**Issue by ghost** [Blood-Asp/GT5-Unofficial#809]
Can Ender IO pipes work with some specific GT blocks like for exapmle Type Filter? Then please add way to convert EU into RF and transfer RF by GT Cables.

**Comment by JasonMcRay** [comment]
Converting EU to RF and vice versa is already possible. Check OverpoweredStuff.cfg file in GregTech config folder.
EnderIO pipes work but they do ignore set stacksize when force pulling items out. When you power the Filters and let the Filter to output the items (not force pull them out) the stacksize control works

**Comment by ghost** [comment]
Ok, next question. Can you mutate crops to grow plants from Harvestcraft?

**Comment by ghost** [comment]
And what do you think about create update for crops(add a new plants, add an integration, ...)?

**Comment by Dragon2488** [comment]
Mod compatibility isn't our issue, espicially when compat is needed on the opposite side. And we won't change earlygame mechanics because GT5U is continuation of official GT5.

**Comment by ghost** [comment]
Ок, but GT5(not GT5U) died? Mod creator create GT6.

**Comment by Dragon2488** [comment]
And?

**Comment by ghost** [comment]
> Mod compatibility isn't our issue, espicially when compat is needed on the opposite side. And we won't change earlygame mechanics because GT5U is continuation of official GT5.

How I must write an issue if GT5 is closed&

**Comment by Blood-Asp** [comment]
GT does add a lot of stuff to other mods, but it will not remove to change anything of them(besides vanilla and IC2) because that is inviting trouble.

So, what exactly do you mean with Harvestcraft?
