### ISSUE TITLE
[1.10.2] Steam boilers do not work

### ISSUE THREAD

**Issue by Tupas1** [Blood-Asp/GT5-Unofficial#813]
Steam boilers do not produce any steam. Sometimes heat level will also not increase even though coal is present.

**Comment by Dragon2488** [comment]
No. They works perfectly.
![](http://i.imgur.com/yB52rez.png)

**Comment by Tupas1** [comment]
That certainly is not the situation that I am getting in my game:
![](http://i.imgur.com/LNg9l1V.png)
This is what happens if I let it heat up and then add water. The boiler does  not explode, but no steam is produced. If I add any amount of water before adding the coal, the temperature will be rising while the first piece of coal burns, after which it will begin to decrease and no more coal will be consumed, but still no steam. Am I doing something wrong? These are the other mods currently installed:

- CodeChickenLib-1.10.2-2.5.0.178-universal

- industrialcraft-2-2.6.134-ex110

- jei_1.10.2-3.13.6.392

- forge1.10.2-12.18.3.2185

**Comment by Dragon2488** [comment]
Try latest version.

**Comment by Tupas1** [comment]
If by latest version you mean the version 24, then I already did try it, and still had this issue.

**Comment by JasonMcRay** [comment]
I am having same/similiar issue.

1) Filled Coal Boiler full with water
2) Put stack of coal in
3) it used a coal and temeprature started to raise
4) after few seconds, the temperature started to drop down and no more Coal has been consumed
5) No steam produced as well

**Comment by Dragon2488** [comment]
Fixed.
