### ISSUE TITLE
[1.10.2 - 5.10.24] Credit recipes broken

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#817]
Recipe for Industrial Copper and Silver Credit are broken.

They are crafted with Iron Shafts from IC2 instead of Industrial Credits.

![2016-12-25_16 23 10](https://cloud.githubusercontent.com/assets/4236895/21471819/8906fda0-cabf-11e6-8e77-f57060dd5065.png)
![2016-12-25_16 23 13](https://cloud.githubusercontent.com/assets/4236895/21471823/93b7d5da-cabf-11e6-8c2e-e634e5fa8772.png)

Also Industrial Credits themselves are not craftable, because they are crafted in Metal Former which is machine that should get disabled with GT installed (currently does not get removed, but I suspect its by mistake)

**Comment by Dragon2488** [comment]
Seems like IC2 broke credit recipes itself.

**Comment by JasonMcRay** [comment]
GregTech is adding the credits. I do not think IC2 has anything to do with it. IC2 credit (the only one they have - (ic:crafting:38) has a correct recipe in Metal Former. And its the only recipe.

But the GregTech "upgrades" of the IC2 credit is I would say handled on GT side.

**Comment by Dragon2488** [comment]
I don't know what does it, but it isn't gregtech itself.

**Comment by JasonMcRay** [comment]
I am not a modder, so sorry if I am mistaken but:
https://github.com/Blood-Asp/GT5-Unofficial/blob/1.10.2/src/main/java/gregtech/common/GT_Proxy.java#L353

This seems to me wrong. It seems to me, that the IC2 credit is being set as Iron Shaft...
Shouldn't it be
`ItemList.Credit_Iron.set(GT_ModHandler.getIC2Item(ItemName.crafting, CraftingItemType.coin, 1));` ?
