### ISSUE TITLE
[1.10.2 - 5.10.24] IC2 machines not removed

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#818]
Some IC2 machines are not getting disabled with GT installed.

here is a list of them:

Blast Furnace, Block Cutting Machine, Centrifuge, Compressor, Electric Furnace, Extractor, Induction Furnace, Macerator, Mass Fabricator, Metal Former, Ore Washing Plant, Recycler, Replicator, Solar Panel, Water Mill, Wind Mill

All of these were disabled in 5.09 by default.

**Comment by Dragon2488** [comment]
Fixed.
