### ISSUE TITLE
Charged Certus Quartz

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#82]
There should be possible unification for charged certus quartz.
When i smelt GT Charged Certus Quartz ore i get GT Charged Certus.)
But when I use Electrolyzer to charge GT Certus Quartz I get AE2 Charged Certus Quartz.

**Comment by Blood-Asp** [comment]
Testing in DevEnv.
ChargedCertus has no special oredict, so there is nothing to unificate. Also Electrolyzer produces the correct AE2 Charged Quartz and there is no smelting recipe for Charged Certus.

**Comment by Blood-Asp** [comment]
Is there still something i can do, or is this a modpack specific issue?

**Comment by JasonMcRay** [comment]
Problem is:
When I smelt GT Charged Certus Quartz Ore i get GT Charged Certus Quartz.
But when I put GT Certus Quartz (not charged) into Electrolyzer i get AE2 Charged Certus Quartz.

i made sure that none of Minetweaker scripts are messing with this.

**Comment by Blood-Asp** [comment]
I'm currently thinking, i should remove charged certus from GT completely. It just breaks everything as AE2 does not have it as ore dict tag itself...

**Comment by JasonMcRay** [comment]
When GT installed it has craftingQuartz and quartzCertus (same as normal Certus Quartz)

**Comment by Blood-Asp** [comment]
but GT has chargedCertusQuartz as tag and generates all stuff about it. The electrolyzer recipe for charged certus does not work with oredict but with the AE2 item directly. The current way is just broken.

By the way, how do you get GT Charged Certus Ore? It should not be in world gen and because of the missing oredict tag there is also no unification.

**Comment by JasonMcRay** [comment]
Spawned in. Did not realized that they do not spawn.

**Comment by Blood-Asp** [comment]
Removed all of charged certus quartz from GT. The more of it i found, the more broken it was.
