### ISSUE TITLE
Multiblocks Missing Byproducts

### ISSUE THREAD

**Issue by Antifluxfield** [Blood-Asp/GT5-Unofficial#825]
During the process of some of the multiblock machines, if you exit and reenter the game, they will lose the byproducts of the interrupted process. For example, the processing array centrifuging ore dusts will lose those tiny dusts, and the distillation tower handling raw oil will only produce heavy oil, missing all other products.

**Comment by Techlone** [comment]
@Blood-Asp @Muramasa- 
`getAmountOfOutputs` returns wrong value when loading NBT
See [here](https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java#L149) and [here](https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_ProcessingArray.java#L316)

**Comment by KpoxaPy** [comment]
I suggest to write amount of outputs (liquid and item) into NBT instead of taking it from code. In current code almost in every multiblock getAmountOfOutputs returns 0, so server stop/start breaking processed recipes.
