### ISSUE TITLE
Using of ClientSide function

### ISSUE THREAD

**Issue by tyra314** [Blood-Asp/GT5-Unofficial#834]
https://github.com/Blood-Asp/GT5-Unofficial/commit/c51dc7a38323776472ef2bb6e7e6723d90982ab0#diff-871db88402d1fdccda53b81aefc881fdR107

World::getProviderName() is a client side only function.

This slipped in, in a recent commit to the 1.10.2 branch.

**Comment by tyra314** [comment]
Why are you closing this?

It's an issue, because it gets called on dedicated servers.

See https://gist.github.com/tyra314/7ecc1b2e75841956084650b54450c140

**Comment by Dragon2488** [comment]
Because it's fixed.
