### ISSUE TITLE
[1.10.2 - 5.10.30] World Generation Crash from GregTech

### ISSUE THREAD

**Issue by DoughnutDev** [Blood-Asp/GT5-Unofficial#835]
http://pastebin.com/i6548aKC

**Comment by Dragon2488** [comment]
I'm not sure exactly what causes it, but full log would help.

**Comment by mura3277** [comment]
@Dragon2488 Looks like the same issue as with #834

**Comment by Dragon2488** [comment]
Ah, then fixed.
