### ISSUE TITLE
Certus Quartz Block recipe

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#84]
Normaly Certus Quartz Block is made with either 4 Certus Quartz or 8 Pure Certus Quartz. Currently the compressor recipe is 9 Pure Certus Quartz => Block. Should be readjusted to 8.

Similiar goes with Nether Quartz and Pure Nether Quartz. Pure nether quartz is oredicted for the compressor recipe, this should be fixed and it split into it's own recipe of 8 pure quartz to a block. Also the shaped crafting recipe for it removed.

**Comment by Blood-Asp** [comment]
With only GT5 and AppEng installed, i only have 4 Certus Quartz into 1 Block, so the valit recipe. Is the Pure Certus into block maybe a Minetweaker recipe?

**Comment by JasonMcRay** [comment]
Sorry. i was trying to find the script for it in MT and wasnt able. But second look, it is indeed MT recipe. Sorry about that.

Well you might now see it as suggestion maybe :)

**Comment by JasonMcRay** [comment]
Actually. Ok you are right with the Certus and Fluix into 1 Block. But the Nether Quartz and Pure NetherQuartz still should be split in compressor.

**Comment by Blood-Asp** [comment]
Pure Nether/Certus/Fluix Quartz now have compression recipes.
