### ISSUE TITLE
Fluid filter works for input only

### ISSUE THREAD

**Issue by Techlone** [Blood-Asp/GT5-Unofficial#840]
I set up the fluid filter by water. Then attached right pipe (first screen) and poured into it some water (second screen). After few seconds all water volume is in left pipe (third screen).
![image](https://cloud.githubusercontent.com/assets/17011260/21652325/0f6475c4-d2ce-11e6-967a-25e0c7172800.png)
![image](https://cloud.githubusercontent.com/assets/17011260/21652332/16dae0ae-d2ce-11e6-8433-5333f8234bab.png)
![image](https://cloud.githubusercontent.com/assets/17011260/21652337/1c6dd1d4-d2ce-11e6-8d65-d41ce223b8b2.png)

**Comment by Blood-Asp** [comment]
FluidFilter now has multiple modes with different behaviors that can be set with the screwdriver: https://github.com/Blood-Asp/GT5-Unofficial/commit/244d54edfda94662c1c2e39c9ce184ba3d168947#diff-e8a8b3638622ed2af49d176051ff5bdb
