### ISSUE TITLE
How detect first slot

### ISSUE THREAD

**Issue by dalekin** [Blood-Asp/GT5-Unofficial#843]
Item Detector don't detect the 0 slot in chest buffer. At all settings.
It don't detect the 0 slot in other gregtech's machines also.

**Comment by Blood-Asp** [comment]
slot 0 is in the most cases not the first slot in the machines. depending on how the slots are arranged overall it is beween 0-5. So you have to try them all first.

**Comment by dalekin** [comment]
![slot0](https://cloud.githubusercontent.com/assets/22941859/21743290/1e7bebb6-d510-11e6-9279-416a8b2b52db.jpg)
![slot1](https://cloud.githubusercontent.com/assets/22941859/21743293/2558596a-d510-11e6-9510-e3e720832f04.jpg)
Place Item Cover on Chest Buffer. Power 1 is only with second slot.
