### ISSUE TITLE
fusion reactor

### ISSUE THREAD

**Issue by natzgzul89** [Blood-Asp/GT5-Unofficial#844]
if you run "fusion reactor" in the helium plasma production, submit americium and naquadria, the reactor after finishing work on helium plasma will begin to produce neutrons, regardless of what the reactor

**Comment by Blood-Asp** [comment]
In case it is what i think: Switching beween fusion materials without needing the startup energy again when not turning off.
Then it is intended secret behavior. 
In case it is something else, i will reopen this.

**Comment by natzgzul89** [comment]
yes, it does not take into account energy. but production neutronium in MK1 is not good.

**Comment by Blood-Asp** [comment]
oh, that second point is really something to fix.

**Comment by codewarrior0** [comment]
It's because the starting energy is what's used to check the reactor tier, right? And if it skips the starting energy, then it also skips the tier check?

**Comment by Blood-Asp** [comment]
Jep, likely something like that.
