### ISSUE TITLE
Advanced Miner II & TerraFirmaCraft Ores

### ISSUE THREAD

**Issue by skushnarev** [Blood-Asp/GT5-Unofficial#846]
HI!
AM2 not dig ore from TFC. Can I somehow fix it?
Now they are not producing Miner, Advanced Miner, Advanced Miner II. As scanner does not detect them.
I hope it's not hard to fix!
Thank you in advance!

> Привет!
> AM2 не копает руды из TFC. Можно ли как-то это исправить? 
> Сейчас их не добывает Miner, Advanced Miner, Advanced Miner II. Так же их не обнаруживает Сканер.
> Надеюсь это не сложно исправить!
> Заранее спасибо!

**Comment by Dragon2488** [comment]
Ты не туда обращаешься. Грегтеч определяет руды, зарегестрированные в OreDictionary с префиксом ore. И если TFC не регистрирует свои руды в OreDictionary, то это его собственные проблема, а не Грегтеча или других модов. Ты можешь зарегестрировать руды TFC в OreDictionary с помощью MineTweaker.

**Comment by skushnarev** [comment]
Add to Dictionary ores. Now there is a scanner, Miner and Advanced Miner. But still ignores Advanced Miner II.

> Добавил в словарь руд . Теперь их находит сканер, Miner и Advanced Miner. Но по прежнему игнорирует Advanced Miner II.

**Comment by Dragon2488** [comment]
Какие конкретно ты добавил имена? На какой версии грегтеча?

**Comment by skushnarev** [comment]
Forge 10.13.4.1614
GregTech-5.09.27
TerraFirmaCraft-0.79.29.922
MineTweaker3-1.7.10-3.0.10
ModTweaker2-0.9.6

Скрипт, тест на одной руде:
// Ore
val OreORE = <ore:oreIron>;
OreORE.add(<terrafirmacraft:Ore1:11>);

https://pp.vk.me/c638416/v638416555/1a312/Lmig_8oSqS4.jpg

Сборка (без тестового скрипта):
https://github.com/skushnarev/Minecraft-TFC-GT

**Comment by skushnarev** [comment]
Может изменить статус заявки, кто то другой думаю в силах помочь.

**Comment by Dragon2488** [comment]
Почему ты измеряешь сканером и рассчитываешь, что оно заработает? Нет, сканеру абсолютно пофиг на имена в оре дикшенори. Однако Advanced Miner II зареганных в оре дикшионари руды копать будет.

**Comment by skushnarev** [comment]
Я не думаю, я знаю, ибо проверил, что хотелось бы и от вас. До момента внесения руды в словарь её сканер и майнеры не видели. Как писал выше, после добавление всё заработало кроме AM2. 

Не надо верить на слово, возьмите и поставьте TFC и проверьте с добавлением руд в словарь. Мне кажется так и должны поступать ответственные люди.
