### ISSUE TITLE
Coolant Cell and Uranium Cell recipes in Canning Machine

### ISSUE THREAD

**Issue by ghost** [Blood-Asp/GT5-Unofficial#848]
Add please this recipe because if you must craft IC2's machines or components for something this is normal, but when you craft armor from Gravisuite or craft Nuclear Reactor, you need a lot of coolant cells and uranium cells.

**Comment by Pilad** [comment]
Coolant cells and uranium cells have craft in gt mechanism.

**Comment by ghost** [comment]
Thanks, maybe I have outdated version.
