### ISSUE TITLE
Regulator + Storage Bus

### ISSUE THREAD

**Issue by ghost** [Blood-Asp/GT5-Unofficial#849]
Can Storage Bus from AE2 show ME-Network items from Regulator and input items in it?

**Comment by Pilad** [comment]
Шина хранения не станет ложить текущие предметы в регулятор, а только новые. Да и то, если приоритет на шине поставишь выше,чем у дисков хранения.

**Comment by ghost** [comment]
Я хочу сделать систему автоматизации ядерного реактора на основе регулятора и отдельных МЕ-сетей. Под каждый реактор я выделю свою сеть, которая будет проверять при помощи шины хранения и предметного уровня сигнала(не знаю точно как её на русском) количество нужных стержней(к примеру) в регуляторе. Если их в сети не хватает, то скорее всего(еще не продумал систему) буду в сеть подавать ингредиенты из другой сети(основной) посредством подключения к МЕ-интерфейсу основной сети, шины хранения. Дальше редстоун сигнал(если стержней меньше нужного количества) подается на шину импорта, а она подключена к МЕ-интерфейсу с вложенным в него рецептом стержней.

**Comment by ghost** [comment]
Я подумал и решил что более стабильна будет такая версия. От интерфейса основной сети в котором вложена карта создания(апгрейд) и рецепты скажем двойного и четверного стержня, которых при помощи карты создания поддерживается 4 и 2. Дальше к интерфейсу подходят 2 шины импорта(доп. сети), для двойного и четверного стержня. Они работают от редстоун сигнала(если в доп. сети меньше 4 двойных и 2 четверных стержней). Дальше к регулятору подключена шина хранения с более высоки приоритетом чем у МЕ-Сундука( он нужен просто что бы сформировать сеть). Таким в системе отображаются 4 и 2 стержня в регуляторе и как только какой то из стержней в реакторе заканчивается, регулятор засовывает их в реактор, количество стержней в его инвентаре уменьшается, это детектится сетью, подается сигнал на загрузку определенных стержней.

**Comment by Dragon2488** [comment]
Я не понял, чего вы тут хотите? Поддержку сторадж баса?

**Comment by ghost** [comment]
В смысле? Я так понял поддержка есть и на основе этого просто предложил вариант автоматизации реактора.

**Comment by Pilad** [comment]
Основная сеть пусть крафтит стержни и ложит в сундук через свой сторадж баз и поддерживает их там. Остальные сети со своими сторадж басами должны так же висеть на сундуке.Если понадобились стержни, то они и возьмут с этого сундука стержни и вставят в регуляторы.А те в реакторы соответственно.Приоритет сторадж базам только ставь высокий.Чтоб система не пыталась ложить их на диски.

**Comment by Dragon2488** [comment]
Вы сюда зачем пришли? Иссусы не для обсуждения созданы.

**Comment by ghost** [comment]
Но все таки, имеется ли поддержка шин хранения регуляторами?

**Comment by Pilad** [comment]
I apologize for the Russian message.

**Comment by Dragon2488** [comment]
Иди и проверь. Если нет - создай новый иссус на английском и там конкретно опиши, как это должно работать.

**Comment by ghost** [comment]
Sorry for the use of the russian language.
