### ISSUE TITLE
Random sound of hammerin

### ISSUE THREAD

**Issue by wujekbrezniew** [Blood-Asp/GT5-Unofficial#85]
On newest version of GT5 i gets random sounds (like using hammer, wrench). I hear that everywhere on all my worlds.

**Comment by Blood-Asp** [comment]
Are you really sure GT5 is the reason for that happening? If you updated other mods at the same time, test them also.
A similiar bugreport could narrow down the reason for this to the new Extra Utilities update.

**Comment by wujekbrezniew** [comment]
You must be right because it happens at older version too.

**Comment by Blood-Asp** [comment]
then: closed
