### ISSUE TITLE
Construction Foam

### ISSUE THREAD

**Issue by Kanol** [Blood-Asp/GT5-Unofficial#852]
Industrial craft allows to hide its cables with construction foam and to mask foam with obscurator. So, why don't add this into gregtech? Masking gregtech cables and pipes will be wery useful.

**Comment by Dragon2488** [comment]
Because GT, instead of IC2, allows covers on cables.

**Comment by Kanol** [comment]
But amount of GT covers is limited, and in the same time IC obscurator allowing to mask foam with ANY texture.

**Comment by Blood-Asp** [comment]
not compatible with the way GT is coded

**Comment by natzgzul89** [comment]
and if the opportunity to do to paint the wire using a chameleon?
more precisely toward the wire, or cover

**Comment by PrincessOfEvil** [comment]
Could you at least give us foamcrete covers?

**Comment by Nex4rius** [comment]
I think it's not possible.
https://github.com/Blood-Asp/GT5-Unofficial/issues/228

**Comment by Dragon2488** [comment]
Yes, covers with custom block textures aren't possible, espicially in 5.10.

**Comment by natzgzul89** [comment]
возможно ли сделать такое с помощью сторонних модов? я не про то что они существуют. к примеру фасад специальный сделать, который будет работать с индастриаловским хамелионом.

**Comment by Dragon2488** [comment]
@natzgzul89 We are talking english here.
> Еще раз, ты хочешь заставить грегтечевские кабеля работать с хамелионом через СТОРОННИЙ МОД? Ты сам понимаешь, какой бред сказал?

**Comment by natzgzul89** [comment]
а, ну да. грег же у нас особенный. в мине нет ничего не возможного, есть люди которые забивают на все.

**Comment by Dragon2488** [comment]
@natzgzul89 We are talking english here. (x2)
I won't respond to your future comments on russian, they will be ignored. If you want to talk, go to discord's #russian channel.

> Если бы ты читал обсуждение выше, ты бы понял, что нужно переписать большое количество кода грегтеча, чтобы такое позволить. И это того не стоит. И ты бы вообще молчал о том, кто на что забивает, особенно учитывая, что ты не сделал для грегтеча ровно нихуя.

**Comment by natzgzul89** [comment]
только не психуй. это всего лишь идея. почему бы ее не бросить в список идей. возможно, однажды в далеком будущем это будет возможно.

**Comment by natzgzul89** [comment]
> сделал для грегтеча ровно нихуя.
я дал шанс людям за 40 не знающим буржуйского языка понимать его.

**Comment by Dragon2488** [comment]
Еще раз повторяю, прекрати сюда писать на русском. Если имеется желание пообщаться на русском - иди в дискорд грегтеча, там специально отдельный канал для русских есть. И если бы ты таки читал то, что пишут выше, ты бы не задавал таких глупых вопросов. Подобная идея уже есть - #228, и выше на нее приводили ссылку. И она добавлена в коллекцию идей.

**Comment by natzgzul89** [comment]
ok
