### ISSUE TITLE
Dismount assembly line

### ISSUE THREAD

**Issue by dalekin** [Blood-Asp/GT5-Unofficial#853]
We can dismount any multiblock. However we can not dismount Assembly Line because Reinforced Glass from IC2 cannot be picked up by any tool once it is placed.

**Comment by OvermindDL1** [comment]
I've not tested, but silk touch cannot get it?

Could use Thaumcraft's Wand of Equal Trade or similar things in other mods if you have them too.

**Comment by Blood-Asp** [comment]
Silktouch or simillar harvesting should work. On the other side: Why does it have to be possible to pick up? At the time the assembly line is build, a few reinforced glass should not be that expensive anymore.

**Comment by dalekin** [comment]
Silktouch and simillar harvesting don't work. It is strange that it was impossible to do own version of the glass. Any machine have to be possible to pick up because it is gregtech. If there is a penalty for each erroneous placement of machine part, which completely destroys the block with the destruction of it spent on materials and time, then it is not the same mod anymore, which had been originally. Yours respectfully.
