### ISSUE TITLE
GT-5.09.27 [MC1.7.10] Coppon comb in Chem reactor failure

### ISSUE THREAD

**Issue by YvanovGrygory** [Blood-Asp/GT5-Unofficial#855]
I'm Trying to use NEI recipe of Coppon comb and copper crushed ore processing in chem reactor (with water), but nothing happend!
Recipe:
![1](https://cloud.githubusercontent.com/assets/9947102/21761583/0d96bcf8-d665-11e6-9976-36c583ebe358.JPG)

Realization:
![2](https://cloud.githubusercontent.com/assets/9947102/21761588/12e8d826-d665-11e6-9e82-56731cbdffae.JPG)

**Comment by mura3277** [comment]
Seems to be working fine for me in .27

**Comment by Blood-Asp** [comment]
also tested and got it working... do you have issues with only that recipe or also others? Also, do at last some recipes work in that chem reactor, to be sure there is no machine issue?

**Comment by YvanovGrygory** [comment]
i found a solution: in config file change parameter "nerf combs"
