### ISSUE TITLE
Diesel engine

### ISSUE THREAD

**Issue by kokochicken** [Blood-Asp/GT5-Unofficial#860]
Diesel engine says it "increases efficiency" when adding oxygen. It uses 2.5x the fuel and produces the same eu/t

**Comment by DEMOOH** [comment]
![image](https://cloud.githubusercontent.com/assets/16781357/22020008/0b94cdce-dcc7-11e6-8de9-a85799f19888.png)

**Comment by Blood-Asp** [comment]
As shown above, EU/t rises 3x while fuel usage rises 2.5x. Is your dynamo hatch upgraded correctly?
