### ISSUE TITLE
Very simple recipe of adv curcuit chips

### ISSUE THREAD

**Issue by Techlone** [Blood-Asp/GT5-Unofficial#861]
I suggest a new recipe of an adv chip
![image](https://cloud.githubusercontent.com/assets/17011260/22086338/236e9d7e-ddfa-11e6-88cc-241fa5e4097a.png)
The luquid is molten glowstone 144L (one dust)
let's discuss

**Comment by ShefardPT** [comment]
Like this! In my opinion adv circuits are too easy to produce now, so HV machines and 8v solars are easy to produce too. This recipe make this things balanced

**Comment by leagris** [comment]
Or use silicon plate and fluid epoxy...
On a more serious note, recipes are tedious enough. Focus on gameplay with actual features and content,  rather than increase grinding for recipes. And if you really want custom recipes for a modpack, use Tweaker scripts.

**Comment by Techlone** [comment]
>use Tweaker scripts

already but i think this recipe shoul be native

**Comment by codewarrior0** [comment]
I'd rather not. Adding two NAND chips barely changes the material cost. You'll still be able to make as many HV machines as you like. And even then, you won't be slamming out HV machines by the dozen until you're well into the late game, at which point those materials are basically irrelevant.

**Comment by Techlone** [comment]
The main reason of this recipe is solar panel 8v

**Comment by Blood-Asp** [comment]
the new solar recipes will get a bit more expensive next update anyways.
The circuit recipes will also get many changes.

**Comment by SapientMC** [comment]
@Blood-Asp can we help you somehow to get it sooner?

**Comment by Blood-Asp** [comment]
Remind me not to be so lazy. :D

**Comment by SapientMC** [comment]
I mean real help. We have at least three java coders in our community and can make some PR if you tell about your plan :)

**Comment by Blood-Asp** [comment]
In that case it would be the best if others were to help with bug reports and testing, so i can focus on adding features.

**Comment by draknyte1** [comment]
Solars are disabled by default anyway aren't they?..

**Comment by Techlone** [comment]
>Solars are disabled by default

Is it the reason don't balance solars or theirs ingredients?

**Comment by draknyte1** [comment]
Solar power is considered OP by Greg. 
So it's disabled by default.

**Comment by DEMOOH** [comment]
Before recent changes only basic solar panels were available. Now you can craft 8 and 32 ones too. As someone mentioned, they are quite cheap, but need a decent tech level to produce.
