### ISSUE TITLE
missing achievement name and description for osmium

### ISSUE THREAD

**Issue by willis936** [Blood-Asp/GT5-Unofficial#862]

**Comment by Blood-Asp** [comment]
does show correctly for me. maybe some localization issue? or old world and the achievements of GT changed? What exactly is shown? What version of GT?

**Comment by willis936** [comment]
I think I incorrectly stated the problem.  Both the title and description of the achievement aren't displayed in the menu.  I'm playing in english.

I'm on GT 5.09.27.

![2017-02-03_17 25 56](https://cloud.githubusercontent.com/assets/13720625/22610937/f5b3130e-ea35-11e6-9d27-fa56076802df.png)

![image](https://cloud.githubusercontent.com/assets/13720625/22611224/6a42eec8-ea37-11e6-90c2-9fbc54a54f52.png)

**Comment by Blood-Asp** [comment]
That means you added Osmium to your worldgen. The Achievements for ores must be added to the vanilla language manager and that is currently hardcoded and does not adapt to config changes. Making this dynamic is on the todo list, so this is issue redundant.
