### ISSUE TITLE
Did I have any way to change NBT in GT ores

### ISSUE THREAD

**Issue by ghost** [Blood-Asp/GT5-Unofficial#865]
I'm doing now modpack with TFC and GT. TFC have his own methods to spawn ore from other mods, _but only if NBT of this ores a lower than 15_. Did I have any way to change NBT in GT ores

**Comment by Dragon2488** [comment]
NBT is internal tag of tile entity or item stack. 0-15 value is Metadata. So no, you cannot change NBT of GT ores.

**Comment by draknyte1** [comment]
It's been long established that TFC cannot spawn GT ores, most mods can't because they don't know how to handle them.

If you're using TFC, enable GT small ores, so you're not having huge veins.

**Comment by Blood-Asp** [comment]
Well, making an compatibility mod beween GT and TFC and coding special functions for that would be possible. But using default functions it is not possible. I did write with the TFC coders a bit in the past, but not much came from it.
