### ISSUE TITLE
ore generation issue

### ISSUE THREAD

**Issue by secirpac** [Blood-Asp/GT5-Unofficial#867]
gregtech version 5.09.27 with BoP 2.1.0.1889 and RWG 1.3.2.using the original config.
ores generate in the nether wrongly. 
For example,sulfur doesn't generate in the nether,when beryllium and diamond generate in the nether.

: (

**Comment by MauveCloud** [comment]
This seems to mostly duplicate #726.

**Comment by Blood-Asp** [comment]
right, duplicate
