### ISSUE TITLE
Minetweaker parsing does not enable items recursively

### ISSUE THREAD

**Issue by repo-alt** [Blood-Asp/GT5-Unofficial#868]
E.g. if I have a recipe using vanadium steel rotor - only rotor itself will be enabled by the script parser, but not the ring used in it's crafting.

Script sample:
recipes.addShaped(<IC2:itemArmorJetpackElectric:27>, [
[<gregtech:gt.metaitem.02:24371>, <gregtech:gt.metaitem.01:32702>, <gregtech:gt.metaitem.02:24371>],
[<gregtech:gt.metaitem.01:32611>, <IC2:itemArmorBatpack:*>, <gregtech:gt.metaitem.01:32611>],
[<gregtech:gt.metaitem.02:21371>, <ore:wireGt04AnnealedCopper>, <gregtech:gt.metaitem.02:21371>]]);

**Comment by Dragon2488** [comment]
I don't think gt really needs this feature.

**Comment by Blood-Asp** [comment]
The script parser actually does this already. Just the ring for the rotor was forgotten.

**Comment by draknyte1** [comment]
How about you let the parser enable materials that are requested by scripts?
It's useless otherwise when most materials are off by default.

**Comment by Blood-Asp** [comment]
materials need to get an ID set or the parser finds an material ID in the MC scripts that is not used. not possible to do that automaticly. the log does list material errors trough.

**Comment by draknyte1** [comment]
*sigh*
Another thing on my 'fix' list then. 
I've found > 100 recipes since changing to .09.27 that have missing items because all the materials don't exist.. Too hard to find and reenable them all by hand.
