### ISSUE TITLE
Processing Array not working

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#87]
The Processing Array does not work with recipes were one item does not get consumed (plate bender with integrated circuit / extruder with extruder shape / precision laser engraver with lens)

gregtech_1.7.10-5.08.23
Tested on a server with Infitech2 modpack v.3.1.2

**Comment by Blood-Asp** [comment]
I did not expect anyone to mass produce anything produced by this machines so much that a processing array makes sense. 
Currently these machines are completely unsupportet. Not sure if i will change that.

**Comment by DarknessShadow** [comment]
Well mass producing plates would be nice sometimes :)

**Comment by Blood-Asp** [comment]
extruder does now work.
