### ISSUE TITLE
[1.10]broken harvest level

### ISSUE THREAD

**Issue by mightydanp** [Blood-Asp/GT5-Unofficial#871]
i started to work on my modpack and i found out that for some reason when i changed the harvest level and reload the game with a new world the ore still has its default mining level
I:HarvestLevel_1=2
its mining level stays at one and i can even mine it with a mining level 1 pickaxe

**Comment by Blood-Asp** [comment]
Not sure if that was changed in 1.10.2, but in 1.7.10 the mining level of ores is set on worldgen, so changing it later will not change the mininglevel of already generated ores.

**Comment by mightydanp** [comment]
No its in 1.10.2 and i have created a new world after i changed the mining level , but it does not change the mining level. It stays its defaul level even after i create a new world

**Comment by mightydanp** [comment]
.... :/
