### ISSUE TITLE
Crash with IC2(new API change?) (5.10.34 + build 144/155/161)

### ISSUE THREAD

**Issue by Rongmario** [Blood-Asp/GT5-Unofficial#873]
https://hastebin.com/yiluxohuqe.sql

**Comment by Rongmario** [comment]
IC2's build 145/155/161 all crash on same error.

**Comment by Chocohead** [comment]
The last version of IC2 that will work is 2.6.142, once crops were ported the old Ic2Items was removed (after being deprecated since the initial 1.8 port).

**Comment by 3TUSK** [comment]
@Rongmario If you don't mind, you can try [this fork](https://github.com/3TUSK/GT5-Unofficial/tree/ic2-2.6.151%2B). I have created a personal pack with this custom build.

**Comment by leagris** [comment]
@3TUSK You could also PR Here :)

**Comment by Rongmario** [comment]
Will check out thanks 3TUSK, I'll remain this open.

**Comment by 3TUSK** [comment]
@leagris #876
