### ISSUE TITLE
Battery Buffer

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#88]
I cannot put batteries into a battery buffer or pull them out automaticly.
I've tested it with:
Conveyor Module
Robot Arm
High Voltage Chest Buffer
Hopper
Item Conduit (enderio)
Storage Bus / Input Bus / Export Bus (ae2)
Basic Logistics Pipe / ItemSinkModule (logisticspipe)

gregtech_1.7.10-5.08.23
Tested on a server with Infitech2 modpack v.3.1.2

**Comment by Blood-Asp** [comment]
Intended behavior, so there is no way for lossless energy transfer.
