### ISSUE TITLE
"machine controller" "shutter module" Combo

### ISSUE THREAD

**Issue by Punchuppercut** [Blood-Asp/GT5-Unofficial#888]
Machine controller, Shutter module combo for use as a control valve not working with fluid pipes

**Comment by DEMOOH** [comment]
I am pretty sure that this combo works.
P.S. It's not the first time when someone creates tickets without any proofs. I might be wrong accusing you but you must be the one that creates screenshots and shows mechanics knowledge to exclude as much reasons as possible.
If you need some help then just ask in the Gregtech discord channel. GitHub issues is the last thing you want to use if you are not completely sure that it's worth creating another issue.

**Comment by xarses** [comment]
It works on my builds all over my base. Keep in mind, that the default configuration requires a HIGH signal (lever on) to close the shutter. And that you can visually see this on large and smaller pipes.

Please provide:
* steps you took to produce your issue (screen shots are helpful)
* the versions you have of IC2, and GT5, and forge

**Comment by Blood-Asp** [comment]
works for me and no more info -> close
