### ISSUE TITLE
Broken automation on recipes in Steam machines

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#891]
In InfiTech 2 we have a recipe for ore clusters (from Thaumcraft) that can be processed in Macerators. Problem is Steam Macerators will not accept the ore clusters via any form of automation. LV Macerator works fine in automation regard.

IIf put the cluster manually into Steam Macerator, it will start it processing just fine.

This issue is not only for Clusters. Noticed it also for Cobble > Sand in Steam Macerator. Cobble > Sand when putting the cobble manually in works fine.

GT: 5.09.27

**Comment by Blood-Asp** [comment]
Does nothing work, or just certain stuff not?

**Comment by JasonMcRay** [comment]
Only certain things. For example I can insert via automation Furnaces into steam macerator just fine.
