### ISSUE TITLE
Item Pipe Routing frequently ignores adjusted distance

### ISSUE THREAD

**Issue by GusSmedstad** [Blood-Asp/GT5-Unofficial#896]
I have an ore processing facility that uses a single item pipe as a general bus. Because it's a general bus, it has a variety of branches, rather than being linear.

The Thermal Centrifuge outputs all centrifuged ores to a universal macerator, and anything else to the general bus. The Universal Macerator outputs everything to the general bus.

There's an item filter accepting certain specific dusts for immediate smelting. Smelting ingots go to general bus. Tiny dusts, small dusts, and nuggets get accepted at various type filters.

There are item type filters pushing various ingots and dusts to specific chests. At one terminus of the bus is a simple chest filter, which acts as a handler for anything not specifically filtered out. There are two Restrictive Item Pipes between the final "overflow" chest and the rest of the bus. Originally I had only one, but I inserted a second one when I first became aware there was a problem. Adding the second restrictive pipe didn't help.

I have a large load of Yellow Limonite processing right now. Yellow Limonite dust is filtered for immediate smelting. Sometimes when I start a session, all the limonite is smelted. Other times, all of it goes to the overflow chest and ignores the type filter connected to the furnace.

It's erratic and unpredictable which behavior I'll see. Sometimes it runs one way, sometimes the other. Type / inverted type filters work reliably for most other things, but are impossible for the overflow chest - there are far more than 9 types of dusts that should not go into the overflow chest, and a positive filter is not a solution either, since the point of the overflow chest is to accept unhandled items which would otherwise block the item pipe.

I also sometimes see tiny dusts entering the overflow chest instead of entering the type filter for tiny dusts.

I'm attempting to attach a screenshot, if that's of any help.

![ore processing](https://cloud.githubusercontent.com/assets/24849717/22857210/e6b3f65e-f06e-11e6-883c-ffba191a2171.jpg)

**Comment by Blood-Asp** [comment]
I can only think of maybe some chunkborder issues. Can't for now think of a way to replicate that correctly. If you can find a way to perfectly repeat it happen i can try to work on it. Otherwise i have no idea where to beginn.
