### ISSUE TITLE
logistics pipe power supplier

### ISSUE THREAD

**Issue by Nex4rius** [Blood-Asp/GT5-Unofficial#897]
The logistics pipe power supplier only works with IC2 machines could you add support for gregtech? (at least with the transformer?)

https://github.com/RS485/LogisticsPipes/issues/732

**Comment by draknyte1** [comment]
Adding gregtech power support is actually a lot of work.. I don't blame the author of any other mod for not supporting it..

**Comment by Dragon2488** [comment]
Use MFE + GT transformer.

**Comment by Blood-Asp** [comment]
The GT power system is incompatible by design and not a bug.
There are two possible ways to take care of this. LP implements the GT power API or always place a IC2 compatible power storage inbeween LP and GT.
