### ISSUE TITLE
Distilation Tower needs Rebalancing for faster processing of everything

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#899]
### Example of issues caused by slowness processing Biomass to Ethanol:

Ethanol is 128000 EU for 1000 L

#### HV Generator (Turbo Diesel Generator):
At HV, 1000L will burn for 250 ticks
At 85% efficiency, it will burn through 1000L of Ethanol in 212 ticks.
Requires: 2 Distillation Towers for 1 Turbo Diesel Generator

#### MV Generator: (Advanced Diesel Generator)
At MV, 1000L will burn for 1000 ticks
At 90% efficiency, it will burn through 1000L of Ethanol in 900 ticks.
Requires: 1 Distillation Tower for 2 Advanced Diesel Generators

#### LV Generator: (Basic Diesel Generator)
At LV, 1000L will burn for 4000 ticks
At 95% efficiency, it will burn through 1000L of Ethanol in 3800 ticks.
Requires: 1 Distillation Tower for 9 Basic Diesel Generators

#### BuildCraft Factory Refinery:
Ouputratio: 1:4 (1L Ethanol from 4L biomass)
Duration: 1 tick/L
Energy Rate: 100 RF/t or 25 EU/t
Energy / Cycle: 25 EU
For 1000L Ethanol, that's 25000EU for 1000ticks from 4000L biomass

#### Forestry Still:
Outputratio: 3:10
Energy Rate: 40RF/t or 10EU/t
Energy / Cycle: 10 EU
Duration: to process 1000L Biomass 20200 RF at 40RF/t = 505 ticks
For 1000L Ethanol, that's 33333.33 EU for 1683.33 ticks from 3333.33 L Biomass

#### Gregtech Distillery:
Outputratio: 12:40
Energy Rate: 24EU/t
Energy / Cycle: 384 EU
Duration: 384EU/24EU/t = 16 ticks for 12L Ethanol
For 1000L Ethanol, that's 32000 EU for 1333ticks from 3333.33 L Biomass

#### Gregtech Distillation Tower:
Outputratio: 60:150
Energy Rate: 64 EU/t
Energy / Cycle: 1600 EU
Duration: 1600EU/64EU/t = 25 ticks for 60L Ethanol
For 1000L Ethanol, that's 26666.67 EU for 416 ticks from 2500 L Biomass

### Suggestion

Re-balance the Distillation Tower recipe for Ethanol to be able to feed 4-8 Turbo Diesel Generators. Means the output rate should be raised × 10 of current, and base EU/t probably be raised to 480 EU/t at HV tier, while maintaining efficiency and total EU cost per processed fluid amount.

**Comment by DEMOOH** [comment]
I think that the recipe should be at least 1000 Eu/t. 4-8 HV Diesel production is very close to nuclear reactors. But I don't really know how much effort needed to maintain such biomass rate.

**Comment by Blood-Asp** [comment]
New Distillation Tower value:
600 Biomass = 240 Ethanol
16 Ticks, 400EU/t. Enough for ~3 HV Diesel Gens, so ~1500EU/t.
Also doubled distilled water speed.
Rised cracked fuel distillation speed slightly to match cracking unit speed exactly.
