### ISSUE TITLE
Packager with schematics

### ISSUE THREAD

**Issue by Zac666** [Blood-Asp/GT5-Unofficial#9]
Problem in packager with schematics like 1x1, 2x2 and 3x3. Recipes work fine(sugar canes -> sugar with schematic 1x1; nuggets and tiny piles for 3x3 and etc), but packager don't accept items for this recipes from hoppers/tubes. (Except: scrap -> scrap box for 3x3)
Same problem with recipes like wires+rubber sheets -> cable. If you put sheets with hands in packager, he start accept wires

**Comment by Dream-Master** [comment]
Try it only from the side. It dont work if you put it from above via Hopper or Pipes in.

**Comment by Zac666** [comment]
http://imgur.com/CF07NpE
http://imgur.com/BCjyVuo
http://imgur.com/pFRffcq
Same with pipe from side. Also "Schematic (Dusts)" works fine.

**Comment by Blood-Asp** [comment]
Found and fixed issue. Will be included next release.
