### ISSUE TITLE
[Maybe bug?] Auto Maintenance Hatch not working

### ISSUE THREAD

**Issue by Azruine** [Blood-Asp/GT5-Unofficial#902]
Using GT 5.09.28 pre3, IC2 exp 2.2.827

1. build multiblock with auto maintenance hatch - not working. No responce from providing energy and input materials.
2. build multiblock with maintenance hatch and replace with auto hatch - not working. 

![2017-02-17_02 24 03](https://cloud.githubusercontent.com/assets/6277538/23032596/47843c62-f4b8-11e6-8e98-30d0a6901a73.png)
![2017-02-17_02 24 08](https://cloud.githubusercontent.com/assets/6277538/23032597/4787a758-f4b8-11e6-9421-47b1134cd613.png)
![2017-02-17_02 24 12](https://cloud.githubusercontent.com/assets/6277538/23032595/4783a482-f4b8-11e6-91ef-98318983fac4.png)

**Comment by Blood-Asp** [comment]
Server or singleplayer? Lubricant in GT cells or IC2 universal cell?

**Comment by Azruine** [comment]
Single payer, lubricant in GT cell.

**Comment by Blood-Asp** [comment]
Just tested with multiple multiblocks and different orders of the needed parts. All worked fine. I only noticed that it is easy to mix up the steel screws with other steel types like dark steel or damascus steel.
I head of some multiplayer issues before, but singleplayer is working fine afaik.

**Comment by Georggi** [comment]
Can confirm this one, happens on both SP and MP, machines do not start with it, you can only make it to work by firstly placing maintenance hatch, fully repairing it and then replacing it with auto maintenance hatch, which would still break later on https://github.com/Blood-Asp/GT5-Unofficial/issues/1053
