### ISSUE TITLE
spelling

### ISSUE THREAD

**Issue by Nex4rius** [Blood-Asp/GT5-Unofficial#903]
<img src="http://i.imgur.com/BPSt89p.png"/>

I think its sulfuric.
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.liquid_sufluriclight_fuel.png
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.liquid_sufluriclight_fuel.png.mcmeta

gregtech-5.09.28pre

edit: I can't find the misspelling in the code but I found another one "Natrural" -> https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/enums/Materials.java#L522

**Comment by Dragon2488** [comment]
Fix of this "missspelling" will break fluids in all worlds.

**Comment by Blood-Asp** [comment]
Right, this in code spelling cant be fixed because it would mess up the savegames.

**Comment by OvermindDL1** [comment]
You could always register the new name as well and make any recipe that take one take both, then as it enters anything you can mess with then 'unify' it to the proper name so storage stays reasonable.
