### ISSUE TITLE
[1.10.2] Crop textures crash

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#906]
http://paste.ubuntu.com/24032382/

This happened even after copying crop textures from a 5.09 jar into the 5.10 jar.

**Comment by Dragon2488** [comment]
Use IC2 .99 version for now

**Comment by MauveCloud** [comment]
Why .99?  According to Chocohead in #873, .142 was the last IC2 build sans crops, so I tried that a few hours ago, and Minecraft launched to menu with that version.  I haven't tried starting a world yet, though.

**Comment by draknyte1** [comment]
That's the latest versions he's built against?..

**Comment by Chocohead** [comment]
http://forum.industrial-craft.net/index.php?page=Thread&postID=206639#post206639 should provide a temporary fix until GT increases it's IC2 build version

**Comment by Chocohead** [comment]
This can be closed now.

**Comment by MauveCloud** [comment]
> This can be closed now.

How do you figure that?  Dragon2488 has yet to put up new binaries that include your fix for this, which is why Pumpkin_233 still needed the shim jar.
