### ISSUE TITLE
[1.10.2] Tool type and harvest level not enforced

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#908]
With GT 5.10.40, I can use a flint shovel to harvest stone, bauxite ore, or even ilmenite ore, all of which should normally require a pickaxe to harvest, and the last of which should require a tier 3 pickaxe such as cobalt or diamond to harvest.

**Comment by xF4m3** [comment]
Also, I'd like to add to that, that I can not break the Bronze Blast furnace or the Heatingcoils of the Electrical Blast Furnace with a wrench. Regardles sof which tool I tried, it takes ages to destroy those. In the end I just went into creative mode and removed them, it was like breaking obsidian by hand :D

**Comment by codewarrior0** [comment]
Some machines seem to have a "wrench harvest level" now. A cobalt wrench breaks them quickly.

**Comment by MauveCloud** [comment]
Note: what inspired me to try mining ores with a flint shovel was noticing that it worked to break ferns/tallgrass, which was different from the 1.7.10 builds.  I don't mind that detail so much, and I wouldn't mind being able to destructively mine blocks with GT tools that are the wrong type or too low-tier (faster than bare hands, but slower than the correct type and tier), but blocks that drop nothing when broken by hand should similarly drop nothing when broken by low-tier or wrong-type GT tools (if minable at all that way)

P.S. as far as the machines xF4m3 mentioned, neither should require a cobalt wrench:
EBF heating coils and bronze plated bricks both get harvest level 2 from https://github.com/Blood-Asp/GT5-Unofficial/blob/1.10.2/src/main/java/gregtech/common/blocks/GT_Block_Casings_Abstract.java#L45

**Comment by MauveCloud** [comment]
Requiring a tier 3 wrench such as cobalt to get decent breaking speed might have been related to #916.

**Comment by Exidex** [comment]
Invalid because of rewrite.
