### ISSUE TITLE
AE2 Seeds Problem with GregTech

### ISSUE THREAD

**Issue by lordjoda** [Blood-Asp/GT5-Unofficial#91]
Since this only occurs when GregTech is installed I assume this is a GregTech issue: 
When crafting Fluix or Netherquarz seeds they are displayed and recognized as a different item then the crafting logic expects and therefore the autocrafting logic breaks. Tested with only ae2-rv2-stable9 and gt-5.08.24 and IC2-2.2.746 and default configs.
Since the itemID doesn't change I'm guessing some nbt data is changed? Is this a unification issue?

![ae2bug](https://cloud.githubusercontent.com/assets/1130533/8730561/d1217818-2bf1-11e5-8a6a-cf661e6d9da5.png)

**Comment by Blood-Asp** [comment]
Do they even have an oredict tag?

**Comment by lordjoda** [comment]
Actually no they don't...

**Comment by Blood-Asp** [comment]
Use http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac to check the nbt tags.

**Comment by lordjoda** [comment]
The freshly crafted item (count 1)(without GT) has no nbt data. It gets it after some time in the inventory (count 5). With GT installed the nbttag is apparently set immediately, as these items did stack.
![nbt](https://cloud.githubusercontent.com/assets/1130533/8731108/6ceda340-2bf5-11e5-8203-88958c76bed0.png)

**Comment by lordjoda** [comment]
Oh and I don't know if this helps but Certus Quarz Seeds don't have this issue...

**Comment by Blood-Asp** [comment]
The tag "progress" should be AE2s own tag how long it did lay in water... GT does not write that in. 
At last it is not GTs fault alone.

**Comment by lordjoda** [comment]
Alright... @yueh you have any idea what might be causing this?

**Comment by Blood-Asp** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv2/src/main/java/appeng/items/misc/ItemCrystalSeed.java#L99 seeing this, the tag is normal for all crystal seeds. Not having it is the issue. Just tested together with GT and all seeds have the NBT tag.

**Comment by Blood-Asp** [comment]
Did you programm the Crafting recipe with the actual item or directly from NEI? The NEI item might miss the tag first. But that is not a GT issue at all.

**Comment by lordjoda** [comment]
Sadly you cannot set the output manually anymore, but I did try to set the input manually, but to no effect.

**Comment by lordjoda** [comment]
So I posted the issue in the AE2 Issue tracker : AppliedEnergistics/Applied-Energistics-2#1718 and basically it appears that that it must be something that GregTech is doing. Would you mind taking another look at this, as it would require a breaking change on the ae2 side to fix it and therefore is not likely to be fixed soon...

**Comment by Blood-Asp** [comment]
Can you try to disable the unification in the GT configs and test if it still behaves the same way?

The only idea i currently have is that alone the check from GT lets AE2 generate the tag. Should it work, i should be able to fix it.

**Comment by lordjoda** [comment]
I set B:CraftingUnification=false but still no change.

**Comment by lordjoda** [comment]
The issue was apparently resolved on the AE2 side, therefore I'm closing this
