### ISSUE TITLE
[1.10.2] Small boilers do not allow quick filling via buckets

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#911]
In GT 5.09 and earlier, it was possible to right-click on a small boiler with a water bucket to add the water without opening the GUI, speeding up the process slightly.  In GT 5.10, doing so opens the GUI, so it is necessary to place the bucket in the GUI slot instead.

**Comment by Dragon2488** [comment]
And now it isn't possible.

**Comment by MauveCloud** [comment]
You mean this was by design?  Could you please explain the logic behind that decision?

**Comment by Dragon2488** [comment]
It bugged and I removed it.

**Comment by Dragon2488** [comment]
First time i tried to make it work with any fluid storage item, but it was too complex and had problems with sync. So I completely removed this feature.
