### ISSUE TITLE
Add way to pass ME network into cleanroom

### ISSUE THREAD

**Issue by Dimach** [Blood-Asp/GT5-Unofficial#914]
This is most needed feature before new circuit system released.

**Comment by Blood-Asp** [comment]
2 Ways: Access the machines indirectly by passing all items trough the hulls or build a quantum gate inside.

**Comment by Dimach** [comment]
Build quantum gate for using ME system inside? Really?
Indirectly inventory access bad idea, some recipes can require same components for craft, and ME interface setting "empty inventory" cant be used in this case.
I recommend add a possibility to pass me network inside using cables, not quantum gates (or discuss it with community).

**Comment by leagris** [comment]
A valid option could be having a valid block whitelist for the Cleanroom. Like Galacticraft  has an air tight whitelist.

**Comment by Blood-Asp** [comment]
At last all current cleanroom recipes have exactly 1 input item, 1 output item.

**Comment by draknyte1** [comment]
I agree with Blood. Quantum gateway it or do it by hand.. Not everything is automatable. Simple.

**Comment by Nex4rius** [comment]
>Not everything is automatable.

But why? I don't like this concept.

**Comment by draknyte1** [comment]
Same reason some things in real life aren't. It simply can't be, or it's easier to have manual handling than invest in expensive infrastructure. Such as a quantum gateway, in this case.
