### ISSUE TITLE
[1.10.2] Marble found in Nether

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#915]
Using only the following mods:
Batty's Coordinates Plus for Forge
CodeChickenLib
GregTech 5.10.40
IndustrialCraft
Inventory Tweaks
JEI
Mouse Tweaks
OpenComputers
Optifine (disabled)
Pressure Pipes
Waila

and WorldGeneration.cfg as attached
[WorldGeneration.cfg.txt](https://github.com/Blood-Asp/GT5-Unofficial/files/812079/WorldGeneration.cfg.txt)

I found a large (or maybe huge) deposit of Marble in the Nether:
![2017-03-01_13 23 54](https://cloud.githubusercontent.com/assets/8942955/23482230/2c27de4a-fe83-11e6-81a0-c0ea713bd1bd.png)

**Comment by Blood-Asp** [comment]
So no mod that adds new biomes to the nether generation?

**Comment by MauveCloud** [comment]
Not this time, unless one of the mods I listed does something to the Nether biomes.  I already knew that kind of thing could interfere with GregTech's ore generation in the Nether, so I didn't even use BoP (despite knowing that Nether biomes haven't been re-implemented in that mod yet).

Update: I've also seen basalt and black granite in the Nether, though the few ore mixes I've found so far have been valid for the Nether (including a Sulfur vein I found fairly early)

**Comment by MauveCloud** [comment]
I've tracked down why this happens:
GT_Worldgen_Stone uses a different inherited function for checking if generation is allowed:
https://github.com/Blood-Asp/GT5-Unofficial/blob/1.10.2/src/main/java/gregtech/api/world/GT_Worldgen.java#L71

GT_Worldgen_GT_Ore_Layer uses this one:
https://github.com/Blood-Asp/GT5-Unofficial/blob/1.10.2/src/main/java/gregtech/api/world/GT_Worldgen.java#L59

However, I'm a bit stumped for how to fix it.  I tried changing the one called by GT_Worldgen_Stone to only compare the two ints passed as arguments, similar to how 5.09 does it, but that apparently prevents the extra stone types from generating in the Nether even if enabled in Worldgeneration.cfg.

I realized while writing this update post that I hadn't tested enabling the extra stone types in the Nether in Worldgeneration.cfg in 5.09, and it seems that doesn't work.

**Comment by MauveCloud** [comment]
Slight correction: when testing to make sure enabling GT stones in the Nether worked, I had only tested with Marble, which ran into a bug inherited from 5.09, leading me to mistakenly that my fix was introducing a new problem.  With all GT stones enabled for the Nether with my change, red granite and black granite still generated.
