### ISSUE TITLE
Reset cleanness of Clean Room

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#917]
If door are opened cleanness should reset to zero and stay so until its closed. After should slowly rise to 100%.

**Comment by leagris** [comment]
Unless door has a, airlock, air in airlock is pumped/cleaned and player is wearing a clean suit.

**Comment by leagris** [comment]
otherwise that clean room should have sealed manipulator gloves or remote-manipulator arms and grabber.
Like this: ![](https://upload.wikimedia.org/wikipedia/commons/2/28/Alpha-Gamma_Hot_Cell_Facility_001.jpg)

**Comment by MauveCloud** [comment]
> Unless door has a sass, air in sass is pumped/cleaned and player is wearing a clean suit.

I'm having trouble finding a meaning for "sass" that allows this sentence to make sense.  Is it similar to an airlock?

**Comment by leagris** [comment]
Yes an Air Lock like that:
![](https://vertassets.blob.core.windows.net/image/0c57bbc8/0c57bbc8-f232-4520-b793-a086003a73bd/clip_image001.jpg)

**Comment by Blood-Asp** [comment]
A check if the door is open and then lowering the efficiency/cleanness a bit is what i will add at last. Just wanted to finish the other stuff first.
Alternative would be to add that two doors in a row as airlock and wearing hazmat suit inside is needed to keep it clean. Not sure i would do that much work, but the idea is there.
