### ISSUE TITLE
eIO Conduits connecting where they should not

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#92]
EnderIO conduits are connecting to the blocks they should not connect. For example it visualy connects Fluid Conduit to GregTech Cable. Not sure if its something that needs to be taken care of on your side on eIO side. So I am reporting this on both issue trackers
![2015-07-19_23 11 50](https://cloud.githubusercontent.com/assets/4236895/8767939/5a2d4c94-2e6e-11e5-9a11-4ae564173879.png)

eIO Issue: https://github.com/SleepyTrousers/EnderIO/issues/2661

**Comment by DarknessShadow** [comment]
I'm not sure if I should post this here or seperate... 

The pipes connect even when its disabled.
<a href="http://imgur.com/s44IkvA"><img src="http://i.imgur.com/s44IkvA.jpg" title="source: imgur.com" /></a>
gregtech_1.7.10-5.08.24
EnderIO-1.7.10-2.2.8.381

**Comment by Blood-Asp** [comment]
Like the EnderIO issue said, there is no way in the api to fix this. You can only manually disconnect trough covers.

**Comment by JasonMcRay** [comment]
Ok then can you explain why fluid conduit doesnt connect to for example
chests or ic2 wires?

**Comment by Blood-Asp** [comment]
They only can check if the tile implements IFluidTank. All GT blocks do that beause they share all the same base block and only change its functions. 
So every GT cable is also a fluid Tank just with 0 cap. For example AE2 cables also do that.
The Energy APIs all have a method to check if the connection is allowed.

**Comment by DarknessShadow** [comment]
But they could be automaticly deactivated if a connected tank has a maximum space of 0.

**Comment by Blood-Asp** [comment]
There is no function that explicit returns the capacity. Even trough you can get it in most cases, it still does not help. Sometimes there is a capacity defined, even trough it is not used, or sometimes it uses fluid internally but does not allow to transfer it anywere.

**Comment by JasonMcRay** [comment]
Oh. Ok thanks for explaining.
