### ISSUE TITLE
Titanium Tetrachlorine doesn't use chlorine recipe in chemical reactor

### ISSUE THREAD

**Issue by Valps** [Blood-Asp/GT5-Unofficial#920]
And the chlorine does not appears on NEI in recipe. Chemical reactor consumes only rutile dust and carbon dust.

Sorry for bad english.

GT version: 5.09.27

EDIT: sorry, I not saw the preview issue page

**Comment by Blood-Asp** [comment]
As you found out, already fixed in dev.
