### ISSUE TITLE
[1.10.2] Railcraft integration

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#921]
Railcraft integration that was working in 1.7.10 does not work in 1.10.2.

Example: Making Standard Rails was made in bending machine in 1.7.10, or a recipe for making RC tanks with the use of plates and tools.

GT: 5.10.40

**Comment by MauveCloud** [comment]
RC tanks and (iirc) rails haven't been re-implemented yet in the 1.10.2 version of that mod, so I don't see how GT would be able to do anything with them.

**Comment by JasonMcRay** [comment]
Well that was just an example. RC Tanks are not in, true, but the rails and tracks are.

**Comment by MauveCloud** [comment]
It looks like the bending machine recipes are still in the code in 1.10.2:
https://github.com/Blood-Asp/GT5-Unofficial/blob/1.10.2/src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java#L1036-L1051
but the ItemList additions probably need to be updated for the 1.10.2 version of Railcraft:
https://github.com/Blood-Asp/GT5-Unofficial/blob/1.10.2/src/main/java/gregtech/common/GT_Proxy.java#L253-L270

Side note: I don't think RC tanks (iron, steel, or water) required tools in their crafting recipes in 1.7.10, even with GT installed.  Some of the RC-specific minecarts did, though.

**Comment by draknyte1** [comment]
I think every modpack made the tank require tools in 1.7.10 though.

**Comment by MauveCloud** [comment]
> I think every modpack made the tank require tools in 1.7.10 though.

Wouldn't surprise me much, but that was probably done with Minetweaker scripts, which wouldn't require any changes to GT 5.10 to support.

**Comment by JasonMcRay** [comment]
GT Itself changed the recipe for the Iron Tanks in 1.7

**Comment by MauveCloud** [comment]
> GT Itself changed the recipe for the Iron Tanks in 1.7

In what version?  Using 5.09.28pre, not in a third-party modpack, I can't confirm that:
![2017-03-05_07 47 51](https://cloud.githubusercontent.com/assets/8942955/23588837/27f84f10-0178-11e7-829e-6323c63c900b.png)

(I also checked my Minetweaker scripts to make sure I wasn't cancelling such a change, and the only Railcraft scripts I had in that instance were a few lines to make the RC steel tools uncraftable)

**Comment by JasonMcRay** [comment]
![image](https://cloud.githubusercontent.com/assets/4236895/23589033/b65257a8-01c6-11e7-907f-9c1290139bf4.png)
Check the recipe on all pages.

Unification of the plates is just terribly broken. So if you have unification target set as RC Plate you can "cheat" without the tools. If you have set it to GT Plates you cannot use GT plates in that "cheaty" recipe

**Comment by MauveCloud** [comment]
Okay, I stand corrected (I'd always figured the rest of the recipes were just for the dyed versions of the tank blocks - if that doesn't quite fill 8 pages in NEI, that means there's one dye color that can't be used for tank walls - apparently black).  Not sure what the point of GT adding that recipe is if RC plates are the default unification target (when RC is installed) and it doesn't remove the "cheaty" recipe, though.

Anyway, it looks like the code for those recipes still exists in GT 5.10:
https://github.com/Blood-Asp/GT5-Unofficial/blob/1.10.2/src/main/java/gregtech/loaders/postload/GT_CraftingRecipeLoader.java#L357
https://github.com/Blood-Asp/GT5-Unofficial/blob/1.10.2/src/main/java/gregtech/loaders/postload/GT_CraftingRecipeLoader.java#L370
Those lines will just need to be tweaked to use the new internal names once RC re-implements those blocks.

**Comment by MauveCloud** [comment]
> Not sure what the point of GT adding that recipe is if RC plates are the default unification target (when RC is installed) and it doesn't remove the "cheaty" recipe, though.

FWIW, I figured this out.  https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/loaders/postload/GT_CraftingRecipeLoader.java#L328 tells it to remove recipes with matching NBT data (presumably so that the recipes for adding dyes to the tank walls remain in place), but the recipe with steel plates and GT tools produces `<Railcraft:machine.beta:13>` while the recipe with 4 steels plates but no GT tools produces `<Railcraft:machine.beta:13>.withTag({color: 15 as byte})`
