### ISSUE TITLE
[1.10.2] Two reipes for iTNT, one is superior to the other

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#924]
There are two recipes for iTNT.

One with Glyceryl + Paper + String in ChR (4EU/t) and second with Toluene+Nitration Mixture in ChR (480EU/t)? The first one is marginaly easier in both materials used and power required.

Only the one with Toluene and Nitration Mixture exist in 1.7.10 as far as I know.

GT: 5.10.40

**Comment by Blood-Asp** [comment]
the glyceryl + paper + string recipe should be for dynamite, not for iTNT.
