### ISSUE TITLE
[5.09.28] Data stick from seismic prospector can't be printed out

### ISSUE THREAD

**Issue by Antifluxfield** [Blood-Asp/GT5-Unofficial#929]
The data stick from the old seismic prospector, already analyzed in the scanner. It does not show the coordinate in the tooltip as it used to be, and its information is not able to be printed either, so seems that there is no way to get the information from this prospector.

**Comment by Antifluxfield** [comment]
Tested for a few more times.
Cannot reproduce stablely, but tend to occur in a newly created world, and recover when entering the world for the second time.

**Comment by Blood-Asp** [comment]
Did you look at the NBT tags of the stick? You should be easily get them when you have minetweaker installed. Just hold stick in hand and write "/mt hand".

**Comment by Antifluxfield** [comment]
It doesn't contain any data about the result, even before analyzed by the scanner.
![h4b4m ivqpw cr1 pqzlwo](https://cloud.githubusercontent.com/assets/17354844/23669886/bf430782-03a0-11e7-84ee-37babc8952cc.png)
That's all of their Tags...

**Comment by maixgame** [comment]
@antifluxfield 
#937 
https://yadi.sk/d/sg-AcFQO3FA7Gy

![2017-03-08_01-37-55](https://cloud.githubusercontent.com/assets/25564867/23681391/e065edf4-039f-11e7-8cb9-db398506b265.png)
![2017-03-08_01-38-26](https://cloud.githubusercontent.com/assets/25564867/23681410/f22b44d0-039f-11e7-9692-27f68feeb3dc.png)

**Comment by Antifluxfield** [comment]
@maixgame 
Tested again for several times with your version.
It seems that the issue is not occuring again. But I'm not really sure whether it's fixed, since as what I said above, I can't stablely reproduce the problem...

**Comment by Blood-Asp** [comment]
Well, will close this for now as it is likely fixed. Should it still happen in later builds just tell me to open it again.
