### ISSUE TITLE
Achievement issue

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#93]
I just crafted for the first time Magnetic Iron Rod and did not received an achievement. Happend on server, tried to: Relog, Restart server, Craft it in vanilla crafting table... No achievement

And yes i have the Steel achievemnt done

**Comment by Blood-Asp** [comment]
I had some issue with that, but thought i fixed it. That server is running the current GT version, right? Currently can't replicate it.

**Comment by JasonMcRay** [comment]
Yep its my own little dev server with latest everything

**Comment by Blood-Asp** [comment]
Could you: Backup your profile, remove achievements per op command, reactivate the prior achievement and then try to get it?

Should that not work, it is not what i think it might be and it gets annoying to search.

**Comment by JasonMcRay** [comment]
Oh. I see where I derped. I actually dont have Steel achievement. I made Steel using thaumcraft transmutation. So maybe add either check for that? Or something?

**Comment by Blood-Asp** [comment]
Hmm, right. I made it so it only unlocks when produced in a Blast Furnace because there is soo much steel loot to find and i do not want it unlocked by non production means.

**Comment by JasonMcRay** [comment]
Since its just an achievement, maybe also detect for the TC research for achievement completion

**Comment by Blood-Asp** [comment]
I wonder if it throws some event. If yes, i will use that.

**Comment by Blood-Asp** [comment]
Just added: Steel Achievement can be unlocked by: Picking up a full stack of steel ingot or a steel nugget when thaumcraft is installed and steel research is done.
Will be in 5.08.26.
