### ISSUE TITLE
[5.09.28]Cleanroom bugs 

### ISSUE THREAD

**Issue by Antifluxfield** [Blood-Asp/GT5-Unofficial#930]
1.Cleanroom does not consume energy. Moreover, it can even work without any energy support.
Edit:
2.Cleanroom can hardly recognize those machines placed after the multiblock structure is completed.
I have waited for minutes, but those latter-placed machines never start working. They only work after I 
re-enter the game or re-build the cleanroom to re-complete the structure.

**Comment by draknyte1** [comment]
Real world clean rooms don't have power funnelled into them past running lights and possibly extractor fans.. Possibly intended, unless the tooltip says otherwise

**Comment by Antifluxfield** [comment]
But the structure requires an energy hatch. If the feature is intended, what is the energy hatch used for?
I think that at least it should consume some energy when rising the cleanness, as if it is filtering the air or doing some other works.
