### ISSUE TITLE
[5.09.28] Low gravity process does not really need low gravity environment

### ISSUE THREAD

**Issue by Antifluxfield** [Blood-Asp/GT5-Unofficial#932]
GalactiCraft installed, config opened, NEI shows that the crystallizaiton of raw crystal chip & data orb "Needs Low Gravity"- but the autoclave still start processing in the overworld.

By the way, my friend find a recipe that you can craft 9 Raw Crystal Chip with only 1 Crystal Processing Unit. We are wondering whether this recipe is intended, or only should the raw chip crafted by crystallizing in  europium?

**Comment by Blood-Asp** [comment]
An invert was missing. So they did work everywhere besides space...

The 1 CrystalPU = 9 raw crystal chip recipe is intended. The europium recipe is only needed to start with crystal chips, after that they can be cheaper duplicated.

**Comment by Antifluxfield** [comment]
@Blood-Asp 
5.09.29pre
This time it doesn't work anywhere, even in the space station...
By the way, in .28 it do work in the space. Seems something wrong with the dim ID.

**Comment by MauveCloud** [comment]
Looking at https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_BasicMachine.java#L735 it seems like it will only work on the space station, and then only if the space station's dimension id is left at default (admittedly, I don't know of any other mod that uses the same dimension id by default id that would require one of them to be changed).  

If "low gravity" is the requirement, shouldn't such a recipe also work on the moon or in the asteroids?  If you really meant "microgravity", the moon can be removed from that list.

Edit: while I'm at it, just checking that it's on the space station might not be enough.  I haven't played Galacticraft much myself, but I came across https://wiki.micdoodle8.com/wiki/Overworld_Space_Station#Spin_Thrusters meaning that certain areas of a space station can effectively have 1G and no longer really be a "low gravity environment".

**Comment by Antifluxfield** [comment]
Already checked the config of galacticraft, the dimension id is at the default value(-27), but the machine still doesn't work in the space station.
"Low gravity" or not is something less imprtant, the critical thing is to make it at least work as expected...

**Comment by JasonMcRay** [comment]
Problem with Space Station dimension is that each Space Station dim will have different ID. For example on server you can have space station with ID -27 but also with ID -30 etc... Each player can make their own SS dimension, so this in this current state will never work.

**Comment by draknyte1** [comment]
A result of improper tested code.
