### ISSUE TITLE
[5.09.28] Too hard to obtain gallium in early game.

### ISSUE THREAD

**Issue by Antifluxfield** [Blood-Asp/GT5-Unofficial#933]
I find that the circuits are starting to use gallium as ingredient since MV. I know that gallium can be produced by pulverizing centrifuged bauxite or sphalerite, but only HV+ macerators have extra slots for the byproducts . Thus before that, the only source of gallium is to centrifuge the purified zinc ore, which means you have to find tons of small zinc ores for the circuits in early game. Is this intended?

**Comment by Techlone** [comment]
Zinc can be find in the nether.

**Comment by Antifluxfield** [comment]
So we ought to hunt the small ores?

**Comment by Blood-Asp** [comment]
I mixed up that sulfur veins contain shalerite ores that can produce zinc and not zinc ores... Will rebalance. The small ores are too few i think.

**Comment by Techlone** [comment]
@antifluxfield oh yep sry
I thought we can find pure zinc in the nether...

**Comment by Antifluxfield** [comment]
@Techlone 
Never mind.
Many other players in my community decide to wait for the rebalence. And those who want to experience .28 on time adopt the idea of small-ore hunting; or they just have reached HV already.

**Comment by StragaSevera** [comment]
So, LV-MV Gallium requirements became lower, but not completely zero. Is it intended that we must hunt for small zinc ores?
I will try to count how many smal zinc ores we will need on the way to HV macerator.

UPD. It seems that we only need 3 'ineffective' (1/4 Gallium) for Good Circuits, after that gallium consumption is very low (around 3/128 tinies for good and 9/128 tinies for advanced). So, 2-3 small zinc ores will be enough =-)

**Comment by antifluxfield** [comment]
@OUGHT 
My result is that we need about 62 small zinc to reach the HV macerator.
The ingredient of HV circuit is quite "cheap" - 1 monocrystalline sillicon(which means 1/9 Ga dust) is enough; but you need at least 1 MV laser and 1 MV cutting machine to handle it, and that's 7 diodes. So the most 'economical' strategy is to make the MV assembling machine at first, 4 'inefficient' Ga dust for the first 4 diodes, and later 1 'efficient' Ga dust for 16 diodes. To sum up, that is 46 tiny gallium dust in total. Meanwhile, you should notice that the impure zinc dust cannot produce any gallium, so only about 3/4 of the small zinc ores is available for our circuits. As a result, we need 46/(3/4)=61.33...≈62 small ores. That's the minimum requirement.
