### ISSUE TITLE
[1.10.2] Occassional crashes, apparently related to rendering

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#938]
Twice today while preparing to craft some LV machines (I haven't actually crafted the steam turbine quite yet), my single-player game crashed, and the logs seem to imply this was caused by the rendering code, so possibly related to #901.

From the second crash:
Client crash report: http://paste.ubuntu.com/24127405/
Integrated server crash report: http://paste.ubuntu.com/24127410/
latest.log: http://paste.ubuntu.com/24127417/
fml-client-latest.log: http://paste.ubuntu.com/24127430/
GregTech.log: http://paste.ubuntu.com/24127439/

**Comment by Exidex** [comment]
Invalid with the rewrite
