### ISSUE TITLE
deactivating unnecessary recipes

### ISSUE THREAD

**Issue by DarknessShadow** [Blood-Asp/GT5-Unofficial#94]
Is it possible to deactivate all recipes for items that are useless?
And with useless I mean items that are only used in recipes to turn them back or to make other items that are also useless.

Because for every material there are around 40 different items you can craft and almost all of them are completly useless because no recipe is using them.

Its really hard with NEI to find out if a resource is actually useful and for what because you have to search way too much.
Its especially bad for new players who don't know which resource is used for what.

**Comment by Blood-Asp** [comment]
Even trough i know how annoying it is, i have no idea how i could possible filter recipelists in NEI automaticly. So all i can do is to say: Impossible within reasonable limits.
