### ISSUE TITLE
Machine maintenance detection not working properly

### ISSUE THREAD

**Issue by MarcNemesis** [Blood-Asp/GT5-Unofficial#941]
![not working](https://cloud.githubusercontent.com/assets/26238531/23639062/43aec388-02b3-11e7-87d7-3105ac472f3e.png)
![working](https://cloud.githubusercontent.com/assets/26238531/23639063/43b058f6-02b3-11e7-81f3-10acfafdcaad.png)

Edit:
This was tested in FTB Infitech 2 (V 3.2.20) for Minecraft 1.7.10
Edit end

Problem:
So in the picture, i have 4 Distillation towers. All of them have the exact same configuration. 
- Each controller have a "Needs maintenance cover" on top of them set to detect atleast 1 maintenance issue.
- Each controller have a "Redstone Transmitter (In)" on the bottom with frequency -64.

If the 3rd & 4th tower both have a minimum of 1 maintenance issue, the lamp is activated via a "Redstone Receiver (Out) on frequency -64. (This part work fine.)
Now if the 4th tower has no maintenance issue and the 3rd one has atleast 1 maintenance issue (Screwdriver in this case), the lamp close has if there was no maintenance issue.

What should happen:
The lamp should be activated to signal that maintenance is required.

Where the problem come from:
I can't say for sure wether it's a problem within the "Needs maintenance cover", the Wireless signal or sompletely something else.

**Comment by MarcNemesis** [comment]
I forgot to mention version details:
This was tested in FTB Infitech 2 (V 3.2.20) for Minecraft 1.7.10

**Comment by Blood-Asp** [comment]
From how i understand it, it is likely the wireless signal you have the issue with. 
If you have multiple inputs on one frequenzy, it checks all inputs and only outputs the last one it checked. So basicly multiple inputs in one frequenzy does not work correctly. Output would be random.
