### ISSUE TITLE
[1.10.2] Loading single-player world sometimes gets stuck at 0%

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#943]
Sometimes when I load a single-player world, it gets stuck at 0%, and I have to use MultiMC's "Kill" button to stop it and try again.  I haven't figured out exactly how often it happens, and for a while I didn't realize GregTech was involved, but then I found an exception in fml-client-latest.log about 100 lines before GregTech's listing of OreDictionary entries, which indicated GT might be to blame.

latest.log: http://paste.ubuntu.com/24128986/
fml-client-latest.log: http://paste.ubuntu.com/24128988/

**Comment by Exidex** [comment]
Invalid with the rewrite
