### ISSUE TITLE
Oil Drilling Rig not working gt 5.9.28 mc 1.7.10

### ISSUE THREAD

**Issue by 9000bowser** [Blood-Asp/GT5-Unofficial#945]
After build the oil drilling rig, this device plate the mining pipe up to the bedrock and stop working.

I trying move the drilling rig and always same a problem.

![2017-03-07_17 52 51](https://cloud.githubusercontent.com/assets/20327368/23667685/ff955f98-035e-11e7-9a50-076e7da7ca95.png)
![2017-03-07_17 53 56](https://cloud.githubusercontent.com/assets/20327368/23667706/1251def4-035f-11e7-9e50-3196addd90b1.png)
![2017-03-07_17 54 00](https://cloud.githubusercontent.com/assets/20327368/23667709/14cc48d6-035f-11e7-9cb0-54c377db3680.png)

I trying to change a config and not work
and is not an power issue
![2017-03-07_17 55 56](https://cloud.githubusercontent.com/assets/20327368/23667801/623f38f8-035f-11e7-9430-b2108eb84615.png)
![2017-03-07_17 56 35](https://cloud.githubusercontent.com/assets/20327368/23667821/6d23c7fc-035f-11e7-851e-fb51fcd3d735.png)

**Comment by MauveCloud** [comment]
A couple of questions to help clarify this:
1. What does the seismic prospector say about the oil type in that area?  It looks like you have cheats enabled already, though you might have to use /mt hand to get the data, based on #929.
2. How far have you moved the drilling rig?  If you moved it within the same 96x96 block area, and that area has no oil or gas, the move won't help.

**Comment by 9000bowser** [comment]
365 mb of natural gas

the command /mt wand not working

**Comment by DEMOOH** [comment]
Might be linked to this issue as well https://github.com/Blood-Asp/GT5-Unofficial/issues/935
Download the build linked at the end of the issue.

**Comment by maixgame** [comment]
@9000bowser try this:
https://yadi.sk/d/sg-AcFQO3FA7Gy
if the problem will disappear, then this bug fixed in #937
