### ISSUE TITLE
[5.09.28] Data Stick, Nanoprocessor Mainframe and Data Orb tooltip enhancement

### ISSUE THREAD

**Issue by StragaSevera** [Blood-Asp/GT5-Unofficial#946]
Data Stick counts as Extreme Circuit and Nanoprocessor Mainframe with Data Orb both count as Master Circuit,  but their tooltips do not mention it. 
If we could type "circuit" in NEI and have full circuit list, it would be great =-)

**Comment by StragaSevera** [comment]
Great. But Data Stick still does not tell which level Circuit it can be =-)

**Comment by Blood-Asp** [comment]
Data + Circuit. Is both in the tooltip.

**Comment by StragaSevera** [comment]
But other circuits of this level are named Extreme, not Data...
