### ISSUE TITLE
[5.09.28] Cleanroom improvement - cleanness % emitted as redstone signal

### ISSUE THREAD

**Issue by StragaSevera** [Blood-Asp/GT5-Unofficial#948]
Automating the circut production would be much more enjoyable if there were some way to get cleanness as redstone signal. This way we could use comparator to prohibit machines from running if cleanness is low - because of recent door opening, or because of power outage.

It can be special block in structure, or secondary controller function. But either way, this feature will be super useful =-)

**Comment by DEMOOH** [comment]
You could just use timer for that.

**Comment by StragaSevera** [comment]
Timer cannot handle properly slow-falling cleanness from door opening. We will need to lurk into source code and look for constants, instead of getting nice and clean output.
