### ISSUE TITLE
Backport UBC support from GT6

### ISSUE THREAD

**Issue by KuroNeko87** [Blood-Asp/GT5-Unofficial#95]
Just to make the official request here since I already asked on IRC.

Would be nice to have UB goodness with GT5u as well! ^_^

**Comment by Blood-Asp** [comment]
Even trough i could copy over the GT6 ore system relatively easy, it would mean a breaking update. All existing ores were lost.

**Comment by KuroNeko87** [comment]
After talking to greg, he said it was possible to keep the old ones while backporting the new ones. Then again, it's up to you as you're the one delving in the code.

**Comment by Blood-Asp** [comment]
While it is possible, the work needed for that is not worth it in my opinion.

**Comment by KuroNeko87** [comment]
Fair enough. Thanks for considering it though.

**Comment by Blood-Asp** [comment]
I still hope greg speeds up his work on GT6 again, so i can switch over once the api has all functions i need. There are afew ideas i have that will be much easier with GT6 than adding them to GT5.
