### ISSUE TITLE
[5.09.29pre] Advanced Circuit Assembling Machine II crafting

### ISSUE THREAD

**Issue by CrazyIvan44** [Blood-Asp/GT5-Unofficial#951]
It seems like crafting of Advanced Circuit Assembling Machine II (HV-tier) is impossible, cirquits needed are all EV tier and require at least HV CAM, so machine is needed to craft components of itself.
![hvcam1](https://cloud.githubusercontent.com/assets/26348700/23825430/db4ef9fc-069a-11e7-8152-74a859c8bbc8.png)
![hvcam2](https://cloud.githubusercontent.com/assets/26348700/23825432/e075f9d0-069a-11e7-8569-7ad96f28e1ed.png)
![ds](https://cloud.githubusercontent.com/assets/26348700/23825434/e6ee9a4c-069a-11e7-9492-1171cb623ca5.png)
![npa](https://cloud.githubusercontent.com/assets/26348700/23825436/ed7db30c-069a-11e7-8323-f92732ed8722.png)
![qp](https://cloud.githubusercontent.com/assets/26348700/23825438/f2464674-069a-11e7-953c-7e818b9c98a9.png)
Workstation (ex Data Storage Circuit) have no craft recipe.

**Comment by MauveCloud** [comment]
Looks to me like Blood Asp already fixed this in GitHub with this commit: https://github.com/Blood-Asp/GT5-Unofficial/commit/d7203bccbde715d006783615c4c05a646d58ccaa (I tried building it locally, and as far as I could tell, some of the circuit options for crafting the HV circuit assembler could now be made with just MV-tier machines)
He just hasn't put up a new preview build with it yet.
