### ISSUE TITLE
[1.10.2] Problems with duplicate liquids

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#957]
Would it be possible to have machines recognize liquids from other mods as well? Just an example Tinkers are adding `<liquid:tin>` but it cannot be used in recipes that require `<liquid:molten.tin>`

**Comment by Blood-Asp** [comment]
GT fluids are intentionally different since some mods have simillar fluids but the amounts or production limitations are different. In modspacks these have to be manually unified either with conversion recipes or by adding nessary recipes to Tinkers (at last in 1.7.10 possible with minetweaker)
