### ISSUE TITLE
Cropnalyzer not chargable in LV Battery Buffer

### ISSUE THREAD

**Issue by JasonMcRay** [Blood-Asp/GT5-Unofficial#96]
Using the latest IC2 (756) the cropnalyzer, which now has 100k EU storage built in, can be charged using an LV battery (RE-battery), but cannot be charged in an LV battery buffer.

**Comment by Blood-Asp** [comment]
100k somehow sounds like it was moved to MV. Did you try that?
IC2 charging works with lower tier batteries, GT not.

**Comment by Blood-Asp** [comment]
Seems problem was found. It is MV now.
