### ISSUE TITLE
GT 5.09.29pre Advanced Circuit Assembling machine II 512 (HV).

### ISSUE THREAD

**Issue by darkeymc** [Blood-Asp/GT5-Unofficial#964]
Can't craft Advanced Circuit Assembling machine II 512 (HV).
Data stick crafts at 160 eu/t (I need Advanced Circuit Assembling machine II to crafting Advanced Circuit Assembling machine II).

**Comment by Antifluxfield** [comment]
Yep. Seems that we need a workstation here, with a recipe requiring MV circuit assembling machine. Currently this recipe is missing.

**Comment by Blood-Asp** [comment]
Duplicate https://github.com/Blood-Asp/GT5-Unofficial/issues/951 , fixed in dev
