### ISSUE TITLE
[5.09.29pre] Only black granite generates in Nether when enabled in WorldGeneration.cfg

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#968]
When attempting to fix #915, I realized I hadn't tested deliberately enabling the GT stone types in the Nether in WorldGeneration.cfg in 5.09.  I'm not sure if anyone is really interested in deliberately making GT stone types appear in the Nether, but when I tried it with a bare minimum of mods (GT, IC2, CCC, and NEI), I discovered that apparently only the black granite generates in the Nether.  Even after flying for more than 3000 blocks in creative mode, I was unsuccessful at finding any red granite, basalt, or marble.

Here is what WorldGeneration.cfg looked like after that:
http://paste.ubuntu.com/24189384/

In the "dimensions" section, I notice that basalt and marble are defaulting to false in the nether for both the "overworld" and "nether" subsections, but black granite and red granite are defaulting to false in the nether for the "overworld" subsection but true for the "nether" subsection, leaving me confused that I could find black granite but not red granite.

**Comment by MauveCloud** [comment]
I figured out why this happens.  https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/loaders/postload/GT_Worldgenloader.java#L35-L44 sets the dimension type to -1 (nether) for `nether.stone.blackgranite.*` and `nether.stone.redgranite.*`, but https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/loaders/postload/GT_Worldgenloader.java#L57-L66 sets dimension type to 0 (overworld) for `nether.stone.marble.*` and `nether.stone.basalt.*`

Might have just been bad luck that I only found the black granite and not the red granite.

**Comment by Blood-Asp** [comment]
So like this? https://github.com/Blood-Asp/GT5-Unofficial/commit/e986232c349ee5e7f3ef242d179363048c8999c0

**Comment by MauveCloud** [comment]
Exactly.  I fixed it in a PR for the 1.10.2 branch, but it looks like you beat me to it for the unstable branch. 😄
