### ISSUE TITLE
Large Heat Exchanger stuck.

### ISSUE THREAD

**Issue by ShelfOwl** [Blood-Asp/GT5-Unofficial#97]
After Large Heat Exchanger turns 50 kL of lava into pahoehoe, it no longer works.
I assume that it collects pollution (as same as Large Boiler) but there is no room for the muffler hatch.

**Comment by AiwendilCiunio** [comment]
Other people experience this, including me. @Blood-Asp, was this fixed in latest version?

**Comment by Blood-Asp** [comment]
There was no update since this report. 
It will in the next update. But that one will likely take a few days more.

**Comment by Blood-Asp** [comment]
Fixed for 5.08.26
