### ISSUE TITLE
[1.10.2] liquid air cells no longer obtainable

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#970]
In GT 5.09, there were a couple of ways to get nitrogen from compressed air cells (option 1: transfer the air to a centrifuge's input tank via fluid canner or output hatch, and add an empty cell; option 2: vacuum-freeze 53 compressed air cells into liquid air cells, and centrifuge those).

However, at some point between MC 1.7.10 and MC 1.10.2, IC2 removed empty cells, and now the way to get air in cells is to put universal fluid cells in a compressor.  However, this produces `<ic2:fluid_cell>.withTag({fluid: {FluidName: "ic2air", Amount: 1000}})` according to CraftTweaker, and the GT recipes have not been updated to handle this.

Transferring air from a GT "air cell" (currently only obtainable in creative mode) to universal fluid cells produces 2 of `<ic2:fluid_cell>.withTag({fluid: {FluidName: "air", Amount: 1000}})`.  Also, the liquid air cell is not legitimately obtainable, since the only recipe shown for it is from a "liquid air plasma cell", which has no recipe.

**Comment by JasonMcRay** [comment]
Are you sure? I remember this and with @Blood-Asp help i have found that other mod was adding this. If I remember correctly it was Computronics: https://github.com/asiekierka/Computronics/issues/205

**Comment by MauveCloud** [comment]
Correction: somehow I missed the JEI recipe for it, but the GT "air cell" is actually obtainable by putting a GT empty cell in a compressor, and the air from that can be centrifuged for nitrogen and oxygen.

However, as far as I can tell, the "liquid air cell" is still not legitimately obtainable, removing an alternate way of producing helium (which now can only be done via fusion or centrifuging endstone), and making it impossible to produce argon (needed for making naquadah alloy)

**Comment by draknyte1** [comment]
1.7.10 doesn't have air->helium. 
Unless you've got Gregtech++ and a distillation tower.

**Comment by Blood-Asp** [comment]
It does have air -> helium, but much more complex than simple destillation.

compressed air -(vacfreez)> liquid air -(cent)> noble gasses -(cent)> helium

**Comment by draknyte1** [comment]
When was that added?
I added the fractional distillation method because none other existed.. Other than end stone and plasma

**Comment by Blood-Asp** [comment]
That recipe is quite old. At last a year. But easy to miss.

**Comment by MauveCloud** [comment]
On a somewhat related note, I came across this line in the code:
https://github.com/Blood-Asp/GT5-Unofficial/blob/1.10.2/src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java#L365
which looks like it's adding a fluid extractor recipe for monazite dust to 200L helium, but I find no such recipe in JEI.  I also tried in creative mode, in case it was a hidden recipe (and used an EV-tier fluid extractor to make sure), but it still had no effect.

**Comment by Blood-Asp** [comment]
The monazit -> Helium likely does not work since Helum is a Gas but the recipes tries to get it as fluid. 
The error is already in GT5.09, likely since 5.07.xx but since no one ever saw the recipe, no one missed it.
According to wikipedia, monazit containing small amounts of helium is correct, so i fixed it in GT5.09.
