### ISSUE TITLE
[5.09.29pre] Oregen on asteroids is broken

### ISSUE THREAD

**Issue by Georggi** [Blood-Asp/GT5-Unofficial#972]
Title says everything, I have flown into new chunks after those updates and I can't find ANY ore, although configs are right. Previously with galacticgreg there were big asteroids just with gregtech ore and granite, now there are none of those.

**Comment by Blood-Asp** [comment]
Is this about galactricraft asteroids in their dimension, or are also End asteroids missing?

**Comment by Blood-Asp** [comment]
Tested, works.
