### ISSUE TITLE
[5.09.28] Confusing word choice: glowstone/naquadah "doted" monocrystals/wafers

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#976]
I'm having trouble finding a meaning of "doted" that makes sense for these items.  "doted" is a form of the verb "dote", having to do with mental decline or excessive affection, which is hard to apply to inanimate objects like the monocrystals/wafers from GregTech - see https://www.merriam-webster.com/dictionary/dote

Was this perhaps supposed to be "dotted" (having dots of different color/material interspersed), or "doped" (with impurities added to alter the properties of the substance)?

**Comment by Blood-Asp** [comment]
It should be doped. Made the error while translating from german in mind.
