### ISSUE TITLE
[1.10.2] Machine inventories sometimes revert to older states after reloading world

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#977]
A couple of times recently in my single-player world, I've gone to my oil drilling rig, sometime after having reloaded the world, and found discharged batteries in the battery buffer I'd set up for it, as well as filled cells in the output hatch, even though I'm certain I had collected these the last time I left the drilling rig (the batteries for recharging, and the cells for oil processing).

I think there was also one time when I was still in steam age that I had left an item casing mold in my steam alloy smelter and it mysteriously vanished, forcing me to make a new one, but I'm less certain about that - I might have somehow just unintentionally dropped it and let it despawn.

**Comment by Exidex** [comment]
If it is GT issues than it is probably invalid with the rewrite. Raise the issue again if the problem persist after rewrite
