### ISSUE TITLE
Data Orb and Super Buffer

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#978]
Due to the increasing complexity of manufacturing Data Orb, now Super Buffer is not available until Fusion. Perhaps it is worth replacing the Data Orb on the Data Stick in Super Buffer recipes?

**Comment by Blood-Asp** [comment]
Added an alternative recipe using 4 Datasticks.
There is also an alternative recipe for the Data Orb that can be used in HV Tier, but that is expensive as hell and meant for enable replication at that point.
