### ISSUE TITLE
Suggestion: Add Large Boiler fuel entries to NEI

### ISSUE THREAD

**Issue by JohannesGaessler** [Blood-Asp/GT5-Unofficial#979]
The NEI entries for liquid boiler fuels are very cryptic and do not represent the EU values you get from burning them in a large boiler at all.

I suggest adding a separate tab that explicitly shows how long certain fuels burn in a large boiler.

So for example the tooltip for heavy fuel would read:

Burn time:
Bronze: 38.4s
Steel: 28.8s
Titanium: 23.04s
Tungstensteel: 21.6s

If possible please also include solid fuels to make comparision easier.

**Comment by draknyte1** [comment]
They're not just large boiler fuels..
The semi fluid generator exists.

**Comment by JohannesGaessler** [comment]
I know that there is a IC2 machine that uses these fuels, but it only provides 32EU per tick which is a little annoying to use.
It's also less efficient than a large boiler.

I'd like to get information on burn times to make planning your setup easier.

**Comment by draknyte1** [comment]
I suggest adding it to the wiki.
