### ISSUE TITLE
[5.09.29pre2]A missing muffler hatch doesn't lead to an 'incomplete structure' message with the electric blast furnace.

### ISSUE THREAD

**Issue by JohannesGaessler** [Blood-Asp/GT5-Unofficial#982]
If you build an electric blast furnace but omit the muffler hatch the blast furnace doesn't give you a hint on the missing muffler hatch in the interface.
The other hatches also take on the look of the furnace.
It is not possible to actually use the electric blast furnace; Recipes will immediately stop after activation.

Similar behavior can be observed with the multi smelter.

**Comment by Pilad** [comment]
Yes, BF work fine without muffler hatch )))
