### ISSUE TITLE
Suggestion: Advanced Rocketry compatibility

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [Blood-Asp/GT5-Unofficial#989]
It seems like MauveCloud made a commit which will ensure that GT ores will generate on AR planets, but IIRC Gregtech 5.09.28 only checks for the presence of Galacticraft to decide whether to enable low gravity processing or not. It would be really cool if low gravity processing could be made to work in Advanced Rocketry space stations and dimensions, and maybe other people have suggestions to improve inter-mod compatibility.

**Comment by OvermindDL1** [comment]
Built in support, as well as an ID list would be useful...

**Comment by Blood-Asp** [comment]
Guess it is. 
Also, is Adv Rocketry finally in a usable state? Did not look at it for some time.

**Comment by bHXDgiuMa5yLHyC8** [comment]
I just visited the Moon while playing with Advanced Rocketry 1.2.5-60 and GT 5.09.32pre1 and it does not appear that any GT ores spawn there even though IC2 and libvulpes ones do, and it also appears that there are no undergound fluids (I drilled three wells with the tungstensteel oil rigs).

**Comment by draknyte1** [comment]
I don't think any support has been added for AR.. 
However you can make fluids generate underground in the config file..
