### ISSUE TITLE
Hot NaK/He Coolant Cell does not get banned

### ISSUE THREAD

**Issue by ShelfOwl** [Blood-Asp/GT5-Unofficial#99]
Put IC2 Coolant Cell into normal Nuclear Reactor will get labeled "Can not be used in Fluid Reactor ..." on tooltip, but NaK/He Coolant Cell will not.
They should forbidden in Fluid Reactor as same as IC2 Coolant Cell.

**Comment by Blood-Asp** [comment]
Fixed in 5.08.26
