### ISSUE TITLE
Suggestion: Ultra-LV machine components

### ISSUE THREAD

**Issue by Valdevon** [Blood-Asp/GT5-Unofficial#991]
Not sure if this has been suggested before, but there are a lot of times that I've wanted a slower pump/conveyor belt than LV, or times when an LV one has been completely overkill for what I'm automating (a coke oven, for example).

The recipes could be made to be cheaper than the LV ones, or, if you feel that is unbalanced (moving items should be expensive), they could be a similar cost but still slower (for niche automation)
 - sticks instead of iron rods (magnetic stick lol)
 - insulated lead cables instead of tin
 - red alloy wires instead of copper
 - for pumps, maybe copper(or wooden) fluid pipe, wooden rotor, and wooden screw

**Comment by Nex4rius** [comment]
+1 for magnetic wood

**Comment by draknyte1** [comment]
They exist in Gregtech++

**Comment by Dream-Master** [comment]
@Valdevon And we will have this mod GT++ soon in GTNH. 1.5.0.0 update.

**Comment by draknyte1** [comment]
Actually, upon quickly checking, I found that I removed ULV ones a while ago, but I'll re-add them before @Dream-Master updates to 1.5.0.0.

1/4 or 1/8 speeds of LV, would you say?

**Comment by Valdevon** [comment]
Probably 1/4, to follow the pattern of the rest of the parts

**Comment by Blood-Asp** [comment]
1/4 or 1/5 would be the pattern to be exact. LV 20sec, MV 5 sec, HV 1 sec, EV 1/5 sec, IV 1/20 sec.
So one transfer every 80 sec or every 100 sec would be the pattern.

Guess i can close this as it is taken care of by GT++
