### ISSUE TITLE
Suggestion: Purified Siftable(Gem) Ore vs. Purified Ore in Type Filter

### ISSUE THREAD

**Issue by Valdevon** [Blood-Asp/GT5-Unofficial#992]
Would be a nice addition to make automated ore processing simpler and encourage people to use gregtech's item transport system more in packs where enderio or some other piping system is cheap and available

**Comment by Blood-Asp** [comment]
Well, in theory a simple version could be build with an item detector on a sifter + shutter. Prevent item transfer past sifter if there is an item inside. So not siftabel ores can only pass when the sifter is empty and still not does accept them. 
Allowing such a function in the filter would be a big internal change and if that would be done it would also have to be done for all the other processing machines.
