### ISSUE TITLE
suggestion: add a anti-matter reactor

### ISSUE THREAD

**Issue by 9000bowser** [Blood-Asp/GT5-Unofficial#995]
I sugget to add the anti-matter reactor

This reactor could need several components to build it and put it into operation:
-Add a particle accelerator mulitblock based on fusion reactor design to produce anti-matter
-Add electromagnetic pipe for the anti-matter transport(power is required for operate (2EU/pipe/tick))
-Add a magnetic quantum upgrade for stroing the anti-matter on a quantum tank(power is required for operate(500EU/t))
-Add electromagnetic power injector for powered the electromagnetic pipe
-Add anti-matter reaction chamber multiblock based on EBF.
-This reactor is capable of providing a Max voltage
-Add a max voltage battery tier or change the ultimate battery tier to max voltage battery tier
-This reactor required a large amount of neutronium for running at a full efficiency

**Comment by Antifluxfield** [comment]
As far as I know, there's already an idea about antimatter, though it's quite different from yours: #489 .

**Comment by Dragon2488** [comment]
Who will do it? You?

**Comment by 9000bowser** [comment]
Is just an idea

**Comment by Technus** [comment]
I already work on it in my addon, but the concept is way different.
https://github.com/Technus/TecTech
https://github.com/Technus/TecTech/tree/master/src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi

As well as some other machinery

**Comment by Technus** [comment]
Also with current GT_Values for tiers + some other places in code
This:
  -This reactor is capable of providing a Max voltage
  -Add a max voltage battery tier or change the ultimate battery tier to max voltage battery tier

would cause infinite EU production per tick and instant charging of items no matter what tier.

GT has Integer_maxValue used for debug purposes.

**Comment by Blood-Asp** [comment]
Duplicate, WIP as Addon, ect. So closed for cleanup.
