### ISSUE TITLE
Crash when initializing (5.10.22)

### ISSUE THREAD

**Issue by SuperHyperPink** [Blood-Asp/GT5-Unofficial#997]
Forge: 1.10.2-12.18.3.2185
IC2: 2-2.6-188-ex110
JEI: 1.10.2-3.14.7.416
CodeChickenLib: 1.10.2-2.5.7.241-universal
Gregtech: 5.10.22

Everything in this setup works normally without gregtech, however when I attempt to load gregtech into my load order, it crashes upon initializing. 

[crash-2017-03-31_08.52.41-client.txt](https://github.com/Blood-Asp/GT5-Unofficial/files/886255/crash-2017-03-31_08.52.41-client.txt)

**Comment by Dragon2488** [comment]
You are using outdated gt version. Grab new one in build/libs
