### ISSUE TITLE
Modular Armor - Always "Too Heavy"

### ISSUE THREAD

**Issue by Drawfox** [Blood-Asp/GT5-Unofficial#999]
Modular armor always gets "Too Heavy", don't matter how much or which plates you use.
Even after removing all the plates, the message and slowdown persists.

**Comment by Antifluxfield** [comment]
Seems that for some of the effects provided by the armor, they can't be canceled on time. Just like what I found: once you get the auto-climbing function provided by the piston, the function will always sustain even if you remove the piston or the entire armor - although the jump-boost effect can be canceled immediately.

**Comment by Blood-Asp** [comment]
Uploaded a pre build of .30 on onedrive with some modular armor fixes. Still some things bugged i know of, but should already be better than before.
